### ISSUE TITLE
Delta numbers on the graphs are confusing

### ISSUE THREAD

**Issue by sudevschiz** [covid19india/covid19india.github.io#100]
**Describe the bug**
Delta values on the graph are the incremental from the previous day. 
When the site is loaded, it shows the incremental change from day before yesterday. That would be confusing for the user.
![image](https://user-images.githubusercontent.com/4298868/77538766-9b476380-6ee3-11ea-8daa-cecd547d4693.png)

**To Reproduce**
Current website

**Expected behavior**
Not delta numbers shown on the graph 

![image](https://user-images.githubusercontent.com/4298868/77539289-7a334280-6ee4-11ea-8d2e-e0959d932c83.png)

**Comment by shahrk** [comment]
Doesn't seem like a bug to me. It's showing latest added cases.

**Comment by Rajanpandey** [comment]
Yes, it doesn't seem like a bug. It's correct, isn't it? @sudevschiz

**Comment by andante-9** [comment]
From a UX perspective, it is a problem. The user is accustomed to seeing today's data when they browse through the map and table. Upon reaching the graphs, they are still in the mindframe that they are seeing today's deltas. The date mentioned in the top left does nothing to alert the user that it's yesterday's date. (People aren't even aware what the date is anymore during the lockdown.)
Two possible solutions:
1. Add today's deltas to the graphs and mention "in progress today" under "Spread Trends"
2. Keep the deltas as it is now (reporting till d-1 days) and mention "(yesterday)" next to/under the date shown in the graph. Test that "yesterday" disappears when you hover over another date in the graph

**Comment by jeremyphilemon** [comment]
I agree with @andante-9, it does seem a little too confusing. If anyone's willing to pick this issue up, I'd suggest to go with:

> Keep the deltas as it is now (reporting till d-1 days) and mention "(yesterday)" next to/under the date shown in the graph. Test that "yesterday" disappears when you hover over another date in the graph

**Comment by vedadeepta** [comment]
implemented possible fix - forgot to notify before starting work :(
