### ISSUE TITLE
Footer Enhancement

### ISSUE THREAD

**Issue by HarshSBhatt** [covid19india/covid19india.github.io#1001]
New footer requirements with more elegant crisp design covering social media as well

**Comment by parthbhide** [comment]
I would like to contribute to this .

**Comment by sudevschiz** [comment]
@HarshSBhatt Could you provide your screenshots and ideas here as a comment too.

Assigning to you anyways.

**Comment by sudevschiz** [comment]
Let's just keep the footer as-is, unless there is an enhancement in functionality (and not in design)
