### ISSUE TITLE
Mode of transmission terminology

### ISSUE THREAD

**Issue by swankyshahir** [covid19india/covid19india.github.io#1002]
**Is your feature request related to a problem? Please describe.**
I cant make out what TBD stands for in mode of transmission column

**Describe the solution you'd like**
To give the full forms of any such abbreviations used

**Describe alternatives you've considered**
Searched the internet of TBD in relation to COVID-19 transmission but it was of no help

**Additional context**

**Comment by Mayur1496** [comment]
I think that stands for:  **To Be Declared**
