### ISSUE TITLE
Responsiveness bug

### ISSUE THREAD

**Issue by nayaksanjay99** [covid19india/covid19india.github.io#1006]
On mobile platforms with screen widths 320px and 375px, there is an extra space in the extreme right.( If you can't see the space, just try zooming out by pinching-in on the screen). The screenshot for 375 px is attached below.

![Screenshot_2020-04-12-18-58-30-87](https://user-images.githubusercontent.com/41791460/79070013-4a5fa980-7cf0-11ea-8d31-2a791056618c.jpg)

# Bug
The reason/bug is because of the block (number of tested patients), the screenshot of which is attached below.

![tested2](https://user-images.githubusercontent.com/41791460/79070150-6c0d6080-7cf1-11ea-81c7-7c2292f75cc7.png)

**Comment by guptadev** [comment]
@nayaksanjay99  can you please let me know in which mobile phone you are checking?
can you please also let me know the height and zooming % so it would be easy to identify the responsive issue.
Thanks,
Dev.

**Comment by nayaksanjay99** [comment]
Device- Realme 3 Pro and Redmi Note 4
U can also reproduce this issue by opening the site in responsive mode using chrome-dev-tools.

**Comment by salus-sage** [comment]
This bug is visible, when you see the figures for whole india which has more digits compared to when you click on any states.

**Comment by Binu42** [comment]
@nayaksanjay99 this bug is fixed in PR #957

**Comment by nayaksanjay99** [comment]
Cool 👍

**Comment by jeremyphilemon** [comment]
Patched by #1170
