### ISSUE TITLE
Statewise heat-map based on Population density

### ISSUE THREAD

**Issue by ikshitiz** [covid19india/covid19india.github.io#1007]
**Is your feature request related to a problem? Please describe.**

State with a large population will have more cases compared to one with less population. I have seen multiple websites (Other countries) using the number of infected persons per million population criteria to plot heatmap. 

This will help in visualizing district-wide hotspots. 

If You compare UP, Maharastra and Kerala. the ratio of infected Population/total Population

- UP: 0.22 cases per million population
- Kerala: 1.12 cases per million population
- Delhi: 6.38 cases per million population
- Maharastra: 1.69 cases per million population

So, Delhi is more affected than Maharashtra but In count. Maharastra is most affected. 

We can go granular to find more hotspots (District or city level). This will help in understanding the affected cities in a more logical way.

**Comment by JunaidBabu** [comment]
Can be an item in Deep-Dive section

**Comment by nishcthulhu** [comment]
Would be happy to work on this. Would need a new API to get the json created for this @JunaidBabu

**Comment by nishcthulhu** [comment]
Is there any branch where i can make temporary commits for this feature?
