### ISSUE TITLE
District-wise number of patients is not showing,instead it is made 'unknown'.

### ISSUE THREAD

**Issue by Godspeed007** [covid19india/covid19india.github.io#1009]
I opened the website to check current number of patients in each district of Uttar Pradesh.But their wasn't any district-wise tally,but an 'unknown' tag.Also,not in U.P but in each of the state
Hope this gets rectified.
Here is the screenshot of the same.
![Screenshot (244)](https://user-images.githubusercontent.com/50884193/79070730-4a15dd00-7cf5-11ea-9b3f-b711e9ec5e44.png)

**Comment by gaurav7118** [comment]
Hi @Godspeed007  if you will open website in smartphone's chrome browser or incognito mode in windows chrome browser then it will work fine.

**Comment by gaurav7118** [comment]
Try to clear cache. After clearing cache everything will work fine

**Comment by Godspeed007** [comment]
Think issue is solved.Check without incognito.

**Comment by gaurav7118** [comment]
Actually it was not the issue. It was just cache problem. I also encountered the problem but after clearing the cache issue was solved
