### ISSUE TITLE
Page won't load when directly entering the page URL instead of main URL

### ISSUE THREAD

**Issue by shahrk** [covid19india/covid19india.github.io#101]
**Describe the bug**
If you enter the URL of a sub-page eg: [clusters page](https://www.covid19india.org/clusters), it won't load.

**To Reproduce**
1. Go to 'https://www.covid19india.org/clusters'
2. The page won't load

**Expected behavior**
The expected page should load

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: chrome, firefox

**Comment by shuklaayush** [comment]
It is loading for me. Can you check again and confirm?

**Comment by rito-rapido** [comment]
Opens for me as well.

**Comment by shahrk** [comment]
Yeah it is working now for me I'm not sure why it wasn't working earlier, I had checked multiple times.
