### ISSUE TITLE
Make select options in demographics cleaner

### ISSUE THREAD

**Issue by nayakrahul** [covid19india/covid19india.github.io#1010]
The select options component is compact. It should be more clean and the font should be same as base font (Archia). It looks bad in mobile devices. It should be responsive.

**Comment by tannakartikey** [comment]
@nayakrahul can you add some screenshots here to explain your case?

**Comment by nayakrahul** [comment]
![Screenshot (15)](https://user-images.githubusercontent.com/11428805/79106609-73d01200-7d90-11ea-8459-e94e0ebd1400.png)

Here I have made the select a bit cleaner than it was before and also used "archia" font.

**Comment by nayakrahul** [comment]
![Screenshot (17)](https://user-images.githubusercontent.com/11428805/79106693-9cf0a280-7d90-11ea-9b3a-914a1059a444.png)
![Screenshot (14)](https://user-images.githubusercontent.com/11428805/79106700-a11cc000-7d90-11ea-8500-772d91511182.png)
Using the above css only, I made it look better in mobile devices. As you can see in the first screeenshot, it is looking odd.

**Comment by nayakrahul** [comment]
I have raised a pull request https://github.com/covid19india/covid19india-react/pull/1012 for this. You can check it.
