### ISSUE TITLE
Wrong recovered trends

### ISSUE THREAD

**Issue by dhanendraverma** [covid19india/covid19india.github.io#1014]
For **All states** the Deceased and Recovered trends have been interchanged whereas it looks fine in number charts

<img width="1141" alt="Screenshot 2020-04-12 at 10 53 40 PM" src="https://user-images.githubusercontent.com/46896989/79075505-e7cad580-7d10-11ea-9124-420229b7d031.png">

**Comment by sudevschiz** [comment]
Thanks for reporting promptly. This has been fixed with https://github.com/covid19india/covid19india-react/commit/a0068f0e410fe5aa9cc0e733cc0b71a42965d64a
