### ISSUE TITLE
Graph of recovered and confirmed cases interchanged for states

### ISSUE THREAD

**Issue by Naitikagrawal** [covid19india/covid19india.github.io#1015]
**Describe the bug**
Graph of recovered and confirmed cases seems interchanged for states. 

**To Reproduce**

1. Go to graphs
2. Click on say chattisgarh
3. There it shows 0 recovered and 9 deceased, however it's other way round.

**Comment by sudevschiz** [comment]
Thanks for reporting promptly. This has been fixed with https://github.com/covid19india/covid19india-react/commit/a0068f0e410fe5aa9cc0e733cc0b71a42965d64a
