### ISSUE TITLE
Last hovered state count showing even after moving out of India map.

### ISSUE THREAD

**Issue by abbhhiisseek** [covid19india/covid19india.github.io#1017]
**Describe the bug**
Count not updated even after hovering out of a state.

**To Reproduce**
On loading page, initially the India count is shown.Now hover over any state. Then, move cursor out of the India map.

**Expected behavior**
After moving out of map,India Count should be visible. But last hovered state count is still showing.

**Comment by dhrubesh** [comment]
Mind if I pick this up?

**Comment by abbhhiisseek** [comment]
@dhrubesh please do

**Comment by dhrubesh** [comment]
@abbhhiisseek please assign it to me

**Comment by abbhhiisseek** [comment]
Seems like it can be assigned once moderators change status to available

**Comment by bee-rickey** [comment]
We are looking at a possible better interaction on the maps. Since the current behavior isn't a bug, but not intuitive enough either! Wil keep this open and not making it available until there's a better interaction :)

**Comment by tannakartikey** [comment]
Possible relation with https://github.com/covid19india/covid19india-react/issues/1030

**Comment by shuklaayush** [comment]
Instead of resetting to India count on mouse exit, we've added an option to reset on clicking outside the map.
