### ISSUE TITLE
Push notification for new cases, with a state level filter

### ISSUE THREAD

**Issue by ayusun** [covid19india/covid19india.github.io#102]
**Is your feature request related to a problem? Please describe.**
Rather than manually looking at dashboard. We can have web app push notification for new cases

**Describe the solution you'd like**
A service worker listening to patients. When there is a change in response from the server, then check if the user should be notified (based on the local storage). If yes, then notify

**Describe alternatives you've considered**
None

**Additional context**

**Comment by aekanshd** [comment]
#178 Same intention. Rather than push notifications (since it's not a PWA yet), a simple ajax call would suffice.

**Comment by codeslane** [comment]
Still Open?

**Comment by jeremyphilemon** [comment]
We've decided adding support for push notifications would instill stress to people, if in any other app it definitely seems reasonable to add push notifications, however, for a tracker like this it wouldn't be much productive.

Feel free to open this issue later if you think otherwise :)
