### ISSUE TITLE
Add a column for # testings done in eash state

### ISSUE THREAD

**Issue by kaustubh77** [covid19india/covid19india.github.io#1025]
It will be useful to compare state wise number of testings done easily. Also since your website is so much popular now, I am sure many authoritative people might be keeping themselves updated using your website. Adding this column will kind of be like pushing them to work harder. Also adding a column showing the number of tests done per million people of each state will be helpful

**Comment by tannakartikey** [comment]
duplicate of https://github.com/covid19india/covid19india-react/issues/945
