### ISSUE TITLE
Chhattisgarh not showing update in recovery list

### ISSUE THREAD

**Issue by ravigaggad** [covid19india/covid19india.github.io#1026]
![IMG_20200413_104944](https://user-images.githubusercontent.com/63439607/79094300-b2f06a00-7d74-11ea-90d5-3b67337235bd.JPG)
![IMG_20200413_105043](https://user-images.githubusercontent.com/63439607/79094304-b552c400-7d74-11ea-976c-0f160a5fb317.JPG)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by sudevschiz** [comment]
This is probably because a recovery reported in the previous day was added today. For this case, delta value shouldn't be shown in table. Not a bug.
