### ISSUE TITLE
After hovering a state in India map, we can't get back all states info again using the map div itself

### ISSUE THREAD

**Issue by nayakrahul** [covid19india/covid19india.github.io#1030]
It's annoying to use the dropdown to again get the all states info in the map. Can' t we use the map itself to again get the all states info.

We can use the area where there is no states in the map div. We can use click or tap (not hover) on empty area to again get the all states info.

Or we can create a button on top right for that.

**Comment by jaibatrik** [comment]
In mobile, just scrolling the page changes the state dropdown. It's terrible usability.

**Comment by shuklaayush** [comment]
@jaibatrik So we've fixed that. It was happening because of touch events being triggered on the table. @nayakrahul We're working on that.
