### ISSUE TITLE
In essentials coloumn while searching for states Arunachal pradesh is mising

### ISSUE THREAD

**Issue by kartheeki-kongara** [covid19india/covid19india.github.io#1031]
**Describe the bug**
When we traverse to essentials in covid19 tracker and search for states in 'choose state' checkbox Arunachal Pradesh is missing. 

**To Reproduce**

1. Go to 'https://www.covid19india.org/essentials''.
2. Click on 'Choose state' check box. 
3. In drop down box 'Arunachal Pradesh is missing'.

**Expected behavior**
In drop down box Arunchal pradesh state should be added.

**Desktop (please complete the following information):**

- OS: Windows
- Browser - Chrome,UC browser
- Version Windows 10

**Comment by vinaypathak07** [comment]
Hi kartheeki-kongara:
The state is missing in the json we are fetching from the api.

**Comment by strikertanmay** [comment]
I checked there is no data available for Arunachal Pradesh in (https://api.covid19india.org/resources/resources.json), that's why it is missing in drop down box.

**Comment by nikita-11** [comment]
As soon as we submit any entry for this particular state in our backend sheet. The data will be reflected.

**Comment by nikita-11** [comment]
@kartheeki-kongara @jeremyphilemon You can close this one. Data team is working on aggregating data from seven sisters. It will reflect as soon as added.
