### ISSUE TITLE
Add test per million 

### ISSUE THREAD

**Issue by kp666** [covid19india/covid19india.github.io#1032]
**Is your feature request related to a problem? Please describe.**
Test per million is a clear indicator of how effective testing happens at the ground level.

**Describe the solution you'd like**
Add test per million header(preferably PPM)
**Describe alternatives you've considered**
Data is not available to do PPM at this point.
**Additional context**
![image](https://user-images.githubusercontent.com/165359/79106660-8c402c80-7d90-11ea-970a-3a52bff2814b.png)

**Comment by jeremyphilemon** [comment]
Closing in favor of #1496
