### ISSUE TITLE
Delhi is not available for hover in country map

### ISSUE THREAD

**Issue by Shaleengovil25** [covid19india/covid19india.github.io#104]
**Describe the bug**
Capital Delhi cases must be available in the hover country Map too, But it can only be seen in Table. 

**Expected behavior**
Delhi should me availible for hover.

**Desktop (please complete the following information):**
 - OS: win 8
 - Browser [chrome ]
 - Version [80]

**Comment by gs-nkumar** [comment]
<img width="847" alt="Resize_and_crop_photos__images_and_pictures_online" src="https://user-images.githubusercontent.com/17634822/77544373-eefb8200-6ece-11ea-9276-4a230ec181c5.png">
This is not a bug. you need to point it to exact co-ordinates.

**Comment by shuklaayush** [comment]
Kindly close.

**Comment by Shaleengovil25** [comment]
I overlooked it due to the same color density.
Thanks for telling.
sorry for your time.
