### ISSUE TITLE
Add info icon and tooltip next to statename in table IF a note needs to be shown

### ISSUE THREAD

**Issue by sudevschiz** [covid19india/covid19india.github.io#1041]
**Is your feature request related to a problem? Please describe.**
When a remark needs to be made regarding a state's number in the main table, it's currently added to the "About (FAQ)" page. Instead of that, it should be a ℹ️ icon, which on tap/hover pops up a tool-tip.

**Describe the solution you'd like**
1. Fetch the `statenotes` field now available in the `statewise` object for each state at [https://api.covid19india.org/data.json ](https://api.covid19india.org/data.json)
<img width="638" alt="image" src="https://user-images.githubusercontent.com/4298868/79133856-afe29180-7de7-11ea-9796-315944a5096f.png">

2. Show an info icon ℹ️ next to the statenames IF there is a valid non-empty string for `statenotes`
3. Show the text as tooltip

**Describe alternatives you've considered**
Currently we show the info message in FAQ for WB.
This is not very useful, now that we have lot more caveats to display.

**Additional context**
1. Data volunteers can update the Statewise sheet to update the notes.
2. Maybe an empty string check might be useful, to avoid just a space in the `statenotes` to cause a ℹ️ to show up.

**Comment by nayakrahul** [comment]
I can take this

**Comment by sudevschiz** [comment]
@nayakrahul Thanks for working on this. Can you make few changes : 
1. It's quite tough to tap on the info icon on phones because that could cause district drop-down. Do you have any better ideas to improve UX? Just make the info icon larger to tap?
2. Possible to make the dialog bubble a bit transparent so that other numbers are not hidden fully?
3. There are some leading white-spaces. Possible to remove those?
