### ISSUE TITLE
Colour coding not working

### ISSUE THREAD

**Issue by nirmalby** [covid19india/covid19india.github.io#1045]
Colour coding given for severity for state is not getting updated with scale change

1. Go to  maps -> kerala
2. Kerala should be in severity scale 1 but shows severity level 2

**Expected behavior**
Kerala to be on least severity 

**Screenshots**
Added

**Desktop (please complete the following information):**

- OS:  windows
- Browser chrome
- Version latest

**Smartphone (please complete the following information):**

- Device: iphone se
- OS: ios 13
- Browser chrome
- Version latest

**Additional context**
![AF39F330-E026-43B0-8C8E-51A94DEE303A](https://user-images.githubusercontent.com/63604605/79139998-e9f66800-7dd4-11ea-975e-e6a91b6971b2.png)

**Comment by shuklaayush** [comment]
Should be fixed in #865

**Comment by shuklaayush** [comment]
Fixed in #1133
