### ISSUE TITLE
Please use datepicker for the dates in demographics

### ISSUE THREAD

**Issue by knayan1** [covid19india/covid19india.github.io#1046]
As the dates are going ahead, we're seeing a long list of dates, that is bit tough to select older dates, specially in mobile.

Please add datepicker/calendar for this.
https://www.covid19india.org/demographics

**Comment by avneeshroks** [comment]
Please assign this to me! PR : https://github.com/covid19india/covid19india-react/pull/1132

**Comment by sudevschiz** [comment]
Will let @jeremyphilemon weigh in.
