### ISSUE TITLE
Please add current status info in demographics

### ISSUE THREAD

**Issue by knayan1** [covid19india/covid19india.github.io#1047]
Please add last status change date and current status (death/recovered/hospitalized) to the demographics of each patient in the popup window.

If possible, please change the color codes too while displayin.

![image](https://user-images.githubusercontent.com/6613637/79141398-58d4c080-7dd7-11ea-8113-70549b61f3cb.png)

**Comment by sudevschiz** [comment]
We are not able to map the exact status changed date for the patients, now that the number of cases are too high. This is not feasible from a data perspective.
