### ISSUE TITLE
Improve the UI of dropdown menu on demographics  page

### ISSUE THREAD

**Issue by strikertanmay** [covid19india/covid19india.github.io#1049]
Attach pics of improved UI dropdown menu-
![rsz_1screenshot_from_2020-04-13_23-10-30](https://user-images.githubusercontent.com/32292953/79144998-81f84f80-7ddd-11ea-99d8-972065b0eb0d.png)

**Comment by strikertanmay** [comment]
https://covid19india-r-git-fork-strikertanmay-strikertanmay-fx-d-f63272.covid19india.now.sh/demographics

**Comment by pooja3** [comment]
Can u assign this bug to me? I am willing to work on this.

**Comment by sudevschiz** [comment]
What are the improvements that you made? Thanks for the PR, however, please wait for the issue to the assigned to you so that we can keep track and follow up.

**Comment by jeremyphilemon** [comment]
Patched.
