### ISSUE TITLE
Add support in cluster to filter data based on state and city

### ISSUE THREAD

**Issue by anuragjain** [covid19india/covid19india.github.io#105]
**Is your feature request related to a problem? Please describe.**
Its difficult to analyze cluster data as in general you want to know the trend in a city or state and see the cluster effect in that region, however right now the only way is to navigate the view which is not ideal

**Describe the solution you'd like**
Put a filter of state and city right below the patient filter

**Describe alternatives you've considered**
Was thinking of click based filter, but that is less ideal

**Comment by rito-rapido** [comment]
![image](https://user-images.githubusercontent.com/61823881/77549391-c7f47e80-6ed5-11ea-9e79-77e94680c907.png)


Do we not already have this, or am I missing something ?

**Comment by anuragjain** [comment]
There is no feature to search the state or city like we have for patient number.
Finding a city across so many points in the graph is the only way to see it which is not practical given hundreds of cities are there.

**Comment by rito-rapido** [comment]
@anuragjain Makes sense. Will start working on this.

**Comment by JunaidBabu** [comment]
Clusters is a different project https://github.com/someshkar/covid19india-cluster

Closing this
