### ISSUE TITLE
Deep-dive Daily cases for India graph is having wrong calculation.

### ISSUE THREAD

**Issue by bee-rickey** [covid19india/covid19india.github.io#1056]
The graph shows active data as: (today's total number of cases - today's recovery - today's deceased count) 
It should be: today's total number of cases.

Eg:
**For 13th April: there were 1242 new cases, 107 recoveries and 27 deaths.**
<img width="583" alt="image" src="https://user-images.githubusercontent.com/63364562/79159740-3d2ce280-7df6-11ea-8af7-82bd103ddae4.png">

The graph shows:
**(1242 - 107 - 27) as active:**
<img width="472" alt="image" src="https://user-images.githubusercontent.com/63364562/79159836-6e0d1780-7df6-11ea-9dee-5539f1f456d8.png">

This is wrong as the cases on 13th April are 1242. Not 1242 - 107 - 27.

Also, _the nomenclature for the new cases shouldn't be Active. It should be "New cases"._ Active is a misleading term since the number of active cases as of 13th is way higher than 1242.

**Comment by Binu42** [comment]
i agree with you @bee-rickey. it's now fixed at #1057 to help @jeremyphilemon @s-naveen

**Comment by Binu42** [comment]
@bee-rickey currently bar plot is showing daily cases from 1 march to today date. which is making plot very clumsy and thin and this plot is going to be thin dailywise. i have raised PR #1061  to solve this issue by limiting the number of days to recent 28 days and i think that nobody will want to know daily cases before 28 days. Have a look...
