### ISSUE TITLE
Create a total tested vs positive graph

### ISSUE THREAD

**Issue by arushibhat** [covid19india/covid19india.github.io#106]
**Is your feature request related to a problem? Please describe.**
feature request

**Describe the solution you'd like**
We can add one graph for total people being tested vs total positive cases. 

**Describe alternatives you've considered**
The data can be extracted from https://docs.google.com/spreadsheets/d/e/2PACX-1vSc_2y5N0I67wDU38DjDh35IZSIS30rQf7_NYZhtYYGU1jJYT6_kDx4YpF-qw0LSlGsBYP8pqM_a1Pd/pubhtml# >> tab "Tested_Numbers_ICMR_Data".
It'll help understand the conversion rate.

Thoughts...

**Comment by Shivam60** [comment]
hey i am interested to do this. What kind of a graph are we looking for ?

**Comment by anuragjain** [comment]
We can have two graphs, one showing tested and positive lines in the same graph.
The other could be conversion rate graph showcasing percentage. In the long run, the conversion percentage should decrease and that is the trend to be analyzed.
Thoughts?

**Comment by Shivam60** [comment]
yeah makes sense, quick question we are planning on getting the data from https://docs.google.com/spreadsheets/d/e/2PACX-1vSc_2y5N0I67wDU38DjDh35IZSIS30rQf7_NYZhtYYGU1jJYT6_kDx4YpF-qw0LSlGsBYP8pqM_a1Pd/pubhtml# right

https://api.covid19india.org/data.json
i guess this is it `	"tested": [
		{
			"source": "Press_Release_ICMR_13March2020.pdf",
			"totalindividualstested": "5900",
			"totalpositivecases": "78",
			"totalsamplestested": "6500",
			"updatetimestamp": "13/3/2020 00:00"
		},
		{`

**Comment by Shivam60** [comment]
and where are we planning to show this graph ?

**Comment by arushibhat** [comment]
Thanks shivam.
we can show it on the first page alongside the graphs for new cases. 
About the source, seems the legit one from DB.
But I am not sure how we are extracting that. the numbers are not adding perfectly. 
if someone can comment.

**Comment by anuragjain** [comment]
There is no api right now, need to create a utility to convert sheet to json and then the file can be fetched via api.
Also for placement, I was thinking of creating a new page and add it to the nav bar as the current page already has too much information.

**Comment by arushibhat** [comment]
Yeah.. we can collect all additional charts and put them under one tab..
A suggestion we can keep country wise stats and statewise/district wise
stats as two tabs.

**Comment by salmandaw** [comment]
This is definitely a must have, this metric can be used to compare ourselves to others in a more accurate way rather than cases per million since others are testing more and we aren't as much . Positive / 1000 tests would definitely be able to give the public some much needed clarity

**Comment by jeremyphilemon** [comment]
I understand that this is a metric we must have. Once we get hold of reliable data, it'll be on the frontpage. Closing this since we currently don't have any source that gives us reliable numbers.

Feel free to open this issue again once you find a reliable source, we'll be happy to have it displayed on the frontpage since it'll be an important number to look up to in our ongoing fight with the pandemic.
