### ISSUE TITLE
Normalize plots with origin on 1st, 10th or 100th case, in All States at Deep Dive.

### ISSUE THREAD

**Issue by vitorgomateus** [covid19india/covid19india.github.io#1060]
Normalize plots with origin on 1st, 10th or 100th case, in All States at Deep Dive

**Is your feature request related to a problem? Please describe.**
No.

I would like to compare how each state (and maybe even cities, maybe for later) deals and progresses after the the 10th case. Usually using the 100th case would be more significant, but some the ones that have crossed that line are still less then half.

**Describe the solution you'd like**
I want to have an option or a separate widget to the "STATES - TOTAL CASES" in DEEP DIVE, where each line is normalized to it's 1st, 10th or 100th case, and therefore compare at which speed the number of cases evolved between states. Usually using the 100th case would be more significant, but the number of states that have crossed that line are still less then half.

**Describe alternatives you've considered**
I considered having it in the main page, but it's complex enough already.

**Additional context**
1) I would like to add that there's a limit of the 10 states with most current confirmed cases, in the aforementioned widget, and I don't understand why. I found the line of code that makes this and it seems one could just erase it.
2) It would also be convenient if clicking on a widget could hide the remaining ones and make it fill the page. Mostly for the most complex ones like the "STATES - TOTAL CASES". I can create a separate issue if it is required.

**Comment by sudevschiz** [comment]
Thanks for the detailed enhancement request. This sounds good! Marking it available.

**Comment by nishcthulhu** [comment]
On it

**Comment by vitorgomateus** [comment]
> On it

I saw you commited this feature, but I don't understand it.
I read your code and it doesn't make sense to me, I have the feeling you didn't understand my idea.
I wrote some code, and tried to clone the project but I don't have the resources to run it. I want for the beggining of each data curve to be matched so we can see how each of them grows differently.

This is what I was thinking
1. have all data combined and `sortedMap` generated as it is done in allStates.js
2. iterate through all the data of each state and make a new dataset `normedStatesData` where only points >=100 go to (states with less than 100 cases would not feature in this dataset) 
```javascript
// iterate through the sortedMap
  const longestStateData = 0;
  sortedMap.forEach((data, key) => {
    const normedData = [];
    statesData.get(key).forEach((value, i) => {
      // * I'm iterating through statesData.get(key), 
      // * but it seems that doing it with data would provide the same effect
      // iterate through each point of the data
      // copy only >=100
      // The reference to the dates will be lost but that's the idea, 
      // as long as the progressions throughout the days is maintained.
      if( value >= 100 ){
        // an improvement would be to parametarize the 100 for 1,10 or 100, and maybe 1000 if it makes sense
        normedData.push(value);
      }
    });
    // note down the length of the data of the state with most data point
    // to later generate X axis
    if(normedData.length > longestStateData){
      longestStateData = normedData.length;
    }
    // push the data of the state into the new dataset
    normedStatesData.set( key, normedData );
  });
``` 
3. make a new array of labels for the X axis `normedLabels` with ["day 1", "day 2", etc...] using the length of the data for the state with most days after above step
```javascript
// making new X axis
  for (let i = 1; i <= longestStateData; i++) {
     normedDates.push("day "+i);
  }
```
4. two possibilities:
 a. make a toggle button to switch between the two datasets and the two label arrays (incorporrated into **allcharts.js**).
 or
 b. feed the `normedStatesData` and the  `normedLabels` to **growthtrendchart.js**

What do you think?

**Comment by nishcthulhu** [comment]
I hadn't committed it yet... Still building it out... But thanks for your suggestions maybe we can work on it together

**Comment by vitorgomateus** [comment]
> Still building it out...

I saw the Growth Trend Chart and assumed it was related with this.
 Isn't this the [commit](https://github.com/covid19india/covid19india-react/commit/f6ca65a89fc76c56f109bc6e55099b2c3a3e727a)?

Also yes, I haven't used React in a long time, but I'll help as I can :)
