### ISSUE TITLE
Stats data and graph data is mismatched

### ISSUE THREAD

**Issue by sarfarazit08** [covid19india/covid19india.github.io#1063]
![IMG_20200414_072437](https://user-images.githubusercontent.com/12494845/79177917-80507b00-7e21-11ea-9b1b-d1beba01b417.jpg)
**Describe the bug**

Stats data and graph data is mismatched.

**Comment by sarfarazit08** [comment]
![IMG_20200414_165351](https://user-images.githubusercontent.com/12494845/79219954-caad1880-7e70-11ea-92be-06b6277d2087.jpg)
This time the issue seems to be with confirmed and recovered cases.

**Comment by srip1** [comment]
i would like to work on this issue if possible please assigned to me.

**Comment by jeremyphilemon** [comment]
This seems to have been patched, thanks for raising the issue!
