### ISSUE TITLE
Corrections needed in Cases from Nagpur and Yavatmal - Maharashtra

### ISSUE THREAD

**Issue by dinesh0612** [covid19india/covid19india.github.io#1064]
In hitavada epaper - Nagpur cases showing are 44 but in website it is showing as 28

same in yavatmal case it is 9 but it's showing 4 

Here giving link for reference
https://www.ehitavada.com/index.php?edition=VLpage&date=2020-04-14&page=1

**Comment by dinesh0612** [comment]
Nagpur cases on dated 11-04-2020 are not added - 17

**Comment by sudevschiz** [comment]
Numbers are matched as per the MH state bulletin.
