### ISSUE TITLE
Fixed SPREAD TRENDS Graph ie position fixed Scroll Property

### ISSUE THREAD

**Issue by sanjeev1379** [covid19india/covid19india.github.io#1065]
**Is your feature request related to a problem? Please describe.**
Hi friends, when we see maharashtra cases on hover to maharashtra you are changing graph cases according to state wise but we are not able to see graph properly. because graph is too below according to state list.

**Describe the solution you'd like**
 Can, we do ne thing make this graph as fixed ie(position: fixed) and when we hover the state list and scroll that time automatically scroll graph according to state wise 

**Describe alternatives you've considered**
or we can do one thing also on click we can give one popup to show all details of particular state.

**Additional context**
Really this is suer website. design and functionality wise.

**Comment by sudevschiz** [comment]
Yes, we are discussing regarding this UX issue. Thanks for your suggestions.

**Comment by shuklaayush** [comment]
Seems to be fixed by the anchors
