### ISSUE TITLE
Access the dataset as csv

### ISSUE THREAD

**Issue by rahulnyk** [covid19india/covid19india.github.io#1066]
**Describe the bug**
Till April 13th the dataset was accessible programmatically as 
``` R 
URL <- 'https://docs.google.com/spreadsheets/d/e/2PACX-1vSc_2y5N0I67wDU38DjDh35IZSIS30rQf7_NYZhtYYGU1jJYT6_kDx4YpF-qw0LSlGsBYP8pqM_a1Pd/pub?output=csv'

data <- read_csv(URL)
```
Data is no longer accessible. 
Is there any way I can read the data programmatically?

**I know this is probably not the right place** to raise this issue, but I can't find any info about the data hosts where I can ask for help. It would be great if the data set was hosted on a Github repository similar to John Hopkins University's repo of the world Data. 

I can volunteer to contribute to host and manage the dataset repo, but doesn't seem to find a way to do that.. the telegram channel is more like a message board it seems.

**Comment by sudevschiz** [comment]
All the data is available through APIs. 
Please check out https://api.covid19india.org/

And this is probably what you are looking for :

```
library(jsonlite)
url <- "https://api.covid19india.org/raw_data.json"
json <- fromJSON(txt=url)
raw <- json$raw_data
View(raw)
```
Please do comment if you need any more information.

**Comment by rahulnyk** [comment]
Thanks a lot!

I have used the data to create a small dashboard shared open source. 
https://impactech.github.io/COVID19_India/
