### ISSUE TITLE
Graph too much Dynamic on the screen

### ISSUE THREAD

**Issue by sarangrakhecha** [covid19india/covid19india.github.io#1069]
**Suggestion for better USER INTERACTION**

**Is your feature request related to a problem? Please describe.**
The graph is too much dynamic for the entire screen, depending on where the cursor is. Problem is, the graph changes on hovering and not on clicking, hence it keeps on changing often. 

**Describe the solution you'd like**
It would be better if the graph does not change on hovering over the states on the left, and should only change on clicking on the map(right). The dropdown option is also available if needed, which is good. 

**Best Case**
The graph change should be done only by clicking on the map and by selection on the drop down and nothing else. The states on the left should only list the data(like it's showing now), and should not change the graph. The red and green for individual cities of daily growing cases should be the only extra feature for cities list.

**Comment by shuklaayush** [comment]
Yeah, I agree. The UX is not the best right now. Can you repost your suggestions on #1017? It's easier for us to track. Closing this
