### ISSUE TITLE
Padding issue in Statistics by State

### ISSUE THREAD

**Issue by arshakanjum** [covid19india/covid19india.github.io#107]
**Describe the bug**
The padding below Statistics by state seems too less

**To Reproduce**
1. Go to covid19india.org

**Expected behavior**
The padding should be same as below India Covid-19 Tracker

**Screenshots**
![image](https://user-images.githubusercontent.com/29006503/77552195-3d158300-6ed9-11ea-9f51-06a75170c13f.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome, Opera

**Comment by SauravKhare** [comment]
This is not even a bug, and look's like already been fixed. Not having the padding issue as you mentioned in any browser not even in responsive layouts.

**Comment by sudevschiz** [comment]
Can't reproduce. @arshakanjum reopen if you face the issue again.
