### ISSUE TITLE
City wise data for newcases, recovered and deceased

### ISSUE THREAD

**Issue by yuvrajsingh79** [covid19india/covid19india.github.io#1071]
**A feature request related to a city data.**
A feature to view the data of city covering new cases, recovered & deceased.
Currently it shows only for new cases in each city.

**Describe the solution you'd like**
I would be using the same pattern in which new cases are being displayed.

**Comment by jeremyphilemon** [comment]
Closing cause duplicate of #596 (also relevant with discussions)
