### ISSUE TITLE
Gujarat state recovery mismatch between state government source and covid19

### ISSUE THREAD

**Issue by DhiralKaniya** [covid19india/covid19india.github.io#1072]
**Describe the bug**
There is a recovery mismatch between gujarat state government web and covid19 data. 

covoid shows 54 recovery and state government website shows 55 recovery.

source link:- https://gujcovid19.gujarat.gov.in/

also city wise all data available by state government. Have a look if you can accommodate.

**Comment by sudevschiz** [comment]
Fixed. Thanks for reporting. Please try to use the Contact Us form next time for (Check the Pinned Issue in the repository)
