### ISSUE TITLE
get States data in the API along with disctricts

### ISSUE THREAD

**Issue by shree-vastava** [covid19india/covid19india.github.io#1074]
I am using a rapid api which sends me the data of state_wise very similar to yours but it highlights the states highlights before jumping to disticts.

```
"Maharashtra":{
"active":"2066"
"confirmed":"2455"
"deaths":"160"
"deltaconfirmed":"121"
"deltadeaths":"0"
"deltarecovered":"0"
"lastupdatedtime":"14/04/2020 12:42:10"
"recovered":"229"
"state":"Maharashtra"
"statecode":"MH"
"statenotes":""
"district":{...
}30 items
```
Will it be possible to add this data? From the current data, I can add up the confirmed cases and delta in confirmed. But there is not data for state level recovered and deceased.

**Comment by shuklaayush** [comment]
Hey @shree-vastava, have a look at this [API](https://api.covid19india.org/data.json). It contains the state-wise breakdown of confirmed, recovered and deaths. Hoping this is what you need.

**Comment by shree-vastava** [comment]
@shuklaayush Thanks. I knew about this API. Could not see the statewise array. Didn't pay attention to the whole data, my bad.
Thanks a lot. i have made an android app using this.
