### ISSUE TITLE
PATIENT AGE bar graph hover does not show appropriate data

### ISSUE THREAD

**Issue by faisal3389** [covid19india/covid19india.github.io#1076]
**Describe the bug**
When hovered upon the bar graph for patient age box, in the deep dive section. It does not show the proper data

**To Reproduce**

1. Go to 'https://www.covid19india.org/deepdive'
2. Scroll down to 'PATIENT AGE'
3. Hover on the age groups and move the cursor to different bars.

**Expected behavior**
The tooltip should show the count of patients the user is hovering upon.

**Screenshots**
<img width="1440" alt="Screenshot 2020-04-14 at 1 57 22 PM" src="https://user-images.githubusercontent.com/16716470/79202895-e0faaa80-7e57-11ea-8cde-1df8f296425d.png">
The mouse is on the differnt bar, and the tooltip appears for different bar.

**Desktop (please complete the following information):**

- OS: [all]
- Browser [chrome]

**Comment by sudevschiz** [comment]
Weird bug. Please do help.

**Comment by gyanendrapatro** [comment]
please do assign it to me i can fix it

**Comment by gyanendrapatro** [comment]
fixed it with below PR
fixing tooltip for agechart #1307

**Comment by gyanendrapatro** [comment]
@shuklaayush @sudevschiz please review it and if you feel do merge

**Comment by sudevschiz** [comment]
Thank you. Merged!
