### ISSUE TITLE
Adding a graph for current active cases

### ISSUE THREAD

**Issue by np000** [covid19india/covid19india.github.io#1077]
**Is your feature request related to a problem? Please describe.**
No. Its an improvement to the existing visualization.

**Describe the solution you'd like**

When we select a particular state there are graphs for Confirmed, Recovered and Deceased. It would be good feature if we can an add en extra graph on "Active Cases"

**Describe alternatives you've considered**
Did not find any.

**Additional context**
![Screenshot_2020-04-14-15-29-23-654_com android chrome](https://user-images.githubusercontent.com/26089883/79212822-c6c7c900-7e65-11ea-8b8d-2e2c6da78f11.png)
Device: Android 
Browser: Chrome

**Comment by shuklaayush** [comment]
Duplicates #825
