### ISSUE TITLE
Double clicking a key in any graph highlights the heading of next graph

### ISSUE THREAD

**Issue by nikitha90** [covid19india/covid19india.github.io#1079]
When the key of any graph is double clicked in desktop, the heading of the next graph is getting highlighted.

1. Click on "deceased" in the key section of INDIA - TOTAL CASES graph
2. See the next graph heading INDIA - DAILY CASES heading getting highlighted in text "INDIA"
3. On deselecting the key, the highlighting is turned off
3. This issue happens with all graphs that contains keys.

Tried in desktop and Google chrome browser.

Attached screenshot below.

![image](https://user-images.githubusercontent.com/25319527/79215572-60dd4080-7e69-11ea-93f7-81511ea61bd7.png)

**Comment by sudevschiz** [comment]
Weird. Marking it available

**Comment by vedadeepta** [comment]
@sudevschiz can you assign it to me, I'm willing to give it a go

**Comment by sudevschiz** [comment]
@vedadeepta Sorry about the delay. However @jeremyphilemon is planning on an overall of the section. So @jeremyphilemon please confirm if this should be worked on?

**Comment by jeremyphilemon** [comment]
@sudevschiz will have to keep this on hold.
