### ISSUE TITLE
How to deploy this script on my website

### ISSUE THREAD

**Issue by guptaofficial17** [covid19india/covid19india.github.io#1088]
Sir first of all thank you for this wonderfull script
Sir i am successfully deploy this scipt on localhost but i have to use it through my public ip
Sir please let me know how to use this with my public IP or A website

**Comment by Akcena007** [comment]
@gupta199862 how did u deployed the same on local host?

**Comment by guptaofficial17** [comment]
it is not a php ... which i go and upload on cpanel and boom started working

**Comment by Akcena007** [comment]
@gupta199862 I need to make my own website with the selective components only from this source code for personal education purpose and for learning. 
I dont need maps and all I just need table of figures statewise.
Can you guide me please.

**Comment by guptaofficial17** [comment]
heroku is best for you in one click

**Comment by shuklaayush** [comment]
Closed due to inactivity
