### ISSUE TITLE
Website seems down. Can't access it

### ISSUE THREAD

**Issue by namanambavi** [covid19india/covid19india.github.io#109]

**Comment by jeremyphilemon** [comment]
Back up, thanks for reporting!

**Comment by vidukapoor** [comment]
some Invalid date issue is there, due to backend code change, its been fixed now.
https://github.com/covid19india/api/commit/0e3d6024cd891828c83264a6c09423f13ff5b5ff

**Comment by vidukapoor** [comment]
hi @jeremyphilemon raised https://github.com/covid19india/covid19india-react/pull/114 for stopping future crashes.
