### ISSUE TITLE
Issues in Raw Data JSON

### ISSUE THREAD

**Issue by Subinsm** [covid19india/covid19india.github.io#1090]
In the https://api.covid19india.org/raw_data.json, there are some misaligned values for keys. All values from "currentstatus" key are assigned to the next key 

For Example,
currentstatus:                         instead of currentstatus: Recovered   
dateannounced : Recovered instead of dateannounced: 21/03/2020

These misaligned keys are seen between dates 17/03/2020 to around 24/03/2020

**Comment by JunaidBabu** [comment]
I'm sorry I don't see any issues. Can you provide a screenshot or something?

**Comment by Subinsm** [comment]
I am terribly sorry for wasting your time. It was a mistake in my JSON parser.
One example:
 "backupnotes": "Returned from Spain; Indira Gandhi National Forest Academy Trainee" 
The semicolon made my parser read "Returned from Spain" as one key and added "Indira Gandhi National Forest Academy Trainee" to the next key.
