### ISSUE TITLE
Sir I was not able to access the api as well the Dashboard on my cell phone for sometime  on 14-04-20 evening

### ISSUE THREAD

**Issue by bansallabs** [covid19india/covid19india.github.io#1092]
was there any issue 

both JSON and site was un available.

**Comment by sudevschiz** [comment]
There could've been some delay in API reflecting the numbers yesterday. However, there should not have been any downtime. 

Please do join the [dev group](https://t.me/joinchat/APSO7lRvI-WwV4CW0LncKw) for faster updates and Q&A regarding the site downtime etc. Thank you.
