### ISSUE TITLE
Add district wise active, discharged, deceased status on expanding the states

### ISSUE THREAD

**Issue by Mrutyunjay1992** [covid19india/covid19india.github.io#1093]
Please add district wise active, discharged status on expanding the states

**Comment by sudevschiz** [comment]
We are capturing the district of the Recovered/Deceased cases as much as possible. However many cases need to be back-updated. Will try to work on this as soon as possible. 

Once the data is more complete, this can be easy shown in the table.

**Comment by jeremyphilemon** [comment]
Closing cause duplicate of #675
