### ISSUE TITLE
how to edit and run this project on my localhost (for personal use)

### ISSUE THREAD

**Issue by Akcena007** [covid19india/covid19india.github.io#1094]
how to edit and run this project on my localhost (for personal use).

I need to make my own website with selective components from the website

**Comment by bootleg-icarus** [comment]
You'll see the 'Fork' option in the top right corner. Click that. This will copy the repo on your page.
You'll see the big green button labelled "clone or download". You can use the link as 
`git clone link` (replace link with the link you copied)
or download and extract the files manually.
You'll need [node](https://nodejs.org/en/) installed on your system. 
Once you're in the directory of the local copy of the project, run `npm install` or `yarn` (if you use yarn)
then `npm start` will start a dev server and you'll the website on your localhost:3000

This question is basic, so maybe google before you ask.

**Comment by bee-rickey** [comment]
Closing.
