### ISSUE TITLE
Selecting All States in drop-down doesn't reset the map

### ISSUE THREAD

**Issue by aishmittal** [covid19india/covid19india.github.io#1095]
**Describe the bug**
On the home page when the user selects **ALL STATES** from the drop-down above the graphs the map still shows the previously selected state instead of a complete map of India. 

**To Reproduce**

1. Go to Home Page
2. Select a state from the table
3. Select ALL STATE option from drop-down above the graphs on left
4. The map on top still shows old selected state

**Expected behavior**
The map should show the complete map of India

**Screenshots**
![image](https://user-images.githubusercontent.com/11550572/79254262-188e4480-7ea2-11ea-9bfb-7943973a7e88.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Chrome
- Version: 80.0.3987.163

**Comment by sudevschiz** [comment]
I am not able to reproduce the issue. 
![Profile-20200415T132143](https://user-images.githubusercontent.com/4298868/79298511-4fa13c00-7f1c-11ea-8980-9f2506ec3aa5.gif)


Could you share more details or share a screen capture?

**Comment by aishmittal** [comment]
@sudevschiz Yes not reproducible in the current build. So I am closing it for now.
