### ISSUE TITLE
City-wise Recovery vs Death Rates

### ISSUE THREAD

**Issue by SIFAR786** [covid19india/covid19india.github.io#1097]
**Is your feature request related to a problem? Please describe.**
I am trying to understand what is the number of Recoveries vs Deaths for Active cases, in the case of Metro Cities like Mumbai, Chennai, Telangana etc. So a City-wise chart showing Active Cases and the number of Recoveries vs Death could give it's citizen's a clear indicator as to how much they are following social-distancing and whether they are still in a Red zone or moved to Yellow, Green zones etc.

**Describe the solution you'd like**
Expecting a City-wise Bar Chart showing number of Active cases and on a secondary axis showing Recoveries vs Death Lines for the usual timeperiods you have already kept for the other charts.

**Describe alternatives you've considered**
City-wise patient cases charted separately on page.

**Additional context**

**Comment by sudevschiz** [comment]
We rarely get city-wise information from the state bulletins. So, with the current data, it might not be possible to plot anything geographically more granular than a district.
