### ISSUE TITLE
Delta count doesn't reset at 12 am. It still adds to the previous day's delta count

### ISSUE THREAD

**Issue by hbgowda** [covid19india/covid19india.github.io#1099]
**Describe the bug**
Delta count doesn't reset at 12 am. It still adds to the previous day's delta. For eg. CONFIRMED  cases delta count was +1023 just before 12 am on 15th April 2020 and at 1:10 am on 15th April the CONFIRMED delta is +1033 when actually it should have been just +10. The same is the case for other statistics such as RECOVERED and DECEASED

**To Reproduce**
Go to home page and check the delta before and after 12 am. The delta count doesn't get reset at 12 am

**Expected behavior**
At 12 am every day the previous day's delta should be reset to zero and and new delta count should start for the new day

**Screenshots**
![image](https://user-images.githubusercontent.com/63492113/79271866-23ef6900-7ebe-11ea-989b-dcd255f29993.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Firefox 74.0.1 (64-bit)

**Comment by deepankkartikey** [comment]
@hbgowda 
Can I look into this?
Also, I was trying to set up the project in my local environment. Do we have document or any steps for this?

**Comment by deepankkartikey** [comment]
@hbgowda 
I was able to launch project in my local, can I look into this issue?

**Comment by deepankkartikey** [comment]
@hbgowda 
The delta is calculated inside the Patient Database sheet only and directly pulled from there. 
The formula applied there may be wrong.

**Comment by sudevschiz** [comment]
@hbgowda @deepank120896 The delta is set to be reset at 7AM every day IST.
This has been set intentionally because many of the state bulletins come out close to midnight and we would like to display the current stats throughout the night. 

Thanks for reporting.

**Comment by sudevschiz** [comment]
However, we do have an inconsistency with this behaviour for the district delta. @deepank120896 could you have al look at #1104 ?

Much appreciate your help.

**Comment by hbgowda** [comment]
Thanks @deepank120896 for your interest in this issue and @sudevschiz for clarification. Appreciate it.
