### ISSUE TITLE
Need to show recent cases added in home page.

### ISSUE THREAD

**Issue by s-naveen** [covid19india/covid19india.github.io#110]

**Comment by jeremyphilemon** [comment]
What do you mean? There are delta values present on the header, would appreciate more information!

**Comment by s-naveen** [comment]
@jeremyphilemon I meant recent cases timeline like the one shown on worldometer. 
https://prnt.sc/rn8vtt

**Comment by JunaidBabu** [comment]
Duplicate of #292
