### ISSUE TITLE
A new Detailed Icon for the page for a better COVID representation. 

### ISSUE THREAD

**Issue by bhaumikmistry** [covid19india/covid19india.github.io#1101]
**Is your feature request related to a problem? Please describe.**
A Graphical representation is very important, hence I have come up with a more detailed image to show the icon for the webpage

**Describe the solution you'd like**
Please see the attached image for the new reference package
![ms-icon-310x310](https://user-images.githubusercontent.com/17535720/79287789-e45f5780-7e92-11ea-967f-302ee8d177da.png)

**Comment by sudevschiz** [comment]
Thanks for your icon design. However, don't you think a minimal flaticon is good enough?

Closes #1102
