### ISSUE TITLE
Total number of confirmed cases are different in map and graph

### ISSUE THREAD

**Issue by pankzkmr** [covid19india/covid19india.github.io#1103]
![IMG_20200415_083230](https://user-images.githubusercontent.com/29862569/79294536-0b9a4100-7ef4-11ea-9392-20b9026c419d.jpg)

**Comment by pankzkmr** [comment]
![IMG_20200415_083627](https://user-images.githubusercontent.com/29862569/79294668-55832700-7ef4-11ea-9c54-20d137cd3fd4.jpg)

**Comment by sudevschiz** [comment]
Yes, this is a known bug. Let me look into this.

**Comment by sudevschiz** [comment]
Fixed this. It was due to a formula not being present in a cell. Thanks for reporting :)
