### ISSUE TITLE
Problem in Json

### ISSUE THREAD

**Issue by vamgan** [covid19india/covid19india.github.io#1105]
**Describe the bug**
There is age inserted in gender.
**To Reproduce**
Check raw_data.json

**Screenshots**
![image](https://user-images.githubusercontent.com/13998000/79298898-1a86f080-7f00-11ea-9468-1663e7b95781.jpeg)

**Comment by sudevschiz** [comment]
Thanks for reporting. This was a data input error. Has been fixed.

**Comment by vamgan** [comment]
Still not reflecting in the json file.
