### ISSUE TITLE
Incorrect state notes for the state in data

### ISSUE THREAD

**Issue by ameya-pandilwar** [covid19india/covid19india.github.io#1106]
**Describe the bug**
Incorrect state notes for the state in data

**To Reproduce**

1. Go to 'https://api.covid19india.org/data.json'
2. Click on 'statewise'
3. Scroll down to 'West Bengal'
4. The statenotes for West Bengal are shown in Punjab

**Expected behavior**
The statenotes for West Bengal should be shown in West Bengal

**Screenshots**
<img width="1280" alt="Screen Shot 2020-04-14 at 10 01 12 PM" src="https://user-images.githubusercontent.com/8572890/79300610-1a550980-7e9c-11ea-9b71-345ea09be749.png">

**Desktop (please complete the following information):**

- OS: Mac OS X
- Browser Firefox
- Version 75

**Smartphone (please complete the following information):**

**Additional context**

**Comment by tannakartikey** [comment]
This is resolved.
