### ISSUE TITLE
Yesterday data button on top of tracker

### ISSUE THREAD

**Issue by maverickpeejay** [covid19india/covid19india.github.io#1107]
1. There should be an EASY way to see yesterday data for main tracker. I believe many users want to compare from last day.

2. Active cases column should be among first columns. Mobile users can see it directly and sort it.

**Comment by roshan000** [comment]
What we need to compare only count from old and new or increased/decreased percent.

**Comment by maverickpeejay** [comment]
Count of confirmed cases- yesterday VS today.
For country, each state and each district/zone

**Comment by tannakartikey** [comment]
@maverickpeejay thanks for creating the issue.

We are already showing the difference on each level you mentioned. 

The confirmed column is shown first as the other three columns sum up to the confirmed column. Also, all the columns are visible clearly on the mobile.
