### ISSUE TITLE
Suggestion for KARNATAKA state missing from Deep Dive Line graph #854 issue

### ISSUE THREAD

**Issue by pradeepAtcodingmart** [covid19india/covid19india.github.io#1108]
**Describe the bug**
KARNATAKA state missing from Deep Dive Line graph

 **Suggestion**
You guys showing only the top 10 states so that's why Karnataka is not visible because it's in 11th place. I have two suggestions for this issue.
1)We can show the top 12 states so that Karnataka will be visible
2) or else, we can show the states which have the count of corona cases >150.

NOTE: Showing all the states might be clumsy.
Suggest me the right one

And please assign this issue to me.

**Comment by Code5500** [comment]
Type:bug

**Comment by sudevschiz** [comment]
This should probably be solved by adding different toggles (Top infected states, Cases > 150) etc.

Please discuss your ideas here.

**Comment by pradeepAtcodingmart** [comment]
![Screenshot 2020-04-20 at 1 59 15 PM](https://user-images.githubusercontent.com/44165454/79731100-6b875200-830f-11ea-8299-d362f4e364cb.png)
I have added this feature
Review needed

**Comment by shuklaayush** [comment]
Can you make a PR? 
Also, I'm closing this. Continue the discussion in #854
