### ISSUE TITLE
No sitemap available (SEO)

### ISSUE THREAD

**Issue by abhishekakade** [covid19india/covid19india.github.io#1110]
**Describe the bug**
Sitemap XML will help increase the reach and improve crawling and overall SEO.

**Comment by tannakartikey** [comment]
@abhishekakade the issue is duplicate of https://github.com/covid19india/covid19india-react/issues/262

Please edit your PR description to point the actual issue as well.

Thanks.

**Comment by abhishekakade** [comment]
@tannakartikey, I searched for 'SEO' issues but didn't find any related to this so I created a new one.
