### ISSUE TITLE
Providing details of the hotspots marked by the government!

### ISSUE THREAD

**Issue by soham4abc** [covid19india/covid19india.github.io#1113]
The recent announcements of the government and the twitter handle of the health ministry should be added I believe. Thus people will be able to see all the government announcements plus the live data of the current cases of covid19 
https://twitter.com/MoHFW_INDIA

**Comment by tannakartikey** [comment]
@soham4abc hotspot request is duplicate of https://github.com/covid19india/covid19india-react/issues/793

I will keep your issue open provided you edit the title and the description of the issue to mention just the social link. 

Thanks.

**Comment by soham4abc** [comment]
> @soham4abc hotspot request is duplicate of https://github.com/covid19india/covid19india-react/issues/793
> 
> I will keep your issue open provided you edit the title and the description of the issue to mention just the social link. 
> 
> Thanks.

Please see to it. Hope it's fine now!

**Comment by GanapathySundar** [comment]
I can work on this issue. Kindly assign it to me
