### ISSUE TITLE
Total test all over india not shown

### ISSUE THREAD

**Issue by Dhrumit8596** [covid19india/covid19india.github.io#1114]
**Describe the bug**
Total number of cases all over the india is not shown.

**To Reproduce**

1. Go to 'https://www.covid19india.org/'
2. Click on 'all states
3. Scroll down to 'Map'
4. It shows a "-" on total number of test done 

**Expected behavior**
It will be great if it shows the total test done.

**Comment by tannakartikey** [comment]
Thanks for reporting the issue, @Dhrumit8596 

It's duplicate of https://github.com/covid19india/covid19india-react/issues/1013
