### ISSUE TITLE
District wise Data is not being displayed in maharashtra

### ISSUE THREAD

**Issue by Code5500** [covid19india/covid19india.github.io#1116]
**Describe the bug**
Rise in number of cases not being available.

**To Reproduce**

1. Go to 'maharastra'
2. Click on 'it'
3. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by shuklaayush** [comment]
Seems to be fixed
