### ISSUE TITLE
PWA for the website

### ISSUE THREAD

**Issue by maddhruv** [covid19india/covid19india.github.io#1121]
**Is your feature request related to a problem? Please describe.**
Every time I have to open the web browser and visit the URL, let's have PWA for the same

**Describe the solution you'd like**
An installable and offline supportive PWA

**Comment by tannakartikey** [comment]
@maddhruv it's duplicate of https://github.com/covid19india/covid19india-react/issues/758

**Comment by ssadev** [comment]
> @maddhruv it's duplicate of #758

Check #133
