### ISSUE TITLE
Uniformity in y-axis scales of summary charts

### ISSUE THREAD

**Issue by akshitmehra** [covid19india/covid19india.github.io#1122]
**Describe the bug**
I think the Confirmed, Active, Recovered and Deceased summary charts have uniform y-axis scales. Because of which, if the Recovered and Deceased are compared with the Confirmed and Active, the line charts for the former look almost flat (straight line) and serves no purpose. The charts will flatten further as and if (god forbid) the cases rise.

**To Reproduce**

1. Go to the homepage

**Expected behavior**
A different scale should be thought of for the Recovered and Deceased summary charts

**Screenshots**
![image](https://user-images.githubusercontent.com/22560083/79333582-6c4d6c00-7f3c-11ea-863b-61c65a1f725d.png)

**Desktop (please complete the following information):**

- OS: All
- Browser: All
- Version: All

**Smartphone (please complete the following information):**

- Device: All
- OS: All
- Browser: All
- Version: All

**Additional context**
N/A

**Comment by Bharath-Kumar-Perumalla** [comment]
I agree with Akshit.
We need to match the Y-axis data scale with the average Y- axis data.
For example we need to use 10 scale ( rather 1000 ) for Y-axis for deaths.
By using 1000 ( K) in Y - axis scale, the graph looks like Flatten esepecailly in death chart.
It may create a wrong impression too.

**Comment by akshitmehra** [comment]
Currently, all the summary charts use the `dailyconfirmed` values from the first chart to calculate their y-axis maximums. I suppose each chart should use their own daily values for this purpose so that they look somewhat like this

![image](https://user-images.githubusercontent.com/22560083/79348060-17b4eb80-7f52-11ea-9743-b8a6138adec1.png)

I don't think, comparing all four charts, makes sense here. In this case, these numbers should be seen as individuals and not related to each other. Please assign to me if this or a similar fix is required.

**Comment by sudevschiz** [comment]
Each chart having an independent axes (like the screenshot) above would be more confusing, imho.

For now, I think we can stick with the scales that's being used. Once the recoveries start picking up in India, that curve will look more prominent.
