### ISSUE TITLE
New addition of cases can be traverse to district level and Ward level of given city.

### ISSUE THREAD

**Issue by prablr79** [covid19india/covid19india.github.io#1124]
All new addition at the city level is fine, however if you can drill down to ward level / Thaluk level will be much help full at stage of project since most of the Govt agencies are started reporting at Municipal level of Red Zone and Green Zone.

**Comment by sudevschiz** [comment]
Ward / City level information is simply too sparse to collect.

We will try to add details regarding the Red-Yellow-Green zones. This is being worked on in this sheet. https://docs.google.com/spreadsheets/d/1A-9EDpiD6vxSaCCa9yYwTRKiNwoJ2hdxjbQkmw_RgTA/edit#gid=0

Please do comment there and help us create a template for the data.

**Comment by jeremyphilemon** [comment]
Closing in favor of #675
