### ISSUE TITLE
Better show case Green Color coding

### ISSUE THREAD

**Issue by prablr79** [covid19india/covid19india.github.io#1125]
Since some of the State/UTs are not growing the cases, can be showcased Green to show case some positive view on the Graph.

its time to showcase both side of the story.

**Comment by shuklaayush** [comment]
Hi @prablr79, it's not a good design principle to create maps with multiple colour hues. Also, a lot of people suffer from Red-green colour blindness (Protanopia), and your suggestion would make it extremely difficult for them to interpret the map. These are some of the reasons that we went with the current design. 

We plan to add separate maps for recovered in the future. Hope that will address your requirement.  Closing for now. Thanks!

**Comment by prablr79** [comment]
Thanks, it's good to see new map with green status.
