### ISSUE TITLE
Add Tested cases in state wise table

### ISSUE THREAD

**Issue by vikramnr** [covid19india/covid19india.github.io#1127]
**Is your feature request related to a problem? Please describe.**
It would be nice to have column to have number of tested cases against each state
![image](https://user-images.githubusercontent.com/8538409/79350714-6c0d9a80-7f55-11ea-85d7-290603407bc4.png)

**Comment by sudevschiz** [comment]
This cannot be added in the main UI as there is simply not enough space to display these numbers. Also, this information is available in the state pages.
