### ISSUE TITLE
Graph to show trends of Active cases 

### ISSUE THREAD

**Issue by adithya77** [covid19india/covid19india.github.io#1128]
**Is your feature request related to a problem? Please describe.**
Currently there are trends for Total cases, recoveries and deaths.
Better to have trends of active cases by which we can clearly see the flattening of the cure.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by shivamsahewala** [comment]
Even I was thinking of a graph showing current active cases. It will help us to show graph curve.

**Comment by cyrilmacphilip** [comment]
+1

**Comment by shuklaayush** [comment]
Duplicates #825
