### ISSUE TITLE
Improve the UI of drop down menu on Essentials Page

### ISSUE THREAD

**Issue by Neha0595** [covid19india/covid19india.github.io#1131]
**Is your feature request related to a problem? Please describe.**
On Essentials page, for state, service and city selection, it'd be better if it have following functionalities:
1. There should be type and search functionality for these selections, as currently user has to scroll down every time in order to find the selection.
2. UI of drop down should be improved 

**Describe the solution you'd like**
For my two cases, I'd like to add following solution
1. For search, local search or search based on api, should be there
2. UI of drop down is currently overlapping the field, i'd be better if it starts from the bottom edge of the field

**Additional context**
Please find the attachment: 

<img width="500" alt="EssentialsScreen" src="https://user-images.githubusercontent.com/36955313/79367774-0a0c5f80-7f6c-11ea-9f0f-de873b6da360.png">

**Comment by Neha0595** [comment]
Please assign this to me.

**Comment by nikita-11** [comment]
1) This problem is only occurring in Mac. Didn't come across this on any other browser or device.
2) Every dropdown has inbuilt search functionality, it will start searching as soon as you put a word in there.
