### ISSUE TITLE
City column in the results table in essentials page has been covered by side navigation menu

### ISSUE THREAD

**Issue by avneeshroks** [covid19india/covid19india.github.io#1135]
**Describe the bug**
The city column in the results table in essentials page is not showing up as the side menu is rendering on top of it.

**To Reproduce**

1. Go to https://www.covid19india.org/essentials
2. Click on Menu on side navigation menu
3. Click on Essentials
4. Click on search
5. Observe the first column i.e City column in the results table is not shown completely

**Expected behavior**
City column in the results table should shown completely.

**Screenshots**
![image](https://user-images.githubusercontent.com/11074737/79399037-dcd9a480-7f9f-11ea-820d-704f858316f8.png)

**Desktop (please complete the following information):**

- OS: Windows
- Browser : Chrome

**Comment by nikita-11** [comment]
@shuklaayush @avneeshroks  This has been fixed. Closing the issue.
