### ISSUE TITLE
Mobile View Layout Issue for Total Test

### ISSUE THREAD

**Issue by codeslane** [covid19india/covid19india.github.io#1137]
Total Tests is hiding from of the viewport. 

Screenshot attached.
![Screenshot_20200416-063620_Chrome](https://user-images.githubusercontent.com/26877201/79403658-267cbc00-7fad-11ea-88d9-965d664b9927.jpg)
![Screenshot_20200416-063625_Chrome](https://user-images.githubusercontent.com/26877201/79403667-2aa8d980-7fad-11ea-8e14-d010ad481782.jpg)

**Comment by sudevschiz** [comment]
`-` was probably there because we hadn't included the total tested numbers then. Please check now and re-open if the issue persists.
