### ISSUE TITLE
Last Updated Time of All India cases is not updating

### ISSUE THREAD

**Issue by agajareiitr** [covid19india/covid19india.github.io#1139]
**Describe the bug**
Last Updated Time of All India cases is not updating its still updated 11 hours ago

**Screenshots**

![image](https://user-images.githubusercontent.com/39427280/79416102-8767bc80-7fcc-11ea-83eb-7ad71b8c7532.png)

**Comment by sudevschiz** [comment]
Some Google scripts were failing then. Has been fixed hence. Thanks for reporting!
