### ISSUE TITLE
Menu item title text should be align center  

### ISSUE THREAD

**Issue by DhiralKaniya** [covid19india/covid19india.github.io#1140]
**Describe the bug**
Menu item title are aligned start of the div. It should be center to provide batter UX. 

**To Reproduce**

1. Go to https://www.covid19india.org/
2. Click on Menu
3. Menu title text

**Expected behavior**
Text should be center for better UX.

**Screenshots**
<img width="1676" alt="Screenshot 2020-04-16 at 10 37 56 AM" src="https://user-images.githubusercontent.com/21332852/79417141-db73a080-7fce-11ea-9f9c-545af5b89145.png">

**Comment by nitinknolder** [comment]
I would like to resolve this issue please assign this issue to me if it is available.

**Comment by jeremyphilemon** [comment]
That was a design choice. Thanks :)
