### ISSUE TITLE
Map View of Uttar Pradesh is overlapping with heading of 'unknown cases'.

### ISSUE THREAD

**Issue by prakhartripathi** [covid19india/covid19india.github.io#1144]
**Describe the bug**
Map View of Uttar Pradesh is overlapping with text of unknown cases (class = unknown)

**To Reproduce**

1. Go to https://www.covid19india.org/
2. Click on Uttar Pradesh on Map view
3.  Uttar Pradesh Map is overlapping with unknown cases text.

**Expected behavior**
It should not overlap.

**Screenshots**
![bug image](https://user-images.githubusercontent.com/22815854/79420169-fdbcec80-7fd5-11ea-8392-9d6f1df28698.jpg)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: chrome
- Version: 80.0.3987.163

**Comment by vivekvroy** [comment]
In mobile view, it overlaps even more
![IMG_0317](https://user-images.githubusercontent.com/10249914/79441080-661ac680-7ff4-11ea-893d-ba6fc8d4209f.PNG)
