### ISSUE TITLE
Call Multiple Times of log.json file

### ISSUE THREAD

**Issue by vivek50** [covid19india/covid19india.github.io#1145]
**Describe the bug**
Call Infine times of log.json file issue.

**To Reproduce**

1. Go to 'https://www.covid19india.org'
2. Click on 'notification icon'
3. Open Network log.

**Expected behavior**
The call of the json file should one time.

**Screenshots**
![Screenshot from 2020-04-16 11-41-41](https://user-images.githubusercontent.com/22144025/79420918-75d7e200-7fd7-11ea-9d27-72c715313892.png)

**Desktop (please complete the following information):**

- OS: ubuntu 18.04
- Browser chrome
- Version 80.0.3987.149 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

**Comment by aishmittal** [comment]
I can work on this issue. Please assign

**Comment by jeremyphilemon** [comment]
Patched :)
