### ISSUE TITLE
redesign issues

### ISSUE THREAD

**Issue by Binu42** [covid19india/covid19india.github.io#1146]
**Is your feature request related to a problem? Please describe.**
new change in design and few other extra functionality are beautiful but current navbar redesign is not good for desktop user, user need to click on menu each time to navigate between pages it's an extra burden for them. and it's creating few other issues for desktop users like essential page. even the issue of not responsive is not fixed in redesign. footer is missing on pages.

**Describe the solution you'd like**
for desktop navbar previous design was good only and for responsive have a look at #957 

**Additional context**
#### demo of few bugs.
* flickering issue
![not stable](https://user-images.githubusercontent.com/45959932/79422828-2f848200-7fdb-11ea-9fe8-c6271da27d8c.gif)
<br>

* scrollbar when menu open
![Screenshot from 2020-04-16 12-09-34](https://user-images.githubusercontent.com/45959932/79422877-462ad900-7fdb-11ea-8666-d7a18cfa6421.png)

**Comment by jeremyphilemon** [comment]
Patched :)
