### ISSUE TITLE
Last Updated time for States is not updating

### ISSUE THREAD

**Issue by agajareiitr** [covid19india/covid19india.github.io#1149]
The Last Updated time for States is not Working or not updating
steps to reproduce
1. hover over states and see on map side

for eg: for Maharashtra it says last updated 16 hours ago 

![image](https://user-images.githubusercontent.com/39427280/79427868-f8b26a00-7fe2-11ea-9ae9-780e64c99abf.png)

**Comment by sudevschiz** [comment]
Duplicate of #1139
