### ISSUE TITLE
Missing Data on Test for Manipur

### ISSUE THREAD

**Issue by JamesMayengbam** [covid19india/covid19india.github.io#1152]
Problem: There are no data of number of test done on the State of MANIPUR. 

Solution: I have no Idea where you got the earlier data from. Or may be our Government's Website is not updated. I have the daily updated data as Image file every day from my network. 

I am new and don't know how to contribute to the data. But you can have the figures from me daily. If you guide me how to update for Manipur I can do that too. 

Regars James

**Comment by jeremyphilemon** [comment]
cc @bee-rickey

**Comment by JamesMayengbam** [comment]
Any update guys. What can I do?

**Comment by bee-rickey** [comment]
Please provide the link where we can get the testing data. We need a source for this. unless we have a source we cannot use the data.

**Comment by JamesMayengbam** [comment]
Okay can I make a google sheet and make it available for public

**Comment by sudevschiz** [comment]
@JamesMayengbam We will have to use official sources which has made the information public. Can you please provide links to those source?

**Comment by jeremyphilemon** [comment]
Closing this due to lack of data from a verifiable source. Feel free to open this if verifiable source is available in the future.
