### ISSUE TITLE
Graph for Active cases state wise

### ISSUE THREAD

**Issue by vikasgarg3112** [covid19india/covid19india.github.io#1154]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by vikasgarg3112** [comment]
This will help everyone to check which state graph is going down. Because at last number of active case is what that matter.

**Comment by vikasgarg3112** [comment]
![25F8E75C-8A6D-4F81-8256-12267179E028](https://user-images.githubusercontent.com/63781500/79439209-281ca300-7ff2-11ea-8d1c-6a24197263a3.png)

For eg this graph is for Australia.. It shows the graph of active case.

**Comment by shuklaayush** [comment]
Duplicates #825. Please comment over there. Thanks!
