### ISSUE TITLE
Close button for menu

### ISSUE THREAD

**Issue by vivekvroy** [covid19india/covid19india.github.io#1156]
Instead of having a separate button for close when we click on menu,
when we hover back to the main content, automatically the menu drop down should go back or get closed.

**Comment by jeremyphilemon** [comment]
I feel like this would involve event listeners on the cursor. Or is there an elegant way to do this?

**Comment by vivekvroy** [comment]
Yes, even I think is better to go with cursor event listener itself.

**Comment by nayakrahul** [comment]
@jeremyphilemon Or just a click in the main content outside the menu should close the menu dropdown.
