### ISSUE TITLE
No of positive cases in Pauri Garhwal District of Uttrakhand is wrong

### ISSUE THREAD

**Issue by mdshamoon** [covid19india/covid19india.github.io#1157]
**Describe the bug**
No of positive cases in Pauri Garhwal District of Uttrakhand is wrong

**Attached file from uttrakhand government website**

[Corrected-15-04-2020-Health-Bulletin.pdf](https://github.com/covid19india/covid19india-react/files/4486238/Corrected-15-04-2020-Health-Bulletin.pdf)

**Comment by jeremyphilemon** [comment]
cc @bee-rickey

**Comment by sudevschiz** [comment]
@mdshamoon Thanks for reporting! I have fixed the districts numbers in Uttarakhand
