### ISSUE TITLE
No of positive cases in Tumakuru District of Karnataka is wrong

### ISSUE THREAD

**Issue by vivekvroy** [covid19india/covid19india.github.io#1158]
No. of confirmed cases for Tumakuru, Karnataka is shown as 1 and it is deceased.
But as per Karnataka government website details,
There is one active case and one person is deceased.
So, total cases should be 2.
[https://karunadu.karnataka.gov.in/hfw/kannada/nCovDocs/15-04-2020(English).pdf](url)
![image](https://user-images.githubusercontent.com/10249914/79443708-ceb77280-7ff7-11ea-8915-2c9e2769db71.png)

**Comment by jeremyphilemon** [comment]
cc @bee-rickey

**Comment by jeremyphilemon** [comment]
Please report data discrepancies in this form https://forms.gle/7NRSrbspW2a6pbm58, thanks :)
