### ISSUE TITLE
The font colors at notification area

### ISSUE THREAD

**Issue by saifeesl** [covid19india/covid19india.github.io#1159]
First of all thanks for the Nobel work.. hats off to you guys..

The notification area is right now plane text area.. 

![image](https://user-images.githubusercontent.com/63785125/79444705-9494a380-7fec-11ea-806c-f81af6ab0a31.png)

can it be like

![image](https://user-images.githubusercontent.com/63785125/79444827-c148bb00-7fec-11ea-9268-a260386cb1a6.png)

**Comment by ghost** [comment]
Assign this to me

**Comment by kousiksatish** [comment]
@kalesourabh01 If you are not working on this, I would like to take this up.

**Comment by saifeesl** [comment]
Sourabh seems engaged with some task, kousik.

**Comment by ghost** [comment]
@saifeesl I look into above enhancement request but I found there response is like

![image](https://user-images.githubusercontent.com/13964313/79876689-fbf58d80-8408-11ea-8b98-32e71388c3c7.png)

to fix this I need update status in a proper data object

**Comment by shubhamjain2998** [comment]
@kalesourabh01, try to use regular expressions to match and replace the response string and manipulate it respectively with the HTML elements.

**Comment by ghost** [comment]
@shubhamjain2998  yep bro doing that

**Comment by kalesourabh01** [comment]
Hi, @shubhamjain2998 I had committed changes but not aware about how to change status here can you help?

**Comment by kousiksatish** [comment]
@kalesourabh01 Any updates on this? I can take this up if you are not working on it.

**Comment by ghost** [comment]
Done and sent a pull request
