### ISSUE TITLE
"Dadra and Nagar Haveli and Daman and Diu" is a single union territory while it is shown as two different states.

### ISSUE THREAD

**Issue by animesh-tarodia-sp** [covid19india/covid19india.github.io#1160]
**Describe the bug**
Dadra and Nagar Haveli and Daman and Diu is a single union territory. It was merged in dec 2019 and came into effect from 26 jan. When we search the state it is shown as two different states.

**To Reproduce**

1. Go to 'Search'
2. Type 'd'

**Expected behavior**
"Dadra and Nagar Haveli and Daman and Diu"  should be shown as single union territory.

**Comment by guneetnarula** [comment]
Yes these two can be merged. Any issues with the length of the UT name or should we go with "Dadra and Nagar Haveli and Daman and Diu". It will have 3 districts.

**Comment by jeremyphilemon** [comment]
@bee-rickey possible to change, or keep as is?

**Comment by shuklaayush** [comment]
Fixed via 6a801d6f41fd26e7c9725a4c248ae24b03f533ee
