### ISSUE TITLE
Home Page Tabular infographic should also display columns for active, recovered and deceased people for the districts

### ISSUE THREAD

**Issue by deepanker0193** [covid19india/covid19india.github.io#1163]
**Is your feature request related to a problem? Please describe.**
There is no problem as such, but this feature will give a detailed insight into a particular area to the reader.

**Describe the solution you'd like**
Add Column for Active, Recovered and deceased when I expand a state.

**Additional context**

<img width="600" alt="Screenshot 2020-04-16 at 3 23 22 PM" src="https://user-images.githubusercontent.com/63586587/79445624-97969080-7ffa-11ea-9f63-4719187735e0.png">

**Comment by deepanker0193** [comment]
Please assign this issue to me.

**Comment by shuklaayush** [comment]
@deepanker0193 This has more to do with the data/API. The relevant code is already there. Also, since this duplicates #888, please continue the discussion over there. It would make it easier for us to track. Thanks!
