### ISSUE TITLE
Clicking on state navigate to state page

### ISSUE THREAD

**Issue by marutha** [covid19india/covid19india.github.io#1169]
**Is your feature request related to a problem? Please describe.**
It is not that user friendly to enter state names and then navigate to state page, it is kind of frustrating to key in and search for each state.

**Describe the solution you'd like**
Click on any state on the map to navigate to state page

**Describe alternatives you've considered**
- Not applicable -

**Additional context**
Existing search is a addtional feature.

**Comment by kousiksatish** [comment]
Same point I had mentioned in #1230
I would like to work on this
### **In map**
![Screen Shot 2020-04-17 at 11 48 24 PM](https://user-images.githubusercontent.com/6641694/79601152-fd237380-8105-11ea-9d0b-82c1165c083e.png)
### **In table**
![Screen Shot 2020-04-17 at 11 45 55 PM](https://user-images.githubusercontent.com/6641694/79601159-001e6400-8106-11ea-9723-0ce0f8e7e5ec.png)

A link like this would look better.

@jeremyphilemon @sudevschiz Please review

**Comment by jeremyphilemon** [comment]
Sure :)

Here's some reference for design consistency:

<img width="638" alt="Screen Shot 2020-04-18 at 3 12 46 AM" src="https://user-images.githubusercontent.com/17938322/79622986-8e084800-8122-11ea-986c-cf8549761528.png">

<img width="507" alt="Screen Shot 2020-04-18 at 3 17 42 AM" src="https://user-images.githubusercontent.com/17938322/79623133-31f1f380-8123-11ea-9113-1a3c59c7a8fa.png">

**Comment by kousiksatish** [comment]
@jeremyphilemon Will do it as you suggested

**Comment by kousiksatish** [comment]
@jeremyphilemon Please review
