### ISSUE TITLE
Show percentage of cases on the main page

### ISSUE THREAD

**Issue by nischalsamji** [covid19india/covid19india.github.io#117]
Show % of statistics in the main page.
Mock 

![image](https://user-images.githubusercontent.com/887091/77565354-1ad83100-6eea-11ea-80c8-a37a31403e95.png)

**Comment by Rajanpandey** [comment]
Hi, I am new here.
Looking to contribute.
I will do this.

**Comment by Rajanpandey** [comment]
Done. Kindly check.
PR: https://github.com/covid19india/covid19india-react/pull/127

**Comment by JunaidBabu** [comment]
Not really useful
