### ISSUE TITLE
[SERIOUS] Menu opens a transparent list !! 

### ISSUE THREAD

**Issue by dpnkrpl** [covid19india/covid19india.github.io#1172]
On mobile devices Tapping on menu opens a transparent list of links leaving it impossible to navigate to the other pages.
A complete mess !!

![Screenshot_2020-04-16-19-34-55-528_com android chrome](https://user-images.githubusercontent.com/27947066/79465776-68434c00-8019-11ea-8f1f-0edd68307609.jpg)

**Comment by Binu42** [comment]
tried to fixed at PR #957 link is [here](https://covid19india-react-25cirxyj3.now.sh/)

**Comment by jeremyphilemon** [comment]
Patched!
