### ISSUE TITLE
Tested Numbers on Home Page shows blank even though data is available

### ISSUE THREAD

**Issue by sandipndev** [covid19india/covid19india.github.io#1174]
**Bug Description**
The homepage of [https://www.covid19india.org/](https://www.covid19india.org/), on it's initial load, doesn't show any tested numbers even though tested data of many states are available.
![image](https://user-images.githubusercontent.com/40622610/79457216-7ab78880-800d-11ea-9df3-e8c134519283.png)

**Expected behavior**
Since data for almost all of the states are available (even if some of them are 3-4 days old), we should display the number of people **tested** as well on the initial load. Expected behaviour is to sum up all the number of tested people from all of the states and display it there.

**Additional context**
![image](https://user-images.githubusercontent.com/40622610/79467016-efdd8a80-801a-11ea-9e39-6d6a06098b0c.png)
Since the tested box has a last updated field and a link field, I guess the initial load should not display those.

**Why is it important?**
The amount of people tested for Covid-19 is extremely significant. The lower the number of people tested, higher is the chance that there is a significant number of people with Covid-positive, unreported. The website provides, as of now, no way to see the total number of people from India who have been tested. Even if some data is a few days old, many state's data of reported Covid-cases, recovered and deaths are old as well. Since those fields are summed up and shown, the tested field must also be summed up and shown.

**Comment by kbpatel1** [comment]
I think, this number should be number of sample tested, not number of people tested. As per ICMR update, as of April 16 number of sample tested are 3,02,956, where as number of people tested are 2,86,714. I think this site https://www.worldometers.info/coronavirus/ is also reporting number of samples tested for all countries.

**Comment by sudevschiz** [comment]
The site now reflects the Total Tested reported by ICMR. Thanks for reporting.

@kbpatel1 , since the other numbers reflect each individual, isn't it better to have parity with that and report the total individual tested?
