### ISSUE TITLE
Content on main page overlaps the Menu items on mobile browser

### ISSUE THREAD

**Issue by ghost** [covid19india/covid19india.github.io#1175]
**Describe the bug**
Content on main page overlaps the menu items becomes un-clickable when 'Menu' button is clicked on top right corner. 

**To Reproduce**
Steps to reproduce the behaviour:

1. Open website on mobile browser. (I am using Chrome on Android)
2. Click on 'Menu' in top right corner.
3. You'll see that content behind the menu items overlaps it.
4. Try and select any item from menu, and you'll see that they are not clickable.

**Expected behaviour**
On mobile browser, content should not overlap menu items.

**Screenshots**
![image](https://user-images.githubusercontent.com/48474184/79468545-ad1cb200-801c-11ea-87c9-c179ad1e72df.png)

**Smartphone:**
- Device: OnePlus 6T
- OS: Android 10
- Browser: Chrome
- Version: 81.0.4044.96

**Comment by ghost** [comment]
[content-overlaps-menu-item(1).mp4.zip](https://github.com/covid19india/covid19india-react/files/4487779/content-overlaps-menu-item.1.mp4.zip)

Zip file contains a video recorded. This might give you more clarity about the issue.

**Comment by Binu42** [comment]
fixed at PR #957 can you look at it once link is [here](https://covid19india-react-25cirxyj3.now.sh/)
duplicate of issues #1172

**Comment by ghost** [comment]
Hey @Binu42 The issue seems to be resolved.
