### ISSUE TITLE
navbaar in mobile mode is not opening proper way

### ISSUE THREAD

**Issue by himanshuhkm** [covid19india/covid19india.github.io#1176]
![covid 19](https://user-images.githubusercontent.com/52048967/79468831-0c7ac200-801d-11ea-83b8-2093ff0dbabc.PNG)

navebar is not opening seperatly its open over the home page

**Comment by Binu42** [comment]
fixed at PR #957 can you look at it once link is [here](https://covid19india-react-25cirxyj3.now.sh/)
duplicate of issues #1175 #1172

**Comment by himanshuhkm** [comment]
yaa looks good now

**Comment by jeremyphilemon** [comment]
Fixed :)

@Binu42 hey, it'd be nice if you could create separate PRs for separate issues instead of adding the fix in an already existing PR addressing a different issue!
