### ISSUE TITLE
Plz Add Dark Mode OR Night Mode !

### ISSUE THREAD

**Issue by ashishnirmal-dev** [covid19india/covid19india.github.io#1177]
Dark Mode OR Night Mode Which Ever Sound Good  ..  Thank You

**Comment by deep5050** [comment]
@nirmalaashish yeah we know its a Trend, a good to have feature. But this project has a lot of issues to be fixed . It is becoming a complete chaos day by day. Inconsistent data , UI elements and what not??!

**Comment by jeremyphilemon** [comment]
#743 Duplicate, but is in the works :)
