### ISSUE TITLE
update time and detail for complete understanding view the video  in zip

### ISSUE THREAD

**Issue by himanshuhkm** [covid19india/covid19india.github.io#1178]
[COVID-19 Tracker _ India - Google Chrome 2020-04-16 20-34-15.zip](https://github.com/covid19india/covid19india-react/files/4488050/COVID-19.Tracker._.India.-.Google.Chrome.2020-04-16.20-34-15.zip)

as we can see in video when pointing to any state the update time and detail shows but when we wont select any state then its not showing the update and detail of India..... it shows when we reload the page

**Comment by sudevschiz** [comment]
There was some issue with the google script that was failing. Last updated should be fine now.

**Comment by himanshuhkm** [comment]
okay good
