### ISSUE TITLE
Revert the old functionality of clicking on name of state to show sub states

### ISSUE THREAD

**Issue by nitin065** [covid19india/covid19india.github.io#1180]
**Describe the bug**
Drop down box in mobile phone is too small to operate. Revert to old option where clicking on state opens up.

**To Reproduce**

1. Click on state name to show district.

**Expected behavior**
Clicking on state name shows district. 

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

- Device: Samsung S9+
- OS: Android 10.
- Browser: Google Chromw

**Additional context**

**Comment by jeremyphilemon** [comment]
The old functionality is still there tho? Could you please clarify?

**Comment by abhishekakade** [comment]
@jeremyphilemon, clicking on the state name used to show the districts table dropdown but it doesn't anymore. One has to click on that `ChevronDown` dropdown arrow like thingy to see the districts table which is not very user friendly.

**Comment by jeremyphilemon** [comment]
Patched :)
