### ISSUE TITLE
Can we have the hotspot districts highlighted

### ISSUE THREAD

**Issue by sirajulm** [covid19india/covid19india.github.io#1188]
Based on the Home Ministry there are some inclusion and exclusion criteria which would help us to mark the hotspot districts with the available data. But we'd need district-wise timeseries to generate those values.

https://economictimes.indiatimes.com/news/politics-and-nation/govts-plan-to-contain-local-outbreak-is-yielding-results-lav-agarwal/articleshow/75159535.cms

**Comment by bootleg-icarus** [comment]
I agree, the criteria is simple enough that the hotspots can be added based on the data automatically. We only need to compare the new reported cases in a district against the state's reports and/or calculate the doubling rate. To exclude,we need to check if no case has been reported in the last 28 days. All these data points are already available from the APIs
Although the data released by the govt could be different and would need to be checked manually.
Maybe we could have a graph with the option of changing which source to look at.

Your views? @sudevschiz @jeremyphilemon @shuklaayush

**Comment by jeremyphilemon** [comment]
Are these classification points announced by the government, I'm unable to view the source at https://economictimes.indiatimes.com/news/politics-and-nation/govts-plan-to-contain-local-outbreak-is-yielding-results-lav-agarwal/articleshow/75159535.cms

**Comment by bootleg-icarus** [comment]
I too am unable to find the source of those rules provided by economic times but I did find sort of [guidelines released by govt to identify hotspots](https://pib.gov.in/PressReleasePage.aspx?PRID=1616084). 
I suspect locking down a district is more nuanced than 4 simple rules. For example, if the number of cases rise from 1 to 2 (doubled in 4 days), is that still a hotspot? 
We probably won't be able to identify all the rules that go into listing a district as a hotspot, but the list is of hotspots is available and can be updated by volunteers.
The rules would probably be helpful to make an educated guess whether the hotspot status should be added or removed based on data that this site currently uses.

**Comment by shuklaayush** [comment]
Fixed via #1712
