### ISSUE TITLE
State selected in table should be highlighted in map and subsequent details should be shown.

### ISSUE THREAD

**Issue by sscsp489** [covid19india/covid19india.github.io#119]
when we select or hover on a state in table , automatically that respective state will get highlighted in map and subsequent detail should be shown , and it should also happen vice versa !

![Screenshot from 2020-03-25 22-58-32](https://user-images.githubusercontent.com/36526662/77566840-3fcda380-6eec-11ea-9b63-cf80d39dcc1f.png)

**Comment by shuklaayush** [comment]
Relevant: https://css-tricks.com/svg-map-rollovers/

**Comment by radhasatam** [comment]
Created pull request #137 for this.
