### ISSUE TITLE
Navbar overlapping with the content on state pages

### ISSUE THREAD

**Issue by saujanyanagpal104** [covid19india/covid19india.github.io#1190]
**Describe the bug**
With the navbar open if I go to any state's page through the search bar, the navbar should close automatically but it's not happening right now on the desktop instead it's blocking the content.

**To Reproduce**

1. Open Navbar by clicking on Menu and keep it open.
2. Search for any city or state and go to the states page you will see that navbar is blocking the content.

**Expected behavior**
When I am going to state's page with the navbar is open it should close automatically.

**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/40171689/79491624-5cb54c80-803c-11ea-85a9-d59c8efacf07.jpg)

**Desktop (please complete the following information):**

- OS: Ubuntu 18.04 and Windows 10
- Browser: Chrome
- Version: 81.0.4044.92 (Official Build) (64-bit)

**Comment by jeremyphilemon** [comment]
Patched.
