### ISSUE TITLE
Date is mismatching with updates timing are not matching

### ISSUE THREAD

**Issue by userhasnoname0** [covid19india/covid19india.github.io#1191]
**Describe the bug**

**To Reproduce**

1. Go to '...Update bell icon '

**Expected behavior**
17 Apr should not be there.

**Screenshots**
[If applicable, add screenshots to help explain your problem.]
![Screenshot_20200417-000717](https://user-images.githubusercontent.com/62875345/79494157-2c6fad00-8040-11ea-9766-4eb36748199d.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

- Device: [e.g. iPhone6] MiA3 
Android 9

**Additional context**

**Comment by JunaidBabu** [comment]
@sudevschiz this still happening?

**Comment by shuklaayush** [comment]
Duplicates #781
