### ISSUE TITLE
New chart to depict source of Confirmed case, may be state wise

### ISSUE THREAD

**Issue by Nikhiljoseph31** [covid19india/covid19india.github.io#1192]
![Screenshot_20200417-001448_Facebook](https://user-images.githubusercontent.com/63017808/79494511-c20b3c80-8040-11ea-81f4-41f0153ad2ce.jpg)
Similar to this pie chart

**Comment by lakshmi14** [comment]
Hi .. There is already a chart with confirmed statewise. 
![image](https://user-images.githubusercontent.com/7721961/79735343-c2902580-8315-11ea-85fb-32614e188c6c.png)


Where would you suggest me to include pie chart. Need your inputs ?

**Comment by Nikhiljoseph31** [comment]
Hi

First let me tell you awesome job building this site, this is amazing hats
off.

No the suggestion was more to indicate pie chart indicating source of
transmission like travel, contact, local transmission etc.

I saw this in one site related just to one state, of that can be collated
across the country will be super useful.

Thanks
Nikhil Stephen

**Comment by lakshmi14** [comment]
Sure will take it forward

**Comment by lakshmi14** [comment]
![Covid Enhancement](https://user-images.githubusercontent.com/7721961/79992553-42aeba80-84d1-11ea-824f-e52d07a930bd.gif)

Please check if it is fine ? Need any corrections ?

**Comment by Nikhiljoseph31** [comment]
Yes this is good, put it in both country and state sites.

**Comment by lakshmi14** [comment]
Sorry I didnt get you? 
Country and state sites meaning ?

**Comment by Nikhiljoseph31** [comment]
https://www.covid19india.org/

And
https://www.covid19india.org/state/MH (for example)

**Comment by lakshmi14** [comment]
Sure thanks :)

**Comment by lakshmi14** [comment]
![Covid Enhancement (1)](https://user-images.githubusercontent.com/7721961/80083222-fae06f80-8572-11ea-8745-de039e2df14c.gif)

Made some changes in colors and displaying the statename. ALso implemented in statewise page too :) If you are okay I  will create a pull request :)

**Comment by Nikhiljoseph31** [comment]
Awesome, please go ahead.

Great job. Thanks.

**Comment by lakshmi14** [comment]
This is the preview site :
https://covid19india-react-git-fork-lakshmi14-newbranch.covid19india.now.sh/

 If its merged then it will be live, there are some merge conflicts which can be resolved only by maintainers.

**Comment by Nikhiljoseph31** [comment]
Any idea if this can be merged?

**Comment by lakshmi14** [comment]
@jeremyphilemon  Can you merge this request ? thanks.

**Comment by lakshmi14** [comment]
@jeremyphilemon can you do something about this ??

**Comment by jeremyphilemon** [comment]
@lakshmi14 I've assigned you to this. We're currently showing this data in demographics. Instead of adding it in deep dive, do you think it would be possible to add this in demographics instead and dynamically calculate the visual summary when the filters are applied?

Head to demographics > Choose modes of transmission

**Comment by lakshmi14** [comment]
> This sounds good, however, we wouldn't want to show that visualization on the first page itself. We'd like to keep it minimal for now, however, you can definitely add it to the state page and demographics page as well! - @jeremyphilemon 

Sounds good. Will do it , Thanks :)

Have a question on do you want me to keep the pie chart in demographics ? As I think its already been assigned in Network of Transmission - Additions #1314  to someone.

**Comment by lakshmi14** [comment]
Also will the below alignment issue along with this 👍 

![image](https://user-images.githubusercontent.com/7721961/80273470-e2e22a80-86ef-11ea-8f52-c5cb779ab795.png)

**Comment by jeremyphilemon** [comment]
> Have a question on do you want me to keep the pie chart in demographics?


A pie chart will be fine for now.

> As I think its already been assigned in Network of Transmission


I don't think #1314 is working on a pie chart, they're referring to the network map in state pages. 

> Also will the below alignment issue along with this 👍


We've actually kept the alignment issue on hold at #1233, would like a discussion before making it available!

Let me know if you have any more questions :)

**Comment by lakshmi14** [comment]
ok @jeremyphilemon  Thanks for your clarification , I will work on it.. Also if you have any suggestions on where you want to place it , you can go ahead and suggest.

**Comment by lakshmi14** [comment]
I have created a pull request, Kindly check @jeremyphilemon  ! Thanks :)

**Comment by lakshmi14** [comment]
@shuklaayush and @jeremyphilemon can you please review it and close.. it's long pending..Thanks :)

**Comment by Nikhiljoseph31** [comment]
Is this not getting included?

**Comment by lakshmi14** [comment]
Not sure seems like nobody responding:(

**Comment by Nikhiljoseph31** [comment]
Hi Lakshmi

No worries, anyway this was good work that was done.

Shame it is not yet reflected in the website after all your efforts.
