### ISSUE TITLE
Date problem in notification

### ISSUE THREAD

**Issue by jaykukadiya99** [covid19india/covid19india.github.io#1193]
![Screenshot_20200417-000924](https://user-images.githubusercontent.com/52033777/79494017-ef0b1f80-803f-11ea-89d6-65b0d4ca49de.jpg)

As per screen shot you can notice when i expend notification i show date 17 apr and all the notification of 16th Apr becomes a notification of 17th Apr. 

Above that you display date and time of last notification. 

Notice It with time on screen shot.

**Comment by sudevschiz** [comment]
If the updates cross over to the next day, yesterday's date should be visible in between the notifs.  The endpoint used to provide this updates has the absolute timestamp present in it. So, this should be easily doable.

https://api.covid19india.org/updatelog/log.json

**Comment by shubhamjain2998** [comment]
@sudevschiz @shuklaayush please review my PR regarding this issue.
