### ISSUE TITLE
Placeholder text should be inside the search bar

### ISSUE THREAD

**Issue by ranujmili** [covid19india/covid19india.github.io#1194]
**Describe the bug**
Placeholder text 'search your city, resources, etc.' should be inside the search bar on homepage.

**To Reproduce**

1. Go to 'https://www.covid19india.org/ '
2. On the homepage see the search bar where bug exists.

**Expected behavior**
Placeholder text should be inside searchbar.

**Screenshots**
![Screenshot 2020-04-17 at 12 12 50 AM](https://user-images.githubusercontent.com/63811664/79494289-60e36900-8040-11ea-993d-e8b46c934020.png)

**Desktop (please complete the following information):**

- OS: MacOS
- Chrome, Safari

**Smartphone (please complete the following information):**

- Device: Poco f1
- OS: Android
- Browser: Chrome

**Additional context**

**Comment by avneeshroks** [comment]
Please assign this to me. PR : https://github.com/covid19india/covid19india-react/pull/1196

**Comment by jeremyphilemon** [comment]
Hey, thanks for filing an issue. This was a design choice :)
