### ISSUE TITLE
Add Polyfill File to the project.

### ISSUE THREAD

**Issue by shubhamjain2998** [covid19india/covid19india.github.io#1199]
**Is your feature request related to a problem? Please describe.**
In Many browsers, CSS is getting a little bit broken, like in Safari on ios search bar is not showing. 

**Describe the solution you'd like**
The use of polyfill or polyfill.io will provide a great support to the site.

OS - ios
browser - Safari

![IMG-20200417-WA0003](https://user-images.githubusercontent.com/30628775/79511798-a19dab00-805d-11ea-9acb-10964e04ea22.jpg)

**Comment by jeremyphilemon** [comment]
How would we go about this?

**Comment by shubhamjain2998** [comment]
Actually, I also don't know exactly how to go about this, but for some reason, some dynamic styling is failing in browsers like edge and UC browser in android, this is not a very critical problem and also we can close this issue. 
Here are the screenshots from edge
![photo_2020-04-27_00-42-21](https://user-images.githubusercontent.com/30628775/80317381-196b9280-8821-11ea-855e-a64f55f470b5.jpg)
![photo_2020-04-27_00-42-08](https://user-images.githubusercontent.com/30628775/80317382-1b355600-8821-11ea-9bb9-f3ce6fdcfc04.jpg)
See expand toggle in demographics.
![photo_2020-04-27_00-45-46](https://user-images.githubusercontent.com/30628775/80317386-225c6400-8821-11ea-850f-dc86e6fe8a8a.jpg)
