### ISSUE TITLE
when tested numbers are not available for a state, the height of stats div decreases

### ISSUE THREAD

**Issue by nayakrahul** [covid19india/covid19india.github.io#1200]
When you hover over a state whose tested numbers are not available, the height of stats div decreases.

**To Reproduce**

1. Hover over states whose tested numbers are not available likeTelangana, Sikkim and Meghalaya.
2. Notice how the height of stats decrease.

**Expected behavior**
Height of all stats div should be fixed regardless of numbers inside them

**Screenshots**
![Screenshot from 2020-04-17 02-37-47](https://user-images.githubusercontent.com/11428805/79507244-07d20000-8055-11ea-81dd-7eb2c4dc34aa.png)

**Desktop (please complete the following information):**

- OS: Ubuntu 19
- Browser: Chrome
- Version 81

**Comment by nayakrahul** [comment]
Notice how the height of stats changes when you move from say Maharashtra to Telangana.

**Comment by prashant0268** [comment]
Hello @maintainers.. I would like to contribute towards fixing this glitch. It is caused when there is no testing data for certain states like Telangana / Bhutan which causes the As Of Date label to show or hide. One fix could be to have the legend boxes of fixed height or show a No Data available for the date label as well.
