### ISSUE TITLE
Padding and Margin issue on the Deep Dive Page on Desktop

### ISSUE THREAD

**Issue by prashant0268** [covid19india/covid19india.github.io#1202]
**Describe the bug**

The Deep Dive Page overlaps with the left Nav bar.

**To Reproduce**

1. Go to 'Deep Dive'
4. Notice the overlap of the left most boxes.

**Screenshots**
<img width="1280" alt="deepdive_issue" src="https://user-images.githubusercontent.com/2460304/79521319-e4905c00-8026-11ea-94bc-075ded7a5463.png">

**Expected behavior**
Proper Margin and Padding should be maintained. 
![image](https://user-images.githubusercontent.com/2460304/79521428-23261680-8027-11ea-911c-70ced6633cf5.png)

**Comment by prashant0268** [comment]
I can work on the fix. Please assign me so that I may create a PR.

**Comment by jeremyphilemon** [comment]
Patched.
