### ISSUE TITLE
cases in last 14 days

### ISSUE THREAD

**Issue by DrAKR** [covid19india/covid19india.github.io#1203]
since it is important to know how active is covid 19 in an area, it is pertinent to know how many fresh cases were confirmed in last 14 days . whether there is a sudden rise or the graph is flattening will be suggested by the number of fresh cases in last 14 days.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by sudevschiz** [comment]
The graph already has an option to select 1 month. Isn't that okay?

**Comment by DrAKR** [comment]
sorry that is just graphs of last 1 month or 2 weeks . but it doesnt give the actual figures during that period. and also incorporate this thing in deep dive section where data is being analyzed with comparing other areas.... 
more over cases are recovering in 14 days so figures of 14 days cases is important

**Comment by sudevschiz** [comment]
Ok, 14 days could be a button in main page and in necessary dee-dive graphs. Marking this available.

**Comment by AnshulAg03** [comment]
I can work on this issue. You can assign it to me.

**Comment by DrAKR** [comment]
thanks for adding the graph of state wise  number of cases in last 7 days. but it would be more relevant if it is 14 days as it matches with the incubation period. if there is no case in last 14 days we can presume that there is no virus floating around. and another 2 weeks absence of cases will confirm

**Comment by jeremyphilemon** [comment]
Patched.
