### ISSUE TITLE
Icon Info Showing wrong

### ISSUE THREAD

**Issue by subhasish1315** [covid19india/covid19india.github.io#1204]
**Describe the bug**
Two State info icon (West Bengal and Punjab are showing wrong... most probably interchanged 

**To Reproduce**

1. Go to 'West Bengal and Punjab info icon in homepage'
2. See the tool tip information 

**Expected behavior**
The status are interchanged.

**Screenshots**
![2020-04-17 10_36_08-COVID-19 Tracker _ India](https://user-images.githubusercontent.com/6847739/79534135-6324e200-8097-11ea-973f-91f5feed9f31.png)

**Desktop (please complete the following information):**

- OS: [Win10]

- Browser - chrome

**Comment by championballer** [comment]
Re : The one showing for Punjab should be for West Bengal and the one for West Bengal should be on for Haryana. 

Edit : The issue is resolved
