### ISSUE TITLE
StateNotes of  West Bengal and Punjab are interchanged 

### ISSUE THREAD

**Issue by ashishkshukla** [covid19india/covid19india.github.io#1205]
**Describe the bug**
If you hover over "West Bengal" a pop-up appears which displays "14 recovered Italian tourists included in the tally. 1 death in Ambala unaccounted ". I guess this information is related to Punjab.
Similarly ;hovering over "Punjab" , pop-up shows information related to West Bengal.
 
**To Reproduce**

1. Go to "Home".
2. Hover over "West Bengal" state field.
3. The pop-up appears with information which is not related to West Bengal.
4. If we do the similar thing on "Punjab" , it shows the information related to West-Bangal.

**Expected behavior**
Pop-up should show relevant information of that particular state.
 
**Screenshots**
**Punjab-**

<img width="821" alt="covid_img_2" src="https://user-images.githubusercontent.com/3691950/79534642-c19e9000-8098-11ea-89f4-eeef844856ed.png">

**West Bengal-**

<img width="766" alt="covid_img_1" src="https://user-images.githubusercontent.com/3691950/79534655-ca8f6180-8098-11ea-8cb6-6ce6da560a5a.png">

**Comment by gaganxsaini** [comment]
The information "14 recovered Italians..." belongs to Haryana.

**Comment by championballer** [comment]
Even Ambala resides in Haryana. So the issue should be modified into wrong statenotes.

Edit : The issue is resolved

**Comment by ashishkshukla** [comment]
Yes.
