### ISSUE TITLE
When clicking on map the other data on screen should change not just confirmed cases

### ISSUE THREAD

**Issue by gauravkhuraana** [covid19india/covid19india.github.io#1207]
Goto https://www.covid19india.org/state/TG

and select the dark small portion i.e. Hyderabad. 

You will notice that  only the confirmed cases gets updated rest remains the same. 

A user can get confused and assume wrong data 

Since user applied map filter we can give them information for that particular state 

![image](https://user-images.githubusercontent.com/15048211/79542935-2d3d2900-80aa-11ea-9c21-9b0fad54af8e.png)

**Comment by shuklaayush** [comment]
Hey, since we currently don't have accurate district-level data for active/recovered/deceased, it won't make sense to change the numbers on the top as well. We would have to leave the active/recovered/deceased empty. We can think about this when we have the data. Closing for now
