### ISSUE TITLE
Show city wise case breakdown (count) on the main page table

### ISSUE THREAD

**Issue by shahrk** [covid19india/covid19india.github.io#121]
**Is your feature request related to a problem? Please describe.**
Not related to any problem

**Describe the solution you'd like**
When the user clicks on a state in the main page table, toggle the city wise case breakdown of that particular state

**Additional context**
The data already has the city for most cases and we can have a common other option in each state if the data doesn't have any associated city.

**Comment by aravindha1895** [comment]
Working on it

**Comment by aravindha1895** [comment]
LInking PR #169

**Comment by shahrk** [comment]
Already added PR #164
