### ISSUE TITLE
Time Problem in the Bell open and State wise Last Updated.

### ISSUE THREAD

**Issue by gondsuryaprakash** [covid19india/covid19india.github.io#1215]
**Describe the bug**

**To Reproduce**

1. Go to Bell icon
2. See the time where it is New Case updated.
3. Go to Same State and See the Last Updated Time

**Expected behavior**
Time variation in the Las Updated.

**Screenshots**
![WhatsApp Image 2020-04-17 at 4 26 01 PM](https://user-images.githubusercontent.com/54699494/79562834-473a3400-80c9-11ea-9e56-40fdbafb4fce.jpeg)
![WhatsApp Image 2020-04-17 at 4 26 18 PM](https://user-images.githubusercontent.com/54699494/79562839-4903f780-80c9-11ea-82b2-d36e19aa5db7.jpeg)

**Additional context**

**Comment by sudevschiz** [comment]
This was due to some Google Scripts failing in the sheet. I have done some remedial action. Will monitor to see if this is happening again. Thanks for reporting.
