### ISSUE TITLE
Five day & Three Day doubling line in Logarithmic Chart

### ISSUE THREAD

**Issue by dlmandalia** [covid19india/covid19india.github.io#1217]
Hi 
For a better understanding of the data. if we can add 3 days doubling and 5 days doubling line on the logarithmic chart. This will signify the logarithmic chart. 

Bellow is chart to make you understand what am I saying.

![image](https://user-images.githubusercontent.com/62377190/79566628-7ef8aa00-80d0-11ea-9293-f92522c9e007.png)

Calculation of this 

for 5 days doubling the line

Considering day 1 from where the first case was reported, 14% compounding daily growth, for example,
day 1 1 case
day 2 1.14 cases
day 3 1.2996 cases. .... so on 

for 3 days doubling the line

Considering day 1 from where the first case was reported, 23.33% compounding daily growth, for example, 

day 1 1 case 
day 2 1.2333
day 3 1.521059 
day 4 1.875913

Please find explaining article https://www.worldpopulationbalance.org/exponential-growth-and-rule-70.

You guys are doing great work. Appreciating your work.

Thanking you,

Dipen Mandalia

**Comment by jeremyphilemon** [comment]
Thanks for raising the feature request, we can add this line to the current timeseries graphs when we choose 1 week. Will mark this open for contributors :)

**Comment by shubhamjain2998** [comment]
I would like to work on this. /claim

**Comment by dlmandalia** [comment]
@shubhamjain2998 let me know if you need any help on calculation part.
