### ISSUE TITLE
Access to data source permission

### ISSUE THREAD

**Issue by aamir200** [covid19india/covid19india.github.io#1221]
Hello Team,

Before I can access the the data source that you given. Now on I cannot access the data source to pull data into my report. and its also taking too long.

Can you please have a look and as I cannot pull latest data for my report

**Comment by shuklaayush** [comment]
The APIs are all here https://api.covid19india.org/

**Comment by aamir200** [comment]
But in my report i use following https://docs.google.com/spreadsheets/d/e/2PACX-1vSz8Qs1gE_IYpzlkFkCXGcL_BqR8hZieWVi-rphN1gfrO3H4lDtVZs4kd0C3P8Y9lhsT1rhoB-Q_cP4/pubhtml

now I cannot refresh the data in my reports can you please give me access. or provide url like that

**Comment by aamir200** [comment]
As many user are looking the report and they are say report dont have latest data please allow me to pull the data every day using following link  https://docs.google.com/spreadsheets/d/e/2PACX-1vSz8Qs1gE_IYpzlkFkCXGcL_BqR8hZieWVi-rphN1gfrO3H4lDtVZs4kd0C3P8Y9lhsT1rhoB-Q_cP4/pubhtml

**Comment by aamir200** [comment]
Any update
