### ISSUE TITLE
Menu items should be placed on the left bar

### ISSUE THREAD

**Issue by soubh1k** [covid19india/covid19india.github.io#1223]
**Describe the bug**
Simply having to click a Menu tab is unnecessary and all the menu items can be placed directly on the left bar.

**To Reproduce**
1. Go to covid19india.ord
2. Click on Menu
This click is unnecessary as there are no more options apart from menu.

**Expected behavior**
Remove Menu from left bar and add all the menu items directly in the left bar.

**Desktop (please complete the following information):**

- OS: Win10
- Browser: Edge
- Version: 81.0.416.53

**Comment by KaustubhDamania** [comment]
Yes, this looks cleaner than the original, I would like to work on this. The end result would look like the pic mentioned below

![image](https://user-images.githubusercontent.com/33577657/79669562-0bdb5a80-81da-11ea-8539-4b03c9049e56.png)

**Comment by soubh1k** [comment]
Can any maintainer please assign this issue? The above screenshot looks much better.

**Comment by KaustubhDamania** [comment]
Yes, it's been 6 days since this issue was created.
How long does it take before being assigned an issue?

**Comment by jeremyphilemon** [comment]
Patched.
