### ISSUE TITLE
Discussion: New design overloading more features and less intuitive

### ISSUE THREAD

**Issue by kousiksatish** [covid19india/covid19india.github.io#1230]
I have been a regular user and a contributor to the website.
I recently noticed the changes in the site and just want to register my humble opinions on them.

1. State wise information
    - State wise pages is an excellent addition to the app
    - The way to reach these pages is not at all intuitive. User has to search for a city and then move to the state page which doesn't make sense.
    - Most of them won't know such a page exists
    - **Solution** -  It should be made easily accessible with a hyperlink from the state name in table and/or drop down in the menu bar

2. Search bar on top
    - Most of the people visit the page for the table. In mobiles, the search bar is occupying major part of the initial screen and we have to scroll
    - Solution - We can have a Search icon in the nav bar itself which can be used to open this on demand. 

3. Search contents
    - Search suggestions and the input requires a lot of work.
    - User is not clear what he is searching for, what results he wants. 
    - If we want to view state page, why should he search?
    - Solution - In my opinion, all the info provided by search should be reachable through navigation from menu bar. Search bar just be opened on demand, not always, and be able to search across the website
    
4. Menu bar changes
   - Earlier we were able to switch between pages in one click. Now has become 2 clicks in desktops. 
  - In my personal opinion, I liked the navbar on tap than on the side.

Let us discuss these points and the solution I have suggested
After taking your opinion/changes, I can work on all these solutions by raising separate issues and provide PRs.

**Comment by kousiksatish** [comment]
@jeremyphilemon @sudevschiz Would love to hear from you on this

**Comment by kousiksatish** [comment]
Please check the above issue. I have suggested a way to navigate to state page.

**Comment by shuklaayush** [comment]
I guess a lot of this is obsolete now. It's best if we open separate issues for things that are still left to be addressed
