### ISSUE TITLE
Content overlapping with dropdown symbol on demographics page

### ISSUE THREAD

**Issue by strikertanmay** [covid19india/covid19india.github.io#1233]
**Describe the bug**
Content is overlapped with the dropdown symbol on the dropdown menu which makes UI messy.

**Expected behavior**
Always have some space between the dropdown symbol and the content on it.

**Screenshots**
![rsz_1screenshot_from_2020-04-17_22-17-58](https://user-images.githubusercontent.com/32292953/79607181-70ca7e00-8110-11ea-8ece-7741ac683fd3.png)

**Comment by avneeshroks** [comment]
Can I please work on this. Please assign this to me. PR : https://github.com/covid19india/covid19india-react/pull/1238

**Comment by jeremyphilemon** [comment]
Need suggestions on how we can solve this, when the widths are set to the size of the content, the widths vary and can even get longer resulting in all of them aligned vertically, making it obstruct the page even more since are filters are stickied above.

**Comment by nayakrahul** [comment]
@jeremyphilemon can we implement multi-level dropdown to solve this problem?
https://mdbootstrap.com/snippets/jquery/mdbootstrap/949080
