### ISSUE TITLE
'Latest Update'  icon notification is Always ON

### ISSUE THREAD

**Issue by Anshul797** [covid19india/covid19india.github.io#1235]
The **Blue Dot** as a new notification in the update icon is always on.
Even if i am done reading all new updates, It dosen't fades off.
The overall Home page looks very decent but the constant Blue dot is a bit irksome.

It would be great if you guys, get it turned off once a user opens up the update bar. :)
![one](https://user-images.githubusercontent.com/31384186/79612720-d28fe580-811a-11ea-9953-a1d1a9bd17c3.png)

**Comment by shubhamjain2998** [comment]
I would like to work on this, assign it to me.
