### ISSUE TITLE
Tested Samples numbers in the main table in the Home page

### ISSUE THREAD

**Issue by sriramsridar** [covid19india/covid19india.github.io#1236]
**Is your feature request related to a problem? Please describe.**
No. It is just a new column that I request to be added in the main table in the Home page.

**Describe the solution you'd like**
Please add another column named "Tested Samples" after "Deceased". It would be great if you can add them. Right now, I have to scroll to every state and then find the tested numbers above the India map. Having the numbers in the main table will make it easier for me and anyone who wants to keep track of testing, and positive cases. I need Tested numbers to calculate "Tests to Positive" ratio for each state - for now, I am manually reading them by hovering the mouse and noting.

**Describe alternatives you've considered**
The current alternative is I can hover the mouse over each state to get statewide Tested numbers above India map. But this is tedious.

**Additional context**
You already display these "Tested" numbers above the India map. So, I hope I don't need to explain much since you already are showing the data. Please add this new column after "Deceased".
![Main Table](https://user-images.githubusercontent.com/63880180/79614734-2674dd00-80cf-11ea-89de-c907cc4b2c52.JPG)

**Comment by jeremyphilemon** [comment]
This will be addressed in #1496
