### ISSUE TITLE
Page stutters on transitioning to new page

### ISSUE THREAD

**Issue by jeremyphilemon** [covid19india/covid19india.github.io#1239]
**Describe the bug**
Page stutters on going back to the home page. Or maybe just stutters between switching to a new page. (Maybe not visible in the gif below)

![ezgif-7-b547074b42e0-2](https://user-images.githubusercontent.com/17938322/79619295-20095400-8115-11ea-8ec0-a7936ba9e26d.gif)

**To Reproduce**
Navigate to any page, and head back to home.

**Expected behavior**
The page shouldn't stutter.

**Comment by lakshmi14** [comment]
Hi I would like to take up this please assign it to me thanks

**Comment by jeremyphilemon** [comment]
@lakshmi14 Sure, all yours :)

**Comment by lakshmi14** [comment]
Hi Jeremy,
I have fixed the issue. How to go about? Should I commit the code?

**Comment by lakshmi14** [comment]
![Covid Tracker Fixes](https://user-images.githubusercontent.com/7721961/79682549-dc136d80-8240-11ea-8d34-a29069bab3c4.gif)

I have fixed the issue let me know if I can commit the same ?

**Comment by jeremyphilemon** [comment]
Sure this looks good according to the gif you've shared! In order to commit, you'd have to open a PR so that we can merge. Can you do that please? :)

**Comment by lakshmi14** [comment]
Can we close this?

**Comment by sizanvenk** [comment]
Hi Jeremy, can you please let me what programming languages you use for APIs and for the charts?

**Comment by sizanvenk** [comment]
Hi Jeremy, can you please let me what programming languages you use for APIs and for the charts?

Sorry to use this thread for this question?
