### ISSUE TITLE
show death rate by age

### ISSUE THREAD

**Issue by saurabhsharma1976** [covid19india/covid19india.github.io#1240]
**Is you
[New Microsoft Word Document.docx](https://github.com/covid19india/covid19india-react/files/4495581/New.Microsoft.Word.Document.docx)

replicate as in new case by age histogram by age to also by death rate

**Comment by sudevschiz** [comment]
The mapping of demographics in Deceased cases are quite low. However, will keep this marked in Deep-dive as a potential idea.

**Comment by strikertanmay** [comment]
https://github.com/covid19india/covid19india-react/pull/978 was already exist!

**Comment by jeremyphilemon** [comment]
Addressed by #967
