### ISSUE TITLE
Can not zoom and select Mumbai in the map.

### ISSUE THREAD

**Issue by np000** [covid19india/covid19india.github.io#1241]
**Is your feature request related to a problem? Please describe.**
Yes. I could not select small districts in the map such as mumbai. I have tried  more than 30 times to zoom and select Mumbai in the Maharashtra map. As it's very small it's not selecting even in the maximum possible zoom . All the nearby districts can be selected but not the Mumbai.
Browser : Chrome
Platform: Android 

**Describe the solution you'd like**
My suggestion is to add an option to select small districts or main city districts such as Mumbai, Bangalore, Chennai, Hyderabad, Delhi etc as a legend outside the india map. For example if we can add a small button or dot in the Arabian sea area near the mumbai we can select mumbai district from the map. Same applies to other districts which is difficult to zoom and select in the state map.

**Describe alternatives you've considered**
Not found any. I will update here when I find any.

**Additional context**

Screenshot
![Screenshot_2020-04-18-08-52-59-619_com android chrome](https://user-images.githubusercontent.com/26089883/79627242-52867180-8154-11ea-8c1e-d6680302426b.png)

**Comment by gyanendrapatro** [comment]
yes same fr me i cant see mumbai you can assign to me i can fix it

**Comment by 07tiru07** [comment]
@np000 I guess the other option already present is to click the major cities in the table itself to check the details. I tried it on my mobile and with a couple of zooms, I was able to click on Mumbai.

**Comment by shuklaayush** [comment]
Hi, you should be able to select those districts from the table. Closing this for now, reopen if you have any other solution
