### ISSUE TITLE
the graph is not showing current data

### ISSUE THREAD

**Issue by soham4abc** [covid19india/covid19india.github.io#1242]
**The graph is showing data of 5th april which is 12 days back
**To Reproduce**

1. Go to '...https://www.covid19india.org/'

3. Scroll down to 'graph'

**Expected behavior**
cumulative
![Screenshot (32)](https://user-images.githubusercontent.com/63705023/79627486-46031880-8156-11ea-90fa-69e671ba5406.png)
 data of the last day should be visible

**Screenshots**
attached

Windows 10 64 bit
Chrome

*

**Comment by gurumukhi** [comment]
I also noticed this issue. Also note - This issue is reproduced only when "All states" is selected in dropdown, you you see graph for any one state, it shows data till today, however if we select 'All states', it shows data till 5th April only.

**Comment by tshrwbl** [comment]
Working perfectly now.

**Comment by gurumukhi** [comment]
> Working perfectly now.

True, its working fine now. This issue can be closed (unless you want to investigate why did this happen at initial place to avoid it being repeated in future).

**Comment by shuklaayush** [comment]
I can't seem to reproduce it now. Might've been a bug with the API. Please open the issue again if the problem persists
