### ISSUE TITLE
Recent reported date for a district

### ISSUE THREAD

**Issue by NaveenBoggarapu** [covid19india/covid19india.github.io#1244]
With rules of changing districts to red, orange and green zones, based on last reported date. 

I would be helpful to have the date on which last positive case was reported in a district.

**Comment by jeremyphilemon** [comment]
@bee-rickey do we record last updated time for districts as well?

**Comment by ishandutta2007** [comment]
Tracked under https://github.com/covid19india/covid19india-react/issues/1040

**Comment by ishandutta2007** [comment]
Now it is being tracked under https://github.com/covid19india/covid19india-react/issues/1815 I have added more details there .
And here is a first cut code change, though this code eventually needs to move to API https://github.com/covid19india/covid19india-react/pull/1679
