### ISSUE TITLE
Tests/Population Density District wise

### ISSUE THREAD

**Issue by nidran** [covid19india/covid19india.github.io#1245]
**Is your feature request related to a problem? Please describe.**
We are already displaying the data of no. of tests conducted, if we could add a feature wherein we show tests for district/ state as per the population will help give more idea of the scenario there

**Describe the solution you'd like**
I understand the census that we currently we have is of 2011, but still could help give us an idea of how rigorous the testing being done currently is. We could add another tab to the statewise information and present this data besides the count of tested tab. 

**Describe alternatives you've considered**

**Additional context**

**Comment by rohanmanthani** [comment]
I'm also looking for district wise population density and population size. Couldn't find anything online. Would be useful to add in one of the APIs.
