### ISSUE TITLE
"Top Districts" on State page is not showing correct data

### ISSUE THREAD

**Issue by rahul1995** [covid19india/covid19india.github.io#1251]
**Describe the bug**
On state page, the "Top Districts" list is not showing correct data.

**To Reproduce**

1. Go to https://www.covid19india.org/state/HR (Haryana state)
2. Scroll down to 'Top Districts' list
3. See that "Nuh" district is not in the list despite it being the most affected district in Haryana.

**Expected behavior**
The districts listed should be in the order of confirmed cases.

**Screenshots**
![Screenshot (34)](https://user-images.githubusercontent.com/7647789/79635487-d6f5e600-818e-11ea-9004-52e62df62a06.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by rahul1995** [comment]
The issue is coming because of `slice()` before `sort()` at https://github.com/covid19india/covid19india-react/blob/master/src/components/state.js#L194

**Comment by shuklaayush** [comment]
@rahul1995 Thanks for identifying this! Just pushed a fix.

**Comment by rahul1995** [comment]
Oops I wanted to submit the fix but cool. Thanks :)

**Comment by shuklaayush** [comment]
Sorry, didn't know that. It was a sensitive bug, so had to fix it ASAP. Feel free to submit other PRs related to open issues. Thanks again! :)
