### ISSUE TITLE
On right header section of  Demographics page legends must be selectable.

### ISSUE THREAD

**Issue by Neha0595** [covid19india/covid19india.github.io#1253]
**Is your feature request related to a problem? Please describe.**
On Demographics page it'd be better if it have following functionality:

> In Header on any selected color modes **(ex. Gender)** its legends **(Male, Female, Unknown)** also have tappable functionality so that user can filter Patient-Cards Infographic on selected legend basis.

**Describe the solution you'd like**
I'd like to add tap functionality on it.
As an example:  In case of gender on tap of **Female** the Patient-Cards Infographic highlights only Female Patients ( ![#f33b6c](https://placehold.it/11/f33b6c?text=+) ).

**Additional context**
Please find the attachment:

<img width="600" alt="Screenshot 2020-04-18 at 4 28 04 PM" src="https://user-images.githubusercontent.com/36955313/79636159-51286980-8193-11ea-86f8-100f8e55e227.png">

**Comment by gyanendrapatro** [comment]
yup it make sense you can assign to me i can fix it

**Comment by gyanendrapatro** [comment]
![colormode](https://user-images.githubusercontent.com/13833855/79691458-477b3080-827d-11ea-8a17-cecb4ac7c97a.PNG)

Here is the sample and the logic which i developed so once you assign i can just upload with few styling

**Comment by jeremyphilemon** [comment]
Quick mockup for reference: 

<img width="670" alt="Screen Shot 2020-04-22 at 3 00 07 PM" src="https://user-images.githubusercontent.com/17938322/79979319-00be4e00-84aa-11ea-98a6-7e514b3ac765.png">
