### ISSUE TITLE
Discussion: Observations on design of the homepage and suggestions for improvement (Desktop Only)

### ISSUE THREAD

**Issue by pulakchakraborty** [covid19india/covid19india.github.io#1254]
Hello everyone, I am a regular user of the website using a web-browser and I have a few observations concerning the design of the home-page from usability perspective which I would like to share with you.

## 1. Spread Trends component is not visible at first glance and not intuitive

- **Problem:** Currently when user visits the home-page from a web-browser, a scroll-down action is needed to view the _Spread Trends_ visualizations. Moreover, if one wants to use all the features of the visualization (i.e. using Beginning, 1 month tabs), his/her options of hovering through the states on the left hand side is limited. As you can see in the picture, I can only start from Odisha if I want to hover through different states to visualize their graphs.

![pic1](https://user-images.githubusercontent.com/9195973/79636744-27af1400-817a-11ea-937f-3ac96e81f9c4.png)

- **Current Workaround:** Currently, users can load visualizations for different states by selecting different states available through a drop-down list.

- **Proposed Solution:** I think making the moving the _Spred Trends_ component to the top-left portion of the page (on top of the table component) would be more user-friendly and intuitive. 

Currently there is a _Search-Bar_ component, and a component which includes total numbers and minigraphs. Point 2 of [#1230 ](https://github.com/covid19india/covid19india-react/issues/1230) already questions the relevance of _Search-Bar_ component, and I also agree with the solution that was proposed. In addition, I think, the components with a div of level and minigraph could be moved to the top-right (more will be discussed in the next point) to make space for the _Spread Trends_ component.

Instead of showing all three visualizations for confirmed, recovered and deceased cases, we can show only one, and incorporate vertical tabs to browse through the different visualizations

![pic2](https://user-images.githubusercontent.com/9195973/79637564-db1b0700-8180-11ea-8733-514d45526cd1.png)

## 2. Redundant information on total numbers

- **Problem:** Currently the information on total numbers is presented in 3 different places. This, in my opinion is a bit redundant, and could be removed to make the hom-page more compact.

![pic3](https://user-images.githubusercontent.com/9195973/79637311-a3ab5b00-817e-11ea-898a-da022a67c3d6.png)

- **Proposed Solution:** The general information from the top of the table could be removed. The uers can take use of the information available on the top right side of the page (available over the map component). This would also help us with the problem 1.

Looking forward to a conversation involving the moderators and contributors to discuss these points. Thank you!

**Comment by shuklaayush** [comment]
Hey @pulakchakraborty, thanks for the detailed suggestions. I think @jeremyphilemon would be able to better explain the design choices. I'll just give my two cents.

I believe you're looking at it only through the lens of a PC user. For example, having the buttons on the right of the *Spread Trends* is difficult to translate to mobile, since horizontal space is extremely limited. Our traffic is predominantly mobile, so we have to keep these things in mind. 

Regarding redundancy in the placement of total numbers, I don't think of the ones above the map are particularly redundant. Think of them as a placeholder until the user goes on to select a state to view the state's numbers.

**Comment by zeus990** [comment]
I think a scroll to top feature can be added on the home page at the bottom right corner.
![image](https://user-images.githubusercontent.com/32170771/79670657-5234b780-81e2-11ea-92c6-83c58f45ff7e.png)

**Comment by Ac-Srikanth** [comment]
I think a scroll to top feature can be added on the home page .
