### ISSUE TITLE
Interactive graph for Active Cases per state in Deep Dive

### ISSUE THREAD

**Issue by sapiencop** [covid19india/covid19india.github.io#1256]
In the Deep Dive Page, Graphs are available for total cases reported state wise. However, there is no graphs for Active Cases. 

We can have a "States - Active Case" Graph on the pattern of "States - Total Cases " graph currently available.

**Comment by GanapathySundar** [comment]
I would like to work on this. Kindly assign to me

**Comment by gyanendrapatro** [comment]
if its not done please assign it to me

**Comment by strikertanmay** [comment]
@jeremyphilemon @shuklaayush  I thought a pie chart is a good option for this. Any thoughts or suggestions?
