### ISSUE TITLE
Flickering of sidebar on menu upon hovering to extreme corner

### ISSUE THREAD

**Issue by helios1101** [covid19india/covid19india.github.io#1261]
**Describe the bug**
On hover to extreme left of menu on sidebar we see flickering of blue color.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to sidebar on menu
2. Hover to extreme
3. See error

**Expected behaviour**
Shouldn't be flickering as shown in video

**Screenshots**
https://drive.google.com/file/d/1b6NjEcyx7bHBIXPbMe0z4e6_pFvgjTmG/view?usp=sharing

**Desktop (please complete the following information):**

- OS: MacOS
- Browser : chrome
- Version : 22

**Smartphone (please complete the following information):**

**Additional context**
N/A

**Comment by jeremyphilemon** [comment]
Patched.
