### ISSUE TITLE
Auto Refresh of Page when we come back from other tab

### ISSUE THREAD

**Issue by ashokramcse** [covid19india/covid19india.github.io#1263]
**Is your feature request related to a problem? Please describe.**
I am not getting the proper data without refreshing the page when I go to another tab and come back to the application

**Describe the solution you'd like**
Auto Refresh of page will get me accurate data.

**Describe alternatives you've considered**
Hard Refresh of page.

**Additional context**
Device: IPhone XR
Version: iOS 13.4.1
Browser: Safari Mobile

**Comment by lakshmi14** [comment]
Hi You can assign it to me. I can do it

**Comment by lakshmi14** [comment]
Is this accepted ? I could see review needed still hasn't been available . Also hard refresh will affect the quality of the application.

**Comment by jeremyphilemon** [comment]
Please refer to this comment https://github.com/covid19india/covid19india-react/pull/711#issuecomment-617447680
