### ISSUE TITLE
Observations and Suggestions on India Daily Cases Visualization in Deep Dive

### ISSUE THREAD

**Issue by pulakchakraborty** [covid19india/covid19india.github.io#1265]
## 1. Color Theme

- Problem: At this moment it is difficult to spot the Deceased part of the stacked column chart at first look.

![Screen Shot 2020-04-18 at 7 56 25 PM](https://user-images.githubusercontent.com/9195973/79647822-a4f57b80-81b0-11ea-87d6-a1fe992570e3.png)

- Solution: Use a different color to render the Deceased part of the column. In addition, avoiding the use of the colours red and green in the same stack might help in distinguishing all the parts in a better way. 

- In Addition: Putting the most important part (at this moment Active) at the bottom of the chart will make it easier for the users to compare the values

- Important Links:
[Rules for using colours](https://nbisweden.github.io/Rcourse/files/rules_for_using_color.pdf)
[Creating Stacked column charts](https://blog.datawrapper.de/stacked-column-charts/)

## 2.  Order of text not in-sync with the order in the stacked columns  

- Problem: In a stacked column the order of the stacks (Active - Deceased - Recovered) is different from the description (Recovered - Deceased - Active), visualized while hovering the mouse over a column.

- Solution: Change the order of either the stacks or the text.

System Used:
MacBook + Chrome

**Comment by shubhamjain2998** [comment]
Assign this issue to me.

**Comment by sudevschiz** [comment]
Assigned to @shubhamjain2998 :)
