### ISSUE TITLE
Ghost cases (Recovered)

### ISSUE THREAD

**Issue by praneetjainIN** [covid19india/covid19india.github.io#1268]
**Is your feature request related to a problem? Please describe.**
I have come across someone who had all the symptoms except fever, he couldn't breath for good 2-3 days without a pump. All the time he thought that he had panic attacks, anxiety of isolation etc. 

**Describe the solution you'd like**
An anonymous page so that they can share their experiences in writing to those who are not out and trying to cure themselves in ISOLATION without knowing that they have COVID-19. 

**Describe alternatives you've considered**
Nothing

**Additional context**
I am not sure if people will use it genuinely or there could be some validations before publishing the blog.

**Comment by bee-rickey** [comment]
A really nice idea. But having moderated a lot of the communication that we receive, I know there'll be a flood of two types of messages on that page: 
1. Updates for so and so state and districts.
2. Feature request.

I would want to close this, but will keep it open for review by other mods :)

**Comment by praneetjainIN** [comment]
I can help in filtering one layer of content (i.e. moderation if required)

**Comment by JunaidBabu** [comment]
Out of scope. Closing.
