### ISSUE TITLE
Adding a Scroll to top button on the home page.

### ISSUE THREAD

**Issue by Ac-Srikanth** [covid19india/covid19india.github.io#1273]
Feature- A scroll to top feature on the home page.

Solution Description.
A arrow located at the bottom right corner of the screen when clicked scrolls to the top of the page.

![image](https://user-images.githubusercontent.com/32170771/79670783-1ea65d00-81e3-11ea-894c-57a40cf790ff.png)

**Comment by jeremyphilemon** [comment]
Will be addressed by #1477
