### ISSUE TITLE
R_t tracking on a district level

### ISSUE THREAD

**Issue by rohanmanthani** [covid19india/covid19india.github.io#1275]
**Is your feature request related to a problem? Please describe.**
Would be useful to show Rt a key measure of how fast the virus is growing. All current measurements and division of districts is done purely on whether there is a case or not. Two weeks from now when more districts are infected, this measurement will become much more useful in categorizing districts as red or green. 

**Describe the solution you'd like**
We can run this on a district by district basis to come up with hyperlocal R_t  for each district to know which districts are high spread (red, Rt>1) and which ones are safe (green, Rt<1).  Right now there is low active cases (relatively) but I think this feature would be very useful 2 weeks from today.

https://github.com/k-sys/covid-19/blob/master/Realtime%20R0.ipynb

This is epidemiological work already done by Systrom -- just need to ingest indian district data, compute daily and display on site.

**Comment by saurabhsharma1976** [comment]
this is briiliant! how do we execute this?

**Comment by gauravbgp** [comment]
Seeing as there are currently no Rt graphs it would be very informative to have them state wise first. Like http://rt.live

As requested here #1084

**Comment by rohanmanthani** [comment]
I have done this. Numbers are still very low for Indian states other than MH, GJ and India as a whole. 
**Daily cases normalized**
![image](https://user-images.githubusercontent.com/16709164/79679308-d2532100-81d2-11ea-9342-48e52b71b9c1.png)

 **Viral Reproductive Rate for India as a whole. Greater than 1 means still growing. Less than 1 means reducing.**
<img width="500" alt="india-rt" src="https://user-images.githubusercontent.com/16709164/79679286-a3d54600-81d2-11ea-8d77-6a489c2ab4d0.png">

**R_t for a few states**
![image](https://user-images.githubusercontent.com/16709164/79679292-b2bbf880-81d2-11ea-8902-8d7d11584978.png)

I can improve on this if daily district level data is available in some API. Currently only have state by state and the fluctuations in the numbers make me feel like there is some misreporting. Will be useful in a few weeks if cases go up.

**Comment by gauravbgp** [comment]
@rohanstreamoid  I think your analysis is not correct. I have tried to plot the obtained Rt as per process. Although this is a very preliminary run and not enough has been done for initial value/error and optimized sigma chosing, but looks like shape of Rt for National Average and States should hold like the graphs.


![00TT](https://user-images.githubusercontent.com/406183/79679889-68189b80-8227-11ea-86d4-abaa89c355c6.png)
![01MH](https://user-images.githubusercontent.com/406183/79679890-6949c880-8227-11ea-80cd-93d95e72ed0d.png)
![02DL](https://user-images.githubusercontent.com/406183/79679891-69e25f00-8227-11ea-92b2-31d46727432a.png)
![03MP](https://user-images.githubusercontent.com/406183/79679892-6a7af580-8227-11ea-9f60-0401d39ca3db.png)
![04GJ](https://user-images.githubusercontent.com/406183/79679893-6a7af580-8227-11ea-8939-89656a7932f5.png)
![05TN](https://user-images.githubusercontent.com/406183/79679894-6b138c00-8227-11ea-8def-e70d2f061bde.png)
![06RJ](https://user-images.githubusercontent.com/406183/79679895-6bac2280-8227-11ea-996f-6f99eb423781.png)
![07UP](https://user-images.githubusercontent.com/406183/79679896-6c44b900-8227-11ea-98c2-c2402e14cb1e.png)
![08KL](https://user-images.githubusercontent.com/406183/79679897-6c44b900-8227-11ea-8a5f-4685e0fbd4a7.png)
![09KA](https://user-images.githubusercontent.com/406183/79679898-6cdd4f80-8227-11ea-9bfd-87225bbe672a.png)

**Comment by rohanmanthani** [comment]
Interesting, thanks for the second set of eyes.  I pulled the state data from the csv available on this site and didn't make major variable changes. Will review. 

I was also reading more into the model framework - the model will not work as testing ramps ups. Its a relative reporting model where the fundamental assumption is a fixed rate&type of testing.  It could become more relevant once rate of testing stabilizes -- but for now the country is still ramping up. 

Useful for later stages.

**Comment by meetsitaram** [comment]
> I have done this. Numbers are still very low for Indian states other than MH, GJ and India as a whole.
> **Daily cases normalized**
> ![image](https://user-images.githubusercontent.com/16709164/79679308-d2532100-81d2-11ea-9342-48e52b71b9c1.png)
> 
> **Viral Reproductive Rate for India as a whole. Greater than 1 means still growing. Less than 1 means reducing.**
> <img alt="india-rt" width="500" src="https://user-images.githubusercontent.com/16709164/79679286-a3d54600-81d2-11ea-8d77-6a489c2ab4d0.png">
> 
> **R_t for a few states**
> ![image](https://user-images.githubusercontent.com/16709164/79679292-b2bbf880-81d2-11ea-8902-8d7d11584978.png)
> 
> I can improve on this if daily district level data is available in some API. Currently only have state by state and the fluctuations in the numbers make me feel like there is some misreporting. Will be useful in a few weeks if cases go up.

I am trying to the same. Nice work. Can you share any link from where you got the historic data?

**Comment by meetsitaram** [comment]
Is there a way to download historic data of cases in csv format? I tried opening http://patientdb.covid19india.org, but that only returns a webpage.

**Comment by meetsitaram** [comment]
I was able to extract the district level data from there, cleaned and uploaded it at https://github.com/meetsitaram/covid-19/blob/master/covid19_india_04_19_2020.csv . See if you can get the notebook work with this. I had trouble running the notebook as the data is much less compared to U.S. data having cumulative and much larger counts.

**Comment by gauravbgp** [comment]
As mentioned in #1084 , kindly check out charts at [covid19rt.in](http://covid19rt.in/)

**Comment by jeremyphilemon** [comment]
Closing this to redirect everyone here to an earlier relevant issue, please discuss this in #1084

I'm aware this mentions it for state, but I'd like this to start at state level and iterate to district :)
