### ISSUE TITLE
Multi Lingual

### ISSUE THREAD

**Issue by sriram2403balajisriram** [covid19india/covid19india.github.io#1277]
**Describe the bug**
Language settings for all the languages used in india.

**To Reproduce**

1. Go to Home page
2. Click on English ,button is not working
4.See error

**Expected behavior**
Multiple language support of the app for the people of india.

**Screenshots**
![Screenshot_20200419-073257](https://user-images.githubusercontent.com/13765446/79677561-6d1e2080-8210-11ea-8b8d-a62a5c8f23d0.png)

**Desktop (please complete the following information):**
Checked in mobile browser.
I thought you understand the problem.
Support india. Jai Hind.

- OS: Android
- Browser - chrome
- Version Latest updated

**Smartphone (please complete the following information):**

**Additional context**

**Comment by JunaidBabu** [comment]
duplicate #432
