### ISSUE TITLE
Make the crowdsourced patient database available as a csv download

### ISSUE THREAD

**Issue by iy3r** [covid19india/covid19india.github.io#1278]
**Is your feature request related to a problem? Please describe.**
The patient database published as HTML from Google Sheets is now pretty heavy, over 22mb. A simple copy-paste into Excel for analysis is no longer easily possible and there are no other ways to access this data except as HTML. 

**Describe the solution you'd like**
Make the data available as a csv download.

**Describe alternatives you've considered**
https://www.reddit.com/r/googlesheets/comments/aymwjd/how_do_you_select_csv_output_for_individual/

**Comment by JunaidBabu** [comment]
https://api.covid19india.org/csv/
