### ISSUE TITLE
Visit State Link next to the State name on main table view.

### ISSUE THREAD

**Issue by jaykishanparikh** [covid19india/covid19india.github.io#1279]
**Is your feature request related to a problem? Please describe.**
Currently 'Visit state page' link is displayed once the State is clicked. This comes as a third column title after 'District' and 'Confirmed cases'

**Describe the solution you'd like**
The user has to expand the state and then click on this link. 
1) An additional click is required
2) The position of this link is more appropriate at the state level than inside state details.

**Describe alternatives you've considered**
Next to the State name, '>' icon that expands state details.

**Additional context**
Easy to do, just need a repositioning.

<img width="621" alt="Screen Shot 2020-04-19 at 3 33 57 pm" src="https://user-images.githubusercontent.com/17736902/79680521-e1c67e80-8253-11ea-8e90-9669b3f62359.png">

**Comment by lakshmi14** [comment]
![Enhancement (2)](https://user-images.githubusercontent.com/7721961/79688872-db91cb80-826e-11ea-97f1-dac38073702b.png)

Hi I have made a icon in the right side with a hover to know that it redirects to view state page. Let me know if I can proceed. Also i would like to take this enhancement

**Comment by jaykishanparikh** [comment]
Hi @lakshmi14  That's wonderful, but how about this.
We put that to each row on the main table. My experience with this page is user is very likely to go thorough table first (especially when they access from mobile as this table renders before the map).

See attached below.
![Uploading Screen Shot 2020-04-19 at 11.28.10 pm.png…]()

**Comment by lakshmi14** [comment]
We have implemented this? (You have closed this.)

I can add the view state next to the table. However, the problem would be in the mobile view. 

I am not able to view your screenshot as well. Can you share that again?
