### ISSUE TITLE
Incorrect Cases in Yavatmal, MH

### ISSUE THREAD

**Issue by amar2215** [covid19india/covid19india.github.io#1280]
Number of cases as shown for YAVATMAL DISTRICT OF MAHARASHTRA does not tally with Government data. 

Government Data shows 13-15 cases viz a viz 5 cases on this website.  

The same needs correction for proper presentation of data.

**Comment by jeremyphilemon** [comment]
Please report data discrepancies using this form https://forms.gle/7NRSrbspW2a6pbm58, thanks :)
