### ISSUE TITLE
Insecure Cross-Origin Resource Access Control 

### ISSUE THREAD

**Issue by PratikVGaikwad** [covid19india/covid19india.github.io#1283]
**At a Glance:**
Classification  : Information

Resource        : /manifest.json

Risk                : **High**

**Request:**

GET /manifest.json 

**Discussion:**
The resource has set an insecure** Cross-Origin Resource Sharing (CORS)** access control. CORS provides mechanisms that allow a server to restrict resource access for cross-site requests to certain trusted domains. The server in question has allowed resource from any origin by setting the value of the "Access-Control-Allow-Origin" response header to a wildcard value. This presents a security risk because any site can issue requests to access resources, regardless of origin. 

**Desktop (please complete the following information):**

- OS: Windows
- Browser : Chrome

**Remediation:**
Set the "Access-Control-Allow-Origin" response header to **allow access from trusted domains only**. Do not allow access from arbitrary domains.

**References:**
Some additional links with relevant information published by third-parties: 
[https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS](url)

Thank you for your consideration,
Best Regards,
Pratik Gaikwad.

**Comment by JunaidBabu** [comment]
We are using github pages to host the website.
How do you suggest we make this change in our case?
