### ISSUE TITLE
Line graph for daily cases in deep dive section.

### ISSUE THREAD

**Issue by shubhamjain2998** [covid19india/covid19india.github.io#1285]
**Is your feature request related to a problem? Please describe.**
Daily cases graph in the deep-dive section is not that much informative in the first look.

**Describe the solution you'd like**
If there is a line graph instead of a bar graph then it will provide a lot of information to the users, like they will be able to see clearly at which date new cases are in its peak, and also help analysts to observe if the trend is going down or not. It will also not look a little bit congested like the current bar graph.

**Additional context**
Assign this issue to me if it feels relevant, I have tried to implement it and here's a look.
It clearly shows the daily trend.

![Screenshot from 2020-04-19 13-09-43](https://user-images.githubusercontent.com/30628775/79683110-5940e180-8245-11ea-82a5-eec3f45525ae.png)

**Comment by pulakchakraborty** [comment]
It's a good suggestion in my opinion. In addition, I also feel that the use and visualization of the new _active_ cases per day in the current chart is a bit odd. _Confirmed_ new cases is more relevant from the visualization aspect.

**Comment by anuragsetia** [comment]
Lines for Confirmed, Recoveries and Deaths should be independent and not have additive effect as visible in the image. See how the top line is going upto 1400 almost when 1062 cases have been confirmed. This can be a problem when high number of recoveries happen on a day and the graph will still be going upwards.

**Comment by shubhamjain2998** [comment]
@anuragsetia I totally agree with you, but in this line graph **lines are independent**, unlike previous bar graph lines are not stacked here, it may have confused you because of the background color.
let me show you a more clear example.
![Screenshot from 2020-04-20 15-35-36](https://user-images.githubusercontent.com/30628775/79740012-9fb53f80-831c-11ea-955b-7fa1749ad6c4.png)
just see the tooltip, if the graph would be stacked then the tip of new cases will be lying to around 1900(1580 + 388 + 38), hope there is no confusion now.

**Comment by anuragsetia** [comment]
That does clarify it. However, if the lines are not additive, its good practice for clear understanding sake not to have the area under the line shaded.

**Comment by shubhamjain2998** [comment]
thanks for the feedback, i will keep this in my mind, let the maintainers also give their views in this and will apply final changes after that.

**Comment by shubhamjain2998** [comment]
@jeremyphilemon @shuklaayush Please have a look at this.

**Comment by JunaidBabu** [comment]
@shubhamjain2998 please raise a PR with your solution.

**Comment by shubhamjain2998** [comment]
@JunaidBabu please review the PR. Also, can I close the PR #1284 now?
