### ISSUE TITLE
Inaccuracy in map

### ISSUE THREAD

**Issue by skandtandon** [covid19india/covid19india.github.io#129]
![Screenshot (53)](https://user-images.githubusercontent.com/21158496/77574078-97254100-6ef7-11ea-83aa-78f9c0fc3c09.png)
Inaccuracy in map , there is this small gap between borders of gujrat  and maharashtra that's Dadar and Nagar Haveli .
List of left out uts/states are:
1)Andaman and Nicobar
2)Chandigarh
3)Daman and Diu
4)Dadar and Nagar Haveli
5)Lakshadweep

Please map them on the map cause in future cases might come from there also

**Comment by shuklaayush** [comment]
It's all there. It's just that they are difficult to select with a cursor since they are tiny. Maybe addressing #119 could help.

**Comment by jeremyphilemon** [comment]
@JunaidBabu Thoughts on the not being able to click on tiny polygons, we add a zoom in?

**Comment by radhasatam** [comment]
Addressed Issue #119  with PR #137

**Comment by shuklaayush** [comment]
This has been pretty well addressed by #352. Don't see a point in adding zoom functionality since the map for the state/UT can instead be expanded by hovering/tapping on the table. Closing
