### ISSUE TITLE
Change the state row colour to green if all the active cases have been recovered.

### ISSUE THREAD

**Issue by Sanskar95** [covid19india/covid19india.github.io#1291]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by nayakrahul** [comment]
You mean that when there are zero active cases. We can display a green dot in the row in such case.

**Comment by Sanskar95** [comment]
Not a green dot as such , but changing the whole row colour from grey to green

**Comment by JunaidBabu** [comment]
Will consider later.
