### ISSUE TITLE
Issue with the Graph while selecting the Kerala as state [Desktop View][Mobile View]

### ISSUE THREAD

**Issue by amittttt** [covid19india/covid19india.github.io#1292]
**Describe the bug**

**To Reproduce**

1. Go to 'https://www.covid19india.org/'
2. Click on 'over on kerala'
3. see the graph is negative values 

[desktop] [mobile] both have the issues 

![image](https://user-images.githubusercontent.com/18753303/79686291-f9563500-825c-11ea-9f7c-155d8ce8e2f2.png)

**Comment by amittttt** [comment]
I want to work on the issue if you will give me the permission :)

**Comment by JunaidBabu** [comment]
It's because the delta of daily-active is negative.

**Comment by amittttt** [comment]
yes, agree ... as a user what do you think?
Active negative values refer what :(
