### ISSUE TITLE
Incorrect spelling of Ahmedabad state under Gujarat

### ISSUE THREAD

**Issue by makjn10** [covid19india/covid19india.github.io#1294]
**Describe the bug**
Spelling mistake.
Ahmedabad is being shown as Ahmadabad.

**Desktop (please complete the following information):**

- OS: [Windows]
- Browser [Chrome]
- Version [81.0.4044.113]

**Comment by shuklaayush** [comment]
Please refer to this https://github.com/covid19india/covid19india-react/issues/662#issuecomment-609377552
