### ISSUE TITLE
Need API based on Area Input

### ISSUE THREAD

**Issue by pvarma8** [covid19india/covid19india.github.io#1297]
API should pull data based on area input.

For Example. using below API we can able to pull State and District wise data.

https://api.covid19india.org/v2/state_district_wise.json

Similar way if we can pull data based on AREA ie District Name would be good, Something like below: 
https://api.covid19india.org/v2/DistrictName.json 
https://api.covid19india.org/v2/Hyderabad.json should give Hyderabad Data.

**Comment by JunaidBabu** [comment]
The data size isn't that huge at the moment. It's easy to get all the data once and then use ones you need from https://api.covid19india.org

Also please raise api related issues at https://github.com/covid19india/api
