### ISSUE TITLE
Website Doesnt Work on IE

### ISSUE THREAD

**Issue by gyanendrapatro** [covid19india/covid19india.github.io#1299]
**Describe the bug**
The website doesn'y show anything on IE it only shows blank screen.
**To Reproduce**

**Expected behavior**
Either i should see the page or else as i know few things doesnt work in IE then atleast i should get a message saying we dont support IE message as users wont think that site is down.
**Screenshots**

**Desktop (please complete the following information):**
- Browser [IE]

**Additional context**

**Comment by JunaidBabu** [comment]
Sorry, the solution is to not use IE
