### ISSUE TITLE
Support District Level Maps

### ISSUE THREAD

**Issue by jeremyphilemon** [covid19india/covid19india.github.io#13]
As shown in the preview:

<p align="center">
<img width="391" alt="Screen Shot 2020-03-22 at 9 44 12 PM" src="https://user-images.githubusercontent.com/17938322/77257577-4a86ff00-6c86-11ea-90a5-1fb37d271963.png">
</p>

**Comment by manojVivek** [comment]
@jeremyphilemon Can you point me where we can get the district level topoJsons for India?

**Comment by jeremyphilemon** [comment]
https://github.com//guneetnarula/covid19-in @manojVivek this is a good place to start!

**Comment by JunaidBabu** [comment]
https://api.covid19india.org/state_district_wise.json can be used to fetch the data.

@manojVivek thanks for this!

**Comment by Goutham88** [comment]
Can I take this or someone is working on this?
@jeremyphilemon

**Comment by manojVivek** [comment]
I'm working on this.

**Comment by akumars0** [comment]
@manojVivek i can help with any QA support you might need

**Comment by JunaidBabu** [comment]
> I'm working on this.

@manojVivek any updates on this?

**Comment by manojVivek** [comment]
@JunaidBabu Making progress, will raise a PR by today evening.

**Comment by manojVivek** [comment]
@jeremyphilemon @JunaidBabu Just realized, I didn't see the attached screenshot in this issue and took a different approach UX wise. Please check the screencast below and let me know. 
 Screencast: 
 ![Screen Recording 2020-03-25 at 11 42 30 AM 2020-03-25 11_49_09](https://user-images.githubusercontent.com/1283424/77507558-aae88d00-6e8e-11ea-8748-6a0bdb4341cc.gif)

**Comment by JunaidBabu** [comment]
@manojVivek 

This is awesome.. if you have this one production ready, please submit PR.

We can also do the initial plan alongside; to have a toggle button to see the whole picture district-wise

What's the plan to display unknown cases?
How big is the geojson for districts?

**Comment by manojVivek** [comment]
@JunaidBabu The geojson size ranges from 50KB to 900KB non-gzipped. 

Shall I raise a PR with few states missing(I'm filing in the geoData state by state)? 
So that someone else can do the implementation of initial plan in parallel?

**Comment by JunaidBabu** [comment]
> Shall I raise a PR with few states missing(I'm filing in the geoData state by state)?

Yes please

**Comment by manojVivek** [comment]
PR #88

**Comment by aadityadar** [comment]
PS: if possible please use district boundaries either from Census 2011 (640 districts; see https://github.com/datameet/maps/tree/master/Districts/Census_2011) or present-day districts (729 as per https://lgdirectory.gov.in). LG directory provides a mapping of all 729 districts in 2020 to 2011 census district codes and therefore it's easier to bring in data from other sources. Here's the csv file https://github.com/aadityadar/covid-19-india-lockdown/blob/master/input/lgdirectorygovin_allDistrictofIndia2020_03_26_01_50_14_830.csv

**Comment by suryaceg** [comment]
One idea for the interaction would be.

Desktop:
Hover on state > Show a small tooltip along with the state % "View district-wise breakup" > On click > Expose the district > Back button as shown to go back to State map

Mobile:
On top > Show state name & data as shown in Issue #90 & show a call-to-action "View district-wise breakup" > On click > Expose the district > Back button as shown to back to State map

CC: @JunaidBabu @jeremyphilemon @manojVivek @s-naveen

**Comment by ghost** [comment]
Can I also work on this?

**Comment by jeremyphilemon** [comment]
Closed! 🎉 #88
