### ISSUE TITLE
Adding testing graphs on Home and State Page

### ISSUE THREAD

**Issue by jaykishanparikh** [covid19india/covid19india.github.io#1301]
**Is your feature request related to a problem? Please describe.**
We are already showing the number of testing done along with total cases, active, recovered and Deceased  number. These are also displayed in graphs below.

**Describe the solution you'd like**
Adding a graph after Deceased number would help to understand increasing number of testing per day. Testing is one of the most important numbers to fight against pandemic. More testing means more efficiency to limit the spread.

**Additional context**
We already have graphs created. Adding this graph would be following the same code. 

<img width="505" alt="Screen Shot 2020-04-19 at 11 36 25 pm" src="https://user-images.githubusercontent.com/17736902/79689298-2e7f7900-8297-11ea-835b-0de829a04ed8.png">

**Comment by jaykishanparikh** [comment]
Along with this, the percentage of death and recovery rate could be very important data. For example, India's death rate was 23% that have now limited to around 17% that is very positive sign and relief to the people.

Closed cases = Total Death + Total Recovered
Death rate = Total Deaths * 100 / Closed cases

**Comment by dhanjit** [comment]
@jaykishanparikh the no. Of tests column doesn't exist.
![Screenshot_20200419-220617_Chrome](https://user-images.githubusercontent.com/2098349/79693744-2967fd00-828a-11ea-8334-1c2e1a0951a6.png)

**Comment by jaykishanparikh** [comment]
> @jaykishanparikh the no. Of tests column doesn't exist.
> ![Screenshot_20200419-220617_Chrome](https://user-images.githubusercontent.com/2098349/79693744-2967fd00-828a-11ea-8334-1c2e1a0951a6.png)

@dhanjit 
It's down to the Map view.

<img width="191" alt="Screen Shot 2020-04-20 at 12 45 29 pm" src="https://user-images.githubusercontent.com/17736902/79709229-0169af80-8305-11ea-9d79-0c1df689773f.png">

**Comment by jaykishanparikh** [comment]
Plz assign this to me.

**Comment by jaykishanparikh** [comment]
My approach
- Update in https://api.covid19india.org/data.json API to return totalTested.
- Update timeseries.js to add one more graph (chartKey5)
- Add required variables in timeseries.js
