### ISSUE TITLE
Cards on deepdive are touching navbar. Make it centered

### ISSUE THREAD

**Issue by ghost** [covid19india/covid19india.github.io#1303]
On Deepdive page the cards are not centered and touching navbar on left. Center the cards container.
![imageedit_3_4302082151](https://user-images.githubusercontent.com/29702340/79690164-9ec9d280-8276-11ea-9cd5-8956fba9b08a.gif)

**Comment by avneeshroks** [comment]
I would like to work on this. Please assign this to me. PR : https://github.com/covid19india/covid19india-react/issues/1303
