### ISSUE TITLE
Adding Google Translator API for Hindi

### ISSUE THREAD

**Issue by ahmadtaquee** [covid19india/covid19india.github.io#1308]
**The website shows the contents only in English. What about if a person wants in Hindi, as Hindi is the native language of India.**

So, to overcome this problem, we can add Google Translator API which translates the website contents to any preferred language.

I already change in Google Translator API code to show the content in Hindi and English only.

Here is the screenshot!!!
**The only problem is that, not able to style the widget in a proper place.**
![image](https://user-images.githubusercontent.com/24306822/79694095-fcb4e500-828b-11ea-86f0-dee838cbb706.png)

**Comment by ahmadtaquee** [comment]
Please assign it to me.

**Comment by Ekaanth** [comment]
Hi,
Why restrict to Hindi? since adding translate is a one-time thing while we can add all the other official languages thus making it helpful for everyone.

**Comment by ahmadtaquee** [comment]
Hi @Ekaanth,
Your opinion is right, will add other languages too.

**Comment by jeremyphilemon** [comment]
Closing in favor of #432, this is in the works
