### ISSUE TITLE
menu sidebar scroll on mobile screen 

### ISSUE THREAD

**Issue by gyanendrapatro** [covid19india/covid19india.github.io#1311]
**Describe the bug**
the menu bar in mobile phone when you click the sidebar is scrollable but it doesnt cover the whole screen its half way so it creates a problem, like i am seeing half menu info and half the back page info.
even if you scroll down you wont be able to close the sidebar as the close button goes up when you scroll.
**To Reproduce**

1. Go to 'mobile'
2. Click on 'menu'
3. Scroll down to the options then you will see half the sidebar of menu ends and main page starts from half
![image](https://user-images.githubusercontent.com/13833855/79695708-07747780-8296-11ea-8d77-2e6e5f514c2b.png)

**Expected behavior**
so the behavior should have been the side menu bar when you scroll also it should only show the menu options thing  it shoul not show the main page after half scroll.
or else when you half scroll and the scrolling sidebar menu options are over if you click below to that it should close automatically the menu sidebar.
so we can keep the close fixed at top when you make the sidebar full screen or after the sidebar area is done if you click anywhere automatically it closes.
**Screenshots**
![image](https://user-images.githubusercontent.com/13833855/79695770-54f0e480-8296-11ea-8558-cc40aa98f80c.png)

**Smartphone (please complete the following information):**

- Device: [any device]
- Browser [any]

**Additional context**

**Comment by gyanendrapatro** [comment]
if the issue needs to be fixed please do assign it to me i can fix it

**Comment by jeremyphilemon** [comment]
Patched in #1364
