### ISSUE TITLE
top navbar and menu button open should be fixed in mobile

### ISSUE THREAD

**Issue by gyanendrapatro** [covid19india/covid19india.github.io#1312]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.
so in mobile the top navbar and menu button should be fixed as its the navigation to all pages
**Describe the solution you'd like**
we can fix the navbar for mobile screens where the main covidindia link and menu button are there.
that should be fixed as it will help us to navigate to any page any section even if you scroll down in a page.
we need to fix the menu and navbar for mabile screens.

**Describe alternatives you've considered**

**Additional context**

**Comment by gyanendrapatro** [comment]
please do assign it to me so that i can fix the navbar for the navbar and menu button for easy navigation in mobile screen

**Comment by jeremyphilemon** [comment]
Addressed by #1477
