### ISSUE TITLE
daily active cases gone negative in timeseries graph

### ISSUE THREAD

**Issue by nayakrahul** [covid19india/covid19india.github.io#1313]
**Describe the bug**
Suppose no. of active cases decreases from day X to day Y. That means there is no addition to no. of active cases for day Y. So my point is : should we show negative value or zero in the daily active cases timeseries graph for day Y.

**To Reproduce**

1. Go to the state page of Tamil Nadu
2. Scroll down to timeseries graphs for Tamil Nadu
3. Choose daily button
4. Notice the active graph
_Note : There are other states too with such scenario._

**Expected behavior**
Should we show negative values or zero ?

**Screenshots**
![Screenshot (25)_LI](https://user-images.githubusercontent.com/11428805/79696564-fa0dbc00-829a-11ea-8b4c-b983fef68db9.jpg)

**Addional Context
Normally the cumulative graph of confirmed, recovered and deceased cases will always be increasing except active cases. So such case will only happen in active cases.

**Comment by nayakrahul** [comment]
You can assign it to me if you feel it to be relevant.

**Comment by shuklaayush** [comment]
What's the point of showing zero instead of negative values for change in active cases?

**Comment by Abhinav-Mani** [comment]
I agree with @shuklaayush. There is no point showing 0 in place of negative. 
I feel the daily active case has no significance, active cases should always be cumulative therefore the active case chart from daily should be removed .

**Comment by nayakrahul** [comment]
I agree with @Abhinav-Mani . Daily active cases chart doesn't make any sense. 
Let me explain with an example
On day 1, person A, B and C are confirmed positive and on day 2, person D and E are confirmed positive but A dies and B recovers. So for day 1, daily active cases is 3. And for day 2, daily active cases is 0 (by formula: confirmed - recovered - deceased) but actually there are 2 active cases added in day 2.

**Comment by shuklaayush** [comment]
I don't see what the confusion is. Active represents the number of people alive who have the virus right now. Thus, it captures the extent of the spread at this point in time. In your example, there were 3 such people on day 1, and on day 2, it remained at 3. Hence, the delta is 0. It makes perfect sense in my opinion.

**Comment by Abhinav-Mani** [comment]
@shuklaayush  in current version many states are showing -ve active cases. So if a state X shows -10 active case for 19 April 2020. Does this have any significance ? Or what does it mean?

**Comment by shuklaayush** [comment]
It means that the number of Active Covid-19 cases decreased by 10 on that day. This could be either because people recovered or because they died. 

The daily graphs don't represent "active cases for 19 April 2020". Rather, they represent the change in the total Active cases on 19 April 2020.

**Comment by nayakrahul** [comment]
In daily chart for confirmed cases, it shows the no. of confirmed persons in a day which is equal to the delta itself (cumulative for current day - cumulative for previous day). Same for recovered and deceased. But for daily active cases, it is just the delta or how much the total number of cases has increased or decreased by.

**Comment by shuklaayush** [comment]
Yes, exactly.
Please close this thread if there's no further confusion.

**Comment by jaibatrik** [comment]
@shuklaayush @nayakrahul I still think this is confusing. I think others also think in the same way (presumably so many issues are getting created because of that). My suggestion is to change the title of the chart from "Active" to "Change in active cases" when the "Daily" tab is selected.

**Comment by nayakrahul** [comment]
> @shuklaayush @nayakrahul I still think this is confusing. I think others also think in the same way (presumably, so many issues are getting created because of that). My suggestion is to change the title of the chart from "Active" to "Change in active cases" when the "Daily" tab is selected.

Actually, all the daily charts are change in _ cases only.

**Comment by jaibatrik** [comment]
Yeah, just that in case of "Active", it's a bit confusing with those negative numbers; which is why I was suggesting verbosity.

If you observe, the "Active" does not sit well in the daily category - it is the only metric that can go negative there. It does not really belong there.

**Comment by nayakrahul** [comment]
Adding a note using tooltip might be useful here.
