### ISSUE TITLE
Map border not visible in Microsoft Edge browser

### ISSUE THREAD

**Issue by rkkmmmkkr** [covid19india/covid19india.github.io#1316]
**Describe the bug**

**To Reproduce**

1. Go to 'Microsoft Edge browser and open this site '
2. Click on 'Sikkim on India map to view its district map'
3. only selected district is visible

**Expected behavior**
map border should be visible so that we can recognize it.

**Screenshots**
![sikkimmap](https://user-images.githubusercontent.com/20758161/79699455-5d084e80-82ad-11ea-9f52-f11032305785.PNG)

**Desktop (please complete the following information):**

- OS: Windows 10 Pro
- Browser Microsoft Edge
- Version 44.17763.1.0

**Comment by gyanendrapatro** [comment]
i saw it in microsoft edge chromiun there it works

**Comment by shuklaayush** [comment]
Closing this for now. Reopen if you're still facing the issue
