### ISSUE TITLE
why tibet is country?

### ISSUE THREAD

**Issue by sidealice** [covid19india/covid19india.github.io#1321]
Under the section of "PATIENT NATIONALITY" I found tibet is a country???

This is a seriouly problem.Wait your response.

UPDATEED:
You don't regard this is a seriouly problem and close without change anything? 
This really hurts other country people. 

I understand peoples suffers from the virus over the world.
At the beginning I'm worry about the India people and your life. But now ,haha.

Thank you change my mind, from now on India is nothing to me, I will never pay attention to you.

**Comment by tshrwbl** [comment]
Bohot accha kam krta he ye pados wala IT survillence.

**Comment by bee-rickey** [comment]
Free Tibet (ง •̀_•́)ง
