### ISSUE TITLE
Convert it to progressive web app

### ISSUE THREAD

**Issue by Surya1231** [covid19india/covid19india.github.io#1322]
The progressive web app will be very handy to use. People don't have to visit the website all the time they want to check status. They can easily install the website as an app in their android/ios devices. You can easily convert this website to a web app. ( progressive web app provide a banner for installing the website as an app in their phone )

Solution:
We need to just add a service-worker.js file in public/ directory and some additions in manifest.json will do it. it will not take that much time but it will create a great impact on users from my opinion.

Exact steps:

- create service-worker.js in public/ (Name should be exact same)
- Define an empty self.addEventListner("fetch" , () => ()) function like this for now.
- In maifest.json define orientation: "portrait primary" 
- In maifest.json add more icons ( 144x144, 512x512).

**Comment by Abhinav-Mani** [comment]
I think its possible to create shortcut to website from browser and add it to home screen. Then directly visit the site.

**Comment by ron2911** [comment]
I am already using it that way on iOS since more than a couple weeks. Works fine for me.

**Comment by shuklaayush** [comment]
Hey @Surya1231, seems like you have it figured out. Can you please comment on #758 and close this? It's easier for us to track

**Comment by jeremyphilemon** [comment]
So for starters, let's start with showing the "add to homescreen" banner. If there's anything else we can add to this and use the power of PWAs to extend a functionality, please feel free to open a new issue addressing that.

**Comment by strikertanmay** [comment]
We can do many kinds of stuff to promote PWAs. This article https://web.dev/promote-install/ will help us to explore other ways as well.
