### ISSUE TITLE
West Bengal Database Related 

### ISSUE THREAD

**Issue by shekzek** [covid19india/covid19india.github.io#1323]
Hey' My Friends Here The States Of West Bengal Have Own Health Care Web Which Have Update Daily For Covid-19 Reports Officially.
For Information:- 
https://www.wbhealth.gov.in/pages/corona/bulletin
#Kalibaba-Pro

**Comment by animesh-tarodia-sp** [comment]
@Kalibaba-Pro The west Bengal bulletin doesn't include total number of positive cases but it only includes active cases in the state.

**Comment by shekzek** [comment]
Hey' My Bro..... Let's Play Some Calculations.
if, Total Number = x
        Active case = y
         Recovered = z
         Deceased = d
so,
x = ( y + z + d)
therefore 
   Total Number = Active case + Recovered + Deceased
:: Total Number = Confirmed.
Thank You.
#Kalibaba-Pro

**Comment by animesh-tarodia-sp** [comment]
I totally agree with u but when you compare mohfw data and bulletin data there is so much difference.

**Comment by jeremyphilemon** [comment]
Please report data discrepancies in this form https://forms.gle/7NRSrbspW2a6pbm58, thanks :)
