### ISSUE TITLE
District wise confirmed cases in state details page

### ISSUE THREAD

**Issue by vivekvroy** [covid19india/covid19india.github.io#1324]
When we go into the details of a particular state for example
[https://www.covid19india.org/state/KA](url) or
[https://www.covid19india.org/state/MH](url)

It will be good to have a table of districtwise numbers like below table.
![image](https://user-images.githubusercontent.com/10249914/79718308-5acbe180-82f9-11ea-888f-be72bebbc7e4.png)

It will be even better when we have a more detailed view like this.
![image](https://user-images.githubusercontent.com/10249914/79718442-b4cca700-82f9-11ea-8d5f-6acc1932255a.png)
The above table screenshot is taken from the source that you are referring to for karnataka numbers ([https://covid19.karnataka.gov.in/storage/pdf-files/Media-Bulletin/19-04-2020-05-00-English.pdf](url))
So, I hope that the data is available but it should just be put in proper format to get that kind of table.

**Comment by gilsedition** [comment]
Yes, this will give a more in-depth view, good suggestion @vivekvroy

**Comment by jeremyphilemon** [comment]
So essentially we're gonna do this like this:

Instead of having a table, we're already showing the top ~6 districts with their deltas and confirmed values. We can have a "view all" button below it to show the rest of the values. The rest of the values would then wrap column wise, pushing the bar graph below :)

**Comment by kousiksatish** [comment]
I would like to /claim this

**Comment by kousiksatish** [comment]
@jeremyphilemon When I do it as you suggested, there are lot of columns of districts which actually mess the view
![Screen Shot 2020-04-25 at 1 15 22 PM](https://user-images.githubusercontent.com/6641694/80274283-e4632100-86f6-11ea-914f-9f662175d275.png)
![Screen Shot 2020-04-25 at 1 15 17 PM](https://user-images.githubusercontent.com/6641694/80274284-e7f6a800-86f6-11ea-96c4-1f9e0ce5e56e.png)

I have made a PR with a basic design as you suggested. You can suggest updates.

We can only fit in maybe 3-4 columns of districts, which is approx 18-24 districts.
Please suggest what to do when number of districts are more.

**Comment by nayakrahul** [comment]
How about implement a carousel for it? Partition all the districts and view them by using carousel.
