### ISSUE TITLE
DatePicker Bugs

### ISSUE THREAD

**Issue by Binu42** [covid19india/covid19india.github.io#1326]
**Describe the bug**
* select date input and date of data shown is not matching when demographics component mount.
* user can enter invalid date input.
* on click of input in date picker (in mobile) keyboard is opening which is awful.

**To Reproduce**

1. Go to Demographic page and see select date in empty.
2. Click on select date and type anything from keyboard.

**Expected behavior**
* on mount select date and data shown date must match
* keyboard input should be restricted to entry of invalid dates.
* only date picker should open in mobiles after click of date picker input not keyboard.

**Screenshots**
#### on opening demographics page select date is empty and it's showing data of one day back.
![Screenshot from 2020-04-20 11-59-40](https://user-images.githubusercontent.com/45959932/79720627-8d2c0d80-82fe-11ea-9dee-94e1f95be6af.png)

#### entry on invalid date
![Screenshot from 2020-04-20 11-54-22](https://user-images.githubusercontent.com/45959932/79720244-cc0d9380-82fd-11ea-9141-a459b0888606.png)

#### keyboard opening in mobile view
![WhatsApp Image 2020-04-20 at 9 57 25 PM](https://user-images.githubusercontent.com/45959932/79776110-dad26580-8352-11ea-9d8a-e2c96132b0e4.jpeg)

**Desktop (please complete the following information):**

all OS, all Browser and all versions.

**Smartphone (please complete the following information):**

- Device: [all]
- OS: [all]
- Browser [all]
- Version [all]

i have raised PR #1327  to fix this issue.

**Comment by nayakrahul** [comment]
All problems related to disallowed or invalid dates can be fixed by not allowing to manually type the dates in input field.

**Comment by Binu42** [comment]
> All problems related to disallowed or invalid dates can be fixed by not allowing to manually type the dates in input field.

that's what i did on PR #1327

**Comment by nayakrahul** [comment]
Oh ! And you set the default to yesterday's date.

**Comment by Binu42** [comment]
> Oh ! And you set the default to yesterday's date.

yeah, otherwise when demographics page get mounted select date is empty and showing patients data for yesterday's doesn't make sense.
