### ISSUE TITLE
Deep Dive - Daily cases

### ISSUE THREAD

**Issue by anuragsetia** [covid19india/covid19india.github.io#1330]
**Describe the bug**
The chart shows new cases, recoveries and deaths in a single bar demonstrating the additive effect of them which is wrong. E.g. when the new cases reduce and the recoveries increase, it might still show a tall bar.

**To Reproduce**

1. Go to 'https://www.covid19india.org/deepdive'
2. See error on center chart on top of the page

**Expected behavior**
There should be separate bars for new cases, recoveries and deaths

**Screenshots**

![image](https://user-images.githubusercontent.com/15847056/79728644-e189ba00-830b-11ea-911e-1fff64b7eabc.png)

**Comment by shubhamjain2998** [comment]
@anuragsetia refer to this suggestion #1285 , if this gets maintainers approval then this bug will also get resolved. or if there is any other better way to solve then please mention as I am already working on this graph.

**Comment by anuragsetia** [comment]
Had a look and #1285 does not address this issue either. It only converts the bar to lines with retention of the same error
