### ISSUE TITLE
Date Picker issue: Clear button not working/freezes

### ISSUE THREAD

**Issue by Vadi91** [covid19india/covid19india.github.io#1332]
**Describe the bug**
Date Picker issue: Clear button not working/freezes

**To Reproduce**

1. Go to 'Menu > Demographics'
2. Update date 12/12/2019

**Screenshots**
![image](https://user-images.githubusercontent.com/16251338/79729359-fd419000-830c-11ea-9392-8dfc56ae63cc.png)

**Desktop (please complete the following information):**

- OS: [Windows]
- Browser [Chrome]
- Version [80.0.3987.163 (Official Build) (64-bit)]

**Smartphone (please complete the following information):**

**Comment by nayakrahul** [comment]
The problem occurs when we type in dates which are not allowed. All problems related to disallowed or invalid dates can be fixed by not allowing to manually type the dates in input field.

**Comment by SmritiRao17** [comment]
There is an open issue in react-date-picker for this.
[Issue Link](https://github.com/wojtekmaj/react-date-picker/issues/247)

**Comment by jeremyphilemon** [comment]
Looks like this has been sorted out in our codebase :P
