### ISSUE TITLE
Map is flickering on moving mouse between Sikkim and West bengal 

### ISSUE THREAD

**Issue by sumukhah** [covid19india/covid19india.github.io#1334]
**To Reproduce**
Move the mouse from Sikkim to West Bengal.

**Screenshots**
![ezgif-3-618435aebf07](https://user-images.githubusercontent.com/23723464/79742113-f7a17580-831f-11ea-8608-20e6ac4b53da.gif)

- Browser  chrome

This error may be raised because of some styling issue, 
selecting west Bengal needs more space in the result cards, so the map will move down,
hovering Sikkim moves the map up, as it does not need much space in result cards

**Comment by Ekaanth** [comment]
Hi, 
I just checked on Brave browser there is no flickering when moved from Sikkim to WB

**Comment by shuklaayush** [comment]
Seems to be fixed
