### ISSUE TITLE
x-axis on spread trends shifts to top leaving non-perpendicular structure 

### ISSUE THREAD

**Issue by meetzaveri** [covid19india/covid19india.github.io#1335]
**Describe the bug**
The x-axis of graph of any state in spread trends section shifts to top, leaving non-perpendicular structure. This happens when I am in Daily tab and I switch to uniform for specific state in spread trends section(home page)

**To Reproduce**
1. Go to Home Page
2. Click on any state and its daily tab
3. Scroll down to see graph and check x-axis
4. See the design error

**Expected behavior**
x-axis should remain perpendicular to y-axis in graph

**Screenshots**
Here is GIF
![chrome-capture (10)](https://user-images.githubusercontent.com/21293048/79748954-eeb6a100-832b-11ea-9965-e8d2744066ec.gif)

Screenshot
![chrome-capture (8)](https://user-images.githubusercontent.com/21293048/79748982-f9713600-832b-11ea-952d-25a97a648b55.jpg)

**Desktop (please complete the following information):**

- OS: Linux
- Browser: Chrome
- Version:80.0.39

**Comment by meetzaveri** [comment]
@jeremyphilemon @shuklaayush 
Hey, it fixed the current issue.

But issue now persists in "active cases" graph. Below is the screenshot.
![chrome-capture (9)](https://user-images.githubusercontent.com/21293048/79828786-10ad3380-83bf-11ea-94de-c093c3d76f37.jpg)

**Comment by shuklaayush** [comment]
@meetzaveri Could you explain what exactly the issue is? Everything looks perpendicular to me

**Comment by meetzaveri** [comment]
Some of the states, when I hover on them, the "active" cases graph's x-axis moves to the top as shown in screenshot above. 

For eg. Hover over "Odisha" and you will see the effect.

**Comment by shuklaayush** [comment]
The change in Active cases is negative for some dates, so we've added an extra zero axis to highlight the change from positive to negative. It is this zero axis that moves up and down.

**Comment by meetzaveri** [comment]
Okay. Sounds perfect then!
