### ISSUE TITLE
Negative number of cases in spread trends

### ISSUE THREAD

**Issue by SachinRammoorthy** [covid19india/covid19india.github.io#1337]
**Describe the bug**
In the daily spread trends for many states, the number of active cases on various dates is negative.

**To Reproduce**
1. Click on Karnataka
2. Click on 'Daily' in the Spread Trends section
3. Scroll down to the Active cases graph

**Expected behavior**
A positive number

**Screenshots**
![Screen Shot 2020-04-20 at 6 12 01 PM](https://user-images.githubusercontent.com/20569603/79753012-dd24c780-8332-11ea-9881-606889ebf715.png)

**Desktop (please complete the following information):**

- OS: macOS
- Browses: Chrome
- Version: 81.0.4044.113

Error occurs on all devices.

**Comment by shuklaayush** [comment]
Please refer to the discussion in #1313, and comment over there if you still have any confusion
