### ISSUE TITLE
Code Suggestion

### ISSUE THREAD

**Issue by pavan-shipmnts** [covid19india/covid19india.github.io#1338]
https://github.com/covid19india/covid19india-react/blob/29de2a7670f250cadb4ac47a9e262128ac1f3495/src/App.js#L18
This should be written outside of the function as it's independent of it.

**Comment by vishwac09** [comment]
Please create a PR if you have suggestions/enhancements for the current code. Try to find more and avoid creating issues for single changes. Find more and combines them according to features like State, Demographics, Deep dive etc. Creating multiple issues as per features is ok but please avoid creating 1 per change :).

**Comment by pavan-shipmnts** [comment]
Creating a PR with changes. Thanks 👍

**Comment by shuklaayush** [comment]
No point in creating a separate issue for this. Looking forward to your PR
