### ISSUE TITLE
Caption to explain uniform and logarithmic

### ISSUE THREAD

**Issue by gauravkhuraana** [covid19india/covid19india.github.io#1339]
**Is your feature request related to a problem? Please describe.**
Technical term which everyone would not know i.e. Logarithmic and Uniform

**Describe the solution you'd like**
If taking our cursor over it explains what it is or a link to some site which can explain in detail

**Describe alternatives you've considered**
A link to explain the idea in detail. A small one liner to explain it there itself 

**Additional context**
below image shows the details where we need to see what is this 
![image](https://user-images.githubusercontent.com/15048211/79760460-b8821d00-833d-11ea-92e7-49e48b8acb4a.png)

**Comment by bootleg-icarus** [comment]
Would like to work on this. Please assign.

**Comment by bee-rickey** [comment]
@bootleg-icarus what description will you provide? And where?

**Comment by bootleg-icarus** [comment]
@bee-rickey The description would be visible on hover over the switches ( with a delay of say 300ms )
### uniform 
- ( if it's **off** ) Turn on to make Y-axes in all graphs match the same range
(Additional info  - this might make the graphs with comparatively smaller numbers seem flatter )
- ( while it's **on** ) Turn off to make Y-axes adjust to their own highest ranges 
(Additional info  - this might make all graphs look like they're on a similar trajectory )
### logarithmic 
- ( if it's **off** ) Turn on to make the Y-axes steps jump with powers of 10
( Additional info - if the graph line is going straight up, it still means the numbers are exponentially increasing )
- ( if it's **on** ) Turn off to make the Y-axes steps increase linearly 
( Additional info - numbers are increasing exponentially if the graph line is curled upwards ) 

I think the additional info is not necessary but something like that could be viewed when the user clicks a 'see more ' button (or link) on the pop-up.

**Comment by jeremyphilemon** [comment]
This sounds good, you can use react-tooltip already present to get this working. A hover over the labels would ideally present this info.
