### ISSUE TITLE
Updates detail showing in previous version

### ISSUE THREAD

**Issue by SREERAGI18** [covid19india/covid19india.github.io#1343]
**Is your feature request related to a problem? Please describe.**
A No. but it was nice when details of the updates were shown in written form.

**Describe the solution you'd like**
A bring it back, please.

**Comment by jeremyphilemon** [comment]
Do you mean this, this is currently present in the website, you just have to click the bell icon to expand it!

<img width="504" alt="Screen Shot 2020-04-20 at 9 42 02 PM" src="https://user-images.githubusercontent.com/17938322/79787513-ca6cbb80-834f-11ea-9912-39144420c421.png">

**Comment by SREERAGI18** [comment]
yes thanks you....just saw it...!!!
