### ISSUE TITLE
Tested number for Tamil Nadu is not correct or inconsistent with whole India numbers

### ISSUE THREAD

**Issue by sriramsridar** [covid19india/covid19india.github.io#1344]
**Describe the bug**
For whole India, the details above India map shows the Tested numbers based on the number of people tested from the ICMR Status Update report and not the number of samples tested, since there can be repeat samples. But Tamil Nadu "Tested" numbers are showing Number of Samples tested. Please have "Total Number of persons tested today/ till date" for Tamil Nadu since that excludes repeat samples.

https://icmr.nic.in/sites/default/files/whats_new/ICMR_testing_update_19April_9PM_IST.pdf
https://stopcorona.tn.gov.in/wp-content/uploads/2020/03/Media-Bulletin20.04.2020.pdf

**To Reproduce**

1. Go to 'https://www.covid19india.org/'
2. Don't click any states, don't hover the mouse towards India map on the right. 
3. Look at the column "Tested" in the table. 
![India Testing Numbers](https://user-images.githubusercontent.com/63880180/79789684-94f8ab80-8318-11ea-8cc6-05ed44d4fc97.JPG)
4. Click the chain icon in the top right.
https://icmr.nic.in/sites/default/files/whats_new/ICMR_testing_update_19April_9PM_IST.pdf
4. Now hover the mouse to Tamil Nadu and check the numbers.
https://stopcorona.tn.gov.in/wp-content/uploads/2020/03/Media-Bulletin20.04.2020.pdf

**Expected behavior**
The numbers need to be consistent. Either both India and Tamil Nadu state numbers should show Total Samples tested (including repeat samples) or both should show Total number of persons tested. Total number of persons tested is better since that excludes duplicates.
![TN Numbers](https://user-images.githubusercontent.com/63880180/79789984-09cbe580-8319-11ea-94dd-77a9b4e8d5a3.JPG)

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser : Chrome
- Version : 80.0.3987.163

**Smartphone (please complete the following information):**

**Additional context**

**Comment by bee-rickey** [comment]
Valid point. If the data on number of people tested is available that should be used @sudevschiz thoughts?

**Comment by jeremyphilemon** [comment]
Please report data discrepancies in this form https://forms.gle/7NRSrbspW2a6pbm58, thanks :)
