### ISSUE TITLE
Hoveringover on Goa in the map shows 0.04 from goa ? It has total confirmed cases == total recovered cases,

### ISSUE THREAD

**Issue by bharatmakhija** [covid19india/covid19india.github.io#1345]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by bharatmakhija** [comment]
Hoveringover on Goa in the map shows 0.04 from goa ? It has total confirmed cases == total recovered cases.
When someone visits the website and hovers over on map and it shows 0.04 from goa, the first impression for this is number of infected patients in state  to the patients in entire country. Is this what 0.04 is ?, if so it should show 0 percent as currently there are no active patients in goa. 
If Not, if it just considers the number of patients ever confirmed irrespective of recovered then is it informed anywhere on website ? If not, It should be added in faq or something, as this information might be misleading. 

tested on chrome browser: latest version

![goainfocovidindia](https://user-images.githubusercontent.com/13132739/79803999-ba210480-8380-11ea-9491-79bdddedbf5f.jpeg)

Sorry for the image distorting as it was taken from my phone, hover window goes away on taking screenshots.

**Comment by gyanendrapatro** [comment]
you can assing this to me i can fix it with extra information showing the current status as well
and also planning to change the color to green which ever state has recovered fully

**Comment by gyanendrapatro** [comment]
![IMG_20200421_225646](https://user-images.githubusercontent.com/13833855/79895026-e346a100-8423-11ea-8d08-05cb0f1647a2.jpg)
![IMG_20200421_225659](https://user-images.githubusercontent.com/13833855/79895043-e9d51880-8423-11ea-9fae-a60ed03b850a.jpg)

Here is the fix which has better explanation and even i was planning to change the color of states to green if they have 0 active.
do let me know if this helps will give a PR

**Comment by gyanendrapatro** [comment]
![image](https://user-images.githubusercontent.com/13833855/79896957-a6c87480-8426-11ea-9408-1469792a8bef.png)
also indicating states with green which has 0 active cases

**Comment by bee-rickey** [comment]
This has to be discussed. Current hover is for total positives the state contributes across the nation. If we are moving towards providing active cases, in that case the behavior has to change across all the states. Closing this bug as of now. If you want a map for active cases, please raise an enhancement for that. We can have the behavior discussions there.
