### ISSUE TITLE
API is down

### ISSUE THREAD

**Issue by abhinav-superlativegaming** [covid19india/covid19india.github.io#1349]
**Describe the bug**

**To Reproduce**

1. Go to https://www.covid19india.org/
2.State-wise data is not coming
3.https://api.covid19india.org/state_district_wise.json is down
![covid19](https://user-images.githubusercontent.com/62693741/79825377-7ba63c80-83b6-11ea-9249-cbdb4c247231.jpg)
![covid19](https://user-images.githubusercontent.com/62693741/79825395-89f45880-83b6-11ea-9219-3a41ba2010c7.jpg)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by anj96** [comment]
This API call is failing as well: https://api.covid19india.org/data.json

**Comment by chandrajob365** [comment]
Seems to be CORS issue

**Comment by jeremyphilemon** [comment]
Thanks for reporting :)

**Comment by lakshmi14** [comment]
![image](https://user-images.githubusercontent.com/7721961/79827445-ec038c80-83bb-11ea-919c-9efccf2bc866.png)


Clearing the cache worked.
