### ISSUE TITLE
Map Visualization show Virus Spread over time

### ISSUE THREAD

**Issue by miztiik** [covid19india/covid19india.github.io#135]
As the virus is spreading to new cities/states in india, It would be interesting to see visually how the virus has spread over a period of time using different colors ( say green(health) to start with and end with red/darkened red for all parts of the state) .

#### Some Thoughts on Implementation
- The necessary data is already available in the dataset. Date of the patients, state information.
- A visual[<sup>Ref</sup>](https://youtu.be/hVimVzgtD6w?t=707) india map for choropleth styling
- A slide bar for days [day(1)....day(N)].
- Each day plotting the patient/state on the map and increase the color gradient to show the intensity of the infection.

#### Enhanced Implementation
A more granular approach would be use map with city data( like https://www.openstreetmap.org) and plot the patients on the map and keep adding as the days progress.

**Why this might be useful?**
- Gives an idea people movement across the region, might be useful for control measures.
- Helps in focussed planning for control measures in hot spots and easing control measures on other places.
- Allows anyone to go back in time to understand the spread of infection
- Ofcourse it is _cool_ to try and become the next [Hans Rolsing](https://en.wikipedia.org/wiki/Hans_Rosling) who made data crunching fancy.

**Comment by jeremyphilemon** [comment]
This is exactly what I references in #317, would you like to take this up?

**Comment by hitesh-tarani** [comment]
@jeremyphilemon I would like to work on this issue.
For the implementation, I guess we would have a Range slider of dates, and based on the date range, we slice the statewise delta to those dates, and then use this data in Map and Timeline components.

**Comment by jeremyphilemon** [comment]
@hitesh-tarani sure go ahead! :)

**Comment by santhosh-ps** [comment]
I created the following one, Is it similar to what we expect to achieve on this issue with heat map?

https://corona-timeline.netlify.com/

**Comment by sudevschiz** [comment]
@santhosh-ps Cool work! Is it possible to do this animation using our API and a bit more smoother?

**Comment by bootleg-icarus** [comment]
Are you thinking of adding a separate map with a date slider or replacing the date on home page with a slider and displaying changes on the choropleth map of India?

We could add this in the homepage but, it's already a bit congested, especially on mobile. ( the date component would either have to move or a new component would need to be added to be able to see it with the map in the same screen ) also, the country's map doesn't have district borders, we would still be able to see how numbers grew in different states over time. We'd have to click on states and view their spread separately.

**Comment by aswaathb** [comment]
I'd like to /claim this

**Comment by aswaathb** [comment]
Reverting status back to /available as I'm working on another PR atm. Feel free to claim it!

**Comment by shubhamjain2998** [comment]
@jeremyphilemon Is this still an active issue, I would like to work on this. A date slider component suggested will be good to visualize the spread.
@bootleg-icarus I think something like [this](https://www.nbcnewyork.com/news/national-international/map-watch-the-coronavirus-cases-spread-across-the-world/2303276/) will not look congested.

**Comment by jeremyphilemon** [comment]
Closed by #2009 after introducing the timeline!

Cheers :)
