### ISSUE TITLE
Essential page in mobile has unnecessary margin reducing space for the content

### ISSUE THREAD

**Issue by kousiksatish** [covid19india/covid19india.github.io#1353]
**Describe the bug**
In essentials page, once we search and select a particular item, the details come up on screen. But the details have a lot of left and right margins wasting almost 2/3rd of the screen space.

**To Reproduce**

1. Go to essentials page
2. Search for a city
3. View a particular project
4. See as in below screenshot

**Expected behavior**
We can remove the margins so that full content is available in one view without the need to scroll.

**Screenshots**
![Screenshot_2020-04-21-10-44-53-210_com android chrome](https://user-images.githubusercontent.com/6641694/79827975-55d06600-83bd-11ea-814d-73cca726253d.jpg)

**Smartphone (please complete the following information):**

- Device: Redmi note 8 pro
- OS: Android
- Browser Chrome

**Comment by kousiksatish** [comment]
I would like to work on this if accepted

**Comment by Binu42** [comment]
This is fixed in PR #1341 issue #1340

**Comment by jeremyphilemon** [comment]
Fixed.
