### ISSUE TITLE
Display wrong date and time  

### ISSUE THREAD

**Issue by poojapatel10** [covid19india/covid19india.github.io#1355]
On the home page of https://www.covid19india.org/  ,it's displying wrong date and time.

I have attached images for your reference, please have a look.

![WhatsApp Image 2020-04-21 at 10 49 30 AM (1)](https://user-images.githubusercontent.com/44190398/79828330-2a01b000-83be-11ea-9998-5afa9150df7b.jpeg)
![WhatsApp Image 2020-04-21 at 10 49 30 AM (2)](https://user-images.githubusercontent.com/44190398/79828335-2c640a00-83be-11ea-9e0f-84ba4b5030c0.jpeg)
![WhatsApp Image 2020-04-21 at 10 49 30 AM](https://user-images.githubusercontent.com/44190398/79828341-2d953700-83be-11ea-9576-ab1d47fa6794.jpeg)

Thanks & Regards,

Pooja Patel

**Comment by harishmathur** [comment]
Please assign this issue to me.

**Comment by shuklaayush** [comment]
Duplicates #781
