### ISSUE TITLE
directory of covid-19 relevant websites

### ISSUE THREAD

**Issue by chetanbnaik** [covid19india/covid19india.github.io#1357]
Hi, 

Do you think you guys could have a directory of covid-19 relevant websites? 

I would like to have my website listed in that directory. The website I own can enable people to watch movies, TV shows together with friends in realtime. These kind of apps are useful during the time of lockdown and #stayhome is encouraged. what do you guys think?

Cheers

**Comment by jeremyphilemon** [comment]
Thanks for raising the PR, however, this sounds a little out of scope and not aligned towards the motivation behind this project at the moment.
