### ISSUE TITLE
Access database issue it frozen

### ISSUE THREAD

**Issue by aamir200** [covid19india/covid19india.github.io#1359]
Hello Shukla

I didn't get any update. I was monitoring that your database in google is frozen for 19th. and didn't update. As I told you earlier that many people are watch this data.

it should open and get latest update every time. I also used in my report and client and other many are giving feedback that your datasets is not update. can you please share me the latest url for the report which will not be frozen.

Please have a look and let me know

**Comment by AnkanDas97** [comment]
Please resolve the issue and keep the Spreadsheet running. My entire analysis works are based on the site's database. Please update the spreadsheet or else all my work will be lost.

**Comment by aamir200** [comment]
Same here I have already raise this issue before but haven't get any reply yet. Don't forzen the database.

My entire analysis works are based on the site's database. Please update the spreadsheet or else all my work will be lost

**Comment by AnkanDas97** [comment]
> Same here I have already raise this issue before but haven't get any reply yet. Don't forzen the database.
> 
> My entire analysis works are based on the site's database. Please update the spreadsheet or else all my work will be lost

You people did a great job sharing us your shreadsheets....please dont freeze it right now .... Please update it by 23:59 tonight. All our hard work will go in vain if its not updated before 00:00 today. We depend on you. Covid19tracker.

**Comment by aamir200** [comment]
please dont freeze the shreadsheets

**Comment by aamir200** [comment]
Any update

**Comment by aamir200** [comment]
Can you please provide he update.

**Comment by bee-rickey** [comment]
@aamir200 How were you using the sheet? What was your methodology?

**Comment by aamir200** [comment]
> @aamir200 How were you using the sheet? What was your methodology?

I am using following below url as a web API
https://docs.google.com/spreadsheets/d/e/2PACX-1vSz8Qs1gE_IYpzlkFkCXGcL_BqR8hZieWVi-rphN1gfrO3H4lDtVZs4kd0C3P8Y9lhsT1rhoB-Q_cP4/pubhtml#

**Comment by aamir200** [comment]
please let me know and also this link https://api.covid19india.org/csv/latest/state_wise.csv
data is not updated regularly

**Comment by aamir200** [comment]
Any update and also I cannot see any updated data in the following link https://api.covid19india.org/data.json please update accordingly as my full report depend on this

**Comment by jeremyphilemon** [comment]
You can access the sheets over at http://patientdb.covid19india.org/

**Comment by aamir200** [comment]
Issue is not solve you guys are closed the ticket may I know why?

1st check this site is updating the data or not and then tell others
Duplicate of # http://patientdb.covid19india.org/
