### ISSUE TITLE
Log graphs

### ISSUE THREAD

**Issue by rishiraje** [covid19india/covid19india.github.io#136]
Covid-19 is an exponential disease.

Looking at a simple graph really does not give true picture of cases.

Log graph will give correct picture on whether the disease is slowing down or further accelerating.

If possible, have log graph on a per state basis

**Comment by s-naveen** [comment]
@rishiraje I did some initial implementation on charts which includes log chart. Let me know your thoughts.

https://covid19-india-react-git-charts.s-naveen.now.sh/

**Comment by rishiraje** [comment]
@s-naveen Looks very nice. I especially like the fact that all the graphs are consolidated and the dates are shown when you click on the graph

**Comment by JunaidBabu** [comment]
@s-naveen this is really nice.. is there a PR for this?

https://covid19-india-react-git-charts.s-naveen.now.sh/

**Comment by s-naveen** [comment]
@JunaidBabu 

https://github.com/covid19india/covid19india-react/pull/237

**Comment by jeremyphilemon** [comment]
Closed by #363
