### ISSUE TITLE
Pie Chart for Outcome of Cases in Deep Dive

### ISSUE THREAD

**Issue by Abhinav-Mani** [covid19india/covid19india.github.io#1362]
**Is your feature request related to a problem? Please describe.**
I do not get clear view of  outcome of cases.

**Describe the solution you'd like**
A pie Chart should be added showing outcome of case in Deep Dive

**Comment by Abhinav-Mani** [comment]
You can assign it to me if you feel it to be relevant.

**Comment by jeremyphilemon** [comment]
This will be addressed in #1496
