### ISSUE TITLE
A daily timeseries chart in deep dive for recovered vs deceased

### ISSUE THREAD

**Issue by nayakrahul** [covid19india/covid19india.github.io#1365]
It will give insights representing hope. It will show if recovery rate is faster than decreased rate or not.

**Comment by Abhinav-Mani** [comment]
Do you mean something like the worldometers' "Outcome of Cases (Recovery or Death)" graph. I too feel it can be insightfull
![outcometimeseries](https://user-images.githubusercontent.com/47060625/79865476-d8c2e200-83f8-11ea-9989-ea565e1d82f9.PNG)

**Comment by jeremyphilemon** [comment]
This is already present in the homepage.
