### ISSUE TITLE
States cases distribution in Deep Dive

### ISSUE THREAD

**Issue by Abhinav-Mani** [covid19india/covid19india.github.io#1367]
**Is your feature request related to a problem? Please describe.**
There is no charts for visualization for distribution of share of corona case in different states. 

**Describe the solution you'd like**
A cases distribution pie graph should be added in deep drive

**Additional context**
This could made similar to worldometers' Countries cases distribution 
![CountyWise](https://user-images.githubusercontent.com/47060625/79864895-db710780-83f7-11ea-9f64-a991934bf65c.PNG)

**Comment by Abhinav-Mani** [comment]
You can assign it to me if you feel it to be relevant.

**Comment by bhavinkotak07** [comment]
I can work on it. Please assign the task to me. Below is the screenshot of my work.
![Screenshot from 2020-04-23 23-29-23](https://user-images.githubusercontent.com/5495645/80133152-6994eb80-85ba-11ea-970d-3ac3eab705cc.png)

**Comment by Abhinav-Mani** [comment]
Assign it to me.

**Comment by Abhinav-Mani** [comment]
You can assign it to me
