### ISSUE TITLE
Navigation between state pages

### ISSUE THREAD

**Issue by ryan-rozario** [covid19india/covid19india.github.io#1372]
**Is your feature request related to a problem? Please describe.**
Navigation from one state page to a different state page without going back to the home page.

**Describe the solution you'd like**
A drop down breadcrumb solution that lists links to all the other states would work well with the current design. 

**Describe alternatives you've considered**
A separate dropdown list would occupy too much space, especially on mobile.

**Additional context**
![image](https://user-images.githubusercontent.com/32513286/79897371-42f27b80-8427-11ea-97e4-86dba0c26ed5.png)

**Comment by shubhamjain2998** [comment]
I would like to work on this.

**Comment by gyanendrapatro** [comment]
i can work o n this

**Comment by Abhinav-Mani** [comment]
I would like to work on this.

**Comment by jeremyphilemon** [comment]
This can be used to replace the current breadcrumbs and also add the requested functionality above https://primer.style/components/Breadcrumbs 

Essentially the breadcrumbs would look like:
Home > State > State/UT Name

Reply with /claim to have this assigned to you.

**Comment by karankiri** [comment]
/claim I would love to work on this

**Comment by karankiri** [comment]
@jeremyphilemon I've attached screenshot for desktop and mobile view for both the modes. Please let me know if any changes required.
![localhost_3000_state_MH(iPhone 6_7_8) (1)](https://user-images.githubusercontent.com/19989161/80275531-77a05480-86ff-11ea-8dc3-46cfaafd9e2b.png)
![localhost_3000_state_MH(iPhone 6_7_8)](https://user-images.githubusercontent.com/19989161/80275532-796a1800-86ff-11ea-87a3-a21ece32c1a5.png)
![image](https://user-images.githubusercontent.com/19989161/80275554-aa4a4d00-86ff-11ea-8c46-17797ce3560e.png)
![image](https://user-images.githubusercontent.com/19989161/80275571-c9e17580-86ff-11ea-8cbd-af06a5ae350f.png)
