### ISSUE TITLE
Deep dive graph for State-wise No. of Tests

### ISSUE THREAD

**Issue by saberprashant** [covid19india/covid19india.github.io#1374]
**Is your feature request related to a problem? Please describe.**
No. of tests plays an important role in understanding the spread, so for a deep dive, there should be one Statewise graph showing no. of tests done.

**Describe the solution you'd like**
A graph which will show no. of states just like we have for "States - Total Cases" in Deep dive in a bar graph format showing the no. of tests done each day. 

**Describe alternatives you've considered**
If we don't have tests done data for each day, then we can show only total no. of tests done for each state.

**Additional context**
This will help to get a deeper insight on how the testing process is going.

**Comment by saberprashant** [comment]
@jeremyphilemon @JunaidBabu 
I can work on this one if you assign it to me.

**Comment by jeremyphilemon** [comment]
Closing cause addressed in #887
