### ISSUE TITLE
Graph display error

### ISSUE THREAD

**Issue by yashshah1** [covid19india/covid19india.github.io#1375]
**Describe the bug**
The baseline of the graph doesn't coincide with the x-axis

**To Reproduce**

1. Go to the graph section, select all states
2. Set graph settings to be Uniform, daily and time interval to be from the beginning

**Expected behavior**
The  0 of the y-axis should be on the x-axis

**Screenshots**
![image](https://user-images.githubusercontent.com/31387795/79898568-1475a000-8429-11ea-9631-e6171627695a.png)

**Desktop (please complete the following information):**

- OS: Ubuntu 19.10
- Browser Chome
- Version 81.04

**Smartphone (please complete the following information):**

- Device: Mi A3
- OS: Android 9
- Browser Chrome

**Additional context**
I've also tested the same on my phone, the bug persists

**Comment by nayakrahul** [comment]
It is because there is -1 as value of y in daily active cases on February 13.
![Screenshot (31)](https://user-images.githubusercontent.com/11428805/79912103-22362000-843f-11ea-915b-288edae73fba.png)

**Comment by yashshah1** [comment]
Okay, it makes sense then! I'll go ahead and close the issue
