### ISSUE TITLE
Graphs should reset to pan India stats if anywhere on page, except on state slab in the table. 

### ISSUE THREAD

**Issue by championballer** [covid19india/covid19india.github.io#1376]
**Is your feature request related to a problem? Please describe.**
When we hover out of the table, the graphs still represent the last state we hovered over. Doesn't seem natural to me.

**Describe the solution you'd like**
I personally would prefer that it reset to pan India stats when we are not hovering over any particular state slab.

**Comment by shuklaayush** [comment]
Thanks, but this is really subjective. I think resetting by clicking anywhere outside the map provides a good middle ground. Closing

**Comment by championballer** [comment]
But even that does not happen, does it? Clicking anywhere on the page also doesn't reset the map. You have to go all the way in the drop box to select All states to get the pan India view.

**Comment by shuklaayush** [comment]
@championballer So it resets if you click anywhere outside the map, but still inside the SVG container. You're right that it should ideally reset by clicking anywhere outside the map on the whole webpage, but I couldn't figure out a way to do that.

**Comment by jeremyphilemon** [comment]
@shuklaayush Found this while playing around with `react-use`, maybe you're looking for [this](https://github.com/streamich/react-use/blob/master/docs/useClickAway.md)?
