### ISSUE TITLE
Clicking on "COVID19INDIA" title in header doesn't close "Menu Panel"

### ISSUE THREAD

**Issue by saberprashant** [covid19india/covid19india.github.io#1378]
**Describe the bug**
This isn't a bug in general but a UX improvement. When we click Menu panel and navigate to some other page like "Deep Dive" then on that page if we again click menu panel(it opens) but we navigate to "Home" page using "COVID19INDIA" title (in middle of the header), then the menu panel doesn't close automatically. Due to this, user won't be able to see the Home content.

**To Reproduce**

1. Click on "Menu panel" and select "Deep Dive" page
2. Click on "Menu panel" again
3. Now, click on "COVID19INDIA" title on the header.
4. You will find that menu panel is still open, but actually, you are navigated to "Home" already.

**Expected behavior**
On clicking "COVID19INDIA" title, menu panel should close automatically.

**Screenshots**
Opened menu panel on deep dive page (check URL):
![deep_dive](https://user-images.githubusercontent.com/20706536/79901423-6caea100-842d-11ea-88ee-1a06b20284c3.png)

Clicked the "COVID19INDIA" title, and home page rendered, but the menu panel is still there:
![home](https://user-images.githubusercontent.com/20706536/79901614-b5665a00-842d-11ea-8516-005190925cb2.png)

View on web app for the same:
![web-app-view](https://user-images.githubusercontent.com/20706536/79901689-d2029200-842d-11ea-9553-74c4341ef531.png)

**Desktop (please complete the following information):**

- OS: iOS
- Browser - Chrome
- Version - 81.0

**Smartphone (please complete the following information):**

- Device: Note 8 Pro
- OS: Android
- Browser: Chrome
- Version: 81.0

**Additional context**
This will make the overall UX better.

**Comment by saberprashant** [comment]
@jeremyphilemon @JunaidBabu 
I would like to work on this one.

**Comment by Binu42** [comment]
hi, @saberprashant , @jeremyphilemon, @JunaidBabu  i've already fixed this issue in #1184

**Comment by saberprashant** [comment]
Awesome @Binu42 .
Closing this issue then
