### ISSUE TITLE
Can't see the complete info 

### ISSUE THREAD

**Issue by Goutham88** [covid19india/covid19india.github.io#1380]
![Screenshot_2020-04-22-01-34-47-545_com android chrome](https://user-images.githubusercontent.com/13810239/79908846-9968b580-8439-11ea-86ff-3f8e5d9e993e.jpg)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by nayakrahul** [comment]
I can fix this. @shuklaayush @jeremyphilemon

**Comment by jeremyphilemon** [comment]
@nayakrahul sure, go ahead :)

**Comment by nayakrahul** [comment]
Hey @jeremyphilemon, the PR for this issue has been merged. Should the issue be closed?
