### ISSUE TITLE
Active colour is in red and deceased in other colour

### ISSUE THREAD

**Issue by Goutham88** [covid19india/covid19india.github.io#1381]
![Screenshot_2020-04-22-01-36-48-767_com android chrome](https://user-images.githubusercontent.com/13810239/79909000-e056ab00-8439-11ea-84f4-a1813d044c93.jpg)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Goutham88** [comment]
I have already made the fix
https://github.com/covid19india/covid19india-react/pull/1305#event-3249204844
I can raise the pr again

**Comment by bee-rickey** [comment]
Please raise issues before hand. Don't raise a PR and then raise an issue. It becomes difficult for us to track.

**Comment by Goutham88** [comment]
Sure @bee-rickey. Will follow from next time

https://github.com/covid19india/covid19india-react/pull/1401
raised the pr again.
