### ISSUE TITLE
UI feedback 

### ISSUE THREAD

**Issue by passion8** [covid19india/covid19india.github.io#1382]
Thank you guys for all your contribution. I tried hard not to criticize  but if i keep my mouth shut you guys will never understand what normal users are going though. 

Earlier website was good but as you guys keep updating and integrating  many features, the website is now cluttered and he is hell confusing.

**Comment by Thedijje** [comment]
I would suggest simplicity over the feature.
For example, 
1. Keeping one simple map on Home page and dedicated map page for all play around.
2. Same goes with the graph, Keep 1 simple graph on the home page and a dedicated section with many controls and fields for graph nerd.
3. We can have statewide pages as well to give a better and cleaner interface.

**Comment by shuklaayush** [comment]
@passion8 Can you elaborate?

**Comment by jeremyphilemon** [comment]
Closing cause no elaboration.
