### ISSUE TITLE
Worse essential page on dark mode

### ISSUE THREAD

**Issue by dpnkrpl** [covid19india/covid19india.github.io#1385]
Essential page contents are barely visible on dark mode. 
![Screenshot_2020-04-22-07-29-07-281_com android chrome](https://user-images.githubusercontent.com/27947066/79932624-9090d780-846b-11ea-817d-b282cc1d10fc.jpg)

**Comment by gyanendrapatro** [comment]
I can fix it assign it to me

**Comment by SensehacK** [comment]
I'm also working on it 👍

**Comment by dpnkrpl** [comment]
Still have problems . 
@SensehacK You didn't fix the position of feedback and add button for mobile devices.
If possible change the colour of these two buttons too . Blue over black is not eye catching. 

![Screenshot_2020-04-22-22-39-20-644_com android chrome](https://user-images.githubusercontent.com/27947066/80011960-33883680-84ea-11ea-9aab-bb296b51025c.jpg)

**Comment by SensehacK** [comment]
@deep5050 We can have a color palette decided for dark mode in a new feature request!

I'll create the request.

It would add more consistency with the overall website.
