### ISSUE TITLE
Navbar Issues which still exist

### ISSUE THREAD

**Issue by Binu42** [covid19india/covid19india.github.io#1386]
New look is superb, but i still found few issues in UI. i've fixed essential page issue of alignment in mobile and desktop in PR #1341 and Navbar issues i'm mentioning below and i'll like to fix it as well.
**Describe the bug**
* when sidenavbar opens, pages get shifted toward right (Desktop)
* icons are not clickable which means user have to first hover over it and then go to sidenav links to change pages infact sidnav get closed on click of icons. (Desktop)
* navbar is not closed on click of covid19India click and page get changed to homepage. (mobile).
* in horizontal view of mobile user are not able see all navigation link in navbar.

**To Reproduce**
go to https://www.covid19india.org/ and hover over menus. you will see it.

**Expected behavior**
* pages should not shift right when side nav opens or close. 
* icons should be clickable. 
* navbar should close on click of covid19India. 
* user should able to scroll navigation links in horizontal mobile view.

**Screenshots**
![pages](https://user-images.githubusercontent.com/45959932/79935036-896cc800-8471-11ea-83e9-bb49493da4a6.gif)

**Desktop (please complete the following information):**

all os, browsers and versions.

**Smartphone (please complete the following information):**

all devices, os, browser, versions.

**Comment by Binu42** [comment]
@jeremyphilemon assign it to me i would like to fix it.

**Comment by Zindra** [comment]
![image](https://user-images.githubusercontent.com/30254595/79953285-3a3a8d80-8499-11ea-8d33-7d6cf1b3a91e.png)

animation on mouse_hover is not working porperly when we moving mouse from left to right. Need to start the animation when a particular icon is hovered by the user.

**Comment by jeremyphilemon** [comment]
Most of these are fixed. Feel free to open a new issue if some functionalities were still no fixed.
