### ISSUE TITLE
Graph

### ISSUE THREAD

**Issue by jeemitsha** [covid19india/covid19india.github.io#1389]
Pls don't pre-define the height of graphs, because it is unable to analyse anything in decreased graph

**Comment by shuklaayush** [comment]
Which graph?

**Comment by jeemitsha** [comment]
You see in Deceased Graph nothing is clear as the it looks as a straight line because the y axis is too long already. Sent from Mail for Windows 10 From: Ayush ShuklaSent: Wednesday, April 22, 2020 11:36 AMTo: covid19india/covid19india-reactCc: jeemitsha; AuthorSubject: Re: [covid19india/covid19india-react] Graph (#1389) Which graph?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by chatRG** [comment]
Agreed. Given these are exponential graphs and deceased rate is not increasing as quickly (thankfully), it makes more sense to toggle the Uniform scale **OFF**.

**Comment by shuklaayush** [comment]
So, right now, the settings for Uniform Scaling are stored in local storage and therefore, preserved across sessions. I think this is a good middle ground. Hence, closing

**Comment by jeemitsha** [comment]
Ha
