### ISSUE TITLE
Wrong data 

### ISSUE THREAD

**Issue by rajathsn** [covid19india/covid19india.github.io#139]
The data in confirmed and active column are same, please fix it. In column confirmed its should be sum of active+recovered+Deceased. Refer the screenshot. 
![5D8439FF-62C5-484E-BFC7-58D41B4BE047](https://user-images.githubusercontent.com/52188338/77602967-db830200-6f34-11ea-8cdd-0eebd28aefe4.png)

**Comment by unmesh-shukla** [comment]
Being addressed in this PR. #140

**Comment by jeremyphilemon** [comment]
Fixed! Thanks!
