### ISSUE TITLE
District wise filter in 'Spread Trends'

### ISSUE THREAD

**Issue by upx86** [covid19india/covid19india.github.io#1391]
Currently there is State level data for 'Spread Trends', we can have additional filter for district to render trends for detailed numbers.

like: 

![image](https://user-images.githubusercontent.com/42634202/79946298-4f112400-848d-11ea-832c-5a487fc857ec.png)

**Comment by pavanmehta91** [comment]
I can pick that up

**Comment by jeremyphilemon** [comment]
@pavanmehta91 sure go ahead :)

Let's try to implement this functionality in the state pages first!

**Comment by pavanmehta91** [comment]
https://api.covid19india.org/
I could not find date wise data for districts of a particular state in this.
Is there data and Api available for it?

**Comment by pavanmehta91** [comment]
@jeremyphilemon can you guide me here?

**Comment by shuklaayush** [comment]
@pavanmehta91 Seems like we don't have district-level time-series data in the API. I'm putting this on hold for now. Will make it available when the data is added

**Comment by Abhishekbhatia** [comment]
I wrote a python script to parse the data from raw_data.json and prepare the data in the form of 
{ State: District:Date: Number of cases }. The sample data is as below :

`"Chhattisgarh": {
        "Rajnandgaon": {},
        "Raipur": {
            "26/03/2020": 1,
            "28/03/2020": 1,
            "31/03/2020": 1
        },
        "Bilaspur": {},
        "Durg": {},
        "Korba": {
            "04/04/2020": 1,
            "09/04/2020": 8,
            "11/04/2020": 7,
            "12/04/2020": 6,
            "14/04/2020": 2,
            "16/04/2020": 3
        },
        "": {}
    },
    "Gujarat": {
        "Surat": {
            "21/03/2020": 2,
            "23/03/2020": 1,
            "24/03/2020": 1,
            "25/03/2020": 2,
            "26/03/2020": 1,
            "29/03/2020": 1,
            "31/03/2020": 1,
            "01/04/2020": 2,
            "04/04/2020": 1,
            "05/04/2020": 3,
            "06/04/2020": 3,
            "07/04/2020": 3,
            "08/04/2020": 1,
            "09/04/2020": 1,
            "10/04/2020": 3,
            "11/04/2020": 1,
            "13/04/2020": 5,
            "14/04/2020": 9,
            "15/04/2020": 9,
            "16/04/2020": 37,
            "17/04/2020": 52,
            "18/04/2020": 13,
            "19/04/2020": 89,
            "20/04/2020": 27,
            "21/04/2020": 78,
            "22/04/2020": 68,
            "23/04/2020": 41,
            "24/04/2020": 6,
            "25/04/2020": 34
        },
        "Ahmadabad": {
            "20/03/2020": 2,
            "21/03/2020": 2,
            "22/03/2020": 3,
            "23/03/2020": 6,
            "28/03/2020": 3,
            "29/03/2020": 4,
            "30/03/2020": 1,
            "31/03/2020": 1,
            "01/04/2020": 8,
            "03/04/2020": 7,
            "04/04/2020": 7,
            "05/04/2020": 8,
            "06/04/2020": 11,
            "07/04/2020": 19,
            "09/04/2020": 59,
            "10/04/2020": 55,
            "11/04/2020": 46,
            "12/04/2020": 39,
            "13/04/2020": 38,
            "14/04/2020": 53,
            "15/04/2020": 77,
            "16/04/2020": 95,
            "17/04/2020": 78,
            "18/04/2020": 239,
            "19/04/2020": 239,
            "20/04/2020": 147,
            "21/04/2020": 125,
            "22/04/2020": 128,
            "23/04/2020": 151,
            "24/04/2020": 169,
            "25/04/2020": 182
        },
        "Vadodara": {
            "20/03/2020": 1,
            "21/03/2020": 1,
            "23/03/2020": 4,
            "28/03/2020": 2,
            "05/04/2020": 1,
            "06/04/2020": 2,
            "08/04/2020": 6,
            "09/04/2020": 4,
            "10/04/2020": 37,
            "11/04/2020": 36,
            "12/04/2020": 6,
            "13/04/2020": 6,
            "14/04/2020": 6,
            "15/04/2020": 8,
            "16/04/2020": 7,
            "17/04/2020": 16,
            "18/04/2020": 14,
            "19/04/2020": 22,
            "20/04/2020": 8,
            "21/04/2020": 11,
            "22/04/2020": 9,
            "23/04/2020": 7,
            "24/04/2020": 5,
            "25/04/2020": 7
        },
        "Gandhinagar": {
            "22/03/2020": 1,
            "23/03/2020": 1,
            "24/03/2020": 3,
            "26/03/2020": 3,
            "28/03/2020": 1,
            "31/03/2020": 1,
            "04/04/2020": 2,
            "10/04/2020": 1,
            "11/04/2020": 1,
            "14/04/2020": 1,
            "16/04/2020": 1,
            "23/04/2020": 1,
            "24/04/2020": 1,
            "25/04/2020": 4
        },
        "Kachchh": {
            "05/04/2020": 1,
            "10/04/2020": 2,
            "20/04/2020": 2
        },
        "Rajkot": {
            "24/03/2020": 1,
            "26/03/2020": 2,
            "27/03/2020": 3,
            "29/03/2020": 1,
            "31/03/2020": 1,
            "07/04/2020": 1,
            "09/04/2020": 2,
            "10/04/2020": 5,
            "15/04/2020": 6,
            "16/04/2020": 4,
            "18/04/2020": 2,
            "19/04/2020": 6,
            "20/04/2020": 2,
            "21/04/2020": 2,
            "22/04/2020": 1
        },
        "Mahesana": {
            "06/04/2020": 1,
            "14/04/2020": 2,
            "19/04/2020": 1,
            "20/04/2020": 1,
            "21/04/2020": 1
        },
        "Bhavnagar": {
            "30/03/2020": 5,
            "02/04/2020": 1,
            "04/04/2020": 2,
            "05/04/2020": 4,
            "07/04/2020": 1,
            "08/04/2020": 4,
            "10/04/2020": 4,
            "11/04/2020": 1,
            "14/04/2020": 3,
            "18/04/2020": 4,
            "19/04/2020": 2,
            "23/04/2020": 1,
            "24/04/2020": 2,
            "25/04/2020": 5
        },
        "Porbandar": {
            "01/04/2020": 2
        },
        "Gir Somnath": {
            "30/03/2020": 1,
            "21/04/2020": 1
        },` 

I can share the script or merge it with the existing code if need be.

**Comment by pavanmehta91** [comment]
If this gives data for all the districts of a state for all the dates, I think this can work @Abhishekbhatia 
Would the districts with no cases for a day show 0?
Also if data is structured in the following way it would be much easier.
```
{
"Gujarat": [
"Ahmedabad": [{date: "24/04/2020", cases: 3},{date: "25/04/2020", cases: 5}],
}
```

**Comment by Abhishekbhatia** [comment]
_Would the districts with no cases for a day show 0?_

The number of cases on a particular date will only be available if the date is available in the "dateannounced" key of the raw_data.json.

_Also if data is structured in the following way it would be much easier._
I can structure that way too.

**Comment by pavanmehta91** [comment]
Let's do it then @Abhishekbhatia .
I'm not sure how the APIs is working. But there's another repo for it and you can suggest a solution there referring the link for this issue.
https://github.com/covid19india/api
Once api is made I can take over.

**Comment by pavanmehta91** [comment]
Looks like APIs are in JS. I hope it won't be much of an issue with you and Ideally api response should also be fast enough.

**Comment by Abhishekbhatia** [comment]
Okay @pavanmehta91 : Will do that. There have been new APIs added recently, so will create an API endpoint probably and will link this issue at https://github.com/covid19india/api.

**Comment by vntkumar8** [comment]
> I wrote a python script to parse the data from raw_data.json and prepare the data in the form of
> { State: District:Date: Number of cases }. The sample data is as below :
> 
> `"Chhattisgarh": { "Rajnandgaon": {}, "Raipur": { "26/03/2020": 1, "28/03/2020": 1, "31/03/2020": 1 }, "Bilaspur": {}, "Durg": {}, "Korba": { "04/04/2020": 1, "09/04/2020": 8, "11/04/2020": 7, "12/04/2020": 6, "14/04/2020": 2, "16/04/2020": 3 }, "": {} }, "Gujarat": { "Surat": { "21/03/2020": 2, "23/03/2020": 1, ........
`
> 
> I can share the script or merge it with the existing code if need be.

@Abhishekbhatia Can you please share your script. It will be helpful :)

**Comment by sudevschiz** [comment]
Let's discuss this at https://github.com/covid19india/api/issues/192
