### ISSUE TITLE
Navbar issue in when switching screen sizes

### ISSUE THREAD

**Issue by sudokoi** [covid19india/covid19india.github.io#1393]
**Describe the bug**
* If the browser size is changed, the navbar icons are displayed on the top right corner, instead of `Menu`

**To Reproduce**

1. Go to 'the homepage' in a desktop in maximized window.
2. Change window size to be small
3. The navbar-icons are displayed in the top right corner instead of `menu` label.
4. Clicking on icons brings up the menu with `close` button, which is the expected behavior.
5. If the window is now maximized, the `Menu` or `Close` label is shown instead of the Navbar-icons.

**Expected behavior**
Correct components when the screen size switches.

**Screenshots**
* Step 1:
![image](https://user-images.githubusercontent.com/22864071/79949897-e4171b80-8493-11ea-8004-0844815f9835.png)
* Step 3: 
![image](https://user-images.githubusercontent.com/22864071/79949963-fe50f980-8493-11ea-99ac-a1a66d709ec3.png)
* Step 5:
![image](https://user-images.githubusercontent.com/22864071/79950083-26d8f380-8494-11ea-8f39-2243afe5d294.png)

**Desktop (please complete the following information):**

- OS: [e.g. iOS] Windows 10
- Browser [e.g. chrome, safari] Chrome
- Version [e.g. 22] 80

**Comment by ShubhamOnGrid** [comment]
I would like to work on this
Already found the solution, 
will create PR as soon as it's assigned

**Comment by jeremyphilemon** [comment]
@shubhamjain2998 Sure go ahead, also looks like part of the issue has been fixed. Would still have to figure out a way to retain "Menu" instead of the home icon as it is now.

**Comment by sudokoi** [comment]
Since @ShubhamOnGrid was taking too long, I have fixed the issue and raised a PR.

**Comment by ShubhamOnGrid** [comment]
@tsuki42 Go ahead, I also have same changes for the fix.
