### ISSUE TITLE
Needs to show covid19 zone (green/orange/red) per state.

### ISSUE THREAD

**Issue by sajus** [covid19india/covid19india.github.io#1394]
**Describe the solution you'd like**
State wise maps under ('state/:stateCode') needs to show covid19 zone, such as green zone, orange zone, red zone. Currently its just showing confirmed case.  As per my requirements it should show, confirm cases , active cases and zone.  

**Additional context**

<img width="430" alt="Screen Shot 2020-04-22 at 12 32 14 PM" src="https://user-images.githubusercontent.com/2240568/79950890-60f6c500-8495-11ea-97ed-7d4d43b4af53.png">

**Comment by keshank** [comment]
Dublicate https://github.com/covid19india/covid19india-react/issues/1040

**Comment by bee-rickey** [comment]
Closing as duplicate.
