### ISSUE TITLE
Let's make the icons clickable in the left navbar

### ISSUE THREAD

**Issue by Zindra** [covid19india/covid19india.github.io#1397]
Let's make the icons clickable in the left Navbar

**Describe the solution you'd like**
Right now we have to click on after hovering over the icons and then on the text.
Idea is to make that icon itself clickable.

Screenshot:
![image](https://user-images.githubusercontent.com/30254595/79954389-e16bf480-849a-11ea-9b01-b914ea94a5f9.png)

**Comment by animesh-tarodia-sp** [comment]
I was about to raise this issue. Glad u did :)

**Comment by animesh-tarodia-sp** [comment]
And please add some graphics for deep dive icon too.

**Comment by Zindra** [comment]
Thank you everyone. cheers.
