### ISSUE TITLE
Dark mode UI issues

### ISSUE THREAD

**Issue by chatRG** [covid19india/covid19india.github.io#1400]
**Describe the bug**
Texts are almost unreadable in dark mode.

**To Reproduce**

1. Go to demographics page
2. See error

**Expected behavior**
A clear and contrast view of text as some user may be color blind and even for normal user it is very hard to read that grey text and the blue text over blue background.

**Screenshots**
You can see the contrast ratio score in chrome itself.
![image](https://user-images.githubusercontent.com/22965855/79974621-4897a200-84b7-11ea-9c6e-c4489b814226.png)

![image](https://user-images.githubusercontent.com/22965855/79974676-6107bc80-84b7-11ea-980b-d23ce616a950.png)

**Desktop (please complete the following information):**

- OS: windows 10
- Browser chrome
- Version 81

**Additional context**
Better to check this site for reference on setting color contrast for better readability: https://contrastchecker.com/

**Comment by jeremyphilemon** [comment]
Closing in favor of #1417, let's track the issue there :)
