### ISSUE TITLE
State pages should have no. of district affected.

### ISSUE THREAD

**Issue by animesh-tarodia-sp** [covid19india/covid19india.github.io#1402]
**Is your feature request related to a problem? Please describe.**
When we open district pages it does not have count of total district and no. of districts affected.

**Describe the solution you'd like**
Just below the map of state we can have something like 20/50 districts affected so that we can get idea of districts with 0 cases.

**Comment by gyanendrapatro** [comment]
You can assign it to me

**Comment by bee-rickey** [comment]
Doesn't add much value IMO. Most of us don't even know the total district count in our states. So what value do we get by showing total districts affected?

**Comment by jeremyphilemon** [comment]
I feel the visual summary would be enough for this instead of knowing the exact values. Thanks for raising the issue anyway :)
