### ISSUE TITLE
Search Field in Home Screen is not working

### ISSUE THREAD

**Issue by xBones397** [covid19india/covid19india.github.io#1404]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by animesh-tarodia-sp** [comment]
Can you please describe the issue?

**Comment by jeremyphilemon** [comment]
Closing due to lack of proper description to reproduce bug.
