### ISSUE TITLE
District Name Mismatch between Table and Map for Dahod, Gujarat

### ISSUE THREAD

**Issue by keshank** [covid19india/covid19india.github.io#1408]
**Describe the bug**
Mismatch of spell for District Dahod  in Gujarat between table and map ( District no being Highlighted )

**To Reproduce**

1. Open Table of Gujarat
2. Look for Dahod District
3. Click on Gujarat Map
4. Click on Dahod district on Map ( No. of cases shown is 0 and map is not been highlighted even though the district has reported cases as per table)

**Expected behavior**

1. District map should be highlighted 
2. No of cases should be displayed above the map

**Screenshots**
![covid19](https://user-images.githubusercontent.com/63340632/79996959-ab4c6600-84d6-11ea-8450-3e0da4f449d1.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser Chrome
- Version  81.0.4044.92

**Smartphone (please complete the following information):**

- Device: iPhone XS
- OS: IOS 13.2.3
- Browser Chrome
- Version 77.0.3865.69

**Comment by keshank** [comment]
@jeremyphilemon @shuklaayush 
I have fixed this issue and I would love to contribute to the project.
Unable to publish my branch please grant me permission.

**Comment by keshank** [comment]
@jeremyphilemon I have fixed it on my local 

![Untitled](https://user-images.githubusercontent.com/63340632/80273729-787eb980-86f2-11ea-9033-4d85ac76d887.png)

**Comment by shuklaayush** [comment]
Fixed via #1704
