### ISSUE TITLE
Graph showing number of total beds available for patient (Total Health care system capacity)

### ISSUE THREAD

**Issue by keshank** [covid19india/covid19india.github.io#1409]
**Is your feature request related to a problem? Please describe.**

Adding a line to the states active case graph at the number of beds available.

**Describe the solution you'd like**

It will be useful to see the number of beds available in every state on the active cases graph helping us understand how many beds are empty and how much have we occupied.

It will also show how well we are flattening the curve with respect to our hospital capacity.

Indicating Health care System Capacity

![11SCI-VIRUS-TRACKER1-superJumbo](https://user-images.githubusercontent.com/63340632/80023183-c7fa9500-84fa-11ea-94ca-d68f2d7bb86e.jpg)

**Comment by bee-rickey** [comment]
Where's the data for this? Some states provide a minimal amount of data. For the rest, we can provide info on this. Plotting a graph seems excessive IMO.

**Comment by keshank** [comment]
@bee-rickey  
No need to plot a new graph you can have a button on existing graph which show a cut off line.
News agencies are regularly updating this information.
https://www.indiatoday.in/diu/story/india-ready-with-4-lakh-beds-in-400-districts-to-tackle-covid-19-1669776-2020-04-22

**Comment by jeremyphilemon** [comment]
A cutoff line makes sense, however would require verifiable data on the number of beds. Please refer to #803
