### ISSUE TITLE
Darkmode button toggling is not working

### ISSUE THREAD

**Issue by asrinivas61** [covid19india/covid19india.github.io#1411]
**Describe the bug**
Darkmode toggle button should work as expected.

**To Reproduce**
1. Open browser in desktop
2. And find the darkmode toggle icon at the left down corner
3. For every click on that icon should toggle the mode.

**Expected behavior**
Toggle actions should work perfectly between dark and light modes.

**Screenshots**
![image](https://user-images.githubusercontent.com/23236106/80008048-0e320300-84bf-11ea-813b-f908b5810660.png)

**Desktop (please complete the following information):**
- Device
  Macbook Pro 
  OSX - 10.14.6
  Browser - Chrome/Safari

**Smartphone (please complete the following information):**
- Device:
  Iphone 11 Pro
  OS - 13.4.1
  Browser - Chrome/Safari

**Comment by jeremyphilemon** [comment]
Patched.
