### ISSUE TITLE
Button Crowdsourced Patient Database link dead.

### ISSUE THREAD

**Issue by SensehacK** [covid19india/covid19india.github.io#1415]
**Describe the bug**
Crowdsourced Patient Database button on every page doesn't work. It returns PR_END_OF_FILE_ERROR

**To Reproduce**
Button opens this link
Open this link : https://patientdb.covid19india.org/
This link returns error "Secure Connection Failed"

1. Go to home
2. Scroll down to bottom footer 
3. Click on Crowdsourced Patient Database

**Expected behavior**

**Desktop (please complete the following information):**

- Browser [e.g. safari, firefox nightly, developer, chrome]

**Screenshots**

<img width="995" alt="Screen Shot 2020-04-22 at 2 13 34 PM" src="https://user-images.githubusercontent.com/8469205/80018043-7672eb80-84a3-11ea-993f-8a4237ee008b.png">

**Comment by bee-rickey** [comment]
This is ded :P (discontinued for now). Use https://api.covid19india.org/csv/

**Comment by SensehacK** [comment]
Shouldn’t we remove the button then?
