### ISSUE TITLE
Consistent Dark Mode Scheme

### ISSUE THREAD

**Issue by SensehacK** [covid19india/covid19india.github.io#1417]
**Is your feature request related to a problem? Please describe.**
I love dark mode everything, 
**Describe the solution you'd like**
Would like to propose a consistent dark mode color scheme / palette across the whole web app.
So that some pages would look consistent with the overall color schemes. 

Relevant Issues: 
#1385
#1416
#1400

**Describe alternatives you've considered**
Dark Reader extension fairly does great job of dark mode, but isn't officially supported on the web.

**Additional context**
We could utilize SASS variables for better scalability in terms of web development in future.

**Comment by jeremyphilemon** [comment]
Go ahead! Let's try to keep discussions about the palette here. For now you can use the palettes that's currently being used and build upon it with a little research from looking at accessibility guides too :)

Resources: 
- https://design.google/library/material-design-dark-theme/#hierarchy-simplify-uis-for-glanceable-information
- https://developer.apple.com/design/human-interface-guidelines/ios/visual-design/dark-mode/

**Comment by balrajsingh9** [comment]
> Go ahead! Let's try to keep discussions about the palette here. For now you can use the palettes that's currently being used and build upon it with a little research from looking at accessibility guides too :)
> 
> Resources:
> 
> * https://design.google/library/material-design-dark-theme/#hierarchy-simplify-uis-for-glanceable-information
> * https://developer.apple.com/design/human-interface-guidelines/ios/visual-design/dark-mode/

The current dark theme is great 👍 . Some minor suggestions I would like to posit.

Can we have something similar to what _twiter_ has? It shows three options to the user -
- Default (Light)
- Dim
- Lights out
<img width="666" alt="Screenshot 2020-05-07 at 5 01 38 PM" src="https://user-images.githubusercontent.com/37571874/81290007-ee850800-9084-11ea-8865-18cce71ac149.png">

There are some colors in the palette which are quite difficult to see. I'm comparing the visibility with the one we have in the default (light) theme. [#1400](https://github.com/covid19india/covid19india-react/issues/1400)

<img width="553" alt="Screenshot 2020-05-07 at 5 09 14 PM" src="https://user-images.githubusercontent.com/37571874/81290428-ae725500-9085-11ea-9271-ea8b3bba8069.png">
<img width="553" alt="Screenshot 2020-05-07 at 5 09 39 PM" src="https://user-images.githubusercontent.com/37571874/81290431-b03c1880-9085-11ea-9872-8b1160a90b29.png">

Using dev-tools I quickly changed the color of the element shown in the screenshot above and according to the _Material_ guideline, the medium emphasis text color on a darker surface should be - `rgba(255,255,255,.60)` or `#FFFFFF` with `60%` alpha. 
<img width="553" alt="Screenshot 2020-05-07 at 5 25 37 PM" src="https://user-images.githubusercontent.com/37571874/81291945-6143b280-9088-11ea-9fe8-ad918b63afe1.png">
To follow the guideline, we need to maintain colors in variables and switch according to the currently applied theme vs the common colors that we have in-place right.

So I agree with @SensehacK that we need to use variables to maintain a consistent style and to have better visibility (accessibility) of texts as compared to what we have currently. 

Extending the above point, I also played with the `font-weight` and had an instant improvement when I reduced it and didn't touch the text-color.

Old - `font-weight = 900` 
<img width="553" alt="Screenshot 2020-05-07 at 5 09 39 PM" src="https://user-images.githubusercontent.com/37571874/81292321-02cb0400-9089-11ea-90e4-4a99c47b26f0.png">

After reducing to `font-weight = 500`
<img width="553" alt="Screenshot 2020-05-07 at 5 18 50 PM" src="https://user-images.githubusercontent.com/37571874/81292349-124a4d00-9089-11ea-81fc-e0c8b2c04dc4.png">

Let me know your thoughts @jeremyphilemon

**Comment by balrajsingh9** [comment]
> > Go ahead! Let's try to keep discussions about the palette here. For now you can use the palettes that's currently being used and build upon it with a little research from looking at accessibility guides too :)
> > Resources:
> > 
> > * https://design.google/library/material-design-dark-theme/#hierarchy-simplify-uis-for-glanceable-information
> > * https://developer.apple.com/design/human-interface-guidelines/ios/visual-design/dark-mode/
> 
> The current dark theme is great 👍 . Some minor suggestions I would like to posit.
> 
> Can we have something similar to what _twiter_ has? It shows three options to the user -
> 
> * Default (Light)
> * Dim
> * Lights out
> 
> <img alt="Screenshot 2020-05-07 at 5 01 38 PM" width="666" src="https://user-images.githubusercontent.com/37571874/81290007-ee850800-9084-11ea-8865-18cce71ac149.png">
> 
> There are some colors in the palette which are quite difficult to see. I'm comparing the visibility with the one we have in the default (light) theme. [#1400](https://github.com/covid19india/covid19india-react/issues/1400)
> 
> <img alt="Screenshot 2020-05-07 at 5 09 14 PM" width="553" src="https://user-images.githubusercontent.com/37571874/81290428-ae725500-9085-11ea-9271-ea8b3bba8069.png">
> 
> <img alt="Screenshot 2020-05-07 at 5 09 39 PM" width="553" src="https://user-images.githubusercontent.com/37571874/81290431-b03c1880-9085-11ea-9872-8b1160a90b29.png">
> 
> Using dev-tools I quickly changed the color of the element shown in the screenshot above and according to the _Material_ guideline, the medium emphasis text color on a darker surface should be - `rgba(255,255,255,.60)` or `#FFFFFF` with `60%` alpha.
> <img alt="Screenshot 2020-05-07 at 5 25 37 PM" width="553" src="https://user-images.githubusercontent.com/37571874/81291945-6143b280-9088-11ea-9fe8-ad918b63afe1.png">
> To follow the guideline, we need to maintain colors in variables and switch according to the currently applied theme vs the common colors that we have in-place right.
> 
> So I agree with @SensehacK that we need to use variables to maintain a consistent style and to have better visibility (accessibility) of texts as compared to what we have currently.

Extending the above point, I also played with the `font-weight` and had an instant improvement when I reduced it and didn't touch the text-color.

Old - `font-weight = 900` 
<img width="553" alt="Screenshot 2020-05-07 at 5 09 39 PM" src="https://user-images.githubusercontent.com/37571874/81292321-02cb0400-9089-11ea-90e4-4a99c47b26f0.png">

After reducing to `font-weight = 500`
<img width="553" alt="Screenshot 2020-05-07 at 5 18 50 PM" src="https://user-images.githubusercontent.com/37571874/81292349-124a4d00-9089-11ea-81fc-e0c8b2c04dc4.png">

**Comment by SensehacK** [comment]
@balrajsingh9  Nice insight on 3 options for UX. 

Also font weight makes quite the difference, I'm currently swamped till next week with my final year project and thats the reason I wasn't able to put some design thinking towards this enhancement. 

If you have any Color palettes in mind, you could share it using a table

1. Light

- Primary color 1: UIColor(rgb x,x,x)
- Primary color 2: UIColor(rgb x,x,x)
- Primary color 3: UIColor(rgb x,x,x)
- Primary color 4: UIColor(rgb x,x,x)
- Primary color 5: UIColor(rgb x,x,x)

2. Dark
- Primary color 1: UIColor(rgb x,x,x)
- Primary color 2: UIColor(rgb x,x,x)
- Primary color 3: UIColor(rgb x,x,x)
- Primary color 4: UIColor(rgb x,x,x)
- Primary color 5: UIColor(rgb x,x,x)

3. Dim
- Primary color 1: UIColor(rgb x,x,x)
- Primary color 2: UIColor(rgb x,x,x)
- Primary color 3: UIColor(rgb x,x,x)
- Primary color 4: UIColor(rgb x,x,x)
- Primary color 5: UIColor(rgb x,x,x)


So that we can all collectively agree on color scheme and have an overall consistent UX.

**Comment by balrajsingh9** [comment]
Thank you @SensehacK.
I'll read more about what color scheme is apt. for the theme variants that we're going to use and which conforms to _Google's Material Guideline_ (Twitter's scheme is good though!). I'll check the exact color values that we can use. 

Let me know if you need any help with writing code for this. I can take out some time out of my job 😆

**Comment by balrajsingh9** [comment]
Twitter has 6 primary colors and they remain the same for all the theme variants. They have chosen a very nice set of primary color scheme which doesn't look odd or creates any visibility issues.

Here is a short video that I recorded demonstrating my above point - [GDrive](https://drive.google.com/file/d/1qqZuTl2B_i6xv_3RVPEHeUtFzsAjim3X/view?usp=sharing)

**Comment by SensehacK** [comment]
So they have played around with opacity of every element like **Basic Color** (h1-h6, span, text) & just change the primary prominent feature of UI with only 5 UIColors options.

By checking your video, only thing they change of the 3 UI Modes is the background color as the **basic contrast color** blends well with it.
Utilizing just one of the 5 UIColor options as "Icing on the cake" personalization. 

This approach is minimalist and I really appreciate it but its @jeremyphilemon decision or moderators whether we should steer in that direction.

**Comment by balrajsingh9** [comment]
@jeremyphilemon Can I take this one?

**Comment by SensehacK** [comment]
@balrajsingh9 Which colors are we choosing for the theme?

**Comment by balrajsingh9** [comment]
@SensehacK I would recommend going with the twitter colors as they work well with all kinds of background we would want to have, _light, dim, Lights out/Pitch black_, etc...

### RGBs for Primary Colors -  
- `rgb(29, 161, 242)`
- `rgb(255, 173, 31)`
- `rgb(224, 36, 94)`
- `rgb(121, 75, 196)`
- `rgb(244, 93, 34)`
- `rgb(23, 191, 99)`

### RGBs/Hex for **Background Colors** -
- Light - No change need, `rgb(255, 255, 255)`
- Dim - We can use the current one or `rgb(21, 32, 43)`
- Lights out/Pitch black - `rgb(0, 0, 0)`
- Graphite/Slate/Mat Grey - `#222831` 

More work to do on **font colors**. Haven't finalized yet, but we can take inspiration/copy from Twitter or any other good looking website.

We may refer to these palettes as well - https://colorhunt.co/palettes/dark

**Comment by SensehacK** [comment]
@balrajsingh9 Looks great!

**Comment by balrajsingh9** [comment]
@SensehacK As you have claimed this, are you going to work on it or you want to collaborate?

**Comment by SensehacK** [comment]
@balrajsingh9 So I'm new to React - I would love to collaborate as I still haven't found time to wrap my head around React state management.

Let me know what works for you.

You can raise an PR as well, I'll also work in parallel & always wanted to try Pair programming on Github fork branches? If you're up for it.

**Comment by balrajsingh9** [comment]
@SensehacK All in. 
/claim

I went through the source code to check how the current theme toggle is working and found that we are using [use-dark-mode](https://www.npmjs.com/package/use-dark-mode) lib to toggle the theme and switch the styles. This prevents us to implement a 3rd variant of background color to choose from, as we can only have either light or a dark theme and not the three variants as we discussed.

Would have worked -
The library provides us the option to pass in the config the class name for both the variants, which is `classNameDark`
Leveraging that config, we can show the user a modal to select the theme, we won't touch the light variant, but for the dark-variant, we can pass the class name acc to what the user chooses.

But the only problem is that we cannot update the config object after passing it initially 😞 

So all in all, we can either - 
- Keep using two variants, light and dark and just change the dark theme's `background-color` and also fix the font styles wherever we have less visibility issue or
- Rewrite the logic of theme toggling for using 3 background variants

**Comment by balrajsingh9** [comment]
Got a workaround. NVM 😀

**Comment by balrajsingh9** [comment]
Sneakpeak 💯 Almost ready.
Lots of lots of color modifications and easy on eyes.


<img width="1792" alt="Screenshot 2020-06-21 at 3 41 47 AM" src="https://user-images.githubusercontent.com/37571874/85212507-257f5680-b371-11ea-9108-86e334a73a98.png">
<img width="1792" alt="Screenshot 2020-06-21 at 3 41 37 AM" src="https://user-images.githubusercontent.com/37571874/85212525-4c3d8d00-b371-11ea-9140-1baeb1e2322b.png">

**Comment by SensehacK** [comment]
@balrajsingh9 Looks nice & where is the code base, I visited your fork didn't seem that you have pushed the code.

**Comment by balrajsingh9** [comment]
> @balrajsingh9 Looks nice & where is the code base, I visited your fork didn't seem that you have pushed the code.

Fixing lint issues. 
Pre-commit hook prevents me to commit before I fix the lint issues.

@SensehacK https://github.com/balrajsingh9/covid19india-react/tree/feat/theme-overhaul
