### ISSUE TITLE
Inconsistent select state and gender drop down in dark mode UI

### ISSUE THREAD

**Issue by Achal1607** [covid19india/covid19india.github.io#1421]
Description:
The select state and gender drop down are not properly recognized as drop down buttons because of their color. 

1. Go to 'Menu'
2. Click on 'Demographics'
3. See error

Expected Behavior:
Select state and gender should have white tab to properly recognize them as drop down menu. 
Just like in light theme UI. 

![Screenshot_2020-04-23-01-44-40-816_com android chrome](https://user-images.githubusercontent.com/55803675/80029237-211af680-8504-11ea-8308-140400c47e37.jpg)

Screenshots:
![Screenshot_2020-04-23-01-28-32-399_com android chrome](https://user-images.githubusercontent.com/55803675/80028702-262b7600-8503-11ea-9a74-f651b9740152.jpg)

**Comment by Achal1607** [comment]
I can fix it if u assign me..

**Comment by jeremyphilemon** [comment]
All yours :)
