### ISSUE TITLE
Two Important Metrics for Deep Dive: Case Fatality Rate and Case Recovery Rate

### ISSUE THREAD

**Issue by abhilaksh** [covid19india/covid19india.github.io#1425]
**Is your feature request related to a problem? Please describe.**
The metrics we have presently are great to understand the spread of coronavirus but don't help us understand the stress that's being placed on the medical system.

**Describe the solution you'd like**
In deep dive, we can add two metrics in a day-wise, state-wise manner:
1) CaseFatality Rate (%)=(Number of deaths due to COVID−19/ Number of confirmed cases of COVID−19)×100
2) Case Recovery Rate (%)=(Number of cases recovered from COVID−19/ Number of confirmed cases of COVID−19)×100

These are helpful parameters to understand medical system stress because states that have an increase in case recovery rate over time are going to be doing something better, whereas states that have an increase in fatality rate are where more help is going to be needed.

In terms of displaying it in the system, I would recommend two charts in deep dive:

1) One that plots, with a state-wise filter (with an option for all states selected by default), the number of deaths over time, displayed as percentages of the total confirmed cases on each day. 
2) One that plots, with a state-wise filter (with an option for all states selected by default), the number of recoveries over time, displayed as percentages of the total confirmed cases on each day. 

**Describe alternatives you've considered**
Presently, the first chart in Deep Dive (Total Cases) and the Statewise charts on the home page are giving indicators of the case fatality rate and case recovery rate, but they are not expressed in percentages over time, but in count over time. 

Counts are notoriously difficult to understand when looking at data statistically. Percentages are much better to understand trends. 

As an example to show the issue, consider two populations (let's say of 2 different states): 
State A has a population of 1,000 people; 300 of these people have the specified disease, 100 of whom die from the disease. In this case, the mortality rate for the disease is 100 ÷ 1,000 = 0.1, or 10 percent. The case fatality rate is 100 ÷ 300 = 0.33, or 33 percent. 

State B also has a population of 1,000 people; 50 people have the disease and 40 die from it. Here the mortality rate is 40 ÷ 1,000 = 0.04, or 4 percent; the case fatality rate, however, is 40 ÷ 50 = 0.8, or 80 percent. 

The incidence of death from the disease is higher in the first population (more people die in the first population), but the severity of the disease is greater in the second. If we were to only compare the counts of different states, we don't get an accurate picture.

This is also why I would warn against using the total population of a state and/or the country in any metrics like what some of the suggestions have.

**Additional context**
I would recommend calculating and displaying CFR and CRR to 3 decimal places.

**Comment by shubhamjain2998** [comment]
Yup, that's a very nice suggestion, would like to work on this.

**Comment by abhilaksh** [comment]
@shuklaayush @jeremyphilemon please do prioritise this at your earliest convenience since it's an easy solution that will have a great impact on our understanding of the severity of the disease in different regions.

**Comment by jeremyphilemon** [comment]
Addressed in #1496, keeping this open for discussion.

**Comment by abhilaksh** [comment]
Thanks for keeping this open for discussion @jeremyphilemon.

#1496 seems like a good idea. How are you planning on showing a single state's change in fatality and recovery rates over each day? 

I think there should be a time interval filter somewhere so we could scroll through the time intervals, and the ability to sort by any of the columns on the table. 

So, in terms of usability, as we scroll through the days/weeks/months on top of the table, the states (rows) can shift up and down the table in line with the sorted column. 

Further, after speaking to a couple of epidemiologists and some research, there are three statistical measures being used to track fatality rate: 

(1) Deaths/Total confirmed *100 (as specified above)
(2) Deaths/Total closed cases *100 [Closed cases are the sum of deceased and recovered cases.]
(3) Deaths/(Total confirmed cases 14 days prior) * 100 (Baud et al's method - source:https://www.thelancet.com/journals/laninf/article/PIIS1473-3099(20)30195-X/fulltext) 

In the initial phase of the epidemic, the number of closed cases is relatively small, and so the CFR calculated per closed cases (2) is an overestimate. By contrast, when the CFR is calculated per total cases (1), the numerator is underestimated, and thus the whole calculation becomes an underestimate.

Further, patients who die on any given day were infected much earlier, and thus the denominator of the mortality rate should be the total number of patients infected at the same time as those who died (estimated by (3)). Notably, the full denominator remains unknown because asymptomatic cases or patients with very mild symptoms might not be tested and will not be identified. Such cases, therefore, cannot be included in the estimation of actual mortality rates, since actual estimates pertain to clinically apparent COVID-19 cases.

This is why Baud's method takes the maximum incubation period of the virus (14 days) and uses the number of confirmed cases who would have been tested positive 14 days prior as the denominator, resulting in a more normalised representation of the Case Fatality Rate. 

So, for Delhi, for the tracker update timestamped 29 Apr, 02:53 IST,
(1) would come to 1.629%, a decrease from yesterday's rate of 1.737%. 
(2) would come to 4.770%, a decrease from yesterday's rate of 5.800%.
(3) would come to 3.422% (54 deaths up to today/1578 total cases on 15th April), which is mostly flat from the previous rate.

Once the virus is done with and all cases are closed, (1), (2), and (3) will all converge to give the real fatality rate of the epidemic. As of now, (1) is an underestimate, (2) is an overestimate, and (3) is somewhere in the middle depending on what incubation period we use (WHO estimates a 10-day window between the onset of symptoms and admittance to an ICU, and between 2 weeks and 8 weeks from infection to death - https://www.who.int/docs/default-source/coronaviruse/who-china-joint-mission-on-covid-19-final-report.pdf).

I'll check in again in a day or so if you have any questions, but it would be cool if we can get an option to choose between (1), (2) and (3) in the table!

**Comment by abhilaksh** [comment]
Do note that (3) is also not a perfect system. There isn't a perfect system.

**Comment by akumar90** [comment]
From a user's perspective, #2 is the easiest to understand, but you're right in that it overestimates the fatality rate. Also, since this is a daily calculation, it is more prone to daily fluctuations. Usually with variables prone to fluctuations, rolling averages are implemented to provide a better view of the increase or decrease in the severity.
This is where #3 would be more appropriate, with taking 14 days as the window. Although there has been more research to suggest that 14 days is not universal and there have been fluctuations on those as well. So, it's not a perfect system, but it is the best option we have at this time.
So, I would suggest going with #3 but we will need a disclaimer on the metric that it's a 14 day rolling average and since the asymptomatic population is not being accounted for in this (and there is no way to account for them anyway), the real numbers might be very different.

If we don't want to get into the nuances, we do still have the option of #2 but in my opinion, we should not call it "Fatality Rate", and rather just "percentage of cases resulting into deaths"
