### ISSUE TITLE
2 data are missing from the count details

### ISSUE THREAD

**Issue by yoghesh** [covid19india/covid19india.github.io#1427]
**2 data are missing from the report**
Patient id 4375 and 4933 are being excluded in all the reports. The reason is because it is missing state details in data source

**To cross verify**
New cases reported on 6th April - As per data is 485 and as per the report in website it is 484
New cases reported on 7th April - As per data is 573 and as per the report in website it is 572

**Screenshots**
![image](https://user-images.githubusercontent.com/4799043/80039170-cf2e9c80-8514-11ea-9cb1-ac2092a77cb1.png)

**Comment by jeremyphilemon** [comment]
cc @bee-rickey

**Comment by jeremyphilemon** [comment]
Please report data discrepancies in this form https://forms.gle/7NRSrbspW2a6pbm58, thanks :)
