### ISSUE TITLE
Remove icon disappears if a search value is not in the search results

### ISSUE THREAD

**Issue by manoj30075** [covid19india/covid19india.github.io#1430]
**Describe the bug**
When you enter a value in the search bar and if the value is not present in the search results the remove icon gets disappeared.

**To Reproduce**

1. Go to home page
2. Click on the search bar
3. Start typing
4. If the value that typed is not in search results the remove icon gets disappeared. 

**Expected behavior**
Remove icon in the search bar should appear if any value is present in the search bar
<img width="1440" alt="Screenshot 2020-04-23 at 7 52 57 AM" src="https://user-images.githubusercontent.com/13013166/80052167-a4a20b00-8537-11ea-8cf0-1377625420e1.png">
<img width="1440" alt="Screenshot 2020-04-23 at 7 53 15 AM" src="https://user-images.githubusercontent.com/13013166/80052188-b388bd80-8537-11ea-8458-2df5ab4437a7.png">

**Screenshots**

**Desktop (please complete the following information):**

Browser: Chrome, safari, firefox

**Smartphone (please complete the following information):**

**Additional context**

**Comment by siddesh-gundkanahalli** [comment]
change the close button which is dependent on results.length to searchValue.length and it work.thats all.

**Comment by jeremyphilemon** [comment]
This should essentially support clearing the input text and search results as well.

**Comment by harshalc** [comment]
You can assign me. I would like to work on this.

**Comment by pavanmehta91** [comment]
I can take this up

**Comment by manoj30075** [comment]
You can assign it to me.

**Comment by aishmittal** [comment]
Fixed it in PR #1489
