### ISSUE TITLE
Add a "Download reports as a PDF" button on homepage

### ISSUE THREAD

**Issue by chaha0s** [covid19india/covid19india.github.io#1433]
**Describe the solution you'd like**
We could add an option to download the current numbers of active,cured and dead cases from all states and districts as a timestamped PDF

**Comment by gyanendrapatro** [comment]
make sense you can assign it to me

**Comment by jeremyphilemon** [comment]
@gyanendrapatro Add it as a button here in demographics :)

<img width="113" alt="Screen Shot 2020-04-23 at 1 03 29 PM" src="https://user-images.githubusercontent.com/17938322/80087262-89e58b80-8563-11ea-8ab4-6f786b118c60.png">

**Comment by gyanendrapatro** [comment]
@jeremyphilemon but the ask is to download it as a whole report information right like statewise active , confirmed like what ever is there in table and map info all those right so shouldn't it be on home page itself, as demographic wont have this much detail

**Comment by gyanendrapatro** [comment]
And also if we put under demographic then people would think that the download content fk demographic page but we need content from main page all the detail right.like active and all.

**Comment by gyanendrapatro** [comment]
@jeremyphilemon could you please let me know where is the best place to put it.

**Comment by jeremyphilemon** [comment]
@gyanendrapatro I guess you're right. How are you planning on adding this feature? And how different would it be from generating a PDF normally by selecting "Save as" or under the "Print as PDF" option?

@chaha0s How exactly should the PDFs be formatted so that an option to allow for that is required? 

Right now json and csv formats are possible. I'm curious to know which use cases would require a PDF format.

**Comment by chaha0s** [comment]
@jeremyphilemon I think the PDF can include sitename , a timestamp and the main data table. 
When saving the pdf using print option, the formatting isn't proper. 
I can see map of India divided into two pages. 
The use case. I can't think of anything much. Just a normal user ( not a dev ) who wants to save data ?
This can be marked as low priority.

**Comment by gyanendrapatro** [comment]
Yes I guess the print as pdf shows every information not sure what information extra which needs to be added as download as PDF , let me know if anything needs to be added as pdf

**Comment by gyanendrapatro** [comment]
i checked for deep dive page if the analytics report someone want to download then the pdf is not coming good its overlapping may be that needs a fix , if someone wants to download as yes it makes sense for non dev people who wants to download it as pdf may be if they dont know how they can save from website
@jeremyphilemon @chaha0s

**Comment by harsshjain** [comment]
Can we add a button which gives result for previous day like this. It would be helpful for those who couldn't catch up previous day's update.

![IMG_20200521_100106](https://user-images.githubusercontent.com/65491327/82544161-530a9180-9b72-11ea-8358-0d9d3d9e118e.jpg)

**Comment by ghost** [comment]
still need help?
