### ISSUE TITLE
Improve telugu translation 

### ISSUE THREAD

**Issue by praveentiru** [covid19india/covid19india.github.io#1447]
**Is your feature request related to a problem? Please describe.**
Telugu translation on feature/localization branch looks like generated from Google Translate with numerous Nouns still holding English values

**Describe the solution you'd like**
Fix the translation to have everything in telugu

**Describe alternatives you've considered**
There is no other alternative

**Additional context**
Examples:

```
"Mahasamund": "Mahasamund",
"Surguja": "Surguja",
"Jashpur": "Jashpur",
```

**Comment by praveentiru** [comment]
I will work on this and place PR for the same.

**Comment by bee-rickey** [comment]
Hi @praveentiru we are currently in the process of reviving the translation/localisation PR, refer #432 and comment there?
