### ISSUE TITLE
Icons near State names indicating how states are performing

### ISSUE THREAD

**Issue by keshank** [covid19india/covid19india.github.io#1449]
**Describe the solution you'd like**

Red upward arrow near state names where number of active cases are higher then number of closed cases. ( eg :- Maharashtra )

Green downward arrow near state names where number of active cases are lower then number of closed cases. ( eg: - Andaman and Nicobar )

Crown icon / Star icon near state names where there are no active cases (eg :- GOA)

This could be very useful to visually understand how are states performing. Especially at later stages of pandemic this can give sense of confidence to people as states will be showing crowns or green arrow instead of red arrow

**Comment by bee-rickey** [comment]
This could be misleading since just a case count of active might not suggest the true picture.

**Comment by keshank** [comment]
@bee-rickey 
![Untitled](https://user-images.githubusercontent.com/63340632/80124018-457edd80-85ad-11ea-960c-adbbd5ba934d.png)
![Untitled2](https://user-images.githubusercontent.com/63340632/80124039-49aafb00-85ad-11ea-9832-f85a221a75b8.png)

What I meant to get the ratio of the active case to closed cases

if the ratio is greater than 1 then red arrow if the ration is less than 1 then green arrow.

if this seems misleading we can at least have star/crown icon for states which have no active case
