### ISSUE TITLE
Toggle switch for 'Scale Uniformly'

### ISSUE THREAD

**Issue by shuklaayush** [covid19india/covid19india.github.io#145]
The checkbox is difficult to tick on mobile. Adding a toggle switch instead would help. 
PS: Maybe change the text to 'Uniform Scaling' as well.

**Comment by VigneshMurugan** [comment]
Will pick this up

**Comment by sivasatvik** [comment]
Made a PR  #158 for this. It works for desktop and mobile versions. Suggestions?

**Comment by jeremyphilemon** [comment]
DUNZOOOO THANKS TO @sivasatvik!
