### ISSUE TITLE
The state page does not render from the top on mobile devices

### ISSUE THREAD

**Issue by tannakartikey** [covid19india/covid19india.github.io#1453]
**Is your feature request related to a problem? Please describe.**
This is only related to mobile devices.

When we scroll down and go to the state page of one of the bottom-most states the next page does not appear from the top. It seems like a blank screen and the user has to scroll up to see the content.

The attached GIF describes it best.

**Describe the solution you'd like**
The next page(the state page) should appear from the top.

**Describe alternatives you've considered**
n/a

**Additional context**
![ezgif com-crop (1)](https://user-images.githubusercontent.com/422544/80111900-1d3bb280-859e-11ea-9ecc-deb2ac3b2fb2.gif)

**Comment by Binu42** [comment]
@tannakartikey assign me i'll do it. same situation is for deepdive in desktop.

**Comment by tannakartikey** [comment]
@Binu42 assigned to you. Thanks
