### ISSUE TITLE
Age chart show percentage data

### ISSUE THREAD

**Issue by bhavinkotak07** [covid19india/covid19india.github.io#1455]
The Deep Dive sections show patients by age chart. Currently, only absolute numbers are reported but it can be modified to show data in terms of **percentage** for better analysis.

Solution: Hovering on the bar chart along with absolute numbers, data in percentage can be shown.
![Screenshot from 2020-04-23 21-31-28](https://user-images.githubusercontent.com/5495645/80121963-87f2eb00-85aa-11ea-8736-ba8a9e05e147.png)

Additional Context: I would like to work on the same. Please assign it to me.

**Comment by KaustubhDamania** [comment]
Yes, both percentage and absolute cases will look better.

**Comment by bhavinkotak07** [comment]
Please assign this task to me. I have attached the proposed change in a screenshot below.
![Screenshot from 2020-04-23 21-31-28](https://user-images.githubusercontent.com/5495645/80121459-f4211f00-85a9-11ea-9619-4dafe426b9ce.png)
