### ISSUE TITLE
Show more relevant statistics on state page

### ISSUE THREAD

**Issue by shubhamjain2998** [covid19india/covid19india.github.io#1456]
**Is your feature request related to a problem? Please describe.**
It will be good if a user will be able to see the statistics in percent if he goes to a specific state page, it depicts the performance of the state.

**Describe the solution you'd like**
A Section showing all the statistics, after the mini graph, a very rough idea of what I suggest is
![Screenshot from 2020-04-23 21-09-24](https://user-images.githubusercontent.com/30628775/80119315-28dfa700-85a7-11ea-8d5e-e50f6227fcdc.png)
##### Yaa definitely with much better styling.
And moreover, we can also showcase doubling rate, cases per million, daily average cases or daily average recoveries

**Additional context**
I would like to work on this if it feels relevant.

**Comment by bee-rickey** [comment]
See if the data can be a switch view? Maybe something like an advanced option or something?

**Comment by shubhamjain2998** [comment]
okay like a switch toggler for the detailed statistics.

**Comment by jeremyphilemon** [comment]
Here's a mockup I had made earlier for this. You can use this for reference! Essentially we can maintain a flex box container that allows adding more stats in the future too.

<p  align="center">
<img width="282" alt="Screen Shot 2020-04-11 at 6 08 09 PM" src="https://user-images.githubusercontent.com/17938322/80156521-ca2d2400-85cc-11ea-99e7-33f0008a06d8.png">
</p>

**Comment by shubhamjain2998** [comment]
@jeremyphilemon ya that's a nice idea to have a flexbox and your layout is also looking very decent.
I think that the flexbox below minigraph with toggler will be good, so a mobile viewer won't need to go down to see stats.
Here's a snippet of what I thought
![stat](https://user-images.githubusercontent.com/30628775/80211221-ec698500-8652-11ea-841a-ba62d8fbd8d1.gif)
![Screenshot from 2020-04-24 17-35-45](https://user-images.githubusercontent.com/30628775/80211230-f25f6600-8652-11ea-80cc-d630c961828a.png)
![Screenshot from 2020-04-24 18-00-53](https://user-images.githubusercontent.com/30628775/80212720-a5c95a00-8655-11ea-8955-319004b680ff.png)

Your final thoughts about it? I will put it below the district bar if you want there only. :smiley:
