### ISSUE TITLE
Gujarat - "Dahod vs Dohad"

### ISSUE THREAD

**Issue by mayankparmar2000** [covid19india/covid19india.github.io#1459]
For Gujarat In Left hand side list, it says "Dahod : 4", but right side in map it shows "Dohad : 0".

The issue may be you are using 2 different names for 1 single district ... 

![Dahod Error](https://user-images.githubusercontent.com/4045325/80124922-98a56000-85ae-11ea-86ee-907c7e994855.png)

**Comment by shuklaayush** [comment]
Duplicates #1408
