### ISSUE TITLE
Scrolling header for table

### ISSUE THREAD

**Issue by jeremyphilemon** [covid19india/covid19india.github.io#146]
**Is your feature request related to a problem? Please describe.**
User is unable to know the context of the table data fields when the header goes out of the screen. 

**Describe the solution you'd like**
Something like this:

<img src="https://miro.medium.com/max/1600/1*kXEEaxvKP_9xRT0HuqScTQ.gif">

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by satishsingh35** [comment]
@bnap00 apply sticky to all 'th', to get 'sticky' to work. 'sticky' does not seem to work on table element 

@jeremyphilemon Can you please add me as contributor to this project?

**Comment by jeremyphilemon** [comment]
@satishsingh35 This seems to have been patched, feel free to work on other available issues!
