### ISSUE TITLE
Wrong state count shown for new cases!

### ISSUE THREAD

**Issue by amitmeetu12** [covid19india/covid19india.github.io#1461]
Hi Team,
Thanks for the great work !

I just checked that, wrong state count is getting displayed under "Punjab".

The total count of new cases shown is 5 for Punjab, but under the cities, it's showing 6 for Jalandhar.

Please find the 
![screenshot-www covid19india org-2020 04 23-23_00_22](https://user-images.githubusercontent.com/5120192/80130927-0a81a780-85b7-11ea-9510-f4888930b4d9.png)
attached screenshot for the same.

**Comment by lakshmi14** [comment]
Its an api side issue, have raised an issue and working on it

**Comment by jeremyphilemon** [comment]
Please report data discrepancies in this form https://forms.gle/7NRSrbspW2a6pbm58, thanks :)
