### ISSUE TITLE
State, City and Services drop-downs selected value is not fully visible

### ISSUE THREAD

**Issue by dharmesh-m** [covid19india/covid19india.github.io#1469]
In Essentials section State, City and Services dropdowns selected value is not fully visible in the Chrome browser. (My browser Version 81.0.4044.122 (Official Build) (64-bit))

OS: Windows 10
Display Resolution: 2160 x 3840 (4k Portrait mode)  or 3840 x 2160 (4k Landscape mode)

<img width="1067" alt="DropdownValuesAreNotReadable" src="https://user-images.githubusercontent.com/5715772/80148535-2ec39100-8583-11ea-9dd0-9299ec46c49f.png">

**Comment by Abhinav-Mani** [comment]
Can you give some more details like screen resolution & OS .I was not able to replicate the problem.

**Comment by Geetakokate** [comment]
@dharmesh-m @Abhinav-Mani I'm able to reproduce the issue. Fixing it.

**Comment by shuklaayush** [comment]
Seems irrelevant now after the Essentials redesign
