### ISSUE TITLE
Refreshing cause webpage to be blank 

### ISSUE THREAD

**Issue by rajathsn** [covid19india/covid19india.github.io#147]
Refreshing cluster, helpful links and faq will results in blank page. ( home page is fine). 

Example screenshot attached 
![E3B1B12B-513B-4E67-90CD-3A7E02306528](https://user-images.githubusercontent.com/52188338/77611738-2a886180-6f4c-11ea-9960-ab77b5fdf6cf.png)
![4067AE46-FA0E-4377-9C3B-7E945B8095AB](https://user-images.githubusercontent.com/52188338/77611741-2c522500-6f4c-11ea-8afd-1c76ffeeb526.png)
![E51E0FAE-B64D-4452-8661-111CCFA797C6](https://user-images.githubusercontent.com/52188338/77611746-2d835200-6f4c-11ea-9c47-b3e7645f0084.png)

**Comment by yogeshvar** [comment]
+1

**Comment by KrishnaPravin** [comment]
@JunaidBabu  I guess latest build/index.html is not properly copied to build/404.html.

Are you still using GH Pages?

**Comment by shuklaayush** [comment]
Maybe related: tabs are not highlighted when going directly through links.

**Comment by KrishnaPravin** [comment]
> Maybe related: tabs are not highlighted when going directly through links.

Yes, It was not highlighted even before when directly going through the links. Because the links were highlighted only on click of the link.
```js
<Link to="/clusters" onClick={()=>{
            setView('Clusters');
}}>
```

**Comment by rajathsn** [comment]
Issue is resolved.

**Comment by Rajath-BeeLab** [comment]
Same bug/issue again.
The issue a raise only on iOS devices. 
Can be reproduced on any browser on iOS.
