### ISSUE TITLE
Modern toggle button in deepdive page

### ISSUE THREAD

**Issue by nayakrahul** [covid19india/covid19india.github.io#1471]
**Is your feature request related to a problem? Please describe.**
The toggle button in deepdive page is too simple and old-style.

**Describe the solution you'd like**
![Screenshot from 2020-04-24 03-14-03](https://user-images.githubusercontent.com/11428805/80152647-b3d99500-85d9-11ea-80b6-110f2beeb13e.png)

It will look like this and will also make changes in charts on clicking.

**Comment by lakshmi14** [comment]
I can take up this 👍

**Comment by lakshmi14** [comment]
@nayakrahul 

![image](https://user-images.githubusercontent.com/7721961/80176894-a6430000-8617-11ea-9104-c8ca74171b9e.png)


See if it works ?
