### ISSUE TITLE
Support notes as tooltips for district rows as well.

### ISSUE THREAD

**Issue by jeremyphilemon** [covid19india/covid19india.github.io#1472]
**Is your feature request related to a problem? Please describe.**
Yes, it can be hard sometimes when some rows are labelled differently to accommodate a special situation etc. where an explanation would be useful to people.

**Describe the solution you'd like**
Similar to the current approach for state notes. The API now also has notes appended in the district objects.
<img width="363" alt="Screen Shot 2020-04-24 at 3 03 44 AM" src="https://user-images.githubusercontent.com/17938322/80161185-395c4580-85d8-11ea-9220-b479aa9c377b.png">

cc @sudevschiz regarding questions about API.

**Comment by Abhinav-Mani** [comment]
You can assign me.  I would like to work on this.

**Comment by jeremyphilemon** [comment]
Awesome, all yours :)
