### ISSUE TITLE
Visually highlight the currently selected row in table

### ISSUE THREAD

**Issue by jeremyphilemon** [covid19india/covid19india.github.io#1473]
**Is your feature request related to a problem? Please describe.**

Currently we have indicators like for map (border) and timeseries graph (dropdown) to show the selected values, however, that's now the case for tables. Highlighting it could largely help to visually navigate around with ease.

**Describe the solution you'd like**
Highlight the rows that are selected. Essentially would have to use the same style as when row is in hovered state.

**Comment by lakshmi14** [comment]
Hello!!! I can take up this.
You mean the states table in the home screen right ?

**Comment by harishmathur** [comment]
Feel free to assign this to me.

**Comment by pavanmehta91** [comment]
I'm willing to take this up @jeremyphilemon Can you please show something visually what needs be done. Cos I can see the gray background on a row when a it's hovered for a particular state selection

**Comment by nayakrahul** [comment]
Hey @jeremyphilemon, I have raised a pull request #1482 for this feature. Can you review and see if this is what is required.

**Comment by jeremyphilemon** [comment]
Hey @lakshmi14, usually I'd assign the first person who requested to be assigned to the issue, but since we've already gotten a PR from @nayakrahul, I suggest we go with this since it's really needed at the earliest.

However, this is a problem we've noticed, and are currently working on a workflow that'll allow people who've requested to get assigned first to mark themselves as assigned to prevent people from hijacking the issue later on.

**Comment by lakshmi14** [comment]
Thanks @jeremyphilemon no problem have taken another enhancement and created pull request,  Please check and merge.
