### ISSUE TITLE
Active & Deceased count needed in District-wise

### ISSUE THREAD

**Issue by devdashboard** [covid19india/covid19india.github.io#1479]
**Is your feature request related to a problem? Please describe.**
Many of the standardized Covid Dashboard websites failed to display the count of Active, Deceased fellows in District-wise

**Describe the solution you'd like**
It will be Good if you can pull out and display 'Active', 'Deceased' count details per District of the respective states.

![image](https://user-images.githubusercontent.com/64152133/80178705-83ffb100-861c-11ea-8fe7-f2d8c554f7c3.png)

@jeremyphilemon : Website is lightweight and awesome!!

**Comment by shuklaayush** [comment]
Duplicates #675
