### ISSUE TITLE
Website hangs when searched for essentials on smartphone

### ISSUE THREAD

**Issue by nprabhav** [covid19india/covid19india.github.io#1486]
**Describe the bug**
Site crashes when we search for essentials on Smartphones.

**To Reproduce**

1. Go to Menu
2. Click on Essentials
3. Click on Search
4. Type anything in Search Keyword
5. See error

**Expected behavior**
At least it should return 'No results found' when the search fails or it should return say top x items related to the search.

**Screenshots**

![issue1](https://user-images.githubusercontent.com/17107647/80206067-554bff80-8649-11ea-8bd1-98fc91de6737.jpg)

**Smartphone (please complete the following information):**

- Device: OnePlus6T
- OS: Android 10 OxygenOS 10.3.2
- Browser Chrome 80.0.3987.149
- Version 80.0.3987.149

**Comment by raxhvl** [comment]
I can look into this.

**Comment by itsplavika** [comment]
The same issue is happening on chrome Mac as well, the page becomes unresponsive
<img width="1680" alt="Screenshot 2020-04-25 at 6 18 20 PM" src="https://user-images.githubusercontent.com/29068720/80280366-4173cc80-8721-11ea-992c-0d65c1eb6c41.png">

**Comment by nikita-11** [comment]
@ravindranrahul Are you working on this? This is a critical fix. Will need to add it soon.

**Comment by nikita-11** [comment]
Else we planned to disable search bar functionality for a while. If possible, Let me know the updates on this.

**Comment by raxhvl** [comment]
Yes, am working on this, meanwhile can we hotfix this by disabling search?

**Comment by raxhvl** [comment]
It would be ideal if we merge #1532 and i can add the fixes on this page too.

**Comment by jeremyphilemon** [comment]
@ravindranrahul 

>For issue #1486 solution might be the same which I have implemented.
Use the inbuilt useDebounce hook which is already defined in react-script - @chinmaydalvi
