### ISSUE TITLE
Search Bar gets hanged

### ISSUE THREAD

**Issue by Achal1607** [covid19india/covid19india.github.io#1488]
**Describe the bug**
Search bar gets hang while finding something

**To Reproduce**

1. Go to 'Home Page'
2. Click on 'Search'
3. Start Typing

Play around with the search, at some point it'll start to lag, and then hand completely. 

**Expected behavior**
Search Bar should work properly without hanging.

**Comment by pavanmehta91** [comment]
Can you please provide a screenshot/gif for the same. Also please check and post if anything is there in the Chrome/Firefox devtools console.

**Comment by shuklaayush** [comment]
Duplicates #1486

**Comment by chinmaydalvi** [comment]
@jeremyphilemon 

I would like to take this issue.

**Comment by chinmaydalvi** [comment]
@jeremyphilemon 

I will take this issue.

Claimed !!!

**Comment by jeremyphilemon** [comment]
Will reopen this again separately.
