### ISSUE TITLE
Updating district map based on current active cases.

### ISSUE THREAD

**Issue by np000** [covid19india/covid19india.github.io#1491]
**Is your feature request related to a problem? Please describe.**
Can we update the colour intensity level of a state's district based on current active cases for state's if district wise stats available?. In kerala Currently more active cases are in Kannur district. Which is updated in kerala government s tracker.

https://dashboard.kerala.gov.in

![Screenshot_2020-04-24-18-22-34-264_com android chrome](https://user-images.githubusercontent.com/26089883/80214954-51c07480-8659-11ea-840c-7ed7119ec5cd.png)
In Kasargod district active cases are less.
The current map of kerala in covid19tracker shows as below
![Screenshot_2020-04-24-18-28-57-577_com android chrome](https://user-images.githubusercontent.com/26089883/80215154-9e0bb480-8659-11ea-821e-bd87a9b9a4af.png)

**Describe the solution you'd like**
Updating the district map color shades based on current active cases for the states the same data is available. This is just a suggestion.

**Comment by shuklaayush** [comment]
Hi! You can now click on the coloured box to switch to Active cases map. I guess that addresses your concern.

![Peek 2020-04-24 18-37](https://user-images.githubusercontent.com/27727946/80215833-c21bc580-865a-11ea-92df-e36dbcc8562e.gif)

**Comment by np000** [comment]
I didn't know it's already available. This is great feature. Thanks for the update.
