### ISSUE TITLE
State Page | Link on Sources for Gujarat is not working.

### ISSUE THREAD

**Issue by jaykishanparikh** [covid19india/covid19india.github.io#1494]
**Describe the bug**
Go to the Gujarat State page. and Click on the 'As of 23 Apr per **source**'. LIke other state pages it should redirect to the source page (In GJ its state dashboard)

**To Reproduce**
1. Go to the Gujarat State page
2. Click on source link

**Expected behavior**
Click should redirect to Gujarat Gov Dashboard.

**Screenshots**
<img width="1530" alt="Screen Shot 2020-04-24 at 11 23 03 pm" src="https://user-images.githubusercontent.com/17736902/80217428-03c06680-8683-11ea-9928-5532b09f3c11.png">

Issue in all browsers, chanells

**Comment by jaykishanparikh** [comment]
Please assign this to me. I have fixed this bug on my local.

**Comment by jeremyphilemon** [comment]
I'm getting redirected to https://gujcovid19.gujarat.gov.in/uploads/pressbrief2304232020085856435.pdf. Seems to working fine. Thanks :)
