### ISSUE TITLE
Prevent graphs from changing on cursor hover

### ISSUE THREAD

**Issue by itssmutnuri** [covid19india/covid19india.github.io#1495]
**Is your feature request related to a problem? Please describe.**
When scrolling down to the graphs, if the cursor passes over the state list table, the graphs change to reflect the state my cursor is hovering upon. I've to always select "All States" from the list to get full country data or reload the page.

**Describe the solution you'd like**
It could be better to have such changes happen on clicking on a particular state, either on the map or in the table.

**Describe alternatives you've considered**
Alternately, a button to go to the country level view could be provided.

**Comment by shuklaayush** [comment]
Duplicates #1243
