### ISSUE TITLE
Allow Table sorting on essentials page

### ISSUE THREAD

**Issue by vishwac09** [covid19india/covid19india.github.io#1498]
**Enable Sorting on essentials Page Table**
User navigates to "/essentials" page, selects a state, city clicks on search. The result set can be large, but i want to sort out or group similar items by clicking on header to sort.

**Describe the solution you'd like**
I Propose Columns City, Category and Organisation to be sortable.

**Describe alternatives you've considered**
None.

**Additional context**
I also propose to enable search by City on the same page. Helpful if dataset it too large and filter using City.

If you find this Feature Request valid please assign it to me.

**Comment by shuklaayush** [comment]
Seems irrelevant now after the Essentials redesign
