### ISSUE TITLE
Dark mode map gradient visibility

### ISSUE THREAD

**Issue by acorreya** [covid19india/covid19india.github.io#1499]
**Describe the bug**
Map gradient color scheme needs to be tweaked in main page while using dark mode for visibility of low count states.

**To Reproduce**

1. Go to 'index' 
2. Scroll down to 'india map'

**Expected behavior**
Better visibility for states like Goa.

**Screenshots**
![2020_04_24_22_12_14](https://user-images.githubusercontent.com/3225091/80236424-985aa280-864a-11ea-8b8c-6f528c755eb3.jpg)

**Smartphone (please complete the following information):**

- Device: Mi A3
- OS: Android 10 stock/pure
- Browser Firefox
- Version 68.7.0

**Comment by jeremyphilemon** [comment]
Whoever claims this, please describe the strategy you would be using to tackle this :)

**Comment by plibither8** [comment]
The main issue here is poor contrast between the background and states with darker colour (lesser number of cases/deaths/etc.). Increasing border brightness might help.

In general I feel contrast around the entire website is lacking in dark mode that will definitely hinder accessibility.
