### ISSUE TITLE
Ayodhya district in Uttarakhand instead of Uttar Pradesh

### ISSUE THREAD

**Issue by ghost** [covid19india/covid19india.github.io#1502]
**Describe the bug**
The district Ayodhya should be present under Uttar Pradesh, but instead is shown under Uttarakhand in the table data.

**To Reproduce**
n/a

**Expected behavior**
District Ayodhya to be present under Uttar Pradesh and not Uttarakhand.

**Screenshots**
<img width="489" alt="Screenshot 2020-04-24 at 23 29 29" src="https://user-images.githubusercontent.com/22128987/80242790-8ea16100-8683-11ea-8576-723c476f4d05.png">

**Desktop (please complete the following information):**

- OS: MacOS
- Browser: FireFox Developer Edition
- Version: 76.0b8

**Smartphone (please complete the following information):**
n/a

**Additional context**

**Comment by pavanmehta91** [comment]
Is this the home page? Maybe it was a data issue or something. Seems fine to me now.

**Comment by bee-rickey** [comment]
It was an issue in the data entry side. All is good now.
