### ISSUE TITLE
Search in home page freezes

### ISSUE THREAD

**Issue by jeremyphilemon** [covid19india/covid19india.github.io#1511]
**Describe the bug**
Search bar gets hang while finding something

**To Reproduce**

Go to 'Home Page'
Click on 'Search'
Start Typing
See error
Play around with the search, at some point it'll start to lag, and then hand completely.

**Expected behavior**
Search Bar should work properly without hanging.

**Comment by chinmaydalvi** [comment]
Claimed

**Comment by chinmaydalvi** [comment]
Claimed

**Comment by chinmaydalvi** [comment]
claimied

**Comment by chinmaydalvi** [comment]
claim

**Comment by jeremyphilemon** [comment]
@chinmaydalvi reply with "/claim" :)

**Comment by raxhvl** [comment]
@chinmaydalvi issue is same as #1486 (assigned to me) & #1488

**Comment by chinmaydalvi** [comment]
@ravindranrahul Yes But will fix this.

**Comment by raxhvl** [comment]
Sure this is what i found, in search.js the following two block is recursive.
  ```
const essentialsAsync = (datums) => {
      // to handle async remote call on initial launch
      essentialsEngine.search(searchInput, essentialsSync);
    };
```
____
`essentialsEngine.search(searchInput, essentialsSync, essentialsAsync);
`

[Function Reference](https://github.com/twitter/typeahead.js/blob/master/doc/bloodhound.md#bloodhoundsearchquery-sync-async)
