### ISSUE TITLE
Latest update notification bell/icon shows wrong date

### ISSUE THREAD

**Issue by iamrajee** [covid19india/covid19india.github.io#1517]
**Describe the bug**
Pressing latest update bell on home page thrice(and thereafter) shows the wrong date.
**Note:** _I observed this bug at 02:35 hour on 25/4/2020. It seems we can only observe this bug at very begging of the day when a new date is included with no update yet._

**To Reproduce**
1. Go to home [page](https://www.covid19india.org/)
3. There is a bell icon below the search bar, press it thrice or more.
4. It shows the wrong date. 

**Bug Screenshots**
![BUG](https://user-images.githubusercontent.com/25712145/80273743-8af8f300-86f2-11ea-827e-0d80c92bbf55.jpg)

**Expected behavior**
![Expected behavior](https://user-images.githubusercontent.com/25712145/80273752-99470f00-86f2-11ea-8c32-1dc4d0c94a90.jpg)

**Smartphone (please complete the following information):**
- Device: [e.g. Realme 5 pro]
- OS: Android
- Browser: chrome
- Version: 81

**Comment by jeremyphilemon** [comment]
\available

**Comment by jeremyphilemon** [comment]
Closing this in favor of #1617
