### ISSUE TITLE
ZEIT automatic check/build failing

### ISSUE THREAD

**Issue by KrishnaPravin** [covid19india/covid19india.github.io#152]
**Describe the bug**
As the rate of new PRs has increased ZEIT builds are failing.

**To Reproduce**
1. Create a new PR

**Expected behavior**
A new build of the Website should be created and hosted by ZEIT

**Screenshots**
<img width="813" alt="Screenshot 2020-03-26 at 10 55 20 AM" src="https://user-images.githubusercontent.com/17372422/77613466-c6b46780-6f50-11ea-823b-7274377b3c2b.png">

**Desktop (please complete the following information):**
 - OS: All
 - Browser: All
 - Version: All

**Smartphone (please complete the following information):**
 - Device: All
 - OS: All
 - Browser: All
 - Version: All

**Additional context**

**Comment by shuklaayush** [comment]
Adding a temporary hack for reference.  
Force pushing the last commit again triggers a rebuild:
```
git commit --amend --no-edit
git push --force-with-lease
```
Do this after some time when the bot calms down.

**Comment by JunaidBabu** [comment]
Not an issue we can resolve at the moment
