### ISSUE TITLE
Navbar UI Issue

### ISSUE THREAD

**Issue by soumiknandi** [covid19india/covid19india.github.io#1524]
**Describe the bug**
On hovering mouse over navbar, it changes to 2 column view. 

**Expected behavior**
There is enough space to fit both the map and the table, yet its not visible when the navbar is not expanded, and visible when it is expanded.

![ezgif-6-e7e712cf8739](https://user-images.githubusercontent.com/23258575/80276913-3b71f180-8709-11ea-9239-87fb6ba182b5.gif)

**Desktop**

- OS: Linux mint
- Browser chromium
- Version 80.0.3987.163

**Comment by Binu42** [comment]
@jeremyphilemon assign it to me if it's get available
@soumiknandi can you tell about which system you are using and what is your screen size ? because i am also using linux and chromium browser, no situation like this is happening..
/claim

**Comment by soumiknandi** [comment]
Model : Lenovo G50-80
product: HD Graphics 5500
vendor: Intel Corporation
physical id: 2
bus info: pci@0000:00:02.0
version: 09
width: 64 bits
clock: 33MHz
capabilities: msi pm vga_controller bus_master cap_list rom
configuration: driver=i915 latency=0
resources: irq:48 memory:c0000000-c0ffffff memory:b0000000-bfffffff ioport:4000(size=64) memory:c0000-dffff
resolution : 1366 x 768 (16:9)
screen size : 39.62 cm (15.6 inch)
![Screenshot from 2020-04-25 16-43-40](https://user-images.githubusercontent.com/23258575/80278546-f18f0880-8714-11ea-8c47-77a524237d1d.png)

**Comment by Binu42** [comment]
@soumiknandi thanks, for all the information you shared. yeah, this problem is happening in this screen resolution. waiting for assignment @jeremyphilemon
