### ISSUE TITLE
Last updated time overlaps with the visit state button

### ISSUE THREAD

**Issue by shuklaayush** [covid19india/covid19india.github.io#1527]
**Describe the bug**
Last updated time overlaps with the visit state button on switching the map if the mouse is hovered to a different state before the map is able to change.

**To Reproduce**

1. Click on any state on the map
2. Swiftly move the mouse to any other state before the map changes

**Expected behavior**
The last updated time should not be shown on state maps since data is not available.

**Screenshots**
![Peek 2020-04-25 16-42](https://user-images.githubusercontent.com/27727946/80278453-f2736a80-8713-11ea-8056-7b06d69c3b0c.gif)
See top right

**Comment by sudevschiz** [comment]
Lol
