### ISSUE TITLE
Remove arrow icon in total row in table

### ISSUE THREAD

**Issue by nayakrahul** [covid19india/covid19india.github.io#1531]
**Is your feature request related to a problem? Please describe.**
The arrow icon in total row in table has no significance. It should be removed

**Describe the solution you'd like**
when the total props is true in row component, we will not show the arrow icon.

![Screenshot (46)_LI](https://user-images.githubusercontent.com/11428805/80281657-556ffc00-872a-11ea-84e5-bb474c070657.jpg)

**Comment by nayakrahul** [comment]
please assign it to me if it becomes available.

**Comment by kushal813** [comment]
@jeremyphilemon Could you please assign this to me?
