### ISSUE TITLE
State row should show up in a separate color(possibly green) when there are no active cases for that state

### ISSUE THREAD

**Issue by kushal813** [covid19india/covid19india.github.io#1533]
**Is your feature request related to a problem? Please describe.**
For states where there are no active COVID cases should be highlighted

**Describe the solution you'd like**
The state should be highlighted in green color

**Describe alternatives you've considered**
None

**Additional context**
<img width="1306" alt="Screenshot 2020-04-25 at 7 43 28 PM" src="https://user-images.githubusercontent.com/6009371/80282084-1e4f1a00-872d-11ea-9f03-6bf8dcb89d59.png">

**Comment by karankiri** [comment]
/claim Would like to work on this
