### ISSUE TITLE
Width of timeseries graph in state page is 100% for mobile devices

### ISSUE THREAD

**Issue by nayakrahul** [covid19india/covid19india.github.io#1536]
**Describe the bug**
Width of timeseries graph in state page is 100% for mobile devices. It should look same as that in homepage.

**To Reproduce**
Steps to reproduce the behavior (mobile device):

1. Go to State page of any state
2. Scroll down to timeseries graph
3. See that the width is 100% of the screen.

**Expected behavior**
Styling should be same as that of timeseries graph in homepage.

**Screenshots**
### State page
![Screenshot (50)](https://user-images.githubusercontent.com/11428805/80283847-76d7e480-8738-11ea-852b-68b8d82aed30.png)
### Homepage
![Screenshot (51)](https://user-images.githubusercontent.com/11428805/80283850-793a3e80-8738-11ea-871f-ee49c85ea521.png)

**Comment by nayakrahul** [comment]
It can be solved by wrapping everything related to timeseries graphs (header, modes, charts, pills) in TimeSeriesExplorer div like in homepage. It should solve the issue.

**Comment by jeremyphilemon** [comment]
@nayakrahul exactly, you got that right! Making this /available.
