### ISSUE TITLE
U have some problem. The covid cases is 0 in jorhat district of Assam. Instead those 8 confirmed are from golaghat district. Kindly correct it

### ISSUE THREAD

**Issue by raktim47** [covid19india/covid19india.github.io#1540]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jeremyphilemon** [comment]
Please report data discrepancies in this form https://forms.gle/7NRSrbspW2a6pbm58, thanks :)
