### ISSUE TITLE
Add district wise numbers for Active, Recovered and Deceased.

### ISSUE THREAD

**Issue by himanshumehta1114** [covid19india/covid19india.github.io#1541]
**Is your feature request related to a problem? Please describe.**
Right now districts under states have only confirmed numbers but don't show Active, Recovered and Deceased numbers.
<img width="480" alt="Screenshot 2020-04-25 at 10 49 51 PM" src="https://user-images.githubusercontent.com/25463496/80286105-1e5c1380-8747-11ea-8ce1-61f515188275.png">

**Describe the solution you'd like**
We can add Active, Recovered and Deceased columns in districts as well.
Like this:
<img width="497" alt="Screenshot 2020-04-25 at 10 51 11 PM" src="https://user-images.githubusercontent.com/25463496/80286137-4cd9ee80-8747-11ea-9b29-11c85afcea01.png">

**Additional context**
I would like to work on this. If this feels relevant.

**Comment by shuklaayush** [comment]
Duplicates #675

**Comment by himanshumehta1114** [comment]
[https://api.covid19india.org/state_district_wise.json](https://api.covid19india.org/state_district_wise.json)
District records with deltas' are available. So I can implement this

**Comment by shuklaayush** [comment]
@himanshumehta1114 We're cleaning up the data for districts. I'm putting this on hold until that's done.

**Comment by himanshumehta1114** [comment]
@shuklaayush cool thanks, can you assign the issue to me?

**Comment by KrishnaPravin** [comment]
fixed #1637
