### ISSUE TITLE
Trending graph for daily cases in a district 

### ISSUE THREAD

**Issue by Abhishekbhatia** [covid19india/covid19india.github.io#1543]
**Is your feature request related to a problem? Please describe.**

The information for number of cases in a district is shown for the present date only. It would be good to show the trend of cases in a line or bar graph for the number of cases reported in a district in the past. Monthly and 2-week graphs could be toggled just like the present functionality

**Describe the solution you'd like**

Line / Bar graph to show the trend of number of cases in a district.

**Describe alternatives you've considered**
None
 
**Additional context**

I tried to get the information from raw_data.json file. I wrote a python code to parse the data and print it in the form of "State => District => Date => No. of cases"
`"Gujarat": {
        "Surat": {
            "21/03/2020": 2,
            "23/03/2020": 1,
            "24/03/2020": 1,
            "25/03/2020": 2,
            "26/03/2020": 1,
            "29/03/2020": 1,
            "31/03/2020": 1,
            "01/04/2020": 2,
            "04/04/2020": 1,
            "05/04/2020": 3,
            "06/04/2020": 3,
            "07/04/2020": 3,
            "08/04/2020": 1,
            "09/04/2020": 1,
            "10/04/2020": 3,
            "11/04/2020": 1,
            "13/04/2020": 5,
            "14/04/2020": 9,
            "15/04/2020": 9,
            "16/04/2020": 37,
            "17/04/2020": 52,
            "18/04/2020": 13,
            "19/04/2020": 89,
            "20/04/2020": 27,
            "21/04/2020": 78,
            "22/04/2020": 68,
            "23/04/2020": 41,
            "24/04/2020": 6,
            "25/04/2020": 34
        },
        "Ahmadabad": {
            "20/03/2020": 2,
            "21/03/2020": 2,
            "22/03/2020": 3,
            "23/03/2020": 6,
            "28/03/2020": 3,
            "29/03/2020": 4,
            "30/03/2020": 1,
            "31/03/2020": 1,
            "01/04/2020": 8,
            "03/04/2020": 7,
            "04/04/2020": 7,
            "05/04/2020": 8,
            "06/04/2020": 11,
            "07/04/2020": 19,
            "09/04/2020": 59,
            "10/04/2020": 55,
            "11/04/2020": 46,
            "12/04/2020": 39,
            "13/04/2020": 38,
            "14/04/2020": 53,
            "15/04/2020": 77,
            "16/04/2020": 95,
            "17/04/2020": 78,
            "18/04/2020": 239,
            "19/04/2020": 239,
            "20/04/2020": 147,
            "21/04/2020": 125,
            "22/04/2020": 128,
            "23/04/2020": 151,
            "24/04/2020": 169,
            "25/04/2020": 182
        },
        "Vadodara": {
            "20/03/2020": 1,
            "21/03/2020": 1,
            "23/03/2020": 4,
            "28/03/2020": 2,
            "05/04/2020": 1,
            "06/04/2020": 2,
            "08/04/2020": 6,
            "09/04/2020": 4,
            "10/04/2020": 37,
            "11/04/2020": 36,
            "12/04/2020": 6,
            "13/04/2020": 6,
            "14/04/2020": 6,
            "15/04/2020": 8,
            "16/04/2020": 7,
            "17/04/2020": 16,
            "18/04/2020": 14,
            "19/04/2020": 22,
            "20/04/2020": 8,
            "21/04/2020": 11,
            "22/04/2020": 9,
            "23/04/2020": 7,
            "24/04/2020": 5,
            "25/04/2020": 7
        },
        "Gandhinagar": {
            "22/03/2020": 1,
            "23/03/2020": 1,
            "24/03/2020": 3,
            "26/03/2020": 3,
            "28/03/2020": 1,
            "31/03/2020": 1,
            "04/04/2020": 2,
            "10/04/2020": 1,
            "11/04/2020": 1,
            "14/04/2020": 1,
            "16/04/2020": 1,
            "23/04/2020": 1,
            "24/04/2020": 1,
            "25/04/2020": 4
        },
        "Kachchh": {
            "05/04/2020": 1,
            "10/04/2020": 2,
            "20/04/2020": 2
        },`

This may be helpful in creating the district level graph using the above data.

**Comment by shuklaayush** [comment]
Duplicates #1391
