### ISSUE TITLE
Dynamically set height of css grid when districts are expanded

### ISSUE THREAD

**Issue by jeremyphilemon** [covid19india/covid19india.github.io#1544]
**Describe the bug**
![Untitled copy](https://user-images.githubusercontent.com/17938322/80286793-1b0c5c00-8736-11ea-90b2-20868f9dfd59.png)

The districts on expansion have a grid rule attached to it, however, due to a fixed height the width overflows. The workaround is using scroll to handle the overflow.

**To Reproduce**

1. Go to any Uttar Pradesh state page
2. Click on view all under top districts

**Expected behavior**
Ideally the height shouldn't be fixed, and it should expand dynamically keeping the no. of columns constant at three. The solution should eliminate the need to scroll.

**Comment by vivekvroy** [comment]
When we click on View All Button, the label **"Top Districts"** should be updated to **"All Districts"**

**Comment by nayakrahul** [comment]
> When we click on View All Button, the label **"Top Districts"** should be updated to **"All Districts"**

Raise an issue for this. I cam take this up if it becomes available.
