### ISSUE TITLE
Please add percentage information to atleast India level numbers. 

### ISSUE THREAD

**Issue by imohitkr** [covid19india/covid19india.github.io#1553]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jeremyphilemon** [comment]
Could you please elaborate on what percentage information?

**Comment by imohitkr** [comment]
Like percentage of death in all cases , percentage of people cured out of all cases , percentage of death among closed cases e.t.c

**Comment by imohitkr** [comment]
Implementation done.
