### ISSUE TITLE
Add a positive indicator for states that hasn't had new confirmed cases the past five days

### ISSUE THREAD

**Issue by jeremyphilemon** [covid19india/covid19india.github.io#1556]
**Is your feature request related to a problem? Please describe.**
Yes, currently bar graphs for states who did not have any new confirmed cases show no data.

<img width="75%" alt="Screen Shot 2020-04-26 at 5 41 06 AM" src="https://user-images.githubusercontent.com/17938322/80296260-05248880-8782-11ea-963f-471e17a7b7ce.png">

**Describe the solution you'd like**
Instead we can show this:

<img width="75%" alt="Screen Shot 2020-04-26 at 5 47 07 AM" src="https://user-images.githubusercontent.com/17938322/80296273-1a011c00-8782-11ea-96a1-f317cc949f5b.png">

**Additional context**
You can use the style used to display the disclaimer boxes around the site.

###### Based on #1533, but on state pages instead on the table.

**Comment by karankiri** [comment]
/claim would love to work on this
