### ISSUE TITLE
Growth Rate

### ISSUE THREAD

**Issue by shouviksmazumdar** [covid19india/covid19india.github.io#1560]
Growth rate is an important metric that everyone would love to track

- Day to Day growth Rate
- Rolling 7 days growth rate
- Doubling Rate 
- Progression of Doubling Rate
- Prediction of numbers in the next 30 days

All these can be calculated from the data source. 

If you accept PR from public , I can volunteer to write this quick snippet. If you have already started working in this , it is helpful.

**Comment by bee-rickey** [comment]
Already in works. At least a basic tabular view of this should be out soon.
