### ISSUE TITLE
Incorrect deceased data for Kerala

### ISSUE THREAD

**Issue by isonso** [covid19india/covid19india.github.io#1566]
**Describe the bug**
Number of deceased for Kerala is 4 while actual value is 3 (as of today, 26-Apr)

**To Reproduce**

This is visible in the home page itself - under Kerala.

**Expected behavior**
Deceased value should be '4'. As per data in 'https://api.covid19india.org/states_daily.json', it should be 3 as well.

**Screenshots**
NA

**Desktop (please complete the following information):**
NA

**Smartphone (please complete the following information):**
NA

**Additional context**

**Comment by JunaidBabu** [comment]
![image](https://user-images.githubusercontent.com/1820279/80304774-21acd900-87f3-11ea-97d8-8f8a642dc5ac.png)

**Comment by jeremyphilemon** [comment]
^Hope this resolves :)
