### ISSUE TITLE
India map not visible in dark mode

### ISSUE THREAD

**Issue by harivnair** [covid19india/covid19india.github.io#1567]
**Describe the bug**
On the bottom left side, on changing to night/dark mode, the India Map visibility goes away. However, mouse hover suggests elements are present.

**To Reproduce**
1.  Go to the bottom left corner.
2. Toggle to dark mode. 
3. See India Map then.

**Expected behavior**
The map should visible as in light mode with a complementary theme.

**Screenshots**
<img width="1330" alt="Screenshot 2020-04-26 at 1 59 24 PM" src="https://user-images.githubusercontent.com/42058479/80302203-3aeb6080-87c6-11ea-96bc-1cd8c4934ba0.png">

**Desktop**

- OS: [MacOS Catalina]
- Browser [Mozilla Firefox]
- Version [76.0b8(64 bit)]

**Comment by shuklaayush** [comment]
@harivnair Thanks for reporting! It should be fixed now :)
