### ISSUE TITLE
New Cases are by default marked female if details awaited

### ISSUE THREAD

**Issue by tanag22** [covid19india/covid19india.github.io#157]
I've noticed new Patients are marked to b female when details are awaited. This causes wrong impression that females are more prone to the virus.
Set a neutral gender if not confirmed.

**Comment by tanag22** [comment]
issue seen specifically for Chhatisgarh Paitents

**Comment by Rajesh-Narayanappa87** [comment]
I want to take it, but I am unable to find bug.. could you add more context to it pls.

**Comment by JunaidBabu** [comment]
Different project. Report the issue here https://github.com/someshkar/covid19india-cluster

Closing.
