### ISSUE TITLE
Include a trend line to show with different teams lines

### ISSUE THREAD

**Issue by Nikhiljoseph31** [covid19india/covid19india.github.io#1573]
**Is your feature request related to a problem? Please describe.**
Indicate a trend line for future dates indicating how the graphs will look with respect to different doubling rates

https://www.google.com/amp/s/www.theverge.com/platform/amp/2020/4/2/21201832/novel-coronavirus-covid-19-best-graphs-tracking-data

This site has such a graph.

**Comment by shuklaayush** [comment]
Can you directly post the graph, please?

**Comment by Nikhiljoseph31** [comment]
![Screenshot_20200426-182018_Chrome](https://user-images.githubusercontent.com/63017808/80308112-a9dab080-87ea-11ea-90c7-3def1bf27840.jpg)
