### ISSUE TITLE
Feature : Deepdive Charts expanded view

### ISSUE THREAD

**Issue by vishwac09** [covid19india/covid19india.github.io#1574]
**Is your feature request related to a problem? Please describe.**
A feature request to be incorporated, allowing charts to expand in a modal for better and bigger view.

**Describe the solution you'd like**
When viewing the deepdive page, i suggest providing an option to view the corresponding Chart as expanded.
![co](https://user-images.githubusercontent.com/7726776/80307143-f3c09800-87e4-11ea-81af-2e8e572a6da4.gif)

**Describe alternatives you've considered**
None

**Additional context**
Added package **react-modal** to accomplish this, created a new component modal-wrapper in _"src/components/Charts"_ . There are few things remaining to work just like adding support for Dark mode etc
Let me know if there are any suggestions and we should proceed with this or not.

**Comment by saberprashant** [comment]
@vishwac09 
This looks good, but, any thoughts on mobile view?
Because I think most of the users use mobile to view this and adding a modal view will look the same as it is right now(as there is not enough width in portrait mode).

**Comment by vishwac09** [comment]
@saberprashant yes i did thought about this and in mobile view i am hiding this. Checking the screen width and deciding whether it is a desktop or not.

**Edit 1** 
Added module react-device-detect which provides options isBrowser, isTablet have added this conditional checking in ""src/components/Charts/modal-wrapper.js" file. Allowing view only on tablet and dektops.
