### ISSUE TITLE
Style changes for Updates list on Home page

### ISSUE THREAD

**Issue by saberprashant** [covid19india/covid19india.github.io#1575]
**Describe the bug**
It's not a bug, but a UX problem. When a user clicks on bell icon for updates, then, a list opens directly which looks a little abrupt. It doesn't look good with the overall experience of the web app.

**To Reproduce**

1. Go to "Home page"
2. Click on "Bell icon under Search Box"
3. "Updates list" will open abruptly.

**Expected behavior**
We can add a good transition to give it a smooth effect.

**Screenshots**
Mobile
![image](https://user-images.githubusercontent.com/20706536/80307465-d42a6f00-87e6-11ea-8768-76f723ade277.png)

Web
![image](https://user-images.githubusercontent.com/20706536/80307501-1653b080-87e7-11ea-8bf7-ad2acc0f3d34.png)

**Desktop (please complete the following information):**

- OS: MacOS
- Browser: Chrome
- Version: 80.1

**Smartphone (please complete the following information):**

- Device: Note 8
- OS: Android
- Browser: Chrome
- Version: 80.1

**Additional context**
We can finalize the transition, but I think a little bit of "ease-in" would help.
We also have options for React transitions.

**Comment by jeremyphilemon** [comment]
This would be an interesting fix because adding transitions on mount is easy, but on dismount we'll have to slow down the dismount in order for the transition to complete. I think a hook from `react-use` must be available for the delayed dismount. Animation can either be added using `animejs` or pure css.

Making this /available.

**Comment by Akshantjain** [comment]
Hi @jeremyphilemon 
I have an idea to solve this issue.
I would be able to manage it using material design.
Let me claim this issue.

**Comment by saberprashant** [comment]
Hey @Akshantjain ,
Thanks for showing interest in this issue.
Well I did submit a PR for this already like a month back,
[https://github.com/covid19india/covid19india-react/pull/1618](https://github.com/covid19india/covid19india-react/pull/1618)

**Comment by Akshantjain** [comment]
oh ok
thanks for a reply
