### ISSUE TITLE
Total number of confirmed cases are incorrect

### ISSUE THREAD

**Issue by ysingla** [covid19india/covid19india.github.io#1577]
**Describe the bug**
Total number of confirmed cases are incorrect. Ministry of health has reported 26,917 cases as of Apr 26 5PM. Here it is showing 26,740. Also number of cases per day is quite different than ministry of health

**To Reproduce**
Visible on website home page

![c2](https://user-images.githubusercontent.com/38974607/80308573-659cdf80-87ed-11ea-84d2-8d9e1ec1873d.PNG)

![Capture](https://user-images.githubusercontent.com/38974607/80308496-08a12980-87ed-11ea-8993-afb5c224c1e2.PNG)

**Comment by ackr-8** [comment]
Same issue

**Comment by ackr-8** [comment]
Please update the count

**Comment by shuklaayush** [comment]
Please report data discrepancies using [this form](https://forms.gle/MLeSrdwRuf8AjFkp9). Thanks! :)
