### ISSUE TITLE
Color shade coming up wrong

### ISSUE THREAD

**Issue by rmmaitrey** [covid19india/covid19india.github.io#1578]
**Describe the bug**
There is something wrong with colors. As I understand darker color represent higher number.
So After Maharastra Gujarat is on second number in terms of positive cases. In map I can see that Tamilnadu is having darker color while Gujarat is in light shade so looks like something wrong with data on calculation. 

**Screenshots**
![image](https://user-images.githubusercontent.com/21305113/80309615-cc24fc00-87f3-11ea-8a6a-53ae41106f39.png)

**Comment by shruti-14** [comment]
Hi @rmmaitrey, the green color stands for recovered cases, and since tamilnadu has second largest number of recovered cases it is darker than gujrat.

**Comment by rmmaitrey** [comment]
Right it was my bad. I didn't knew that it is preserving the last selected state.
