### ISSUE TITLE
[BUG][UI] Grid view of expanded districts is breaking for mobile screens

### ISSUE THREAD

**Issue by SubhamZoman** [covid19india/covid19india.github.io#1580]
**Describe the bug**
In mobile when switching to an expanded view of districts, the second column of the grid creates extra space thus breaking the mobile-friendly UI.

**To Reproduce**
1. Go to West Bengal State page
2. Click on `View All` button in `Top Districts` section.

**Expected behavior**
Second column in grid should be visible within the screen max-width.

**Screenshots**
<img width="364" alt="Screenshot 1942-02-06 at 8 27 37 PM" src="https://user-images.githubusercontent.com/38680964/80311444-47d77680-87fd-11ea-922a-d5e3c70b2d30.png">

**Comment by shuklaayush** [comment]
Duplicates #1544
