### ISSUE TITLE
Logarithmic scale can't have zero as y value.

### ISSUE THREAD

**Issue by nayakrahul** [covid19india/covid19india.github.io#1585]
**Describe the bug**
A logarithmic axis can only plot positive values. There simply is no way to put negative values or zero on a logarithmic axis.
https://blog.datawrapper.de/weeklychart-logscale2/
There are few scenarios where the y-value is always 0 like in case of Sikkim where there are no cases till now. Thing is we can't plot zero in logarithmic scale. Refer to the screenshot to understand it more clearly. The y-axis value is at 1 which is incorrect. This is happening when we try to plot 0 on logarithmic axis.

**To Reproduce**

1. Go to state page of Sikkim
2. Scroll down to timeseries graph
3. Turn on logarithmic scale mode
4. See that the graph shows 1 but it is actually 0.

**Expected behavior**
when y-axis value is 0, we should not plot anything on graph because logarithmic axis can't plot zero and negative values.

**Screenshots**
![Screenshot (54)_LI](https://user-images.githubusercontent.com/11428805/80315279-1322e980-8814-11ea-9baf-81088e53fb30.jpg)

**Comment by nayakrahul** [comment]
Please assign me if it becomes available.

**Comment by nayakrahul** [comment]
@shuklaayush I need suggestion for this. Now 0 is plotted as 1 in logarithmic axis. Shall we show 0 as 0.1 in logarithmic scale? If we do this, the transition from 1 to 0 or 2 to 0 or vice-versa will be visible in graph. If we just remove 0's from logarithmic graph, line chart will just stop at 1 and not progress ahead until some positive number comes. For now, transition from 1 to 0 is also not visible in chart like in Goa state rather 1 and 0 are on same height from bottom.

**Comment by shuklaayush** [comment]
Yeah, handling zeros in a log scale is a pain. You can try starting the scale from 0.1 instead of 1. I'm just afraid that it might lead to a lot of extra empty space at the bottom.

**Comment by nayakrahul** [comment]
@shuklaayush yeah, it will lead to a lot of extra empty space at the bottom. I made domain min and domain max different which fixed the chart when every value is 0 like in sikkim. But still 1 and 0 are shown as same on chart. Please check the PR #1605 .
