### ISSUE TITLE
Support zoom for MapExplorer

### ISSUE THREAD

**Issue by jeremyphilemon** [covid19india/covid19india.github.io#1587]
**Is your feature request related to a problem? Please describe.**
People get frustrated when it comes to clicking on small states/UTs like Delhi, Puducherry, Andaman and Nicobar islands from the map. 

**Describe the solution you'd like**
Zoom in support.

<p align="center">
<img width="363" alt="Screen Shot 2020-04-26 at 9 42 11 PM" src="https://user-images.githubusercontent.com/17938322/80316981-aa367400-8809-11ea-8698-c6238949ef2a.png">
</p>

###### Relevant #485

**Comment by jeremyphilemon** [comment]
@shruti-14 Hey thanks for claiming the issue, are you still working on this or shall I open it up again?

**Comment by shruti-14** [comment]
You can re-open it, sorry for the delay, as I am new to this D3 library.

**Comment by shubhamjain2998** [comment]
I would like to work on this if it gets available.

**Comment by munna** [comment]
@jeremyphilemon  We can make this map more intractive using library like openlayer/leaflet. I would love to contribute here. 
These library will help user to navigate smoothly.
