### ISSUE TITLE
Missing Daman and Diu leading to console errors on state page

### ISSUE THREAD

**Issue by Binu42** [covid19india/covid19india.github.io#1590]
**Describe the bug**
when selecting daman and diu from drop down or navigating for D & D from search result blank screen is apearing with errors. i think this is happening because we don't have D & D json map.

**To Reproduce**
go to https://www.covid19india.org/state/DD

**Expected behavior**
it should either show details about daman and diu if available or daman and diu shouldn't be in dropdown options, but it should not show blank screen.

**Screenshots**
![D D](https://user-images.githubusercontent.com/45959932/80317217-158b4080-8820-11ea-8d00-04a1680f82c0.gif)

**Desktop (please complete the following information):**
this problem is common everywhere.

**Comment by Binu42** [comment]
assign it to me i'll fix it, if you will make it available :peace_symbol:  and also suggest which kind of fix will be better.

**Comment by lakshmi14** [comment]
HI @Binu42/ @jeremyphilemon  , 

The problem being no value for Daman & Diu in MAP_META in the constants also no json file in public/maps directory for Daman & Diu. Screenshots below. Adding those will fix the issue !

src/constants.js
![image](https://user-images.githubusercontent.com/7721961/80401379-e1745600-88d9-11ea-9f94-34594b9787c6.png)

public/maps
![image](https://user-images.githubusercontent.com/7721961/80401468-010b7e80-88da-11ea-930a-e3320a3de3b1.png)

**Comment by animesh-tarodia-sp** [comment]
Before going any further on this issue, issue #1160 must be resolved first.

**Comment by shuklaayush** [comment]
Fixed via 6a801d6f41fd26e7c9725a4c248ae24b03f533ee
