### ISSUE TITLE
Active cases wrong for haryana

### ISSUE THREAD

**Issue by raghavkhurana** [covid19india/covid19india.github.io#1593]
No. Of active cases are mentioned wrong for haryana as confirmed=296 Active=79 Recovered=199 Decreased=3 does not add up! And on the haryana bulletin it says Active=94

**Comment by vsasvipul0605** [comment]
- There are various **sources** that are tracking and aggregating _coronavirus_ data. They update at different times and may have different ways of gathering data.

- This **data** changes rapidly and might not reflect some cases still being reported.

**Comment by raghavkhurana** [comment]
okay!
