### ISSUE TITLE
Number of recovered cases in districts of tamilnadu is not equal to total number of recovered cases in tamilnadu.

### ISSUE THREAD

**Issue by subashiniu** [covid19india/covid19india.github.io#1594]
**Describe the bug**
Number of recovered cases in each district of TamilNadu is not equal to the total number of cases in TamilNadu.

**To Reproduce**

1. Go to 'HomePage'
2. Click on 'TamilNadu'
3. Click on 'Visit state page'
4. Click on 'Recovered cases'
5. See the count shown on map for each state and check with total count

**Expected behavior**
Number of recovered cases in each district of TamilNadu should be equal to the total number of cases in TamilNadu.

**Desktop (please complete the following information):**

- OS: iOS
- Browser - Chrome
- Version - 81.0.4044.122

**Comment by shuklaayush** [comment]
Looks like it's fixed now :)
