### ISSUE TITLE
Number of cases is not updated in map as data

### ISSUE THREAD

**Issue by fantops** [covid19india/covid19india.github.io#1595]
**Describe the bug**
Number of Cases not updated in map with the data populated. Incase of Bihar observed, some districts still showing 0 even there are cases

**To Reproduce**
Scroll to maps go to location and compare with data populated in list

**Comment by shuklaayush** [comment]
Please give the name of a district as an example, so that we can reproduce.

**Comment by fantops** [comment]
Check for Munger and Kaimur Bhabhua in Bihar for example , even you can check for bhopal and khandwa, Indore too in MP

**Comment by shuklaayush** [comment]
Might've been happening because of district name mismatches. Should be fixed now
