### ISSUE TITLE
Get Location of the user and display the Infection stats of their city.

### ISSUE THREAD

**Issue by gopaljigaur** [covid19india/covid19india.github.io#1598]
**Is your feature request related to a problem? Please describe.**
I would like to see the coronavirus cases in my city as soon as I open the webpage, instead of selecting it from the list.

**Describe the solution you'd like**
There can be a section in the top right of the homepage which will display the infected, recovered, deceased and tested stats of the user's current location or city. Get the location of the user when they open the webpage and display the details on the top right or below the country stats (above the map).

**Describe alternatives you've considered**
An alternative would be letting the user set his/her location and showing them the data if they prefer to.

**Additional context**
No additional context

**Comment by anuragakella** [comment]
I'd like to work on this, can anyone let me know how I can get started?
