### ISSUE TITLE
Page is displayed with 404 message in Brave browser

### ISSUE THREAD

**Issue by vivek1996** [covid19india/covid19india.github.io#1602]
**Describe the bug**
The browser  shows the  404 message (Still  the page displayed) when the page is reloaded on routes other than '/'.

**To Reproduce**

1. Go to some route eg:  'https://www.covid19india.org/demographics'
2. Reload the page.
3. The page is shown with the message as 'Sorry that page is missing'.

**Expected behavior**
Page should be displayed without that error banner.

**Screenshots**
![image](https://user-images.githubusercontent.com/15796694/80378272-0953c180-88ba-11ea-832f-d5871d17b349.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser Brave Browser
- Version Version 1.7.98 Chromium: 81.0.4044.113 (Official Build) (64-bit)

**Comment by devtechnocode** [comment]
![covid19india_demograpics](https://user-images.githubusercontent.com/52890488/80383070-bb8e8780-88c0-11ea-8b7a-0872cb76dc1c.png)
It is working fine on brave browser.Also it's loading the page with '/' and without these also.So,kindly close the issue.

**Comment by vivek1996** [comment]
> 
> 
> ![covid19india_demograpics](https://user-images.githubusercontent.com/52890488/80383070-bb8e8780-88c0-11ea-8b7a-0872cb76dc1c.png)
> It is working fine on brave browser.Also it's loading the page with '/' and without these also.So,kindly close the issue.

Could you please refresh the page on the 'https://www.covid19india.org/demographics' route and check.

**Comment by devtechnocode** [comment]
Yes, I checked it. It's working Fine.

**Comment by vivek1996** [comment]
> 
> 
> Yes, I checked it. It's working Fine.

ok may be the issue with the brave for windows.

**Comment by har2008preet** [comment]
Its also happening on mac 
![image](https://user-images.githubusercontent.com/7850138/81778036-adbb4200-950f-11ea-91f5-cf4c36407798.png)
**NOTE**: It is 404 in chrome as well
