### ISSUE TITLE
Enhancement - UX: Serial number for States and districts

### ISSUE THREAD

**Issue by mkesavan13** [covid19india/covid19india.github.io#1604]
**Is your feature request related to a problem? Please describe.**
It felt so difficult to find on what position my state is at although I get to sort. I had to count manually.

**Describe the solution you'd like**
We can have serial numbers state wise and district wise of each state so that it is easy to see the position of a state. 

**Describe alternatives you've considered**
There could be no alternative to this.

**Additional context**
I have this tried this one out and code ready and so I'd like to claim this issue to be assigned to myself.

**Comment by mkesavan13** [comment]
Although I've mentioned once in the original issue request, adding it here as well.

I'd like to /claim this issue myself if the reviewer sees this one to be a valid one.

**Comment by venunalla7731** [comment]
After going through https://www.covid19india.org/ , felt that serial number could help to sort by number for state and district.
From a developer perspective, I wanted to suggest, that to make sure those serial numbers are assigned for each entity so that when the filter button (up/down arrow) is clicked it automatically resets.

**Comment by mkesavan13** [comment]
Hi @venunalla7731,

By resets, do you mean that, if I click on a particular column sort, the serial number should still say 1,2,3 and not get rearranged as well like 32,31,30?

**This is a screenshot that is sorted descending by confirmed cases:**

<img width="1665" alt="1" src="https://user-images.githubusercontent.com/8044050/80431902-595d7300-8910-11ea-8815-96ea24cbcc72.png">

**This is a screenshot that is sorted descending by active cases:**

<img width="1670" alt="2" src="https://user-images.githubusercontent.com/8044050/80431910-5ebabd80-8910-11ea-8144-ed29089d22ef.png">

This way, for example if you take MP in the screenshot, it is in 5th position of total number of confirmed cases where as it is in 4th position of total number of confirmed cases. 

Is this the same thing you mentioned or am I missing something? Kindly let me know.

**Comment by venunalla7731** [comment]
Yes, that's true.
once everyone agrees, you can move forward.
Thanks.

**Comment by mkesavan13** [comment]
Great. Thank you for your review.

**Comment by bee-rickey** [comment]
@mkesavan13 What does this look like on a mobile screen?

**Comment by mkesavan13** [comment]
Hi @bee-rickey 

Please find below the screenshots of the same,

**State wise Confirmed Descending order -** 
![Confirmed desc](https://user-images.githubusercontent.com/8044050/80863702-aee0a980-8c9b-11ea-90e1-2e6dc86d46c6.png)

**District wise Confirmed Descending order -** 
![State Confirmed desc](https://user-images.githubusercontent.com/8044050/80863704-b0aa6d00-8c9b-11ea-8df5-39e555533f41.png)

**State wise Active Descending order -** 
![State Active desc](https://user-images.githubusercontent.com/8044050/80863703-af794000-8c9b-11ea-9f92-dac5c42a5161.png)

**District wise Confirmed Descending order -** 
![Active desc](https://user-images.githubusercontent.com/8044050/80863696-ab4d2280-8c9b-11ea-8497-3e42d66d9878.png)

**Comment by mkesavan13** [comment]
Hi @bee-rickey,

Can I open a PR for this so that you can see how it looks by yourself?

Looking forward. Thank you.

**Comment by mkesavan13** [comment]
Hi @bee-rickey,

I am still waiting for an update from you. Kindly let me know.

Thank you.
