### ISSUE TITLE
Feature : Table on home page showing confirm cases district-wise, should also show active cases, recovered and decreased cases district-wise.

### ISSUE THREAD

**Issue by devtechnocode** [covid19india/covid19india.github.io#1607]
**Is your feature request related to a problem? Please describe.**
No, it is related to enhance the home page by, showing the details of the active cases, recovered and decreased cases district-wise.

**Describe the solution you'd like**
By adding a column of number of active, recovered and decreased cases.

**Describe alternatives you've considered**
Alternatively, it can show the same information, once the particular state map is open and district is selected there, itself it can show the active cases, recovered and decreased cases.

**Additional context**
![covid1](https://user-images.githubusercontent.com/52890488/80390283-da454c00-88c9-11ea-84e2-f6b364c2c701.png)
*This particular table should show the detail number of active, recovered and decreased cases.*
<br>
![covid](https://user-images.githubusercontent.com/52890488/80390439-0b258100-88ca-11ea-9864-90f84376379a.png)
*Like this which is showing details state-wise.*

**Comment by qwerty101-hub** [comment]
Where I can find the total no of cases date wise and district wise....plzz help me.

**Comment by KrishnaPravin** [comment]
> Where I can find the total no of cases date wise and district wise....plzz help me.

https://github.com/covid19india/api
