### ISSUE TITLE
Feature: Calculating and showing the number of days in which cases double for each state

### ISSUE THREAD

**Issue by pranavtalwar** [covid19india/covid19india.github.io#1611]
**Is your feature request related to a problem? Please describe.**
A good measure of the growth in covid cases is by looking at the days it takes for cases to double 

**Describe the solution you'd like**
Adding a column next to each state showing the case doubling rate/ days on the homepage

**Describe alternatives you've considered**
Adding a chart in the deep dive section to compare the doubling rate for each state

**Comment by shuklaayush** [comment]
Should be covered in #1496
