### ISSUE TITLE
Active cases calculation

### ISSUE THREAD

**Issue by nidhinakrani** [covid19india/covid19india.github.io#1616]
**Describe the bug**
The calculation for Active cases seems like _ACTIVE_CASES_ON_SELECTED_DATE = CONFIRMED_CASES_ON_SELECTED_DATE - RECOVERED_CASES_ON_SELECTED_DATE - DECEASED_CASES_ON_SELECTED_DATE_. This shows negative values for those days when confirmed cases are less than the sum of Recovered and Deceased.

**To Reproduce**

1. Select Telangana/Kerala from the list
2. Scroll down to graphs section
3. Select Daily option(from Cumulative and Daily options)
4. Active cases graph shows negative values

**Expected behavior**
Shouldn't active cases on specific date be calculated like _ACTIVE_CASES_ON_SELECTED_DATE = TOTAL_CONFIRMED_TILL_SELECTED_DATE - TOTAL_RECOVERD_TILL_SELECTED_DATE - TOTAL_DECEASED_TILL_SELECTED_DATE_?

**Screenshots**
![ACTIVE_CASES_ISSUE](https://user-images.githubusercontent.com/11330227/80415582-5e122f00-88f0-11ea-84d4-e694f49bbdbc.png)

**Comment by shuklaayush** [comment]
Please refer to the discussion in #1313, #1426 and reopen this if you think it's still valid.
