### ISSUE TITLE
Essentials page -->drop-down names are cutting down.

### ISSUE THREAD

**Issue by venunalla7731** [covid19india/covid19india.github.io#1619]
**Describe the bug**
Found Bug in essentials page, in which ALL STATES, ALL CITIES, and ALL SERVICES drop-down fields not properly visible.

**To Reproduce**

1. Go to 'essentials tab'
2. Immediately after opening the page, field names on drop-down are not visible properly.

**Expected behavior**
needs to be visible fully.

**Screenshots**
added.
![image](https://user-images.githubusercontent.com/24906340/80429970-2c727700-88a2-11ea-9b2c-e3e74ea2cdd1.png)

**Desktop (please complete the following information):**
Tested in desktop and ready for the fix to push.

**Comment by harishmathur** [comment]
Please assign this to me

**Comment by venunalla7731** [comment]
code changes are available to push from local.
Just waiting for the status to ready, so that I can create PR.
Thanks.

**Comment by shuklaayush** [comment]
Irrelevant after the Essentials redesign

**Comment by venunalla7731** [comment]
thanks
