### ISSUE TITLE
Need for static code analysis setup

### ISSUE THREAD

**Issue by vinay-thallam** [covid19india/covid19india.github.io#162]
It is observed that, though eslint config is present in the repo, source code has many lint rule violations. Eg: assignments to variables that are never used, Usage of == instead of === in few places, missing trailing commas, indentation and space issues.

Not having having proper check on these may result in  potential bugs. 

This can be solved by adding few things listed below, 

- prettier setup for code formatting. 
- VS Code recommended extensions file and settings to do format on file save. 
- Pre-commit hook to do lint fix and format fix ( takes care if developers not using VS code as their IDE )
- Lint and prettier Validate npm scripts in package.json ( can be invoked manually OR in CI if required)

**Comment by vinay-thallam** [comment]
@jeremyphilemon  Please let me know if I can work on these

**Comment by satishsingh35** [comment]
Great suggestion @vinay-thallam 
[setting sync](https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync) can be used to keep vscode settings in sync .

**Comment by jeremyphilemon** [comment]
@vinay-thallam sure! which ones from the list you've mentioned above do you plan on addressing? 

Right now I'm planning on sticking to eslint and google's javascript style guideline, would like to hear suggestions on this. And would it be possible to have both eslint and prettier in the pipeline?

**Comment by vinay-thallam** [comment]
> Great suggestion @vinay-thallam
> [setting sync](https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync) can be used to keep vscode settings in sync .

Thanks @satishsingh35 for suggestion. I checked about setting sync as you mentioned. Looks like for me it is better suited for an individual to sync his VS Code settings across multiple machines. 

I am looking at simpler solution where vs code applies the settings only for this repo when it is opened in vs code, thus not messing too much esp when he is working on other projects.

**Comment by vinay-thallam** [comment]
> @vinay-thallam sure! which ones from the list you've mentioned above do you plan on addressing?
> 
> Right now I'm planning on sticking to eslint and google's javascript style guideline, would like to hear suggestions on this. And would it be possible to have both eslint and prettier in the pipeline?

@jeremyphilemon  Will be addressing all of them. 
We can continue to stick to the google's guideline for Code-quality rules and prettier can handle formatting rules.  Please check below link for more info,
https://prettier.io/docs/en/comparison.html
It is possible to have both in pipeline.

**Comment by abhishekakade** [comment]
@jeremyphilemon, @JunaidBabu, this shouldn't be under enhancement, this issue should be made high priority and resolved ASAP. Everyone is using their own way and changing a lot of code as they see fit without any style guide and its getting messy.

**Comment by kousiksatish** [comment]
@vinay-thallam @jeremyphilemon I can work on fixing the eslint errors. Please let me know how to go about it. Should I create a new PR now or do it after the rules are finalised?

**Comment by jeremyphilemon** [comment]
@kousiksatish So the ESlint errors have been fixed, looks like we still have a few warnings that need to be looked at, I've opened an issue for it at #313 and added a quick reference to get anyone started.

Closing this for now since the majority of it has been addressed! @vinay-thallam Thank you for bringing up this issue!

**Comment by vinay-thallam** [comment]
@jeremyphilemon  That's great. Thank you for incorporating as suggested.
