### ISSUE TITLE
Daily Increase Rate is Wrong

### ISSUE THREAD

**Issue by Rithvik2109** [covid19india/covid19india.github.io#1620]
Bug:
The daily increase yesterday night(27/04) was 1560, but today it shows 27/04's daily increase at 1052. 

**To Reproduce**
Steps to reproduce the behavior: Go to graph > select all states > check total cases (1052 increase on 27/04). 

**Expected behaviour**
Needs to reflect 1560. 
<img width="630" alt="Screenshot 2020-04-28 at 11 42 30 AM" src="https://user-images.githubusercontent.com/64458533/80453539-19b17e00-8946-11ea-8ca9-c2e47ef879ac.png">
<img width="630" alt="Screenshot 2020-04-28 at 11 43 23 AM" src="https://user-images.githubusercontent.com/64458533/80453545-1c13d800-8946-11ea-8977-3629636f109c.png">

**Screenshots**

**Desktop (please complete the following information):**

- OS: MacOS Catalina
- Browser Safari
- Version 13.1

**Comment by shuklaayush** [comment]
It's showing 1568 for me. Can you check again please?

**Comment by Rithvik2109** [comment]
It is rectified now. Thanks.
