### ISSUE TITLE
Number of deceased not reflected in state map of Tamil Nadu

### ISSUE THREAD

**Issue by kvnsnaresh** [covid19india/covid19india.github.io#1625]
**Describe the bug**
In Tamil Nadu map, the district wise spilt-up of deceased cases is not getting depicted/reflected in the state view. 

**To Reproduce**

1. Go to state map of Tamil Nadu by clicking directly on the map
2. Hover/Click the mouse over any district.
3. Although at the time of reporting this bug, there are 24 deceased cases, all districts are showing 0 deaths

4. This issue is seen only in Tamil Nadu, although other states needs to be verified.
![TN_Stateview_Bug](https://user-images.githubusercontent.com/64458314/80460242-2e474380-8951-11ea-8289-36f174457483.PNG)

5. The above behavior is reproducible on smart phones as well. Follow same steps

**Expected behavior**
The district wise spilt-up of deceased cases is shall be depicted as done in every other state 

**Screenshots**
See attached screenshots

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: chrome
- Version 81.0.4044.122 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

- Device: OnePlus 3T
- OS: Oxygen 9.0.6
- Browser Chrome
- Version 81.0.4044.117

**Comment by shuklaayush** [comment]
Looks like it's fixed now :)
