### ISSUE TITLE
Sort the drop-down menu in alphabetical order

### ISSUE THREAD

**Issue by sk100797** [covid19india/covid19india.github.io#1628]
**Describe the bug**
The Drop-down menu present in spread trends is currently sorted based on the states table.
It is better to sort it in alphabetical order, so that it would be easy to select states.

**To Reproduce**
Select the drop-down menu present in SPREAD TRENDS. 

**Expected behavior**
Sort the values in Alphabetical order by default.

**Screenshots**

![image](https://user-images.githubusercontent.com/35917611/80475366-673de300-8966-11ea-8d44-8d6107bc1e9f.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Chrome
- Version : 81

**Additional context**
The drop-down can be sorted alphabetically only if we sort the states table. But by default the states table is sorted by Confirmed cases. So drop-down is also getting sorted in the same way. It would be easier to select states in drop-down if they are sorted in alphabetical order.

**Comment by bee-rickey** [comment]
The ordering is based on the ordering of the table. So if you sort the table, this should reflect in the dropdown too.
