### ISSUE TITLE
No cases on 27/04/2020 in demographics page

### ISSUE THREAD

**Issue by nayakrahul** [covid19india/covid19india.github.io#1629]
**Describe the bug**
There are no cases on 27/04/2020 in demographics page.

**Screenshots**
![Screenshot (60)](https://user-images.githubusercontent.com/11428805/80476172-a587d200-8967-11ea-9afb-10f63344b985.png)

**Comment by shuklaayush** [comment]
Why would there be cases in 2016? :stuck_out_tongue:
Anyways, I think it might be related to [this](https://telegra.ph/Changes-in-rawdata-api-04-26)

**Comment by nayakrahul** [comment]
Oh. sorry. typo mistake :D. Its's 2020 only
