### ISSUE TITLE
feedback and add text color not consistent in essentials page in dark mode in mobile devices

### ISSUE THREAD

**Issue by nayakrahul** [covid19india/covid19india.github.io#1630]
**Describe the bug**
feedback and add text color is not consistent with other buttons in essentials page in dark mode which makes it not visible in dark mode **in mobile devices**

**To Reproduce**

1. Go to Essentials page
2. Notice the color of text in feedback and add button

**Expected behavior**
Should be of same color as of other buttons.

**Screenshots**
![Screenshot (62)_LI](https://user-images.githubusercontent.com/11428805/80477242-3ca15980-8969-11ea-861f-e37d72d63f3e.jpg)

**Comment by nayakrahul** [comment]
Please assign me if it becomes available.

**Comment by KrishnaPravin** [comment]
cc @nikita-11
