### ISSUE TITLE
District wise data columns as it available for state wise

### ISSUE THREAD

**Issue by saifeesl** [covid19india/covid19india.github.io#1631]
The state-wise columns for confirmed - Active - Recovered - Deceased available, The similar breakdown is available at state map for the districts, can the same data made available as columns too in the data grid at the second level too. 

![image](https://user-images.githubusercontent.com/63785125/80484545-f0eeb000-8968-11ea-9f53-20346b388220.png)

![image](https://user-images.githubusercontent.com/63785125/80484605-0b288e00-8969-11ea-8f45-438712ee0d3a.png)

**Comment by shuklaayush** [comment]
Duplicates #1607
