### ISSUE TITLE
update also which place person recover covid-19 and how many? 

### ISSUE THREAD

**Issue by 1998kajal** [covid19india/covid19india.github.io#1633]
the update also which place a person recover COVID-19 and how many person place wise.
It is important and helpful full user also

**Comment by shuklaayush** [comment]
We do show the recovery numbers for states and districts. Is that what you're looking for?

**Comment by 1998kajal** [comment]
here you are just showing the recovery number person whose
belong which state not districts.
So I am trying to say that also shows the recovery person belongs to
districts also. It is helpful for us.
the same column (confirmed, recovered, active, death) show also district
wise.


Thanks and Regards


Kajal Kumari
Master Of Technology(M.Tech)
Dept. of Computer Science & Engg.
*Indian Institute of Technology Dhanbad.*
Email:erkajalkumari@gmail.com
Contact :- +91-7991160058
            +91-9155847825

**Comment by shuklaayush** [comment]
Okay. There's already an issue for that #1607
