### ISSUE TITLE
Why are you not added no. of test done by particular state?

### ISSUE THREAD

**Issue by priteshradadiya-coviam** [covid19india/covid19india.github.io#1634]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by priteshradadiya-coviam** [comment]
Can you add the no. of test done so far , from each state?

**Comment by shuklaayush** [comment]
The testing numbers show up on the state pages and when you hover on the states on the map

**Comment by vsasvipul0605** [comment]
This is not an issue as this is already on website :)

![SharedScreenshot](https://user-images.githubusercontent.com/47572837/80523930-76e01a80-89ac-11ea-9490-9735c02b171e.jpg)
