### ISSUE TITLE
API Data3 not fetching proper results

### ISSUE THREAD

**Issue by avinasshcm** [covid19india/covid19india.github.io#1636]
**Describe the bug**

https://api.covid19india.org/raw_data3.json returns following result.

Date | Number of Cases detected
27-04-2020 | 474
28-04-2020 | 435

**Comment by vsasvipul0605** [comment]
what's the issue?

**Comment by vsasvipul0605** [comment]
can u explain in detail @avinasshcm ?

**Comment by Sushant-DA** [comment]
Facing the same issue, also do we have a single column for date? "dateannounced" which is being updated every time a patient either recovers or in case of death? For eg if I have to get the total number of cases in Karnataka today, I have to filter on the currentstatus column as well

**Comment by Sushant-DA** [comment]
was this closed without resolution?

**Comment by avinasshcm** [comment]
Yes. I did not notice that for some states it was updated in Bulk, i.e. 1 row in result contains more than 1 patient added. found a work around later.
