### ISSUE TITLE
Distric wise breakdown change value is not updated

### ISSUE THREAD

**Issue by codebynitish** [covid19india/covid19india.github.io#1638]
![IMG-20200428-WA0012](https://user-images.githubusercontent.com/41028477/80523694-c1529e80-898e-11ea-98b7-47b5b3897b44.jpg)

**Comment by vsasvipul0605** [comment]
This is not an issue. As the change in values totally dependent on data coming from API.

**Comment by codebynitish** [comment]
If there is no data coming as a district-wise change.. then that shouldn't bbe displayed.. it gives no information on drilling down.

**Comment by sudevschiz** [comment]
The delta values for each districts are present in the API, even if it's 0. Whether to show 0 or now is a matter of interpretation. For now, let's keep this as is.
