### ISSUE TITLE
top districts of delhi not showing correctly

### ISSUE THREAD

**Issue by vsasvipul0605** [covid19india/covid19india.github.io#1639]
**Describe the bug**
Top districts are not showing perfectly. they are mixing into each other.

**To Reproduce**

1. Go to '[link](https://www.covid19india.org/state/DL)'
2. Click on 'Top Districts'
3. See error

**Expected behavior**
proper margin and padding.

**Screenshots**

![SharedScreenshot](https://user-images.githubusercontent.com/47572837/80525234-86f8f980-89ae-11ea-9b3b-fc8beca01d6b.jpg)

**Desktop (please complete the following information):**

- OS: [windows 10]
- Browser [chrome]

**Additional context**
if you'll add label, I'm ready to claim and check and correct issue

**Comment by shuklaayush** [comment]
Duplicates #1641, since it appears to be the same problem
