### ISSUE TITLE
Global Ranking 

### ISSUE THREAD

**Issue by ghost** [covid19india/covid19india.github.io#1642]
An international ranking will allow people to determine how is India and other countries standing against corona virus . It can also be followed by a list of countries sorted according to different options like testing rate, death toll , recovery rate etc.

**Comment by shuklaayush** [comment]
I think this is a bit out of our scope right now, since we don't collect this data. Will open it later if it becomes relevant. Thanks anyway!

**Comment by ghost** [comment]
Okay , I get that
