### ISSUE TITLE
Daily graph for tested

### ISSUE THREAD

**Issue by petronav** [covid19india/covid19india.github.io#1644]
**Is your feature request related to a problem? Please describe.**
Right now the tested graph shown only works for cumulative switch but not for daily switch. Upon clicking on daily switch the testing graph vanishes where as the rest four graphs remain in their position as they were.

**Describe the solution you'd like**
Show a daily basis tested graph just like the rest of the four graphs of confirmed, active, recovered, deceased ones. There might be a problem for lack of data as the tested graph data starts from 13th March - in that case you guys can put something like unconfirmed lest the slider goes behind the date.

**Comment by shuklaayush** [comment]
Hi! The testing time series also contains some missing data points in between since the information wasn't released by the state/central government. For example, there's no data for 22 April in the All States chart. I couldn't think of an elegant solution to handle this, so I didn't add the daily testing graph. Let us know if you have a solution in mind. Thanks!

**Comment by petronav** [comment]
Yup, didn't notice this discontinuity. There's multiple dates 28 march, 29 march, 20 April - no data. How about we put something like 'Not Available' for two days when we have data missing for a day, like plotting zero on graph but writing NA in stead of any count along with fluctuation wrt previous day on the plot legend. We have data for the 19th, the 21st - we don't know exact count for the 20th and the 21st itself, thus we'll have to sacrifice two days daily count for a single day missing value. Bet so many lapses won't look good on the plot either.

**Comment by shuklaayush** [comment]
I think your approach makes sense. We can omit the bar for an extra day for the period when the data is missing. Also, instead of writing NA, we can just show a '-' like we do for the cumulative graph.

Let me know if you'd like to make a PR for this.

**Comment by petronav** [comment]
I'll have to pass on PR. I'm not well versed in react, tbh.

**Comment by shuklaayush** [comment]
Sure, nevermind
