### ISSUE TITLE
Optimization.

### ISSUE THREAD

**Issue by shubhamjain2998** [covid19india/covid19india.github.io#1645]
**Describe the bug**
Table and row components in home page need optimized code as the whole table get re-rendered on hovering or selecting the city like it re-renders almost 15 20 times on normal hovering, use of state and effect hook are doing this, the performance of app can be improved if the number of re-renders can be reduced and kept to child component only

The attached gif explains more what I am trying to say. It's not much clear but I am displaying render count and also see the console it is updating in every render.

![perform](https://user-images.githubusercontent.com/30628775/80538335-32ac4480-89c3-11ea-8d45-c11136bc7d27.gif)

**Additional context**
Assign it to me if it feels relevant.

**Comment by abhishekakade** [comment]
I believe those are onMouseEnter and onMouseLeave events on table rows added to highlight states/districts on hover.

**Comment by shubhamjain2998** [comment]
Yes definitely, but I think it will be good if it will not re-render the whole table component on every hover whether its district or state, also there are some extra useState and useEffect hooks that can be optimized to restrict the re-rendering of the component.

**Comment by abhishekakade** [comment]
I meant that's probably where the problem lies.

**Comment by shubhamjain2998** [comment]
okay, sorry for getting you wrong. :)

**Comment by shuklaayush** [comment]
I think this has been fixed now. The performance should be much better
