### ISSUE TITLE
Auto suggester on the search field

### ISSUE THREAD

**Issue by jeremyphilemon** [covid19india/covid19india.github.io#1649]
**Is your feature request related to a problem? Please describe.**
Currently the search bar is empty. A suggester on the type on search inputs can be a good visual aid in letting people know what all searches it supports.

**Describe the solution you'd like**
Something like this:

<p align="center">
<img src="https://user-images.githubusercontent.com/17938322/80554384-9e97a880-89d5-11ea-9ab1-b1d2c572dfc4.gif" width="50%"></img>
</p>

**Additional context**
Looking for a vanilla solution to this, but I wouldn't mind a tiny module that can support this!

**Comment by nayakrahul** [comment]
/claim . I will make a try.

**Comment by nayakrahul** [comment]
@jeremyphilemon should the terms in the box be in a loop?

**Comment by jeremyphilemon** [comment]
@nayakrahul Yes ideally that's what I'm looking for, but what do you suggest?

**Comment by nayakrahul** [comment]
@jeremyphilemon I have tried by looping the terms in the box. Soon I will raise a PR.
