### ISSUE TITLE
Text overlap in barchart

### ISSUE THREAD

**Issue by vivekvroy** [covid19india/covid19india.github.io#1650]
For some states the bar chart overlaps with the content behind I.e. confirmed, active, date and numbers.
![ACF383C0-CAB7-43DB-8E24-59E3D5B0B145](https://user-images.githubusercontent.com/10249914/80556556-8b92d180-89f1-11ea-921f-366fffe53773.png)

**Comment by swoodipto** [comment]
We can fix this by increasing the height of the parent container and aligning the graph to the bottom of the parent, _just enough_ so that the info text container at the top left corner and the graph do not overlap.

Let me `/claim` this if you agree.

**Comment by shubham-aneja** [comment]
I can fix this, if this is available. Please confirm @shuklaayush

**Comment by shuklaayush** [comment]
We need a good design solution for this

**Comment by dvj1988** [comment]
@shuklaayush We can move the name below the graph and have the date and number of cases in a single line on top left for eg. Apr 28 (27 -54).

**Comment by AvinashVunnava** [comment]
@shuklaayush We can also have `center-aligned` text with some decent `margin-bottom` for the stats div something like below
![image](https://user-images.githubusercontent.com/33828997/87575189-2778d300-c6ed-11ea-8e25-7ab09a42c6ba.png)

*Note: In the above image the margin for stats div is missing*

**Comment by kousiksatish** [comment]
@shuklaayush @jeremyphilemon How about this?
Before:
![Screen Shot 2020-07-23 at 8 08 07 PM](https://user-images.githubusercontent.com/6641694/88299851-78f21500-cd20-11ea-85d8-f86094b5da40.png)
After:
![Screen Shot 2020-07-23 at 8 08 46 PM](https://user-images.githubusercontent.com/6641694/88299871-7c859c00-cd20-11ea-8306-a931250cde3c.png)

/claim

Please let me know. I can work on this.

**Comment by shuklaayush** [comment]
@kousiksatish Difficult to judge just by looking at an image. Create a PR?

**Comment by kousiksatish** [comment]
@shuklaayush Please have a look at the PR above.

**Comment by fleece30** [comment]
@shuklaayush is this issue still open? I'd like to work on it /claim

**Comment by swoodipto** [comment]
~If this is still open I would like to /claim it~
NVM, just noticed [the PR](https://github.com/covid19india/covid19india-react/pull/2285)
