### ISSUE TITLE
india map hotness weighted by area

### ISSUE THREAD

**Issue by Mryashbhardwaj** [covid19india/covid19india.github.io#1655]
**Is your feature request related to a problem? Please describe.**
Currently the indian map we show , is only colored on basis of total number of case in that area. a smaller area with more cases is more alarming than the other

**Describe the solution you'd like**
the indian map should be coloured statewise with respect to the area, of the state. you can normalise the color with respect to area of state and that may seem mode appropriate. also this can be added as an option to view.

**Comment by rajkapadia247** [comment]
I disagree on this request. The user is expecting to see the hotness based on the number of cases. However, we can add another country map in which the hotness can be weighted by area or by population or by population density.

**Comment by shuklaayush** [comment]
I think this is an inherent limitation with Choropleth maps. We can normalize the colours based on a number of factors, but that won't solve it completely. I'm hoping that the recently added Hotspots view addresses this
![image](https://user-images.githubusercontent.com/27727946/82139546-21c65480-9846-11ea-9343-7681af373279.png)
