### ISSUE TITLE
Dark Mode: Essentials page search keywords not clearly visible

### ISSUE THREAD

**Issue by aishmittal** [covid19india/covid19india.github.io#1658]
**Describe the bug**
Search keywords are not clearly visible in dark mode on the essentials page.

**To Reproduce**

1. Go to 'https://www.covid19india.org/essentials'
2. Click on 'Search' Button
3. Type the search keyword in the search box.

**Expected behavior**
The search keyword and search icon should be clearly visible. The color should be consistent with all other input fields in dark mode. 

**Screenshots**

![darkmode_bug](https://user-images.githubusercontent.com/11550572/80606865-67b3a800-8a52-11ea-9d3e-ebf578492b8d.png)

- OS: Windows 10
- Browser: Chrome

**Comment by anirudh411** [comment]
let me /claim the issue.

**Comment by KrishnaPravin** [comment]
cc @nikita-11

**Comment by Hyraze** [comment]
Issue is fixed please see the reference of pull request

**Comment by aishmittal** [comment]
@Hyraze The color of the search icon is still black which is not visible clearly.

**Comment by Hyraze** [comment]
@aishmittal  I have changed it to gray which is the default color set text in the app #1675 
this is the preview deployment of my pull request. please let me know your view on that
https://covid19india-react-git-fork-hyraze-master.covid19india.now.sh

**Comment by Hyraze** [comment]
> cc @nikita-11

Can you review this

**Comment by shuklaayush** [comment]
Irrelevant after #1872
