### ISSUE TITLE
Include increase or decrease in active case count

### ISSUE THREAD

**Issue by tarun7singh** [covid19india/covid19india.github.io#1659]
**Is your feature request related to a problem? Please describe.**
Active cases is a really important criteria for seeing if a country or a particular state is doing bad or good, in containing corona infection.

**Describe the solution you'd like**
Showing a positive or negative daily change, maybe by using (todayNewCases - deathsToday - recoveriesToday )

**Describe alternatives you've considered**
Calculating it in my mind itself. and it frustrates me to not have that particular on hand always.

**Additional context**
It looks really weird to not have that subtext in active cases category.

**Comment by phoenicopteri** [comment]
Something like this can be good

<img width="424" alt="active" src="https://user-images.githubusercontent.com/11295641/80652072-cf8ae280-8a94-11ea-836f-6c50e4ed2531.png">

Although I'm not sure if the colors for daily active in state rows should be the same for positive / negative values.

**Comment by kambleaa007** [comment]
that are present `+number` is there @tarun7singh

**Comment by bee-rickey** [comment]
This is already part of the daily graph by the way. The reason why we've held off on active count is because -ve numbers seem to confuse people a lot.

**Comment by tarun7singh** [comment]
I Understand how it could be confusing to some people but surely we can add
little information icon like some States show so when you hover, so it
explains the data.

**Comment by jaibatrik** [comment]
@bee-rickey My suggestion is to make the chart title more verbose (something like "Change in active cases" instead of just "Active") when "Daily" is selected. Related https://github.com/covid19india/covid19india-react/issues/1313#issuecomment-623478272.

**Comment by jaibatrik** [comment]
If the proposal is okay, I can send a PR.

**Comment by shuklaayush** [comment]
Added now
