### ISSUE TITLE
Case count details at district levels within state

### ISSUE THREAD

**Issue by christopherbramya** [covid19india/covid19india.github.io#1661]
Please add count for Active case Recovered and Death in state page details at district levels .

Example Chennai is district in TamilNadu
It is showing only confirmed case count of 772

**Comment by skkart** [comment]
Please assign me if it becomes available.

**Comment by KrishnaPravin** [comment]
these counts are available
![Screenshot 2020-05-01 at 12 21 29 PM](https://user-images.githubusercontent.com/17372422/80788321-68f5e980-8ba6-11ea-8680-2802199f7689.png)
![Screenshot 2020-05-01 at 12 21 44 PM](https://user-images.githubusercontent.com/17372422/80788326-6bf0da00-8ba6-11ea-8b12-3b1c8c3a3e89.png)
