### ISSUE TITLE
Add last case reported date in state wise and district wise 

### ISSUE THREAD

**Issue by christopherbramya** [covid19india/covid19india.github.io#1663]
Add last case reported date in state wise and district wise .

**Comment by vsasvipul0605** [comment]
Check the website. This is already there when you click on the bell icon under search bar.

![SharedScreenshot](https://user-images.githubusercontent.com/47572837/80662618-58af1300-8aaf-11ea-845e-d13649613e81.jpg)

**Comment by christopherbramya** [comment]
This is very hard to go through for each state and district wise instead you can add as an extra column after Confirmed , Active , Deceased , then you can display one more column latest cases reported date . So we can go through as easiest way in all state and district at a single glance

**Comment by KrishnaPravin** [comment]
#1496
