### ISSUE TITLE
Add Expected recovered date for Active cases in State and District wise

### ISSUE THREAD

**Issue by christopherbramya** [covid19india/covid19india.github.io#1665]
Add Expected recover date for Active cases in State wise and District wise details based on everyday report

**Comment by KrishnaPravin** [comment]
Could you elaborate on what you mean by _Expected recover date_.
Also, is that date available in the everyday reports?

**Comment by christopherbramya** [comment]
Hi Krishna Pravin 
First a fall thanks for review my feature request . I'm looking through the map state wise and district wise it will very hard to understand when it will solve all cases in particular districts and state wise. 
For example Chennai is a district present inside a state of TamilNadu . It has more cases and don't know when it will get cured all patients . To know the rough estimate we can calculate some days for example consider last cases is reported today may 02 we can add 28 days and mentioned expected recover all patients by May 30 .
It is not accurate but it will help to understand within the mentioned date all patients will be recovered . We can add like this in all districts and state wise.

**Comment by bee-rickey** [comment]
IMO this could be very speculative and misleading. Unless all the asymptotic cases are mapped and there are no unknown cases, the average recovery rate cannot be used to predict the estimated date of recovery for all patients.

**Comment by christopherbramya** [comment]
Thanks
________________________________
