### ISSUE TITLE
Adding number of individuals tested from ICMR data in daily section 

### ISSUE THREAD

**Issue by codewithkaranjeswani** [covid19india/covid19india.github.io#1667]
**Is your feature request related to a problem? Please describe.**
In the graphs for number of cases (confirmed, active, recovered and deceased), there is a number of people **"Tested"** graph for the **Cumulative** section. There is no such graph in the **Daily** section.

**Describe the solution you'd like**
It is simple to calculate the number of tested individuals per day by using the cumulative tested data from ICMR (this is already available and is being used). I would like to suggest that you make a graph for number of people tested daily.

**Describe alternatives you've considered**
N.A.

**Additional context**
This image shows the cumulative section where we see a graph for the number of people "Tested" below "Confirmed", "Active", "Recovered" and "Deceased".
![cumulative_graphs](https://user-images.githubusercontent.com/34395853/80719168-b6c41080-8b18-11ea-9c79-ff43bef10169.PNG)
This one shows that there is no number of "Tested" people graph in the daily section below "Confirmed", "Active", "Recovered" and "Deceased".
![daily_graphs](https://user-images.githubusercontent.com/34395853/80719175-b9bf0100-8b18-11ea-92c6-8ca0e60e7095.PNG)

**Comment by shuklaayush** [comment]
Duplicates #1644
