### ISSUE TITLE
Style issues in table 

### ISSUE THREAD

**Issue by nayakrahul** [covid19india/covid19india.github.io#1668]
**Describe the bug**
- districts heading text color not same as states heading text color.
- Arrow up and down icon does not appear on recovered heading unlike others in district table on clicking it while sorting based on recovered.
https://github.com/covid19india/covid19india-react/blob/820e14ace2acf5987f87d61bd8cb27c3dbfa540d/src/components/row.js#L314 (Don't know what `sort-black` is. It should be `initial` like others)
- And I don't know if the space above and below district table are intentional or not.

**Expected behavior**
The bugs need to be fixed. 

**Screenshots**
![Screenshot (67)_LI](https://user-images.githubusercontent.com/11428805/80728551-af0a6900-8b24-11ea-9f71-3a426b2a589e.jpg)

**Comment by nayakrahul** [comment]
please assign me if it becomes available. It's a quick fix.

**Comment by KrishnaPravin** [comment]
- Recovered heading arrow is fixed
- Space above and below district table are intentional
