### ISSUE TITLE
Website Hit Count, to be displayed as counter on the dashboard.

### ISSUE THREAD

**Issue by ashutoshkokam** [covid19india/covid19india.github.io#167]
It would be great, if we can display the website hits counter on the bottom left corner of the dashboard.
would be getting an insight on the popularity or the reach of the website.

**Comment by satishsingh35** [comment]
@ashutoshkokam IMO, This is not a commercial website. Don't see much use of putting counter.
Usually counters are done to do social proof(marketing term). We don't need it here

**Comment by aekanshd** [comment]
This is not necessary.
