### ISSUE TITLE
Visit stage page in mobile not proper

### ISSUE THREAD

**Issue by Achal1607** [covid19india/covid19india.github.io#1671]
**Description**
Visit stage page button has not proper alignment in mobile view. 

**To Reproduce**

1. Go to 'home page'
2. Click on 'Any state name'
3.See error

**Expected behavior**
Proper alignment in one line should be there. 

**Screenshots**
![Screenshot_2020-04-30-22-10-25-212_com android chrome](https://user-images.githubusercontent.com/55803675/80736775-36110e80-8b30-11ea-9cb7-b3d4a610db3a.jpg)

**Smartphone (please complete the following information):**

- Device: Redmi Note 7 pro
- OS: Android
- Browser:Google Chrome

**Comment by Achal1607** [comment]
I can fix it..

**Comment by shuklaayush** [comment]
Seems to be fixed now
