### ISSUE TITLE
Giving the % of new cases registered if possible.

### ISSUE THREAD

**Issue by rohitbabugaddeti** [covid19india/covid19india.github.io#1672]
**Is your feature request related to a problem? Please describe.**

There's a lot of misunderstanding around the number of new cases registered. If "A" is doing "n" tests per day and the other guy "B" is doing "n-k" tests per day, where 'k'<'n' and 'n'>0. Because of showing only the number of new cases, people seeing the stats may think that "B" is really doing a great job in controlling the pandemic.

**Describe the solution you'd like**

In order to address this issue, we can show the percentage of new cases registered on the day alongside the number of new cases registered on the day.

**Comment by kpkeerthi25** [comment]
I think this may do a great job. Because people can see the prediction and they'll stay in their homes in order to prevent the predicted numbers. Assign me for this .

**Comment by rohitbabugaddeti** [comment]
@kpkeerthi25 There is no prediction described. The issue is about giving accurate and unambiguous information. However, if you want to take up the issue, try "/claim". The github-bot may assign it.
