### ISSUE TITLE
Good to have new chart "daily recovered & confirmed cases" in deep dive section

### ISSUE THREAD

**Issue by skkart** [covid19india/covid19india.github.io#1673]
**Is your feature request related to a problem? Please describe.**
Would be great to see daily trend of recovered & confirmed cases in deep dive section

**Additional context**
This chart will give us the signal & outcome of virus on a daily basics. 
In coming future, we would be seeing crossover of trend between confirmed cases and recovered cases which will demonstrate the positive sign.

**Comment by gyanendrapatro** [comment]
You can assign it to me
