### ISSUE TITLE
Disable invalid hidden hyperlink in State Pages

### ISSUE THREAD

**Issue by abbhhiisseek** [covid19india/covid19india.github.io#1681]
**Describe the bug**
The back button or the button to exit state pages is not visible. 

**To Reproduce**
Click on any of the Visit State Pages. 
Back button is not visible. 

**Expected behavior**
Back button should be visible. 
Once site is switched to dark mode and back, back button is visible. But initially on visting site and goint to state pages, back button not there 

**Desktop (please complete the following information):**

- Windows 7 and 10

**Smartphone (please complete the following information):**

- OS Android

**Comment by shuklaayush** [comment]
Which back button is this? Can you send a screenshot?

**Comment by abbhhiisseek** [comment]
[
![back](https://user-images.githubusercontent.com/27771780/80791936-c4c57000-8bb0-11ea-8fd4-1be3dd1098ad.png)
](url)

**Comment by abbhhiisseek** [comment]
![back2](https://user-images.githubusercontent.com/27771780/80792024-03f3c100-8bb1-11ea-83e6-9322e5eb3b38.png)

**Comment by shuklaayush** [comment]
Okay, so we've intentionally hidden the back button on the state pages since you can use the breadcrumbs on the top to go back.
![image](https://user-images.githubusercontent.com/27727946/80792655-9fd1fc80-8bb2-11ea-8807-9cec52958996.png)

> Once site is switched to dark mode and back, back button is visible. 

This should never happen since we've hidden the back button. I can't reproduce it either. Can you confirm again that this happening? Maybe send a screenshot as well.

**Comment by abbhhiisseek** [comment]
![back3](https://user-images.githubusercontent.com/27771780/80792924-56ce7800-8bb3-11ea-81f7-64848838fafa.png)
Please find back button, today's date

**Comment by shuklaayush** [comment]
That is not a state page

**Comment by abbhhiisseek** [comment]
got it. Thanks

**Comment by abbhhiisseek** [comment]
however, even in state pages, at the location where back button was there's a hidden hyperlink which returns you back
![back3](https://user-images.githubusercontent.com/27771780/80793715-7ebedb00-8bb5-11ea-810c-ea0efac709ba.png)


should this  hidden hyperlink be visible?

**Comment by shuklaayush** [comment]
Yeah, the reason it returns you to the home page is because the link is actually invalid :sweat_smile:. It's a remnant from reusing the same map component as on the home page. I guess you can hide it through some small changes to MapExplorer.js and/or the CSS. Feel free to make a PR

**Comment by abbhhiisseek** [comment]
sure :) making a PR

**Comment by abbhhiisseek** [comment]
Created PR. Can you please check ?

**Comment by abbhhiisseek** [comment]
Guess this one is solved now?
