### ISSUE TITLE
See overall India statistics date wise

### ISSUE THREAD

**Issue by abbhhiisseek** [covid19india/covid19india.github.io#1682]
**Is your feature request related to a problem? Please describe.**
Currently the Confirmed, Active, Recovered and Deceased cases for all state in a rowwise manner in the home screen, are visible only for the present Calendar day. No option there to check rowwise statistics for all states, individually, in one screen, at one glance for previous dates. 

**Describe the solution you'd like**
All state statistics rowwise should be displayed on the home, and filterable as per date selected, not only current date.

**Comment by anamritraj** [comment]
Given here there is less control on the backend, it might be a bit tough to transform the data to be presentable. If you want you can check https://github.com/anamritraj/livecovid.in-webapp. 
I recently implemented something similar to what you are talking about and you are welcome to contribute :)

**Comment by abbhhiisseek** [comment]
@anamritraj your dashboard is nice :) I will check the codebase.

**Comment by shuklaayush** [comment]
Added now :)

**Comment by abbhhiisseek** [comment]
Awesome work!
