### ISSUE TITLE
Mismatch of Data and Tally

### ISSUE THREAD

**Issue by ravigaggad** [covid19india/covid19india.github.io#1684]
**Describe the bug**
Their is mismatch in tally of Total no. of patients,Active Patient,Recoverd Patient,Deceased.

**To Reproduce**

1. Go to 'Covid19india web site.'
2. Click on '' Menu button"
3. Scroll down to 'Himachal pradesh'
4.  Click on Himachal Pradesh 
5. See error the total tally of the no.of active patient & no. of Recoverd patient,No.of Deceased patient is not representating Total number of patients. Their is a difference. 

**Expected behavior**
Expected Result is number of active Patient 
Must be 10.
![IMG_20200501_135857](https://user-images.githubusercontent.com/63439607/80793139-ed9b3480-8bb3-11ea-845e-844599fca88b.JPG)

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by sudevschiz** [comment]
HP has 4 Migrated cases which are reduced from Active #. Also, death of Tibetan refugee is included in deceased numbers, but not in confirmed.

I have added this explanation to the note besides the state names. Thank you!
