### ISSUE TITLE
The user shouldn't be shown the state charts merely on hovering on a state as it creates unintended effects. 

### ISSUE THREAD

**Issue by rajkapadia247** [covid19india/covid19india.github.io#1689]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I'm moving my mouse through the screen and now when I'm looking at the chart, instead of showing me the country's stats it is showing me some random state's stats that I had accidentally hovered over. Also, now to see the country's trends I have to go to the drop-down and select "All states."

**Describe the solution you'd like**
Instead of showing the chart on hover of a row, it should be shown on click of a row. It even makes more sense. 

Also, we can add a button next to the drop-down to directly view the country's stats.

**Additional context**
![GIF](https://user-images.githubusercontent.com/47295446/80808093-63b39180-8bdc-11ea-9c7a-af724450c53f.gif)

**Comment by nikhilo** [comment]
I agree. That is very annoying. We can also consider increasing the hover duration before triggering the update on the charts.
