### ISSUE TITLE
doesn't showing the correct map data as on the table format

### ISSUE THREAD

**Issue by mazarie** [covid19india/covid19india.github.io#1691]
when I open the map and for eg click a state and then select the state and then the district its showing the 0 cases while on the table the district have reported the cases.
![Screenshot_2020-05-01-18-46-10-713_com android chrome](https://user-images.githubusercontent.com/36659626/80809926-58fafb80-8be0-11ea-909e-0a330423df9d.jpg)
![IMG_20200501_184713](https://user-images.githubusercontent.com/36659626/80809943-61ebcd00-8be0-11ea-943a-2599cb5291e8.jpg)

**Comment by nayakrahul** [comment]
This is happening because of spelling mismatch.

**Comment by nayakrahul** [comment]
It can be fixed by editing here: public/maps/bihar.json

**Comment by shuklaayush** [comment]
Fixed via #1704
