### ISSUE TITLE
Difference in sum of tests done, as total sum of tests done in india is not same as cumulative sum of tests done by each state.

### ISSUE THREAD

**Issue by devtechnocode** [covid19india/covid19india.github.io#1692]
**Describe the bug**
Difference in data, as tests done differ when we see tests done in india and total sum the tests done adding up all states.

**Expected behavior**
There should not be difference between total tests done in india and cumulative sum of tests done by states.

**Screenshots**
As it is showing that tests done in india is approx 8.3 Lakhs but by adding separately all states sum of test done is coming approx 9.9 Lakhs.
![covid19](https://user-images.githubusercontent.com/52890488/80761290-e6ded400-8b57-11ea-9967-3f067c182234.png)

**Comment by bee-rickey** [comment]
This is not an issue on data collection or the front end. This is an issue with the govt agencies reporting different numbers. Let us know if there's any genuine mistake on our side, else I'll be closing this issue. Thank you :)
