### ISSUE TITLE
visual zone classification across the country

### ISSUE THREAD

**Issue by ashok-tg** [covid19india/covid19india.github.io#1695]
**Is your feature request related to a problem? Please describe.**
As the govt. has released the zone tag against districts, it will be helpful to have visual cue across the map represented by zone color. The map gets updated as the status of district changes.

**Describe the solution you'd like**
Start with the table listing of district Vs zone tag. Extend to map in sub-menu.

**Additional context**
There is a lack of clarity among people regarding the zone tag released by govt. and the status of districts will potentially change on a day-day basis, going forward.

**Comment by arjunsoota** [comment]
check issue #1699

**Comment by shuklaayush** [comment]
Duplicates #1040
