### ISSUE TITLE
Negative Active cases Found

### ISSUE THREAD

**Issue by capturemathan** [covid19india/covid19india.github.io#1698]
**Describe the bug**
The active cases are negative under some circumstances like Recovered cases become equal to Confirmed cases (eg) **Thoothukkudi** active cases column in the below image.

**To Reproduce**
Fix the minor arithmetic error.

**Screenshots**
See **Thoothukkudi** active cases column

![covidindiabug](https://user-images.githubusercontent.com/36666781/80825490-1f38ed80-8bfe-11ea-943a-1f5353c958f0.jpg)

**Comment by dewansh3255** [comment]
Why do am I getting so many mails from COVID19 even after I have
unsubscribed the respective thing

**Comment by bee-rickey** [comment]
Issue has been fixed. TN was not publishing the data of the deceased and this lead to this discrepancy. Thank you for reporting. This does not require a front end fix as this is a data issue.
