### ISSUE TITLE
Colorize city name based on their zones

### ISSUE THREAD

**Issue by jashasweejena** [covid19india/covid19india.github.io#1699]
**Is your feature request related to a problem? Please describe.**
As the Govt. Of India has divided the cities and districts into several zones, namely, Red Zones, Orange Zones, and Green Zones. According to the color that the city or district is assigned, we can color the specific cell in the page by red, orange, or green. 

**Describe the solution you'd like**
Firstly, there is a list that the Govt. Of India has released. That list could be used to retrieve the color for a specific district or city, and then hardcode it into its respective cell. But this won't be dynamic and this will need regular human intervention to change its color, especially if the number of cases decreases or increases. So, I am suggesting to make an API that is dynamically updated from several sources, some of which may include 

- Manually updating it

- Scraping official Govt. websites to procure it.

Preferably, the second option.

**Additional context**
These are the cells that should be provided with an accent color in some way so that they reflect their status.
![image](https://user-images.githubusercontent.com/20218197/80832714-cc196780-8c0a-11ea-94af-6b984e2e3008.png)

**Comment by arjunsoota** [comment]
I have scraped the pdf and added a [csv](https://github.com/covid19india/covid19india-react/pull/1700) for the same.

**Comment by jashasweejena** [comment]
> I have scraped the pdf and added a [csv](https://github.com/covid19india/covid19india-react/pull/1700) for the same.

Great work! Can I use your data in the code?

**Comment by arjunsoota** [comment]
Yeah it's open source 😉

**Comment by jashasweejena** [comment]
Thanks 🙂

**Comment by shuklaayush** [comment]
Hi, we already published an [API yesterday](https://api.covid19india.org/zones.json). I'm not sure whether it was done manually, or if the data was scraped from the pdf. In any case, it's better if the information is published over an API and is not statically stored.

**Comment by jashasweejena** [comment]
> Hi, we already published an [API yesterday](https://api.covid19india.org/zones.json). I'm not sure whether it was done manually, or if the data was scraped from the pdf. In any case, it's better if the information is published over an API and is not statically stored.

Well, I don't think that the Green Zones are going to change to Red Zones overnight or vice versa. So even if the data IS hardcoded, I guess it still can be statically stored and updated. But anyway, an API is always more efficient.

**Comment by bee-rickey** [comment]
This is in progress. https://github.com/covid19india/covid19india-react/pull/1712

**Comment by shuklaayush** [comment]
Added via #1712
