### ISSUE TITLE
Update API Endpoints in Demographics Page.

### ISSUE THREAD

**Issue by shubhamjain2998** [covid19india/covid19india.github.io#1701]
**Describe the bug**
Currently, in the Demographics page, data is fetched from old raw_data API that is frozen now as shown in the documentation of API repository and as a result, page not showing anything from 27th April onwards. 

**To Reproduce**

1. Go to Demographics Page
2. Select any state and date after 26
3. No data is displayed

The code needed to be refactored according to the latest API Endpoints.

**Additional context**
I can help to fix this issue.

**Comment by bee-rickey** [comment]
This needs to be picked up by @jeremyphilemon after discussion on the behaviour. Putting this on hold till then.

**Comment by shuklaayush** [comment]
Fixed via #1899
