### ISSUE TITLE
Zone based font color of districts name (Red, Orange and Green)

### ISSUE THREAD

**Issue by navilg** [covid19india/covid19india.github.io#1702]
**Is your feature request related to a problem? Please describe.**

Government of India has categorised all the districts into three categories, Red, Orange and Green. And conditions in districts will be evaluated weekly and based on that districts will be placed in one of three categories every week.

**Describe the solution you'd like**

When we expand the state in the list, it display the list of districts and count of cases. Font color of those districts can be made based on the category to which they belong to. This will help identify tye districts of respective zones. 

**Describe alternatives you've considered**

Alternatively, Cell/textBox of district name can be filled with respective light color.

**Additional context**

**Comment by arjunsoota** [comment]
check issue #1699 and close this issue

**Comment by shuklaayush** [comment]
Duplicates #1699. Please comment over there
