### ISSUE TITLE
Wrong number of cases is indicated

### ISSUE THREAD

**Issue by bharath-spartan** [covid19india/covid19india.github.io#1705]
TIRUPUR, TAMILNADU 
[official Twitter handle - Tirupur district collector](https://twitter.com/Vijaykarthikeyn/status/1256228947760644097?s=09)
 
Actual active cases -4
Active cases shown in website -7

![Screenshot_20200502-072824](https://user-images.githubusercontent.com/64671780/80852662-defe5d00-8c47-11ea-9d01-4540b99785e3.png)

**Comment by shuklaayush** [comment]
Please report data discrepancies using [this form](https://forms.gle/MLeSrdwRuf8AjFkp9). Thanks! :)
