### ISSUE TITLE
The Title on the sidebar is distorted.

### ISSUE THREAD

**Issue by w3dg** [covid19india/covid19india.github.io#1707]
**Describe the bug**
The **COVID19INDIA** writing on the top left wraps in a weird way making it hard to read at once

**To Reproduce**

1. Go to homepage
2. See the logo distorted and wrapped around in the column

**Expected behavior**
I expect the text Covid 19 and India to be on separate lines

**Screenshots**
![Screenshot_2020-05-02-09-54-21-933](https://user-images.githubusercontent.com/51162936/80855352-27287a00-8c5e-11ea-9a01-2fbf0b294101.jpeg)

**Smartphone**

- Device: Lenovo TAB4 10
- OS: Android Nougat 7.0
- Browser Chrome
- Version 81.0.4044.117

**Comment by w3dg** [comment]
![image](https://user-images.githubusercontent.com/51162936/80909812-d80b4380-8d48-11ea-9cf0-355b9036448b.png)
**Desktop**
Device: Lenovo ideapad 110 151BR
OS: Windows 10 1903
Browser: Chrome
Version 81.0.4044.129

The issue occurs on desktop as well.

**Comment by w3dg** [comment]
Sorry for closing the issue it was a mistake. this issue still exists

**Comment by navkumar258** [comment]
Hi, i am looking for my first contribution, but not able to reproduce the issue in the latest build. Please help. thanks !

**Comment by w3dg** [comment]
@navkumar258 Well Yeah, the issue is with resolution and scaling i guess. I am on a 1366 * 768 laptop monitor, standard laptop resolution i guess, and when viewed on that resolution the text essentially wraps like the pics above. if i zoom onto 150% the text and ui is back fine again

**Comment by w3dg** [comment]
ok its fine now the issue is no more. closing for now.

**Comment by w3dg** [comment]
@navkumar258 Can you go to the production build and see if you can reproduce this? I emptied cache and hard reloaded the page even.

![image](https://user-images.githubusercontent.com/51162936/86323658-de3f7280-bc5a-11ea-919e-8b8b59c05fbe.png)

See how the heading wraps for me?

**Comment by w3dg** [comment]
Adding a break tag in the middle makes it a bit better for me?

![image](https://user-images.githubusercontent.com/51162936/86324096-a38a0a00-bc5b-11ea-9a36-cc4d9d6be291.png)
![image](https://user-images.githubusercontent.com/51162936/86324111-a97feb00-bc5b-11ea-988d-69ff7a9e55e7.png)

This change (although messes up colors i think that is done by me) fixes kin of for me.

![image](https://user-images.githubusercontent.com/51162936/86324555-53f80e00-bc5c-11ea-82de-bdbb2fb22b40.png)

**Comment by shuklaayush** [comment]
Hey @debopamgupta, any way to reproduce this on other screens? I tried adjusting the screen size in Chrome, but the logo doesn't seem to break

**Comment by sudevschiz** [comment]
Not reproducible.
