### ISSUE TITLE
West Bengal Worng City Name

### ISSUE THREAD

**Issue by shekzek** [covid19india/covid19india.github.io#1708]
Hey My Bro .... Here Have A Wrong District Name On West Bengal 
Here Purba Medinipur Is Not Purba It's Paschim ( West) and Paschim Medinipur is Purba (East).
example:

![Screenshot (133)](https://user-images.githubusercontent.com/62648401/80858001-0bc86980-8c74-11ea-984e-fc268f05884a.png)
Alter That Purba And Paschim.
Thank You .
#Kalibaba-Pro

**Comment by shuklaayush** [comment]
Thanks for pointing it out. District names are difficult to get right. Please refer to [this](https://github.com/covid19india/covid19india-react/issues/662#issuecomment-609377552)
