### ISSUE TITLE
How to make this app work both in Linux and Windows? [Help Needed] 

### ISSUE THREAD

**Issue by manigandan-dorairaj** [covid19india/covid19india.github.io#171]
Hi Devs,

I am new to react. Need advice.

I am a windows user. I couldn't run the website initially. I got 'PORT' is not recognized error.

To fix it I did these:
- Installed dotenv package and created a .env file with PORT=3000.
- Installed cross-env
- Removed  PORT=3000  from here  "react-scripts start css-watch"

It started working. Can you please advise is it correct or not? And how do we make this work both in Linux as well as Windows?

Thanks
Mani

**Comment by SanjeevYadavcr7** [comment]
I was also facing the same problem this is how i resolved it. On windows you can simply start by 
1. cloning the project files then use `npm install -D` to install all the required dependencies
2. after this you can do `npm run build` to build the project.
3. run `npm install -g serve` to serve the project on browser
4. at last run `serve -s build` and this will generate localhost address.
![windows](https://user-images.githubusercontent.com/33087026/77646458-9984ab00-6f8a-11ea-9d3f-9fe6de91cf65.PNG)

**Comment by rupeshkmr** [comment]
I tried the same in ubuntu 18.04 LTS
The server is running but the browser responds 
**404 the requested path cannot be found**

Any solution to this?

**Comment by manigandan-dorairaj** [comment]
Thanks, @SanjeevYadavcr7.  I am able to run it through this approach but it lost the instant updates (hot reload) feature. Whenever I make any changes I need to rebuild again which takes some time.

**Comment by manigandan-dorairaj** [comment]
> 
> 
> I tried the same in ubuntu 18.04 LTS
> The server is running but the browser responds
> **404 the requested path cannot be found**
> 
> Any solution to this?

In Linux you can just do this 

npm i && npm start

**Comment by rupeshkmr** [comment]
This error comes up
![image](https://user-images.githubusercontent.com/37209481/77650140-069b3f00-6f91-11ea-82a6-51f1d5557550.png)

**Comment by Rajanpandey** [comment]
Added the installation method for windows in readme.
PR: https://github.com/covid19india/covid19india-react/pull/177

**Comment by manigandan-dorairaj** [comment]
> 
> 
> This error comes up
> ![image](https://user-images.githubusercontent.com/37209481/77650140-069b3f00-6f91-11ea-82a6-51f1d5557550.png)

Did you run npm install  ?

**Comment by rupeshkmr** [comment]
yes

**Comment by manigandan-dorairaj** [comment]
## This worked for me.

In **package.json** under `scripts` -> `start` replace existing command to following 

`SET PORT=3001 && react-scripts start css-watch`

But I guess this may not work in Linux.

**Comment by Shashwat-Goyal** [comment]
The best solution for this is that we can create an .env file in the root of our application and set the PORT environment variable as 3001 there. That way we can run this app in both Linux and windows system. I can share a PR if required.

**Comment by jeremyphilemon** [comment]
Closed since future revision of codebase wouldn't require setting the port.
