### ISSUE TITLE
Display total number of added test

### ISSUE THREAD

**Issue by anilgupta1591** [covid19india/covid19india.github.io#1713]
**Description**
Number of added test in total count under Tested data column  as showing in other part like Recovered, Active , Deceased etc

![Coronavirus_Outbreak_in_India_covid19india_org](https://user-images.githubusercontent.com/9134071/80860214-e9d6e300-8c83-11ea-9a01-37cdc873a189.png)

**Comment by bee-rickey** [comment]
What should be the behaviour if a state does not report testing numbers for a specific day? Will the number show the 2 day jump for the next report?

**Comment by anilgupta1591** [comment]
Yes, if not reported then fine, otherwise as I see already updating test data daily statewise and All state data.

**Comment by bee-rickey** [comment]
> Yes, if not reported then fine, otherwise as I see already updating test data daily statewise and All state data.

So if on 1st May the test report is not given. On 2nd May the report is given, then what's the + count you would want to show in the graph for 2nd May? Would it be the delta from 30th April to 2nd May? Or zero?

**Comment by anilgupta1591** [comment]
On 1st May Zero and 2nd May the report is given, but as I see its implemented. If yes please close the ticket.

**Comment by shuklaayush** [comment]
Fixed via #1676
