### ISSUE TITLE
Scaling of Y axis

### ISSUE THREAD

**Issue by hardik124** [covid19india/covid19india.github.io#1714]
**Describe the bug**
All graphs use same Y range, it would be better if y ranges were independent for each graph , so for deaths graph, a Y axis of 100 as max would be better than 3K . 
**Screenshots**
![Screenshot from 2020-05-02 15-34-08](https://user-images.githubusercontent.com/6649948/80861206-9b791280-8c8a-11ea-9674-13908c9aa8cb.png)

**Desktop (please complete the following information):**

**Comment by shuklaayush** [comment]
Hi! Use this to adjust the scales
![Peek 2020-05-02 15-43](https://user-images.githubusercontent.com/27727946/80861345-ac765380-8c8b-11ea-9e71-86f816211880.gif)
