### ISSUE TITLE
path of MiniGraph is not visible in Edge.

### ISSUE THREAD

**Issue by sandeepsj** [covid19india/covid19india.github.io#1716]
**Describe the bug**
The path in the Mini Graph is not visible in Edge. 

**To Reproduce**
Open the page in Edge browser 

**Expected behavior**
The reason I found is that hexcode of rgba format is not working with edge. The problem can be fixed either by using rgba() function or by adding a style of attribute opaque.

**Screenshots**
![image](https://user-images.githubusercontent.com/36895341/80863304-e863e580-8c98-11ea-9e0d-c78cf7d260be.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Microsoft Edge 44.18362.449.0
- Version: 44

**Comment by prksh143** [comment]
I can fix it. I will change it to RGBA

**Comment by JunaidBabu** [comment]
Is this still happening?

**Comment by sandeepsj** [comment]
Yes it is still happening. I have made a PR

**Comment by sandeepsj** [comment]
Looks like nothing changed!!
