### ISSUE TITLE
Incorrect Data is shown in areal graph  for Kadapa District  (Andhra Pradesh)

### ISSUE THREAD

**Issue by sandeepr1** [covid19india/covid19india.github.io#1719]
Details: 
iOS 13.4
Safari Browser

![C8F1F4B4-F20E-4071-AFAD-9485A3978FDE](https://user-images.githubusercontent.com/15373793/80865715-13dbd580-8c83-11ea-8f78-ccdc94813bb7.jpeg)

![D179334B-9EC8-4B2E-8E88-D24253E70056](https://user-images.githubusercontent.com/15373793/80865670-d414ee00-8c82-11ea-9106-f62ec6b0386e.jpeg)

**Comment by nayakrahul** [comment]
This is happening due to spelling mismatch.

**Comment by nayakrahul** [comment]
@sudevschiz fix this too

**Comment by sudevschiz** [comment]
This has been fixed. Thank you!
