### ISSUE TITLE
Firozpur district of Punjab in map and in table are spelled different due to which the cases are not reported accurately on map

### ISSUE THREAD

**Issue by viggyprabhu** [covid19india/covid19india.github.io#1722]
**Describe the bug**
The district in Table is "Firozpur" but in map it is Ferozepur. Thats why in table it is showing 26 cases as of 2nd May but in map it shows 0% with 0 cases. 

**To Reproduce**
Hover over Firozpur in Punjab district table

**Expected behavior**
Map and table should be in sync.

**Comment by sudevschiz** [comment]
This has been fixed. Thanks for reporting!
