### ISSUE TITLE
Percentage of confirmed, active, recovered and decreased cases are showing same in the particular district in the map.

### ISSUE THREAD

**Issue by devtechnocode** [covid19india/covid19india.github.io#1726]
**Describe the bug**
Percentage of the confirmed, active, recovered and decreased cases are same in a particular district on the map but it's should be different as it is calaculated on the basis of the percentage of recovered, confirmed and decreased in a particular states accordingly.

**To Reproduce**
Show proper percentage of confirmed, active, recovered and decreased cases .

1. Go to '[ click to site](covid19india.org)'
2. Click on 'map'
3. Select particular state map.
4. See the percentage of confirmed, active, recovered and decreased cases for a particular district.

**Screenshots**
![Confirm](https://user-images.githubusercontent.com/52890488/80870007-545a4400-8cc1-11ea-98a2-e6d9388a30ce.png)
![active](https://user-images.githubusercontent.com/52890488/80870008-57edcb00-8cc1-11ea-8810-4c164732d2f5.png)
![recovered](https://user-images.githubusercontent.com/52890488/80870013-5cb27f00-8cc1-11ea-9b05-855d869b8fbe.png)
![decreased](https://user-images.githubusercontent.com/52890488/80870015-60de9c80-8cc1-11ea-8399-b631fd0ab182.png)
See this as reference it's example of one of the district of a particular state.

**Comment by ashishdawale20** [comment]
I can work on this issue..

**Comment by ashishdawale20** [comment]
@jeremyphilemon @shuklaayush - Please take a look
 Created PR https://github.com/covid19india/covid19india-react/issues/1726
After fix:
![varanasi1](https://user-images.githubusercontent.com/43884208/80873194-8032f500-8cd4-11ea-9b86-7d6853023a64.png)
![varanasi2](https://user-images.githubusercontent.com/43884208/80873197-832de580-8cd4-11ea-970a-abdf03d76c15.png)
![varanasi3](https://user-images.githubusercontent.com/43884208/80873201-85903f80-8cd4-11ea-9094-8f562af96024.png)
![varanasi4](https://user-images.githubusercontent.com/43884208/80873208-86c16c80-8cd4-11ea-8e41-ebd4547cf44b.png)

**Comment by shuklaayush** [comment]
Fixed via #1712
