### ISSUE TITLE
Total cases is not matching with sum of active, recovered, death cases.

### ISSUE THREAD

**Issue by pthadaka** [covid19india/covid19india.github.io#1728]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by sudevschiz** [comment]
This is due to some migrated cases (HP) and a non-covid related death in Karnataka. Please see the info icon near the state names.
