### ISSUE TITLE
Graph is not showing correctly

### ISSUE THREAD

**Issue by vikujangid** [covid19india/covid19india.github.io#1730]
![34BBD8C2-CABC-4A72-BDC4-34DB05EF77F1](https://user-images.githubusercontent.com/12443918/80898365-29530d00-8d20-11ea-8d7d-bb96bc9ba846.png)

Graph values are spreading in minus values. I’m not sure if it is an issue or not. But I supposed to let you know about it. Great work guys !!

**Comment by phoenicopteri** [comment]
If the number of recovered cases ( 126 in this case ) is more than the number of confirmed cases ( 106 in this case ) , the number of active cases will drop and show as negative on the graph
This isn't an issue
