### ISSUE TITLE
Colour-coding of districts

### ISSUE THREAD

**Issue by YuvrajGit** [covid19india/covid19india.github.io#1731]
Districts are classified as red, orange and green zones on the basis of incidence of coronavirus cases. I wish to see the same color coding for distric in this website.

Read more at:
https://economictimes.indiatimes.com/news/politics-and-nation/colour-coding-of-districts-in-battle-against-covid-19/articleshow/75416339.cms

**Describe the solution you'd like**
Either backgroud color or font color shall describe the zone status of each district

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by bee-rickey** [comment]
Duplicate https://github.com/covid19india/covid19india-react/issues/1040
