### ISSUE TITLE
Feature: To represent districts as red, orange and green zone as divided by government and show it on the map.

### ISSUE THREAD

**Issue by devtechnocode** [covid19india/covid19india.github.io#1732]
**Describe the solution you'd like**
Representation of district as red,orange and green zone on the map of states of india by adding a new column other than confirmed,active,recovered and decreased case , and so it on the map .

**Describe alternatives you've considered**
It can be also shown on the table by adding an column of zone to show zone of the districts.

**Additional context**
![Screenshot from 2020-05-03 16-00-09](https://user-images.githubusercontent.com/52890488/80911937-363f2300-8d57-11ea-8eda-08937f289f3c.png)
Like this add an option to view district with red,orange and green zone.

**Comment by shuklaayush** [comment]
Duplicates #1040

**Comment by devtechnocode** [comment]
But, the issue was about showing these zones on map. So, how can it be same as #1040 @shuklaayush

**Comment by shuklaayush** [comment]
@devtechnocode The other issue also mentions showing the zones on the map. Please comment over there, since we're already that discussion

**Comment by Sushanthece** [comment]
Could add one more option...
