### ISSUE TITLE
Himachal Pradesh Records miss-match

### ISSUE THREAD

**Issue by DhiralKaniya** [covid19india/covid19india.github.io#1735]
**Describe the bug**
Himachal Pradesh records are not matching properly.
Total:- 40
Active:- 1
Recovery:- 34
Death:- 2

I believe Total = Active + Recover + Death.
Attached screenshot for reference.

<img width="650" alt="Screenshot 2020-05-03 at 6 55 12 PM" src="https://user-images.githubusercontent.com/21332852/80915424-ddc84f80-8d6f-11ea-99b5-b3558b50a9de.png">

**Comment by DhiralKaniya** [comment]
This four case miss-match is effected in total as well.
Screenshot for reference.

<img width="549" alt="Screenshot 2020-05-03 at 6 59 33 PM" src="https://user-images.githubusercontent.com/21332852/80915485-41eb1380-8d70-11ea-899d-dd02c5b2af21.png">

**Comment by phoenicopteri** [comment]
HP has 4 migrated cases which are reduced from active# . Also, death of Tibetan refugee is included in deceased numbers but not in confirmed.
This is mentioned in the disclaimer ( the small i circle )  besides the state name

**Comment by DhiralKaniya** [comment]
I think this is miss-leading in total Confirmed cases. 
Confirmed cases should be =.Active +. recovered + Death. 
Is there any way to display 4 cases in the column of Total as well?

**Comment by bee-rickey** [comment]
> I think this is miss-leading in total Confirmed cases.
> Confirmed cases should be =.Active +. recovered + Death.
> Is there any way to display 4 cases in the column of Total as well?

Well as of now there's no way since the state govt isn't giving enough details about where the patients migrated to and why the refugee death has not been considered.
