### ISSUE TITLE
'No Results Found' on search field when nothing matches the entered text

### ISSUE THREAD

**Issue by lokeshpathrabe** [covid19india/covid19india.github.io#1739]
**Is your feature request related to a problem? Please describe.**
The Search Location/Essentials field on home page does not show "No Results Found" is the entered text matches no result. Feedback, in this case, is needed to suggest user reenter text in the field.

**Describe the solution you'd like**
Show "No Results Found" in results when nothing matches.

PS: If this suggestion is accepted please assign issue it to me. I would love to contribute it.

**Comment by nayakrahul** [comment]
![Screenshot_20200503-201756](https://user-images.githubusercontent.com/11428805/80917248-61d40480-8d7b-11ea-99bd-6ce81081ab52.jpg)

It is there in essentials page.

**Comment by lokeshpathrabe** [comment]
It's not on the home page. Similar should be added here
![image](https://user-images.githubusercontent.com/13837361/80917405-4c130f00-8d7c-11ea-9bde-bbd55ab49413.png)

**Comment by ashishdawale20** [comment]
I can work on this issue

**Comment by nmgvikas** [comment]
I can work too.

**Comment by mkesavan13** [comment]
Are any one of you working? Because this is not under either of your names yet. 

Kindly read the guideline [here](https://github.com/covid19india/covid19india-react/blob/master/CONTRIBUTING.md) on contribution and claiming an issue.
