### ISSUE TITLE
District Wise date should also be sorted by Confirmed column

### ISSUE THREAD

**Issue by ishan0445** [covid19india/covid19india.github.io#174]
![IMG_0040](https://user-images.githubusercontent.com/3998905/77643899-29742600-6f86-11ea-82fc-a7e0b4a8f9e0.JPG)

**Comment by Shashwat-Goyal** [comment]
@jeremyphilemon This is fixed and here is the PR:
https://github.com/covid19india/covid19india-react/pull/207

Please review the live deployed link:
https://covid19india-react-66o0srlls.now.sh/
