### ISSUE TITLE
Doubling time graph with progressing days in deepdive

### ISSUE THREAD

**Issue by nayakrahul** [covid19india/covid19india.github.io#1740]
**Describe the bug**
Doubling time graph with progessing days in deepdive will show at what rate the infection is spreading whether it is increasing or decreasing. The formula is given in following link: https://blog.datawrapper.de/weekly-chart-coronavirus-doublingtimes/ . We can use it to plot a graph.

**Comment by nayakrahul** [comment]
If it is relevant, please assign me.

**Comment by shubhamjain2998** [comment]
A graph like this can be very much informative I think.

![Screenshot from 2020-05-06 06-36-31](https://user-images.githubusercontent.com/30628775/81130695-4e38c180-8f66-11ea-9cd0-da9ac05ef54e.png)
