### ISSUE TITLE
Head

### ISSUE THREAD

**Issue by ghost** [covid19india/covid19india.github.io#1741]
-

**Comment by ayushagarwal016** [comment]
Also , this sort arrow doesn't have any work , arrange it so that it can sort the states by name.

![Screenshot_20200503-205314_Chrome](https://user-images.githubusercontent.com/62665157/80918022-63ec9200-8d80-11ea-92a1-344a69e94768.jpg)

**Comment by ghost** [comment]
Kindly delete this issue.

**Comment by ghost** [comment]
Please delete this complete issue.
