### ISSUE TITLE
District wise Deceased records are missing. 

### ISSUE THREAD

**Issue by DhiralKaniya** [covid19india/covid19india.github.io#1744]
**Describe the bug**
District wise Deceased records was there. After "Added zones to district tables" is all Deceased became empty for all states.

**To Reproduce**

1. Go to https://www.covid19india.org/
2. Click on Gujarat

**Expected behavior**
Deceased records should be displayed District wise. 

**Screenshots**
<img width="552" alt="Screenshot 2020-05-03 at 9 16 22 PM" src="https://user-images.githubusercontent.com/21332852/80918663-ba0f0480-8d83-11ea-9f8e-e1ae30d1591f.png">

**Comment by jeremyphilemon** [comment]
Patched :)
