### ISSUE TITLE
State table content overflow in mobile browser

### ISSUE THREAD

**Issue by DhiralKaniya** [covid19india/covid19india.github.io#1745]
**Describe the bug**
The last column "Deceased" for State table is not properly visible in the mobile browser. The content overflow from the right side of the screen. 

**To Reproduce**

1. Go to Mobile Chrome Browser
2. Search for https://www.covid19india.org/
3. Scroll down to State
4. Expand state
5. See the right side of Table

**Expected behavior**
Content should be properly fit in the browser

**Screenshots**
![WhatsApp Image 2020-05-03 at 9 22 20 PM (1)](https://user-images.githubusercontent.com/21332852/80918944-1c1c3980-8d85-11ea-9161-109e767b571c.jpeg)

![WhatsApp Image 2020-05-03 at 9 22 20 PM](https://user-images.githubusercontent.com/21332852/80919004-48d05100-8d85-11ea-91ef-070f6d17fbfb.jpeg)

**Smartphone (please complete the following information):**

- Device: Vivo V9, iPhone 5, iPhone 6
- OS: Android, iOS
- Browser Chrome

**Comment by jeremyphilemon** [comment]
Seems to be working fine in this environment

<img width="656" alt="Screen Shot 2020-05-03 at 7 15 31 PM" src="https://user-images.githubusercontent.com/17938322/80919430-811a6400-8d72-11ea-957c-1603ee01b664.png">

Not sure why chrome on iOS is behaving differently. Looking for an more elaborate fix than a media query (last resort)

/available

**Comment by kousiksatish** [comment]
I have checked in my Redmi Note 8 pro... Seems to be working fine...

**Comment by shubhamjain2998** [comment]
Yeah, content is overflowing in table component as I can see in my phone, and also in chrome dev tools.
![Screenshot from 2020-05-03 23-14-00](https://user-images.githubusercontent.com/30628775/80921495-58a36180-8d94-11ea-9187-3ea560f613bd.png)

**Comment by DhiralKaniya** [comment]
The resolution is 375 * 667 and 325 * 568 on which I got this issue.

**Comment by relaxedcoder** [comment]
/claim
I have been working on this issue and I have found a solution.

**Comment by vigneshbrb** [comment]
![7BCFD7C1-96ED-462E-A208-B51474FFEA8E](https://user-images.githubusercontent.com/20576119/83902423-f87c5280-a779-11ea-9d40-5c5c6cfff672.png)
I have the same problem in my iPhone SE in which district names are overflowing.
