### ISSUE TITLE
Default sort behaviour should be Descending order of confirm cases not Ascending order

### ISSUE THREAD

**Issue by DhiralKaniya** [covid19india/covid19india.github.io#1746]
**Describe the bug**
Default sort is happening on the Ascending order of confirm cases for new users.
Table sort column default behavior should be descending order of confirm column for new users. 

**To Reproduce**

1. Remove sort order from local storage if any
2. Go to https://covid19india-react.now.sh/
3. Scroll down to State table

**Expected behavior**
Sort should be happen to Descending order of confirm column. Same for district-level information.

**Screenshots**

<img width="1678" alt="Screenshot 2020-05-03 at 9 38 37 PM" src="https://user-images.githubusercontent.com/21332852/80919451-8930ce80-8d87-11ea-9a7c-7f16da3a1bd9.png">

**Comment by jeremyphilemon** [comment]
Thanks! Patched :)

https://github.com/covid19india/covid19india-react/commit/54ae761915e5283680294f9b5b4e9991aabb3ba1

**Comment by DhiralKaniya** [comment]
Adding local storage image for batter understanding.

<img width="1680" alt="Screenshot 2020-05-03 at 9 52 19 PM" src="https://user-images.githubusercontent.com/21332852/80919611-8e424d80-8d88-11ea-9f28-f366e605050b.png">

**Comment by DhiralKaniya** [comment]
sorry comment was not reflected.
