### ISSUE TITLE
[BUG]: Crowdsourced Patient Database button redirects to API page.

### ISSUE THREAD

**Issue by Cryptonex7** [covid19india/covid19india.github.io#1752]
**Describe the bug**
Crowdsourced Patient Database button on the main website and on the API home page, both redirect to API page itself.

**To Reproduce**

1. Go to 'https://www.covid19india.org/'
2. Scroll down to 'The End of the page'
3. Click on 'CROWDSOURCED PATIENT DATABASE'
4. See error: Redirects to the API page.

**Expected behavior**
Its should transfer to the Database page where everything is placed, typically in a Spreadsheet - Google Sheets as before?

**Desktop (please complete the following information):**

- OS: Windows
- Browser: Edge, Chrome
- Version: Respective Latest Versions

**Smartphone (please complete the following information):**

- Device: Samsung Galaxy A6+
- OS: Android Pie
- Browser: Edge, Chrome
- Version: Respective Latest Versions

**Additional context**
If that button isnt functional anymore - or even temporarily not functioning, it should be removed.

**Comment by bee-rickey** [comment]
Since we have partitioned the data into three different sheets, the google sheets link has been deprecated on the site. Please use the csv file if you wish to see in the sheet format.

**Comment by Cryptonex7** [comment]
Hey @bee-rickey
While I am fully Aware of the data partition that took place, I have raised this issue from a UX perspective. 
______

![image](https://user-images.githubusercontent.com/34197902/81081093-1ce0d700-8f0f-11ea-9ac7-0401ca31ca77.png)

## This Button for "CROWDSOURCED PATIENT DATABASE" should be removed, and also the hyperlinks on https://api.covid19india.org
_____

I can take up the issue and submit a PR if Status is turned to Available.
