### ISSUE TITLE
Add no of patient recovered in district wise  display

### ISSUE THREAD

**Issue by shamse-alam** [covid19india/covid19india.github.io#1758]
**Is your feature request related to a problem? Please describe.**
Currently, it displays the count of a new patient in red at the district level

**Describe the solution you'd like**
Adding count of patient recovered at district wise will be a good feature. Currently its display a commutative count at the state level

**Comment by bee-rickey** [comment]
We do show the recovered in both the table and state views. Can you elaborate where you need the recovered count?
<img width="515" alt="Screenshot 2020-05-04 at 5 31 30 PM" src="https://user-images.githubusercontent.com/63364562/80963734-314ca300-8e2d-11ea-9e39-32cbbe270a9b.png">

**Comment by shamse-alam** [comment]
My suggestion was to daily recovered count at the district level similar to the state level in green color. It's there. 

Thanks
