### ISSUE TITLE
Bugs in state expansion button

### ISSUE THREAD

**Issue by rajathsn** [covid19india/covid19india.github.io#176]
**Describe the bug**
1. State expansion button/symbol is not aligned properly 
2. The clickable area of state expansion button is to small. Unable to expand it to show district wise table

**To Reproduce**
1. Go to ‘any mobile browser'
2. Click on 'state expansion symbol' see the attachment 

**Expected behavior**
1. Symbol to be aligned properly to state.
2. Large clickable/tap-able area will help in selecting expansion 

**Screenshots**
![EA4D4DE7-73C3-4DA3-83C3-57AB04009B9D](https://user-images.githubusercontent.com/52188338/77648214-c6868d00-6f8d-11ea-9b90-06c43e34fa52.jpeg)

**Comment by rebelgiri** [comment]
Issue seems to fixed. Can we close it?

![image](https://user-images.githubusercontent.com/18268525/77777023-eb096480-7074-11ea-927d-d13b6292aa9b.png)

**Comment by rajathsn** [comment]
Fixed
