### ISSUE TITLE
hover is not working as expected

### ISSUE THREAD

**Issue by Banbari** [covid19india/covid19india.github.io#1762]
**Describe the bug**
On hover to some state row right side of page is showing the information related to hovered state but after removing the mouse pointer from hovered row it's still showing previous hovered state data until we are not hover to some other state row. which is not expected and also a bad user experience. Generally if mouse pointer is removed from hovered state row, data should be restored to some default count which could be the data of country.

**To Reproduce**
1. Hover to any state row and check the total
2. remove the mouse pointer from that row
3. it's still showing the previous focused row data.

**expected behavior**
Data should be reset to selected row if available otherwise reset to country data.

**Comment by bee-rickey** [comment]
Hi can you provide more details? Which browser you are facing this issue in? Screenshot maybe?

**Comment by Banbari** [comment]
I've checked in chrome on mac. Since can't capture the mouse pointer in Screenshot so attaching the video. please check the link [https://vanspublicbucket.s3.us-east-2.amazonaws.com/Hover+Issue.mov](url)

**Comment by Banbari** [comment]
after removing the mouse pointer from last focused state row, it's still showing last focused row data.

**Comment by cheralathann** [comment]
Yes, after mouse leave table row remains highlighted. Need to remove this `is-highlighted` class from table row after mouse leave.

**Comment by Banbari** [comment]
I've fixed it in other way where if some state is expended/clicked then default will be that clicked row data other country data will be there.
