### ISSUE TITLE
Active cases showing in negative

### ISSUE THREAD

**Issue by ikshitiz** [covid19india/covid19india.github.io#1765]
**Describe the bug**
Active cases showing in negative for few districts of Kerala.

**To Reproduce**
See screenshot 

**Expected behavior**
It should not be negative 

**Screenshots**
Added
![Screenshot )](https://user-images.githubusercontent.com/23147077/80965396-14fe3580-8e30-11ea-86cf-d292cf6e3735.png)

- OS: Windows
- Browser: chrome
- Version: 55.x

**Comment by Joyouou** [comment]
so does for Meghalaya

![image](https://user-images.githubusercontent.com/33721742/80965549-5393f000-8e30-11ea-8058-c8922db7d1f7.png)

**Comment by jaibatrik** [comment]
https://github.com/covid19india/covid19india-react/issues/1313#issuecomment-623478272
