### ISSUE TITLE
Blank page displayed, when selecting Daman & Diu through dropdown in statewise page

### ISSUE THREAD

**Issue by iamnagaky** [covid19india/covid19india.github.io#1769]
**Describe the bug**
Blank page displayed, when selecting Daman & Diu through dropdown in state-wise page

**To Reproduce**
Steps to reproduce the behaviour:

For Eg. 
1) Enter Tamil Nadu state page from main page
2) From the Dropdown in Home/Tamil Nadu ^ select Daman & Diu
3) Only a blank page is displayed

**Expected behaviour**
Daman & Diu state page should be displayed.
If there is no info available, appropriate error message must be displayed.
Else Daman and Diu needs to be removed from drop down.

**Screenshots**

**Desktop (please complete the following information):**

- macOS
- Chrome
- Version 81.0.4044.129

**Comment by shuklaayush** [comment]
Fixed via 6a801d6f41fd26e7c9725a4c248ae24b03f533ee
