### ISSUE TITLE
Update Data By Dristict

### ISSUE THREAD

**Issue by shekzek** [covid19india/covid19india.github.io#1772]
![Screenshot (134)](https://user-images.githubusercontent.com/62648401/80986354-18081e80-8e4e-11ea-83a3-599869e66bff.png)
Update That...!!!
Please Visit That  link :-
That Was Given by West Bengal govt. That is New Format Which Given By WB Govt.
URL is
https://www.wbhealth.gov.in/uploaded_files/corona/WB_DHFW_Bulletin_4TH_MAY_FINAL.pdf
That This Describe Vary Well By District By Hole Transparency Maintained.

District Wise Containment Zones
https://wb.gov.in/containment-zones-in-west-bengal.aspx

**Comment by bee-rickey** [comment]
This is already updated.
