### ISSUE TITLE
Wrong 'num of cases' scale for Daily Cases histogram

### ISSUE THREAD

**Issue by pavelkudr** [covid19india/covid19india.github.io#1780]
**Describe the bug**
Open page https://www.covid19india.org/deepdive
Wrong 'num of cases' scale for Daily Cases histogram
Selected item has 3656 confirmed cases for 04 may, but the top end of red line is between 4500 and 5000 of the scale

**To Reproduce**
See screenshot

**Expected behavior**
Top end of red line should be between 3500 and 4000 of the scale
**Screenshots**
![Screenshot 2020-05-05 at 10 55 36](https://user-images.githubusercontent.com/16879850/81042210-aae1a100-8ec0-11ea-8479-9a4e31e52161.png)

**Desktop (please complete the following information):**

- OS: macOS 10.15.4 (19E287)
- Browser: safari
- Version: 13.1 (15609.1.20.111.8)

**Comment by phoenicopteri** [comment]
This graph shows the total number of confirmed + deceased + recovered cases,
You can check for the total number of confirmed cases only by toggling off deceased and recovered 

<img width="290" alt="daily cases" src="https://user-images.githubusercontent.com/11295641/81056955-28b9a280-8ee9-11ea-800d-e7e31f109c10.png">
