### ISSUE TITLE
Home page shifts right while hovering on side bar b'coz of the right scroll bar.

### ISSUE THREAD

**Issue by vipul1999** [covid19india/covid19india.github.io#1781]
**Describe the bug**
The whole home page shifts right while hovering on the left sidebar and It comes into original form when hovering ends. This creates an undesired user experience.

**To Reproduce**

1. Hover over the left sidebar
2. Sidebar will expand
3. Home web page shift right
4. Right scroll bar disappears 
5. Returns into original when hovering ends

**Expected behavior**
The Home web page should not shift that way it will look more stable and robust.
**Screenshots**

![HomepageGlitch](https://user-images.githubusercontent.com/42087486/81043879-cce31f80-8ed0-11ea-90f6-6dcfe95f46f1.gif)

**Desktop (please complete the following information):**

- OS: Windows 10 ( V-1909)
- Browser: Chrome (Version 81.0.4044.129 (64-bit))

**Comment by wsameer** [comment]
Let me /claim this issue

**Comment by vipul1999** [comment]
This is fixed Now
