### ISSUE TITLE
Graph of Active Cases

### ISSUE THREAD

**Issue by atulgaurnet** [covid19india/covid19india.github.io#1782]
Hi,

1. Please include trends of active cases in total cases graph in deep dive section

![image](https://user-images.githubusercontent.com/64836891/81053105-34ee3180-8ee2-11ea-87db-9801b3950dd6.png)

2. Also for total cases by state please provide a selection to view trends for total or active cases.
![image](https://user-images.githubusercontent.com/64836891/81053446-b5ad2d80-8ee2-11ea-8596-f2354a72bc05.png)

3. Further for states growth trends please provide a toggle to deselect all states just like you have added for total cases for states
![image](https://user-images.githubusercontent.com/64836891/81053594-f442e800-8ee2-11ea-9b93-1bbe8a51fac4.png)

**Comment by gyanendrapatro** [comment]
You can assign it to me I can fix it

**Comment by atulgaurnet** [comment]
@gyanendrapatro Thanks for your response but it seems that I cannot assign an issue to you or is it something that I am missing here. I am also new to this space.
