### ISSUE TITLE
Value in graph uses Indian numbering system, while axis uses international number system

### ISSUE THREAD

**Issue by AgamAgarwal** [covid19india/covid19india.github.io#1787]
**Describe the bug**
For example, in the "Tested" graph, the current value is shown as `11,07,233` while the Y-axis of the graph shows the numbers in millions like `1M`.

**To Reproduce**

1. Go to https://www.covid19india.org/
2. Scroll down to "Tested" graph on the bottom right.
3. Select "All States" to show data for all states. (Bug is there even without this but based on current numbers it shows only when "All States" is selected.

**Expected behavior**
Numbering system used in graph should be consistent with numbering system used in the axis.

**Screenshots**
<img width="589" alt="Screenshot 2020-05-05 at 6 55 12 PM" src="https://user-images.githubusercontent.com/4919246/81071191-f7010580-8f01-11ea-8fd8-f41ea20226c3.png">

**Desktop (please complete the following information):**

- OS: OSX 10.15.4
- Browser: Chrome
- Version: 81.0.4044.129

**Additional context**
None

**Comment by ayushya** [comment]
I would like to /claim it
