### ISSUE TITLE
Indicate a difference between no cases in a state vs data not updated yet.

### ISSUE THREAD

**Issue by sai-chervi** [covid19india/covid19india.github.io#1791]
I'm always confused about what to comprehend when I do not see a red upward arrow beside the confirmed cases of a state. Does it mean there were no new cases in that state that day? Or does it mean the data hasn't been obtained yet?

I think it would be a good idea to show a zero (say, in blue- without an arrow) to represent when there have been no new cases in a state on a day. 
Alternatively, we could show a yellow warning like symbol for those states we haven't obtained data yet to show that the data would soon be updated.

Till 11 PM IST on 5th May, Telangana showed nothing beside confirmed cases. It then got changed to 11 cases within few minutes. (Here data wasn't updated). Mizoram also didn't show anything beside the confirmed cases. It did have zero cases today!

**Comment by bee-rickey** [comment]
From a data operations point of view, unless states say that they have zero cases that day, we cannot update it to zero. And a lot of states do not send out a report at all on a given day if they have no new cases/recoveries to update for the day.
