### ISSUE TITLE
 e.changeLanguage is not a function [Status: Review Needed]

### ISSUE THREAD

**Issue by kumargulshan91** [covid19india/covid19india.github.io#1795]
#1798  [Status: Review Needed] e.changeLanguage is not a function error is coming in console due to not initialization of language modules properly

**Comment by kumargulshan91** [comment]
#1798 added fix for localization issue

**Comment by bee-rickey** [comment]
Hi @kumargulshan91 did you have a read about the contributing guidelines: https://github.com/covid19india/covid19india-react/blob/master/CONTRIBUTING.md ? Please do not fix an issue unless one of the mods has a look at the issue.
