### ISSUE TITLE
Feature: To show details of top disctricts active, recovered and decresed cases similar to confirm cases on state  page when hover.  

### ISSUE THREAD

**Issue by devtechnocode** [covid19india/covid19india.github.io#1796]
**Is your feature request related to a problem? Please describe.**
To show details of top disctricts active, recovered and decresed cases similar to confirm cases on state  page when hover. By hovering on the confirm, active, recovered and decreased cases we can see the data of top district on the state page. 

**Describe the solution you'd like**
By adding the same as done for confirmed cases.

**Additional context**
Like in this on right side it is showing top districts confirmed cases, it should similarly show the active, recovered and decresed cases when hovered on. 
![Screenshot from 2020-05-06 02-01-43](https://user-images.githubusercontent.com/52890488/81113798-698fd680-8f3e-11ea-9d38-4c1effd2ac7d.png)

**Comment by shuklaayush** [comment]
Duplicates #1603

**Comment by devtechnocode** [comment]
But , it not similar as I ssaid to show the active , recovered and decreased cases as shown for confirmed cases on the right side of the state page as you can see in the screenshot @shuklaayush

**Comment by shuklaayush** [comment]
Hey @devtechnocode, this was addressed in the PR linked to that issue. Anyways, it's been added with #1626.
