### ISSUE TITLE
Overlapping zone maps when switched from one state to another

### ISSUE THREAD

**Issue by sudevschiz** [covid19india/covid19india.github.io#1802]
**Describe the bug**
Boundary of the previous state map remains when switched from one state to another on the Red/Orange/Green zone maps on the main page.

![image](https://user-images.githubusercontent.com/4298868/81139855-3e3ed300-8fa2-11ea-8977-9ec53c318317.png)

**To Reproduce**
1. Switch to All India zone view.

2. Dropdown the districts of any state (Chhattisgarh, in this example) from the table.
![image](https://user-images.githubusercontent.com/4298868/81140374-10f32480-8fa4-11ea-9799-7f7603a9aa07.png)

3. Double click on any district of a **different** state (Uttarakhand, in example) to get state level zone
![image](https://user-images.githubusercontent.com/4298868/81140413-33853d80-8fa4-11ea-8135-18289a5d19e0.png)

4. Hover on the district table dropped in Step 2.
![image](https://user-images.githubusercontent.com/4298868/81140453-59124700-8fa4-11ea-9bd3-eb86019d687b.png)

Uttarakhand boundary map is not removed before Chattisgarh is drawn over it.

**Expected behavior**
Clear the previous state boundary before plotting new.

**Desktop (please complete the following information):**

Can confirm in Chrome and Safari

**Smartphone (please complete the following information):**
Same behaviour with Tap on phone

![image](https://user-images.githubusercontent.com/4298868/81140673-33397200-8fa5-11ea-8fca-cb5fca264955.png)

**Comment by shuklaayush** [comment]
Fixed via e0b5657802c6248b5185294965bc992af1f8eb3a
