### ISSUE TITLE
Today's Data is displaying wrong.

### ISSUE THREAD

**Issue by priya90rw8l** [covid19india/covid19india.github.io#1804]
**Describe the bug**
Today's Data is displaying wrong.

**To Reproduce**

1. Go to 'https://www.covid19india.org/'
2. Verify data

**Expected behavior**
Data shuuld be proper.

**Screenshots**
![Screenshot 2020-05-06 at 5 10 31 PM](https://user-images.githubusercontent.com/17856723/81172951-d649b600-8fbc-11ea-96a3-d49a8f6768c6.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by parthbhide** [comment]
yes i came here for this !! Got a mini heart attack after looking that +19,739  !!

@shuklaayush @sudevschiz

**Comment by swapdewalkar** [comment]
Working fine for me. Can you add brower details. 
I checked on phone and mac working fine.

**Comment by shuklaayush** [comment]
Seems to be fixed
