### ISSUE TITLE
Search placeholder stops working after blur event

### ISSUE THREAD

**Issue by rbharadbb** [covid19india/covid19india.github.io#1805]
**Describe the bug**
Placeholder of the search input field goes away after first blur event on search input.

**To Reproduce**

1. Go to home page
2. You can see the placeholder of the search input field is working
3. Click on search box
4. Remove the focus (click somewhere else)
5. Now the placeholder is gone

**Expected behavior**
Once focus is removed from the search input, the placeholder should work as originally working

**GIF**

![search-onblur-before](https://user-images.githubusercontent.com/60638346/81172832-a69aae00-8fbc-11ea-943c-c551702f6c4b.gif)

**Desktop (please complete the following information):**

- OS: macOS (10.14.4)
- Browser: Chrome
- Version: 81.0.4044.129

**Smartphone (please complete the following information):**

- Device: iPhoneX
- OS: iOS 13.3.1
- Browser: Chome
- Version: 81.0.4044.124

**Comment by rbharadbb** [comment]
@bee-rickey Thank you for assigning this issue to me. I've already raised #1768 to fix this issue. Please have a look.

**Comment by anuj-kh** [comment]
I am willing to work on this issue if it's still pending.

**Comment by rbharadbb** [comment]
Thank you for looking into this @anuj-kh . I have already raised a PR for fixing this issue. Link - https://github.com/covid19india/covid19india-react/pull/1768
