### ISSUE TITLE
Timeseries explorer not aligned center in homepage in mobile

### ISSUE THREAD

**Issue by nayakrahul** [covid19india/covid19india.github.io#1807]
**Describe the bug**
Timeseries explorer elements are not aligned center. They are towards left side.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to Home
2. Scroll down to timeseries explorer
3. Notice the issue

**Expected behavior**
It should be same as in state page

**Screenshots**
 
![Screenshot_20200506-171915](https://user-images.githubusercontent.com/11428805/81173468-bbc40c80-8fbd-11ea-91ec-90d62af9d4f1.jpg)

**Comment by shuklaayush** [comment]
Fixed via 7740f5c8f764b7a521fdfae695b622f160d2e734
