### ISSUE TITLE
Change state colour in map according to active cases

### ISSUE THREAD

**Issue by DattaPurohit** [covid19india/covid19india.github.io#1809]
**Describe the solution you'd like**

Map colour gradient which changes dynamically according to active cases would give a more accurate visualisation of the data

**Comment by shuklaayush** [comment]
Did you try this?

![Peek 2020-05-06 18-27](https://user-images.githubusercontent.com/27727946/81179581-7a385f00-8fc7-11ea-8ad0-92255c4e9610.gif)
