### ISSUE TITLE
Today's bulletin data updated

### ISSUE THREAD

**Issue by ShekharReddy4** [covid19india/covid19india.github.io#1811]
**Is your feature request related to a problem? Please describe.**
I want to see on the home page if today's bulletin is released by state and the data is updated or the data is as of yesterday.

**Describe the solution you'd like**
add a column on the far right and put a :heavy_check_mark: if today's bulletin is updated yet.

**Describe alternatives you've considered**

**Additional context**

**Comment by bee-rickey** [comment]
The uptick on each state tells whether the data is updated today. That's an indication of data being updated based on today's bulletin?

**Comment by ShekharReddy4** [comment]
but 'no uptick' doesn't mean that it is not updated --assuming that a few northeast states are having no updates(everything is stable for the day/no bulletin) for the day.

**Comment by shuklaayush** [comment]
I think the 'Last updated...' part on expanding the state serves this purpose. We're already pretty much out of space in the main table.
