### ISSUE TITLE
Show data from other top 10 countries for comparison

### ISSUE THREAD

**Issue by parasgoyal12** [covid19india/covid19india.github.io#1813]
**Is your feature request related to a problem? Please describe.**
A comparison chart with countries from top 10 total case count in the deep dive section as people need to visit other sources like worldometers or john hopkins

**Describe the solution you'd like**
The table might include similar stats as the worldometers.info/coronavirus
Data can be extracted from john hopkins.
**Describe alternatives you've considered**

**Additional context**

**Comment by shuklaayush** [comment]
I think this is out of our scope
