### ISSUE TITLE
Track daily trend of how zones look like 

### ISSUE THREAD

**Issue by ishandutta2007** [covid19india/covid19india.github.io#1815]
**Is your feature request related to a problem? Please describe.**
Creating a new issue as per discussion https://github.com/covid19india/covid19india-react/issues/1040#issuecomment-624843738

**Describe the solution you'd like**
Some works have been done on this https://github.com/covid19india/covid19india-react/pull/1679
Just the code needs refactoring to move it from UI to API. And since govt may have some more criteria on their once in a while published zone list, not to confuse with govt list we would name this dynamic zones something like _recent positive zone, moderately old positive zone, very old positive zone_

**Additional context**
This issue is branched out from https://github.com/covid19india/covid19india-react/issues/1040

**Comment by bee-rickey** [comment]
This isn't a straight forward classification. Zone classifications are based on the state/central decisions. These decisions cannot be taken by us. Also, the api for Zones is already available [here](https://api.covid19india.org/zones.json).

**Comment by ishandutta2007** [comment]
@bee-rickey we are talking about different classification not the usual Red, Orange , Green one by government. Secondly we are creating this new kind of parallel classification because the standard govt zones are not updated daily. As the title states the new system will get updated daily and give us a clear picture of where the country is heading. Please refer to the thread in the link for detailed discussion on this.
