### ISSUE TITLE
Sticky 'spread trends' component is not working

### ISSUE THREAD

**Issue by purveshmakode24** [covid19india/covid19india.github.io#1817]

**Comment by anantakrroy** [comment]
Why was this closed?  I see the sticky attribute set but it is not "truly" sticky. When the `.home-left` component is scrolled to the bottom , the `.home-right` starts scrolling after a certain point too. I do not know the reason why this happens even as `position: sticky!important;` is set and hence came to check if someone brought this up.

**Comment by shuklaayush** [comment]
I guess that's because an element is only `sticky` till the end of it's parent. Anyways, the issue was closed because they didn't follow the issue template, and it was difficult to make out what they meant.
