### ISSUE TITLE
Active testing in labs citywise

### ISSUE THREAD

**Issue by 1709abhishek** [covid19india/covid19india.github.io#1819]
**Is your feature request related to a problem? Please describe.**
During these lockdowns, people are constantly searching for productive and useful news for the coronavirus cure and testing. We can add name and number of labs state or citywise to keep people informed about the testing carried by given labs.

**Describe the solution you'd like**
We can map the labs in a seperate tab to specify that in which all cities testing labs are present and we can specify count as well as the name of labs.

**Comment by bee-rickey** [comment]
Have you checked the essentials tab? https://www.covid19india.org/essentials
