### ISSUE TITLE
Once the user clicks on State/UT or District list sorting header(Arrow - Up or Down), there is no way to get back to default sorted list as per no of cases. 

### ISSUE THREAD

**Issue by kapilraghuwanshi** [covid19india/covid19india.github.io#1820]
**Describe the bug**

Once the user clicks on sorting on states or districts, there is no way to get back to default sorted as per no of cases. Since, we are storing user's sorting preference in the local storage, untill we remove that there is no way to get back to the original sorted even if you refresh the page. This is common issues across web, mobile.

**To Reproduce**

1. Go to '...' Home page 
2. Click on '....' State/UT or District list sorting header (arrow up/down)
3. Scroll down to '....' full list and district wise as well
4. See error Check once you clicked on the header, you can not go back to default sorted list

**Expected behavior**

Expectations should be non-persistence of sorting behaviours. Instead of storing save user's sorting preference to local storage, we should store into session storage, so that they get their current preference in current session only. Next time they visit this site, they get the default sorted list again. Otherwise, there is no going back possible for end user to default sorting way.

**Screenshots**

![image](https://user-images.githubusercontent.com/38580123/81258328-080d5c00-9053-11ea-9e12-fbe4d520731d.png)
![image](https://user-images.githubusercontent.com/38580123/81258416-3f7c0880-9053-11ea-8651-1290c78d7ead.png)

**Desktop (please complete the following information):**

- OS: [e.g. iOS] MacOS Catalina
- Browser [e.g. chrome, safari] Google Chrome
- Version [e.g. 22] Version 81.0.4044.129 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

- Device: [e.g. iPhone6]. RealMe Pro 2
- OS: [e.g. iOS8.1] Android 9
- Browser [e.g. stock browser, safari] Google Chrome

**Additional context**
Once the user clicks on sorting on states or districts, there is no way to get back to default sorted as per no of cases. Since, we are storing user's sorting preference in the local storage, untill we remove that there is no way to get back to the original sorted even if you refresh the page. This is common issues across web, mobile.

**Comment by nayakrahul** [comment]
The default sorting is based on no. of confirmed cases. You can click on confirmed header tab to get default sorting order. You can sort the rows on the basis of alphabetical order, no. of confirmed, active, recovered and deceased cases.

**Comment by bee-rickey** [comment]
One can always click on confirmed header to get back to default sorting order no? Why does it have to be per session? One could easily make an argument that the choice should persist across sessions.

**Comment by kapilraghuwanshi** [comment]
@nayakrahul explained the complete behaviour of sorting in the data tables, so this issue can be closed now. Thanks for the support.
