### ISSUE TITLE
Please Add this features tab in website that points to https://coronalatestupdate.com

### ISSUE THREAD

**Issue by iamkanhaiya** [covid19india/covid19india.github.io#183]
My team just seen this website , good guys you're doing a amazing work ! We at Wappgo also took an initiative and build a app https://coronalatestupdate.com/app as well as website https://coronalatestupdate.com , Our website has a section to track live status of India for that we are going to build a dedicated dashboard for India, but when i saw your website i think yes !! that's what we need and it is already there ..! So i like to point your website on our section . And i request you to create section of search nearby hostpitals and testcenters and point this link https://coronalatestupdate.com/hospitalandtestcenters.php and also for downloading app if someone wants to track status of whole world and dedicated countries !! please check out our app and website as well .!! Together we can help more better to our audience .Thankyou !!

**Comment by siddharthhp** [comment]
https://coronalatestupdate.com/hospitalandtestcenters.php

This seems to be a really helpful link and a must have feature in the current application. Let's wait for admin to get back if we really can get this link in our application.

**Comment by iamkanhaiya** [comment]
Yes !! for sure.

**Comment by siddharthhp** [comment]
@jeremyphilemon Can you please take a look at this and let us know if we can get the hospitals and test centers link added to our application. If yes I can take it up!

**Comment by sudevschiz** [comment]
@iamkanhaiya @siddharthhp Thanks for bringing this website to our attention! Great work. However, we won't be able to point to this website as it is not using any of our data and is unrelated.

Thank you!

**Comment by iamkanhaiya** [comment]
@sudevschiz its not about the data..!! Its about to help the society .!! Please take a look it can help many people .!! Its time to think about our country.
 @jeremyphilemon please you too have a look.
