### ISSUE TITLE
Bug - Navbar About icon Incorrect navigation

### ISSUE THREAD

**Issue by Priya1114** [covid19india/covid19india.github.io#1832]
**Describe the bug**
When the About icon inside Navbar is clicked it is navigating to Homepage. whereas the text  'About' beside the icon is navigating correctly to `/about`.
This happening because the link to the icon is `/faq` whereas the link to the text is `/about`.

**To Reproduce**

1. Go to the last option in Navbar and hover on the question mark icon.
2. Click on the icon.
3. It Navigates to the homepage which also happens when the first option in navbar i.e homepage icon is clicked.

**Expected behavior**
When the about the icon in the navbar is clicked it is expected to navigate to `/about` route just like 'About' text beside the icon does.

**Screenshots**
<img width="1440" alt="Screenshot 2020-05-08 at 2 21 24 PM" src="https://user-images.githubusercontent.com/22993719/81389404-66ac0600-9137-11ea-8616-b8f94694b532.png">

**Desktop (please complete the following information):**

- Browser: Not a Browser specific issue.

**Comment by niinpatel** [comment]
I'd like to work on this if possible.

**Comment by Priya1114** [comment]
Let me /claim this issue
