### ISSUE TITLE
The know more in the home page (compiled from State govt... )href seems to be not working. Its just refreshing the home page.

### ISSUE THREAD

**Issue by ruralad** [covid19india/covid19india.github.io#1833]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by bee-rickey** [comment]
Duplicate of https://github.com/covid19india/covid19india-react/issues/1832
