### ISSUE TITLE
Hover issue with Navbar

### ISSUE THREAD

**Issue by Pranav9931** [covid19india/covid19india.github.io#1834]
Issue
When we hover over the navbar or any nav items the page loses its proper orientation.
This thing happens in desktop version of the site, the divisions on the page get styled by display: flex; or something like that and they come one after another that looks weird.

I think that this issue should be solved.
I do am trying but wants other to solve this.

**Comment by bee-rickey** [comment]
Can you add a screenshot for the same? 
Thank you!

**Comment by Pranav9931** [comment]
Before

![Coronavirus Outbreak in India - covid19india org - Google Chrome 08-05-2020 22_15_42](https://user-images.githubusercontent.com/64951792/81428449-e4910100-9179-11ea-8fe9-aba8642d820c.png)

 After

![Coronavirus Outbreak in India - covid19india org - Google Chrome 08-05-2020 22_15_36](https://user-images.githubusercontent.com/64951792/81428480-ed81d280-9179-11ea-8f6e-551c451c87ad.png)

**Comment by KapoorAyush** [comment]
let me /claim this issue

**Comment by noii98** [comment]
What is the size of your viewport?

**Comment by Pranav9931** [comment]
Its 1366*768 man

**Comment by Pranav9931** [comment]
Done Thanks..😊😊
