### ISSUE TITLE
Crowdsourced Map Tracking Important Locations

### ISSUE THREAD

**Issue by swapnilshrikhande** [covid19india/covid19india.github.io#1835]
**Problem**

- Track mobile clinics, checkpoints, help desks, food distribution points setup by local authorities and NGOs in an area
- Tracking open / closed food malls, grocery stores, vegetable stalls etc. in an area
- Track crowded places which should be avoided.

**Solution**
- Use a crowd sourced mapping platform like [Ushahidi](https://github.com/ushahidi/platform)

**Alternatives**
Please suggest alternatives

**Additional context**
Are there any existing apps / webapps supporting this already ?

**Comment by swapnilshrikhande** [comment]
Duplicate Of : #848

**Comment by bee-rickey** [comment]
> Duplicate Of : #848

Closing as it's a duplicate.
