### ISSUE TITLE
[BUG]: Crowdsourced Patient Database button redirects to API page.

### ISSUE THREAD

**Issue by Cryptonex7** [covid19india/covid19india.github.io#1838]
**Describe the bug**
Crowdsourced Patient Database button on the main website and on the API home page, both redirect to API page itself.

**To Reproduce**

1. Go to 'https://www.covid19india.org/'
2. Scroll down to 'The End of the page'
3. Click on 'CROWDSOURCED PATIENT DATABASE'
4. See error: Redirects to the API page.

**Expected behavior**
Its should transfer to the Database page where everything is placed, typically in a Spreadsheet - Google Sheets as before?

**Desktop (please complete the following information):**

- OS: Windows
- Browser: Edge, Chrome
- Version: Respective Latest Versions

**Smartphone (please complete the following information):**

- Device: Samsung Galaxy A6+
- OS: Android Pie
- Browser: Edge, Chrome
- Version: Respective Latest Versions

**Additional context**
If that button isnt functional anymore - or even temporarily not functioning, it should be removed.
While I am fully Aware of the data partition that took place, I have raised this issue from a UX perspective. 
______

![image](https://user-images.githubusercontent.com/34197902/81081093-1ce0d700-8f0f-11ea-9ac7-0401ca31ca77.png)

## This Button for "CROWDSOURCED PATIENT DATABASE" should be removed, and also the hyperlinks on https://api.covid19india.org
_____

I can take up the issue and submit a PR if Status is turned to Available.

**Comment by bee-rickey** [comment]
API is still a database in a way no? Why should it go away?

**Comment by Cryptonex7** [comment]
What I think is, when you put a button for the Database for public access, they generally look for something like a spreadsheet. 

## Problem
- A common man wont understand the API and how it works, they wont know how to look at JSON files and HTTP requests. This has happened to me when I showed the website to my parents and relatives. Some of them who dont have a technical background, yet get fascinated by technology clicked that button and got redirected to the API page and then got confused what to do. They wont understand variables like raw_data. And I am sure this might be a case for a lot of them.
- Moreoever, the word, "Patient Database" can be misinterpreted as a DB of Patients where you can find Patient data. 

I got to know about this problem a few days ago, when my grandmother got diagnosed with COVID19 and passed away eventually. I thought you guys where maintaining a patient DB so I thought to check whether an entry with her name was there or not (Which, I suppose, was initially being done.). It had been more than a month that I had opened the DB, and I noticed, it redirected me to the API. From there I went into the raw_data files (Which had been partitioned). I noticed that its not a Patient DB anymore - in fact, it just reports the cases without any data about the patient.
I also understand that it is due to the lack of data reported by Govt. APIs and other sources which this API uses. But then, with the change of situations, the visuals should also change.

## Solution
So, maybe if the name can be changed to something more appropriate, say, Opensource API or Open Data Sources or Open Data Store something on those lines, then it would make more sense than redirecting users to the API page.

## Additionally
The API page redirection could happen through a Call to action button saying, "Use Our API" or a longer CTA, say, "Create your own tracker using our API".

## Finally
I would be willing to make the appropriate changes if allowed.

**Comment by bee-rickey** [comment]
@jeremyphilemon and @shuklaayush  your views on this?

**Comment by shuklaayush** [comment]
I agree that the terminology might be confusing now. We can switch if we have a good alternative

**Comment by bee-rickey** [comment]
Assigned to @Cryptonex7 Please change it to "Crowdsourced data API". And include an appropriate icon if the current one looks odd.
