### ISSUE TITLE
Crumbled text on smaller devices

### ISSUE THREAD

**Issue by qadratic** [covid19india/covid19india.github.io#1839]
**Describe the bug**
Crumbled Level component data text on smaller devices displaying large number.

**To Reproduce**

1. Go to 'home page'
2. See error

**Expected behavior**
Clear and meaning ful text appearance.

**Screenshots**
![WhatsApp Image 2020-05-07 at 5 55 53 PM](https://user-images.githubusercontent.com/36514842/81440332-7eae7480-918d-11ea-8946-86f6646f0121.jpeg)

**Desktop (please complete the following information):**

- OS: iOS
- Browser safari

**Smartphone (please complete the following information):**

- Device: iPhone 5s
- OS: iOS 12.4
- Browser safari

**Comment by relaxedcoder** [comment]
I too have noticed this on my iPhone.
@jeremyphilemon, https://github.com/covid19india/covid19india-react/pull/1757 fixes this issue along with table content overflow.

**Comment by qadratic** [comment]
As a matter of fact, I have also solved this issue here #1825 I believe small text is preferable here over  rounding the number off.

**Comment by aseef17** [comment]
> As a matter of fact, I have also solved this issue here #1825 I believe small text is preferable here over  rounding the number off.

Rounding off might be required once the cases cross a threshold number. I suppose that can be started with 100,000 or 1 lakh.

**Comment by subodhk01** [comment]
Don't you think decreasing font size of the crumbled text would be a better fix 🤔🤔

**Comment by aseef17** [comment]
> Don't you think decreasing font size of the crumbled text would be a better fix 🤔🤔

It is a better fix but when the numbers become large, the text would need to be shrunk even further which won’t be legible anymore

**Comment by qadratic** [comment]
If numbers become very large (god forbid) then we will have to change layout on other places as well. Not just here.

**Comment by shuklaayush** [comment]
Fixed via addca3bce4dda6c0a9543ab03c805f0ef2b6469d
