### ISSUE TITLE
Switch to use Bright/Dark Theme 

### ISSUE THREAD

**Issue by manigandan-dorairaj** [covid19india/covid19india.github.io#184]
**Is your feature request related to a problem? Please describe.**
It would help to provide user option to choose either Bright or Dark theme

**Describe the solution you'd like**
A small bulb icon in the header. On click of it, the theme of the site should toggle between dark and bright. The preference of user selection should be stored in cookie so that they can see the same mode next time when they visit.

**Comment by shuklaayush** [comment]
See #116

**Comment by manigandan-dorairaj** [comment]
Super, it is done!
