### ISSUE TITLE
Wrong Delhi Test Data

### ISSUE THREAD

**Issue by bshivam2001** [covid19india/covid19india.github.io#1844]
The number of cumulative tests done in Delhi on 8th May is **81,367** according to the daily health bulletin, while the site shows **82,367**.
Seems like a common typo.

**Comment by nagu741** [comment]
Also notifications is showing new cases in delhi but not in State table
![Screenshot_20200509-192343](https://user-images.githubusercontent.com/10534116/81476103-90475900-922d-11ea-8c41-1a83170f13c8.png)

**Comment by bshivam2001** [comment]
> Also notifications is showing new cases in delhi but not in State table
> ![Screenshot_20200509-192343](https://user-images.githubusercontent.com/10534116/81476103-90475900-922d-11ea-8c41-1a83170f13c8.png)

**Comment by bshivam2001** [comment]
> Also notifications is showing new cases in delhi but not in State table
> ![Screenshot_20200509-192343](https://user-images.githubusercontent.com/10534116/81476103-90475900-922d-11ea-8c41-1a83170f13c8.png)

That happens when you view the site while they are updating the data. It takes a few minutes after they receive the date for them to upload it to the database.

**Comment by bee-rickey** [comment]
Closing the issue as it seems to be an understanding issue.
