### ISSUE TITLE
Active Case shows negative number

### ISSUE THREAD

**Issue by rkkmmmkkr** [covid19india/covid19india.github.io#1846]
**Describe the bug**
the active case shows negative number

**To Reproduce**

1. Go to covid19india.org
2. Expand Uttrakhand to shows district wise case 
3. Scroll down to Unknown district

**Expected behavior**
no of Active case is calculating by (active = confirmed - recovered ) but there should be a negative check

**Screenshots**
If applicable, add
![active](https://user-images.githubusercontent.com/20758161/81476483-cdace600-922f-11ea-9726-d1e6ab919d4a.PNG)
 screenshots to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by bshivam2001** [comment]
That is not a bug, it's a feature.

When the recovered number is higher than the today's positive count, the number of Active Cases is reduced, i.e the number of Active Cases is negative for that day.

By introducing a check to negative Active Cases, you are essentially saying that the number of Active Cases cannot be less what it was the previous day, which is not necessarily true for each day.

By contrast, the number of Confirmed Cases cannot be negative.

**Comment by gsluthra** [comment]
The point of an active column is to tell the reader -- how many active cases are there?

A -ve number is confusing. 0 is all they care about, which means, no active cases.

**Comment by shuklaayush** [comment]
Yes, it looks like an error. Active cases shouldn't be negative. Only the delta can be negative

/cc @bee-rickey

**Comment by bee-rickey** [comment]
Active unknown = Confirmed Unknown - Recovered Unknown - deceased unknown. 

When the state releases the district details of all the patients who are confirmed positive, but does not release the district details of recovered and deceased patients, in that case the number of unknown active cases becomes -ve. This is neither a bug, nor a feature. This is essentially the dashboard telling you that the state needs to release data more transparently :)

**Comment by shuklaayush** [comment]
I guess that clears things up
