### ISSUE TITLE
filtering and showing new cases in orange/green zones

### ISSUE THREAD

**Issue by naveennamani** [covid19india/covid19india.github.io#1847]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Is it possible to add a filter such that the table only shows orange/green zones from each state where there are new cases.
If filtering of the table is not possible, add a chart in the deep dive page where the trend shows the number of orange/green zones where there are new cases.

**Describe alternatives you've considered**

**Additional context**
This feature can be useful to identify the severity of the spread of covid by tracking how the number of red zones, orange and green zones are changing.

Thank you.

**Comment by shuklaayush** [comment]
Not relevant since zones have been deprecated
