### ISSUE TITLE
Homepage not loading

### ISSUE THREAD

**Issue by abhishekkhandait** [covid19india/covid19india.github.io#1854]
**Describe the bug**
Homepage details not visible

**To Reproduce**
Open . Homepage shows up with just stats. Map, chart, footer everything is not visible.

1. Go to  https://www.covid19india.org/
2. Click on Home
3. Scroll down

**Expected behavior**
Homepage should be visible as expected

**Screenshots**
![Screenshot_20200510-190837](https://user-images.githubusercontent.com/25871546/81500730-acacc980-92f1-11ea-9722-3a6bdb5409f6.jpg)

**Desktop (please complete the following information):**
NA

**Smartphone (please complete the following information):**

- Device: OnePlus 7 pro
- OS: OxygenOS @latest
- Browser: chrome
- Version: @latest

**Additional context**

**Comment by abhishekkhandait** [comment]
![steps to reproduce](https://thumbs.gfycat.com/SpecificWarlikeAmericanratsnake-size_restricted.gif)

**Comment by rahulbhanushali** [comment]
I have found the issue, it's due malformed data entry in the https://api.covid19india.org/state_test_data.json.

We both created the same issue around the same time. We can link one of these and mark one as duplicate. https://github.com/covid19india/covid19india-react/issues/1855. I have added the details of the record causing the problem in the mentioned link.

**Comment by abdulnasar85** [comment]
https://github.com/covid19india/covid19india-react/pull/1858/ This PR has an additional check to instantiate this as an array. Its always a best practice to assign an empty array  using || [] when the data is null or undefined.

**Comment by shuklaayush** [comment]
Fixed via 8e2bc774f1111d3fcad71407f7f376be41aeb05c
