### ISSUE TITLE
Home page not showing state & district wise table

### ISSUE THREAD

**Issue by rahulbhanushali** [covid19india/covid19india.github.io#1855]
**Describe the bug**
The state and district wise table showing the numbers is no longer rendering on the home page.
Possibly due to a change in keys of API response.

**To Reproduce**

1. Go to the home
2. See missing table

**Expected behavior**
The table should be visible.

**Screenshots**

**Smartphone (please complete the following information):**

- Device: iPhone XS
- OS: iOS 13.4
- Browser: Safari

**Additional context**
I could see errors on the desktop browser console. Stacktrace below:

```
TypeError: Cannot read property 'length' of undefined
    at commonfunctions.js:171
    at Array.forEach (<anonymous>)
    at T (commonfunctions.js:164)
    at home.js:127
    at s (runtime.js:45)
    at Generator._invoke (runtime.js:274)
    at Generator.forEach.t.<computed> [as next] (runtime.js:97)
    at r (asyncToGenerator.js:3)
    at u (asyncToGenerator.js:25)
```

**Comment by rahulbhanushali** [comment]
This is happening due to a malformed entry which has the state value set to a space value in the https://api.covid19india.org/state_test_data.json API.

Malformed record here:

```
{"negative":"","numcallsstatehelpline":"","numicubeds":"","numisolationbeds":"","numventilators":"","populationsourcecovid19india":"","positive":"7","source":"https://twitter.com/dip_goa/status/1248237654258352129?s=09","source2":"","state":" ","tags":"Samples Sent","testpositivityrate":"2.03%","testspermillion":"223","testsperthousand":"0.22","totalpeopleinquarantine":"","totalpeoplereleasedfromquarantine":"","totaltested":"344","unconfirmed":"","updatedon":"09/04/2020"}
```

**Comment by m-garg** [comment]
The site seems to be loading now.

**Comment by shuklaayush** [comment]
Seems to be fixed
