### ISSUE TITLE
Home page is not getting loaded fully as there is an error is some variable usage please check on that

### ISSUE THREAD

**Issue by nambi-rajan-k** [covid19india/covid19india.github.io#1857]
![Screenshot from 2020-05-10 19-30-59](https://user-images.githubusercontent.com/58591984/81501247-006ce200-92f5-11ea-8ecb-49c7727cb2f5.png)

**Comment by rahulbhanushali** [comment]
Hi, there's already an open issue for this: https://github.com/covid19india/covid19india-react/issues/1855
