### ISSUE TITLE
Showing negative data for active cases

### ISSUE THREAD

**Issue by parthbhide** [covid19india/covid19india.github.io#1859]
**Describe the bug**
In **'unknown'** row for MAHARASHTRA state, number of active cases shown are negative.

**To Reproduce**

1. Go to covid 19 home page
2. In states table click on MAHARASHTRA
3. Scroll down to last row for the state

**Expected behavior**
If all cases recovered active cases should be zero. 
It may be affecting total tally for the state.

**Screenshots**

![Screenshot_2020-05-10-23-20-42-235_com android chrome](https://user-images.githubusercontent.com/50196988/81506724-0d4dfd80-9316-11ea-86e4-7f974d5647a1.jpg)

**Comment by bee-rickey** [comment]
This is when the total confirmed cases are mapped to districts but the recovery data is not mapped to districts. Happens with Maharashtra since they do not update the recovered details immediately. 

Active unknown = Confirmed unknown - Recovery unknown - deceased unknown.
