### ISSUE TITLE
Image button not working

### ISSUE THREAD

**Issue by iamsh4shank** [covid19india/covid19india.github.io#186]
**Describe the bug**
The image button present on top left corner in the website is not working.

**To Reproduce**
open the website

**Expected behavior**
I should open the global tracker or the news related to covid-19

**Screenshots**
![Screenshot from 2020-03-26 19-42-36](https://user-images.githubusercontent.com/52889867/77656842-78c45180-6f9a-11ea-92d4-e175428fe534.png)

**Desktop (please complete the following information):**
 - ubuntu
 - firefox
 - 72.0.1

**Smartphone (please complete the following information):**
 - Realme 5
 - Android 9.0
 - chrome

**Comment by Rajanpandey** [comment]
I will do it.
Where do we want it to redirect though? who.int?

**Comment by siddharthhp** [comment]
@Rajanpandey Usually such click triggers are usually pointed to the homepage of the application. I know we have a 'home' tab right next to it but still it should be pointing to the homepage i believe.

**Comment by Rajanpandey** [comment]
@siddharthhp Agreed.

**Comment by iamsh4shank** [comment]
Should I fix this?

**Comment by Rajanpandey** [comment]
@robustTechie Ok go ahead

**Comment by iamsh4shank** [comment]
@Rajanpandey it may open a global tracker. Which page should it direct?

**Comment by siddharthhp** [comment]
@robustTechie I believe this is the link it should redirect to !
https://www.worldometers.info/coronavirus/

**Comment by iamsh4shank** [comment]
Should I link this to the button?

**Comment by vairavlaksh** [comment]
I already created a Pull Request on this. https://github.com/covid19india/covid19india-react/pull/108.
