### ISSUE TITLE
Addition of Doubling rate of cases

### ISSUE THREAD

**Issue by mohammedsrehan** [covid19india/covid19india.github.io#1861]
**Describe the solution you'd like**

A new feature can be added which describes the doubling rate of the coronavirus cases in India can be displayed and state wise doubling rate can be displayed in the state page. By adding this feature the covid19.org website will be more informative in terms of statistics.

**Comment by sourabhbagrecha** [comment]
Any chance if we can get the doubling rate displayed on the home? @shuklaayush
