### ISSUE TITLE
Incorrect values

### ISSUE THREAD

**Issue by ketanyadav10** [covid19india/covid19india.github.io#1867]
**Describe the bug**
Washim district of maharashtra shows 1 confirmed - 2 active  and 3 recovered 
**Smartphone (please complete the following information):**

- Device: oneplus5t
- OS: android 9
- Browser chrome

**Additional context**

**Comment by bee-rickey** [comment]
MH state dashboards are having some very weird numbers. We aren't really sure what to do with this data. This is on 11th May:
<img width="223" alt="Screenshot 2020-05-12 at 12 08 23 AM" src="https://user-images.githubusercontent.com/63364562/81598328-bd8a3780-93e4-11ea-8b14-97aa36b520af.png">
