### ISSUE TITLE
Empty list in the state dropdown

### ISSUE THREAD

**Issue by OptimusKrish** [covid19india/covid19india.github.io#1870]
**Describe the bug**
There is an empty `<li>` placed inside `<ul>` in the state page drop-down selection

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to https://www.covid19india.org/state/MH
2. Click on (Eg: Maharashtra)state dropdown
3. Scroll down to the state list
4. See error empty list in the select dropdown without any state name

**Expected behaviour**
Need the proper state name or the empty `<li>` list must be removed from the drop-down

**Screenshots**
<img width="320" alt="Screenshot 2020-05-12 at 12 01 35 AM" src="https://user-images.githubusercontent.com/7058950/81598264-a3e8f000-93e4-11ea-9cb1-455a4b8d0e77.png">
<img width="709" alt="Screenshot 2020-05-12 at 12 01 45 AM" src="https://user-images.githubusercontent.com/7058950/81598274-a6e3e080-93e4-11ea-8eca-07c18cec25b8.png">

**Desktop (please complete the following information):**

- OS: macOS Catalina
- Browser Chrome
- Version 81.0

**Comment by skippersumit** [comment]
Can I try ?

**Comment by mayankkt9** [comment]
Can I work on this ?

**Comment by shuklaayush** [comment]
This was because of a stray entry in the API. It's fixed now
