### ISSUE TITLE
Hyderabad city which is part of telangana state having active patients is larger than Telangana state total

### ISSUE THREAD

**Issue by SanjayChandak95** [covid19india/covid19india.github.io#1873]
![496D1241-76BB-4F71-868F-83409D86C694](https://user-images.githubusercontent.com/32013144/81711274-1d3e1c80-9491-11ea-8e7e-3b3a979452b5.png)

You can see the overall active patients in Hyderabad is 451 but overall telangana state have 444 active patients. Seems like a bug.

**Comment by bee-rickey** [comment]
Issue is with Telangana state not releasing district wise recovery data. This results in some districts having a higher count of active cases since their active cases haven’t been adjusted with the recovery numbers. Nothing much we can do about this.
