### ISSUE TITLE
STATE_CODE for Telangana should be TS instead of TG

### ISSUE THREAD

**Issue by sivasatvik** [covid19india/covid19india.github.io#1877]
**Describe the bug**
As the heading suggests, the abbreviation for Telangana is widely known as TS instead of TG. (TS signifying Telangana State). The redirects for state details has "/state/TG". It should be "state/TS" instead.

Thoughts?

**Comment by mayankkt9** [comment]
Can I work on this ?

**Comment by bee-rickey** [comment]
@sudevschiz Your call. I don't see how we can fix this on the API side. Loads of changes.

**Comment by shuklaayush** [comment]
I think it's too late for this now
