### ISSUE TITLE
Google search not finding https://www.covid19india.org/ in search list

### ISSUE THREAD

**Issue by shishupal082** [covid19india/covid19india.github.io#1878]
**Is your feature request related to a problem? Please describe.**

When we search **covid 19 india** on google, search result does not show https://www.covid19india.org/ in search items. When i tell someone about this website and i have to send him exact link of this website.

**Describe the solution you'd like**
- I think some short of meta tags are required for google to make it available in search.

**Describe alternatives you've considered**
- No idea

**Additional context**
- It will help others to see Covid-19 real time status

**Comment by vineetrathor** [comment]
let me \claim  in this @shishupal082

**Comment by arhamshah** [comment]
\claim

**Comment by Wise2006** [comment]
claim ?

**Comment by shishupal082** [comment]
> \claim

Kewords are not visible in the page source (On right click on page --> Voew page source) [view-source:https://www.covid19india.org/](view-source:https://www.covid19india.org/)

And also when we search on google **covid19** or **coronavirus**, this page [https://www.covid19india.org/](https://www.covid19india.org/) is not visible in search result.
