### ISSUE TITLE
mumbai suburban none

### ISSUE THREAD

**Issue by kunvarsinghbisht** [covid19india/covid19india.github.io#1880]
In that Mumbai suburban count is 0 so it's green zone.
but it's Red area and in that dahisar location 10 people  cronna positive

**Comment by sgandhi9** [comment]
I think it's a duplicate issue which already exists. Please follow the following link: https://github.com/covid19india/covid19india-react/issues/1287
Also, this is is been long pending, needs to be addressed.

**Comment by bee-rickey** [comment]
Not exactly a duplicate. But This cannot be handled as the state bulletin does not give the breakup of Suburban. And the categorization of the zones is based on MOHFW list.
