### ISSUE TITLE
Charts not aligned properly in mobile breakpoint

### ISSUE THREAD

**Issue by abhisheknaiidu** [covid19india/covid19india.github.io#1881]
**Describe the bug**
Charts are not aligned properly

**To Reproduce**

![Screenshot_20200514-004745](https://user-images.githubusercontent.com/55599878/81855277-c6157600-957c-11ea-9e46-a4c17cf7518d.jpg)

**Expected behavior**
 `margin-left` needs to be given in charts div.

**Smartphone (please complete the following information):**

- Device: OnePlus 
- OS: Oxygen OS
- Browser: Chrome

**Additional context**
I can work on this :)

**Comment by nayakrahul** [comment]
Issue #1807 and PR #1823 are already for this.

**Comment by shuklaayush** [comment]
Fixed via 7740f5c8f764b7a521fdfae695b622f160d2e734
