### ISSUE TITLE
Scalar field negative for Maharashtra

### ISSUE THREAD

**Issue by championballer** [covid19india/covid19india.github.io#1882]
**Describe the bug**
The confirmed cases for unknown = 0, and recovered is being shown as 2, which puts active to -2. This seems to be an updation error and should be accounted for.

**To Reproduce**
Go to the main page of the website, expand to the Maharashtra row, and scroll to the bottom of the cases information for the state. 

**Expected behavior**
The sum of all involved fields should be consistent, keeping all fields non-negative.

**Screenshots**
![Screenshot 2020-05-14 at 12 50 23 AM](https://user-images.githubusercontent.com/39242078/81855785-6cfa1200-957d-11ea-90a5-ec9704bfbd0a.png)

**Desktop (please complete the following information):**

- OS: MacOS
- Browser : Chrome

**Comment by shuklaayush** [comment]
Refer to [this comment](https://github.com/covid19india/covid19india-react/issues/1846#issuecomment-626884611)
