### ISSUE TITLE
Incorrect data in testing json

### ISSUE THREAD

**Issue by isonso** [covid19india/covid19india.github.io#1884]
**Describe the bug**
Data incorrect here. Updatedon should be 04/04/2020.
https://api.covid19india.org/state_test_data.json
{
			"negative": "8586",
			"numcallsstatehelpline": "",
			"numicubeds": "",
			"numisolationbeds": "",
			"numventilators": "",
			"populationsourcecovid19india": "",
			"positive": "306",
			"source": "https://dashboard.kerala.gov.in/testing-view-public.php",
			"source2": "https://dashboard.kerala.gov.in/quarantine-view-public.php",
			"state": "Kerala",
			"tags": "Samples Sent",
			"testpositivityrate": "3.14%",
			"testspermillion": "277",
			"testsperthousand": "0.28",
			"totalpeopleinquarantine": "734",
			"totalpeoplereleasedfromquarantine": "",
			"totaltested": "9744",
			"unconfirmed": "852",
			**"updatedon": "04/02/2020"**  --> Should be 04/04/2020
		}

**To Reproduce**

NA
**Expected behavior**
Since its a running total, before and after data shows this date should be 04/04 and not 04/02.

**Screenshots**
NA

**Desktop (please complete the following information):**

NA

**Smartphone (please complete the following information):**

NA

**Additional context**

**Comment by KapoorAyush** [comment]
let me /claim this issue

**Comment by bee-rickey** [comment]
Issue is fixed. Thanks for bringing this to our notice.
