### ISSUE TITLE
Ceiling should be taken instead of round off.

### ISSUE THREAD

**Issue by nayakrahul** [covid19india/covid19india.github.io#1885]
**Describe the bug**
In state page, when we tell "x persons have passed away or recovered", we should consider ceiling not round off because if mortality rate is 1.4%, it means 2 persons have passed away not 1, we should consider 0.4% as 1 too. It makes sense when mortality rate is say 0.4% because according to current method, it will say "0 have passed away" which is obviously misleading. We are taking people into account. so a fraction should be considered ONE person regardless of whether it is less than 0.5 or more than. 

**To Reproduce**

1. Go to state page of Odisha
2. Scroll down to state metacards
3. See in mortality rate card that mortality rate is 0.49% but it is written "0 has passed away for 100 people" which is misleading.

**Expected behavior**
Ceiling should be taken not round off.

**Screenshots**
![98000612_3002614863150405_3014041373536944128_n](https://user-images.githubusercontent.com/11428805/81925709-7d9e9c80-95fe-11ea-8d83-8fb8a3a33126.jpg)

**Comment by KapoorAyush** [comment]
let me /claim this issue
