### ISSUE TITLE
Time period filter on the Demographics Tab

### ISSUE THREAD

**Issue by amogh-kalalbandi** [covid19india/covid19india.github.io#1886]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

There needs to be a time period filter on the Demographics tab. Currently it has a filter on a single day by selecting a date. Add a feature of time period filter which has start_date and end_date. This helps understand the increase/decrease in the positive cases as per our city.

**Describe alternatives you've considered**

**Additional context**

**Comment by vigneshkc06** [comment]
Can you confirm this is still an issue?.

**Comment by amogh-kalalbandi** [comment]
This is more like a feature and not an issue. If there is a time period
filter on the tab, It gives us the number of cases per city which is not
present in the site.

Thanks & regards,
Amogh Kulkarni

**Comment by shuklaayush** [comment]
Obsolete now since demographics has been deprecated
