### ISSUE TITLE
News Feed Features

### ISSUE THREAD

**Issue by Prankurtiwari** [covid19india/covid19india.github.io#1887]
**Is your feature request related to a problem? Please describe.**
Simple news feeds feature to display top feeds on the side of the page.
 
**Describe the solution you'd like**
A div on the page to show the latest news like the top 10 news feed.

**Comment by ludwig2000** [comment]
assign me this issue , I will like to work on it

**Comment by bee-rickey** [comment]
Hi we have purposefully kept this out since curating the feed would be an effort. And the decisions on what news handles should be used and which shouldn’t are extremely opinionated.
