### ISSUE TITLE
Bug in Gujarat district wise data view.

### ISSUE THREAD

**Issue by tejashbutani** [covid19india/covid19india.github.io#1894]
AMRELI district is showing in other state  in Gujarat state. AMRELI is one of the district of Gujarat and i suggest you to include in list of district

**To Reproduce**
Steps to reproduce the same.

1. Click on 'Gujarat state name'
3. Scroll down to last district mentioned
4. You will see that amreli is under heading of other state

**Expected behavior**.
Consider amreli inside the list of district in Gujarat.

**Comment by bee-rickey** [comment]
This is an understanding issue. "Other state" is a category where Gujarat has put number of patients belonging to other states. This is not some other state to which Amreli belongs.

**Comment by tejashbutani** [comment]
Okay got your point.
