### ISSUE TITLE
District label shown as Unknown and active count shown in negative (-1)

### ISSUE THREAD

**Issue by ijesuraja** [covid19india/covid19india.github.io#1895]
District label shown as Unknown and active count shown in negative (-1). Below is the screen shot of data and it was taken from Tamil Nadu state. 

![IMG_20200515_214242](https://user-images.githubusercontent.com/65412962/82073850-7b6c3900-96f7-11ea-8783-abf2e52f785b.png)

**Comment by bee-rickey** [comment]
This is not an issue. The reason why the unknown is negative is because the district for the deceased is not provided by the state at that point in time. So unknown active = unknown confirmed (0) - unknown deceased (1). Hence -1.

**Comment by ijesuraja** [comment]
> This is not an issue. The reason why the unknown is negative is because the district for the deceased is not provided by the state at that point in time. So unknown active = unknown confirmed (0) - unknown deceased (1). Hence -1.

**Its fine. But it will be good to show as 0 or NA instead of showing in negative...**
