### ISSUE TITLE
Social - Twitter, fb, insta button + scrolling banner

### ISSUE THREAD

**Issue by Reddevilsab** [covid19india/covid19india.github.io#19]
We(Social team) need a scrolling banner on the top of the page which will contain factoids and Mythbusters. All content will be supplied by us. Please make that functionality and we shall give you the content. Much needed as so much fake news circulates in the media nowadays and we want to get out the facts to our 150,000+ Daily viewers.
Second - we need our social media pages to be pinned onto the website so as to divert traffic from the website to SM pages as well. Mainly have an icon for twitter below the 'Last case seen on'. And insta and fb buttons in the right top corner. 
Please complete both of these on priority. 
Thanks.

**Comment by dakshshah96** [comment]
Duplicate of #8

**Comment by Reddevilsab** [comment]
Does it have a mention of scrolling banner on the top of the page with
factoids?

**Comment by jeremyphilemon** [comment]
@JunaidBabu @sudevschiz Thoughts on the banner?

**Comment by sudevschiz** [comment]
@jeremyphilemon Closed the issue for Social Media icons. We will add them later.
But the scrolling banner with Factoids is necessary now I think. Social team has already created this.

Reusing this issue for that work. 

@JunaidBabu , created an issue for that in API https://github.com/covid19india/api/issues/4

**Comment by zeffirara** [comment]
Scrolling banners are hard to read. A carousel style banner with text that keeps changing after a fixed interval would be better I think.

**Comment by jeremyphilemon** [comment]
@kapiljain-128 your wish has been fulfilled! 😌
