### ISSUE TITLE
Add more informational regarding Transmission rate, mortality rate, age and sex ratio, symptoms, incubation, how to protect yourself, myth busters, virus life on different surfaces

### ISSUE THREAD

**Issue by Rajanpandey** [covid19india/covid19india.github.io#190]
Refer to the following websites.
1. https://www.cov19.xyz/info/mortality-rate
2. https://worldcoronavirus.org/symptoms

We can use the same information and put it on this website.

**Comment by sudevschiz** [comment]
All this could probably go into a "Deep-Dive" tab. Could be a nice separate project on its own.

PR welcome.

**Comment by shuklaayush** [comment]
Relevant: #141

**Comment by sagarv1997** [comment]
Just read the contributing guidelines @sudevschiz Please assign the Myth Buster section to me

**Comment by jeremyphilemon** [comment]
Added by #539, #325 addresses myth busters
