### ISSUE TITLE
Total Cases reported are wrong

### ISSUE THREAD

**Issue by ysingla** [covid19india/covid19india.github.io#1909]
**Describe the bug**
Total cases reported, recoveries etc are wrong. MOH says number of cases till 16 May is 90,927 but on your website it's 90,649.

**To Reproduce**
Steps to reproduce the behavior: Check website of MOH and compare with COVID19India.

**Comment by shuklaayush** [comment]
Please read https://github.com/covid19india/covid19india-react/issues/662#issuecomment-612361044
