### ISSUE TITLE
Readme invalid link

### ISSUE THREAD

**Issue by krishnasen2401** [covid19india/covid19india.github.io#191]
the link provided for live data link for google is not  view only link or shareable. pleas update it if possible

**Comment by r2dragon** [comment]
that should be read-only to the public tho right? 
There is a form where users can submit cases -->  https://forms.gle/7NRSrbspW2a6pbm58

**Comment by krishnasen2401** [comment]
I asking for the dataset read access so it can be used other dashboard developments not using programming like react js . I am asking read access(view only not edit) for using in powerbi and tableau dashboard and i havent found any reliable datasource anywhere else

**Comment by krishnasen2401** [comment]
moreover it was given as public dataset to used to anything else at https://www.mohfw.gov.in/ in resources section

**Comment by krishnasen2401** [comment]
It was written as dataset source at

**Comment by krishnasen2401** [comment]
It's was written as dataset source at https://innovate.mygov.in/covid19/
That why's I was asking for read access

**Comment by JunaidBabu** [comment]
Not a bug
