### ISSUE TITLE
ALL-STATE as a button not in drop-down

### ISSUE THREAD

**Issue by tshrwbl** [covid19india/covid19india.github.io#1913]
**Is your feature request related to a problem? Please describe.**
Users always need to reset ALL-STATE through the drop-down menu although it's most sought after graph view. The site has become much dynamic with hover feature all over. The only safe mouse path is the green one. Make a mistake and you have to reset it.
![image](https://user-images.githubusercontent.com/27141947/82142325-247e7500-9859-11ea-9ef9-dfb746a51583.png)

**Describe the solution you'd like**
ALL-STATE button near the drop-down menu. It will make the site more user friendly.

**Comment by nayakrahul** [comment]
You can click in empty space in map(where there is no states) or total row in the table to reset it.

**Comment by tshrwbl** [comment]
I can't reproduce what you said @nayakrahul

**Comment by aman4512** [comment]
> 
> 
> You can click in empty space in map(where there is no states) or total row in the table to reset it.

Double click in map's empty area works for me

**Comment by tshrwbl** [comment]
Damn 😒

**Comment by shuklaayush** [comment]
I guess the new icon fixes this
![image](https://user-images.githubusercontent.com/27727946/86740382-3bb93200-c054-11ea-879d-6087b0897077.png)
