### ISSUE TITLE
Add recovery rate & mortality rate to the dashboard

### ISSUE THREAD

**Issue by djkher** [covid19india/covid19india.github.io#1919]
**Problem:**
Currently the dashboard displays the numbers (active, confirmed etc) but it doesn't show various rates such as recovery rate, mortality rate etc. These figures could be quite useful. 

**Solution:**
Add recovery and mortality rate to the dashboard. These can be calculated using simple division.

Recovery Rate = Total Recovered / Total Confirmed * 100
Mortality Rate = Total Deaths / Total Confirmed * 100

This could be at country level as well as state level.

Additionally we could also show these rates on a per day basis to understand the trend over a period of time. Although this might not be as useful as the overall recovery rate, it is worth considering

**Comment by deepshikha02** [comment]
Is this available to pick up?

**Comment by djkher** [comment]
> Is this available to pick up?

Yes available

**Comment by navkumar258** [comment]
Is it completed or is someone working on it....i am looking for my first contribution. thanks !

**Comment by deepshikha02** [comment]
The status was still on Review needed, so I left it. You can pick it up if you like. @navkumar258

**Comment by navkumar258** [comment]
Duplicate of #1984 
![image](https://user-images.githubusercontent.com/7344604/85947033-fa46c980-b965-11ea-9cec-41c5dbaf6b05.png)

Hi team, tried to take it up, got it compiled and running as expected on my machine. thanks 😄
