### ISSUE TITLE
Website not loading on Browsers

### ISSUE THREAD

**Issue by prabodhmeshram** [covid19india/covid19india.github.io#1923]
**Describe the bug**
The site is down

**To Reproduce**

1. Go to 'https://www.covid19india.org.'
2. See blank page
3. Console error

**Expected behavior**
Should load the website

**Screenshots**
<img width="1384" alt="image" src="https://user-images.githubusercontent.com/6660187/82284032-a1befc80-99b5-11ea-8a87-96b2dcfe0844.png">

**Desktop (please complete the following information):**

- OS: MacOS
- Browser : Both Chrome and Safari
- Version: Chrome : 81.0.4044.138, Safari : Version 13.1 

**Smartphone (please complete the following information):**

Working on mobile

**Comment by shuklaayush** [comment]
Seems to be fixed
