### ISSUE TITLE
Space between confirmed and active case

### ISSUE THREAD

**Issue by harsshjain** [covid19india/covid19india.github.io#1924]
To change little formatting between the confirmed and active case.

![Screenshot_2020-05-19-11-06-14-567_com android chrome](https://user-images.githubusercontent.com/65491327/82288929-38dd8180-99c1-11ea-95a0-c84d5337b4db.png)

**Comment by ChaituVR** [comment]
+1 same for me in smaller devices

**Comment by anukaal** [comment]
Yes , I think so some spaces should be there in between the confirmed and the active cases

**Comment by gurudeb** [comment]
Let me /claim this issue

**Comment by harsshjain** [comment]
Issue solved!

![IMG_20200520_111832](https://user-images.githubusercontent.com/65491327/82409682-e7e68f80-9a8b-11ea-9eca-386ae4993aab.jpg)
