### ISSUE TITLE
Title not highlighted

### ISSUE THREAD

**Issue by iamsh4shank** [covid19india/covid19india.github.io#193]
**Describe the bug**
If home, FAQ or helpful links are selected then they are highlighted but if the cluster is selected then that is not highlighted.

**To Reproduce**
Click on clusters

**Expected behavior**
It should also get highlighted as home, FAQ or helpful links

**Screenshots**
![Screenshot from 2020-03-26 20-50-10](https://user-images.githubusercontent.com/52889867/77664156-f04aae80-6fa3-11ea-823f-5a58c8f38de7.png)

![Screenshot from 2020-03-26 20-50-18](https://user-images.githubusercontent.com/52889867/77664161-f17bdb80-6fa3-11ea-9f8c-a0f774b9d089.png)

**Desktop (please complete the following information):**
 - OS: ubuntu
 -firefox
 - 72.0.1

**Comment by iamsh4shank** [comment]
I would like to work on this.

**Comment by iamrishav** [comment]
> I would like to work on this.



> **Describe the bug**
> If home, FAQ or helpful links are selected then they are highlighted but if the cluster is selected then that is not highlighted.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> Click on clusters
> 
> **Expected behavior**
> It should also get highlighted as home, FAQ or helpful links
> 
> **Screenshots**
> ![Screenshot from 2020-03-26 20-50-10](https://user-images.githubusercontent.com/52889867/77664156-f04aae80-6fa3-11ea-823f-5a58c8f38de7.png)
> 
> ![Screenshot from 2020-03-26 20-50-18](https://user-images.githubusercontent.com/52889867/77664161-f17bdb80-6fa3-11ea-9f8c-a0f774b9d089.png)
> 
> **Desktop (please complete the following information):**
> 
>     * OS: ubuntu
>       -firefox
> 
>     * 72.0.1

Duplicate of #91
