### ISSUE TITLE
Bihar state recovery increment numbers not shown in state row

### ISSUE THREAD

**Issue by anantakrroy** [covid19india/covid19india.github.io#1930]
**Describe the bug**
The recovery increment numbers using the green arrow and corresponding number is not being shown for Bihar state since atleast the past 4 instances even though the updates stated the same.

**To Reproduce**

1. Go to 'https://www.covid19india.org/'
2. Scroll down to 'Bihar' and check **Recovered** column
3. See error

**Expected behavior**
The updates mention recovery and the column should reflect the same using the green arrow and number of recoveries.

**Screenshots**
![issue](https://user-images.githubusercontent.com/20229180/82308819-efe8f580-99df-11ea-8896-a31e2a1e89e8.png)

**Desktop (please complete the following information):**

- OS: Windows10 Home
- Browser: Chrome
- Version: v81.0.4044

**Comment by vineetrathor** [comment]
I don't think that green arrow is shown for any state, the only red arrow is shown when a new case comes.

**Comment by anantakrroy** [comment]
> I don't think that green arrow is shown for any state, the only red arrow is shown when a new case comes.

Please refer to state of Odisha in attached image. Green arrows are a part of the row

**Comment by vineetrathor** [comment]
yes that's true, I will try to solve it

**Comment by anantakrroy** [comment]
Any updates on this? **To add:** The recovery number increments are shown very rarely and I do not understand why this is so for certain days but are not shown rest of the days.Aren't the update figures mapped to the row data? Currently, this does not seem to be true.

**Comment by shuklaayush** [comment]
All these are coming from the API. There's no way to handle it in this codebase. The reason the numbers might not be showing up beside the arrow might have been because the numbers were for yesterday
