### ISSUE TITLE
State daily report missing

### ISSUE THREAD

**Issue by sarangrakhecha** [covid19india/covid19india.github.io#1936]
**Describe the bug**
Per day information for some states is missing. This feature for some reason keeps on changing. 
It shows up for some states, but for most of them its missing. Maharashtra is always missing, where the cases are the highest.

**Screenshots**
<img width="538" alt="Screen Shot 2020-05-19 at 8 38 24 AM" src="https://user-images.githubusercontent.com/20394342/82327329-39b7e880-99ac-11ea-8b48-a98538af8bd8.png">

**Laptop:**
MacOS Catalina 10.15.3
Safari 13.0.5

**Comment by phoenicopteri** [comment]
The daily cases are updated here after state governments provide an update with the daily bulletin. For Maharashtra it is usually at night around 8-9 pm local time daily. 
At the end of the day , the numbers for all states that provided an update on that day can be seen

**Comment by bee-rickey** [comment]
Understanding issue. The behavior is already explained by @phoenicopteri. Closing this. If there's a difference in our understanding, please tag me in a comment.
