### ISSUE TITLE
Text overlapping in statistics area

### ISSUE THREAD

**Issue by Divastra** [covid19india/covid19india.github.io#1938]
**Describe the bug**
The number of confirmed cases and active cases of whole india are overlapping because after crossing 1 lakh confirmed cases, I there is no gap between the two columns.

**To Reproduce**

1. Go to 'Main page'
2. Scroll down to 'Statistics of whole India'
3. See error

**Expected behavior**
A small space between the numbers of 2 columns was expected as it was earlier but not now. 

**Smartphone (please complete the following information):**

- Device: [e.g. Vivo S1]
- OS: [e.g. Android 9]
- Browser [e.g. Google Chrome]
- Version [e.g. 81.0]

**Additional context**

**Comment by iamrishav** [comment]
Duplicate #1924
