### ISSUE TITLE
Clicking on banner can trigger next text to display.

### ISSUE THREAD

**Issue by s-naveen** [covid19india/covid19india.github.io#194]

**Comment by iamrishav** [comment]
unable to understand!! please provide description.

**Comment by s-naveen** [comment]
@iamrishav I mean this banner https://prnt.sc/rnan4s. Clicking on it can show next text.

**Comment by iamrishav** [comment]
ok

**Comment by iamrishav** [comment]
@jeremyphilemon @s-naveen  label this issue as #enhancement

**Comment by parthpatel1470** [comment]
hey, I can do this.
