### ISSUE TITLE
Problem with the display attribute

### ISSUE THREAD

**Issue by humble-barnacle001** [covid19india/covid19india.github.io#1943]
**Description*
The problem with the display attribute of the sidebar (I guess) on 1366*768 resolution monitor. Basically, on hovering over the sidebar, the map and the list of states is displayed side by side and moving away from it displays them both on top of each other.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to homepage
2. Hover over the side navigation bar
3. See the Error

**Expected behaviour**
The state-wise list and map should not be displayed side by side on hovering over the sidebar. I guess this is happening because you have disabled scroll-bar on hover over the sidebar but 

**Screenshots**
I have added screen capture file in .gif format.
![Capture-03](https://user-images.githubusercontent.com/58736240/82409296-08fab080-9a8b-11ea-8799-255e7f05bb8f.gif)

**Desktop (please complete the following information):**

- Windows 10 v1909
- Chrome
- 81.0.4044.138

**Additional context**
I suggest checking if the width of the state-wise list (class="home-left") is set to 50vw on desktop and suggest to set it to 50% and similarly for the map (class="home-right").

**Comment by harishmathur** [comment]
Please assign this to me

**Comment by humble-barnacle001** [comment]
> Please assign this to me
Comment with '/claim'

Ref: https://github.com/covid19india/covid19india-react/issues/662

**Comment by humble-barnacle001** [comment]
I think the issue has been resolved so closing the issue. Please let me know if otherwise.
