### ISSUE TITLE
Tap on Maharashtra on India map redirects to karnataka

### ISSUE THREAD

**Issue by mohammedsrehan** [covid19india/covid19india.github.io#1944]
**Describe the bug**
Tapping on the Maharashtra on the India map redirects to the Benguluru urban in Karnataka

**To Reproduce**

1. Go to 'India map section'
2. Click on Maharashtra
3. See error

**Expected behavior**
Maharashtra state page was expected to be displayed.
But it is directing to the Bengaluru urban district in Karnataka

**Screenshots**
![Chrome](https://user-images.githubusercontent.com/65021509/82434268-402f8880-9ab0-11ea-8584-525527810d05.gif)

**Smartphone (please complete the following information):**

- Device: [Redmi Note 5 pro]
- OS: [Android 9.0]
- Browser [Google Chrome]

**Comment by mohammedsrehan** [comment]
I have noticed that this unexpected behaviour happens with all the states. Tapping on a state redirects to another state's district.

Also this doesn't happen on all occasions. It happens few times but it is very annoying. So it has to be fixed.

**Comment by bee-rickey** [comment]
@jeremyphilemon @shuklaayush Have you noticed this any time? Some state resolution issue or caching issue perhaps?

**Comment by shuklaayush** [comment]
Naa, I think it's because of the flexbox. Somehow touch events aren't propagated properly when the layout changes due to differences in state numbers. We should be able to fix it by adjusting the width of the boxes.

![Peek 2020-05-20 20-19](https://user-images.githubusercontent.com/27727946/82460797-408f4a00-9ad7-11ea-8810-23a3811c3950.gif)

**Comment by mohammedsrehan** [comment]
This is happening when we switch from the India map with confirmed cases of length 6 digits to state map with cases < 6 in length. The width of the confirmed cases increases when the confirmed cases length exceeds 6 digits. There by moving the alignment of the map every time this change in cases happen.

To solve this issue the width of the confirmed cases can be increased to accomodate digits of length 6 or higher. 
This will also push the no of tested tab downwards permanently and hopefully the issue can be solved.

**Comment by mohammedsrehan** [comment]
i want to /claim this
