### ISSUE TITLE
Bug: Need to click two times on the menu button to close it on mobile version

### ISSUE THREAD

**Issue by gopaljigaur** [covid19india/covid19india.github.io#1946]
**Describe the bug**
On the mobile version of the site, after opening the menu we need to click on the menu button twice to close it. Clicking it only once causes the menu list to reopen.

**To Reproduce**

1. Go to mobile version of the webpage
2. Click on menu button, menu list will open
3. Click on the menu button again, it won't close
4. Click on it again and it will close this time

**Expected behavior**
The menu should close on first click.

**Screenshots**
No screenshots necessary

**Smartphone (please complete the following information):**

- Device: Redmi Note 4
- OS: Android 10
- Browser: Brave browser (based on Chromium)
- Version: 1.5.131

**Additional context**
No additional context necessary

**Comment by shuklaayush** [comment]
Seems to be working fine for me on Chrome. Is this browser specific?

**Comment by gopaljigaur** [comment]
Yeah, so I checked that again today on the same browser and it worked fine now. Yesterday, I couldn't see the 'close' button on opening the menu, but now it seems to be working fine.
