### ISSUE TITLE
Count of state unassigned 

### ISSUE THREAD

**Issue by brunettebungirl** [covid19india/covid19india.github.io#1947]
Wanted to know if these cases have been counted twice

**Comment by bee-rickey** [comment]
Open for interpretation I would say. The MohFW site puts these numbers out as unassigned to any state. And we have seen PB say they have transferred cases to "Central pool". So these could be cases that are not being owned by states for whatever reason. We tally with the state bulletin counts. And every morning by 9:15 (when the mohfw site updates), we match with mohfw state numbers. Hence it's an indication that these numbers are not counted by the states.
