### ISSUE TITLE
Corrupted data for Haryana coming

### ISSUE THREAD

**Issue by VarunChawla** [covid19india/covid19india.github.io#1948]
Please find attached screen shot for the same..
![Screenshot_20200520-213708](https://user-images.githubusercontent.com/8905041/82470158-9c130500-9ae2-11ea-827d-55b4dabbc5f6.jpg)

**Comment by shuklaayush** [comment]
Refer to https://github.com/covid19india/covid19india-react/issues/1846#issuecomment-626884611
