### ISSUE TITLE
Telangana contains a data point called 'Unknown', containing '-430' active cases.

### ISSUE THREAD

**Issue by HelioStrike** [covid19india/covid19india.github.io#1951]
**Describe the bug**
Telangana contains a data point called 'Unknown', containing '-430' active cases.

**To Reproduce**

1. Go to [covid19india.org](https://www.covid19india.org/).
2. Click on 'Telangana' in the states list.
3. 7th in the list of places is 'Unknown' with '-430' active cases.

**Expected behavior**
The number of active cases shouldn't be negative.

**Screenshots**
![Screenshot_2020-05-21 Coronavirus in India Latest Map and Case Count](https://user-images.githubusercontent.com/34064492/82536802-aa0a6980-9b66-11ea-8ae9-f51044e5484d.png)

**Desktop (please complete the following information):**

- OS: Ubuntu 20.04
- Browser: Mozilla Firefox
- Version: 76.0.1

**Smartphone (please complete the following information):**

- Device: Xiaomi Note 5 Pro
- OS: MIUI 11.0.3.0
- Browser: Google Chrome
- Version: 81.0.4044.138

**Comment by shuklaayush** [comment]
Refer to https://github.com/covid19india/covid19india-react/issues/1846#issuecomment-626884611

**Comment by HelioStrike** [comment]
@shuklaayush I still don't get it. What variables are fixed in the equation, from the data that's released?

Active unknown = Confirmed Unknown - Recovered Unknown - deceased unknown.

From what I understand 'Confirmed Unknown' is the only data that we receive.

**Comment by shuklaayush** [comment]
So what happens is that sometimes states do not disclose the districts of the patients who are recovering. For confirmed cases, the data is usually released. In this case, the Unkown confirmed becomes less than the Unknown recovered, and therefore the Unknown active is negative. 

Hope that clears things up.

**Comment by HelioStrike** [comment]
@shuklaayush I think I understand. Thanks :)
