### ISSUE TITLE
Issue with CSS while changing the language

### ISSUE THREAD

**Issue by guru-sode** [covid19india/covid19india.github.io#1952]
In home page there is a option to change the language. If we click 'English' which is default selection the CSS is breaking

**To Reproduce**
1. Visit the homepage.
2. Click on 'English' 
2. See the CSS breaking

**Expected behavior**
The width of the selection panel should be proper.

**Screenshots**

![Screenshot 2020-05-21 at 4 39 50 PM](https://user-images.githubusercontent.com/41196239/82553497-c49e0c00-9b81-11ea-8391-bbf02c2bb24c.png)

**Desktop (please complete the following information):**

- OS: Mac OS
- Browser Chrome
- Version Latest

**Comment by guru-sode** [comment]
@shuklaayush Please assign this issue to me, if it is a genuine issue

**Comment by hmaheshwari92** [comment]
On hovering the mouse pointer on the different languages their is no effect......

**Comment by shuklaayush** [comment]
Seems obsolete since this was based on an earlier design
