### ISSUE TITLE
Show changes over a time period

### ISSUE THREAD

**Issue by specter78** [covid19india/covid19india.github.io#1953]
**Is your feature request related to a problem? Please describe.**

I want to see changes in the last 24 hours and in the last 7 days, which I do not think is possible. 

**Describe the solution you'd like**

Add a button or page where changes over a time period can be seen. 

**Describe alternatives you've considered**
NA

**Comment by shuklaayush** [comment]
We do have a time-series at the bottom which shows changes in the state/country data. Or are you referring to something else?

**Comment by specter78** [comment]
On a closer look, yes that does provide the data.
