### ISSUE TITLE
Within State total count is less than showing count.

### ISSUE THREAD

**Issue by Dinesh-Dewangan** [covid19india/covid19india.github.io#1957]
Within State total count is not showing proper.
![image](https://user-images.githubusercontent.com/35292249/82591646-4bbca580-9bbd-11ea-8214-d04250267c56.png)

Expected:- State Count should be show summation of all district

**Comment by anukaal** [comment]
API is not working properly

**Comment by shuklaayush** [comment]
Nothing we can do about it here
