### ISSUE TITLE
Calendar View

### ISSUE THREAD

**Issue by maheshwarimrinal** [covid19india/covid19india.github.io#1960]
Request for calendar view in website where user can go and check details as per dates

**Comment by shuklaayush** [comment]
Hey, we added a timeline scroller to view data for earlier dates. Hope that addresses this :)

**Comment by maheshwarimrinal** [comment]
I liked what you did with the calendar view but if user want to directly come to todays date or want to go to a specific date let’s suppose 1st May 2020 there isn’t any option like that. 
It would be great if you look into that matter.
