### ISSUE TITLE
For Marathi, show digits in Marathi (e.g. ४ instead of 4)

### ISSUE THREAD

**Issue by crygnus** [covid19india/covid19india.github.io#1963]
**Is your feature request related to a problem? Please describe.**
People trying to look at the data in their regional language (e.g. Marathi) like to see digits in their regional language.

**Describe the solution you'd like**
Render the digits in numbers in Marathi when user has chosen Marathi as the locale.

**Describe alternatives you've considered**
No alternatives.

**Additional context**
Adding screenshots of how it looks now (English digits rendered) vs. how it should actually look like (Marathi digits rendered when language selection is Marathi)
|English Digits|Marathi Digits|
|-|-|
|<img width="422" alt="marathi_with_english_digits" src="https://user-images.githubusercontent.com/12181062/82664409-f7074200-9c31-11ea-994e-1780cce23577.png">|<img width="410" alt="marathi_with_marathi_digits" src="https://user-images.githubusercontent.com/12181062/82664418-fbcbf600-9c31-11ea-9bb3-a4c69466efb4.png">|

**Comment by bhavyachhabra65** [comment]
Claim

**Comment by sudevschiz** [comment]
Arabic numerals are common and easily understood even in these regions. Let's not complicate things.
