### ISSUE TITLE
There is a deepscan plug-in VScode used to scan all react code for unused variables, code practice and warnings. I am implementing that on our code base so that there might be some cleanup

### ISSUE THREAD

**Issue by yashbujji** [covid19india/covid19india.github.io#1969]
**Describe the bug**
A clear and concise description of what the bug is. If your issue is regarding an error in the data, it's best reported through [this form](https://forms.gle/MLeSrdwRuf8AjFkp9).

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by shuklaayush** [comment]
Please follow the issue format
