### ISSUE TITLE
Scanning our code base with DeepScan Plug-in of Visual studio code.

### ISSUE THREAD

**Issue by yashbujji** [covid19india/covid19india.github.io#1970]
There may be some code clean-up like unused variables, null-check operator, code severity warnings. We can run a deepscan plug-in provided by VS-code. and see if our code is free of the above.

To Reproduce:
1.Install DeepScan plug-in from extensions on the left panel in VScode.
2.after it is installed, confirm the plug-in message and start running.
3. To run, go to any .js file and wait for 1 sec, go to problems window in the terminal and see it mentions any errors. (if no errors, it throws a message stating 'no problems have been detected in the workspace so far').
4. If errors, it throws the line number followed by an error message.
5. make necessary changes and save the file, you will see the error getting disappeared

By doing this, we can resolve all the utility bugs in our code and make our code more bug-free and robust.

(Once running deepscan, make sure the application is running as it previously.)

<img width="1440" alt="Screenshot 2020-05-23 at 12 45 23 AM" src="https://user-images.githubusercontent.com/36237332/82702056-dfaa7200-9c8e-11ea-90b0-b5ca3ef42128.png">
Check the screenshot.

**Comment by ggupta011** [comment]
DO we have any command to check entire code base to scan in one go ?

**Comment by shuklaayush** [comment]
Yes, there's a pre-commit hook which runs `eslint` to check for errors. Anyways, you can always create an issue and make a PR if you find any errors that may have been missed
