### ISSUE TITLE
Summation of confirmed cases for the day in Haryana

### ISSUE THREAD

**Issue by championballer** [covid19india/covid19india.github.io#1976]
**Describe the bug**
The total cases for Haryana are not equal to the sum of cases from individual districts. Is there a specific reason behind it?

**To Reproduce**
Tap the Haryana row in the main stats table. 

**Expected behavior**
In my knowledge the confirmed cases for the day should be equal to the sum of cases confirmed from individual districts. Would love to know if a different design decision was made for the same.

**Screenshots**
![Screenshot 2020-05-23 at 10 45 30 PM](https://user-images.githubusercontent.com/39242078/82736445-818d9580-9d47-11ea-83d5-a7ee2a9dcc34.png)

**Desktop (please complete the following information):**

- OS: MacOS
- Browser Google Chrome

**Comment by harsh1399** [comment]
I'm new to react and a first-time contributor. But I would like to work on this.

/claim

**Comment by bee-rickey** [comment]
Can you tell for which date this was?

**Comment by championballer** [comment]
23rd May

**Comment by bee-rickey** [comment]
> 23rd May

Will have a look. Thank you!

**Comment by shuklaayush** [comment]
Seems to be fixed
