### ISSUE TITLE
Footer in all pages

### ISSUE THREAD

**Issue by nayakrahul** [covid19india/covid19india.github.io#1977]
**Is your feature request related to a problem? Please describe.**
Footer should be added in all pages (deepdive, essentials, about).

**Comment by viji12oct** [comment]
Do you mean links to GitHub page and others at the bottom?

**Comment by nayakrahul** [comment]
> Do you mean links to GitHub page and others at the bottom?

Yes

**Comment by harsh1399** [comment]
I'm new to react and a first-time contributor. But I would like to work on this.

/claim

**Comment by kanup4m** [comment]
Hey, i would like to help with that issue.
/claim

**Comment by navkumar258** [comment]
Hi, tried to take it up, looking for my first contribution.
**CHANGES:** Imported Footer in faq.js & essentials.js and added just before the ending of root div in render function.
Compiled & running on my local machine. Hope it helps. Thanks 😄
