### ISSUE TITLE
Last updated time missing

### ISSUE THREAD

**Issue by rajathsn** [covid19india/covid19india.github.io#198]
Last updated time is missing 
![AF62AB06-EE53-4672-9BFD-DE0F895CB4F9](https://user-images.githubusercontent.com/52188338/77674202-32c6b800-6fb1-11ea-96ec-479ffa1f384b.png)

**Comment by abhishekkhandait** [comment]
@Rajath-BeeLab I can't reproduce.

**Comment by abhishekkhandait** [comment]
@Rajath-BeeLab : I cant reproduce this. Tested it on all available devices with device mode in Chrome DevTools

**Comment by iamrishav** [comment]
Can't reproduce it.

**Comment by Rajesh-Narayanappa87** [comment]
It works in chrome. I could reproduce in safari desktop view itself..

**Comment by rajathsn** [comment]
Then I think issue is in all iOS or apple device. All browsers in iOS.

**Comment by Rajesh-Narayanappa87** [comment]
yes.. I can confirm issue exist on chrome of iOS too..

**Comment by rajathsn** [comment]
I’m using iPhone and couldn’t see last updated time. I dint have android device in hand to check. So I think this is issue arise only in iPhone or iOS devices

**Comment by Rajesh-Narayanappa87** [comment]
Also strange one.. When i try working in local on same safari browser, it works. 
But when i open prod version it isn't..

Both below snaps are from safari on MacOS

Prod version:
<img width="968" alt="Screenshot 2020-03-26 at 11 08 16 PM" src="https://user-images.githubusercontent.com/25228632/77678199-ccdd2f00-6fb6-11ea-9784-766c79bd8088.png">

local version:
<img width="674" alt="Screenshot 2020-03-26 at 11 08 28 PM" src="https://user-images.githubusercontent.com/25228632/77678225-d6669700-6fb6-11ea-8a8a-02e620696023.png">


I strongly feel something went wrong during bundling.. Still checking

**Comment by s-naveen** [comment]
I checked this and found the cause

We are checking date is valid or not by using Date.parse() safari returns NaN in this case while chrome parses it without any issues. . We might need to use library like momentJS to fix this issue.

**Comment by s-naveen** [comment]
@Rajesh-Narayanappa87 your local might not have the latest changes.

**Comment by jeremyphilemon** [comment]
Gotcha fam! Patched 🍃
