### ISSUE TITLE
onClick of "State Unassigned" in dropdown takes to "All State data"

### ISSUE THREAD

**Issue by roydebalina** [covid19india/covid19india.github.io#1980]
**Describe the bug**
Click on "State Unassigned" in the drop down menu of state data takes the cursor to "All State" data, i.e. to the beginning of the list.
If using keyboard to navigate the list. This makes you return to top and the keyboard cursor never reaches to the states bellow "State Unassigned"

**Comment by shuklaayush** [comment]
Should be fixed now. Thanks for reporting! :)
