### ISSUE TITLE
Wrong report of cases in Telangana

### ISSUE THREAD

**Issue by aseef17** [covid19india/covid19india.github.io#1981]
The number of recovered cases for unknown district is more than the confirmed. 

![image](https://user-images.githubusercontent.com/26878414/82747207-7ae93780-9db4-11ea-97b1-bdc24c4cf88e.jpeg)

**Comment by shuklaayush** [comment]
Refer to https://github.com/covid19india/covid19india-react/issues/1846#issuecomment-626884611
