### ISSUE TITLE
Summation of confirmed cases for the day in Goa

### ISSUE THREAD

**Issue by anukaal** [covid19india/covid19india.github.io#1982]
**Describe the bug**
The total cases for Goa(increased cases) are not equal to the sum of cases from individual districts. Is there a specific reason behind it?

**To Reproduce**
Go to the section of Goa in the map and click it..

**Expected behavior**
In my knowledge the confirmed cases for the day should be equal to the sum of cases confirmed from individual districts. Would love to know if a different design decision was made for the same.

**Screenshots**
<img width="669" alt="Screenshot 2020-05-24 at 7 47 35 PM" src="https://user-images.githubusercontent.com/53907493/82756433-eef8ff00-9df7-11ea-960a-aa5dd5deeab3.png">

**Desktop (please complete the following information):**

**Comment by harsh1399** [comment]
I'm a first-time contributor. But I want to contribute to solving this issue.  

\claim

**Comment by shuklaayush** [comment]
Seems to be fixed. Might have been because of a delay in the API update
