### ISSUE TITLE
Red/Orange/Green Zone is missing

### ISSUE THREAD

**Issue by Divastra** [covid19india/covid19india.github.io#1983]
**Describe the bug**
Red zone orange and Green Zone was present earlier is now missing from all the states in the statistics

**To Reproduce**

1. Go to 'All state statistics'
2. Click on 'Any state name'
3. See error

**Expected behavior**
Colours of all zones was expected to be present in the district of all states.

**Smartphone (please complete the following information):**

- Device: [Vivo s1]
- OS: [Android 9]
- Browser [Chrome]
- Version [81.0.4044.111]

**Additional context**

**Comment by bee-rickey** [comment]
Zones have been removed from the site aa, the classification has moved to containment zones. Zones will not be displayed unless the govt brings back district zones.
