### ISSUE TITLE
Percentage value of number of death and recovered.

### ISSUE THREAD

**Issue by Indrasen-007** [covid19india/covid19india.github.io#1984]
**Is your feature request related to a problem? Please describe.**
As a user I would like to know what percentage of people have recovered and percentage of the total cases led to death.

**Describe the solution you'd like**
A very simple percentage value.
For example RecoveryRatePercentage = TotalRecovery * 100/TotalCases
TotalDeathsPercentage = TotalDeaths * 100/TotalCaese

**Describe alternatives you've considered**
NA

**Additional context**
It is good metric to understand how are we processing with the COVID-19 fight.
People are able to relate with percentage more easily than the big numbers.
We can also add a graph of percentage value, how it changed with time.

**Comment by harsh1399** [comment]
I'm new to react and a first-time contributor. But I would like to work on this.

/claim

**Comment by Kacppian** [comment]
Can I work on this?

**Comment by Kacppian** [comment]
Will we be working on this?

**Comment by navkumar258** [comment]
Hi team, tried to take it up.
![image](https://user-images.githubusercontent.com/7344604/85924871-a8913700-b8b2-11ea-9782-6671f17b2c94.png)

Compiled and running as expected on my local machine. thanks 😄

**Comment by Indrasen-007** [comment]
What should be the next step here ?

**Comment by ronalddas** [comment]
@shuklaayush , can you assign this issue to someone?(I would be happy to be help), there was already a PR created #2160 , or reopen the old the PR?
I think, this will be a useful feature.
