### ISSUE TITLE
Dropdown in displaying an empty string

### ISSUE THREAD

**Issue by prabureddy** [covid19india/covid19india.github.io#1987]
**Describe the bug**
An empty string which is rendered in the breadcrumb dropdown list on the state page.

**Description of PR**

I tested this in my machine. When I console log the states in PureBreadcrumbs Method which is located in components/ state.js, I noticed there is a state code called UN which does not exist and the state code UN is rendered in the PureBreadcrumbs dropdown list as an empty string. So I filtered the state codes before rendering it to the page.

**Screenshots**

![image](https://user-images.githubusercontent.com/44055337/82780978-4fc71c80-9e76-11ea-9215-f670e1c853c4.png)

**To Reproduce**

1. Go to any of the State pages i.e. https://www.covid19india.org/state/MH
2. Click on the dropdown on breadcrump i.e. Home / TamilNadu
3. Inside the dropdown list below Bihar, you will find empty string rendered
4. The empty string is rendered which is state code UN which doesn't exist

**Expected behavior**
Want to filter the dropdown before rendering on the page.

**Comment by prabureddy** [comment]
I would like to /claim this issue after this issue is /available.
Thank You.

**Comment by shuklaayush** [comment]
Seems to be fixed
