### ISSUE TITLE
Gender and Age distribution plots not updated with all raw data API

### ISSUE THREAD

**Issue by aayushgupta97** [covid19india/covid19india.github.io#1988]
**Describe the bug**
The gender pie chart and the age distribution histogram are not using all the 5 different raw data APIs. The collective sum of both should be over 20k while our sample is only 5k and 2k respectively.

**To Reproduce**

1. Go to https://www.covid19india.org/deepdive
3. Scroll down to Patient Gender and patient's by age

**Expected behavior**
Should be updated with all the 5 apis as seen here https://covidnineteendash.herokuapp.com/india
I'm using the same APIs as well.

**Comment by prabureddy** [comment]
I would like to /claim this issue after this issue is /available.
Thank You.

**Comment by bee-rickey** [comment]
There are some data changes that need to be done in order for this to work. @jeremyphilemon is currently working on this. Till then this will be kept on hold.
