### ISSUE TITLE
TypeError: ansiStyles.color is undefined

### ISSUE THREAD

**Issue by flashblaze** [covid19india/covid19india.github.io#1989]
**Describe the bug**
Upon running `npm i && npm start`, the app displays this error
`TypeError: ansiStyles.color is undefined`

**To Reproduce**

1. Clone the repo
2. Go into the directory and run `npm i && npm start`
3. The app shows blank screen with `TypeError: ansiStyles.color is undefined` error in console

**Expected behavior**
The app should display the map of India along with the statistics.

**Screenshots**
![image](https://user-images.githubusercontent.com/13968549/82857664-49e14200-9f2f-11ea-8604-a525495b2da3.png)

**Desktop (please complete the following information):**

- OS: [Windows 10]
- Browser [Firefox, Brave]
- Version [FF 76.0.1, Brave 1.9.72]

**Additional context**

**Solution which worked for me**
Installing `ansi-styles` as a dev dependency by `npm i -D ansi-styles` worked and displayed everything correctly

**Comment by bee-rickey** [comment]
Works fine for me. @jeremyphilemon @shuklaayush Confirm?

**Comment by flashblaze** [comment]
Any updates?

**Comment by shuklaayush** [comment]
I tried on a fresh clone, and it works fine. Might be specific to Windows? I can't check

**Comment by flashblaze** [comment]
Working fine now without any changes. No idea how. Closing.
