### ISSUE TITLE
State name is state unassigned

### ISSUE THREAD

**Issue by vsasvipul0605** [covid19india/covid19india.github.io#1991]
**Describe the bug**
the state name is state unassigned after Uttar Pradesh state in the table with 4013 active as well as 4013 confirmed cases.

**To Reproduce**

1. Go to ['link'](https://www.covid19india.org/)
2. Scroll down in states table after the state name UP.
3. See error

**Expected behavior**
State name must be something.

**Screenshots**
![Screenshot (8)](https://user-images.githubusercontent.com/47572837/83017989-3246ae00-a042-11ea-85ad-eefe1565fa22.png)

**Desktop (please complete the following information):**

- OS: [e.g. Windows]
- Browser [e.g. chrome]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by nayakrahul** [comment]
This is intentional. They are yet to be assigned.
https://indianexpress.com/article/india/coronavirus-india-lockdown-unassigned-cases-near-3000-rise-as-curbs-on-movement-lifted-6428789/
