### ISSUE TITLE
State unassigned showing on the website

### ISSUE THREAD

**Issue by Avni-Sharma** [covid19india/covid19india.github.io#1999]
On viewing on Chrome browser[Desktop] the state under UP shows `state unassigned`
![Screenshot from 2020-05-29 18-38-23](https://user-images.githubusercontent.com/18097007/83263151-c39d5800-a1db-11ea-85f6-231bbf187457.png)

**Comment by shuklaayush** [comment]
Tap/click on the info icon next to it to see why it's there
