### ISSUE TITLE
Expand button is in disabled state

### ISSUE THREAD

**Issue by afeesps** [covid19india/covid19india.github.io#2001]
**Describe the bug**
Expand toggle button is in disabled state under Demographics

1. Go to https://www.covid19india.org/demographics

**Expected behavior**
Expand Toggle button is unnecessary

**Screenshots**
https://www.covid19india.org/demographics
![Capture](https://user-images.githubusercontent.com/8069377/83288620-4c7aba80-a201-11ea-8e81-cd8e381452d4.PNG)

**Comment by ggupta011** [comment]
I want to claim this issue, I will fix and will create a pull request

**Comment by ggupta011** [comment]
Should we remove this toggle button from the component ?

**Comment by shuklaayush** [comment]
Seems obsolete now since demographics was deprecated. Closing
