### ISSUE TITLE
Missing phone number in Essentials

### ISSUE THREAD

**Issue by RisingGeek** [covid19india/covid19india.github.io#2002]
**Describe the bug**
Some of the results only show the telephone icon but not the phone number. This may happen if a certain result doesn't have a phone number.

**To Reproduce**

1. Click on  'Essentials'
2. In my area, clicking on the 'Lab' tag reproduce the issue.

**Expected behavior**
No telephone icon when the phone number is not available.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/37294158/83294767-7afd9300-a20b-11ea-8803-3e140fe3a1a6.PNG)

**Desktop:**

- OS: Windows
- Browser: Chrome
- Version: 83

**Comment by ggupta011** [comment]
Can i work on this issue?

**Comment by RisingGeek** [comment]
I want to claim this issue once it's status is changed to available.
