### ISSUE TITLE
Confusing category tags in Essentials

### ISSUE THREAD

**Issue by RisingGeek** [covid19india/covid19india.github.io#2003]
**Is your feature request related to a problem? Please describe.**
The category tags present in Essentials are a bit confusing. It seems to be difficult to keep track of which tag is enabled.

**Describe the solution you'd like**
Instead of using color as an indicator of currently applied tags, It would be better to represent it by a checkbox.

**Describe alternatives you've considered**
Another alternative can be to display tags as filters just like e-commerce websites.

**Comment by KapoorAyush** [comment]
I think it would be better if applied tags are represented by color indicator along with the checkbox.
I would like to work on this if it becomes available.
