### ISSUE TITLE
Decrease the scale of Deceased Graph 

### ISSUE THREAD

**Issue by vishrut277** [covid19india/covid19india.github.io#2008]
As the number of deaths are relatively less as compared to active, recovered and confirmed cases. Following the same scale of thousands doesn't give a clear picture. If the y-axis scale is in the order of hundreds the growth and change would be more clear.

**Comment by srvnngtm** [comment]
You can use the "Uniform" toggle under 'spread trends' to autoscale Y-axis on all charts.

Thanks
