### ISSUE TITLE
Language choice option

### ISSUE THREAD

**Issue by PrajaktaSathe** [covid19india/covid19india.github.io#2010]
**Is your feature request related to a problem? Please describe.**
Not a problem as such. Just a suggestion on accessibility of the language choice option.

**Describe the solution you'd like**
It would be more helpful if the option of the choice of language is given at the beginning (i.e. when the site is opened) itself.

**Describe alternatives you've considered**
N/A

**Additional context**
N?A

**Comment by shuklaayush** [comment]
We're just following the convention here. Usually, people expect the language switching option to be in the top/sidebar. That's why it's kept as so
