### ISSUE TITLE
How can Active numbers of covid positive patients can be Negative?

### ISSUE THREAD

**Issue by gaurav7118** [covid19india/covid19india.github.io#2011]
**Is your feature request related to a problem? Please describe.**
In Manipur state on expanding some of the districts showing negative active covid patients which is not possible.

**Screenshot of problem**
![screenshot-www covid19india org-2020 06 01-13_28_15](https://user-images.githubusercontent.com/46915693/83388321-e01fd700-a40b-11ea-84c4-f0e918f25053.png)

**Comment by shuklaayush** [comment]
Seems to be fixed now
