### ISSUE TITLE
List of containment zones

### ISSUE THREAD

**Issue by shaileshtewari** [covid19india/covid19india.github.io#2012]
As of today with recent Government direction , Red , Orange and Green zones are no longer relevant . How ever most important zone to track will be list of Containment zone. Movement is allowed but in containment zones so it will be quite helpful to see whether an area is ina containment zone before stepping out of home.

**Comment by sudevschiz** [comment]
This data is too dynamic and difficult to capture at national scale. Citizens would've to reach out to your local administration to get the latest information. Closing this issue as this is out of scope for us.
