### ISSUE TITLE
Validation of negative data in test done

### ISSUE THREAD

**Issue by Bhupesh-cyber** [covid19india/covid19india.github.io#2014]
There are negative figures in test done in some state which is some kind of error. Please add validation for negative data in chart. It would be better to not reflect the data of that data which is negative.

I am adding screenshot of issue.
![Screenshot_20200601-223258_Chrome](https://user-images.githubusercontent.com/66257429/83434390-04a1a080-a458-11ea-952d-7d0d55c20ba3.jpg)
![Screenshot_20200601-223238_Chrome](https://user-images.githubusercontent.com/66257429/83434404-0bc8ae80-a458-11ea-8c7e-5f56e5783d21.jpg)
![Screenshot_20200601-223217_Chrome](https://user-images.githubusercontent.com/66257429/83434421-15eaad00-a458-11ea-8590-5db86e3f19e7.jpg)

**Comment by shuklaayush** [comment]
Nothing we can do about it. It's based on data released in state bulletins. Can't fix it until there's a clarification by the state government
