### ISSUE TITLE
Top districts `View all` button text is not aligned to the center.

### ISSUE THREAD

**Issue by shvms** [covid19india/covid19india.github.io#2015]
**Describe the bug**
In the `covid19india.org/state/<state>` page, under the `Top districts` section, the `View all` button text is not aligned to the center and looks odd.

**To Reproduce**

1. Go to `covid19india.org/state/WB`
2. Scroll to 'Top districts'
4. See 'View all' button.

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/44120980/83443208-ff981d80-a466-11ea-9450-fca66694f356.png)

**Desktop (please complete the following information):**
- Browser: Chrome
- Version: 83

**Comment by sparsh-99** [comment]
@shvms I think this would take to large-scale implementation as all the pages use the same alignment. This is just a waste of time.

**Comment by shvms** [comment]
@sparsh-99 it seems that the issue is very specific to the `.district-bar .district-bar-left button`. This issue can be resolved from there in two ways and since the styling scope is minimal, I don't think it will effect other elements.

**Comment by shuklaayush** [comment]
Fixed via 015ff12e772653c96cead91873a792d7f971d926. Thanks for reporting! :)
