### ISSUE TITLE
Number formatting issues in State Wise (Top District & Map section)

### ISSUE THREAD

**Issue by ghost** [covid19india/covid19india.github.io#2016]
**Describe the bug**
In the covid19india.org/state/<state>, under the Top districts section numbers in the graph and charts are not formatted in thousands. Same with the numbers in the map section

**To Reproduce**

1. Go to **https://www.covid19india.org/state/MH**
2. Navigate to **Top Districts** section (right hand side)
3. Check the numbers beneath the Top districts section, it is not separated by thousand
4. Also, formatting issue can be seen in Map section of District wise page

**Screenshots**
Below is the screenshot for the same - 

![image](https://user-images.githubusercontent.com/23272561/83449617-8fdb6000-a471-11ea-8296-a72f93624d05.png)

**Desktop (please complete the following information):**

- Browser - Chrome
- Version - 83

**Comment by shuklaayush** [comment]
Fixed
