### ISSUE TITLE
"state Unassigned" for a state in states list. 

### ISSUE THREAD

**Issue by sachin10101998** [covid19india/covid19india.github.io#2018]
**Describe the bug**
State Unassigned in place of name of a state. 

**To Reproduce**

1. Go to www.covid19india.org
2. Look into the states' list. attaching a screenshot for reference.

**Expected behavior**
Name of the state.

**Screenshots**
![Screenshot from 2020-06-02 10-17-37](https://user-images.githubusercontent.com/34926285/83481077-7ca0b280-a4ba-11ea-8ec8-a0ba2dfedb7d.png)

**Desktop (please complete the following information):**

- OS:Ubuntu 18.04
- Browser Chrome latest

**Comment by shuklaayush** [comment]
Nothing we can do about this. It's how MoHFW reports it

![image](https://user-images.githubusercontent.com/27727946/83497562-44a86800-a4d8-11ea-9687-18538afcfa9c.png)
