### ISSUE TITLE
Bring back the increment of stats from previous day

### ISSUE THREAD

**Issue by ysingla** [covid19india/covid19india.github.io#2019]
It was good when the stats showed us how many cases/tests/active/recovery has been reported by each state and that too like how many changed from previous like if Maharashtra did 15K tests on day 1 and day 2 9K, the difference of 6K should be highlighted in graph. I think it has been removed today only.

**Comment by shuklaayush** [comment]
Fixed via ce69bbd8c549815b70231a52e439e1d6eb85cb96
