### ISSUE TITLE
Daily Graph on the Home page does not render the previous day count properly

### ISSUE THREAD

**Issue by amogh-kalalbandi** [covid19india/covid19india.github.io#2020]
**Describe the bug**
A clear and concise description of what the bug is. If your issue is regarding an error in the data, it's best reported through [this form](https://forms.gle/MLeSrdwRuf8AjFkp9).

**To Reproduce**

1. Go to 'Home Page'
2. Choose any state from dropdown.
3. Change the graph mode to daily.
4. See the graph of previous day is overlapping with y-axis.

**Expected behavior**
increase the width of the container rendering the svg and also the y-axis translate property.

**Screenshots**
<img width="564" alt="Screen Shot 2020-06-02 at 11 46 58 AM" src="https://user-images.githubusercontent.com/31251210/83486525-f8a0f780-a4c6-11ea-9a27-9b4ba2a618bb.png">

**Desktop (please complete the following information):**

- OS: iOS [e.g. iOS]
- Browser - Chrome [e.g. chrome]
- Version - Version 83.0.4103.61 (Official Build) (64-bit) [e.g. 22]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by 2580ayush2580** [comment]
I want to work on this

**Comment by amogh-kalalbandi** [comment]
I am still seeing this issue.
The daily count graph's previous day bar is overlapping with y-axis

Specs:
OS = macOS High Sierra 10.13.6.
Browser = Google chrome.

<img width="502" alt="Screen Shot 2020-06-11 at 5 43 01 PM" src="https://user-images.githubusercontent.com/31251210/84385071-98b7f880-ac0c-11ea-82d5-6824a3cf9493.png">
