### ISSUE TITLE
After going to a particular date and coming back cases increase statewise are not updated

### ISSUE THREAD

**Issue by Achal1607** [covid19india/covid19india.github.io#2022]
**Describe the bug**
When we go to a particular date to see number of cases and come back to today`s date the number of cases increase statewise remains of the previous date only it is not updated.

**Expected behavior**
Cases increase statewise of today's date should be updated automatically after coming back.

**Screenshots**
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/55803675/83499183-90f4a780-a4da-11ea-9f28-4ad7944fa9f1.gif)

**Comment by Achal1607** [comment]
If you assign it to me I can try to solve it...

**Comment by shuklaayush** [comment]
Fixed via ededdea8044ec1b3578a51517956e5801f429051
