### ISSUE TITLE
Confirmed Cases Per Million (National) on State Details Page is Wrong

### ISSUE THREAD

**Issue by princechauhan1992** [covid19india/covid19india.github.io#2023]
We are using number of confirmed cases from state to calculate total confirmed cases per million (at national level). We need to send the overall total in props in order to get the correct number.
![Screenshot from 2020-06-02 17-10-46](https://user-images.githubusercontent.com/28181749/83516084-0de04b00-a4f4-11ea-815a-da4633a83b48.png)

**Comment by shuklaayush** [comment]
Fixed via 44736d184e297c362d375555cf87c78a0b71771d. Thanks for reporting! :)
