### ISSUE TITLE
way to reset the timeline to today

### ISSUE THREAD

**Issue by nayakrahul** [covid19india/covid19india.github.io#2024]

**Comment by shuklaayush** [comment]
If you're on PC, you can press Esc. We'll have to think of something for mobiles

**Comment by nayakrahul** [comment]
@shuklaayush a fast-forward icon at the right-most side might suffice.

**Comment by nayakrahul** [comment]
@shuklaayush double click on the right date should take to the end (today)

**Comment by rtkg12** [comment]
Can you provide more details about what exactly is needed?
