### ISSUE TITLE
Full calendar for selecting date

### ISSUE THREAD

**Issue by aman4512** [covid19india/covid19india.github.io#2026]
**Is your feature request related to a problem? Please describe.**
The access of historical data is a great addition but allowing to select from only 3 dates at a time isn't great UX wise. 

**Describe the solution you'd like**
A full calendar to select date would be nice. Also, a toggle to reset to today.

**Describe alternatives you've considered**

**Additional context**

**Comment by akbansa** [comment]
Let me /claim this

**Comment by aman4512** [comment]
What happened to this? Two files seem to have conflicts. Can they be resolved?

**Comment by akbansa** [comment]
@aman4512  Let me resolve them!

**Comment by aman4512** [comment]
A maintainer will have to comment on that. I was just asking since I raised the issue and it seems very close to completion. @shuklaayush please shed some light!

**Comment by akbansa** [comment]
@aman4512 Let's wait for them to reply!
