### ISSUE TITLE
Alternative for District Level : Zones	

### ISSUE THREAD

**Issue by muthukumarsm** [covid19india/covid19india.github.io#2028]
**Describe the bug**
Please let us know what is the backup/alternative for folks using : 

District Level : Zones

While I completely understand that this is volunteer driven APIs and respect the work immensely, i dont see a point in you randomly taking away APIs and doing an EOL as it shifts the decision making away from the core and demands time to be incurred in rebuilding with some other available APIs. if you are planning to do an EOL, can you please atleast make it clear for us not to rely on those APIs and that you won't be able to suppor them in future? I did not see this note for district level zones atleast. 
--

. 

**To Reproduce**
District level zones API usage.

**Expected behavior**
Please provide us if you have any alternatives planned for district level zones.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by shuklaayush** [comment]
Hi, I think the API is still up, just not updated since the government hasn't released any new data. Also, please open an issue in the [API repo](https://github.com/covid19india/api) if you'd like a discussion on this.

https://api.covid19india.org/zones.json

**Comment by muthukumarsm** [comment]
Thanks, but the API is marked as EOL in the table, probably soon to be
taken off?

[image: image.png]
