### ISSUE TITLE
Recovered cases are subtracted from the active cases of the same day.

### ISSUE THREAD

**Issue by shashwatS22** [covid19india/covid19india.github.io#2029]
![error](https://user-images.githubusercontent.com/46936675/83541133-dc2cab80-a516-11ea-9817-c678f1d1146f.JPG)

According to this image, there are  4489 new confirmed cases, 2059 new active cases, 2359 new recovered cases, and 71 new deceased cases.

The number of active and confirmed cases should be the same because according to these numbers it means that out of 4489 cases that were reported today 2359 were recovered and 71 were deceased the same day which is not possible.

**Comment by anurag-ux** [comment]
I can fix this issue.

**Comment by bee-rickey** [comment]
Active only means that those number of new requirements came up. This is the logic followed everywhere for active delta. Hence this behavior is correct IMO.

**Comment by shashwatS22** [comment]
IMO active means the number of cases that are still infected by the virus. According to this behavior the Total cases=Active+Recovered+Deceased.
This means that the people who were found positive today were recovered the same day, which is totally wrong.
The correct behavior should be that the total confirmed cases and the total active cases that were added the same day should be equal and the recovered cases should be subtracted from the total active cases, not the new active cases.

**Comment by shuklaayush** [comment]
It's a question of semantics. Our definition is already established and is consistent with how the meaning of daily Active is generally perceived. In addition, there's also no point in changing the definition now that most of the people who visit the website are used to this. Hence, closing
