### ISSUE TITLE
Districts record

### ISSUE THREAD

**Issue by iamsh4shank** [covid19india/covid19india.github.io#203]
**Is your feature request related to a problem? Please describe.**
on hovering over a map it only shows percentage. It will be great if on clicking a particular state it will show the record of each district present in that state.

**Describe the solution you'd like**
On clicking the state the dropbox of that particular state can be opened so that all the districts can be visible.

**Describe alternatives you've considered**
Also, one solution can be as on clicking a particular state it will open a small box there which will show the record of each district.

![Screenshot from 2020-03-26 23-33-18](https://user-images.githubusercontent.com/52889867/77681084-dc5e7700-6fba-11ea-9e37-dfa6e02fb61e.png)
![Screenshot from 2020-03-26 23-38-46](https://user-images.githubusercontent.com/52889867/77681262-16c81400-6fbb-11ea-8a04-24ef23e0d871.png)

**Comment by JunaidBabu** [comment]
Duplicate of #13
