### ISSUE TITLE
Remove anchor in timeseries explorer for touch devices

### ISSUE THREAD

**Issue by nayakrahul** [covid19india/covid19india.github.io#2031]
**Describe the bug**
Anchor should be removed in timeseries explorer for touch devices because it is not needed rather it  causes a problem when tapped. When tapped, the map explorer disappears. In the screenshot you can see that there is no map between table and timeseries.

**To Reproduce**
Steps to reproduce the behavior (Mobile): 

1. Go to Home
2. Notice the anchor icon in timeseries

**Expected behavior**
No anchor icon 

**Screenshots**
![102305735_2837064816539331_8953386514272747520_n](https://user-images.githubusercontent.com/11428805/83552435-6250ee00-a527-11ea-9079-70bf4a53be1c.jpg)

**Comment by shuklaayush** [comment]
@jeremyphilemon Not sure if it was intended, but I actually like the pin/anchor on phones
@nayakrahul That's exactly what it's supposed to do, hide the map

**Comment by nayakrahul** [comment]
@shuklaayush in desktop view, anchoring is present to use both table and timeseries/map simultaneously which I think is difficult to do in mobile view.
