### ISSUE TITLE
Search Bar Not working 

### ISSUE THREAD

**Issue by amit-sgwn** [covid19india/covid19india.github.io#2032]
**Describe the bug**
Search box not working on Mac (Checked on Chrome and Safari)
**To Reproduce**

1. Go to https://www.covid19india.org/
2. Click on Demographics
3.  Click on Home
3. Now type something  in search bar, nothing is typed, search  bar is empty 

**Expected behavior**
 Search should work fine
**Screenshots**

**Desktop (please complete the following information):**

- MacBook Pro 16-inch(macOS Catalina 10.15.5)
-  Chrome, Safari

**Comment by ZalakBhojani** [comment]
Hello there, I have found the code which is causing the bug

```<div className="select">
            <DatePicker
              value={filterDate}
              minDate={new Date('30-Jan-2020')}
              maxDate={subDays(new Date(), 1)}
              format="dd/MM/y"
              calendarIcon={<Icon.Calendar />}
              inputProps={
                (onkeydown = (e) => {
                  e.preventDefault();
                })
              }
              clearIcon={<Icon.XCircle />}
              onChange={(date) => {
                setFilterDate(date);
                const fomattedDate = !!date ? format(date, 'dd/MM/yyyy') : '';
                handleFilters('dateannounced', fomattedDate);
              }}
            />
          </div> 
```

in src/components/demographics.js

The part causing the issue is:

```
inputProps={
                (onkeydown = (e) => {
                  e.preventDefault();
                })
              }
```
I do not understand the usage of event.preventDefault() here, I did not find anything regarding inputProps over react-date-picker documentation it seems something related to textfield API but I can not find the usage of it in the code. Without inputProps DatePicker, demographics and search bar seems to work properly.
So can someone help me out here?

**Comment by harirajv** [comment]
@ZalakBhojani if preventDefault() isn't present, then when date picker is opened,  the arrow keys will scroll the body of the page instead of changing the selection in the date picker.

**Comment by nayakrahul** [comment]
> @ZalakBhojani if preventDefault() isn't present, then when date picker is opened, the arrow keys will scroll the body of the page instead of changing the selection in the date picker.

I think that is manageable.

**Comment by sidhanshumonga** [comment]
If we do event.preventDefault(), it registers this method for all inputs through keyboard. 

I have fixed this issue by using event.preventDefault() only if arrow keys are pressed. Otherwise, it will behave as expected.

**Comment by shuklaayush** [comment]
Seems obsolete
