### ISSUE TITLE
District heat map 

### ISSUE THREAD

**Issue by ninjakx** [covid19india/covid19india.github.io#2035]
District heat map with zoom constraint with hover functionality.

![district_ind](https://user-images.githubusercontent.com/29797787/83561487-903d2f00-a535-11ea-8f65-b9f5840e1802.gif)

I guess this will give more info which part of the india has more spread. 
https://plnkr.co/edit/AzflYyovnJ6YwE5I
#992

**Comment by shuklaayush** [comment]
Added via #2204
