### ISSUE TITLE
Districts records not completely visible

### ISSUE THREAD

**Issue by iamsh4shank** [covid19india/covid19india.github.io#204]
**Describe the bug**
Districts record only contain confirmed cases. It doesn't show active cases, recovered cases, and deceased cases.

**To Reproduce**
Click on the dropbox arrow of any state.

**Expected behavior**
It will also show all the records which will help to maintain statistics.

**Screenshots**
![Screenshot from 2020-03-26 23-37-50](https://user-images.githubusercontent.com/52889867/77681634-a66dc280-6fbb-11ea-81ba-3f0040bda51a.png)

**Desktop (please complete the following information):**
 - OS: ubuntu
 - firefox
 - 18.0

**Comment by Invoker96** [comment]
@robustTechie Data is not available for active cases, recovered cases, and deceased cases when I hit districtWise api 'https://api.covid19india.org/state_district_wise.json'.
Once available please assign this issue to me.

**Comment by JunaidBabu** [comment]
We do not have this info at district level. Will implement this once we have such granular information from the govt.
