### ISSUE TITLE
Error in Data shown when we switch dates between previous and current.

### ISSUE THREAD

**Issue by maheshwarimrinal** [covid19india/covid19india.github.io#2040]
**Describe the bug**
A clear and concise description of what the bug is. If your issue is regarding an error in the data, it's best reported through [this form](https://forms.gle/MLeSrdwRuf8AjFkp9).

**To Reproduce**

1. Go to **history button**
2. Click on previous date like **27th May**
3. Scroll back to **Today's date**
4. You will see numbers on every state.

**Expected behaviour**
Data of same date should be shown not previous data.

**Screenshots**
![28th May 2020 DATA SHOWN as on 12:53 PM](https://user-images.githubusercontent.com/11848011/83608435-8c8fc380-a59a-11ea-907f-0a906df00646.png)
![TODAY's Data shown where their are no results of other states as on 12:53 PM](https://user-images.githubusercontent.com/11848011/83608483-9d403980-a59a-11ea-91ea-13aed722b82a.png)

**Desktop (please complete the following information):**
- Browser Safari (Version 13.1.1)
- Chrome (Version 83.0.4103.61)

**Smartphone (please complete the following information):**
- Device: iPhone XR (Safari, iOS 13.5.1)

**Comment by shuklaayush** [comment]
Fixed via ededdea8044ec1b3578a51517956e5801f429051
