### ISSUE TITLE
Unnecessary <br> tag when hovering on the info icon.

### ISSUE THREAD

**Issue by madhusr-github** [covid19india/covid19india.github.io#2041]
**Describe the bug**
 An unnecessary line break (br) tag can be seen when hovered on the info icon beside the state names.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to the Home page.
2. Hover on the info icon(octicon) beside the state name(Tamil Nadu, Delhi etc).  
3. A line break (br) tag can be seen.

**Expected behaviour**
No line break (br) tag should be seen.

**Desktop (please complete the following information):**

- OS: [Windows 10]
- Browser [Chrome]
- Version [83.0.4103.61]

**Smartphone (please complete the following information):**

- Device: [Samsung A50]
- OS: [Android]
- Browser [Chrome]
- Version [83.0.4103.61]

**Additional context**
No context about the problem.

**Comment by sudevschiz** [comment]
I have fixed these in the Sheet.
