### ISSUE TITLE
UI is broken in Firefox when privacy.resistFingerprinting is enabled

### ISSUE THREAD

**Issue by esrk** [covid19india/covid19india.github.io#2042]
**Describe the bug**
As part of Mozilla Firefox's privacy measures, when `privacy.resistFingerprinting` flag is enabled in Firefox developer settings, [UI](https://www.covid19india.org/) does not display tables. 

**To Reproduce**

1) Enable `privacy.resistFingerprinting` in `about:config` of Mozilla Firefox.
2) Open [website](https://www.covid19india.org/).

**Expected behavior**
As shown in screenshots

**Screenshots**

**Current behaviour :**
<img width="500" alt="Firefox" src="https://user-images.githubusercontent.com/19510263/83613624-93571000-a573-11ea-9d44-7778080adfe8.png">

**Expected behaviour:**
<img width="500" alt="Chrome" src="https://user-images.githubusercontent.com/19510263/83613777-cc8f8000-a573-11ea-9821-30698631e8a2.png">

**Desktop (please complete the following information):**

- OS: MacOS Mojave 10.14.6
- Browser: Firefox
- Version: 77.0 64 bit

**Additional Context**
The UI was working till last few days with this config. Hence it could either be a recent UI release or a browser release making it incompatible

**Comment by esrk** [comment]
**RCA:**

Could see that the issue is due to the usage of [react-spring](https://github.com/react-spring/react-spring) package for animations. This same [issue](https://github.com/react-spring/react-spring/issues/664) is being tracked there as well.

**Comment by shuklaayush** [comment]
In that case, it's irrelevant to discuss this here
