### ISSUE TITLE
deep dive not showing up in menu 

### ISSUE THREAD

**Issue by iamrajee** [covid19india/covid19india.github.io#2044]
**Describe the bug**
"Deep dive" is not showing up in the menu on the homepage.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to deep dive [page](https://www.covid19india.org/deepdive). Although it is redirecting to the homepage itself.
2. See the menu in the left-hand side

**Screenshots**
![Screenshot from 2020-06-03 14-55-25](https://user-images.githubusercontent.com/25712145/83620509-0af46180-a5ab-11ea-9db1-3ea9fa419556.png)

**Device**

- Device: [e.g. Acer predator helios 300]
- OS: Ubuntu, Linux
- Browser: chrome

**Comment by shuklaayush** [comment]
Yep, deep-dive was not being actively maintained, and hence we decided to deprecate it. We do plan to redesign it sometime in the future. Let us know if you'd like to help with that

**Comment by iamrajee** [comment]
I see, thanks for the confirmation!
