### ISSUE TITLE
To improve in understanding 

### ISSUE THREAD

**Issue by codewithbk** [covid19india/covid19india.github.io#2046]
Hey there your website it to great but one thing that I noticed and I hope if you do this so your website look more cool that thing you write if the _COVID-19_ case are greater in past records so you write this line  **Today is largest growth** in _COVID-19_ case.

**Comment by shuklaayush** [comment]
Thanks for the suggestion, but I think this would be pretty evident in the time-series graphs

**Comment by codewithbk** [comment]
Ok as your wish thanks for read these and reply you answer.🙏🙏
