### ISSUE TITLE
Doc// typo mistake in contribution.md

### ISSUE THREAD

**Issue by abhi07iiest** [covid19india/covid19india.github.io#2049]
solved

**Comment by abhi07iiest** [comment]
self assigned

**Comment by abhi07iiest** [comment]
#2050 
**Typo fixed in contribution.md**

**Comment by naveensaigit** [comment]
Actually, first off is correct English and the change you made must be "first of all" instead of "first off all" incase you really want to change the statement

**Comment by karthikshetty03** [comment]
There is no issue in this right ?
