### ISSUE TITLE
A disclaimer note should be on front page mentioning this is not an official site

### ISSUE THREAD

**Issue by engg-rehman** [covid19india/covid19india.github.io#205]
Before anything I must say, your work is very appreciated. 

I believe there should be a disclaimer on the front page mentioning that this is not an official site, and the data collection is a community-driven effort collected from different sources of media. Optionally you can also have a link to the [Health ministry](https://www.mohfw.gov.in/) site which has official statistics 

I know you have already mentioned that on your FAQ page. But for a sensitive topic like COVID-19 statistics will give the reader a clear idea about site objective and where it stands

**Comment by sudevschiz** [comment]
We have done lot of initiative (Adding FAQ, mentioning that this is a crowdsourced website, replying to key people in Twitter) to get this message across. 

That's enough time and effort spent on that. So, not change for now. Thanks for notifying!
