### ISSUE TITLE
Totalling Issue

### ISSUE THREAD

**Issue by Mohitbhc** [covid19india/covid19india.github.io#2052]
When there is a raise in active cases the. Confirmed cases should also raise but if recovered cases also raises it is still adding raise in active case and raise in Recovery cases and total of both is added to confirmed cases
Example
Confirm case - C
Active case - A
Recovered - R
C-1000.   A-200.    R- 100
Then 
C-1100.   A-300.    R- 100
Again 
C-1200.   A-250.    R- 150
But it is showing
C-1500.   A-250    R- 150
Totalling active and recovering in total confirmed cases

**Comment by BiswaCodes** [comment]
I think you should add Dead people also.

**Comment by shuklaayush** [comment]
Please take a look at [this](https://github.com/covid19india/covid19india-react/issues/2038#issuecomment-641962963)
