### ISSUE TITLE
Plot overlaps with headings

### ISSUE THREAD

**Issue by naveensaigit** [covid19india/covid19india.github.io#2057]
**Describe the bug**
Since the default is set to 1 month in the plots, the plot overlaps with the headings for some states

**To Reproduce**

1. Go to [covid19india.org](https://www.covid19india.org)
2. Scroll down to Spread Trends
3. Select Andaman and Nicobar Islands in the dropdown
This can be replicated with Telangana and a few other states as well

**Expected behavior**
Place the headings after y-axis ends

**Screenshots**
![Screenshot(53)](https://user-images.githubusercontent.com/56525288/83833692-24f88600-a70a-11ea-9c8e-9d785d89d1bd.png)

![Screenshot(54)](https://user-images.githubusercontent.com/56525288/83833735-3fcafa80-a70a-11ea-9eb1-43ef5f0dc38f.png)

**Desktop (please complete the following information):**

- OS: Windows
- Browser Chrome
- Version 83.0.4103.61

**Additional context**

**Comment by shuklaayush** [comment]
Duplicates #1650
