### ISSUE TITLE
Count for active cases

### ISSUE THREAD

**Issue by brunettebungirl** [covid19india/covid19india.github.io#2058]
Would like to start of by thanking the team to be so prompt with my earlier issues/requests and this website is the only website I rely on for numbers.
In fact often suggest people to rely on this website for the numbers more than any other place solely due to the number crunching and how the data is represented. Thank-you for making our lives more sorted and helping us understand the dynamics of the uprising number of cases all around the country.

Coming to the request of a new feature, I noticed that the daily count for active number of cases was removed, could you please restore that? It helps us get a sense of calm and read the actual rise in cases vs numbers recovered.
Secondly, do you plan on adding any additional features? Like the weekly top 10 cities with highest % of recoveries or % of rise in cases or something on those lines?

**Comment by bdsgupta** [comment]
Yes I totally agree with you!! It helps alot when we get to see the active counts as well..but apparently they have removed cause few people don't understand what the ACTIVE cases are apparently

**Comment by shuklaayush** [comment]
Hi! I've explained our reasoning for removing Active counts in https://github.com/covid19india/covid19india-react/issues/2105. I wasn't particularly enthusiastic about it either, but it helps take load off us volunteers.

**Comment by brunettebungirl** [comment]
Ouch! No worries. Appreciate the work you guys are doing 😊
