### ISSUE TITLE
Message below the search box overlaps the timeline component, when timeline is active.

### ISSUE THREAD

**Issue by FrozenHearth** [covid19india/covid19india.github.io#2060]
**Describe the bug**
Opening up the timeline by clicking on the clock icon, and then clicking on the search box, causes the message below the search box (message quoted below) to overlap the timeline component.
            
> To those who are in states affected by Cyclone Amphan or have family/friends there, click here to view helplines for assistance.

**To Reproduce**

1. Go to the Home page.
2. Click on the 'clock' icon below the search box.
3. Then, click on the search bar.
4. The overlapping can be seen.

**Expected behavior**
The message should not overlap the timeline component.

**Screenshots**

![Step 1](https://i.imgur.com/roikNe1.png)

![Step 2](https://i.imgur.com/RcREO67.png)

![Step 3](https://i.imgur.com/ohW0pHb.png)

**Desktop (please complete the following information):**

- OS: macOS Catalina
- Browser: Chrome
- Version: 10.15.4 

**Additional context**
N/A

**Comment by BenzhaminKim** [comment]
I've pulled the request to fix this [here](https://github.com/covid19india/covid19india-react/pull/2083)
