### ISSUE TITLE
Include graph displaying ratio of positive tests in DeepDive

### ISSUE THREAD

**Issue by nishantrai18** [covid19india/covid19india.github.io#2062]
**Is your feature request related to a problem? Please describe.**
The current scenario in India is a grim one with cases rising each day. However, one should note that this can be a side-effect of increased testing. Percentage of positive results wrt number of tests performed is a good indicator of the spread and impact of a disease. Including this data in DeepDive should provide a normalized view of the spread, something which the site lacks currently.

**Describe the solution you'd like**
The solution is pretty straight-forward - plot the graph of (positive cases / number of tests performed). Depending on the benevolence of the issue assignee, we can include state-wide statistics as well.

**Describe alternatives you've considered**
I've considered not filing this issue, but decided to go through with it in the end.

**Additional context**
If we look at spread trajectories across different nations. The %positive cases is a strong indicator of the impact of Covid-19. Including this should allow us to separate increase in testing infrastructure from the actual spread of the virus.

**Comment by shuklaayush** [comment]
We're thinking of an elegant way to add the positivity rate. But since deep dive is already deprecated, this issue is obsolete
