### ISSUE TITLE
Logarithmic y-scale persists in daily section in timeseries

### ISSUE THREAD

**Issue by nayakrahul** [covid19india/covid19india.github.io#2064]
**Describe the bug**
Logarithmic y-scale persists in daily cases section if log mode is switched on. If it is intentional, then log mode should not be disabled in daily section.

**To Reproduce**

1. Go to Home
2. Scroll down to timeseries
3. Click on cumulative tab and switch on log mode
4. Then click on daily tab
5. See that the logarithmic y-scale persists in daily section as well.

**Expected behavior**
No log mode in daily section 

**Screenshots**
![Screenshot (74)_LI](https://user-images.githubusercontent.com/11428805/83942316-fcf34a80-a80f-11ea-922b-e076d3684500.jpg)

**Comment by shuklaayush** [comment]
No, I think this is a bug. Nice catch!
