### ISSUE TITLE
Language isn't changing in the summary bar 

### ISSUE THREAD

**Issue by sourabhbagrecha** [covid19india/covid19india.github.io#2071]
**Describe the bug**
While I am changing the language using the change language button on the top left of the screen, the change is applied to every component on the screen but the summary bar.

**To Reproduce**

1. Go to: home
2. Click on English(or any lang that you have chosen already) on the top left corner
3. On the summary bar where all complied data is shown in the order

| Confirmed       | Active    | Recovered     | Deceased     |
| :------------- | :----------: | :-----------: | --------------: |
|  240327 | 123927   | 110000    | 6400     |

**Expected behavior**
The language for "Confirmed", "Active"... titles should also be changed.

**Screenshots**
![Screenrecorder-2020-06-07-10-02-16-54](https://user-images.githubusercontent.com/27056663/83960600-13e57b80-a8a8-11ea-92fc-0762683065db.gif)

**Comment by shuklaayush** [comment]
Fixed via bc0e181d2e1fa23117601ee44fa966519d9e77fc

**Comment by sourabhbagrecha** [comment]
Great work @shuklaayush
