### ISSUE TITLE
Daily cases count is incorrect

### ISSUE THREAD

**Issue by devdashboard** [covid19india/covid19india.github.io#2073]
**Describe the bug**

Team, starting form 03.55 pm IST today, there is a glitch in values getting displayed for Daily counts. Showing incorrect values. Please take a look. I'm using your API in my https://devdashboard.github.io

**Screenshots**

![Issue](https://user-images.githubusercontent.com/64152133/83967492-a5241480-a8df-11ea-9fbd-7845e571b8ff.JPG)

**Comment by shuklaayush** [comment]
Should be fixed now. But if this happens again, please open an issue on the [API repo](https://github.com/covid19india/api) instead of posting here
