### ISSUE TITLE
Count in state-wise details not visible since the bars overlook the count

### ISSUE THREAD

**Issue by shubham-aneja** [covid19india/covid19india.github.io#2075]
**Describe the bug**
Count in state-wise details not visible since the bars overlook the count.

**To Reproduce**

1. Go to 'home page'
2. Scroll down to 'state wise details'
3. Select state "Maharashtra"
4. Look at the active state. The count is getting hidden by the bar

**Expected behavior**
Count should be visible clearly

**Screenshots**
![image](https://user-images.githubusercontent.com/27283920/83972065-e4605e80-a8fb-11ea-8e98-3d5bd62a5d94.png)

**Desktop (please complete the following information):**

- OS: miui
- Browser chrome

**Smartphone (please complete the following information):**

- Device: mi note 4
- OS: miui
- Browser chrome

**Comment by shuklaayush** [comment]
Duplicates #1650
