### ISSUE TITLE
Overflow problem when tooltip is open in state page in mobile

### ISSUE THREAD

**Issue by nayakrahul** [covid19india/covid19india.github.io#2076]
**Describe the bug**
Page overflow when tooltip is opened in state page in mobile

**To Reproduce**
Steps to reproduce the behavior: (mobile)

1. Go to state page
2. Tap on tooltip icon present in right cards
3. Notice the issue

**Expected behavior**
Should not overflow

**Screenshots**
![Screenshot_20200607-203139](https://user-images.githubusercontent.com/11428805/83972471-ee835c80-a8fd-11ea-9678-bb4bf3a32835.jpg)
![Screenshot_20200607-202238](https://user-images.githubusercontent.com/11428805/83972473-f04d2000-a8fd-11ea-8543-ac7d66a8575f.jpg)

**Comment by sirdarthvader** [comment]
@nayakrahul @shuklaayush Can anyone of you guys review the PR and share feedback if any. Thanks.

**Comment by sirdarthvader** [comment]
@nayakrahul @shuklaayush Need your help with this team, I am quite confident that we can close this if someone can review the PR and merge it or share feedback otherwise.

**Comment by nayakrahul** [comment]
@shuklaayush kindly look into this.
