### ISSUE TITLE
Phone numbers overflow in case of multiple numbers in search results

### ISSUE THREAD

**Issue by nayakrahul** [covid19india/covid19india.github.io#2078]
**Describe the bug**
When there are more than 4 phone numbers, they overflow in search results.

**To Reproduce**

1. Go to Home
2. Focus on search bar
3. Click on Mumbai suggestion
4. Notice that in one of search results phone numbers overflow 

**Expected behavior**
Wrap all phone numbers

**Screenshots**
![Screenshot (76)_LI](https://user-images.githubusercontent.com/11428805/83980032-0a9ff180-a930-11ea-9ec8-69d73baebfe7.jpg)

**Comment by palashjnath** [comment]
Do you think some of the numbers should be added to the next line?
