### ISSUE TITLE
deltas in summary not resetting after 12 midnight

### ISSUE THREAD

**Issue by s-naveen** [covid19india/covid19india.github.io#208]
However deltas in table got reset.

https://photos.app.goo.gl/ZTJBoiRSgkYVwCmAA

**Comment by JunaidBabu** [comment]
Probably an issue with the sheet @sudevschiz @mohammedshafeeqet

delta in table is generated by api, I've made sure that's updated at 00:00 IST

**Comment by mohammedshafeeqet** [comment]
@s-naveen deltas for the total fields right? They reset manually till now. It is fixed at the moment. 
However, I am writing a script to automate it. Testing it now. Should be on production from tomorrow.
