### ISSUE TITLE
Map of states coloured according to number of cases is not much of a use.

### ISSUE THREAD

**Issue by longloop** [covid19india/covid19india.github.io#2081]
**Is your feature request related to a problem? Please describe.**
The map on front page which show states in shades of red is not much informative. Delhi, Gujarat, Tamil Nadu etc are in lighter colour than Maharashtra. This gives perception of Nashik, Nagpur, Jalgaon etc to be more corona effected than cities like Delhi, Ahmedabad, Chennai etc.

**Describe the solution you'd like**
1. Colour it per District/City, or
2. Colour it per state on the basis of `corona-cases/population-size` 

**Describe alternatives you've considered**
NA

**Additional context**
<img width="556" alt="india-states-coloured-as-per-corona-cases" src="https://user-images.githubusercontent.com/1381839/83982323-98d1a300-a943-11ea-8964-811f4032e589.png">

**Comment by shuklaayush** [comment]
We do have a 'Per million' button which normalizes the map based on population. Also, do check out the 'Hotspots' button which shows the distribution based on districts

**Comment by longloop** [comment]
Wow. Figured out those button just now. Clearly this is a no-issue. Both the things are already there. Maybe we can improve discoverability by some other placement if needed.
