### ISSUE TITLE
New cases not getting displayed and also new unassigned category cases not shown

### ISSUE THREAD

**Issue by ysingla** [covid19india/covid19india.github.io#2085]
![Capture](https://user-images.githubusercontent.com/38974607/84026418-ecc3a280-a9aa-11ea-81fb-2b22cf6e175c.PNG)

**Comment by kishan0725** [comment]
Possible duplicate of #2084

**Comment by shuklaayush** [comment]
This happened because of MoHFW decreasing the count of 'State Unassigned'. Should be okay now
