### ISSUE TITLE
Total number of cases not tallying

### ISSUE THREAD

**Issue by drjabhelp** [covid19india/covid19india.github.io#2087]
Today's total case count is not tallying.
Today June 8th 2020 (19:47) the total number of covid cases in India is not tallying with the individual state wise count. The total count is showing lesser number of cases. Please correct this technical glitch.
(https://www.covid19india.org/).

To Reproduce

1. Go to https://www.covid19india.org/
2. Click on home page
3. Scroll down to Total count.

Expected behavior
Please re-tally the data count of cases and add to the total count.

Smartphone
- OnePlus 5T
- OS: [9.0.11]
- Browser [Google Chrome]
- Version [83.0.4103.96]

**Comment by shuklaayush** [comment]
I'm guessing it was fixed
