### ISSUE TITLE
Population :: Add a new column against each state mentioning the population or Cases/1M population

### ISSUE THREAD

**Issue by archana900** [covid19india/covid19india.github.io#209]
Population :: Add a new column against each state mentioning the population or Cases/1M population.

This will help understand how severe hit a state is.

**Comment by iam-hitesh** [comment]
May I fix this issue @JunaidBabu ?

**Comment by dprodigalson** [comment]
statewise google sheet is not having overall population information...This census link may be helpful here. 

[Statewise Overall Population Census Link](https://data.gov.in/resources/stateut-wise-overall-population-st-population-percentage-sts-indiastate-total-population)

**Comment by jeremyphilemon** [comment]
Can we get data for population in respective districts we're displaying? If so, instead of cluttering the state rows with another datapoint, the district table have empty slots that can be filled. 

Thoughts on the availability of district wise population?

**Comment by JunaidBabu** [comment]
There is already a PR on this #228 
But we'll be handling this as a separate tab. Closing this for now. Will add later.
