### ISSUE TITLE
Count Mismatch of Confirmed Cases

### ISSUE THREAD

**Issue by abhijeet3112** [covid19india/covid19india.github.io#2097]
On 8th June, Total no of cases and the sum of cases of each state and UT are different. Total no of cases is less than the sum of cases in each state  and UT.

**Comment by shuklaayush** [comment]
Elaborate, please

**Comment by abhijeet3112** [comment]
Fine, I get that. My bad I didn't watch out the notification of unassigned.

**Comment by abhijeet3112** [comment]
Closing this issue
