### ISSUE TITLE
Search bar not working properly

### ISSUE THREAD

**Issue by surya94179260** [covid19india/covid19india.github.io#2098]
**Describe the bug**
Search bar is does not work once we go to demographics or essential part and come back to home

**To Reproduce**

1. Go to demographics
2. Again come back to home 
3. type something in search bar it won't work 

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by shuklaayush** [comment]
Duplicates #2032
