### ISSUE TITLE
Need help to build reportfake.org | to stop fake Coronavirus news and messages

### ISSUE THREAD

**Issue by monk1337** [covid19india/covid19india.github.io#210]
Hello guys, 

This is Aaditya, I am an A.I Researcher and backend developer. I am looking front-end help for website reportfake.org. 

**What is more dangerous than Coronavirus?**

This time, everyone in India following Social Distancing and Self-Quarantine to break the chain and help to stop Coronavirus. People are getting information and updates only from social media like Facebook and Whatsapp but there are many people who are spreading fake news, facts and information regarding the Coronavirus. which is misleading and very dangerous.  Lack of knowledge and no facts check is more dangerous than Coronavirus. people are coping and afraid because of fake news and information and following misleading and non-sense advises which are putting them into more critical situations. 

**What we can do?**

I am planning to build a website, where people who are aware and knowledgable who check the facts before sending or forwarding any news and Whatsapp message, to report the fake news and messages on reportfake.org website. 

**How it will help?**

-  Since there are few messages which are being forward again and again and if we can build a good database of those messages on report fake.org website with proof that why this information is misleading and why you shouldn't follow this. Then people can check their facts and clear their doubts if the message is fake or not by searching into report fake database.

- We can submit this text messages to Google with the tag of "misleading and fake info" google will index this pages and when people check online about any of that message, it will show if the information is correct or not.

-  Building an A.I fake corona news detector which will identity quickly if the message is fake or not.

**How people will  contribute?**
Simple, when you see any fake news message on Whatsapp, just take the screenshot and upload it on the website and select a tag { misleading info, fake medicine, No source available }

**How to help?**
I am looking for help in front-end development, if people like you can help to build a portal where people can upload a pic and tag that pic, backend we'll collect the data and store and submit to google. 

**Why you are doing this?**
Being into the research field, I always prefer to check information and research about something before sharing with someone but there are many people who are blindly sending the false information and then there are aware and knowledgeable people who are willing to help but not able to. we can build this portal to help people by providing correct information and stopping fake news and messages.

If anyone is interested to help, ping me please aadityaura@gmail.com

**Comment by JunaidBabu** [comment]
Not relevant to the current project.
