### ISSUE TITLE
If district or state does not match in search bar it shows nothing

### ISSUE THREAD

**Issue by surya94179260** [covid19india/covid19india.github.io#2102]
**Describe the bug**
If district or state does not match in search bar it shows nothing

**To Reproduce**

1. Go to home
2. Click on search bar
3. type anything different than state or district name
4. it shows nothing

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by shuklaayush** [comment]
Please follow the issue template
