### ISSUE TITLE
Add day in spread table date table

### ISSUE THREAD

**Issue by priyanshujain** [covid19india/covid19india.github.io#2103]
![image](https://user-images.githubusercontent.com/9302265/84132759-e1807d80-aa63-11ea-8d59-ac62597e371b.png)

If you can add Monday to 8 June -> 8 June, Monday

**Comment by navkumar258** [comment]
Hi, tried to take it up....and got it running as expected in my local machine.
**CHANGES:** Added new WEEK_DAYS constant and then got the value of day using getDay() in timeseries component.

![image](https://user-images.githubusercontent.com/7344604/86137745-42532100-bb0b-11ea-9f57-2959496a4396.png)

Hope it helps, thanks 😄

**Comment by priyanshujain** [comment]
@navkumar258 Can you please send an PR to the this repo?

**Comment by navkumar258** [comment]
@priyanshujain Sorry, facing some hard-disk issues with my system having the local repo.Will do after it is repaired. anyways, appreciate the reply.

**Comment by shuklaayush** [comment]
I think this isn't a good approach. Adding more text to the chart will lead to more overlaps. See #1650

**Comment by navkumar258** [comment]
@shuklaayush What would you suggest - Not displaying it or Can we use  the initials of each week day e.g. Mon,Tue,etc. ? thanks :smile:

**Comment by shuklaayush** [comment]
I'd say not display it for now until we have a good fix for #1650

**Comment by sudevschiz** [comment]
What's the value add of showing the day of the week? It makes sense when we are showing trends for sales/travel etc. While testing do have a weekend trend, I think showing it in the chart forever would be of much use. Let's not do that.

Closing this issue.
