### ISSUE TITLE
Active reports

### ISSUE THREAD

**Issue by bdsgupta** [covid19india/covid19india.github.io#2105]
There seems to be an issue with the active counts. Firstly it doesn't get displayed for district, state n for the entire country.
It would be great if you could rectify and make sure the active counts are visible for all those who rely on this data

**Comment by shuklaayush** [comment]
Active counts seem to be there for me. Can you be more specific?

**Comment by bdsgupta** [comment]
![PicsArt_06-10-11 12 18](https://user-images.githubusercontent.com/66697631/84231274-67a3cf00-ab0b-11ea-9e36-7ce3a9f25c81.jpg)
![PicsArt_06-10-11 12 57](https://user-images.githubusercontent.com/66697631/84231278-696d9280-ab0b-11ea-9050-297605987a23.jpg)

**Comment by bdsgupta** [comment]
So if you see I can't view the active increase counts.. example for orrisa it shows 110 has increased but it doesn't show the active increase, like how it shiws for recovered or death

**Comment by bdsgupta** [comment]
![Screenshot_20200610-134804__01](https://user-images.githubusercontent.com/66697631/84244488-5665bd00-ab21-11ea-8fbc-13af5220658f.jpg)

**Comment by bdsgupta** [comment]
I hope this has clarified the issue..the increase of recovery and death is showing as 296 and 2 respectively,whereas for active we don't see the increase..

**Comment by shuklaayush** [comment]
Yes, the active deltas were removed since a lot of people seemed to get confused with what the 'Active' counts represented. We've experimented with them a couple of times now, but every time, we're overwhelmed with queries such as why the Active delta has gone negative etc. You can still view them in the time-series graphs at the bottom

**Comment by bdsgupta** [comment]
But honestly that helped alot to understand, especially when we look at our state,district wise.. and the graph that you mentioned below it gives the updates at the end of the day that also for the entire country..
Is there any other way where we can see the active counts..

**Comment by shuklaayush** [comment]
I share the sentiment, but it was a collective decision that we took since the number of queries was getting out of hand. Nothing else really that I can suggest right now, apart from mentally calculating _ΔA = ΔC - ΔR - ΔD_
