### ISSUE TITLE
Demographics | Changing the date is changing the selected state and city.

### ISSUE THREAD

**Issue by sumitbatwani** [covid19india/covid19india.github.io#2106]
**Describe the bug**
While changing the date of filtering demographics data, selected state/city are also changing.

**To Reproduce**

1. Go to 'Demographics'
2. Select a state and city and change the date
3. State/city selected is changing

**Expected behavior**
It should not change the selected state/city

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by sainiajay** [comment]
Would like to contribute a fix for this. Let me know if I can go ahead.
Thanks!

**Comment by sainiajay** [comment]
Hey @sumitbatwani,
I did try reproduce the issue, but I couldn't. State/City isn't getting reset after selecting the date.

**Comment by shuklaayush** [comment]
Seems obsolete now that Demographics has been deprecated
