### ISSUE TITLE
Additional graph of ( Confirmed / Tested ) daily percentage is needed and adds more insight.

### ISSUE THREAD

**Issue by mohanbvk** [covid19india/covid19india.github.io#2107]
Existing graphs are good for getting an idea on the overall situation but I fee there is on key element that needs more attention and is missing.

The primary data related to Confirmed in Red is relative information to the number of tests conducted in a given day, well, the confirmed cases may not always relate to the tests conducted in the same day anyway, the confirmed case on a given day maybe due to the test conducted on the previous day.

However, an additional graph (the only graph in my opinion that makes more sense) of (Confirmed / Tested)% for a given day would give us more insights on the situation like:

- Are there more cases because of more testing?
- Are there less cases even with more testing? (eventual/expected case)
- Cumulative increase / decrease in the percentage

**Comment by archit120** [comment]
Just a nitpick suggestion, it might be good to have a graph that shows daily positive/tested ratio along with a parameter slide to control exponential smoothening similar to tensorboard.

**Comment by bvkmohan** [comment]
Realized it may not 

> Just a nitpick suggestion, it might be good to have a graph that shows daily positive/tested ratio along with a parameter slide to control exponential smoothening similar to tensorboard.

**Comment by bvkmohan** [comment]
Closing

**Comment by mohanbvk** [comment]
Closing because,

Number of active cases in a given day may not reflect due to the number of tests done in that same day, from multiple sources I came to know it usually takes around 4 to 5 days to get the result for a test, so the active cases in a given day X may include lot of results from tests conducted on (X-4) OR (X-5) days.

The proposed feature may not reflect the ground reality, unless it includes an offset for 4 / 5 days, which again may not reflect the truth.
