### ISSUE TITLE
Page for remaining active counts

### ISSUE THREAD

**Issue by ashishgujrathi** [covid19india/covid19india.github.io#2108]
**Is your feature request related to a problem? Please describe.**
Currently not able to check whether active cases are decreasing or not after number of patients recovered and deceased. It just looks like active cases are only increasing not decreasing.

**Describe the solution you'd like**
There should be field or something else which shows remaining active case after deduction the number of recovered and death case. 

**Describe alternatives you've considered**

**Additional context**

There is no way to check how many cases are deducted from active case. 
Remaining active case=active case - recovered - deceased
Can we have separate page for it. If click on active field then a new page should open which shows many cases added and deducted after sum of recovery and deceased.
![Screenshot_2020_0610_075147](https://user-images.githubusercontent.com/13534446/84220536-a37d6b00-aaf0-11ea-9a8a-ff51a4168495.png)

**Comment by shuklaayush** [comment]
I think you're confusing the definitions. Refer to https://github.com/covid19india/covid19india-react/issues/2038#issuecomment-641962963
