### ISSUE TITLE
Drop-down to select a particular date.

### ISSUE THREAD

**Issue by madhusr-github** [covid19india/covid19india.github.io#2111]
**Is your feature request related to a problem? Please describe.**
On the home page to view the stats of a particular day, it is hard to click the dates multiple time to go to the desired day.

![stats](https://user-images.githubusercontent.com/46236472/84261171-f0852f80-ab38-11ea-9ad7-097ba19dcd57.PNG)

**Describe the solution you'd like**
It would be nice to have a drop-down menu to select a particular date instead of just clicking multiple times.

**Additional context**
No Additional context.

**Comment by shuklaayush** [comment]
Duplicates #2026
