### ISSUE TITLE
View nearby essentials not working

### ISSUE THREAD

**Issue by nayakrahul** [covid19india/covid19india.github.io#2113]
**Describe the bug**
View nearby essentials is not working.

**To Reproduce**

1. Go to Essentials
2. Click on View Nearby essentials
3. Nothing comes up

**Expected behavior**
Should work as before

**Screenshots**
![Screenshot (79)](https://user-images.githubusercontent.com/11428805/84318171-9feaf200-ab8b-11ea-835f-e9f4cf878459.png)

**Comment by iamkhush** [comment]
It seems the import from Leaflet is wrong. I will fix this and send a PR

**Comment by shuklaayush** [comment]
Seems obsolete now that Essentials was removed
