### ISSUE TITLE
Overlapping of Phone numbers onto the Map

### ISSUE THREAD

**Issue by draco-malfoy** [covid19india/covid19india.github.io#2116]
**Describe the bug**
When viewing the city/area details through search, the helpline numbers overlap with the map

**To Reproduce**

1. Go to homepage (covid19india.org)
2. Search for 'Hyderabad' in the search box
3. The phone numbers for 'Telangana State Police Department' overlap with map.
(Likewise for any city with phone numbers more than 4-5 would overlap with the map)

**Expected behavior**
Them shouldn't overlap

**Screenshots**
![Capture](https://user-images.githubusercontent.com/46344490/84357463-50d0ab80-abe3-11ea-9fb2-14d9659e7d43.JPG)

**Desktop (please complete the following information):**

- OS: [Windows 7]
- Browser [Chrome]
- Version [80.0.3987.163]

**Comment by draco-malfoy** [comment]
Just realized a similar(on different URL's) [pull request](https://github.com/covid19india/covid19india-react/pull/1995) failed with compilation, although it didn't had any issues adjoined.

**Comment by shuklaayush** [comment]
This should already be fixed. I have a feeling that you might be on an older/cached version of the website

**Comment by draco-malfoy** [comment]
> This should already be fixed. I have a feeling that you might be on an older/cached version of the website

Unfortunately I was
