### ISSUE TITLE
Map explorer and timeseries explorer not getting updated in state page

### ISSUE THREAD

**Issue by nayakrahul** [covid19india/covid19india.github.io#2118]
**Describe the bug**
When you change states using dropdown in state page, map explorer and timeseries explorer does not get updated accordingly. In the gif, you can see that there is no change in map and timeseries.

**To Reproduce**

1. Go to any state page
2. Change to any other state using dropdown
3. Notice that map and timeseries explorer does not get updated. It is same as for the previous state.

**Expected behavior**
They should get updated properly

**Screenshots**
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/11428805/84374249-589c4a00-abfb-11ea-9294-dd300347ecc4.gif)

**Comment by shuklaayush** [comment]
Looks like the routing isn't working

**Comment by nayakrahul** [comment]
> Looks like the routing isn't working

@shuklaayush on the change of statecode, map explorer and timeseries explorer components are not being updated.
