### ISSUE TITLE
Addition issue

### ISSUE THREAD

**Issue by akshar124** [covid19india/covid19india.github.io#2119]
The addition of new cases in india is not true. All the cases have not been totalled correctly **Describe the bug**
A clear and concise description of what the bug is. If your issue is regarding an error in the data, it's best reported through [this form](https://forms.gle/MLeSrdwRuf8AjFkp9).

**To Reproduce**

1. Go to '.covid19india.org..'
3. Scroll down to 'newly reported total cases ...'

**Expected behavior**
The addition should have been precise. It's a simpal mathematical error.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

- Device: lenovo tab7
- OS: android 
- Browser : chrome

**Additional context**

**Comment by shuklaayush** [comment]
Please follow the issue format. Reopen once edited
