### ISSUE TITLE
Graphs showing negative values for active cases

### ISSUE THREAD

**Issue by SarthakJain26** [covid19india/covid19india.github.io#2124]
In 'Spread Trends' section on the home page, graphs of few states are showing negative values for active cases under 'Daily' section. 

I don't think it is a data issue, rather there are some calculation errors.
 
Daily active cases should be calculated by the formula:

daily_active = total_confirmed_till_date - (total_recovered_till_date + total_deaths_till_date)

**Comment by shuklaayush** [comment]
There is no calculation error. Refer to https://github.com/covid19india/covid19india-react/issues/2038#issuecomment-641962963 for the definitions
