### ISSUE TITLE
Can't hover over first bar in bar graphs

### ISSUE THREAD

**Issue by SarthakJain26** [covid19india/covid19india.github.io#2125]
In 'Spread Trends' section, I can't hover over first bar in any of the bar graphs

System specifications : 
- OS: Windows10
- Browser : Chrome
- Version 83.0.4103.97

**Comment by shuklaayush** [comment]
Fixed via 9ef4ca39173a58859996d4d8151a64c385533ca9. Thanks for pointing out!
