### ISSUE TITLE
There is a discrepancy in the confirmed count in the home stats and meta stats.

### ISSUE THREAD

**Issue by deepshikha02** [covid19india/covid19india.github.io#2126]
**Describe the bug**
The number that is shown as the confirmed count is less than the number shown for June 11th. 
There ideally shouldn't be a discrepancy in the number. 
<img width="1233" alt="Screenshot 2020-06-12 at 11 18 51 AM" src="https://user-images.githubusercontent.com/11979108/84469441-b2098500-ac9e-11ea-96f2-12c2fd01df6c.png">
<img width="1233" alt="Screenshot 2020-06-12 at 11 19 01 AM" src="https://user-images.githubusercontent.com/11979108/84469449-b6ce3900-ac9e-11ea-88b2-eefdac0aeb5c.png">

**Comment by shuklaayush** [comment]
Looks like it's because of this
![image](https://user-images.githubusercontent.com/27727946/84475379-141bb780-acaa-11ea-8655-4f97f767c661.png)
