### ISSUE TITLE
One state selected shows data of another state

### ISSUE THREAD

**Issue by devatquarxps** [covid19india/covid19india.github.io#2127]
Steps to reproduce: 
1. go to https://www.covid19india.org/state/KA
2. from dropdown select Bihar
3. State selected is BR but map and partial data is shown for KA.
<img width="1440" alt="Screen Shot 2020-06-12 at 11 28 36 AM" src="https://user-images.githubusercontent.com/31564115/84470312-b20a8480-aca0-11ea-8c51-c78faf6ac03e.png">

**Comment by shuklaayush** [comment]
Duplicates #2118
