### ISSUE TITLE
Data Discrepancy 

### ISSUE THREAD

**Issue by RamithaD** [covid19india/covid19india.github.io#2129]
On 8th and 11th June there is a subtraction of number of cases.(773 and 296 respectively)
But the subtraction is done from both total Unassigned cases  and total confirmed cases (reported  on that particular day) which is not correct.

If you take counts on 8th June ,
Actual total of confirmed cases  : 9309
Confirmed case(Available on the page now) : 8536 ( 9309 - 773)
Total  "Unassigned" on 7th June : 8610
Total "Unassigned" on 8th June  : 7837  ( 8610 -773 )

**Comment by shuklaayush** [comment]
Yes, the total confirmed is just a sum of each of the state's confirmed cases. Since Unassigned is also counted as a state as of now, that's the way to go about it.
