### ISSUE TITLE
Recovered case shown in confirmed case

### ISSUE THREAD

**Issue by godwin-l** [covid19india/covid19india.github.io#2130]
**Recovered case shown in confirmed case**
The confirmed case is shown with down arrow , then it should be considered as recovered, but it was added in confirmed column

**To Reproduce**

1. Just look into the Unassigned state row

**Expected behavior**
The recovered case should be shown in recovered column

**Screenshots**
![Screenshot from 2020-06-12 12-42-25](https://user-images.githubusercontent.com/34455677/84476229-74f7bf80-acab-11ea-8300-cb930754ddf2.png)

**Desktop (please complete the following information):**

- Every OS
- Chrome,Firefox

**Comment by shuklaayush** [comment]
It's a category maintained by [MoHFW](https://www.mohfw.gov.in/). They don't add it to the recovered cases, so neither do we.

![image](https://user-images.githubusercontent.com/27727946/84480058-95c31380-acb1-11ea-9b81-f1f76211d4b4.png)
