### ISSUE TITLE
Past stats for individual states.

### ISSUE THREAD

**Issue by madhusr-github** [covid19india/covid19india.github.io#2131]
**Is your feature request related to a problem? Please describe.**
It would be a great idea to have past stats for each individual state (stats in a particular district on 
a particular day just like we have for whole India.

**Describe the solution you'd like**
Like we select a date and see the stats of each state, we should be able to do the same for districts in a state, we should be able to see the stats of a district on a particular day.

**Additional context**
No Additional context.

**Comment by shuklaayush** [comment]
It's already there. The district statistics are only available from 26th April since that's the day that we started accurately tracking the individual district counts.

![Peek 2020-06-12 13-42](https://user-images.githubusercontent.com/27727946/84480766-b63f9d80-acb2-11ea-8f04-d3b2d0e95598.gif)

**Comment by madhusr-github** [comment]
@shuklaayush sir, I can understand. How can we see the number of cases in a district (for example Mumbai) on a particular day (say Yesterday)?

**Comment by madhusr-github** [comment]
@shuklaayush sorry I didn't see that. And thanks for your time.
