### ISSUE TITLE
The total of new cases does not tally

### ISSUE THREAD

**Issue by Jilyak** [covid19india/covid19india.github.io#2133]
![Screenshot_1](https://user-images.githubusercontent.com/66826102/84490746-3a991d00-acc1-11ea-84c6-30d0ae3b0047.png)
**Describe the bug**
A clear and concise description of what the bug is. If your issue is regarding an error in the data, it's best reported through [this form](https://forms.gle/MLeSrdwRuf8AjFkp9).

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by shuklaayush** [comment]
Please follow the issue template. Reopen this after editing
