### ISSUE TITLE
Incorrect total no of cases

### ISSUE THREAD

**Issue by virajjasani** [covid19india/covid19india.github.io#2135]
**Describe the bug**
Total no of daily cases are incorrect, it is not matching with the addition of all states. Must be today's regression because till yesterday, it was all good.

**Screenshots**
<img width="509" alt="Screen Shot 2020-06-12 at 5 54 18 PM" src="https://user-images.githubusercontent.com/34790606/84502533-24498c00-acd6-11ea-8e87-54d369b3106d.png">

**Comment by ChaoticMarauder** [comment]
I think this has been happening since the last two days, but the numbers get corrected by 10-11 pm

**Comment by shuklaayush** [comment]
I hope you're accounting for the decrease in unassigned cases. The chances of the total not tallying are extremely low since there are no manual calculations involved in the process.

![image](https://user-images.githubusercontent.com/27727946/84508675-49db9300-ace0-11ea-8148-a1ece5542a66.png)

**Comment by virajjasani** [comment]
Oh, my bad. Now I realized that Unassigned has negative value. But this somehow doesn't look good: If there is decrease in no of cases, it should be part of Recovered column.
Thought?

**Comment by shuklaayush** [comment]
We're following [MoHFW](https://www.mohfw.gov.in/) on this. They don't add it to the recovered cases, so neither do we.

![image](https://user-images.githubusercontent.com/27727946/84513780-96769c80-ace7-11ea-8602-850c3889c1a6.png)
