### ISSUE TITLE
The font of drop down menu above trend charts need to be fixed.

### ISSUE THREAD

**Issue by mohilkhare1708** [covid19india/covid19india.github.io#2137]
**Describe the bug**
The drop-down menu which is used to show state-wise active/recovered/deceased charts has a different font from the site theme.

**To Reproduce**

1. Go to home page of the website.
2. Click on drop-down menu of states
3. See error

**Expected behavior**
Font should match with that of the website and menu shouldn't have thin white border.

**Screenshots**
![Screenshot (198)](https://user-images.githubusercontent.com/22223027/84561623-9ae49900-ad6b-11ea-8fd3-9ca7d8f54410.png)

**Desktop:**

- OS: Windows 10 Home
- Browser Firefox
- Version 77.0.1

**Comment by shuklaayush** [comment]
This is probably a browser issue. /available

**Comment by navkumar258** [comment]
Hi, tried to take it up but after some debugging found out that both have font-family of 'archia', font-weights are different though. Any suggestions/comments would be helpful. thanks !

**Comment by mohilkhare1708** [comment]
> 
> 
> Hi, tried to take it up but after some debugging found out that both have font-family of 'archia', font-weights are different though. Any suggestions/comments would be helpful. thanks !

This seems like a browser based issue, I'm trying to find a workaround for it.
