### ISSUE TITLE
Recognize all contributors

### ISSUE THREAD

**Issue by dakshshah96** [covid19india/covid19india.github.io#214]
**Is your feature request related to a problem? Please describe.**
There are a ton of amazing people working on this project and it's only fair to recognize the efforts of each and every one of them.

**Describe the solution you'd like**
I propose to use the awesome [All Contributors](https://allcontributors.org/) to automagically manage a table of all contributors in the project README.

**Comment by JunaidBabu** [comment]
@dakshshah96 thank you for raising this. Could you help with this?

**Comment by dakshshah96** [comment]
> @dakshshah96 thank you for raising this. Could you help with this?

Would love to help! Don't have the necessary permissions for installing the bot though.

**Comment by JunaidBabu** [comment]
Will do this later. Closing for now.
