### ISSUE TITLE
Add Number of tests done in the view

### ISSUE THREAD

**Issue by hariharapanigrahy** [covid19india/covid19india.github.io#2146]
The result only shows the cases confirmed, active, recovered, deceased. But if we add column of number of tests done it will reduce the panic of the people and give more visibility into the result. 

So, can we add number of tests done into the view?

**Comment by shuklaayush** [comment]
The reason it's not there on the table, for now, is because we don't have district-level data for samples tested. So, for the district rows, this column would essentially be empty.

> ..reduce the panic of the people...

I'm curious about this though. Why do you feel that it'll reduce panic among people? What's the rationale here?

**Comment by Abhilash24** [comment]
@shuklaayush when we display the testing data in the card view, people will have more faith in the medical infrastructure of the state. Testing figures are showing in https://covid19japan.com dashboard too.

**Comment by shuklaayush** [comment]
@Abhilash24 There's just not enough space at the top. We've added it next to the map for now
