### ISSUE TITLE
Banner chart showing downward trend when day starts

### ISSUE THREAD

**Issue by manigandan-dorairaj** [covid19india/covid19india.github.io#215]
When the day starts, the banner charts are showing downward trend

**To Reproduce**
Check when the day starts
![image](https://user-images.githubusercontent.com/53426835/77721681-8c5ecf00-7011-11ea-992c-9016919b5409.png)

**Expected behavior**
The end point of the graph should stay as it was when the day ends and continue to update only when new cases gets added.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version74

**Comment by jeremyphilemon** [comment]
Patched! Thank you for reporting :)
