### ISSUE TITLE
Selecting "Lakshadweep" shows graphs with no data

### ISSUE THREAD

**Issue by praty94** [covid19india/covid19india.github.io#2154]
**Description**
Selecting State option which does not have any data is showing confirmed,active,recovered and deceased graphs with empty data.

**To Reproduce**

1. Go to Home Page > "Spread Trends" (section)
2. Select "Lakshadweep" from state selector drop down

**Expected behavior**
If data is not available for a particular state , it should show message which clearly describes the case to the user instead of showing graphs with no data .

**Screenshots**

![SharedScreenshot](https://user-images.githubusercontent.com/8337749/84699779-c3d57b80-af6f-11ea-9980-c10448306336.jpg)

**Comment by nithincspnr** [comment]
Let me /claim this issue
