### ISSUE TITLE
Change in States and Cities name for mobile devices

### ISSUE THREAD

**Issue by maheshwarimrinal** [covid19india/covid19india.github.io#2155]
**Is your feature request related to a problem? Please describe.**
If we view website in mobile device the **STATE/UT** column is way too much in width and because of that the **Deceased** moves more towards right.

**Describe the solution you'd like**
It would be great if **States and Union Territories** will be shown as for example Rajasthan as RJ, Delhi as DL and so on which can be a better approach.

**Comment by varungupta3009** [comment]
This is exactly what I was going to suggest. Having the shorter state codes rather than the entire state name would be a much better choice. The table feels really fidgety on shorter width devices.

**Comment by naveensaigit** [comment]
But the table now has a horizontal scroll bar, so it should be fine right? Unless you want to view all columns at once.

**Comment by maheshwarimrinal** [comment]
If user is getting option to view directly that would be better instead of scrolling.

**Comment by sudevschiz** [comment]
Using the scroll to get more information is the preferred approach. We will be adding more columns to the table soon like recovery percentage etc. So, scrolling is inevitable. 

Also, codes won't work well for district names. Let's stick with the full name.
