### ISSUE TITLE
two nav icons are getting highlighted on about page

### ISSUE THREAD

**Issue by Binu42** [covid19india/covid19india.github.io#2156]
**Describe the bug**
when user click on about page two nav icons are highlighted.
![Screenshot from 2020-06-16 22-06-06](https://user-images.githubusercontent.com/45959932/84802181-d908e380-b01d-11ea-83d4-8d5a29be03e4.png)

**To Reproduce**

1. Go to [here](https://www.covid19india.org/about) you will able to see it..

**Expected behavior**
only about icons should be highlighted.

**Screenshots**

**Desktop (please complete the following information):**
common issue not depend on systems.

**Comment by navkumar258** [comment]
Hi, i am looking for my first contribution.
I found the problem: In navbar.js line:126, replace '/about' with '/blog'. compiled and running as expected in my local machine. 
Hope it helps. 😃

**Comment by Binu42** [comment]
i've already fixed this issued in PR #2157. it's not merged yet
