### ISSUE TITLE
Extra comma appearing in spread trends charts

### ISSUE THREAD

**Issue by bogdanvaduva9** [covid19india/covid19india.github.io#2159]
**Describe the bug**
When the number of gets over 100k (100.000), an extra comma appears in the labels of the charts. I have attached a screenshot to showcase this bug.

**To Reproduce**

1. Go to https://www.covid19india.org/
2. Scroll until you can see "Spread trends" on the right side of the screen.
3. Select a province with more than 100.000 cases
4. Hover the mouse cursor over the charts and go to a date that has more than 100.000 cases.
5. See the extra comma that appears.

**Expected behavior**
The comma should not be there. Instead of 1,00,000 it should be 100,000

**Screenshots**
![image](https://user-images.githubusercontent.com/20244559/84887875-12cdfe80-b09f-11ea-8c28-73c55d4319c0.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser : chrome
- Version : latest

**Comment by bee-rickey** [comment]
We have decided to follow imperial system here. Hence the extra comma.

**Comment by bogdanvaduva9** [comment]
Fair enough, but there is still an extra comma there.
You have 1,00,000 when it should be
100,000
Still follows the imperial system. Or am I missing something here?

**Comment by nayakrahul** [comment]
@bogdanvaduva9 Actually we have followed the use of comma according to Indian numbering system.
https://en.m.wikipedia.org/wiki/Indian_numbering_system

**Comment by bogdanvaduva9** [comment]
Oh, okay, now that makes more sense. 
Thanks a lot for the response. 
You learn something new everyday.
