### ISSUE TITLE
Scaling of Deceased Graph

### ISSUE THREAD

**Issue by harsshjain** [covid19india/covid19india.github.io#2165]
The deceased graph below the main table on the home page does not wake up from Flat line irrespective of the increase in death rate. Can it be scaled appropriately?

**Comment by harsshjain** [comment]
![IMG_20200627_104412](https://user-images.githubusercontent.com/65491327/85915252-67be0180-b863-11ea-8c73-155028e046a4.jpg)

**Comment by shuklaayush** [comment]
Fixed via b34cd938e06942688cde6756dac1c76b23e19c4b
