### ISSUE TITLE
Including predictions along with historic data

### ISSUE THREAD

**Issue by mayankbhagya** [covid19india/covid19india.github.io#2166]
**Is your feature request related to a problem? Please describe.**
Historic data looks perfect. But it'd be useful to know what can be expected in another week. Or month. Policymakers can make much better decisions and plan resource allocation accordingly.

**Describe the solution you'd like**
Simply allow the user to pick a future date just as one can pick historic dates today. The UI, charts and map will show predictions. Disclaimers included, of course.

We've been successfully able to train a deep learning model based on https://arxiv.org/abs/2005.04809 and request the team to take a look and evaluate integration. It would be as simple as hosting yet another json in the covid-api project.

**Describe alternatives you've considered**
Any other alternative ways to present the data can be discussed.

**Additional context**
Implementaiton and integration here: https://bit.ly/2UZTYCR
![sevaml](https://user-images.githubusercontent.com/557860/85100106-e3dd9700-b21c-11ea-9c72-1ff7ec0c6682.png)

**Comment by shuklaayush** [comment]
Can you share the backtesting results of the model?

**Comment by mayankbhagya** [comment]
Sure @shuklaayush 
You can find some some predictions listed [here](https://indiacovid.seva.ml/2020/06/04/20-day-forecaster.html?utm_source=ci&utm_medium=gh&utm_campaign=tr). MAPE turns out ~8%.
All code is open source and available in our repo.

Our model is WIP and is still a univariate model that predicts daily confirmed cases. There are some issues in the integration too. We are always short of devs.

The idea is to get to a multivariate model where we can predict variabes like confirmed, recovered and deceased cases simultaneously, bundle a json and deliver every few days. Currently, it takes about 2 days to train the univariate model and hence the TAT is high. We're working on improving both the TAT and accuracy currently.

But provided the quality of our results is satisfactory, would you guys be open to integrating these predictions?

**Comment by shuklaayush** [comment]
I think this was discussed on Telegram. Including predictions on the website is probably not a good option
