### ISSUE TITLE
Website crashes for dates below 26-Apr if district table(s) are open

### ISSUE THREAD

**Issue by naveensaigit** [covid19india/covid19india.github.io#2167]
**Describe the bug**
Website crashes for dates below 26-Apr if district table(s) are open

**To Reproduce**

1. Go to https://www.covid19india.org
2. Click on any state and leave the district table open
3. Now click on rewind button and go to Apr 25
4. The website crashes 

**Expected behavior**
This is probably because district level data is not available before 25-Apr. A message that district level data is not available before 25th Apr would suffice

**Screenshots**
![Coronavirus-Outbreak-in-India-co](https://user-images.githubusercontent.com/56525288/85123757-72b2d980-b246-11ea-94f4-fd69f013e64d.GIF)

**Desktop (please complete the following information):**

- OS: Windows
- Browser Chome
- Version 83.0.4103.106

**Additional context**
 Although there is very less chance that someone goes this far, its better to fix this. Note that the website doesn't crash if all of the states' rows are collapsed

**Comment by abbhhiisseek** [comment]
it's happening in Andriod too

**Comment by w3dg** [comment]
The website doesnt crash for me but this happpens .

![image](https://user-images.githubusercontent.com/51162936/86153621-96680080-bb1f-11ea-9c88-fe8bde9df0e2.png)

and on 25th Apr onwards the map goes blank and again the same error is fired.

![image](https://user-images.githubusercontent.com/51162936/86153799-cc0ce980-bb1f-11ea-8efb-fe8b8d30dbf0.png)

**Comment by w3dg** [comment]
maybe its a api issue , like not getting data from the locales json?

**Comment by naveensaigit** [comment]
I think its fixed now, not sure why it was crashing a few days back

**Comment by w3dg** [comment]
i think this issue should be renamed to like cant get data below 26 apr and map goes blank or something as that is what is happening

**Comment by shuklaayush** [comment]
Yeah, there's no district-wise data before 26th April. I guess we could make that explicit somewhere. Anyways, I'm closing this
