### ISSUE TITLE
Text is not localized for multiple pages other then main page UI.

### ISSUE THREAD

**Issue by maheshchinna** [covid19india/covid19india.github.io#2168]
**Issue:**
Text is not localized for multiple pages other then main page UI.
**Expected Result:** 
When user selects tje language then all the UI pages text should display in the appropriate langauage.
**Actual Result:**
Text is appearing in EN for NON-EN selected languages also like Hindi, Telugu..

**Please find the attached issue screenshots for reference.**

![image](https://user-images.githubusercontent.com/52688733/85132574-ac8bdc00-b256-11ea-9f25-6ef963088052.png)

![image](https://user-images.githubusercontent.com/52688733/85132032-a1847c00-b255-11ea-8900-8fc7807bfd98.png)

![image](https://user-images.githubusercontent.com/52688733/85132390-50c15300-b256-11ea-8aca-bbfddfc41464.png)

![image](https://user-images.githubusercontent.com/52688733/85132452-7189a880-b256-11ea-944a-6e0c5e9e4c4f.png)

**Comment by shuklaayush** [comment]
Duplicates #2254
