### ISSUE TITLE
Daily Spread Trends not reflecting Current Date 

### ISSUE THREAD

**Issue by 23f2005514** [covid19india/covid19india.github.io#217]
The Daily spread trends is expected to reflect the current date's situation. The same is not reflected
1. Go to Spread Trends.
2. Click on Daily
3. The Data for 26 Mar 2020 is only reflected and not 27 Mar 2020.

The Data for 27 Mar 2020 needs to be reflected.

![image](https://user-images.githubusercontent.com/32433336/77727840-2da15180-7021-11ea-8d21-85e429dd5d4f.png)

**Comment by JunaidBabu** [comment]
This is by design. Daily delta can be seen on top anyway.
