### ISSUE TITLE
No Data on Essentials Page and OnBackTransition Not Working 

### ISSUE THREAD

**Issue by Anshul1507** [covid19india/covid19india.github.io#2170]
**Describe the bug**
No Data is showing on [Essentials](https://www.covid19india.org/essentials) after given the location access and after that if we press back then also no data is showing on [Home Page](https://www.covid19india.org/) unless i refresh that.

**To Reproduce**

1. Go to https://www.covid19india.org/essentials
2. Click on 'View Nearby Essentials'
3. Blank White Screen comes out.

**Expected behavior**
As this screen is not visible, i didn't expect the actual behaviour.

**Screenshots**
Essentials Page
![Essentials Page](https://user-images.githubusercontent.com/38963667/85156215-61ce8c00-b277-11ea-98b2-71d2cafe4f7c.png)
OnBackPress to HomePage from Essentials Page
![OnBackPress to HomePage from Essentials Page](https://user-images.githubusercontent.com/38963667/85156372-9cd0bf80-b277-11ea-98cd-30ed82fac721.png)
[Video](https://drive.google.com/file/d/1Nljg3HnKFqJ4_yRzEh9ityPoyMHmHpXp/view?usp=sharing)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser Chrome
- Version 83.0.4103.106 (Official Build) (64-bit)

**Additional context**
I think this white screen may comes due to no essentials present nearby my location.

**Comment by iiaishwarya** [comment]
Possible duplicate of [https://github.com/covid19india/covid19india-react/issues/2113](url)

**Comment by Anshul1507** [comment]
yep 👍 , and back button also showing blank screen, check that also.
