### ISSUE TITLE
Statewise testing graph broken

### ISSUE THREAD

**Issue by abhijeetviswam** [covid19india/covid19india.github.io#2171]
**Describe the bug**
State specific testing count graph is not working

**To Reproduce**

1. Scroll down tk graphs in the landing page
2. Select any state eg : Maharashtra from the dropdown
3. Tested graph is not plotted

**Expected behavior**
Tested graph should be plotted correctly

**Screenshots**
![Screenshot_20200619-230619__01](https://user-images.githubusercontent.com/42885985/85164914-a6abf000-b282-11ea-80b2-6be9650a8897.jpg)

**Desktop (please complete the following information):**
NA. Tested on Phone

**Smartphone (please complete the following information):**

- OnePlus 3T android 9 pie
- Google Chrome 81.0.4044.138

**Additional context**
NA

**Comment by shuklaayush** [comment]
Looks like this was temporary
