### ISSUE TITLE
Language switcher not visible when user scrolls down the page and clicks the language in the nav bar

### ISSUE THREAD

**Issue by praty94** [covid19india/covid19india.github.io#2172]
**Describe the bug**
When user scrolls down a bit on any page and then clicks on the language switch button on the navbar , the language switcher either shows up partially or not at all (out of view) , user needs to manually scroll up to see the language switcher. 
[New users might not even recognize that the language switcher is there in the top of the page]

**To Reproduce**

1. Go to any page which is scrollable (has height more than the viewable area in the screen)
2. Scroll down a few times
3. Click on language switch button on the nav bar 
4. The language switcher comes up but is out of view of the user

**Expected behavior**
Whenever language switcher is shown , the window should be scrolled up , so that it is clearly visible . 

**Screenshots**
![final](https://user-images.githubusercontent.com/8337749/85171937-a36a3180-b28d-11ea-824b-be3f55825eb5.gif)

Should be reproducible in all devices.

**Comment by praty94** [comment]
I would like to /claim this issue

**Comment by praty94** [comment]
Let me /claim this issue

**Comment by navkumar258** [comment]
Hi team, found the issue and tried something.
**CHANGES**: In navbar.js, after Line#70, added: window.scrollTo(0, 0); to the navbar-left class onClick event handler.
Working as expected in my local machine, please check & update. Thanks 😄

**Comment by navkumar258** [comment]
@shuklaayush Looking for my first contribution, please help in creating a pull request, would like to merge my changes into the master.

**CHANGES:** https://github.com/covid19india/covid19india-react/issues/2172#issuecomment-650068625

**Comment by shuklaayush** [comment]
Hi @navkumar258, you need to fork the repository and push a commit to your fork before creating a PR. Although it seems like there are already pending PRs which fix this

**Comment by navkumar258** [comment]
@shuklaayush thanks for the quick response....will continue to watch the repository and fork if necessary.
@sudevschiz seems like there are already a pending PR for fixing this issue, don't want to duplicate.

**Comment by shuklaayush** [comment]
Fixed via #2220
