### ISSUE TITLE
Numbers in Incorrect Format

### ISSUE THREAD

**Issue by erin-cho** [covid19india/covid19india.github.io#2175]
**Describe the bug**
Numbers in the hundred thousands do not show up in proper format. For instance, Maharashtra's confirmed cases show up as 1,28,205 when it should be 128,205 (as seen in the screenshots below). All numbers show up in this incorrect format. This is confusing as you're left wondering if the numbers should be in the hundred thousands or in the millions. 

**Screenshots**
<img width="556" alt="Screen Shot 2020-06-20 at 8 41 10 PM" src="https://user-images.githubusercontent.com/64560658/85214251-7a51ab80-b336-11ea-8ae1-ea14fdd6deb6.png">

<img width="587" alt="Screen Shot 2020-06-20 at 8 36 54 PM" src="https://user-images.githubusercontent.com/64560658/85214180-e089fe80-b335-11ea-89b7-a0f7f63449eb.png">

<img width="497" alt="Screen Shot 2020-06-20 at 8 36 12 PM" src="https://user-images.githubusercontent.com/64560658/85214168-cd772e80-b335-11ea-9c68-c22432e920d8.png">

**Desktop (please complete the following information):**

- OS: MacOS
- Version: 10.14.6
- Browser: Chrome

**Comment by nayakrahul** [comment]
@erin-cho Actually we have followed the use of comma according to Indian numbering system.
https://en.m.wikipedia.org/wiki/Indian_numbering_system
