### ISSUE TITLE
Covid Visit Schedule

### ISSUE THREAD

**Issue by shubhparekh** [covid19india/covid19india.github.io#2176]
**Is your feature request related to a problem? Please describe.**
Currently there is no proper schedule which people follow while going out for buying essentials which leads to crowd.

**Describe the solution you'd like**
Suggest a unique hour (from 8 AM to 6 PM) to people based on there GPS location when they can plan outside visit on daily basis **whenever possible**. The unique hour provided to users varies at every few kilometre. Due to this multiple visits in a day will reduce as people will plan ahead of time. 

If we consider earth as a grid of latitudes and longitudes. Then the slot provided to a user will be unique in a certain range of latitude and longitude. The slot will vary for a different user staying in a lat, long box some kilometres away from first user in any direction. In this way the algorithm is able to assign all users of a city to a time slot from 8 AM in morning to 6 PM in evening. The algorithm gives a different slot everyday to a user, as a result everyone gets a slot they like and the one they don’t like.

The algorithm evenly distributes the number of people stepping out of their house throughout the day. By following this outside visits are synchronised with others to reduce crowd. The location information of user is not stored only used for computing slot.

**Describe alternatives you've considered**

**Additional context**
We have already implemented it at https://covid19quarantine.in/suggest-time. But due to lesser popularity of our site its not used. Do let me know if it will be a valuable addition to covid19india.org.

Below each colour shows different time people are suggested to travel throughout day.

![Screenshot from 2020-06-29 22-40-04](https://user-images.githubusercontent.com/9915960/86036289-44f63d80-ba5b-11ea-9cdb-c5adf426ffa8.png)
![Screenshot from 2020-06-29 22-38-57](https://user-images.githubusercontent.com/9915960/86036310-4aec1e80-ba5b-11ea-97af-1d9298b7e2e5.png)
![Chennai](https://user-images.githubusercontent.com/9915960/86036352-59d2d100-ba5b-11ea-93ec-cb302f4614ae.png)

**Comment by shubhparekh** [comment]
@jeremyphilemon Please can someone review this.

**Comment by shubhparekh** [comment]
added screenshots

**Comment by shuklaayush** [comment]
I think this is out of the scope of covid19india.org website. We can reopen this if something thinks otherwise
