### ISSUE TITLE
Unnecessary Navbar rerendering on URL change

### ISSUE THREAD

**Issue by abhishekakade** [covid19india/covid19india.github.io#2177]
**Describe the bug**
`Navbar` component rerenders on every URL change.

**To Reproduce**
1. Select slow 3G from network throttles
2. Visit all the components like Demographics, About, Essentials, etc.
3. Notice the Navbar rerendering on each initial URL change.

**Expected behavior**
Navbar does not rerender with every URL change/other components.

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Chrome 
- Version: 83.0.4103.106 (Official Build) (64-bit)

**Comment by shuklaayush** [comment]
Looks like it's already fixed
