### ISSUE TITLE
UI: Unnecessary scrollbar appears when cursor moved on to Meghalaya's info icon

### ISSUE THREAD

**Issue by harnirvair** [covid19india/covid19india.github.io#2179]
**Describe the bug**
When moving the cursor on the Meghalaya info, an unnecessary scrollbar appears.

**To Reproduce**
Steps to reproduce the behaviour:
1. Scroll down to Meghalaya state 
2. Move cursor on 'i' icon
3. Scrollbar appears on moving the cursor

![ezgif-3-96efd2932c3f](https://user-images.githubusercontent.com/13620254/85224367-982b1900-b3e7-11ea-92b5-07917e889c27.gif)

**Expected behaviour**
The scrollbar should not appear just like other states above.

**Desktop:**

- OS [Windows 10]
- Browser [Chrome 83.0.4103.106]

Additional Info:
All states with information appearing at the bottom of the table show a similar bug.

**Comment by shuklaayush** [comment]
/available Try to fix this without removing `overflow-x: auto`

**Comment by khpatel8** [comment]
cant seem to reproduce the issue. looks like it has been fixed.

**Comment by shuklaayush** [comment]
Sort by Confirmed ascending and hover over Maharashtra info icon

**Comment by rahulmr123** [comment]
@shuklaayush Just checked now it's because of the info popup the scroll bar is appearing.
instead of giving `overflow-x: auto`, we can give `overflow: auto` to the table container to fix the vertical overflow issue.
I would like to work on this issue.

**Comment by rahulmr123** [comment]
@shuklaayush I would like to work on this.
