### ISSUE TITLE
The count under confirmed cases shows -8 in spread Trends

### ISSUE THREAD

**Issue by 23f2005514** [covid19india/covid19india.github.io#218]
The increase in confirmed cases needs to be reflected as "+num"

1. Go to Spread Trends
2. Click on Daily Trends
3. The confirmed cases shows "78-8"

It should show "+num".

![image](https://user-images.githubusercontent.com/32433336/77728071-b91ae280-7021-11ea-807d-9190c3762942.png)

**Comment by shuklaayush** [comment]
I don't think this is a bug. The new cases earlier were 86 and the next they reduced to 78. Hence, -8.

**Comment by rebelgiri** [comment]
Is it really a bug?

**Comment by JunaidBabu** [comment]
Not bug.
