### ISSUE TITLE
Rate of positive test results

### ISSUE THREAD

**Issue by akumar90** [covid19india/covid19india.github.io#2182]
**Is your feature request related to a problem? Please describe.**
Have a clear understanding on whether the increased number of cases is because of increased testing Vs. increased spread. As per WHO guidelines, if a positive test rate is greater than 10%, the country is not doing enough testing.

**Describe the solution you'd like**
Understanding what the trend of rate of positive tests has been overtime.

**Describe alternatives you've considered**
N/A

**Additional context**
Having a graph similar to the active graph would be great. I am imagining the rate to be calculated as (number of positive results/number of tests)%

**Also working on creating something for rate of transmission of the disease. Will create a new feature ticket once I have requirements flushed out.

**Comment by rtkg12** [comment]
I think this will be a good metric to add too and I'm interested in working on this.

**Comment by agrahajigyasu** [comment]
This feature will be really helpful and will help people to judge which state is ahead in testing. Very interested to work on this feature

**Comment by akumar90** [comment]
In addition to the positivity rate, creating a view for Rt (i.e. rate of transfer) would also be helpful.
I have taken the liberty of writing the code for these functionality (in Python though). Hopefully someone can re-use this code to be implemented as part of React.

Check **data_processing.ipynb**

[covid.zip](https://github.com/covid19india/covid19india-react/files/4880629/covid.zip)
