### ISSUE TITLE
Make the death graph on the main screen decreasing the unit of y-axis by factor of 10 so that daily changes donot look like a straight line.

### ISSUE THREAD

**Issue by negimohit1209** [covid19india/covid19india.github.io#2183]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by shuklaayush** [comment]
We're not a fan of hardcoded values like '10 times', but let's see if we can make it more useful
