### ISSUE TITLE
To have country level stats same as the current state level stats

### ISSUE THREAD

**Issue by sourabhbagrecha** [covid19india/covid19india.github.io#2184]
**Is your feature request related to a problem? Please describe.**
This is just an additional feature so that we can have country-level statistics on the main page itself same as we are currently showing in the corresponding state page

**Describe the solution you'd like**
To have a country level stats section on the main page like below:
![image](https://user-images.githubusercontent.com/27056663/85504905-a7d67780-b60a-11ea-9f56-4a95ada43510.png)

**Comment by Swayam-dell** [comment]
This is a very useful feature. Can I contribute by adding this feature.

**Comment by sourabhbagrecha** [comment]
I think @shuklaayush  already started working on it. Please coordinate before starting @Swayam-dell .

**Comment by shuklaayush** [comment]
Fixed via #2278
