### ISSUE TITLE
Active cases shows as negative at district level

### ISSUE THREAD

**Issue by atmakur** [covid19india/covid19india.github.io#2186]
**Describe the bug**
The active cases on Unknown and Other State at district levels show as a negative number. Due to this, the actual total count changes.

**To Reproduce**

1. Go to covid19india.org
2. Expand the states (Tamil Nadu, Telangana, Assam, Kerala, Goa, Manipur, Nagaland, Sikkim, Meghalaya)
3. Sort by Active cases
4. Scroll to the end of the state. The last row for some states shows negative numbers.

**Expected behavior**
How can active cases by a negative? All numbers here should be positive except the change in count.

**Screenshots**
![image](https://user-images.githubusercontent.com/25097239/85576302-e9145a80-b5fd-11ea-9566-e24717a3969d.png)

**Desktop (please complete the following information):**
- OS: Windows
- Browser - chrome

**Comment by alexcat3** [comment]
I am confused about the steps needed to reproduce this bug-- I cannot find the screen you are viewing. Could you provide more detail about reproduction?

**Comment by alexcat3** [comment]
Never mind, I'm stupid. I see it now.

**Comment by shuklaayush** [comment]
Refer to #1951
