### ISSUE TITLE
Can you add 7 day average of daily count to the graphs? 

### ISSUE THREAD

**Issue by bharathEF** [covid19india/covid19india.github.io#2188]
This graph will help us identify the trend of increase or decrease of the active cases. This average is better than daily decrease or increase.

**Comment by aseemgautam** [comment]
I agree. For now there is another tracker which is doing this. https://covidtracking.in. You can find 7 & 14 day trends here.

**Comment by Kacppian** [comment]
Can I pick this up?

**Comment by Swayam-dell** [comment]
Hi, I have been following this website for a long time. and find myself suitable to add this useful feature.

**Comment by artorias111** [comment]
Hey, I want to contribute to my first open source project, can I take this up if it's not taken?
