### ISSUE TITLE
Leh and Kargil Locations on the Map are in correct

### ISSUE THREAD

**Issue by MahekMody** [covid19india/covid19india.github.io#2189]
**Describe the bug**
The hotspot map as location of different cities on the Map. the location of Leh and Kargil on it are incorrect.

**To Reproduce**
Hotstops map on the main page

**Expected behavior**
Actual Location
![image](https://user-images.githubusercontent.com/9478442/85827262-9379b280-b7a3-11ea-9164-aa76e99bb2df.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/9478442/85827233-7cd35b80-b7a3-11ea-9eb6-444709fd9087.png)

**Desktop (please complete the following information):**

Browser Chorome

**Smartphone (please complete the following information):**

OS - Windows 10

**Additional context**

**Comment by shuklaayush** [comment]
The centre of the circle is the centroid of the Leh and Kargil **districts**. _Hotspots_ is not the most appropriate term. We're planning to change that. Hopefully, that answers it
