### ISSUE TITLE
State-wise spread trends 

### ISSUE THREAD

**Issue by namahtuog** [covid19india/covid19india.github.io#219]
The states in India have become pretty much isolated from each other, post lockdown - essentially making them different communities/entities combating Covid-19. Also different states are deploying different strategies and measures in combating Covid - like intensity of testing, quarantine, patient contact tracking etc.

Hence, the countrywide "SPREAD TRENDS" chart doesn't give a meaningful indication of the spread of Covid-19 or the effectiveness of mitigation measures anymore.

So It'll be great if we can also generate this "SPREAD TRENDS" chart for each individual states, as they form separate entities now, since the lockdown.

**Comment by sudevschiz** [comment]
@mohammedshafeeqet 
Need statewise cases time series for plotting this. 

A Google script to compute the Confirmed, Recovered, Deceased, Active values for all states at 00:01 hours should do the trick?

**Comment by parthpatel1470** [comment]
Can we do a thing as when we hover to a state it shows most affect city in that state??
It could possible spread more awareness among for where not to go in this situation

**Comment by sachingargtech** [comment]
Here is an example current state-wise charts, with wide difference in trends across states. Will be really great if we have updated state-wise charts here on this site.

https://www.thehindu.com/data/covid-19-state-wise-tracker-for-coronavirus-cases-deaths-and-testing-rates/article31248444.ece?homepage=true

**Comment by jeremyphilemon** [comment]
Closing this since #80 was raised.
