### ISSUE TITLE
Strings overlapping in Chart

### ISSUE THREAD

**Issue by harsshjain** [covid19india/covid19india.github.io#2191]
**Describe the bug**
Strings overlapping as per screenshot attached.

**To Reproduce**

1. Go to covid19india.org
2. Scroll down to Spread Trends
3. See error

**Expected behavior**
String Overlapping on chart

**Screenshots**
![IMG_20200627_104127](https://user-images.githubusercontent.com/65491327/85915341-3b56b500-b864-11ea-9d42-40692128df3d.jpg)

![IMG_20200627_104137](https://user-images.githubusercontent.com/65491327/85915343-3db90f00-b864-11ea-8a42-627b44d6f68c.jpg)

**Comment by shuklaayush** [comment]
Duplicates #1650
