### ISSUE TITLE
Covid19India website not working on Apple SE, iOS 11.2, Safari Browser

### ISSUE THREAD

**Issue by saurav-mbe** [covid19india/covid19india.github.io#2192]
**Describe the bug**
covid19india.org displays an empty white sheet on iOS 11.2 Safari browser.

**To Reproduce**

1. Go to the stock safari browser
2. Type the website link and load
3. It displays an empty sheet.

**Expected behavior**
It should work on the safari browser on Iphone.

**Smartphone (please complete the following information):**

- Device: [iPhoneSE]
- OS: [iOS11.1.1]
- Browser [ stock browser, safari]

**Additional context**
It was working previously , suddenly it has stopped to work on Safari browser , iOS 11.2 since the last two weeks.

**Comment by shuklaayush** [comment]
Any chance you have a log?

**Comment by saurav-mbe** [comment]
Yes, this is how the logs look - 
![image](https://user-images.githubusercontent.com/5649706/85946896-2ada3380-b965-11ea-8fc8-cee35cfb12e8.png)

It was working earlier and it is still working for iOS 12.1 and above. I found this link which might be explain the reason.
https://github.com/mhartington/lazy-load-image/issues/1

**Comment by Rohithgilla12** [comment]
<img width="1440" alt="Screenshot 2020-06-30 at 8 37 28 PM" src="https://user-images.githubusercontent.com/19389850/86143119-a7117a00-bb11-11ea-8d6c-792664c78b7f.png">
It seems to be working fine.

**Comment by av1v3k** [comment]
Yes, it is not working in Safari Browser.

Safari Version: 12
Device: Macbook Pro

![image](https://user-images.githubusercontent.com/1721339/86332620-64ae8100-bc68-11ea-8444-41ce8e673265.png)
