### ISSUE TITLE
Essentials woman pushing cart is misalgined

### ISSUE THREAD

**Issue by datmemerboi** [covid19india/covid19india.github.io#2195]
**Description**
While loading *essentials* on desktop, **Essentials woman pushing cart** is positioned **away from the platform**. They are to be placed over one another. It is better to group them into one div.
**THIS BUG ISN'T PRESENT ON SMARTPHONE VIEWS**

**Steps to Reproduce**
1. Go to https://www.covid19india.org/essentials
2. Once the page loads, you'll see the misalignment

**Expected behavior**
The **lady pushing cart** must land / lie on **the platform**

**Screenshots**
![image](https://user-images.githubusercontent.com/34474140/86148072-c9a69180-bb17-11ea-8a46-426922564e0d.png)

**Desktop**

- OS: elementaryOS
- Browser: Chrome

**THIS BUG ISN'T PRESENT ON SMARTPHONE VIEWS**

**Comment by w3dg** [comment]
@datmemerboi its all in line for me 

![image](https://user-images.githubusercontent.com/51162936/86210055-82f57d80-bb91-11ea-8222-ba5d9cd755ce.png)

**Comment by navkumar258** [comment]
@shuklaayush seems like the issue is fixed, not able to reproduce in any of the screens - mobile/desktop. thanks :smile:

**Comment by shuklaayush** [comment]
Also obsolete now that Essentials has been deprecated
