### ISSUE TITLE
Current day cases count for all the states is not accurate

### ISSUE THREAD

**Issue by purveshmakode24** [covid19india/covid19india.github.io#2196]
Current day cases count for all the states doesn't give the right summation for what is shown in the total count cases.

**Comment by shuklaayush** [comment]
Looks good to me. Can you a breakdown of your calculation?

**Comment by purveshmakode24** [comment]
Consider 30th June cases,
When you add up all the current cases 4878+3943+2199+.......+2 = 18,818 (excluding unassigned cases), this count doesn't match up with the total 18,256 cases of that day.

**Comment by shuklaayush** [comment]
You can't just exclude unassigned cases. Anyways, seems to match for me

![image](https://user-images.githubusercontent.com/27727946/86225725-441ef200-bba8-11ea-8b7e-9a142a164597.png)

**Comment by purveshmakode24** [comment]
You can check the same problem in today's cases or any other previous day cases as well. Total count differs from what is shown at the bottom.

**Comment by bee-rickey** [comment]
@purveshmakode24 Please let us know if there's some other issue. Else will be closing this.

**Comment by purveshmakode24** [comment]
No other issue. Everything is working fine now.
