### ISSUE TITLE
Getting TypeError: Cannot read property 'geoJSON' of undefined in View Nearby Essentials

### ISSUE THREAD

**Issue by SidWorks** [covid19india/covid19india.github.io#2197]
**BUG Description**
Getting TypeError: Cannot read property 'geoJSON' of undefined in View Nearby Essentials

**To Reproduce**

1. Go to '.Essentials..'
2. Click on '..View Nearby Essentials..'
3. See error Cannot read property 'geoJSON' of undefined 

**Expected behavior**
When you click on View Nearby Essentials one should be getting details about nearby Nearby Essentials

**Screenshots**

![image](https://user-images.githubusercontent.com/51191127/86216211-4fb7ec00-bb9b-11ea-82d2-1d36ca1457f8.png)

**Desktop (please complete the following information):**

- OS: win10
- Browser chrome
- Version 83.0

**Additional context**

**Comment by shuklaayush** [comment]
Seems obsolete now that Essentials has been deprecated
