### ISSUE TITLE
Add positivity rate chart

### ISSUE THREAD

**Issue by anand-kay** [covid19india/covid19india.github.io#2199]
**Is your feature request related to a problem? Please describe.**
Not all states are increasing testing at the same rate. So we can't rely only on the confirmed cases count. The percentage of positive cases for the number of tests done will give a clear picture of the situation. This should be done for both national and statewise data.

**Describe the solution you'd like**
Add a new timeseries chart below the tested chart which displays the positivity rate graph. The confirmed cases and tested count on that particular day, retrieved from the API, should be used for calculating both national and statewise positivity rate.

**Additional context**
I've already built such a feature for personal reference and I've been using it for quite a few days now. This statistic really proves to be useful. For example, Delhi's positivity rate has decreased substantially after they increased testing. But not so much in other states. I'm attaching screenshots of it for reference.

**Delhi daily graph:**
![Screenshot from 2020-07-02 02-01-32](https://user-images.githubusercontent.com/36853431/86288881-4dd84200-bc08-11ea-8d71-fa7e9e94cbd6.png)

**Tamil Nadu daily graph:**
![Screenshot from 2020-07-02 01-58-51](https://user-images.githubusercontent.com/36853431/86288893-54ff5000-bc08-11ea-9fd1-88b824fd7a9c.png)

**Tamil Nadu cumulative graph:**
![Screenshot from 2020-07-02 01-46-09](https://user-images.githubusercontent.com/36853431/86288912-5cbef480-bc08-11ea-923e-6142b5600ca4.png)

**Comment by parvezdittia** [comment]
I would like to work on this issue, if not already being worked on.
