### ISSUE TITLE
Color change for active and confirmed cases. 

### ISSUE THREAD

**Issue by abhinav098** [covid19india/covid19india.github.io#220]
I feel color for **active cases** should be **red** and for **confirmed** it should be something else.

Refer screenshot for the same. I can even pick this issue myself to fix. 

Let me know in the comment section.

<img width="1280" alt="Screenshot 2020-03-27 at 12 21 33" src="https://user-images.githubusercontent.com/26408955/77729780-84a92580-7025-11ea-9769-1c3071f9ecc0.png">

**Comment by Rajanpandey** [comment]
Can I do this?

**Comment by Rajanpandey** [comment]
Can I do this?

**Comment by Rajanpandey** [comment]
Done. Color swapped for confirmed and active everywhere (level, minigraph, table and choropleth), except for the SPREAD TRENDS. 
Didn't understand the whole graph svg thing. If it needs to be changed too, then someone call use my PR and code on top of it.
PR: https://github.com/covid19india/covid19india-react/pull/229

**Comment by Rajanpandey** [comment]
@abhinav098 Done. Swapped color in level, minigraph, table, choropleth, and spread trends.
PR: https://github.com/covid19india/covid19india-react/pull/229

**Comment by sudevschiz** [comment]
I vote No for this change. There is no solid value add in changing the colors, especially now that the colors have been established.
@JunaidBabu  OR @jeremyphilemon make the final call.

**Comment by Rajanpandey** [comment]
Personally I feel that swapping the colors makes sense. The UI makes more sense and looks better when active cases are red, recovered cases are green and deceased cases are grey. 
The changes in my PR has fixed the color scheme throughout the app so it has regained uniformity again.
The rest is your call.

**Comment by lavac** [comment]
Is this bug still open? i see @Rajanpandey said he has already fixed it in the comment. Let me know if it is need to be fixed.

**Comment by Rajanpandey** [comment]
@lavac Yes it's done and a PR has been created.

**Comment by Rajanpandey** [comment]
See how it looks: https://covid19india-react-i10jsp90z.now.sh/

**Comment by jeremyphilemon** [comment]
We've established the colors and we can't confuse the users now. At this point we've defined what the colors mean, so we don't have to worry about what they usually mean.
