### ISSUE TITLE
Logo doesn't appear right on medium to large devices

### ISSUE THREAD

**Issue by reetpriye** [covid19india/covid19india.github.io#2201]
**Is your feature request related to a problem? Please describe.**
Covid19India logo doesn't appear right on devices more than 769 px.

**Describe the solution you'd like**
I want to update the font size from 0.6rem to 0.5rem.

**Describe alternatives you've considered**
Changing font size should do the necessary correction. No alternatives required.

**Additional context**
I want to get assigned on this issue and make the changes. One small contribution to one of the best react project.
![1](https://user-images.githubusercontent.com/55601795/86327483-0d58e280-bc61-11ea-9b38-fc528a341d10.png)

![2](https://user-images.githubusercontent.com/55601795/86327493-0fbb3c80-bc61-11ea-9b39-52e0d96412aa.png)

**Comment by anand-kay** [comment]
Changing the font size might not be the best solution to this issue. On my laptop, the logo appears properly for 0.6rem and wraps wrongly for 0.5rem, which is the other way round in your case.

There could be a hacky solution to this though. Add a `<br/>` tag in-between the `"Covid19"` and `<span>` inside the `<a>` tag. Then set `display:none` on `<br/>` outside the media query and `display:block` inside the media query.

**Comment by shuklaayush** [comment]
Duplicates #1707. Please discuss over there
