### ISSUE TITLE
Fix: Fix Theme(Darkmode) Toggle in Navbar

### ISSUE THREAD

**Issue by coding-with-binaries** [covid19india/covid19india.github.io#2203]
**Bug Description**

- Ideally the theme toggle is different from other navbar items
- By default event is propagated to the parent

**To Reproduce**

1. Toggle Navbar theme
2. Toggle again
3. Navbar state keeps changing on theme toggle
4. Verify this behavior

**Expected behavior**
- On toggling theme(darkMode) the navbar state should not change

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. iOS] OS X
- Browser [e.g. chrome, safari] Chrome, Brave

**Smartphone (please complete the following information):**

**Additional context**

**Comment by coding-with-binaries** [comment]
Any updates? Is this the expected behavior?

**Comment by shuklaayush** [comment]
Fixed via 81bf76559b49fdef5621e47543010098a08ae199
