### ISSUE TITLE
GitHub logo is not visible

### ISSUE THREAD

**Issue by SwagataJ** [covid19india/covid19india.github.io#2209]
**Is your feature request related to a problem? Please describe.**
GitHub logo is not visible in both desktops/laptops and mobile devices when using dark theme unless brightness is at maximum.

**Describe the solution you'd like**
Changing the color of GitHub logo might be considered(  A white logo would go with the dark theme but would not work on the original white theme. A halfway happy color has to considered.

**Comment by balrajsingh9** [comment]
@SwagataJ I have fixed this already in #2180
But my PR is awaiting review, so not sure if the fix in my PR counts. 👀

**Comment by SwagataJ** [comment]
Oh! Cool.
