### ISSUE TITLE
Change "Tests per Million" to "Tests per Positive case"

### ISSUE THREAD

**Issue by LoknathBehera2112** [covid19india/covid19india.github.io#2213]
Since population is not uniform across states so Tests per million population is not a good parameter to judge states. Tests per Positive cases makes much more sense. This parameter doesn't takes population into consideration. In the current scenario, states with small population will always have a very high Tests per million which states with big population can never beat. Its just illogical.

**Comment by LoknathBehera2112** [comment]
![IMG_20200705_220405](https://user-images.githubusercontent.com/31297544/86537268-7794b000-bf0b-11ea-9ded-c6ef41e87c20.jpg)

**Comment by sudevschiz** [comment]
Using the 'per million' metric is exactly due to reason you mentioned - populations are different across states. 
Tests per confirmed case is also a useful metric which could be added separately. We are working towards bringing this information into the website soon.
