### ISSUE TITLE
Wrong Active number of users

### ISSUE THREAD

**Issue by hg1996** [covid19india/covid19india.github.io#2216]
**Describe the bug**
(Active + Recovered + Deceased) != Confirmed

**To Reproduce**

1. Go to `https://www.covid19india.org/`
2. See error

**Expected behavior**
(Active + Recovered + Deceased) = Confirmed

**Screenshots**
Taken on 06th July 2020 at 2:00 AM IST

<img width="581" alt="Screenshot 2020-07-06 at 1 53 46 AM" src="https://user-images.githubusercontent.com/16164190/86541615-e7b32e00-bf2b-11ea-95a9-282525afb6a8.png">

<img width="749" alt="Screenshot 2020-07-06 at 2 02 05 AM" src="https://user-images.githubusercontent.com/16164190/86541720-c1da5900-bf2c-11ea-8a53-242bb80fb58c.png">

**Desktop (please complete the following information):**

- OS: MacOS
- Browser: Chrome
- Version: 83.0.4103.116

**Additional Information:**
By looking at data from `https://www.worldometers.info/coronavirus/`, it looks like Active number of users is faulty rather than recovered, deceased or confirmed. PFA the screenshot for same. :)

**Comment by bee-rickey** [comment]
There are cases that are marked as "non covid deaths" and "migrated". These get counted in confirmed, but do not get added to recovered or deceased. Hence Active = confirmed - recovered - deceased - "migrated/non-covid death".
