### ISSUE TITLE
Show district level charts on-click of district

### ISSUE THREAD

**Issue by sunshinecool** [covid19india/covid19india.github.io#2217]
**Is your feature request related to a problem? Please describe.**
can city level graphs be displayed like you have for state level graphs? 

**Describe the solution you'd like**
on-click on a city (same as state today) shows the chart (# of reported, active, etc.) of the cases for that city.

**Additional context**
I think this is very useful when comparing the two cities in terms of doubling rate, rate of increase to predict when the cases would peak.re.

**Comment by balrajsingh9** [comment]
I think you meant **District level**? @sunshinecool

**Comment by sunshinecool** [comment]
Sorry yes, that's what I meant. @balrajsingh9

**Comment by shuklaayush** [comment]
Added via #2215. Go to the state pages to see district level graphs :)
