### ISSUE TITLE
State wise travel guidelines

### ISSUE THREAD

**Issue by SPATAN18** [covid19india/covid19india.github.io#2222]
**Context**
As flight operations have resumed and curbs have been lifted on interstate travel, people have been traveling to their native places or are making urgent trips to other states. Every state has some set of guidelines to follow when somebody comes from a different state e.g. in Rajasthan, a 14 day home quarantine is mandatory for people coming from other states via flights.

**Problem**
I have observed that a lot of people are not aware of updated guidelines and procedures to follow when making such trips and there is not a single source to find the relevant information directly. It causes a lot of uncertainty and fear amongst travelers and renders them anxious about the same. Secondly, most of the search result that pops up on search engines is not always updated with the latest changes.

**Solution**
Showing state-wise travel guidelines in the current dashboard can provide valuable information without making people ramble on the internet on their own.

**Comment by bee-rickey** [comment]
Would be very difficult to maintain given the frequent changes in these and lack of reliable sources.
