### ISSUE TITLE
Shaded region for case stats offset from optimum position

### ISSUE THREAD

**Issue by JapneetSingh5** [covid19india/covid19india.github.io#2223]
**Describe the bug**
A clear and concise description of what the bug is. If your issue is regarding an error in the data, it's best reported through [this form](https://forms.gle/MLeSrdwRuf8AjFkp9).

**To Reproduce**

1. Go to 'https://www.covid19india.org'
2. Click on 'Confirmed'
3. Click on 'Active'

**Expected behavior**
Shaded region should match with the shaded part on hover.

**Screenshots**
on Hover
<img width="623" alt="Screen Shot 2020-07-07 at 12 46 36 AM" src="https://user-images.githubusercontent.com/54809290/86631370-abdf9d80-bfeb-11ea-845a-091f5d182f65.png">
Active State
<img width="630" alt="Screen Shot 2020-07-07 at 12 46 51 AM" src="https://user-images.githubusercontent.com/54809290/86631401-b5690580-bfeb-11ea-9c68-e2f666339143.png">

**Desktop (please complete the following information):**

- OS: [macOS]
- Browser [Safari]
- Version [Catalina]

**Additional context**
How do I take up this issue?

**Comment by balrajsingh9** [comment]
@JapneetSingh5 I'm unable to reproduce the issue using the steps you provided. I have tried both in Safari and Chrome Canary and is using the same device specs and OS version. 😕

**Comment by JapneetSingh5** [comment]
I can confirm that the issue still exists, Safari 13.1 is what I am using.
