### ISSUE TITLE
Search bar showing results for unknown and unassinged places when searched for 'u'

### ISSUE THREAD

**Issue by Rudra1607** [covid19india/covid19india.github.io#2224]

**Comment by balrajsingh9** [comment]
@Rudra1607 When you create an issue, please follow the contribution guidelines and make use of the template. 
Without proper descriptions, screenshots, steps to reproduce, and platform specs, this issue will be closed by the maintainers.

Please adhere to the guidelines.

**Comment by shuklaayush** [comment]
Fixed via 64ce1d2354a35563a0998ff476d0b6baf3f2f89c
