### ISSUE TITLE
Previous dates filter still visible in background when choose language box view in front

### ISSUE THREAD

**Issue by vjsatyawan** [covid19india/covid19india.github.io#2225]
Previous dates filter still visible in background when choose language 
![Screenshot_20200707-170857_Chrome](https://user-images.githubusercontent.com/11697742/86775287-e2adc600-c074-11ea-9459-25a1f8d7b509.jpg)

**Comment by bhanprakash23** [comment]
In mobile version it is working fine but issue is still present in desktop version, find attached the screenshot. @tanmaybhatt
![image](https://user-images.githubusercontent.com/5822377/87183595-0cc8e780-c304-11ea-95e8-40cdc015e232.png)

**Comment by tanmaybhatt** [comment]
@bhanprakash23 my changes are not released yet, the pull request is still open

**Comment by shreeshampandey** [comment]
#2231

**Comment by shreeshampandey** [comment]
Can be fixed by #2231
