### ISSUE TITLE
Dark Mode UI 

### ISSUE THREAD

**Issue by Shubham0324** [covid19india/covid19india.github.io#2228]
When switch to dark mode the data is shown in color code of '6c757d', but this creates a user issue which has sensitive eye also it is little bit uneasy for eyes during night mode and rest time also
I suggest switching colour to code 'FFFFF'F'(i.e. white).
It result in better viwe of Data in night mode also in every device.

![#6c757d](https://user-images.githubusercontent.com/53115519/87047691-74096d80-c218-11ea-8fe4-fd1b70f7582c.PNG)
![#FFFFFF](https://user-images.githubusercontent.com/53115519/87047694-753a9a80-c218-11ea-896e-2e37aa982078.PNG)

**Comment by balrajsingh9** [comment]
@Shubham0324 This should address your concerns #2180

**Comment by Shubham0324** [comment]
@balrajsingh9 It does address my concerns! Hence closing the issue. Just a suggestion when switching light mode every time popup would be kind of frustrating the variation selection feature should have different approach For eg.
When user switch to dark mode a button / bar should appear in either top right or near footer region helping to customize the variation of as describe by u in #2180.
Just A Suggestion.

**Comment by balrajsingh9** [comment]
@Shubham0324 I believe a user won't be toggling themes too much, once he decides a combination to use. The browser will remember the flavor of the theme (as long as he doesn't clear browser data/uses incognito mode). 

I followed Twitter's UX Flow for this. I believe once the theme is toggled and a combination has been chosen, he will keep the same for some time longer.

I welcome your idea and please feel free to share your UX opinions (with screenshots/some samples), but I strongly believe once the user toggles the theme, he will be settled on it for quite some time. 👀
