### ISSUE TITLE
data mismatch

### ISSUE THREAD

**Issue by krishnasen2401** [covid19india/covid19india.github.io#223]
when i have the accessed the api at
https://api.rootnet.in/covid19-in/unofficial/covid19india.org and https://api.covid19india.org/raw_data.json

this was the details present
![image](https://user-images.githubusercontent.com/13378434/77730709-53c9f000-7027-11ea-9d63-d2c2ea176e1a.png)

were as in the react website it shows as 

![image](https://user-images.githubusercontent.com/13378434/77730780-7cea8080-7027-11ea-88d9-cd5ea34b8f5b.png)

here is the manual verification of the api in the rest call itself

![image](https://user-images.githubusercontent.com/13378434/77730902-ccc94780-7027-11ea-9031-33d54596c9be.png)

![image](https://user-images.githubusercontent.com/13378434/77731987-fe431280-7029-11ea-92cc-ff5f5cdb07ca.png)

**Comment by krishnasen2401** [comment]
it was done in power bi itself and data is auto categorized in matrix

**Comment by krishnasen2401** [comment]
what does migrated means

**Comment by JunaidBabu** [comment]
Some state's have manually entered data in the API. this is not a bug related to this project

**Comment by krishnasen2401** [comment]
Does the website use the same api in your i.e raw_data.json or a different one??

**Comment by JunaidBabu** [comment]
The site uses a cleaner version of raw_data.
https://api.covid19india.org/data.json
