### ISSUE TITLE
blog dashboard does not have valid title

### ISSUE THREAD

**Issue by veer87** [covid19india/covid19india.github.io#2236]
Find Marked place in the screenshot.
<img width="949" alt="blog-dashboard-Error" src="https://user-images.githubusercontent.com/9028245/87231658-a5c83300-c3d6-11ea-99b1-c4cd98d03bf0.PNG">

**To Reproduce**
1. Go to '.https://www.covid19india.org/..'
2. Hover left side and Click on '..blog..'
3. See Title of the page which doesn't look valid

**Expected behavior**
Blog page should have valid title like 'Blog'.

**Screenshots**

- Browser [e.g. chrome]
- Version [e.g.83.0.4103.116 ]

**Comment by shuklaayush** [comment]
@bee-rickey Hmmmmmm

**Comment by bee-rickey** [comment]
@veer87 Well.... We wanted to stretchhhhhhh a bit....
