### ISSUE TITLE
Total beds per district 

### ISSUE THREAD

**Issue by ghost** [covid19india/covid19india.github.io#2237]
there is a panic in citizens now whether beds are available or not, we know total number of beds in a state or a big city.but we actually do not know the exact covid-19 beds per district. like in gurgaon there are today{12th july 2020} there are 1040 active cases according to the district website's bulletin and beds are around 1623. This info would be nice to add

**Comment by bee-rickey** [comment]
This info is extremely hard to come by. Maintaining and making it reliable would be difficult if not impossible. Hence this will have to wait.

**Comment by ghost** [comment]
Yes, I agree even district administration does'nt give any information
about beds and only the  God knows about private hospitals scene
