### ISSUE TITLE
Trend chart for death rate

### ISSUE THREAD

**Issue by anuragster** [covid19india/covid19india.github.io#2239]
**Is your feature request related to a problem? Please describe.**
Looking at the data I don't get a sense of realtime death rate of state/country. 

Death Rate = 100 * (# of deaths) / (# of recoveries + # of deaths)

**Describe the solution you'd like**
Does it make sense to have a trend chart for last 7 day moving average of death rate for each day? The reason to propose this is that it is more real time than cumulative death rate shown on say worldometers.info. Also, last 7 days will smoothen the death rate but still be real time.

**Describe alternatives you've considered**
Importing the data from covid19 and creating my own excel sheet is cumbersome.

**Additional context**
I want to see an additional trend chart similar to the screenshot [here.](https://snipboard.io/PsOuLq.jpg)

**Comment by shuklaayush** [comment]
Death rate has been added to the table
