### ISSUE TITLE
Refresh webpage cause it to loose UI design 

### ISSUE THREAD

**Issue by rajathsn** [covid19india/covid19india.github.io#224]
**Describe the bug**
Refreshing cluster, helpful links and FAQ page cause the webpage to reload with unaligned framework.

**To Reproduce**
1. Go to 'any browser and any operating system'
2. Click on ‘refresh'
3. You will see that webpage loses it’s UI framework

**Screenshots**
1. When loaded by clicking tab
![9999E480-D594-4E78-B4F9-4526EB9A3454](https://user-images.githubusercontent.com/52188338/77730862-aefbe280-7027-11ea-8791-8928ca2df558.png)

2. Refreshing webpage 
![3C10D978-E71E-4141-BE09-37241D3A9B2B](https://user-images.githubusercontent.com/52188338/77730884-c044ef00-7027-11ea-8757-6e9cea36c99b.png)

3. After page refreshes 
![311CB457-2549-433A-8399-99EB0F27B578](https://user-images.githubusercontent.com/52188338/77730916-d2bf2880-7027-11ea-94f2-7ede374f8315.png)

**Comment by JunaidBabu** [comment]
@sudevschiz I think we should remove the cluster link. it's not able to perform well with the latest numbers

**Comment by rebelgiri** [comment]
Clusters tab has a refresh issue. I have just verified in Desktop Firefox browser Issue is reproducible.
Same behavior for Clusters, Helpful Links  and FAQ  Tabs

**Comment by abhishekakade** [comment]
Clusters page when refreshed, gets a 404 on CSS file.
`GET https://www.covid19india.org/static/css/main.1a275089.chunk.css net::ERR_ABORTED 404 (Not Found)`

**Comment by sudevschiz** [comment]
@someshkar please suggest your roadmap. We can take the link off for development if more work is needed on the cluster viz.

**Comment by someshkar** [comment]
@sudevschiz As for the performance issue, we have some ideas on how to fix them (TLDR: run as many functions server-side as possible, just use frontend to display nodes instead of calculating positions too) 

Moreover, the refresh issue on the clusters tab that @rebelgiri mentioned doesn't seem to be reproducible for me? Can you send a screenshot? Also, the issue seems to be for the Clusters tab + the Helpful links tab + the FAQ tab? It can't be a clusters only issue then.

**Comment by rajathsn** [comment]
Seems like issue is fixed. Now On refresh the page displays content properly

**Comment by rebelgiri** [comment]
Seems issue is fixed, not able to reproduce on Windows, Firefox version 74.0 (64-bit)
Can we close the issue?

**Comment by rajathsn** [comment]
Yes, since the issue is fixed, I’m closing this issue.
