### ISSUE TITLE
 https://api.covid19india.org/csv/latest/case_time_series.csv Not updating since yesterday.

### ISSUE THREAD

**Issue by gurunitin** [covid19india/covid19india.github.io#2243]
Hi Team, 

I have observed the data in https://api.covid19india.org/csv/latest/case_time_series.csv is not updating since yesterday, Can you please have a look.

Thanks,
Nitin

**Comment by shuklaayush** [comment]
Please raise an issue in the [API repo](https://github.com/covid19india/api)
