### ISSUE TITLE
location based overview at the top of the page

### ISSUE THREAD

**Issue by himanshu8426** [covid19india/covid19india.github.io#2245]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated whenever I go to the webpage I go down to the table and check for rajasthan and then check for KOTA.

**Describe the solution you'd like**
there can be a case overview table at the top for a location-based overview. 
for eg: I live in the Kota district which is in state Rajasthan. An overview of covid19 info kota and Rajasthan should be there at the top, so that I have don't have to go down and check.

**Comment by sudevschiz** [comment]
We do not wish to capture the user's location unless the feature adds extreme value. Site has both search, sort and dropdown  selection options to get the necessary information for each district and state. Let's stick to that and keep it simple.

**Comment by himanshu8426** [comment]
@sudevschiz,
Agree on the user's location point. But definitely it is not simple. 
If you try to search for a location(district). It suggests and navigates you to the state's page. 
where you can find the`Top districts`(with a lot of information). Now you have to click `view all` to see the full list of districts.

How did the `search` feature help me in the scenario?
