### ISSUE TITLE
Feature: District specific graphs. (Need Data)

### ISSUE THREAD

**Issue by Nitromon** [covid19india/covid19india.github.io#2248]
Currently the site has graphs for data per state, but the issue is that there is wide disparity between state and district infection rates. Two districts in the same state can be at different stages of infection spread. I feel a comparative graph of active cases could be charted out for atleast the Tier 1 cities. (Mum, Del, Hyd, Blr, etc) since there is high population density the people could see herd immunity acting in real time. 

I've reason to believe that charting these would prove useful and reduce panic on a local scale. I don't think 'total cases' paints a correct picture. Focusing on active cases should be the goal instead. I do think the larger cities may show downward trends, infact.

I'm here to ask if any of the data scientists behind this project could help me out with this. I'm sure there would be a time series log of cases on a district level (there's already one .csv for state level) that I could use. Creating these numbers from scratch would be time consuming.

**Comment by Nitromon** [comment]
Found the concerned csv file and working on making the graphs myself.  Marking as closed as it was a non-issue.

**Comment by shuklaayush** [comment]
Just fyi, district graphs are already there in the state pages

![image](https://user-images.githubusercontent.com/27727946/87589777-63b72e00-c703-11ea-83cb-327fd35f75d3.png)
