### ISSUE TITLE
Deep Dive Dashboard

### ISSUE THREAD

**Issue by ninjakx** [covid19india/covid19india.github.io#2249]
With reference to #812.

Is this still required?

![cdash](https://user-images.githubusercontent.com/29797787/87714071-d9d19880-c7c8-11ea-9104-7016ee14f11e.gif)

**Demo:** https://ninjakx.github.io/corona_dash/
Or
http://bl.ocks.org/ninjakx/raw/9ee1324250e2d0bb62eac34e147a5da3/7015e9d7bf4ee90d65b815f1cd4c0cbaf1a02fc8/

**Comment by shuklaayush** [comment]
Hey, looks good but I think a lot of this is already there on the website. Nice work though!
