### ISSUE TITLE
Add a Daily new cases column

### ISSUE THREAD

**Issue by arihantkode** [covid19india/covid19india.github.io#2250]
**Is your feature request related to a problem? Please describe.**
There arefive numeric columns available at country, state and district level. These columns are namely : Confirmed, active, recovered, death and total tested. Requesting to add another column, i.e. daily/weekly new confirmed cases to achieve the ability to be able to look at the most affected states or districts.

**Describe the solution you'd like**
A column with moving weekly average of new confirmed cases and a column of daily new confirmed cases.

**Describe alternatives you've considered**

**Additional context**

**Comment by shuklaayush** [comment]
Daily new cases are already shown with an arrow wherever necessary
