### ISSUE TITLE
Track your Location - (Add GeoLocation district wise)

### ISSUE THREAD

**Issue by piyushsi** [covid19india/covid19india.github.io#2251]

**Comment by bee-rickey** [comment]
Can you provide more details?

**Comment by piyushsi** [comment]
we can show initial data dependent on current location, if location is enabled.

**Comment by sudevschiz** [comment]
No, we do not prefer the get the location of the users. It's quite unnecessary when the site has search and dropdown options to get the state/district information that the user needs. Thanks for the suggestion.
