### ISSUE TITLE
Case time series data not updated. 

### ISSUE THREAD

**Issue by ajinkyad92** [covid19india/covid19india.github.io#2259]
![image](https://user-images.githubusercontent.com/55271394/87902317-ebd86300-ca76-11ea-8821-eb6ec7c3119c.png)

data is updated till 18th July 2020

Kindly check. 

Thank You!

-Ajinkya

**Comment by shuklaayush** [comment]
Please create an issue in the [API repository](https://github.com/covid19india/api). Though it seems to be fixed now
