### ISSUE TITLE
Covid 19 Tracker Active count

### ISSUE THREAD

**Issue by 23f2005514** [covid19india/covid19india.github.io#226]
The Active count on the top of the dash board shows "-1" instead of the "+num".

1. Go to the dashboard
2. The Active count on the top of the dash board is reflected as "-1".

The Active count should reflect as  increase as "+num"
![image](https://user-images.githubusercontent.com/32433336/77734824-6c3e0880-702f-11ea-8eee-114bc26b3892.png)

**Comment by shuklaayush** [comment]
The numbers in brackets reflect the daily change where:
Active = Confirmed - Recovered - Deceased.

Right now, this is (18 - 17 - 2 = -1). Hence the negative value. Don't think this is a bug.

**Comment by JunaidBabu** [comment]
@shuklaayush is right. But to remove any further confusion, we've removed the field from website
d94e2be52555e2d5a0ec1ccf5bd47eaf2ce9c4dd

**Comment by Invoker96** [comment]
@shuklaayush Anyone working to correct this one?

**Comment by shuklaayush** [comment]
Hi @Invoker96. It was decided that we skip the change in active cases on the website since it was confusing some people. So, as far as we're concerned, there's nothing to correct.
