### ISSUE TITLE
Features need to be included/modify to help in better visualization of the tabular content and web page. 

### ISSUE THREAD

**Issue by SumanthKongani** [covid19india/covid19india.github.io#2260]
I feel like the tabular content could be **improvised by adding some more features** to it.
The features like adding a **separate column for new positive cases** and adding a **new column for the total population**.
And even features like **ratios between two columns**, for example, *the ratio between active cases and total population, the ratio between total deceased and total population* would be helpful for many data analysts out there.

And there is some **problem with the padding** on the web page as it is shown in the below image.

![Screenshot (49)_LI](https://user-images.githubusercontent.com/44552125/87992070-12dd7600-cb05-11ea-8594-d8c47f8dedf0.jpg)
 
As there is a lot of space in the padding it **doesn't require a scroll option** to the table when viewing on a large screen like 13inch, 15inch laptops, or tablets. 

![Screenshot (50)_LI](https://user-images.githubusercontent.com/44552125/87992343-b169d700-cb05-11ea-873c-01a33b5c0b1a.jpg)

And in the graphs, the Deceased visual graph is of gray color which makes it odd as rest all have different color compared to the main table but **Deceased graph color mixed up into the table** has both are of greyish color, I want you to change it to some other neon color like yellow which shouldn't pop out but should match the other graphs.

or check out this link for some good color: [Neon color Palettes](https://www.shutterstock.com/blog/neon-color-palettes)

![ss graph](https://user-images.githubusercontent.com/44552125/87992733-7f0ca980-cb06-11ea-8493-8c4fc6edd75f.PNG)

**Comment by dsaw** [comment]
@JunaidBabu  I noticed the extra padding on large screens too - definitely could be decreased to make it look natural. For the addition of columns, I think splitting it into a new issue would be ideal since there is a quite some features in this.

**Comment by m-garg** [comment]
Came on this repo to suggest the same.
The solution is to remove the fixed width from these classes : .Home .home-left, .Home .home-right {width: 32rem;}
And also remove the width from table class: .table {width: calc(100% - 2rem);}
Due to the width less than 100%, it is always showing scroll on the table irrespective of the available length.
