### ISSUE TITLE
language and menu not overlap

### ISSUE THREAD

**Issue by shyamkumaryadav** [covid19india/covid19india.github.io#2261]
I'm always frustrated when i open menu and click on language select then not show Language list. 
![Screen Shot 2020-07-22 at 01 13 34](https://user-images.githubusercontent.com/46707211/88099352-b045b200-cbb8-11ea-8084-950657f564b9.png)

**Comment by karan171996** [comment]
Hey Can i work on this ?

**Comment by shyamkumaryadav** [comment]
@kant @tuxdna @slightlyoff

**Comment by abhisharkjangir** [comment]
> This issue is available for contribution.
> 
> Please reply "/claim" (without quotes) if you wish to work on this issue.

/claim

**Comment by abhisharkjangir** [comment]
@shyamkumaryadav  Can you please describe more about it? I mean what is the actual issue?

**Comment by shyamkumaryadav** [comment]
@abhisharkjangir here is
![shyamkumaryadav_video](https://user-images.githubusercontent.com/46707211/88570985-998cd880-d05a-11ea-89ef-28138b5f1868.gif)

**Comment by abhisharkjangir** [comment]
@JunaidBabu Added PR, please review...
