### ISSUE TITLE
Telangana data not correct at District level - Name changed from Telengana

### ISSUE THREAD

**Issue by MillikenDB1** [covid19india/covid19india.github.io#2262]
Since the State name was changed from Telengana to Telangana the District data comes through as Unknown.

**Describe the bug**
A clear and concise description of what the bug is. If your issue is regarding an error in the data, it's best reported through [this form](https://forms.gle/MLeSrdwRuf8AjFkp9).

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by shuklaayush** [comment]
There has been no change in the state name. Refer to https://github.com/covid19india/api/issues/398#issuecomment-660257576
