### ISSUE TITLE
I suggest removing unnecessary props in component.

### ISSUE THREAD

**Issue by Bookman0001** [covid19india/covid19india.github.io#2264]
## About 
I found declared but never used props definition.
I suggest removing unnecessary props because of code enhancement. 

## Seems Targeted Files

```
~/src/components
About.js
Footer.js
Home.js
State.js
```

**Comment by shuklaayush** [comment]
Can you create a PR?

**Comment by Bookman0001** [comment]
I created PR(https://github.com/covid19india/covid19india-react/pull/2267)
Please review on it.
