### ISSUE TITLE
The T column in the table is not correct

### ISSUE THREAD

**Issue by RajarshiBhadra** [covid19india/covid19india.github.io#2265]
There seems to be some issue in rendering of the T column in Mobile Phones as illustrated below

![Screenshot_20200723-105212](https://user-images.githubusercontent.com/8817352/88254371-c8a9ef80-ccd2-11ea-8bdd-241a002bf3a0.jpg)

For example  Andaman the numbers are low but the T is very high

#
![Screenshot_20200723-105242](https://user-images.githubusercontent.com/8817352/88254420-e8d9ae80-ccd2-11ea-9b17-2b4d7d53169b.jpg)

**Comment by sudevschiz** [comment]
T column indicates the number of Tests done. So, it can be quite high compared to the number of cases.
