### ISSUE TITLE
In the aim of making it fancy, its complicating things

### ISSUE THREAD

**Issue by sarangrakhecha** [covid19india/covid19india.github.io#2269]
In need of making it look fancy and stylish, the UI is slowly and gradually getting complicated.
Earlier it was more subtle, informative and especially clean.

Adding too much of graphical/dynamic UI for unnecessary things, makes it look good(good on the eyes) but not every user friendly. Neither the short forms are helping! (Eg. A or C or even 1M for instance). 
The colors are anyway helping it to make it look vibrant. Too much UI changes (making it dynamic when not needed) is not helping.

Too much UI like: Why do you need a rectangle? What was wrong with the earlier version. Was much clean and easy!

[
![Screen Shot 2020-07-23 at 11 58 46 AM](https://user-images.githubusercontent.com/20394342/88309664-a0bf8980-ccdc-11ea-8df5-00bff198c68f.png)
](url)

**Comment by shuklaayush** [comment]
The rectangles are there to switch between different maps. I'm trying to understand, how is that too much UI?

![Peek 2020-07-23 23-38](https://user-images.githubusercontent.com/27727946/88321969-a13c3c80-cd3d-11ea-9ee8-00bcaa7fdb97.gif)

**Comment by bee-rickey** [comment]
@sarangrakhecha Without the rectangular highlighting, it would be nigh impossible to visually show the change of category. Unless there's a valid point here, would like to close this issue. 🤷‍♂️
