### ISSUE TITLE
Deceased Graph is not showing properly when Uniform option is turned on

### ISSUE THREAD

**Issue by first-phoenix** [covid19india/covid19india.github.io#2270]
When uniform option js turned on, the graph for deceased is not showing any curves. It is not working properly. Please see the screenshot attatched to it.
![Screenshot_20200724-095925](https://user-images.githubusercontent.com/67274232/88360722-66b1be80-cd94-11ea-88b5-b49ee9bc7b04.png)

**Comment by JunaidBabu** [comment]
This is the reason why we have a button to toggle uniform scale option. When the deceased and confirmed data has such huge difference, this is bound to happen.
