### ISSUE TITLE
Come back to home page(India section) from a state section

### ISSUE THREAD

**Issue by first-phoenix** [covid19india/covid19india.github.io#2271]
Please link the home page to the "Covid19India" heading of the page or to a dedicated tab written "India" so that anyone can jump to the graph of India section again after visiting graph of state sections.

**Comment by shuklaayush** [comment]
The home page is already linked to the "Covid19India" :confused:  

Anyways, try using the back button (rightmost)
![image](https://user-images.githubusercontent.com/27727946/88368255-46d9c500-cdab-11ea-9444-bbde7c4095fb.png)
