### ISSUE TITLE
ADDING A PLEDGE WINDOW AND STORY WINDOW

### ISSUE THREAD

**Issue by iamkrishnakanhaiya** [covid19india/covid19india.github.io#2275]
Add a pledge window for users to get aware and get some people aware about this Coronavirus.
 And also add success stories of people from corona positive to negative...
![Untitled-1 jpgiii](https://user-images.githubusercontent.com/68463317/88471972-677d5880-cf2c-11ea-90b3-1ffc9cc2526b.jpg)

**Comment by shuklaayush** [comment]
This seems out of scope for us. It'll be difficult to maintain
