### ISSUE TITLE
Feature Request to Connect Patients with Plasma Donors. 

### ISSUE THREAD

**Issue by raunak-r** [covid19india/covid19india.github.io#2277]
**Is your feature request related to a problem? Please describe.**
Not related to any existing problem with the website.
In general, it is very difficult for patients to find appropriate plasma donors at the time of need. Given that covid19india.org has a very large user base, it makes sense to open a section on the website to help people find donors.

**Describe the solution you'd like**
A section of the website dedicated towards finding Plasma Donors.

1. On the section, 2 types of user registration can take place 
- Patient 
- Donor 
(Both set of users will be required to mandatorily provide district and contact numbers + other data).

2. On gettting a patient registration, a simple email or text message can be sent to available donors. 
OR
Donors can be identified based on distance (example within 5 kms), and such donors can be sent a request with the patient details.
OR any other optimized algorithms.

3. A donor will have the option to set an attribute True or False, in case the donor wishes to stop receiving donation requests.
4. Users can be given the option to remove their data. 

**Describe alternatives you've considered**
Alternatives are to build another website, and link it to the existing covid19india.org
OR
A section to reference all other such websites to redirect user base to another 3rd party website.

**Comment by shuklaayush** [comment]
Hey, I don't think we have the bandwidth to attempt/maintain something like this. Will leave this for someone else to pick up

**Comment by raunak-r** [comment]
Well I can help, I also know a couple of good backend engineers, who can very much technically help. Let me know if needed. The only point was that an existing website with considerable amount of userbase has to undertake this to make a very distinctive mark. And with the growing cases, it's becoming more than important to find ways to reduce deaths and active cases.

Currently, covid19india.org outputs knowledge, but not solutions, would love to integrate this and bring in changes which help in practical usage to reduce and recover cases.

For a short workaround, covid19india.org can have a section to list all such available websites which helps patients find a donor.
