### ISSUE TITLE
What does the negative number mean in the tested bar chart?

### ISSUE THREAD

**Issue by kuharan** [covid19india/covid19india.github.io#2279]
**Describe the bug**
There is a negative integer in the **tested** bar chart of Delhi - Date 13th July.

**To Reproduce**
Select "**Delhi** from the dropdown. Select the **Daily** tab so that the graph shows daily numbers for all the visuals."

**Screenshots**
![image](https://user-images.githubusercontent.com/22185333/88486147-5ae31980-cf99-11ea-814f-bad888b8c526.png)

The number of tests conducted on a single day can go down to zero, but what does the negative integer mean? Can someone explain?

**Comment by shuklaayush** [comment]
Refer to https://twitter.com/covid19indiaorg/status/1282947830986899461?s=20
