### ISSUE TITLE
Percentage tested column - Total Tests/Total population *100

### ISSUE THREAD

**Issue by tarun7singh** [covid19india/covid19india.github.io#2280]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Seeing a column named percentage tested which is equal to 
Percentage Tested  = Total Tests / Total population *100

**Describe alternatives you've considered**
Calculating it myself

**Additional context**
It would be nice to see that data. as i think it is important for checking state of districts and how they are doing.

**Comment by shuklaayush** [comment]
Use the per million button (1M) to get tests normalized by population. It's essentially the same information
![image](https://user-images.githubusercontent.com/27727946/88511208-163f9880-d002-11ea-948c-20805c12d287.png)
