### ISSUE TITLE
Add a new feature to support Indian Number system ( i.e Lakhs, crores ) along with Millions/Billions

### ISSUE THREAD

**Issue by google-30** [covid19india/covid19india.github.io#2281]
Considering the Indian audience, majority of the people are not comfortable with International system which talks in Millions and Billions. It would be highly beneficial for showing these numbers in Indian Number system and help people to understand easily without doing unneeded Maths.

**Comment by may55** [comment]
I think this is a good suggestion, and I would like to work/help on the same.
/claim

**Comment by snehsumant** [comment]
Do you need this issue to be solved? I can work on this.

**Comment by jay1310** [comment]
Yeah, its a very important requirement. Can, I work on it?

**Comment by syedsadiqali** [comment]
it would be better to have both kind of number systems, interchangeable by a click, showing a tooltip for first time users, default could be Indian number system.

**Comment by FrozenHearth** [comment]
> it would be better to have both kind of number systems, interchangeable by a click, showing a tooltip for first time users, default could be Indian number system.

Agreed. This is the best of both worlds.
