### ISSUE TITLE
Change the onFocus and onBlur animation of the search bar.

### ISSUE THREAD

**Issue by khpatel8** [covid19india/covid19india.github.io#2286]
Feature Suggestion:
The search bar onFocus/Blur animations are static compared to the other ones in the website like navbar onMouseEnter/Exit and Language Switcher which takes away the consistency of the website.
 
Solution:
I suggest making the animation similar to the language switcher. This can be done using react-spring with very less additional code. The flex display would have a justify-content of space evenly to place it into the center of search bar. **Also, need opinion on adding a title of "Suggestion" on top the suggestions.**

Fix Recording:
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/56375328/88594610-5577e480-d016-11ea-8a57-027e7c4a7b87.gif)

PS: I already have a fix and can quickly create a PR

**Comment by bee-rickey** [comment]
Doesn't add much value to the site. Closing this issue.
