### ISSUE TITLE
(mobile view ) graph overlapping text for some states

### ISSUE THREAD

**Issue by parikannappan** [covid19india/covid19india.github.io#2288]
**Describe the bug**
In the mobile view, the graph is overlapping the text.

**To Reproduce**

1. Go to 'Spread Trends'
2. ADD ' Maharashtra'
3. Scroll down to 

**Expected behavior**

**Screenshots**

 
**Smartphone (please complete the following information):**

- Device: [e.g. iPhone se]

iPhone se

ios 13 

safari
![WhatsApp Image 2020-07-28 at 4 17 47 PM](https://user-images.githubusercontent.com/44460396/88657222-326d3380-d0ef-11ea-8bbf-d725ca6d8509.jpeg)

**Additional context**

**Comment by shuklaayush** [comment]
Duplicates #1650
