### ISSUE TITLE
[First, Enhancement] A feature to track in which state or city people are getting discharged (lack of bed and other issues) without being fully recovered, 

### ISSUE THREAD

**Issue by iamirulofficial** [covid19india/covid19india.github.io#2290]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**

It will be really informative as this measure to get discharge people from hospital without being fully recovered is limited to certain cities where may be more cases!

**Describe alternatives you've considered**
Not any, I guess

**Additional context**
Nope!

**Comment by shuklaayush** [comment]
Hey, this would probably be useful, but it's difficult to get this data from any credible source. Most of our sources are official state government bulletins and I don't see this being available there
