### ISSUE TITLE
Negative count for Tested

### ISSUE THREAD

**Issue by Vasudha15** [covid19india/covid19india.github.io#2291]
Could please clarify if it is bug?
How can number of “Tested” can be negative for Delhi on 13th July

**Comment by Vasudha15** [comment]
![B0C2C5AE-6465-4F9D-974D-F51E20D552D5](https://user-images.githubusercontent.com/30729845/88752502-ba971b80-d177-11ea-8eb6-5725f46e188a.jpeg)

**Comment by shuklaayush** [comment]
Duplicates #2279
