### ISSUE TITLE
District level CSV data can't be fetched by Google Sheets due to large size

### ISSUE THREAD

**Issue by vishalgodha** [covid19india/covid19india.github.io#2292]
**Describe the bug**
District level CSV data can't be fetched by Google Sheets due to large size

**To Reproduce**

1. Go to https://api.covid19india.org/documentation/csv/
2. Scroll down to https://api.covid19india.org/csv/latest/districts.csv
3. In Google Sheet formula A1 > =IMPORTDATA("https://api.covid19india.org/csv/latest/districts.csv")
4. Formula Error - Resource at URL contents exceeded maximum size

**Expected behavior**
Data should have been fetched by Google sheet, may be you need to split data.

**Comment by shuklaayush** [comment]
Please create an issue in the [API repository](https://github.com/covid19india/api)
