### ISSUE TITLE
hover info for 3 filter buttons

### ISSUE THREAD

**Issue by navnit0707** [covid19india/covid19india.github.io#2295]
**while clicking on these three options map changes but I didn't know what is this for because I don't know the meaning of that three-button**

** solution **
I want to use simple external CSS hover for these three buttons to show quick hover info about them
![Screenshot (407)](https://user-images.githubusercontent.com/40719341/88854217-95092100-d20e-11ea-8ea2-b4d9a894e1bd.png)
 
let me know if this feature will help you or not; if help you then any suggestion alternate to my idea.

**Comment by rahulmr123** [comment]
Hey all
            I am a react developer and a first-time contributor, I would like to work on this issue.

**Comment by govardhan27** [comment]
Hey Guys,
Is the review for this done?
I am willing to help out here. Please let me know
Thanks

**Comment by navnit0707** [comment]
no , owner didnt replied yet you can send a pull req if he founds useful then it will be good else time waste , thats why i waited for reply .
you can work on it .

**Comment by bee-rickey** [comment]
Hover is useful for web versions. 95% of the site users are mobile users. I don't really find much of a value in this. But I'm making this available. Please pick up and raise a PR.

**Comment by sakshianand** [comment]
Is someone already working on this issue? Else I can take this up.

**Comment by navnit0707** [comment]
Sakshi you can work on this because Govardhan is not working on this I
think ... i opened this but have no time to do so this will good for you
.And I also want to see (codes) how this will be implemented because I
never contributed in large projects

**Comment by govardhan27** [comment]
Hey Guys, have already started on this task.

**Comment by navnit0707** [comment]
ok govardhan let me mention you so that no people will be confused  later.

**Comment by navnit0707** [comment]
@govardhan27 is working on this feature

**Comment by abhisharkjangir** [comment]
I claimed it, If anyone interested to work on this, please let me know, I can unassign me.

**Comment by govardhan27** [comment]
Hey, @abhisharkjangir I have already started on this.

**Comment by abhisharkjangir** [comment]
@govardhan27 Okay, let me unassign it.

**Comment by shivansh-13** [comment]
@abhisharkjangir hey, I am a new developer and learning opensource for the first time. I want to work on this issue. can you please assign me it? or  tell me how to claim ?

**Comment by abhisharkjangir** [comment]
@shivansh-13  This issue is already claimed and I assigned it to @govardhan27 .

**Comment by shivansh-13** [comment]
@govardhan27 I have completed the work already. I am ready to create a PR.  If you haven't done the work please give me the claim so that I can create a PR.
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/80212477/119230244-ffda6e80-bb38-11eb-8c72-ba0f3ef7edc0.png">

EDIT: PR generated with PR number #2480
