### ISSUE TITLE
to change district,time ,notes in hindi when user select hindi language

### ISSUE THREAD

**Issue by navnit0707** [covid19india/covid19india.github.io#2296]
**problem**
when user select the Hindi language some important things like short with ascending, descending,  district name, time should also change in Hindi for better understanding for all peoples

**solution**
1) I would change the time conversation in Hindi when users select the Hindi language.
2) will change district name in Hindi so that when user changes lang he will find helpful.
3) in the notes section there is also a need for hindi conversion of the text so I will implement it by writing it in hindi
![Screenshot (409)](https://user-images.githubusercontent.com/40719341/88855912-38f3cc00-d211-11ea-94d1-0bda887aefd6.png)

**if you found this project will help you then let me know **
and if any suggestions to how to do and what you want to avoid suggest me I want to work on it .

**Comment by shuklaayush** [comment]
Partially fixed via 9b310bb7b9ee4f8d881d53af993e099227aefe5e
