### ISSUE TITLE
UI issue | Graph overlapping with the count and title.

### ISSUE THREAD

**Issue by rahulmr123** [covid19india/covid19india.github.io#2298]
**The graph is overlapping with the count, title and date when the base of the graph is negative, no issues when the base of the graph is zero.**

For reproducing the issue, select '**DELHI**'.

solution
It would be better for graphs with negative base, the title count can be shown at the bottom.

![graph_covid19](https://user-images.githubusercontent.com/21059591/88881482-29927400-d24d-11ea-8c88-5778611ad606.png)

**Comment by shuklaayush** [comment]
Duplicates #1650
