### ISSUE TITLE
Guys we need a graph Total cases vs vs recovered ones

### ISSUE THREAD

**Issue by shaunmulark** [covid19india/covid19india.github.io#23]
Isn't the website already having this?
Can you provide more details?

**Comment by turbanpride** [comment]
We can have a `bar chart` to show this data. It can easily show total data along with recovered cases. Check the screenshot which i have attached below. :)
<img width="576" alt="2VT41" src="https://user-images.githubusercontent.com/36756462/77512692-8e9e1d80-6e99-11ea-8b9e-ccfbb1f86181.png">

**Comment by rohit-gohri** [comment]
I think what they mean is a biaxial chart: eg. http://recharts.org/en-US/examples/BiaxialBarChart

**Comment by shaunmulark** [comment]
Can you look at this and check out the various graphs used ? https://docs.google.com/spreadsheets/d/1dEXS5dndsDvyJeWsjFllhq51Y_vntUS-1S_p2u1Om6c/edit#gid=0
Those would be helpful. Sorry for responding this late

**Comment by jeremyphilemon** [comment]
The graphs already present pretty much do the job, I understand they may, however, not be on the same graph itself. This maybe a thing we implement in the future, but not at present. Thanks!
