### ISSUE TITLE
Error in Displaying Active Cases

### ISSUE THREAD

**Issue by mkp95** [covid19india/covid19india.github.io#2302]
If there are more recovered cases than new confirmed cases then the active cases graph show it as negative but in real world the new confirmed cases are actually active cases for next day. So i think it should reflect the same in the Graph. It should be shown maybe as 

**Active Cases = (New cases + Old Active Cases) - (Recoveries + Deaths)**

It would reflect current total active cases in any location rather than showing negative counting.

**Steps to reproduce the error**

1. Country: India, State: Andhra Pradesh, Dist: Kurnool, Date: 22nd July 2020
2. Country: India, State: Andhra Pradesh, Dist: SPS Nellore, Date: 23rd July 2020
2. Country: India, State: Andhra Pradesh, Dist: Guntur, Date: 18th, 23rd & 30th July 2020

there are many more such occurrences.

![1](https://user-images.githubusercontent.com/27913072/89100331-dae30680-d413-11ea-8486-e89514575e60.png)

**Comment by shuklaayush** [comment]
Refer to https://github.com/covid19india/covid19india-react/issues/2038#issuecomment-641962963

**Comment by ksasan** [comment]
The defect is still there!

As of today (8-Aug-2020), the graph of Total active cases in Delhi is showing negative bar entries (which is not possible!)

Possibly the formulae of calculation needs revisit


![image](https://user-images.githubusercontent.com/9150010/89706782-73363980-d986-11ea-81cd-e4e0615b94ec.png)

**Comment by mkp95** [comment]
> Refer to [#2038 (comment)](https://github.com/covid19india/covid19india-react/issues/2038#issuecomment-641962963)

I know that I already read that but to make the severity clear we should use a current active case to be the method i proposed as it makes a clear picture of what the current situation is.. As of any day the total active cases should always be positive as new cases are coming daily...
