### ISSUE TITLE
In Search box of " your district or state " It should must take users district or state name automatically.

### ISSUE THREAD

**Issue by IamAkku** [covid19india/covid19india.github.io#2303]
As I was seraching for Covid positive people in my district and then I found this website, but the problem what I see when I open the website it is not showing the data according to my current location. It should must take users district or state name automatically and show the covid record data locally, along with total record. As I am taking example I go through the website " weather " my location name, state name , along with the details of temprature ,precipitation,humidity and wind speed automatically showing.
                                            If this feature added to this website this will help alot for the people not only for knowing records of covid but also for safety purpose as people can easily knows the records of covid and they can take precautions before going anywhere in covid positive region.
 
    This can be done using location API.

**Comment by shuklaayush** [comment]
Duplicates #2251
