### ISSUE TITLE
Display before day Confirmed, Recovered, Deceased cases

### ISSUE THREAD

**Issue by saandeepgithub** [covid19india/covid19india.github.io#2305]
Would be good, if the app can display a day before active, recovered ,deceased cases like in below image,

This would give a glimpse on how our country is overcoming the virus day by day

we can change display colour to green if today confirmed cases are less than yesterday and red if they more and vice-versa for deceased and recovered cases

Note: I have shown the sample data only for active cases (like how it can be if this feature addition gets approved)

![image](https://user-images.githubusercontent.com/32898077/89158405-abefa080-d58b-11ea-9d49-4bb349363fc9.png)

Solution: i am still going through the code, but this can be doable, i will produce the possible solution in day or two

**Comment by shuklaayush** [comment]
I don't see any particular need for doing this. The trend of daily increase in cases can already be seen in the charts

![image](https://user-images.githubusercontent.com/27727946/89165915-e27ee880-d596-11ea-966b-d2f53ce4e6ba.png)
