### ISSUE TITLE
Source for districtwise testing data

### ISSUE THREAD

**Issue by archit120** [covid19india/covid19india.github.io#2306]
I went through the APIs and the raw data but I couldn't find what the source for the district-wise testing data is. I'm specifically curious for Bihar as I'm not aware of any public sources that release the exact districtwide testing counts for Bihar.

**Comment by shuklaayush** [comment]
Check out [this file](https://github.com/covid19india/api/blob/gh-pages/csv/latest/district_testing.csv)
