### ISSUE TITLE
Hide Top Districts for States like Telangana with No District info available.

### ISSUE THREAD

**Issue by BhargavSatya** [covid19india/covid19india.github.io#2307]
**Describe the bug**
A clear and concise description of what the bug is. If your issue is regarding an error in the data, it's best reported through [this form](https://forms.gle/MLeSrdwRuf8AjFkp9).

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by shuklaayush** [comment]
Follow the issue template

**Comment by shuklaayush** [comment]
Follow the issue template
