### ISSUE TITLE
Negative Active Cases in Bar Graph

### ISSUE THREAD

**Issue by ksasan** [covid19india/covid19india.github.io#2309]
See the right bottom Graph in attached image. The graph has negative bar entries as well for Active Cases (in Delhi), which is not possible. Formulae needs revisiting.

1) Goto Home Page
2) Click Delhi -> Details
3) See below 

**Expected behavior**
Active cases should always be >= 0

**Screenshots**
![image](https://user-images.githubusercontent.com/9150010/89706889-5c441700-d987-11ea-8d30-f5e118100638.png)

Desktop:
- OS: Ubuntu 18.04
- Browser Chrome
- Version 81.0.4044.129

**Comment by shuklaayush** [comment]
Refer to https://github.com/covid19india/covid19india-react/issues/2038#issuecomment-641962963
