### ISSUE TITLE
Direct access to URL /clusters not available or shows blank page

### ISSUE THREAD

**Issue by Thedijje** [covid19india/covid19india.github.io#231]
**Describe the bug**
When navigation to `/clusters` from home page, it works fine. If i share someone direct URL `/clusters`, it either shows a page with lots of errors and most of the time its just blank page.

**To Reproduce**
1. Go to 'https://www.covid19india.org/clusters'

2. See the blank page.
3. If navigated through home page, it works absolutely fine.

**Expected behavior**
Should open full page without an error or blank page. 

**Screenshots**
https://www.covid19india.org/clusters
![image](https://user-images.githubusercontent.com/1737771/77752024-c7322880-704c-11ea-8579-4ad28457a845.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 80

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by shuklaayush** [comment]
Seems to be working fine for me. Can you recheck?

**Comment by syntnc** [comment]
Checked with the same specs, wffm. Please recheck this issue.

**Comment by Rajesh-Narayanappa87** [comment]
Same to me as well.. though there are some warnings, loading isn't halted..

**Comment by shuklaayush** [comment]
Closing this for now. Will reopen if the issue resurfaces.
