### ISSUE TITLE
UI Issue

### ISSUE THREAD

**Issue by Achal1607** [covid19india/covid19india.github.io#2311]
**Description**
The history of cases timeline and suggestions for search bar coincide with each other.
 
**To Reproduce**

1. Go to 'Go to any date in history'
2. Click on 'search bar'
3. See error

**Expected behavior**
A clear distinction should be seen between suggestions and timeline

**Screenshots**
![Screenshot (4)](https://user-images.githubusercontent.com/55803675/89895956-425e3a80-dbfa-11ea-82d4-d09329153748.png)
![Screenshot (6)](https://user-images.githubusercontent.com/55803675/89895965-45592b00-dbfa-11ea-8f21-c7d124b69566.png)

**Comment by shuklaayush** [comment]
Duplicates #2225
