### ISSUE TITLE
Detail Information of Country

### ISSUE THREAD

**Issue by RamolaWeb** [covid19india/covid19india.github.io#2313]
**Is your feature request related to a problem? Please describe.**
It will be great to add information like recovery ratio, active ratio, case fertility ratio, and average growth ratio for India similar to the state.

**Describe the solution you'd like**
The same UI showed in the State details page can be used here.

**Comment by shuklaayush** [comment]
Check out this button 

![Peek 2020-08-11 20-44](https://user-images.githubusercontent.com/27727946/89915120-988ba780-dc13-11ea-8deb-2c67a50a9686.gif)
