### ISSUE TITLE
Active cases delta

### ISSUE THREAD

**Issue by yrvenkat** [covid19india/covid19india.github.io#2314]
**Is your feature request related to a problem? Please describe.**
No, Just a nice to have.

**Describe the solution you'd like**
It would be nice to have Active case changes delta. Ex. If 5 nos decreased in active we can show it in green. If 5 nos increased in active we can show it in red with count.

**Describe alternatives you've considered**
--

**Additional context**
--

**Comment by shuklaayush** [comment]
Refer to https://github.com/covid19india/covid19india-react/issues/2105#issuecomment-641833409
