### ISSUE TITLE
Question - What is the difference between maps and projected_maps ?

### ISSUE THREAD

**Issue by alkuhlani** [covid19india/covid19india.github.io#2316]
What is the difference between [maps](https://github.com/covid19india/covid19india-react/tree/master/public/maps) and [projected_maps](https://github.com/covid19india/covid19india-react/tree/master/public/projected_maps)

I have a map for my country in the last covid19india editions, they work fine, but now after you update the covid19india, my maps do not work, and I don't know what is the difference between them.

How can I convert my maps to projected_maps?

Thank you in advance!

**Comment by shuklaayush** [comment]
`maps` contain the raw map files where each value corresponds to a lat/long coordinate.
`projected_maps` contains a pre-projected Mercator projection of these maps onto a fixed size canvas. Here, each value corresponds to the x/y coordinate of the map after projection onto the canvas. Check out [this script](https://github.com/covid19india/covid19india-react/blob/master/scripts/project-maps.sh)

**Comment by alkuhlani** [comment]
@shuklaayush thank you for your replay, 

Could you please provide me with any way to convert my maps to be a fixed size canvas.
for example how ydo ou change this file https://github.com/covid19india/covid19india-react/blob/master/public/maps/india.json to be this https://github.com/covid19india/covid19india-react/blob/master/public/projected_maps/india.json
because I have this file https://github.com/alkuhlani/Yemen-JSON-Map/blob/master/yemen_admin0_ploygons.topojson (my country map) but I can not convert it to be a projection.

Thank you in advance

**Comment by alkuhlani** [comment]
@shuklaayush 
Okay thank you I check the script, and it does the mission, thank you again for your replay.

**Comment by alkuhlani** [comment]
@shuklaayush 
I tried to **bash** the script project-maps.sh but I get these errors:
topomerge: command not found
topo2geo: command not found
geoproject: command not found
geoproject: command not found
Also I tried to install them by npm install - but I get errors again

Note: I delete the maps in the projected_maps before I start the **bash**

Is there are another way to run the project-maps.sh file

Thank you in advance
