### ISSUE TITLE
Question -  Source of Shape Files

### ISSUE THREAD

**Issue by ShadabFaiz** [covid19india/covid19india.github.io#2317]
What is the source of Shapes files that the project is using for plotting India map and district maps ?

**Comment by guneetnarula** [comment]
@ShadabFaiz the admin boundaries are sourced from state/district government gazettes wherever possible, or from block level or ward level maps in some cases, and then digitized by the datameet.org community. The one's that have been used here are for visualizations only and are not super accurate.
