### ISSUE TITLE
Site Crashing Arbitrarily with " ChunkLoadError: Loading chunk 27 failed ".

### ISSUE THREAD

**Issue by abbhhiisseek** [covid19india/covid19india.github.io#2318]
[**Describe](url) the bug**
Site crashing arbitrarily with  ChunkLoadError: Loading chunk 27 failed ".

**To Reproduce**
1 ) Hit the site URL
2) Try to scroll down.
3) Site crashes.

**Expected behavior**
 Contents should load.

**Screenshots**
[
![Capture](https://user-images.githubusercontent.com/27771780/90313628-a438e000-df2b-11ea-842b-e4ecd804e36c.PNG)
](url)

**Desktop (please complete the following information):**

- OS: Windows 7 and 10
- Browser Chrome Version 84.0.4147.125 (Official Build) (64-bit) 
                Mozilla Version 79.0 64-bit)
-

**Comment by shuklaayush** [comment]
I'm guessing it's because the browser is looking for old chunks which have been cleaned up. A refresh should usually solve this.

/cc @JunaidBabu

**Comment by JunaidBabu** [comment]
I've also felt this when there is a new build. I think we should disable the CLEAN field in the build workflow for some time.

**Comment by abhisharkjangir** [comment]
@shuklaayush I think if a major chunk is failing to load then it should reload the page automatically.

**Comment by shuklaayush** [comment]
This might've been because of dynamic imports (check [this](https://medium.com/@botfather/react-loading-chunk-failed-error-88d0bb75b406)). I added a retry to all dynamic imports in 9b53879ef29fc3aefe1f11f039f0af0227d9dee4 so this should be fixed
