### ISSUE TITLE
"Unassigned" State in States Dropdown

### ISSUE THREAD

**Issue by kashyapkaki** [covid19india/covid19india.github.io#2323]
**Describe the bug**
An "Unassigned" State appears in States Dropdown in Spread Trends Section.
By selecting that dropdown, incorrect data appearing in Maps and Charts as well. 
Refer the screenshot for reference.
![image](https://user-images.githubusercontent.com/30841403/90487034-8223a580-e157-11ea-853c-1cbabd8090d9.png)

**To Reproduce**

1. Go to 'Homepage' or'Dashboard'.
2. Click on State dropdown in Spread Trends Section.
3. Scroll straight to down.
4. You can find Unassigned State in that dropdown.

**Screenshots**
Dropdown:
![image](https://user-images.githubusercontent.com/30841403/90487949-c6637580-e158-11ea-8e7d-495b8aa3459d.png)
Charts:
![image](https://user-images.githubusercontent.com/30841403/90488051-ee52d900-e158-11ea-8193-7ad55fe973ec.png)
Map:
![image](https://user-images.githubusercontent.com/30841403/90488116-088cb700-e159-11ea-92df-2ce4939fd7d9.png)

**Additional context**
If you feel this Issue as worth fixing, accept the issue and assign to me. I would like to work & fix that.

**Comment by shuklaayush** [comment]
Duplicates #2018. It has to be kept in the historical data to maintain consistency
