### ISSUE TITLE
Toggling the languages options on clicking current language in sidebar

### ISSUE THREAD

**Issue by akash-jain-toppr** [covid19india/covid19india.github.io#2331]
Clicking on the current language on the side bar does not close the select language menu.

**To Reproduce**

1. click on the current language on the side bar.. it open the menu to select the language.
2. clicking on the current language on the sidebar does not close the menu.

**Expected behavior**
clicking on the current language on the sidebar if the select language menu is open then it should close.

**Comment by priyanshshah1997** [comment]
i've reviewed it and saw that, whenever as user click the on the language selected button, and at the moment languageSwitcher menu is open, and when a user clicks the button then there are two **set Change** events, which makes the **_showLanguageSwitcher_** from false to true. which eventually doesn't doesn't closses the languageSwitcher

i want to work on this issue.

/claim

**Comment by priyanshshah1997** [comment]
i've resolved the issue in my local machine, please asssign me the task, so that i can push the my branch and i can PR.

**Comment by priyanshshah1997** [comment]
#2335 @ #2335 please check the PR request

**Comment by shuklaayush** [comment]
Fixed via b5bdd8ea191ab5c18ac09c7d9672d1414bd0247f
