### ISSUE TITLE
Allow inter-state navigation when viewing state details

### ISSUE THREAD

**Issue by SahilRS200** [covid19india/covid19india.github.io#2332]
**Is your feature request related to a problem? Please describe.**
Currently when we click "see more details" on a state, it navigates to the state page. To see another state, we need to go back and select the state

**Describe the solution you'd like**
We would like to see a paginated view, so that we can navigate to the previous or next state without needing to go back.
We can also add a jump to optin

**Describe alternatives you've considered**
There is no other way to jump to another state without intuitively guessing state code or navigating back

**Additional context**
![image](https://user-images.githubusercontent.com/31073493/91535444-c883bc00-e930-11ea-9916-f8788f4c8789.png)

I would be happy to take this change up

**Comment by shuklaayush** [comment]
There is actually a way 

![Peek 2020-08-28 14-18](https://user-images.githubusercontent.com/27727946/91541128-78f5be00-e939-11ea-9bfb-254115153585.gif)

**Comment by sahil-sheikh-jdas** [comment]
Oh.. perhaps a dropdown arrow could help.. i never thought of clicking the title.
Thanks for the info
