### ISSUE TITLE
Can we improve the version of react-spring to v9?

### ISSUE THREAD

**Issue by whitesky1225** [covid19india/covid19india.github.io#2336]
**Describe the enhancement** 
v9 api is more convenient and allows for more compact, less distracting code. 
For example, the component named Timeline.js use react-use-gesture and react-spring,  but it's inconvenient to use react-use-gesture with react-spring that is of version v8.

[Reference link](https://use-gesture.netlify.app/docs/introduction)

**Comment by shuklaayush** [comment]
Hey
We tried migrating to `react-spring` v9 a couple of months ago but had some difficulties. Would be great if you could raise a PR. /available

**Comment by adrijshikhar** [comment]
I would like to contribute to this issue but I am unable to claim it.

**Comment by bee-rickey** [comment]
> I would like to contribute to this issue but I am unable to claim it.

@adrijshikhar because it's already claimed.

**Comment by whitesky1225** [comment]
> I would like to contribute to this issue but I am unable to claim it.

I'm too busy on working to handle it by myself, can we handle it together?
