### ISSUE TITLE
Negative values in active cases graph

### ISSUE THREAD

**Issue by abde1992** [covid19india/covid19india.github.io#2337]
**Describe the bug**
![image](https://user-images.githubusercontent.com/2977369/92653852-3ba50f00-f2ef-11ea-91e2-009c3e188a72.png)

The active cases graph shows negative numbers.

**To Reproduce**
https://www.covid19india.org/state/RJ
Go to a state with relatively low number of cases such as this one. Select a city such as Jaipur.

**Expected behavior**
Numbers expected to be positive. Or at-least an explanation of how the active cases are arrived at (is it the difference of new confirmed cases and recovered cases or something else?)

**Comment by shuklaayush** [comment]
Refer to https://github.com/covid19india/covid19india-react/issues/2038#issuecomment-641962963
