### ISSUE TITLE
Enhancement: Additional graph of (No. of infections) / (No. of tests) for each day

### ISSUE THREAD

**Issue by Anshuman04** [covid19india/covid19india.github.io#2338]
**Need of this enhancement:**
I have observe that no. of tests done vary a lot (like there is drop in testing for every 7th day) which actually distorts the way we interpret no. of infected cases .
For Ex: day1: 5 infected case when 10 tests were done, day2: 5 infected case when 5 tests were done.

There should be a graph that do not shadows the info that infection is increasing.

**Solution:**

Additional graph where we plot (No. of infections/ No. of tests * 100) vs time.

**Comment by ayushsrivastav0811** [comment]
hi

**Comment by Anshuman04** [comment]
Hey...

Any issues in understanding the requirement?


Regards,
Anshuman

**Comment by karishnu** [comment]
I suggest this be done in the stats section over a 7 day period since number of tests are not updated regularly and are correct over larger periods of time (atleast for Mumbai)

**Comment by shuklaayush** [comment]
Duplicates #2199
