### ISSUE TITLE
Circle size not correct

### ISSUE THREAD

**Issue by DheeruYS** [covid19india/covid19india.github.io#2339]
If you see the circle circle map of india , 

there we can see bengaluru has a big circle and chennai has a really small circle tho the difference is not much
I think there is a issue 

Please check 
Thanks

**Comment by shuklaayush** [comment]
The difference is of 30,000. Use the map for confirmed if you want to compare the value of confirmed cases.

![Peek 2020-09-13 05-00](https://user-images.githubusercontent.com/27727946/93006792-46c19e80-f57e-11ea-8ed9-df53ec7dd791.gif)
