### ISSUE TITLE
Idea: Integrate the globe visualization

### ISSUE THREAD

**Issue by dhruv10** [covid19india/covid19india.github.io#234]
**Is your feature request related to a problem? Please describe.**
Currently, `covid19india` doesn't depict the seriousness of the problem in a visual manner which should be easy to understand by an average joe. Exponential graphs are not much relatable to a wider audience especially with rural areas or non-mathematical minds, etc.

**Describe the solution you'd like**
I would like to integrate another open-source project with the same objective.

[Corona Viz ](https://coronaviz.netlify.com/) visualizes the planetary distribution of COVID19 with real-time statistics with an objective to remind people to stay inside & prevent the whole planet from becoming red. This viz shows the global pandemic from a bird's eye view and people get to know how serious it is. This project GitHub repository sits [here](https://github.com/dhruv10/coronaviz).

**Additional context**
I would like to collab with your data and make it granular to the state or district level. We can even make it generic can allow people to add data for other countries as well based on crowd-sourced data.
This would bring even more traction to the project.

Here is an image of the viz:

![image](https://user-images.githubusercontent.com/32517802/77763965-e25b6300-7061-11ea-85b9-f316d3f50b52.png)

**Comment by shivamkansal** [comment]
Nice Suggestion.
The visualization of data will be a great help to make this project engaging and interesting.
Comparisons in the increase of cases wrt the population in a region also help to analyze the scenario the situation.

**Comment by sudevschiz** [comment]
Hi, Great suggestion! It would be so cool.

However, this would be out of our scope. Please feel free to use our data to work on this. Thank you.

Closing.
