### ISSUE TITLE
UI: Missing heart icon in Active section of the state-wise view.

### ISSUE THREAD

**Issue by whoque** [covid19india/covid19india.github.io#2342]
**Describe the bug**
In the state-wise view, the heart icon is missing in the active section just above the active count.

**To Reproduce**

1. Click on any state to expand for options.
2. Click on 'See more details on <STATE NAME>'
3. See the active section for the missing icon.

**Expected behavior**
A blue colored heart icon should be present in the active section just like for other sections.

**Screenshots**
![image](https://user-images.githubusercontent.com/39428121/93089321-c3589800-f6b8-11ea-9bd7-c7cd2d67d4f1.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser : Chrome
- Version : 85.0.4183.102

**Comment by satyakam3156** [comment]
The above issue was reflecting due to the presence of a check condition which used to render the '\u00A0' character. Removing the condition has resolved the issue.
PR number #2346

**Comment by shuklaayush** [comment]
Refer to https://github.com/covid19india/covid19india-react/issues/2105#issuecomment-641833409

**Comment by whoque** [comment]
This was my very first contribution to open source.
Thanks @shuklaayush for closing it.
I know its verrry insignificant but its a start :)
