### ISSUE TITLE
Overlapping Graph text and graph bar. 

### ISSUE THREAD

**Issue by tshrwbl** [covid19india/covid19india.github.io#2347]
**Describe the bug**
Minor UI bug.

**Expected behaviour**
Text and graph bar should not overlap.

**Screenshots**
![image](https://user-images.githubusercontent.com/27141947/94337424-d009b400-0007-11eb-9e7b-8404eb6d07a4.png)

**Desktop (please complete the following information):**
- OS: Windows 10
- Browser: chrome
- Version  85.0.4183.121

**Comment by shuklaayush** [comment]
Duplicates #1650
