### ISSUE TITLE
Question on APIs

### ISSUE THREAD

**Issue by kuharan** [covid19india/covid19india.github.io#2348]
Hello,

I want to know which API this app is using to display daily counts (confirm, recover, decease, active) for district wise results. I found this [National/State/District Level : Latest cumulative/daily counts](https://api.covid19india.org/v4/data.json) but its cumulative. This [National/State/District Level : Specific date cumulative/daily counts](https://api.covid19india.org/v4/data-YYYY-MM-DD.json) has 404 status.

**Comment by shuklaayush** [comment]
This: `https://api.covid19india.org/v4/data.json`.  Example:
![image](https://user-images.githubusercontent.com/27727946/94427659-12b8c100-01ad-11eb-8ee7-7534d692f03b.png)

The `YYYY-MM-DD` in `https://api.covid19india.org/v4/data-YYYY-MM-DD.json` represents the date. As an example, try [`https://api.covid19india.org/v4/data-2020-07-26.json`](https://api.covid19india.org/v4/data-2020-07-26.json).
