### ISSUE TITLE
Why is the change in Number of Active Cases not displayed?

### ISSUE THREAD

**Issue by unmesh-shukla** [covid19india/covid19india.github.io#235]
https://github.com/covid19india/covid19india-react/blob/309c48f613c51b5cc2222b78587df20844977dcf/src/components/level.js#L46

**Comment by Rajanpandey** [comment]
I think it might be related to this: https://github.com/covid19india/covid19india-react/issues/168

**Comment by shuklaayush** [comment]
Please refer #226. It was intentionally removed since it was causing a bit of confusion. Closing.
