### ISSUE TITLE
Add appropriate Badges to the project for better viewer understanding and documentation

### ISSUE THREAD

**Issue by krithikha2001** [covid19india/covid19india.github.io#2352]
### **Is your feature request related to a problem? Please describe.**
The readme file of this project is not properly done.Adding badges could increase efficiency of code

**Describe the solution you'd like**
Badges can improve the readability of a GitHub repository because they provide the users with a quick way to collect metrics about the repository.

**Comment by krithikha2001** [comment]
I would like to work on this issue

**Comment by shuklaayush** [comment]
Thanks for creating an issue, but I don't think this adds much value
