### ISSUE TITLE
Alignment of the Active/ Confirmed/ Deceased/ Recovered on main page broken.

### ISSUE THREAD

**Issue by nischalsamji** [covid19india/covid19india.github.io#236]
![image](https://user-images.githubusercontent.com/887091/77767877-b5aa4a00-7067-11ea-91f2-d6799967d0ab.png)

The first two categories appear higher than the next two.

**Comment by shuklaayush** [comment]
I'm not sure what you're referring to. Seems fine to me.

![image](https://user-images.githubusercontent.com/27727946/77769406-cc51a080-7069-11ea-8206-56f860eb3109.png)

**Comment by nischalsamji** [comment]
It looks okay now. My be I was zoomed in/ out.
![image](https://user-images.githubusercontent.com/887091/77771107-48e57e80-706c-11ea-96fb-0d138c6651c9.png)
