### ISSUE TITLE
The navigation panel appears to be behind all the elements in mobile sized screens.

### ISSUE THREAD

**Issue by abhinavkrin** [covid19india/covid19india.github.io#2364]
**Describe the bug**
In small screens, the navigation pane appears to be behind all the other elements in the start. Though after some time, the navigation panel appears correctly.

**To Reproduce**
1. Open the website in mobile browsers.
2. Click on "menu".

**Expected behavior**
The navigation panel should be displayed on top.

**Screenshots**
![alt text](https://i.ibb.co/BZyrkn1/www-covid19india-org-Moto-G4.png)

**Comment by shuklaayush** [comment]
Spooky. Should be fixed via 234d2daa2f45f7b0a5cbc19865d2e2afa4f337b0
