### ISSUE TITLE
Text and chart bars are overlapping in Daily growth chart under Spread Trends

### ISSUE THREAD

**Issue by nikhilcheke** [covid19india/covid19india.github.io#2368]
**Describe the bug**
When we click on "Daily" button under spread trends and select "India" in drop down list, in the charts for "confirmed", ""active", "recovered" etc. there is an overlapping between chart heading/statistic details and chart bars(which shows the number of patients)

**To Reproduce**

1. Go to 'Spread Trends'
2. Click on 'Daily' button
3. Select Scale Modes either as uniform or not uniform
4. Select 'India' in drop down list
5. See the overlapping for 'confirmed', 'active', 'recovered' charts

**Expected behavior**
There should not be any overlapping in the chart area

**Screenshots**
<img width="556" alt="Screenshot 2020-10-07 at 10 37 00 AM" src="https://user-images.githubusercontent.com/24985664/95290164-399c8480-088a-11eb-923e-b919ed10a4af.png">

<img width="562" alt="Screenshot 2020-10-07 at 10 46 10 AM" src="https://user-images.githubusercontent.com/24985664/95290592-3f469a00-088b-11eb-98c1-c5db54882811.png">

**Desktop (please complete the following information):**

- OS: Mac OS
- Browser: Chrome
- Version:  81.0

**Smartphone (please complete the following information):**

- Device: OnePlus
- OS: Android
- Browser: FireFox
- Version: 68.11.0

**Comment by K-Phaneendra** [comment]
Hey team, here is the fix for this issue, kindly mark this as "Available". I can submit my PR on this.

Here is my work sample

![image](https://user-images.githubusercontent.com/33480024/95378735-f67df800-0901-11eb-916f-206e8c5333b0.png)
