### ISSUE TITLE
Sikkim test per million is suddenly zero

### ISSUE THREAD

**Issue by i-anuragmishra** [covid19india/covid19india.github.io#2373]
**Describe the bug**
Sikkim Test per million is reduced to 0(Zero).

**To Reproduce**

1. Go to 'the covid19.org website'
2. Click on 'Sikkim more details'
3. Scroll down to 'test per million'

**Expected behavior**
The test per million of Sikkim is released by the govt and was also there on website till yesterday, but now test per million in Sikkim is showing zero.

**Screenshots**
![image](https://user-images.githubusercontent.com/50531324/96026282-ede27000-0e73-11eb-9e9e-8c21b9cb476e.png)

**Desktop (please complete the following information):**

- OS: [Mac os]
- Browser [chrome]

**Comment by shuklaayush** [comment]
Seems to be fixed
