### ISSUE TITLE
District wise cases for Assam

### ISSUE THREAD

**Issue by sanyam-git** [covid19india/covid19india.github.io#2379]
The website says that the state bulletin does not provide district wise data. The district wise data is available at https://covid19.assam.gov.in/all-districts/. I myself would have made the change, but I'm not that familiar with the code yet. And this should be added as soon as possible. Thanks !
![assam](https://user-images.githubusercontent.com/43791665/97069011-82726e00-15ea-11eb-85d8-273e4c484fef.png)

**Comment by shuklaayush** [comment]
It's better if you can create an issue in the [API repository](https://github.com/covid19india/api). Anyways, @bee-rickey @sudevschiz you might want to have a look

**Comment by sanyam-git** [comment]
moved to [API repository](https://github.com/covid19india/api/issues/433) as suggested by @shuklaayush
