### ISSUE TITLE
website doesn't scale properly in tablet/pc screens

### ISSUE THREAD

**Issue by ar363** [covid19india/covid19india.github.io#238]
The website doesn't scale properly in tablet/pc screens

Here are screenshots from 10.1 inch tab:-

![Screenshot_2020-03-27-22-33-11](https://user-images.githubusercontent.com/49993491/77781377-77b72100-707b-11ea-88fe-a80505a25d0c.png)

![Screenshot_2020-03-27-22-32-46](https://user-images.githubusercontent.com/49993491/77781384-7a197b00-707b-11ea-96bb-f104f6371089.png)

I can fork the project and fix the issues by tomorrow afternoon

**Comment by shuklaayush** [comment]
Related to #200. Can you confirm if the same happens in portrait orientation as well? And whether it fixes with a refresh? Thanks!

**Comment by JunaidBabu** [comment]
Clusters is a different project: https://github.com/someshkar/covid19india-cluster
Please report there

**Comment by ar363** [comment]
> Related to #200. Can you confirm if the same happens in portrait orientation as well? And whether it fixes with a refresh? Thanks!

The issue gets fixed in potrait orientation. It remains same after refresh and in other landscape devices
