### ISSUE TITLE
Daily active cases are showing negative in graph

### ISSUE THREAD

**Issue by riteshkr54** [covid19india/covid19india.github.io#2385]
Daily active cases shown for state is negative for some dates, most probably due to wrong formula being assigned (daily positive- daily recovered ??) instead of total postive - total recovered till that day

**Comment by harirajv** [comment]
@riteshkr54 Could you please share a screenshot of it?

**Comment by riteshkr54** [comment]
![dailyactive2](https://user-images.githubusercontent.com/31988503/102994774-b8c65e00-4545-11eb-8b53-9a9cdfd78cb9.png)
![dailyactive1](https://user-images.githubusercontent.com/31988503/102994779-bcf27b80-4545-11eb-88ee-09732c72e51c.png)

**Comment by TheTrio** [comment]
If you want to see `total positive - total recovered`, click on the Cumulative tab. Daily shows `new positive - new recovered`, which can certainly be negative.

**Comment by ShikariShambuJr** [comment]
In case recovered cases and deceased cases are more than the confirmed cases on that particular day the graph will go in negative

**Comment by shuklaayush** [comment]
Refer to https://github.com/covid19india/covid19india-react/issues/2038#issuecomment-641962963
