### ISSUE TITLE
Count going out of screen

### ISSUE THREAD

**Issue by SingingApple** [covid19india/covid19india.github.io#2388]
**Describe the bug**
The number of confirmed cases are not completely visible now. 

**Expected behavior**
Confirmed cases should be visible within the site container. 

**Screenshots**
![Screenshot_2020-12-19-01-21-40-678_com.android.chrome.jpg](https://user-images.githubusercontent.com/39864404/102655924-19961500-4199-11eb-9556-d94d2fd2a460.jpg)

**Comment by grahanpurush** [comment]
brother though I am new here, I support your dedication. Salute you.
