### ISSUE TITLE
Regarding Mutated Virus Cases in India

### ISSUE THREAD

**Issue by Shubham0324** [covid19india/covid19india.github.io#2392]
In past days Sars Cov-2 virus cases are increasing in India and people visiting a website do not know which district or states the spread is.

It is better to mark **states either in a different colour** for direct understanding or give **Normal Case + Sars Cov-2** confirm case pattern or **give the necessary information in the information icon next to the state name**. This way we can give better information and helps control the spread.

You can assign it to me also if you feel this is a good issue and I of any help.

**Comment by sambhavsaxena** [comment]
I would like to work on this issue
Please assign

**Comment by bee-rickey** [comment]
We don’t plan to do this since we do not anticipate these numbers being published over a longer period of time
