### ISSUE TITLE
Add a columns Showing Vaccines Distributed!

### ISSUE THREAD

**Issue by jain** [covid19india/covid19india.github.io#2395]
Currently the amount of vaccines administered are not being tracked, and I am sure this is a statistic many people would like to see. It would be great to get this information and display it on the site, ideally another column like tested.

**Comment by ShikariShambuJr** [comment]
Hi, We've seen vaccination summary data published. Will wait to see the format and frequency at which this is published in coming days and decide the best way to represent on the site.
