### ISSUE TITLE
No of people vaccinated state wise

### ISSUE THREAD

**Issue by kuharan** [covid19india/covid19india.github.io#2397]
This is a feature request related to no of vaccinated candidates, if the data is available in some api.

This feature will show the no of people vaccinated beside confirm active recovered and deceased. 

This will add a huge benefit to all whoever is still tracking the information on this website.

**Comment by ShikariShambuJr** [comment]
Refer Here- https://twitter.com/covid19indiaorg/status/1355558760354205696?s=20
