### ISSUE TITLE
Graphs required

### ISSUE THREAD

**Issue by shaunmulark** [covid19india/covid19india.github.io#24]
Guys we need much more visualisations
 #Every existing graphs must have a log scale.
1. Total cases vs vs recovered ones
2. Total cases vs deceased ones 
3. Recovery rate vs Death Rate ( its going to be importannt in the coming time)
4. Most importantly we need a compare option with other countries; baseline being the first case reported/confirmed/deceased.

**Comment by sudevschiz** [comment]
1. Is already available.
2. Available
3. Percentage could be an addition
4. This is out of our scope. We can't focus on getting data about other countries etc.
