### ISSUE TITLE
Upon changing the filter the incorrect state is displayed expanded 

### ISSUE THREAD

**Issue by gosharmaa** [covid19india/covid19india.github.io#240]
**Describe the bug**
If state (let's say at position 3 ) is expanded by user and after that a filter is added > Incorrect state is displayed as expanded

**To Reproduce**
1. Go to Dashboard
2. Click on any state to expand let's say the state on 3rd Position
3. Change the order by applying filter ( let's say by recovered )
4. Notice that the order of states have changed now but the expanded state is still the 3rd State instead of the state which was expanded by the User.

**Expected behavior**
State which was expanded by the user should be displayed as expanded after any filter

**Smartphone (please complete the following information):**
 - Device: [OnePlus 7t]
 - OS: [Android 10]
 - Browser [I used Chrome]

**Comment by shuklaayush** [comment]
Nice catch! Though it seems a bit more complicated than the state at the same index being expanded.

![Peek 2020-03-27 23-43](https://user-images.githubusercontent.com/27727946/77787078-f06eab00-7084-11ea-9dc5-d0587d04f397.gif)

**Comment by sadarshannaiynar** [comment]
Can I work on this?

**Comment by sadarshannaiynar** [comment]
#245 PR Raised
