### ISSUE TITLE
Page does not load

### ISSUE THREAD

**Issue by himanshub16** [covid19india/covid19india.github.io#2400]
**Describe the bug**
The page does not load on opening, due to some errors (see screenshot)

**To Reproduce**

1. Go to "https://covid19india.org"
Page does not load

**Expected behavior**
Page should load

**Screenshots**
![image](https://user-images.githubusercontent.com/14041572/106357362-b10b8d80-632b-11eb-9c96-579dcfab76e7.png)

**Desktop (please complete the following information):**

- OS: Mac OS
- Browser Chrome
- Version 88.0.4324.96

**Comment by shuklaayush** [comment]
Should be fixed now
