### ISSUE TITLE
Add new fields for main dashboard

### ISSUE THREAD

**Issue by RahulMR42** [covid19india/covid19india.github.io#2404]
Would it possible to add two more fields to get more accurate and positive view with 

- % test positivity ( as it has the test count and positive case hopefully it would be easy).

- % detection rate ,like what is the % of cases per X numbers (100 or 1000) of cases were tracked

**Comment by Akshantjain** [comment]
I think these features are already there in the dashboard with name "Test positivity Ratio".
<img width="1279" alt="image" src="https://user-images.githubusercontent.com/34630484/109217862-021c6f00-777c-11eb-946a-e779cc8c29a4.png">

And for the detection rate, there is already one with cases per 10L.
