### ISSUE TITLE
Vaccine Data is ambiguous. 

### ISSUE THREAD

**Issue by panwarab** [covid19india/covid19india.github.io#2406]
It should separately show the first dose administration count and second dose administration count for better clarity.

**Comment by srikanthlogic** [comment]
There is a detailed vaccination data put out by CoWIN - from 08 March 2021 onwards.

Data for each day updated as of 6 PM IST, change the date parameter. A proper data archiving / visualization design that scales needs to be worked on.

* All India Statistics - Summary at state level - https://api.cowin.gov.in/api/v1/reports/v2/getPublicReports?state_id=&district_id=&date=2021-03-08
* Statewise Statistics - Summary at district level  - https://api.cowin.gov.in/api/v1/reports/v2/getPublicReports?state_id=22&district_id=&date=2021-03-08
* Districtwise Statistics - Summary at vaccination site level - https://api.cowin.gov.in/api/v1/reports/v2/getPublicReports?state_id=22&district_id=400&date=2021-03-08

**Comment by ShikariShambuJr** [comment]
We are adding and archiving all the data points on State,District and All India Wise. You can have a look at Cowin Sheets at StateWise (http://api.covid19india.org/csv/latest/cowin_vaccine_data_statewise.csv)
District Wise (http://api.covid19india.org/csv/latest/cowin_vaccine_data_districtwise.csv)
