### ISSUE TITLE
Graphs,Data shifts to the left in potrait view

### ISSUE THREAD

**Issue by anmol-gh** [covid19india/covid19india.github.io#2414]
![Screenshot_20210403-211703_Chrome](https://user-images.githubusercontent.com/75087252/113483817-f5014700-94c2-11eb-8325-207d692a28c1.jpg)
The window cannot be scrolled to see the data of states if we open the entire data which contains vaccination status active ratio and so on.

**Comment by sambhavsaxena** [comment]
i would like to work on this issue

**Comment by anmol-gh** [comment]
Great let me know if any changes have been approved,I will be happy to test it out.

**Comment by shuklaayush** [comment]
Fixed via 886b39a379f1b4dfa7135abd99941ed6c60ae37d. Thanks for reporting!
