### ISSUE TITLE
Add vaccination data source

### ISSUE THREAD

**Issue by humble-barnacle001** [covid19india/covid19india.github.io#2417]
**Describe the solution you'd like**
The source of the vaccination could be put as a link here: 
![image](https://user-images.githubusercontent.com/58736240/114127845-b16e6900-9918-11eb-884d-0dfa86981839.png)

**Comment by shubham1532** [comment]
Hello, I want to add source of the vaccination link . please give me this opportunity

**Comment by humble-barnacle001** [comment]
Create a pr

**Comment by ShikariShambuJr** [comment]
Can you describe what will be the use of it?

**Comment by shubham1532** [comment]
Can we use 'a' tag for this.?

**Comment by humble-barnacle001** [comment]
> Can you describe what will be the use of it?

So that we shall be able to directly obtain the data directly from source as well as cross-verify. Also, we can see the first dose and second dose data seperately

**Comment by ShikariShambuJr** [comment]
We are working on separating the doses part on our side.It will rolled out in the coming months. The data is sourced from www.mohfw.gov.in but as the data on the website is dynamic(Changes everyday) there is no use of adding the source here.
