### ISSUE TITLE
Please add Hospital beds available in major cities. 

### ISSUE THREAD

**Issue by Prankurtiwari** [covid19india/covid19india.github.io#2424]
It would be very useful if you people could add number of beds available in the cities or states where there is surge in covid cases.
One of my friend created an API for DELHI only. It would be great if it could be extended to various states or major cities and if possible whole country.
Just a suggestion if you could implement it.

**Comment by priyanshshah1997** [comment]
how would you like to add those section?

**Comment by JigneshWorld** [comment]
Yeah, I was thinking for this same feature.. it would be really helpful to many people now a days.. 

I got these kind of details in PDF for my city - Ahmedabad, Gujarat. (From my WhatsApp groups)

[ALL COVID HOSPITAL NODAL PERSON 06-APR.pdf](https://github.com/covid19india/covid19india-react/files/6329964/ALL.COVID.HOSPITAL.NODAL.PERSON.06-APR.pdf)
[AMC REQUISITIONED HOSPITAL STATUS 16-04-2021 5.00 PM ONLINE.pdf](https://github.com/covid19india/covid19india-react/files/6329965/AMC.REQUISITIONED.HOSPITAL.STATUS.16-04-2021.5.00.PM.ONLINE.pdf)

**Comment by JigneshWorld** [comment]
@Prankurtiwari can you share some insight or reference - how this things are currently working for Delhi?

**Comment by Prankurtiwari** [comment]
@JigneshPatel23 this is the link for the reference
 https://delhifightscorona.in/data/hospital-beds/

@priyanshshah1997 sorry I couldn't understood what you are asking.

**Comment by priyanshshah1997** [comment]
@Prankurtiwari in which page and where to show available beds category?

**Comment by Prankurtiwari** [comment]
@priyanshshah1997  we could add a section for that in the page, not exactly on homepage rather a help/info section to fetch user location and help help to locate nearby hospital with beds available and there contact details. 
Few days back when i was check this app on mobile there was this section but now I couldn't able to find it on web app.

**Comment by ShikariShambuJr** [comment]
There is no source where we can this data in real time that was the reason of no work on this. The data from Delhi App is subjected to adding the data from Staff which is not useful as the situation changes in minutes adn the application is updated every 2 hours I presume.
