### ISSUE TITLE
State wise history timeline data

### ISSUE THREAD

**Issue by GNSubrahmanyam** [covid19india/covid19india.github.io#2425]
**Is your feature request related to a problem? Please describe.**
Yes, I will be very useful if we provide statewise history timeline data and playback feature

https://user-images.githubusercontent.com/18217008/115137408-9223ba00-a043-11eb-8e90-bf0dd76a7e19.mp4

**Comment by ShikariShambuJr** [comment]
Implemented in the latest Build.

**Comment by GNSubrahmanyam** [comment]
@ShikariShambuJr Where i can't see that ?
