### ISSUE TITLE
Adding the list of empty beds for Delhi hospitals ( as of now we can expand for other states with time) 

### ISSUE THREAD

**Issue by ssinha8752** [covid19india/covid19india.github.io#2426]
**Is your feature request related to a problem? Please describe.**
Since there is exponential growth in the number of patients it's very difficult to keep a track record of empty beds. ( in Delhi as of now)  

**Describe the solution you'd like**
Since the API is yet to be built. Delhi government has come up with their website (https://coronabeds.jantasamvad.org/) which is keeping a record of all the beds in Hospitals. We can add an icon right of state name so that people will be redirected to have a look at the empty beds as most of the population is following covid19india.org. It's important to link it till we build our API.

**Describe alternatives you've considered**
Making an API and fetching data from it that would be refreshed accordingly and will be shown in the UI once the user clicks on the state name.

**Additional context**

**Comment by devRawnie** [comment]
Seems a great feature for the current website. Would love to work upon this

**Comment by zippytyro** [comment]
> Seems a great feature for the current website. Would love to work upon this

read the contribution guide @devRawnie use the **"/claim"** feature to claim an issue, after review.
