### ISSUE TITLE
Graph issue

### ISSUE THREAD

**Issue by justshivam** [covid19india/covid19india.github.io#2428]
**Describe the bug**
Daily active cases cannot be negative

**To Reproduce**
Just visit the site😂

**Expected behavior**
Daily active cases should always be positive

**Screenshots**
![Screenshot (30)](https://user-images.githubusercontent.com/59390818/115379448-28e0aa00-a1ef-11eb-8caf-7fa1ab910094.png)

**Desktop (please complete the following information):**

- OS: Windows 10 (20H2)
- Browser: Brave 
- Version: 1.23.71 Chromium: 90.0.4430.72 (Official Build) (64-bit)

**Comment by shuklaayush** [comment]
https://github.com/covid19india/covid19india-react/issues/2038#issuecomment-641962963
