### ISSUE TITLE
Add a resources page for people looking for Oxygen, Remdesivir, Plasma etc

### ISSUE THREAD

**Issue by zippytyro** [covid19india/covid19india.github.io#2429]
**Is your feature request related to a problem? Please describe.**
The site is having a good amount of traffic, add a resources page, people are looking for Oxygen, Remdesivir, Plasma, Meal services, Blood banks, Beds, etc, expanding #2426 

**Describe the solution you'd like**
I've looked for resources that have some data related to this, state or city-wise. Adding them as resources will do the work, API not needed so that they get more exposure. [https://covid19-twitter.in/](https://covid19-twitter.in/) and [https://hydcovidresources.com/](https://hydcovidresources.com/) are examples. And I think there are more resources like this available. I can do the work to find them.

**Describe alternatives you've considered**
People are desperately looking for these things on social media, and other people who have access to these things are posting to help, like on [https://covid19-twitter.in/](https://covid19-twitter.in/). Adding some relevant links/banner on the site may help a lot of people to reach verified sources

**Additional context**
I can get to work to collect some more resources regarding this, government sources will be preferred. These two mentioned above are doing good work, and some doctors have too provided their contact details. It's an expansion of the #2426 issue. 

Thank you!
Shashwat

**Comment by ShikariShambuJr** [comment]
We have collaborated with CovidFyi Today. Browse the website Covid19india.org. We have linked them.
