### ISSUE TITLE
Mobile: UI : Text Overlapping when ANDAMAN AND NICOBAR ISLANDS is selected

### ISSUE THREAD

**Issue by gosharmaa** [covid19india/covid19india.github.io#243]
**Describe the bug**
Header 'Confirmed Cases' overlaps to the placeholder of Deceased cases when state/UT is selected as ANDAMAN AND NICOBAR ISLANDS

**To Reproduce**
1. Select ANDAMAN AND NICOBAR ISLANDS (It's pretty hard to select the Andaman and Nicobar in mobile phone - try to zoom and select)
2. Notice the header 'Confirmed Cases' overlaps to the placeholder of Deceased cases

**Expected behavior**
Should not be any overlaps

**Screenshots**
![Screenshot_20200327-235949](https://user-images.githubusercontent.com/62764438/77788998-46911d80-7088-11ea-9e5b-67302859fe91.jpg)

**Smartphone (please complete the following information):**
 - Device: [OnePlus 7T]
 - OS: [Android 10]

**Comment by kiku511** [comment]
### Suggestion:
Move status boxes under the region name in a row.

####Mock:

**Current Behavior**
![image](https://user-images.githubusercontent.com/22063646/77796265-2fbcdd80-702c-11ea-8e7b-7220ea43910d.png)


**Proposed Behavior**
![image](https://user-images.githubusercontent.com/22063646/77796201-1451d280-702c-11ea-9485-c7f6a3318b08.png)

I can try the fix and send the PR

**Comment by jeremyphilemon** [comment]
Fixed!
