### ISSUE TITLE
List of testing center and vaccination district wise

### ISSUE THREAD

**Issue by abhi31aug** [covid19india/covid19india.github.io#2430]
**Is your feature request related to a problem? Please describe.**
-> we can have list of testing centers and their location: People can get to know the testing centers(different colour coding for RAT and RT-PCR) nearby and get themselves tested.
-> the list of vaccination centers can help people who are planning to walk-in.

**Describe the solution you'd like**
-> There must be government source of database for the list of testing and vaccination centers information. It can be tagged and refreshed daily if there is any update.

**Describe alternatives you've considered**

**Additional context**

**Comment by ShikariShambuJr** [comment]
At cowin.gov.in you can vaccination centres and at icmr.gov.in for testing facilities.
