### ISSUE TITLE
Covid Resource

### ISSUE THREAD

**Issue by pramodgargpkg** [covid19india/covid19india.github.io#2436]
**Problem**
1. No single resource to access all covid related resources. 
2. Currently, all information is scattered on all social media like Facebook Instagram Twitter.
3. People are facing problems with bed availability, oxygen availability.
4. No one knows what to do when they get a positive result. All they try is a home remedy or people mostly panic.

**Solution**
1. Since this website is accessed by many people and this website is already considered trustworthy so it can act as a tool for people for any information related to covid.
2. We can provide all details like bed availability, oxygen availability
3. We can give basic details like what to do when people are tested positive. What type of remedy they can do at home
4. We can publish doctors' videos who are giving suggestions.
5. I believe this website can act as a single point source for all information related to Covid.

**Description**
1. Above features are currently scattered for eg. https://life.coronasafe.network/ acting as hospital beds availability.
2. For doctors' videos/advice - People usually refer WhatsApp which has lost its trust because of false information spreading on it.

**Comment by yogirana5557** [comment]
Can anybody tell me how line graph at top in calculated?

![image](https://user-images.githubusercontent.com/12079020/115954748-517ae380-a510-11eb-8dea-137b20c38ae7.png)

**Comment by Sayan-Nandy** [comment]
> **Problem**
> 
>     1. No single resource to access all covid related resources.
> 
>     2. Currently, all information is scattered on all social media like Facebook Instagram Twitter.
> 
>     3. People are facing problems with bed availability, oxygen availability.
> 
>     4. No one knows what to do when they get a positive result. All they try is a home remedy or people mostly panic.
> 
> 
> **Solution**
> 
>     1. Since this website is accessed by many people and this website is already considered trustworthy so it can act as a tool for people for any information related to covid.
> 
>     2. We can provide all details like bed availability, oxygen availability
> 
>     3. We can give basic details like what to do when people are tested positive. What type of remedy they can do at home
> 
>     4. We can publish doctors' videos who are giving suggestions.
> 
>     5. I believe this website can act as a single point source for all information related to Covid.
> 
> 
> **Description**
> 
>     1. Above features are currently scattered for eg. https://life.coronasafe.network/ acting as hospital beds availability.
> 
>     2. For doctors' videos/advice - People usually refer WhatsApp which has lost its trust because of false information spreading on it.

1. For solution 3&4, maybe write a blog? There's already a feature there. 
2. As for oxygen availability, I don't think the data is available district/state-wise in real time. But I maybe wrong.
3. Bed availability isn't going to help either if we don't specify where the bed is available(i.e. which hospital in the state/district has how many beds) as saying UP has n no. of beds isn't going to help anybody if we don't get specific as to which hospital has how many.

**Comment by pramodgargpkg** [comment]
1. For 2, we can collect data from the administration. Currently, they don't have it. We can create some feature where the administration can provide data in the required format and that can be shared. Something like an android app.
2. For 3, this is what I am suggesting, We will collect data of all hospitals in India and we will update in real-time. We can have volunteers ( at least big hospitals can provide real-time data).

**Comment by pramodgargpkg** [comment]
Please add https://covidfacts.in/ on your website. This seems a genuine website.

**Comment by Aanandgupta** [comment]
> **Problem**
> 
> 1. No single resource to access all covid related resources.
> 2. Currently, all information is scattered on all social media like Facebook Instagram Twitter.
> 3. People are facing problems with bed availability, oxygen availability.
> 4. No one knows what to do when they get a positive result. All they try is a home remedy or people mostly panic.
> 
> **Solution**
> 
> 1. Since this website is accessed by many people and this website is already considered trustworthy so it can act as a tool for people for any information related to covid.
> 2. We can provide all details like bed availability, oxygen availability
> 3. We can give basic details like what to do when people are tested positive. What type of remedy they can do at home
> 4. We can publish doctors' videos who are giving suggestions.
> 5. I believe this website can act as a single point source for all information related to Covid.
> 
> **Description**
> 
> 1. Above features are currently scattered for eg. https://life.coronasafe.network/ acting as hospital beds availability.
> 2. For doctors' videos/advice - People usually refer WhatsApp which has lost its trust because of false information spreading on it.

for this we can devide this into specific route of each district where group of 3/4 people will collect genuine information and put them live on site 
for i can take responsibility of kanpur with group of my friends and same should be followed for all other districts

**Comment by ShikariShambuJr** [comment]
Refer to covid19india.org/resources
