### ISSUE TITLE
District portal

### ISSUE THREAD

**Issue by Aanandgupta** [covid19india/covid19india.github.io#2437]
**Is your feature request related to a problem? Please describe.**
I want to work on one route "/kanpur" which will be of my district kanpur containing verified information of beds and oxygen cylinder  and other medicenes  we were thinking of making a new website for that but it will take time so adding one route for this will work.

**Additional context**

**Comment by hareshpatel1990** [comment]
I think you are talking something like [https://life.coronasafe.network/uttar_pradesh/kanpur_nagar](https://life.coronasafe.network/uttar_pradesh/kanpur_nagar)

**Comment by Aanandgupta** [comment]
> I think you are talking something like https://life.coronasafe.network/uttar_pradesh/kanpur_nagar

yes and thanks for the link
