### ISSUE TITLE
Red alert for covid patients

### ISSUE THREAD

**Issue by Aanandgupta** [covid19india/covid19india.github.io#2438]
As the last years recovery rate was 98Percent people think that they just need to be quarantined when turned positive but thats not the case now people need to be told getting an oximeter and having regular check for that. first people dont check and when they check its too late simmiliar cases are find every where and as they oxygen level goes down to 80's people think its normal and dont get hospitilaized because nothing wrong in human behaviour is found but there lungs get damged and recovering becomes very difficult no news channel  is spreading awareness ABOUT THAT please with red alert mention the importance of oximeter.
when oxygen level goes in 40s even then people can look normal.
and also if oxygen level is below 80 people dont have to wait for rtpcr report which can take 3 days hrct scan is must beacuse it tells about the damage in lungs

**Comment by Sayan-Nandy** [comment]
Again, these infos can be put into the blog(which can be renamed as FAQ or Important Info) section of the website.

**Comment by ShikariShambuJr** [comment]
We have made a telegram group regarding Medical Help(https://t.me/CovidMedHelp) and we do post awareness material on our twitter handle regularly. Do check that out.
