### ISSUE TITLE
implement a symptom checker and add links to the helpful links section

### ISSUE THREAD

**Issue by sainak** [covid19india/covid19india.github.io#244]
**Is your feature request related to a problem? Please describe.**
add a symptom checker so that the users can check if the require examination

**Describe the solution you'd like**
implement a symtom checker than can evaluate the result based on the answers of the users
example:
https://covid.bhaarat.ai/
https://www.apple.com/covid19/

**Describe alternatives you've considered**
for now add the links to these websites in the helpful links

**Additional context**

[![image](https://user-images.githubusercontent.com/46787056/77789225-a4256a00-7088-11ea-8057-2f43760d6678.png)](https://covid.bhaarat.ai/)

[![Screenshot_20200328_000024](https://user-images.githubusercontent.com/46787056/77789460-0ed6a580-7089-11ea-9703-07a5bdb8c1a9.png)](https://www.apple.com/covid19/)

**Comment by manugupta10** [comment]
@aakash714 Please review #250

**Comment by sainak** [comment]
Yeah it's great

**Comment by sudevschiz** [comment]
Maybe we can later add this in "Showcase".
