### ISSUE TITLE
Language Issue: displaying English in some fields, even when other languages are selected

### ISSUE THREAD

**Issue by ghost** [covid19india/covid19india.github.io#2441]
Strangely website is displaying other language when selected for a particular language.
when English is selected some other language is displayed in some fields.
when any other language is selected other than English there are many fields which are displaying other than the selected language .  
[New Microsoft Office Word Document.docx](https://github.com/covid19india/covid19india-react/files/6386235/New.Microsoft.Office.Word.Document.docx)

**Comment by shuklaayush** [comment]
Duplicates #2440
