### ISSUE TITLE
Telangana name being rendered incorrectly in resources page.

### ISSUE THREAD

**Issue by hemanth-kotagiri** [covid19india/covid19india.github.io#2442]
**Describe the bug**
The name of the state Telangana is being rendered as "Telengana" in the resources page.

**To Reproduce**

1. Go to 'resources page'
2. Scroll all the way down
3. See error

**Expected behavior**
I can see from the project structure that these names, links are being directly fetched from this link : `https://api.covid19india.org/crowdsourced_resources_links.json`
And so, I went to the API repository and I didn't find any file as such. Therefore, fixing the name in that file would do the trick.

The expected behaviour would be to render the name of the state as `"Telangana"`.

**Screenshots**
Below is the screenshot of what I am referring to:

![Screenshot from 2021-04-28 12-43-022](https://user-images.githubusercontent.com/24365579/116363423-bc822e00-a820-11eb-8596-d19340c69b35.png)

**Desktop (please complete the following information):**

- OS: Arch Linux 64-bit
- Browser: Brave
- Version Version 1.23.71

**Comment by rajputmahesh** [comment]
Yes to fix, changes required at the API side. 

Telengana Government Should be "Telangana Government"
Independent aggregator - Telengana Should be "Independent aggregator - Telangana"

**Comment by hemanth-kotagiri** [comment]
@maheshdevelop absolutely. I'll raise one over there as well.

**Comment by rajputmahesh** [comment]
> @maheshdevelop absolutely. I'll raise one over there as well.

Sure, I will check how that could be fix

**Comment by hemanth-kotagiri** [comment]
> > @maheshdevelop absolutely. I'll raise one over there as well.
> 
> Sure, I will check how that could be fix

AFAIK, we can't fix it. It comes directly from the server and I have also mentioned the route of which the data is available through. And, in the API Repository as well there is no mention of the link I just pasted. If you have found something, or any other way we can fix it, do let me know here first. Thanks!

**Comment by rajputmahesh** [comment]
> > > @maheshdevelop absolutely. I'll raise one over there as well.
> > 
> > 
> > Sure, I will check how that could be fix
> 
> AFAIK, we can't fix it. It comes directly from the server and I have also mentioned the route of which the data is available through. And, in the API Repository as well there is no mention of the link I just pasted. If you have found something, or any other way we can fix it, do let me know here first. Thanks!

Well this is the JSON - https://api.covid19india.org/crowdsourced_resources_links.json
where changes are required, currently I am not sure where this JSON is, I am configuring API project to understand better

**Comment by bee-rickey** [comment]
There's nothing to fix on the API. This is directly pulled from a google sheet and the same has been corrected. Thank you for notifying the error.

**Comment by hemanth-kotagiri** [comment]
@bee-rickey Exactly, as I said. We as contributors couldn't do anything because the data itself is coming from a different private source. Thanks for elaborating more on the issue. Awesome!
