### ISSUE TITLE
See More Detail Button Position

### ISSUE THREAD

**Issue by adarshsunil** [covid19india/covid19india.github.io#2443]
**Is your feature request related to a problem? Please describe.**
See more Detail Button is almost hidden in all the views, even though expand button shows it.
![gt1](https://user-images.githubusercontent.com/17540187/116371192-c9a31b00-a828-11eb-9e75-b45fb4e30ded.png)

**Describe the solution you'd like**
 Can be positioned to left-side to have a better view both in web and mobile view and reposition the timeline

**Describe alternatives you've considered**
A direct statistics tab would be ideal

**Comment by adarsh500** [comment]
Yes, I agree, a direct link to statistics would be preferred. I would like to work on this.

**Comment by ShikariShambuJr** [comment]
You can also move slightly towards right without clicking on expand to have a view on the Detail Button. The button also works in partial view redirecting to the state page without any issues.
