### ISSUE TITLE
Add documentation what counts as a case and what as a death

### ISSUE THREAD

**Issue by surfmuggle** [covid19india/covid19india.github.io#2446]
**Is your feature request related to a problem? Please describe.**
It is unclear to me how cases (active infections, deaths) are determined. 
On https://www.mohfw.gov.in/ i could not find details about that

**Describe the solution you'd like**
If possible document what counts as a case. For example a case is every person with a confirmed positive rtPCR-test result or someone who has antibodies.
Some countries also count a close contact to a confirmed case as a case. 

**Describe alternatives you've considered**
This information could be added to the readme or as a wiki page in this repository

**Additional context**
[New Zealand mid term testing strategy ](https://www.health.govt.nz/system/files/documents/pages/mid-term_national_testing_strategy_covid-19_june_2020.pdf) contains this
 
- Component 1: Testing those with relevant symptoms --> Action: Identification of a positive PCR test precipitates confirmation of positive test status (including whole genome sequencing) and if appropriate, declaration of a case. 
- And on page 8: Whole  genome sequencing (WGS) of isolates ,,, may result in reassessment ... and reclassification of cases.

My understanding is that in new zealand a positive PCR test is reviewed by trying to find the whole virus. If this fails the positive test result is classified as a false positive. 
As you probably know the positive predictive value of a PCR test depends on its sensitivity, specificity and the prevalence. These parameters determine how many false positive occur. On top of that a PCR test can be positive up to  [82 days following recovery](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7417974/pdf/S0899823X20003438a.pdf)

**Comment by ravi-maithrey** [comment]
What i can see is the mohfw itself isnt releasing too many details. before we classify anything, we need further info on how these are being classified at the source
