### ISSUE TITLE
Cases in negative

### ISSUE THREAD

**Issue by Jaideep25** [covid19india/covid19india.github.io#2447]
Hi!
Your app is just amazing and cool!

Just their is a bug I have seen....
Click on daily,
And choose any state, or let it be the coutry, as you can see the active cases go to negative
![image](https://user-images.githubusercontent.com/67269475/116723563-4edf2900-a9fd-11eb-9800-e0900d74e364.png)
Hoping you can solve this problem or bug!
Thank you!
Regards!

**Comment by pratham1002** [comment]
That is the daily change in active cases you are seeing, it is not a bug but is supposed to be that way. To track the total number of active cases on a particular day, use the `Cumulative` graphs.

**Comment by Jaideep25** [comment]
But how can the cases go negative?? @pratham1002

**Comment by pratham1002** [comment]
More people recovered on a particular day than got infected. Hence the net change in active cases is negative.

**Comment by Jaideep25** [comment]
But in real... we can't get negative....

**Comment by krishnashenoy123** [comment]
@Jaideep25, it's not the confirmed cases, active case can't be negative whereas the active cases it can go negative or positive or zero. If more number of people are recovered than the number of confirmed cases that day, then the active case will become negative.
active case = confirmed case - recovered case - deaths.

**Comment by Jaideep25** [comment]
I know that formula, but active cases means that the number of people who still are suffering from corona that day, which isn't possible to be negative..

**Comment by krishnashenoy123** [comment]
You still didn't get it !!?
Its not the people suffering, its the net total for the day.

**Comment by ShikariShambuJr** [comment]
Refer to https://github.com/covid19india/covid19india-react/issues/2038#issuecomment-641962963
