### ISSUE TITLE
Test positivity ratio is incorrect on main page

### ISSUE THREAD

**Issue by JaapHaitsma** [covid19india/covid19india.github.io#2448]
<img width="1272" alt="Screen Shot 2021-04-30 at 14 27 36" src="https://user-images.githubusercontent.com/905295/116738372-59c79880-a9c0-11eb-8b14-05b14ee8623a.png">
See screenshot: For instance test positivity ratio in Karnataka is shown as 6% while there were almost 50.000 new cases and number of tests were 1.9L. So positivity rate should be around 25%

**Comment by bee-rickey** [comment]
Table shows the overall TPR

**Comment by JaapHaitsma** [comment]
@bee-rickey how do you calculate overall TPR?
