### ISSUE TITLE
Add Vaccinations per Million to States Page

### ISSUE THREAD

**Issue by pratham1002** [covid19india/covid19india.github.io#2449]
**Is your feature request related to a problem? Please describe.**
Just like the
![image](https://user-images.githubusercontent.com/54350608/116749527-b35eb000-aa1e-11eb-989c-1c3732b23fd3.png)
it might be useful to have vaccinations per million

**Describe the solution you'd like**
Simply another tab on the state page without any required change to API.

**Describe alternatives you've considered**
None

**Additional context**

**Comment by ShikariShambuJr** [comment]
You can click on 10L button to view Total Doses Administered(Vaccination) per million at the Home Page not only for Statewise but also for DistrictWise
![Screenshot from 2021-05-20 21-12-54](https://user-images.githubusercontent.com/68983486/119010272-806e6300-b9b1-11eb-8bdc-4e6572a6822e.png)
