### ISSUE TITLE
 Capturing of Covid Antigen Test results along with the date when the test is done 

### ISSUE THREAD

**Issue by Ncchoudhury** [covid19india/covid19india.github.io#2452]
**Feature Description **
 - > Ability of feature to capture the test results of the Covid antigen Test (carried out at home)in the tracking app
- > The Tracking App feature gives a reminder to the person/user to carry out the Covid antigen  test every two days. 
- > Ability of the Tracking app feature to register the history of test results of the user over a period of 14 days or even more.. 

**Short Description of how the App feature could function**

Given that the antigen tests that can be carried out at home are available for use with specific serial numbers on them, the new tracking app feature can capture the result on a particular day along with the date and time of taking the test, using a photograph of the test result along with the test serial number in it. Tracking app only registers photographs where the test serial number is present in it.  Hence the tracking app can detect if there are multiple entries of the same test in the app. 

Tracking app feature can also detect a positive test using the  photo uploaded in the app of the test taken. 
When tested positive for infection, every person in the vicinity of the infected person to be warned immediately by the tracking app and the person notified to move into quarantine.

**Comment by ShikariShambuJr** [comment]
The data you are referring is not available anywhere to capture from.
