### ISSUE TITLE
Please provide a open source data link which update daily

### ISSUE THREAD

**Issue by nitesh0007-edith** [covid19india/covid19india.github.io#2456]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by nitesh0007-edith** [comment]
provide us data link which can easily connect with Tableau / Power BI etc

**Comment by ShikariShambuJr** [comment]
All data is available at api.covid19india.org. The data is updated every 10 minutes.
