### ISSUE TITLE
Wrong calculation of total number of tests,

### ISSUE THREAD

**Issue by kaijain** [covid19india/covid19india.github.io#2457]
The total number of test reflected is wrong because when you add all the states test individually the number is much higer.
This error is leading to a high test posotivity ratio.
Please look into the error.

**Comment by ShikariShambuJr** [comment]
This maybe due to different cut-off timings for reporting for the every state  and for national data. Would request you to contact authorities via relevant channels like RTI etc to get a clarification on this.
