### ISSUE TITLE
Mumbai test cases numbers not visible since 30th Jan 2021

### ISSUE THREAD

**Issue by niteshnamdeoshinde** [covid19india/covid19india.github.io#2458]
**Describe the bug**
A clear and concise description of what the bug is. If your issue is regarding an error in the data, it's best reported through [this form](https://forms.gle/MLeSrdwRuf8AjFkp9).

**To Reproduce**

1. Go to Maharashtra section
2. Click on Mumbai/Thane district
3. Scroll down to Tested
4. no counts found since 27th Jan

**Expected behavior**
its should ideally should have shown us numbers being tested in Mumbai/Thane area, but its 0

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by thecodingaviator** [comment]
[Collection of testing data at district level has been stopped](https://api.covid19india.org/)

**Comment by niteshnamdeoshinde** [comment]
atleast add for main cities in Maharashtra as its the worst affected state :( 
and if data is not collected at district level/city level how its available to social media pages/news channels/newspapers?

**Comment by ShikariShambuJr** [comment]
It is a very hectic and difficult task to collect this data as we are a volunteer based group with limited resources so have discontinued it.
