### ISSUE TITLE
Cases in table are negative

### ISSUE THREAD

**Issue by jayavardhan3112** [covid19india/covid19india.github.io#2462]
**Describe the bug**

**To Reproduce**

1. Go to Home page
2.  Click the option toggle button on the top left of the table
3. Check the Table entries 

**Expected behavior**
Screenshots shouldnt be in negative

**Screenshots**
<img width="1440" alt="Screenshot 2021-05-09 at 6 06 09 PM" src="https://user-images.githubusercontent.com/22497670/117581386-15ec3600-b11a-11eb-8ca9-e028bacc124a.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
if the entry is negative we can round it off to 0 for all the negative entries

**Comment by ShikariShambuJr** [comment]
This was due mismatches in totals.Has been corrected by reconciliation of the entries.
