### ISSUE TITLE
Remove Case fatality and Add Death per million/thousand

### ISSUE THREAD

**Issue by adarshsunil** [covid19india/covid19india.github.io#2464]
**Is your feature request related to a problem? Please describe.**
Case fatality is totally misleading as it stays low if cases rises too much. We have seen this metric gone wrong with Delhi, Maharashtra and Kerala where death when rising still show low case fatality due to large number of cases
**Describe the solution you'd like**
Remove case fatality and Add deaths per million/thousand which will make people more aware and serious about the loss of life

**Describe alternatives you've considered**
Daily rise in death can also be plotted to make more serious efforts for flattening the curve

**Comment by ShikariShambuJr** [comment]
You can click on 10L button to switch to Deceased per Million
![Screenshot from 2021-05-20 21-12-54](https://user-images.githubusercontent.com/68983486/119008979-4a7caf00-b9b0-11eb-8c4f-46c057eeae13.png)
