### ISSUE TITLE
test numbers are not right

### ISSUE THREAD

**Issue by absuag** [covid19india/covid19india.github.io#2466]
The number of tests for Lucknow, Mumbai and other cities are the same since December 2020.

![image](https://user-images.githubusercontent.com/34994647/118092398-b1ff9100-b3e9-11eb-9add-c87e34f93686.png)

**Comment by absuag** [comment]
it seems data is not getting updated:
![image](https://user-images.githubusercontent.com/34994647/118097969-f7738c80-b3f0-11eb-84ee-c6f1a6f0dab4.png)

**Comment by ShikariShambuJr** [comment]
We have discontinued District Wise Testing from Feb'21
