### ISSUE TITLE
Enhancement: Move time-series controls to the top with other Spread Trends controls

### ISSUE THREAD

**Issue by Siddharth-Gandhi** [covid19india/covid19india.github.io#2467]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when I have to scroll all the way to the bottom to have to see graphs by time period. I think it really looks out of place at the bottom. When I first used the site, I was bummed that I couldn't find any controls for seeing trends over a specific time period (say last 30 days), even though they were there at the end.

**Describe the solution you'd like**

I suggest moving the time series button to the top along with the rest of the 'Spread Trends' controls (like scale modes, 7-day moving average switch, state-wise filter, etc). 

**Describe alternatives you've considered**
NA

**Additional context**

Suggestion:

![final](https://user-images.githubusercontent.com/61461606/118356869-e06d9f80-b594-11eb-808f-9dab9fad2853.jpg)

Something like what Google has:

![OMnFTcTz6k](https://user-images.githubusercontent.com/61461606/118356601-a6e86480-b593-11eb-8a2c-be5b6b9c1139.gif)

**Comment by shuklaayush** [comment]
I think it's too late to change this now. It'll probably annoy more people than it pleases
