### ISSUE TITLE
Menu Layout

### ISSUE THREAD

**Issue by vitamin2025** [covid19india/covid19india.github.io#2468]
The Dark mode Button and "A crowdsourced initiative." statement is on the same line, which may create confusion.
![2021-05-15 (2)](https://user-images.githubusercontent.com/72799488/118371142-cf3e8600-b5c8-11eb-9388-5bc9b54427de.png)

**Comment by arshzip** [comment]
It would make more sense for that to be pushed to the empty space at the bottom like so

![image](https://user-images.githubusercontent.com/23417273/118386809-a86b6880-b637-11eb-89a9-1486e4628eaa.png)

I have a fix ready, will issue a PR once someone okays it

**Comment by vitamin2025** [comment]
Yea, i can help too :)

**Comment by shuklaayush** [comment]
Duplicates #2423
