### ISSUE TITLE
website content size

### ISSUE THREAD

**Issue by froster02** [covid19india/covid19india.github.io#2471]
**Describe the bug**
A clear and concise description of what the bug is. If your issue is regarding an error in the data, it's best reported through [this form](https://forms.gle/MLeSrdwRuf8AjFkp9).

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

On visiting the website the content of the website is being shown in compressed form which seen to be glitchy rendering initially and user can only see the full content completer after only hitting the expand button, this process show be reversed as when the user visits the website show them the expanded form and then only give them the option to shrink the content on to the centre.
<img width="1320" alt="Screenshot 2021-05-17 at 07 57 58" src="https://user-images.githubusercontent.com/41764421/118425227-5f262200-b6e6-11eb-84d7-54e9af0eedcc.png">
<img width="1320" alt="Screenshot 2021-05-17 at 07 58 14" src="https://user-images.githubusercontent.com/41764421/118425234-62b9a900-b6e6-11eb-80df-dea92d8d574c.png">

**Comment by shuklaayush** [comment]
What's your screen resolution?

**Comment by froster02** [comment]
> What's your screen resolution?

the issue has been resolved by developers !
