### ISSUE TITLE
Negative daily active cases

### ISSUE THREAD

**Issue by stephen-talari** [covid19india/covid19india.github.io#2472]
**Describe the bug**
Negative daily active counts are shown in the spread trends, 
we can not have any number less than 0.
Ex: 
```
The Active cases on 16th May is '-100883', previous day difference is '-44895'
```
We can not have `-100883` as daily count.

**To Reproduce**

1. Go to https://www.covid19india.org
2. Click on 'Daily' tab in 'spread trends' and select 'India' from drop down
3. Scroll down to 'Active Chart(blue)'
4. See negative daily counts from May 10th to 16th 

**Expected behavior**
Daily counts should always be a whole number [>=0]

**Screenshots**

<img width="806" alt="Screenshot 2021-05-17 at 10 40 44 AM" src="https://user-images.githubusercontent.com/1725945/118436451-753fdc80-b6fe-11eb-91ae-13363bdf73af.png">

**Desktop (please complete the following information):**

- OS: OSX 11.2
- Browser [safari]
- Version [14]

**Comment by ShikariShambuJr** [comment]
Refer to https://github.com/covid19india/covid19india-react/issues/2038#issuecomment-641962963

**Comment by stephen-talari** [comment]
Referred to that comment, from that comments, only delta will be negative but not daily reported active cases. 

This issue is not related to that!
