### ISSUE TITLE
Number in percentage

### ISSUE THREAD

**Issue by dheerajagrawal19** [covid19india/covid19india.github.io#2473]
India is huge and numbers could look big and small from the point where we stand, for example 1 million people for India could be small but for many European countries it's big.
Whether we talk about the testing/tested/vaccinated, everyone is discussing as a cumulative number, instead of let's talk in percentage as well.

**Describe the solution you'd like**
For Vaccination, let's show much a city/state/town has been vaccinated, fetching number for vaccine given in a state/city could be troublesome but the population can be easily referred using govt sites.

**Describe alternatives you've considered**
We can begin small..
1) Show percentage for overall country
2) Then start to show for States/Big cities.
3) All cities in each state.

We can do it for tests, cases and vaccination, not necessarily in one go but gradually it will be good.

**Comment by ShikariShambuJr** [comment]
We are working on this and will soon add it in the same way described by you. Due to some personal issues it has been postponed for a while for implementation.
