### ISSUE TITLE
Do not render Unknown for district view in the table

### ISSUE THREAD

**Issue by DantrazTrev** [covid19india/covid19india.github.io#2476]
**Describe the bug**
When switched to the district view the data viewed also contains an Unknown [ State Name ] which more or less has the entire state data 
![Screenshot_20210519-013721_Chrome.jpg](https://user-images.githubusercontent.com/43457420/118716844-eab4c580-b842-11eb-8d4a-b86eec54b91a.jpg)

**To Reproduce**

1. Go to the table view 
2. Switch to district 
3. See the Unknown [State Name] 
4. It is the same data as the State

**Expected behavior**
The district should only contain districts rather than the states masking as districts .

**Smartphone (please complete the following information):**

- Device: Galaxy M21
- OS: Android 10
- Browser Chrome

**Comment by ShikariShambuJr** [comment]
It is there because states like Telangana,Assam,Manipur,Goa,Sikkim,Delhi,Andaman and Nicobar do not provide district wise data. If they start displaying data this will go away
