### ISSUE TITLE
Black Fungus Infection

### ISSUE THREAD

**Issue by kuharan** [covid19india/covid19india.github.io#2477]
Add a section to display the New Black Fungus Infection numbers.

Reasons:
1. It is related to covid-19
2. The numbers are significantly increasing and are a matter of concern.

**Comment by ShikariShambuJr** [comment]
The project is related to Covid. We would like to stick to that. 
Moreover no public database for this disease exists.

**Comment by Anubhav-developr** [comment]
@kuharan which api is providing the data how will you get the numbers .....?
