### ISSUE TITLE
Adding styling to the scrollbars, according to theme of the web app

### ISSUE THREAD

**Issue by Nirmitjatana** [covid19india/covid19india.github.io#2482]
**Is your feature request related to a problem? Please describe.**
White scrollbars look odd with respect to the current theme of the website.

**Describe the solution you'd like**
We can add styling to the scroll bar for both dark mode and light mode. 

**Describe alternatives you've considered**
The solution is pretty straightforward, and shouldn't require alternatives

**Additional context**
Styling can be added to both side and overflow scroll bar
![image](https://user-images.githubusercontent.com/52108077/119298373-8a76b700-bc7a-11eb-8c91-a4baff37f46c.png)

**Comment by shuklaayush** [comment]
Duplicates #2158
