### ISSUE TITLE
Possible to pull total number of population within the given district  ?

### ISSUE THREAD

**Issue by prablr79** [covid19india/covid19india.github.io#2484]
**Is your feature request related to a problem? Please describe.**
Possible to pull total number of population within the given district  ? Need clarity since vaccination is not sufficient in terms of doses / district.

**Describe the solution you'd like**
total number men and women count from age of 18+ from aadhar db

**Describe alternatives you've considered**
provided this data should not have any implication from Ministry of Health and support. if they have correct data that would be good to track.

**Additional context**

**Comment by shuklaayush** [comment]
Population data is already there if you expand the table

![image](https://user-images.githubusercontent.com/27727946/120882467-c7856680-c5f5-11eb-8e61-dfdd9c79e72b.png)

**Comment by prablr79** [comment]
Thanks
