### ISSUE TITLE
Size of front page numbers are not right

### ISSUE THREAD

**Issue by sayanmdn** [covid19india/covid19india.github.io#2487]
I have tested it in Android, 6.2 inch, Chrome, it's looks annoying. please take a look at the confirm and active numbers.
![Screenshot_2021-05-28-11-57-55-67](https://user-images.githubusercontent.com/21085290/119940426-c8424b00-bfac-11eb-8fb1-6aecc1798f14.jpg)

**Comment by ujjwalpuri29** [comment]
This seems to be an issue on your end...Maybe some setting tweaking or accessibility option. Is there a way to replicate this on our phones?

**Comment by shuklaayush** [comment]
Looks like you're using an older version of Chrome that doesn't support CSS min/max functions. Should be fine once you update
