### ISSUE TITLE
District and State graph UI not consistent

### ISSUE THREAD

**Issue by ujjwalpuri29** [covid19india/covid19india.github.io#2489]
The 90 days graph UI on the homepage (India and states) has a smooth curve which was updated a few months back. But on the districts page, the graph is still old bar graph style and not continuous.

**Solution**
Change the districts graph UI for 90 days to be consistent with the state graph

**Screenshots**
Homepage graph for 90 days
![image](https://user-images.githubusercontent.com/77334754/120796354-5b085a00-c558-11eb-9292-ad70b31a0207.png)

District graph for 90 days
![District graph](https://user-images.githubusercontent.com/77334754/120796139-154b9180-c558-11eb-8994-16c29c7b6fa8.png)

**Additional comments**
While using the slider, I realized that the homepage graph turns smooth at 90 days, and the district graph turns smooth at 91 days
![image](https://user-images.githubusercontent.com/77334754/120796839-ee418f80-c558-11eb-8e9b-9c46df9974e7.png)

**Comment by shuklaayush** [comment]
This might've been because of different page margins. Should be fixed in the latest build
