### ISSUE TITLE
Implement Calendar Picker to look at a specific day's status

### ISSUE THREAD

**Issue by vidhyasagarreddy** [covid19india/covid19india.github.io#2495]
With current To and Fro controls, we can just jump on to one day at-a-time. I would suggest you to include a "Calendar Picker" to easily navigate to a specific day and see status

**Comment by shuklaayush** [comment]
It's already there

![Peek 2021-06-09 19-34](https://user-images.githubusercontent.com/27727946/121369821-d2275f00-c959-11eb-9422-930c79d7e1ea.gif)

**Comment by vidhyasagarreddy** [comment]
May be the accessibility is way too bad. How would a user expect the current date label is clickable ? May be place a Calendar icon on the right or left of those control set.

**Comment by shuklaayush** [comment]
Yeah, you're right. I guess I thought the change of colour while hovering would be enough of a hint, but it's probably not. I'll look into this

**Comment by vidhyasagarreddy** [comment]
Thanks for adding new calendar icon :) Kudos.
