### ISSUE TITLE
Every click on page sends request to fetch data

### ISSUE THREAD

**Issue by krishhteja** [covid19india/covid19india.github.io#2497]
**Describe the bug**
A clear and concise description of what the bug is. If your issue is regarding an error in the data, it's best reported through [this form](https://forms.gle/MLeSrdwRuf8AjFkp9).

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

Not sure if it is expected but any click on page sends 3 requests (data.min.json, timeseries.min.json, log..json). This could be modified to fetch data every 1 hour or so

**Comment by shuklaayush** [comment]
I think it only fetches data when the tab regains focus. Otherwise, it should fetch only once every ~10mins (which is reasonable). Are you observing something different?

**Comment by krishhteja** [comment]
Yes. Any click on any part of the page fetches data

**Comment by shuklaayush** [comment]
Can you share a video/gif?

**Comment by krishhteja** [comment]
https://user-images.githubusercontent.com/8438143/121646863-6c90bb00-ca9e-11eb-9108-db7b6b515d42.mov

This issue is not reproducible in mac with chrome but very clearly observed in windows with chrome (version 91.0.4472.77)

**Comment by shuklaayush** [comment]
Weird, I'm guessing it's a browser issue. Anyways, it shouldn't really matter since the files are served from cache so there's no network usage

**Comment by krishhteja** [comment]
That's great. I was thinking about network load on server side as people tend to click tens of times.

Quick question : What is the point on sending requests when it uses cached data?

**Comment by shuklaayush** [comment]
Ideally, it should only send requests every 10 minutes or so to check for updated data. We don't want people to manually have to refresh the website to see if there's a data update. The service worker handles the caching part of the requests
