### ISSUE TITLE
first load and scroll of page to map renders empty view

### ISSUE THREAD

**Issue by krishhteja** [covid19india/covid19india.github.io#2498]
**Describe the bug**
A clear and concise description of what the bug is. If your issue is regarding an error in the data, it's best reported through [this form](https://forms.gle/MLeSrdwRuf8AjFkp9).

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

When page is loaded for the first time and scrolled to map area, it stops rendering and shows a blank screen. Refreshing the page fixes it. Observed it on both windows and macOS

![image](https://user-images.githubusercontent.com/8438143/121714497-8bb33b00-cae6-11eb-93dc-e87a610eec58.png)

**Comment by ujjwalpuri29** [comment]
Sometimes it does happen on my device too (both phone and laptop) but not always

**Comment by shuklaayush** [comment]
Probably CDN/caching issues. Seems to be fixed for now
