### ISSUE TITLE
Hindi search bar Isn't working properly

### ISSUE THREAD

**Issue by YatinMishra** [covid19india/covid19india.github.io#2499]
**Describe the bug**
When changed the application from english to hindi the search for district and states isn't working properly.

**To Reproduce**

1. Go to languages
2. Click on Hindi
3. Scroll to Search for districts or states

**Expected behavior**
Name of districts or states should be clearly seen in hindi.

**Desktop (please complete the following information):**

- OS: Windows, Mac
- Browser chrome, safari

**Additional context**
Check other languages also.
mishrayatin2501@gmail.com

**Comment by hrishikeshp7** [comment]
Its true for instance this screenshots depict the errors 
https://jumpshare.com/v/rmFy4mkfX2e28iQcU8Uf
Plus The dropdown bar present in Hindi Shows only "Active" and the "Deceased" Cases in English

**Comment by shuklaayush** [comment]
Duplicates #2322
