### ISSUE TITLE
Find a better placement for database & telegram links

### ISSUE THREAD

**Issue by suryaceg** [covid19india/covid19india.github.io#25]
Database & telegram link take up precious first fold space. They can be simple icons in the top nav bar. Don't see a need for them to occupy so much space there.

![image](https://user-images.githubusercontent.com/840117/77308905-b5d1df00-6d21-11ea-853c-3af76c9e1967.png)

**Comment by JunaidBabu** [comment]
I think this was already done @jeremyphilemon ?

**Comment by JunaidBabu** [comment]
Done
