### ISSUE TITLE
Sort by New Confirmed, Recovered, Deceased, Tested 

### ISSUE THREAD

**Issue by vidhyasagarreddy** [covid19india/covid19india.github.io#2501]
Currently, the sort feature sorts data based on the entire data, but not on new entries. Can we have similar sort icon on the right side, along side current sort icon on the left (PFB) ?

![image](https://user-images.githubusercontent.com/3716334/122155266-3bd8c900-ce84-11eb-9c49-de042d04123d.png)

**Comment by shuklaayush** [comment]
If you long-press the column header, then it sorts by new entries/cases

![Peek 2021-08-05 14-41](https://user-images.githubusercontent.com/27727946/128324578-0c96df54-45fc-432b-b370-3858d34038fa.gif)

**Comment by vidhyasagarreddy** [comment]
I think this is usability issue. How would once expect long press on header would toggle to different filter!
