### ISSUE TITLE
Logo At Footer Redirects to Github Instead of Website

### ISSUE THREAD

**Issue by hrishikeshp7** [covid19india/covid19india.github.io#2503]
The Logo or precisely at footer the Covid19India Title Redirects user to this Github Repo , Instead It should Redirect to the Main Website 

Its Better to set the Redirect to Homepage as we already have the Github Link in the Icon

**Comment by ujjwalpuri29** [comment]
There is already a home button to redirect you to the main website in the nav bar. I feel this is not required.
The foorter covid19india is for the organization and they link it to their github profile
