### ISSUE TITLE
No Option to Select Back India as a whole Country after seeing a state or District

### ISSUE THREAD

**Issue by hrishikeshp7** [covid19india/covid19india.github.io#2504]
Its Currently not being Possible to Reselect India back after looking up an District or a state .  The measure to make a dropdown Option to India would be a good Choice to see the Stats for Total Country.

**Comment by DHECK17** [comment]
Oh I thought It Only Happens With me

**Comment by iLagTooMuch** [comment]
Click on India at the bottom of state lists to revert back to india :) hope this helps 👍

**Comment by hrishikeshp7** [comment]
@iLagTooMuch  No Its different , Its not happening I mean there is no Dropdown Bar for states there what i am trying to say is Different
When you select Toggle Between States and Per Lakh People , You will Find whats my Issue

**Comment by ujjwalpuri29** [comment]
Click anywhere outside the map to revert to india stats

**Comment by hrishikeshp7** [comment]
A button would be really great , it is very difficult while selecting Back

**Comment by shuklaayush** [comment]
If you're referring to the map, then clicking/tapping on any empty space resets back to India stats

**Comment by DHECK17** [comment]
No bro it doesn't let me show oy what I am talking

**Comment by hrishikeshp7** [comment]
Hey @shuklaayush  it doesnt I have attached a video see it here :

https://user-images.githubusercontent.com/68657160/128327878-b51b0d1e-37d5-4880-8e60-fa0981dbc858.mp4

**Comment by shuklaayush** [comment]
Hmm, weird. Works for me. Which browser/OS are you using?

![Peek 2021-08-05 15-05](https://user-images.githubusercontent.com/27727946/128328343-888f3127-5ed8-417e-b17f-0ea78424a491.gif)
