### ISSUE TITLE
Add Expires headers

### ISSUE THREAD

**Issue by hrishikeshp7** [covid19india/covid19india.github.io#2505]
Web pages are becoming increasingly complex with more scripts, style sheets, images, and Flash on them. A first-time visit to a page may require several HTTP requests to load all the components. By using Expires headers these components become cacheable, which avoids unnecessary HTTP requests on subsequent page views. Expires headers are most often associated with images, but they can and should be used on all page components including scripts, style sheets, and Flash.

TBH this problem was shown on my website defence and checking system.

**Comment by shuklaayush** [comment]
I think the resources are already cached since we're using service workers
