### ISSUE TITLE
Blog page title is wrong

### ISSUE THREAD

**Issue by Aayush-Bhatt** [covid19india/covid19india.github.io#2506]
The bug is located on the Blog page of the website. The title should contain the name of the site, but it's something else.

Steps to reproduce the behaviour:

1. Go to 'Navigation bar on left
2. Click on 'Blog'
3. See an error on the top named "Stretchhhh"

**Screenshots**
![Screenshot from 2021-06-18 19-24-16](https://user-images.githubusercontent.com/65692432/122571994-f32f3480-d06a-11eb-8e96-f7e06eda35b9.png)

**Desktop (please complete the following information):**

- OS: [Windows,MacOs,Linux]
- Browser [chrome, safari]
- Version [22]

**Smartphone (please complete the following information):**

- Device: [iPhone6 nad above, Android 8 and above]
- OS: [ iOS8.1]
- Browser [stock browser, safari]
- Version [22]

**Additional context**
Kindly comment on the PR request to correct the bug.

**Comment by hrishikeshp7** [comment]
Yes the Problem Occurs need to make available , can fix it easily

**Comment by hrishikeshp7** [comment]
If its Available i can fix it , I have already got the error 
To Specify the mistake is there in the Strong tag on the page

**Comment by hrishikeshp7** [comment]
@shuklaayush Please Give this to me , I have a lot of Desire to help and Conrtibute

**Comment by hrishikeshp7** [comment]
I have fixed the error btw just a commit is required , changed at https://github.com/hrishikeshp7/Covid-19-India-Fixing-heading-Error

**Comment by VikashAnandJha** [comment]
yes the title says strechhhh
![image](https://user-images.githubusercontent.com/6469187/123769919-6a748c00-d8e7-11eb-9152-99bedfa92eaf.png)

**Comment by howdyAnkit** [comment]
Can I get assigned for this @shuklaayush

**Comment by hrishikeshp7** [comment]
This issue is already resolved , Please check in Covid 19 India Blog Repo. The title Stretch is done Intentionally not mistakenly 
@howdyAnkit

**Comment by shuklaayush** [comment]
Refer to https://github.com/covid19india/blog/issues/5
