### ISSUE TITLE
The delta for Total Active cases is not displayed

### ISSUE THREAD

**Issue by probal31** [covid19india/covid19india.github.io#2509]
Hi Team,

The delta for Total Active cases is not displayed.
Whereas I see the delta for others heads like Confirmed, Recovered, Deceased is properly displayed.

Is there any reason why particularly delta for Active is hidden?

I can fix this. Just wanted to understand why is the reason behind.

Thanks.

**Comment by shuklaayush** [comment]
Refer to https://github.com/covid19india/covid19india-react/issues/2105#issuecomment-641833409
