### ISSUE TITLE
Add Spanish translation to the website

### ISSUE THREAD

**Issue by Panquesito7** [covid19india/covid19india.github.io#2511]
**Is your feature request related to a problem? Please describe.**

I saw the website and checked the available languages. It'd be cool if there was a Spanish translation (I can work on it if you want, it's my native language).
_Offtopic: One question by the way: does this project use Weblate for translations?_

**Describe the solution you'd like**

Add Spanish translation to the website.

**Describe alternatives you've considered**

None yet. If you have any, please write them below.

**Comment by shuklaayush** [comment]
We use [I18next](https://www.i18next.com/) for translations. 
Honestly, I don't think adding Spanish translation would add much value since we're only tracking cases in India. Also, > 99% of our users are from India
