### ISSUE TITLE
Data regarding Population and percentage vaccinated is wrong 

### ISSUE THREAD

**Issue by adityacholle04** [covid19india/covid19india.github.io#2513]
Hi team,

Currently we only have 18+ population eligible for vaccination in India and website says India's population is 133.3Cr which is correct if we consider entire age range but if 0 to 18 group is not eligible  for vaccination why are we considering them for percentage vaccinated ?

**Comment by shuklaayush** [comment]
The data isn't "wrong". 

In my opinion, it's only a matter of time before 12-18 years will be allowed to get vaccinated (as in the US, Israel etc.) so it doesn't make sense to have a temporary metric showing only the percentage of 18+ population vaccinated. It will just add to the confusion later. 

Also, I'm not sure if only 18+ population data is readily available for all states/districts

**Comment by FrozenHearth** [comment]
> The data isn't "wrong".
> 
> In my opinion, it's only a matter of time before 12-18 years will be allowed to get vaccinated (as in the US, Israel etc.) so it doesn't make sense to have a temporary metric showing only the percentage of 18+ population vaccinated. It will just add to the confusion later.
> 
> Also, I'm not sure if only 18+ population data is readily available for all states/districts

Hey, isn't India's population around 140 crores? And almost 40 crore people are vaccinated as of today, which would make the "Atleast one dose" percentage be 28.5%, but it shows 24%. How is this calculated?

**Comment by adityacholle04** [comment]
Till now only 31.9 crore First dose has been administered so its correct 24%.
40-41 crore is total vaccination 32(first dose) + 9(second dose) = 41 crore .

**Comment by adityacholle04** [comment]
> > The data isn't "wrong".
> > In my opinion, it's only a matter of time before 12-18 years will be allowed to get vaccinated (as in the US, Israel etc.) so it doesn't make sense to have a temporary metric showing only the percentage of 18+ population vaccinated. It will just add to the confusion later.
> > Also, I'm not sure if only 18+ population data is readily available for all states/districts
> 
> Hey, isn't India's population around 140 crores? And almost 40 crore people are vaccinated as of today, which would make the "Atleast one dose" percentage be 28.5%, but it shows 24%. How is this calculated?

Till now only 31.9 crore First dose has been administered so its correct 24%.
40-41 crore is total vaccination 32(first dose) + 9(second dose) = 41 crore .
