### ISSUE TITLE
Should I make a Mobile app for covid19india-react

### ISSUE THREAD

**Issue by virejdasani** [covid19india/covid19india.github.io#2515]
I have made mobile apps with react-native from react based websites.
I think an Android and IOS app would be very cool to have and I'd be more than happy to make the app (using react native) myself and open a pull request.
Let me know if you would be willing to merge such a pull request so I can get on making the app or let me know if you want to make a new repo for the app or I can do it too 👍

**Comment by gandhisamay** [comment]
@virejdasani, I would really like to collaborate too with you, for making an app, if needed. By the way what are planning to use to make the app, Flutter ?

**Comment by virejdasani** [comment]
> @virejdasani, I would really like to collaborate too with you, for making an app, if needed. By the way what are planning to use to make the app, Flutter ?

No, with react native because it would be easier to transfer the code from ReactJS to React Native. Let me know what your Discord is if you wanna collaborate 👍

**Comment by sandeepdhobi** [comment]
I'm in

**Comment by gandhisamay** [comment]
I 

> > @virejdasani, I would really like to collaborate too with you, for making an app, if needed. By the way what are planning to use to make the app, Flutter ?
> 
> No, with react native because it would be easier to transfer the code from ReactJS to React Native. Let me know what your Discord is if you wanna collaborate 👍

I m in too ..my discord id is samay_200

**Comment by virejdasani** [comment]
> I m in too ..my discord id is samay_200

I hope the maintainers of this repo allow us to make the app. Then we can proceed

**Comment by themissingbracket** [comment]
@virejdasani 
I am keen as well

**Comment by virejdasani** [comment]
As soon as the status gets approved, I'll make a Discord server for the 4 of us, @gandhisamay, @sandeepdhobi, @themissingbracket, and myself can collaborate on making the app 👍

**Comment by vasut02** [comment]
This application is already already a progressive web app, we can install in our mobile from browser. IMO I don't think this will get approval 🤔 . If they did gave us approved add me as well 👍

**Comment by shuklaayush** [comment]
As @vasut02 mentioned, it's already a PWA so I don't see how creating a native app would add more value. But go ahead if you're interested in working on it. All our code and data is open-source with a permissive license. You can do whatever you want with it and don't need our approvals
