### ISSUE TITLE
Vaccine second dose due date

### ISSUE THREAD

**Issue by surijatin** [covid19india/covid19india.github.io#2519]
Suggestion -
We can provide a provision for the user to check when their next covid vaccine dose is due, for different vaccines which are being administered in the country.

Solution -
Provide a date-picker and checkboxes for selecting the type of vaccine, which in turn could return the due date for the second jab after computation.
I have a working model of the same prepared [here](https://surijatin.github.io/covid-second-dose/)

![image](https://user-images.githubusercontent.com/75334549/128851998-b350d5b7-2175-4bf5-938e-59498abd351a.png)

**Comment by surijatin** [comment]
@ShikariShambuJr Would you mind mind providing some comment ?

**Comment by surijatin** [comment]
@shuklaayush  Can you please help on why this idea was discarded? Just trying to look out for some reasoning, nothing else.

**Comment by shuklaayush** [comment]
Hey @surijatin, it's a good idea but it doesn't fit the purpose of our website. We're only tracking the spread and impact of Covid-19 in India through our database and API.
