### ISSUE TITLE
Use redux or react context for state management.

### ISSUE THREAD

**Issue by rohitpotato** [covid19india/covid19india.github.io#252]
After seeing the source code, it is quite obvious that a lot of prop drilling is going on and functions are being passed from component to component. This will become a lot trickier when the project grows. 

I sugggest a battle tested state management solution for the project. Redux or Context maybe?

**Comment by JunaidBabu** [comment]
@jeremyphilemon @shuklaayush @s-naveen thoughts?

**Comment by shuklaayush** [comment]
I don't have any experience with either but would love to learn.

**Comment by rohitpotato** [comment]
Can i make a pull request with a redux setup for the project?

**Comment by s-naveen** [comment]
I am not that much familiar with redux either. Maybe we can try it if it does not make codebase complex.

**Comment by rohitpotato** [comment]
> I am not that much familiar with redux either. Maybe we can try it if it does not make codebase complex.

The codebase will get trickier if the project expands and there's no state management container in place.

**Comment by findelallc** [comment]
Guys I don't think it will require a redux wrapped for this project as of use case, a plan to use react context in one of the main part would be sounds good to prevent memory leaking..Don't make the codebase complex for the sake of simplicity and usability.

**Comment by rohitpotato** [comment]
Hi everyone, since I am new to open source contribution on github, I didn't exactly see the guidelines and made a pull request. Really sorry for that. Would anyone mind reviewing that?

**Comment by naveen-nrj** [comment]
I think redux using hooks will not be that much complex since we are using functional components
So redux with hooks is a good choice. Also, Don't know much about context.

**Comment by vramana** [comment]
Hi, I just came across this repo. I have experience with Redux and Context. I'll take a look around source and try to make suggestion.  But simply sticking to prop drilling is just fine in some cases even if it's 5 to 6 levels deep.

**Comment by rohitpotato** [comment]
@naveen-nrj @KrishnaPravin  check out a pull request I made: [HERE](https://github.com/covid19india/covid19india-react/pull/284)

**Comment by rohitpotato** [comment]
> Hi, I just came across this repo. I have experience with Redux and Context. I'll take a look around source and try to make suggestion. But simply sticking to prop drilling is just fine in some cases even if it's 5 to 6 levels deep.

Prop drilling is just bad practice and it becomes harder to debug when the project grows. I am assuming this project will eventually grow. It makes a lot of sense to stick with battle tested solutions.

**Comment by vramana** [comment]
I looked around the source code. There is no problem with source I didn't spot any instance of prop-drilling. Data fetched via API is just passed 1 or 2 levels deep. I think this is a non issue at this point.

**Comment by crup** [comment]
> I looked around the source code. There is no problem with source I didn't spot any instance of prop-drilling. Data fetched via API is just passed 1 or 2 levels deep. I think this is a non issue at this point.

+1 on that. 
I'm huge redux fan but imo this project is too tiny to have a state container like redux. Prop drilling and React Context will work just fine for this.

**Comment by jeremyphilemon** [comment]
So I went through the discussion here, and frankly I'd love a redux store too. However, this project seems too small for a store like redux. It sucks to close this because I'm sure we'd might opt redux if the project gets too big to handle prop drills, but by that time the PRs would become outdated with the issue.

Hence, when we feel a move to redux is apt, we'll have it issued! Thank you so much for having it set up anyway :)
