### ISSUE TITLE
Some issue with total number population with Action and / confirmed case numbers

### ISSUE THREAD

**Issue by prablr79** [covid19india/covid19india.github.io#2520]
**Describe the bug**
Some issue with total number population with Action and / confirmed case numbers

**To Reproduce**

for eg: Click on Karnataka
expand the table 
calculated confirmed case +Active  + vaccine does administered.
number varies it cross more that 1 Cr but total population is 95.9 L
as on today 8/11 : 

**Expected behavior**
Vaccine does Adminstered with population + confirmed case /Active case should tally 

I can add few more details if required.

**Comment by surijatin** [comment]
I believe the summation that you are trying to achieve doesn't include the mutually exclusive sets.
Wouldn't Confirmed Cases include the Active Cases?
Also what if a person was under the Confirmed Cases, then recovered and got the vaccine dose?
