### ISSUE TITLE
Issues with district names

### ISSUE THREAD

**Issue by meghprkh** [covid19india/covid19india.github.io#253]
**Describe the bug**
District names of some districts are different in the maps and the data that we have. E.g Bangalore, Bengaluru; Mysore, Mysuru

**To Reproduce**
1. Go to site
2. Click on Karnataka in the map
3. See that neither of Bangalore or Mysore are coloured and have 0 cases

**Expected behavior**
They have more than zero cases and hence must be coloured

**Screenshots**
Map of Karnataka
![image](https://user-images.githubusercontent.com/5979605/77811722-31ba8700-7094-11ea-805c-98c3548d8466.png)

**Additional context**
I don't know what is the preferred approach for fixing this issue, fixing the map files or creating an alias map. The alias map might be useful in case we don't have data for the exact district but for a group. (I am not sure about this, but is the data for Bangalore and Bangalore Rural combined or separately available?)

Nevertheless, I will try to create a PR for districts that have been renamed or reorganized if I can find them or find updated maps

**Comment by meghprkh** [comment]
As of the current data from the API, the following districts are missing in the maps:

```json
{
    "Delhi": [
        "East Delhi",
        "South West Delhi",
        "West Delhi",
        "Delhi",
        "South Delhi",
        "North East Delhi",
        "North Delhi",
        "North West Delhi"
    ],
    "Telangana": [
        "Bhadradri Kothagudem",
        "Ranga Reddy",
        "Medchal Malkajgiri"
    ],
    "Rajasthan": [
        "Jhunjhunu",
        "Pratapgarh "
    ],
    "Haryana": [
        "Gurugram",
        "Sonepat"
    ],
    "Uttar Pradesh": [
        "Gautam Buddha Nagar",
        "Kanpur"
    ],
    "Tamil Nadu": [
        "Tiruneveli"
    ],
    "Karnataka": [
        "Bengaluru",
        "Kalaburagi",
        "Mysuru"
    ],
    "Andhra Pradesh": [
        "S.P.S. Nellore",
        "Chitoor"
    ],
    "Uttarakhand": [
        "Pauri"
    ],
    "Andaman and Nicobar Islands": [
        "N&M Andaman"
    ]
}
```

(Tiny ugly script: might come handy later)
```js
const sdwise = require("./state_district_wise")

var missing = {}
Object.keys(sdwise).map(state => {
    const mmeta = mapMeta[state]
    // Since these are missing
    if (['Ladakh', 'Jammu and Kashmir', 'Puducherry', 'Chandigarh'].indexOf(state) != -1) return
    var obj = JSON.parse(fs.readFileSync(mmeta.geoDataFile, 'utf8'));
    const mapDistricts = getDistrictNames(obj)
    const toprint = Object.keys(sdwise[state].districtData).map(district => mapDistricts.indexOf(district) === -1 && district != 'Unknown' && district).filter(Boolean)
    if (toprint.length) missing[state] = toprint
})

console.log(JSON.stringify(missing))
```

**Comment by meghprkh** [comment]
https://github.com/covid19india/covid19india-react/pull/256

**Comment by jeremyphilemon** [comment]
Really appreciate the well thought out issue! 
> The alias map might be useful in case we don't have data for the exact district but for a group.

Could you please elaborate more on this? Like if it's a group, how would we show that on the map? 🤔

**Comment by JunaidBabu** [comment]
Resolved
