### ISSUE TITLE
Districts of Jammu and Kashmir, and Ladakh are missing

### ISSUE THREAD

**Issue by jeremyphilemon** [covid19india/covid19india.github.io#254]
Self explanatory :)

**Comment by jeremyphilemon** [comment]
Assigned to @guneetnarula

**Comment by guneetnarula** [comment]
Question for whoever is working on the district visualizations: I am right now working on / cleaning up the attributes, are these required: "cartodb_id", "censuscode", "st_cen_cd" and "dt_cen_cd" or do we just need the "district" and "st_nm" attributes?
