### ISSUE TITLE
Direct dial Helpline Numbers

### ISSUE THREAD

**Issue by rishabhnama** [covid19india/covid19india.github.io#2549]
A tap to call helpline numbers feature can be added to the footer for the visitors who may need assistance.
A single click on the link will prompt the user to make the call to mygov helpline portal and seek help. This feature on mobile will redirect to the dialer (on smartphone) and trigger call prompt (Windows Browsers) to the connected smartphone.
Adding the following code to the footer.js file will implement the feature as shown in Screenshot.

```<div>
<h3>Covid-19 Helpline:
<a href="tel:1075" >|Health Ministry| </a>
<a href="tel:1098"> | Child Support | </a>
<a href="tel:08046110007"> | Mental Health | </a>
<a href="tel:14567"> | Senior Citizens | </a>
<a href="tel:14443"> | Counselling | </a>
<a href="tel:9013151515"> | MyGov Whatsapp Helpdesk | </a>
</h3>
</div>
```

![Screenshot (48)](https://user-images.githubusercontent.com/47190861/130798653-01c1e2d9-a48e-4156-a049-a4f5b10e2289.png)

**Comment by itsMustafa** [comment]
Nice feature 👍🏻

**Comment by Arshadali7** [comment]
Good one 👌🏻

**Comment by forbidden451** [comment]
Helpfull 😯

**Comment by vipersvend** [comment]
Nice One👍🏼

**Comment by AkshayManekari** [comment]
Nice👏👏

**Comment by Sudeep-Mudaliar** [comment]
Good one. 👍
