### ISSUE TITLE
Operational handover documentation

### ISSUE THREAD

**Issue by chrisrrowland** [covid19india/covid19india.github.io#2554]
**Is your feature request related to a problem? Please describe.**
My organization is investigating keeping this site and its entire process operational rather than letting it go offline.

The documentation, at least as I am aware of it, doesn't go into a particularly detailed level covering daily operation (data updates) and publication.

Given the approaching end of life of the site, this investigation is a high priority for me, and I am actively trying to learn about the site having previously had 0 knowledge of its existence prior to yesterday, so please forgive me if I have missed some sources of information.

This request likely crosses the boundaries of all of the related covid19india repositories but I'm just creating the one issue at this point.

**Describe the solution you'd like**
Create or make public detailed documentation that details daily operation.  I have no experience with Telegram, but presumably could figure that out.  But more generically how individuals become aware of data that needs attention, how they update the data, and a general idea of how many person hours a day this requires.

Additionally if there is any knowledge of potential alternative data sources to reduce the number of individual data sources that need to be monitored.

Details about what code must be modified to support being hosted on an alternate domain.

Please feel free to ask for more details, I'm hoping a lot of what I'm interested in exists somewhere and I just haven't seen it.
I'm asking before I have had time to fully investigate myself due to the perceived urgency of the need.

Thank you for your help.

**Comment by shuklaayush** [comment]
Hi
We have a couple of blog posts detailing our tech stack and operations that you might want to go through. Happy to answer if you have more particular questions
https://blog.covid19india.org/2020/09/04/architecture
https://blog.covid19india.org/2021/08/24/operations

**Comment by chrisrrowland** [comment]
> Hi
> We have a couple of blog posts detailing our tech stack and operations that you might want to go through. Happy to answer if you have more particular questions
> https://blog.covid19india.org/2020/09/04/architecture
> https://blog.covid19india.org/2021/08/24/operations

Thank you, I have looked over those doucments. I suppose I thought those were more high level descriptions for curious folks, as opposed to low level day to day operations guides for people involved in running things, which was more of what I was looking for.

Since it seems like the majority of effort is spent in manual data entry (am I right about that?) is it easy to estimate approximately how  many person hours are used per day on this process, and what sort of domain knowledge is needed?

**Comment by bee-rickey** [comment]
Hi @chrisrrowland the things mentioned in the https://blog.covid19india.org/2021/08/24/operations are pretty much what happens on a day to day basis. 
1. Get the bulletin.
2. Send it to a bot to get values to enter in a sheet.
3. Enter into the sheet.

There are no specific requirements wrt to the skillset required. Since everything is driven by telegram and google sheets, one needs basic technology knowledge to keep values up to date. 

For data operations we have around 3-4 volunteers spending around 40min each per day.
