### ISSUE TITLE
SEO: Page title changes for all pages

### ISSUE THREAD

**Issue by UdayMallikarjun** [covid19india/covid19india.github.io#258]
Suggestions:
**Index page:** Coronavirus cases live dashboard | India
**Clusters:** Coronavirus spread in India | Visual Map
**Helpful Links:** Official Support helpline & useful links | Coronavirus
**FAQ:** FAQs | covid19india

Whoever is working on this, can also add hreflang tag in <head>

**Comment by Rajesh-Narayanappa87** [comment]
I can work on this.. Can you confirm below point.

1. Should below hreflang tag is fine?
`<link rel="alternate" href="https://www.covid19india.org" hreflang="x-default" />`
or should i set hreflang specific to india. Something like this.
`<link rel="alternate" href="https://www.covid19india.org" hreflang="en-in" />`

**Comment by Rajesh-Narayanappa87** [comment]
@UdayMallikarjun, @s-naveen : Could you pls have a look at PR

**Comment by jeremyphilemon** [comment]
Closing this since #261 addresses this
