### ISSUE TITLE
Can we do a thing as when we hover to a state it shows most affect city in that state?? It could possible spread more awareness among for where not to go in this situation

### ISSUE THREAD

**Issue by parthpatel1470** [covid19india/covid19india.github.io#260]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by JunaidBabu** [comment]
Could you explain clearly what you want to see?

**Comment by parthpatel1470** [comment]
https://drive.google.com/file/d/10X3bNqOqpvvXiMKz2qMYIKzHhVnmXkDU/view?usp=sharing

here in below maharastra we could write
as 
mumbai the most affected city

**Comment by agam-kashyap** [comment]
@parthpatel1470 Hey your idea is nice, but having that would be redundant, don't you think? Because we will anyway be able to click on a state and then see the severity. It isn't like a person will make a decision in hurry. Seems valid? Tell me if I am wrong :)

**Comment by JunaidBabu** [comment]
Not really an issue. Closing

**Comment by parthpatel1470** [comment]
Thanks I got the point you are trying to make
