### ISSUE TITLE
SEO: Meta tags optimisation & Schema markup addition

### ISSUE THREAD

**Issue by UdayMallikarjun** [covid19india/covid19india.github.io#261]
We have to change the meta details of each page to match & optimize for search queries. Similarly, we have to add schema markup so that search engines can know more about our site and pages. 

Whoever is working on this issue can pm on telegram for content. We will try to update the content here before that.

TG username: uday7darkrai

**Comment by vandanachandola** [comment]
@jeremyphilemon , @UdayMallikarjun  Is this taken? If not, I would like to give this a shot.

**Comment by UdayMallikarjun** [comment]
> @jeremyphilemon , @UdayMallikarjun  Is this taken? If not, I would like to give this a shot.

Sure you can take it up @vandana

**Comment by UdayMallikarjun** [comment]
> > @jeremyphilemon , @UdayMallikarjun  Is this taken? If not, I would like to give this a shot.
> 
> Sure you can take it up @vandanachandola

**Comment by jeremyphilemon** [comment]
@vandanachandola would you like to revive this?

**Comment by vandanachandola** [comment]
> @vandanachandola would you like to revive this?

yes, i'll be on it!
