### ISSUE TITLE
Submitting page to google for crawling/indexing + adding sitemap

### ISSUE THREAD

**Issue by UdayMallikarjun** [covid19india/covid19india.github.io#262]
We have to add the sitemap and submit the site. We can also ping google for crawling every time there is a major update.

More details: https://blog.hubspot.com/marketing/submit-website-google

**Comment by delsin474** [comment]
Is anyone working on this ?..If not you can assign it to me

**Comment by jeremyphilemon** [comment]
@delsin474 how does this work? I'm just curious about the process, don't mind assigning it to you!

**Comment by xi1570-krupeshanadkat** [comment]
I can help @delsin474 , I have knowledge about sitemap and submitting website to google webmaster for indexing.

**Comment by jeremyphilemon** [comment]
@krupeshxebia sure go ahead :)

**Comment by xi1570-krupeshanadkat** [comment]
> @krupeshxebia sure go ahead :)

I will start today at evening and hopefully complete it before monday, thanks :)

**Comment by xi1570-krupeshanadkat** [comment]
@jeremyphilemon Hi, due to heavy office workload, It is getting delayed. If you wish, you can un-assign me or if possible wait for few days more. sorry for inconvenience.

**Comment by jeremyphilemon** [comment]
@krupeshxebia no problem :)

**Comment by jeremyphilemon** [comment]
Closed by #1111
