### ISSUE TITLE
Pulling more data

### ISSUE THREAD

**Issue by shaunmulark** [covid19india/covid19india.github.io#27]
If possible extract data from major affected cities
Be it Bergamo from Italy or Madrid from Spain or Tehran from Iran.
It'll be useful in extrapolation of our affected states separately.

**Comment by sudevschiz** [comment]
This will be a nice analysis based on our data. Could you work on this? Would love to feature this on our website.

**Comment by sauravpratihar** [comment]
@shaunmulark do you have any UI/UX in mind for this?
