### ISSUE TITLE
"Admitted", "Indigo" etc. Showing Up As Travel Clusters Among Cities and Countries

### ISSUE THREAD

**Issue by ikartik90** [covid19india/covid19india.github.io#272]
**Describe the bug**
Certain airlines such as "Indigo", "Emirates" and "Air Arabia G9", and words like "Admitted" and "Arrived" are showing up on the Travel Cluster as International Destination Nodes.

**To Reproduce**
1. Go to 'covid19india.org'
2. Click on 'Clusters' tab
3. Select 'Travel' cluster filter
4. You would notice the above mentioned words showing up as international travel nodes on the graph.

**Expected behavior**
These values should not show up on the map as they are either the means of travel or are actions and have nothing to do with one's travel itinerary.

**Screenshots**
<img width="1048" alt="Screenshot 2020-03-28 at 2 48 44 PM" src="https://user-images.githubusercontent.com/11576848/77819821-da53ff80-7103-11ea-9519-dfc049713feb.png">
<img width="1174" alt="Screenshot 2020-03-28 at 2 49 03 PM" src="https://user-images.githubusercontent.com/11576848/77819827-e213a400-7103-11ea-986a-3a71e7972fe7.png">
<img width="1174" alt="Screenshot 2020-03-28 at 2 49 30 PM" src="https://user-images.githubusercontent.com/11576848/77819828-e344d100-7103-11ea-807b-feeaabeb3551.png">

**Additional context**
The problem is probably cropping up as this information is being fetched by crawling through the Notes tagged to each patient and exploring for comma separated values in those notes.

**Comment by JunaidBabu** [comment]
Please report to https://github.com/someshkar/covid19india-cluster

**Comment by sibeshkar** [comment]
@nirantk dealing with this. NLP analysis error.
