### ISSUE TITLE
Countries and Their Acronym Aliases Showing Up As Separate Nodes on Graph

### ISSUE THREAD

**Issue by ikartik90** [covid19india/covid19india.github.io#276]
**Describe the bug**
Countries that are also addressed by their acronyms, such as UK for the United Kingdom are showing up as two different international destination nodes on the travel cluster graph. You can see "UK" and "United Kingdom" as two separate nodes in the screenshot below. Similarly, "US" and "USA" are showing up as two separate international destination nodes on the graph. This is leading to skewing and misrepresentation of information.

**To Reproduce**
1. Go to 'www.covid19india.org'
2. Click on 'Clusters' tab
3. Select 'Travel' cluster filter
4. You would notice "UK" and "United Kingdom", and "USA" and "US" as separate nodes on the graph

**Expected behavior**
Countries and their aliases should be merged and represented as a single node.

**Screenshots**
<img width="1175" alt="Screenshot 2020-03-28 at 3 12 22 PM" src="https://user-images.githubusercontent.com/11576848/77820252-eab9a980-7106-11ea-855a-dc95d8302a5b.png">

**Additional context**
The problem is probably cropping up due to the crawling of CSV values in Patient Notes and not processing them for alias values before mapping them on to nodes.

**Similar Issue**
#272

**Comment by JunaidBabu** [comment]
Please report to https://github.com/someshkar/covid19india-cluster
