### ISSUE TITLE
WHY ALL CAPS?

### ISSUE THREAD

**Issue by suryaceg** [covid19india/covid19india.github.io#28]
Why everything in the website is in capital letters? Rethink the strategy.

**Comment by jeremyphilemon** [comment]
Very subjective. The uppercased type maintains consistency and is not used on body text at all. As far as type is concerned, we're using very minimal information and there aren't sentences of words to use Sentence Casing. However, might raise a poll to get a better opinion though, but closing this for now.

**Comment by suryaceg** [comment]
It's not subjective. It's science. All caps is best used sparingly.

Resources: 
1. https://blog.prototypr.io/all-caps-on-ui-good-or-bad-2570f14dc457 
2. https://uxmovement.com/content/all-caps-hard-for-users-to-read/ 
3. https://practicaltypography.com/all-caps.html
