### ISSUE TITLE
Improper column alignment in district-wise cases

### ISSUE THREAD

**Issue by shuklaayush** [covid19india/covid19india.github.io#282]
On mobile, the sticky header is misaligned when district entries are expanded. Gives the wrong impression that the entries are part of the Active Cases column.

![image](https://user-images.githubusercontent.com/27727946/77821082-60c10f00-710d-11ea-8786-cae7f2abd911.png)

**Comment by rahulzura** [comment]
I'd like to work on it, assign it to me.

**Comment by jeremyphilemon** [comment]
So the strategy here would be is to make the district headers sticky just below the state headers.

**Comment by rahulzura** [comment]
That requires the district heading to be a th element inside a thead and there can be only one thead inside a table. I've tried several ways but none produced a good solution.

**Comment by jrishabh55** [comment]
Is this issue still open for a volunteer ?, I'd like to work on the same

**Comment by nithinnani07** [comment]
How to reproduce this issue, Im willing to resolve this ! @shuklaayush 
@jeremyphilemon

**Comment by kirandeep123** [comment]
I would like to work on this one. if available, please assign.

**Comment by jrishabh55** [comment]
@jeremyphilemon I don't think issue exists any longer, can you confirm and let me know if you can replicate the same 

![image](https://user-images.githubusercontent.com/18290665/78688431-e4031180-7912-11ea-8934-632223d1a7df.png)

**Comment by jeremyphilemon** [comment]
@jrishabh55 Oh you're right! Sorry for having assigned you, feel free to request an "available" issue, I'll be glad to assign you again :)
