### ISSUE TITLE
Enhance sort logic

### ISSUE THREAD

**Issue by crup** [covid19india/covid19india.github.io#285]
**Is your feature request related to a problem? Please describe.**
Enhance sort function to sort by changes and total affected. If some states have equal number of affected people, it should then sort them on `delta`. Whichever has higher delta will be shown on top. 
![image](https://user-images.githubusercontent.com/2614954/77823721-38dca600-7123-11ea-9d79-c452f46b3f49.png)

**Describe the solution you'd like**
Would like to update the sort function that I wrote in my pr #211 if it gets merged. 

In the screenshot attached, if the states have same number of patients, they are then sorted alphabetically - obviously. It'd be great if there were a one more level of sorting on delta.

**Comment by ramakrishnan3** [comment]
can I take this up?
