### ISSUE TITLE
Activity Center needed to see history of cases throughout the day

### ISSUE THREAD

**Issue by bwayne2015** [covid19india/covid19india.github.io#292]
**Is your feature request related to a problem? Please describe.**
Whenever a new case coming in I cannot understand where it happened for  example I can see 1 minute ago updated and I can see the numbers but they are not clear enough to give me a clear picture where it happened without going into the db

**Describe the solution you'd like**
if there is a activity center where it can be mentioned something like this : "A new Confirmed case in the state of Maharashtra"
or "YaY!!! A new patient recovered from Covid-19"
then it will be helpful
**Describe alternatives you've considered**
The Other Alternative can be notifications but people can miss notifications and it's annoying also...rather an activity center will keep a history of events which I can come back to by the end of day and have a look.

**Comment by JunaidBabu** [comment]
This would be an interesting problem to solve. Change logs of the data is available here https://github.com/covid19india/api/commits/master

The change logs could be autogenerated to form meaningful statements.

**Comment by faisal3389** [comment]
I would like to pick this up, please assign this to me.

**Comment by jeremyphilemon** [comment]
@faisal3389 sure, go ahead! We would want the updates to be displayed below the table as of now.

**Comment by faisal3389** [comment]
@jeremyphilemon thanks for assigning the issue to me. I have added the activity center to look like this.
<img width="1084" alt="Screenshot 2020-04-06 at 12 42 29 PM" src="https://user-images.githubusercontent.com/16716470/78531979-15d98280-7804-11ea-98a9-93642457c592.png">

Let me know if this is fine.

**Comment by bwayne2015** [comment]
can't there be a bell icon on the top which shows this info on click of it...with a simle scrolling feature

**Comment by jeremyphilemon** [comment]
Closed by #725

**Comment by jeremyphilemon** [comment]
@bwayne2015 Can you open a new issue for that? Would be easier to assign someone!
