### ISSUE TITLE
Last update time is wrong only on apple devices 

### ISSUE THREAD

**Issue by rajathsn** [covid19india/covid19india.github.io#293]
**Describe the bug**
Last updated time is not getting updated on iOS devices like iPhone 

**To Reproduce**
1. Go to 'www.covid19india.org'
2. on 'any iOS and MacOS devices 
3. It works fine on android devices 

**Screenshots**
![337D641E-9E10-4D63-830D-4454AF6B4C1F](https://user-images.githubusercontent.com/52188338/77828815-c8924c80-7143-11ea-9c37-bd64f4878531.jpeg)

**Comment by ankush-0x90** [comment]
Hi @rajathsn, I have confirmed it. It shows 5 hours ago. :) Good work guys

**Comment by JunaidBabu** [comment]
@jeremyphilemon that z issue?

**Comment by shuklaayush** [comment]
@jeremyphilemon @JunaidBabu Can someone try this with #216 (without the colon in the timezone)? I think that's a better approach.
~~Nevermind, doesn't work with that either.~~ It does :P.
