### ISSUE TITLE
Display the state wise Last updated time

### ISSUE THREAD

**Issue by chinmaydalvi** [covid19india/covid19india.github.io#294]
**Description**
When I load the page every time I always see that Page updated a few minutes ago. But the count for many states remains the same, and this gives the wrong assumption to the user that no new patient found in a particular state. 

For example, I am seeing the count for Kerala is still 182 from the last few hours. and Recent page update is showing 10 minutes ago and count for other states are changing so because of that user wrongly assumes that new patients are not coming from Kerala.

**Solution**
It would be a good idea to display the Last updated time for every state. as it helps users to understand that we didn't get any updated data from that particular state from the last few hours and this also avoids any possibility of the assumption that no new patient found in a particular state.

**Comment by chinmaydalvi** [comment]
If this feature is accepted then I will work on this issue.

**Comment by chinmaydalvi** [comment]
Thanks, I will work on this.

**Comment by jeremyphilemon** [comment]
How/where do you plan on displaying the last updated time for each states?

**Comment by s-naveen** [comment]
Can we show it above district table when state is clicked?

**Comment by jeremyphilemon** [comment]
~I don't think that would be immediately obvious. Also having the last updated above the table could misrepresent that the whole table was last updated then (which is technically true but defeats the purpose of showing the last updated time for only districts).~ How about when you expand the state row, you could show the last updated time right below the state row, and above the district rows?

**Comment by s-naveen** [comment]
> How about when you expand the state row, you could show the last updated time right below the state row, and above the district rows?

That's exactly what I meant by saying above district table.

**Comment by jeremyphilemon** [comment]
@s-naveen I need sleep.

**Comment by chinmaydalvi** [comment]
@jeremyphilemon  @s-naveen 
I am planning to display just above the district table, as well as just after state name in India map, when the user clicks on any particular state, as many users don't open district table they just hover on states in the map.

**Comment by jeremyphilemon** [comment]
@chinmaydalvi Sounds good! :)

The lower right corner seems to be empty as of now, so here's another suggestion:

<img width="353" alt="Screen Shot 2020-03-29 at 11 07 49 AM" src="https://user-images.githubusercontent.com/17938322/77844238-a2a19200-71ad-11ea-8876-4152eb2f2bb5.png">

**Comment by chinmaydalvi** [comment]
@jeremyphilemon  Thanks
yes, we can display in district map also.

**Comment by chinmaydalvi** [comment]
@jeremyphilemon 

I need your view on  [comment](https://github.com/covid19india/covid19india-react/issues/294#issuecomment-605601257)

Currently, for Country map, I have shown the Last updated status for states and I am changing it when the user is hovering on different states.

On the district, map Should I need to show the Last updated status of the currently selected State as It gives the wrong perception to the user that we are showing the district wise status as well as we are keeping it as it is on hovering over districts. So it leads to confusion that on the Country map we are changing status on hovering but on the district map we aren't. 

As well as Currently, from API we are getting the blank status for the last update of every district. so in future when API is capable of sending district wise status that time we need to display District wise status over there.

So  Could you please tell me should I show the State's Last update status on the district map or just ignore it for now?

Thanks

**Comment by jeremyphilemon** [comment]
Hey, this is well thought out! I appreciate the analysis you've done :)

I believe it's best to show the last update times when hovered over the states, once we switch to district maps, it's best to remove the datapoint from the view. If you want, you can still add support for district last updates right now so that they can automatically display when we get the data! 

So when the datapoint is missing, we don't show the last update time, and when the datapoint is there, we can show it!

**Comment by chinmaydalvi** [comment]
Thanks, @jeremyphilemon  for your quick response. 

As per your suggestion, I am adding a provision to display the district status on the district map. Currently, it won't be visible to the user as district status is missing from API and would be visible automatically when API will start sending it.

**Comment by chinmaydalvi** [comment]
Hi @jeremyphilemon 

I have raised [PR](https://github.com/covid19india/covid19india-react/pull/342) for this feature 
Please have a look. 

Thanks and Regards,
Chinmay Dalvi
