### ISSUE TITLE
Delhi map does not show information

### ISSUE THREAD

**Issue by Nitin96Bisht** [covid19india/covid19india.github.io#298]
**Describe the bug**
Delhi map does not show information when you click on Delhi.

**To Reproduce**
1. Click on Delhi from the state list.
2. Select the Delhi map from the India map.
3. See error

**Expected behavior**
It should show information on the Delhi map like other states.

**Screenshots**
![image](https://user-images.githubusercontent.com/23516674/77830052-c633f080-714b-11ea-9df4-06fe75c10dc2.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 80.0.3987.149

**Comment by parthpatel1470** [comment]
It is happening for 
firefox too
on ubuntu

**Comment by parthpatel1470** [comment]
Probably happening because the name district and state is the same
and the bug starts happening when we start hovering, and the data initially shown is also of delhi as district not state

**Comment by tuxdna** [comment]
@jeremyphilemon Please review PR #303

**Comment by parthpatel1470** [comment]
covid19india/api/state_district_wise.json
in line 76 if you just change Delhi to New Delhi the bug would be solved just by adding simply one word
