### ISSUE TITLE
Dark Theme 

### ISSUE THREAD

**Issue by rsamit26** [covid19india/covid19india.github.io#299]
Working on the dark theme.

<img width="1440" alt="dark-1" src="https://user-images.githubusercontent.com/12140899/77830762-ce425f00-7150-11ea-9c53-972480e6bc10.png">
<img width="1440" alt="dark-2" src="https://user-images.githubusercontent.com/12140899/77830766-d1d5e600-7150-11ea-8297-9b53ce0b4136.png">
<img width="1440" alt="dark-3" src="https://user-images.githubusercontent.com/12140899/77830769-d4384000-7150-11ea-9c68-e7a83540b89f.png">

**Comment by shuklaayush** [comment]
Hey @rsamit26, please look at #116 before you proceed.
