### ISSUE TITLE
Update the data on page after every 15 / 20 mins

### ISSUE THREAD

**Issue by chinmaydalvi** [covid19india/covid19india.github.io#300]
**Description**
If you kept the page open for a long time it doesn't update the page automatically.
For example Currently, when you load the page first time it fetches the latest updated data and shows last updated is 10 min ago Now when you keep the tab open for a long time or minimize the browser (In case of the mobile device) and back again after 2 hours it still shows Last updated 10 min ago and data is not updated and this creates confusion to the user. therefore the user needs to reload the page manually.

**Solution**
After reloading the page hit the API to fetch the data after every 15 to 20 mins (any suggestion on time intervals are welcome) and according to that update the page. So that it keeps the page updated, as well as the user need not reload the page manually.

**Comment by chinmaydalvi** [comment]
If this feature is accepted then I will work on this issue.

**Comment by kousiksatish** [comment]
@JunaidBabu Please assign it to me. I would like to work on this.

**Comment by chinmaydalvi** [comment]
@kousiksatish 
I have already started working.

**Comment by kousiksatish** [comment]
@chinmaydalvi Okay. Missed to see that it was already assigned.

**Comment by sharathm** [comment]
I know this might already be part of the UI design, but mentioning that the page auto refreshes would definitely help. Something like

```
This page refreshes every {xx} minutes should be good somewhere at the top.
```

**Comment by chinmaydalvi** [comment]
@sharathm @JunaidBabu 
So Should I refresh the page after x min or do it without refreshing the page?

**Comment by sharathm** [comment]
@chinmaydalvi 
The whole page need not refresh right? it has to be one or more ajax calls from the page to refresh the content only.

**Comment by chinmaydalvi** [comment]
@sharathm @JunaidBabu 
I am implementing it without refreshing the page.  But In case you want to refresh the page after x min then I can also do that. 

I am seeking for proper approach. So please suggest me the approach.

**Comment by bhaskarghosh16** [comment]
@chinmaydalvi  I think it would be better to have this feature in place without refreshing the entire page. At the same time, the UX should be such, that the user understands that the data was refreshed , and he/she need not manually refresh again.

**Comment by chinmaydalvi** [comment]
@bhaskarghosh16 
Thanks for your opinion so will go ahead with the same approach.

**Comment by prabu-manickam** [comment]
@chinmaydalvi It would be great to have the counter to know the time left for the next automatic refresh

**Comment by chinmaydalvi** [comment]
@prabu-manickam 
I Need an opinion on your point.

@jeremyphilemon Are we good with functionality which I developed or do we need anything more?
