### ISSUE TITLE
Uttarakhand Map does not show information for Pauri district

### ISSUE THREAD

**Issue by tuxdna** [covid19india/covid19india.github.io#301]
**Describe the bug**
Uttarakhand Map does not show information for Pauri district

**To Reproduce**
1. Go to https://www.covid19india.org/
2. Click on "Uttarakhand" map

**Expected behavior**

The map shows Garhwal district, instead of Pauri. Rename from Garhwal -> Pauri required.

**Screenshots**

![Screenshot from 2020-03-29 00-04-54](https://user-images.githubusercontent.com/52947/77830928-04cca980-7152-11ea-9e01-e3802cf2ef09.png)

**Comment by JunaidBabu** [comment]
@guneetnarula could you please handle this?

**Comment by jeremyphilemon** [comment]
@guneetnarula I see that you've merged the PR! I'm not sure if all the corrections have been made, if so go ahead and close the issue :)

**Comment by tannakartikey** [comment]
@guneetnarula @jeremyphilemon I don't think the issue is fixed. I still see Garhwal with no cases.

**Comment by tannakartikey** [comment]
Are you sure it's deployed?

**Comment by jeremyphilemon** [comment]
Just merged and deployed, Garhwal with reference to this issue has been fixed!
