### ISSUE TITLE
PDF download/Excel Download for state wise/ City wise Breakout for analysis along with Print functionality 

### ISSUE THREAD

**Issue by bahuja** [covid19india/covid19india.github.io#310]
**Is your feature request related to a problem? Please describe.**

It is not related to the problem but it will be good to have featured since doctor and analyst might be interested in Print the whole page to get a snapshot of the current instance of the state or download it as a report so that it can be sent over to seniors etc. Also In analysts and researchers want to aggregate data that can be provided at the state level for the analysis purpose. 

**Describe the solution you'd like**
1. Export To Excel Button by clicking of which user can get the state wise or district wise count.
2. Export to PDF Button by which users can get the tabular view and map view with statewide data. 

**Describe alternatives you've considered**
PDF can download functionality can be implemented via IText sharp Etc. 

**Additional context**
Not Specifically.

**Comment by maniac-tech** [comment]
I can pick this up for Dev

**Comment by abhay6694** [comment]
I can take this and develop print and download functionality.

**Comment by shawavisek35** [comment]
I would like to work on this

**Comment by jeremyphilemon** [comment]
Closed by #661. If the people who commented here read this, csv/json downloads are being used at the moment, but a little more enhancements can be made especially when the filters are applied! Feel free to open it as an issue and assign yourself if you'd like to work on it :)
