### ISSUE TITLE
Fixing react-hooks/exhaustive-deps warnings.

### ISSUE THREAD

**Issue by jeremyphilemon** [covid19india/covid19india.github.io#313]
**Describe the bug**
Would be great if we could fix the `react-hooks/exhaustive-deps` warnings shown in the console . 

**To Reproduce**
Just open your console after `npm I && npm start`

**Expected behavior**
The console should be clear of these warnings.

**Screenshots**
<img width="862" alt="Screen Shot 2020-03-29 at 8 14 54 AM" src="https://user-images.githubusercontent.com/17938322/77840974-a5908880-7195-11ea-946e-3f9bd0e2735b.png">

**Additional context**
Fixing this would mean reading up `useEffect` and how their dependencies work. Here's a nice little guide https://overreacted.io/a-complete-guide-to-useeffect/

**Comment by vinay-thallam** [comment]
@jeremyphilemon  Can I take this issue ?

**Comment by ssonal** [comment]
Happy to help with this. Have 5 components cleaned up so far.

**Comment by jeremyphilemon** [comment]
@ssonal thank you :)

I'm gonna have to go with @vinay-thallam since he wanted to take the issue first! 

Feel free to checkout the other available issues!

**Comment by ssonal** [comment]
No problem. This was a great way to learn the code-base! Will help out elsewhere.

**Comment by vinay-thallam** [comment]
wow... You guys are awesome. 
Sorry. got busy with other work. @ssonal If you have already made progress please go ahead. 

@jeremyphilemon Thanks for the gesture.

**Comment by jeremyphilemon** [comment]
@ssonal all yours :)

**Comment by shuklaayush** [comment]
Fixed via #328
