### ISSUE TITLE
state map dashboard 

### ISSUE THREAD

**Issue by rajathsn** [covid19india/covid19india.github.io#314]
**Describe the bug**
In state map dashboard, the active, recovered and deceased is not showing any numbers 

**To Reproduce**

1. Go to ' www.covid19india.org '
2. Click on 'any state twice to open state map'
3. Confirmed number appears in its tab but active, recovered and deceased number are missing

**Expected behavior**
Display numbers in active, recovered and deceased 

Or

If state wise numbers not available, then remove the active, recovered and deceased box and just keep confirmed number

**Screenshots**
![EB5D58DA-2B3D-4ACF-9FFE-C0DB7DA935B4](https://user-images.githubusercontent.com/52188338/77842581-94ee0b80-71b1-11ea-81b5-312ff78bc1a9.jpeg)

**Smartphone (please complete the following information):**

- Device: iPhone SE and Moto E4 plus
- OS: iOS 13.3.1 and Nougat 7.1.1
- Browser: chrome browser and safari

**Comment by jeremyphilemon** [comment]
Patched!
