### ISSUE TITLE
Request: tiny arrows near Recovered and Deceased

### ISSUE THREAD

**Issue by acorreya** [covid19india/covid19india.github.io#316]
Please add tiny arrows near Recovered and Deceased showing recent activity, just like in Confirmed cases. Thank you!

**Comment by jeremyphilemon** [comment]
@JunaidBabu what was the reason behind removing state deltas from the table for active/recovered/deceased?

**Comment by sudevschiz** [comment]
Replied in #317 

If this is a duplicate, please close @jeremyphilemon
