### ISSUE TITLE
Feature: Comparison between yesterday and today's data

### ISSUE THREAD

**Issue by shayanpaul** [covid19india/covid19india.github.io#317]
Is it possible to show the new death count beside each state just like the new cases has been denoted using red up arrow. 

And also is it possible to have a separate tab to view the yesterdays’s data to compare with today’s data.

**Comment by jeremyphilemon** [comment]
The state deltas you're talking about has already been issued a little earlier, you'll have the status of that answered here at #316 

Regarding the comparison of yesterday vs today's data, I think a timeline scrub would be a nice feature to compare data across different dates. At the moment you can do the comparison in the time series graphs below across all dates so far, but I'm assuming you'd like to see data changes in the table and the maps too. 

This would be a nice feature. 

Here's how I see it being done, the data is fetched in the home component and distributed to the map, the table and the charts. Manipulating/Slicing the data would enable us to limit what's being supplied to the other components and achieve this timeline effect. 

As a start, a timeline axis can be placed at the bottom and on slicing/scrubbing can manipulate the data above for ranges of dates, or on a specific date.

<img width="637" alt="Screen Shot 2020-03-29 at 11 18 50 AM" src="https://user-images.githubusercontent.com/17938322/77844385-17c19700-71af-11ea-8463-4de63af48e1a.png">

**Comment by sudevschiz** [comment]
@shayanpaul Daily delta of number of deceased and recovered cannot the calculated from the raw_data directly as of now. This has to be calculated in a special way at the data source level, @mohammedshafeeqet is working on this.

After this is available through the API, we can show the delta numbers for each state.

**Comment by abhay6694** [comment]
At the data source level we can put a filter of time on data (Statewise) . Data which comes between 12:00:00AM to next day 12:00:00AM can be considered that day data and that way we can calculate the delta of that data for each state.

**Comment by abhay6694** [comment]
There could be many ways through which we can collect the data:- 

1. Make a simple google sheet form for the hospital admin staff to maintain the record. And then we can collate those results.
2. Maintain day wise data for each state.

**Comment by jeremyphilemon** [comment]
Just chiming in to say that 1. and 2. (specifically) have been added. You can check the individual states' pages to compare between the last five days :)

<img width="509" alt="Screen Shot 2020-04-24 at 3 33 51 AM" src="https://user-images.githubusercontent.com/17938322/80162595-6f032d80-85dc-11ea-9ee2-96ef6c03ceb6.png">
