### ISSUE TITLE
Rajasthan map does not show details.

### ISSUE THREAD

**Issue by SinghRajenM** [covid19india/covid19india.github.io#318]
**Describe the bug**
In map patient count is not reflecting on 'Pratapgarh' district of Rajasthan

**To Reproduce**

1. Go to 'Rajasthan map and expand it'
2. Click on 'Pratapgarh district'
3. Scroll down to 'Rajasthan' under column State\UT
4. See the patient count

**Expected behavior**
1. Map color of Pratapgarh should be changed (slight red)
2. It should show count as 2.

**Screenshots**
![image](https://user-images.githubusercontent.com/14791461/77844006-0a60d880-71c0-11ea-8170-1a6057470520.png)

**Desktop (please complete the following information):**

- OS: [e.g. iOS]: Win10
- Browser [e.g. chrome, safari]: FireFox 74.0
- Version [e.g. 22]: 74.0

**Comment by sijusamson** [comment]
Can i do this ?

**Comment by sijusamson** [comment]
@jeremyphilemon can i take this issue ?

**Comment by sijusamson** [comment]
@jeremyphilemon it seems for this issue we are using below mentioned url: "https://api.covid19india.org/state_district_wise.json",
it returns : "Rajasthan": {
    "districtData": {
      "Jaipur": {
        "confirmed": 11,
        "lastupdatedtime": ""
      },
      "Jhunjhunu": {
        "confirmed": 7,
        "lastupdatedtime": ""
      },
      "Bhilwara": {
        "confirmed": 21,
        "lastupdatedtime": ""
      },
      "Jodhpur": {
        "confirmed": 4,
        "lastupdatedtime": ""
      },
      "Unknown": {
        "confirmed": 10,
        "lastupdatedtime": ""
      },
      "Pratapgarh ": {
        "confirmed": 2,
        "lastupdatedtime": ""
      },
      "Ajmer": {
        "confirmed": 1,
        "lastupdatedtime": ""
      }
    }
  },  
**"Pratapgarh"** is displayed like "Pratapgarh " with a space, which should be avoided, I have created a pull request in API Repository, please review it, or if you say we can handle it in frontend, though its not a good practise.

**Comment by jeremyphilemon** [comment]
This looks like a fix for API. I'll transfer this issue over there! @JunaidBabu @sudevschiz transfer issue to api repo no?

**Comment by sijusamson** [comment]
Okay. @jeremyphilemon

**Comment by sijusamson** [comment]
@jeremyphilemon Issue has been fixed :-)
