### ISSUE TITLE
Daily delta needs to be near the delta graph

### ISSUE THREAD

**Issue by suryaceg** [covid19india/covid19india.github.io#32]
Daily delta sitting on top the cumulative number doesn't make sense. It needs to be near the small delta charts with a legend 

[+10 TODAY] something like this. Otherwise it's a very unintuitive data point. Many came to the group asking for what the number is in the past.

**Comment by Rajanpandey** [comment]
I can do it.
Let me know after the triage.

**Comment by suryaceg** [comment]
Hi @Rajanpandey this is done. Thanks

**Comment by suryaceg** [comment]
Pull request added by @s-naveen

**Comment by s-naveen** [comment]
#159
