### ISSUE TITLE
Replace the Patient DB excel link with a new page in the website

### ISSUE THREAD

**Issue by tecoholic** [covid19india/covid19india.github.io#322]
**Is your feature request related to a problem? Please describe.**
The patient DB is currently a link to a published Google Sheet. It is not very useful without any filtering or sorting functionality and also, it takes the user out of the website. There is no way to download the excel either.

**Describe the solution you'd like**
Add a page in the website which will show the patient DB as a HTML table with sorting and pagination which will allow the users to browse the DB directly in the website. Ability to download this data as CSV would be helpful too.

**Describe alternatives you've considered**
I have tried developing a data portal for this requirement, but was unruly stopped by a mob of Indian users who not only overloaded the system and crashed the server, but also left a bunch of useless reports.

**Additional context**
Example of the table that was provided by the portal

![image](https://user-images.githubusercontent.com/383862/77846542-74837880-71d4-11ea-9f22-7d17086ada1c.png)

**Comment by jeremyphilemon** [comment]
Dunzo!
