### ISSUE TITLE
Retract the old district wise popup when a new one is expanded on the table.

### ISSUE THREAD

**Issue by sivasatvik** [covid19india/covid19india.github.io#326]
**Is your feature request related to a problem? Please describe.**
When you expand more than one district view in the table, all of the previous ones stay open. It might not be what the users would want.

**Describe the solution you'd like**
When we expand a new district table, the previous one, if opened, should close.

**Additional context**
Any thoughts on this enhancement? (I can work on this if it's accepted :p)

**Comment by tannakartikey** [comment]
It might be possible that the user wants to keep it open. We can give the 'Close All' feature.

**Comment by sivasatvik** [comment]
Then the question begins to arise as to which state to focus on the map when which state is expanded. If there's a feature like this, it might be aesthetically sound and functionally unambiguous. Just a thought. Open to suggestions.

**Comment by tannakartikey** [comment]
When we hover over the name of the state the map highlights the state. I think that is good enough. 

I think it's better to keep multiple tabs open because it's easier to compare and take screenshots that way.

Leaving it to maintainers with that.

**Comment by jeremyphilemon** [comment]
The problem with automatically closing tabs is that the table jumps around on the user's screen. In order to prevent that, I had made the decision to leave them open. Might as well enable people to compare the numbers between states 👀 

Say if this feature was implemented anyway, it makes people lose the ability to compare then. No two state rows can be expanded, we're limiting the functions here. 

However, if we let it be just the way it is right now, the user still has freedom to do whatever he wants with the expanded district tables. Whadya think?

**Comment by shuklaayush** [comment]
I think #297 has addressed it perfectly without compromises. Just stick to expanding the map of the last clicked state (or state which contains the last hovered on district).

**Comment by sivasatvik** [comment]
Ah. I see. If the basic functionality is to provide user with as much information as possible, then the current functionality looks good. 
I just felt like if the user decides to expand a lot of the rows, then the user has to scroll a lot in order to get from one place to the other place. Although as it is the information is what we aim to show, then this would be inevitable. 

But as @tannakartikey suggested, we can prolly have the collapse all feature. What do you guys think.

**Comment by shuklaayush** [comment]
@jeremyphilemon How about adding an arrow to the left of the table header as well? Expand/Collapse all?

**Comment by sivasatvik** [comment]
How do you picture it? It's functionality would be 

1. Expand all of the district views*
2. Close all of the expanded district views*
(* no matter what all district views are opened or closed currently)

Or do you have something else in mind?

**Comment by shuklaayush** [comment]
@sivasatvik Exactly.
