### ISSUE TITLE
District labelling in the map of Manipur is done with old data!

### ISSUE THREAD

**Issue by khaaba** [covid19india/covid19india.github.io#327]
1. Present number districts in the state of Manipur is 16 (sixteen), NOT 9 (nine)
2. Imphal West District should have been next to the Imphal East District.
![Present](https://user-images.githubusercontent.com/19713703/77847705-bd3f2f80-71dc-11ea-9c23-cf636328f95c.png)

Manipur map showing the districts and its location with boundaries: 
![manipur-district-map](https://user-images.githubusercontent.com/19713703/77847709-c92af180-71dc-11ea-90b8-f5a29809deb7.jpg)

**Comment by tannakartikey** [comment]
May I ask how have we got this data for the map?

**Comment by JunaidBabu** [comment]
@guneetnarula can you check this?

**Comment by guneetnarula** [comment]
Solving issue #413 should fix this too

**Comment by jeremyphilemon** [comment]
Closed by #521
