### ISSUE TITLE
The heading should say more in the "Map" section

### ISSUE THREAD

**Issue by suryaceg** [covid19india/covid19india.github.io#33]
The heading says "Map" now doesn't say anything about the data you're about to see. It should be descriptive of the data shown below.

**Comment by firofame** [comment]
![Screenshot 2020-03-24 at 9 38 33 AM](https://user-images.githubusercontent.com/11689383/77387390-4f959c80-6db3-11ea-83c4-e29744e4b453.png)

@suryaceg is this better?

**Comment by steffyjohn** [comment]
**STATE-WISE STATUS** or **STATE-WISE STATISTICS**  would be good

**Comment by jeremyphilemon** [comment]
Fixed!
