### ISSUE TITLE
Top logo at home page looks clickable but it isn't.

### ISSUE THREAD

**Issue by Rajesh-Narayanappa87** [covid19india/covid19india.github.io#330]
**Describe the bug**
Logo on (fadeInUp logo) img looks clickable as hand pointer appears. But it is not clickable.

**To Reproduce**
1. Load https://www.covid19india.org/
2. hover on logo appearing left of Home, cluster link.

**Expected behavior**
Page refreshes and loads home page

OS : mac
Browser: Chrome

Common on all browsers.

**Comment by Rajesh-Narayanappa87** [comment]
@JunaidBabu : I can disable cursor for img tag. Pls assign to me..

**Comment by tanishq-soni** [comment]
@JunaidBabu  I can change it, i can assign homepage to that logo, when user clicks then he/she will be on HOME page.
or i can disable cursor,,.

please assign these task to me,.

**Comment by saberprashant** [comment]
#332

**Comment by saberprashant** [comment]
#332

**Comment by saberprashant** [comment]
@vamshi9666, I already submitted one PR #332 for this.

**Comment by vamshi9666** [comment]
My bad.  I didn't see that.

**Comment by vamshi9666** [comment]
Shall i close my pr ?

**Comment by saberprashant** [comment]
@vamshi9666, sorry, but I don't know that buddy.
Let, @JunaidBabu @jeremyphilemon decide which PR they want to merge :)

**Comment by vamshi9666** [comment]
okay cool

**Comment by jeremyphilemon** [comment]
Closing this because a lot of people seem to want to fix this. I shall hereby declare that the logo button shouldn't be clickable/hyperlinked, henceforth.
