### ISSUE TITLE
Donation Link not available.

### ISSUE THREAD

**Issue by tanishq-soni** [covid19india/covid19india.github.io#335]
Donation link to PM's COVID-19 relief fund not available in website,
It should be added as a button link which directly jumps to the website of COVID-19 relief fund when clicked on that button,
i can do if you assign the task to me.

**Comment by tecoholic** [comment]
There are some important questions raised here about that tweet did not officially come from @pmoindia. I think it is better to not include that link at this point.
https://twitter.com/logic/status/1243888629593731072?s=20

There are also individual state governments requesting donations, then it will become an issue of representation. It is better that the site stays unbiased.
