### ISSUE TITLE
Extra non-uniform coloured space on expanding any "ODD" number state

### ISSUE THREAD

**Issue by akshat112** [covid19india/covid19india.github.io#344]
**Describe the bug**
There are 3 lightgrey <td> on expansion on any ODD number of row in the state table on home page. 

**To Reproduce**

1. Go to 'Home page'
2. Click on 'any row  with lightgrey background color in the state table'
3. See error

**Expected behavior**
That should be changed to white color to get consistency.

**Screenshots**
![image](https://user-images.githubusercontent.com/36301928/77855188-7f59ff80-720c-11ea-8857-1af5a3ff9b82.png)

**Desktop (please complete the following information):**

- OS: Windows
- Browser Chrome

**Comment by AnirudhSriram** [comment]
This issue seems to be fixed with #319

**Comment by shuklaayush** [comment]
@AnirudhSriram Yep
