### ISSUE TITLE
Error Generate while click on cluster user's pointing icons.

### ISSUE THREAD

**Issue by harshk8** [covid19india/covid19india.github.io#345]
**Describe the bug**
Error coming on Cluster page, while clicking on the cluster user's pointing icon, whose data is not available in the data file/database i.e. from P1129
We can fix this by just deleting the unwanted rows.

![COVID-19 Tracker   India (1)](https://user-images.githubusercontent.com/30121010/77855722-d4e3db80-720f-11ea-8625-5c1a0c2ff219.png)

**To Reproduce**
Error Generated while clicking on the cluster user's pointing icon, whose data is not available in the data file/database
As of now, As shown in the screenshot, I faced the issue started from serial number "P1129".

**We can fix this by just deleting the unwanted rows from the file where we are taking data.**

- OS: Linux/Ubuntu
- Browser: Chrome 
- Version: 80.0.3987.149 (Official Build) unknown (64-bit)

**Comment by shuklaayush** [comment]
Please report in https://github.com/someshkar/covid19india-cluster. Closing
