### ISSUE TITLE
In mobile it should say "tap" not "hover"

### ISSUE THREAD

**Issue by suryaceg** [covid19india/covid19india.github.io#35]
The map subtext should say "tap" or "click" the map rather than hover in mobile devices.

**Comment by manishkungwani** [comment]
Will take this up.

**Comment by andante-9** [comment]
Will using regex work? 
https://stackoverflow.com/questions/11381673/detecting-a-mobile-browser

**Comment by jeremyphilemon** [comment]
Fixed in patch #62
