### ISSUE TITLE
Tracking Non-Virus Covid19 Lockdown Deaths 

### ISSUE THREAD

**Issue by anivar** [covid19india/covid19india.github.io#354]
**Is your feature request related to a problem? Please describe.**
India have an increasing death rate linked to Covid19 Lockdown measures. This is peculiar comparing to other countries in the world. 

**Describe the solution you'd like**
Please integrate API from 
http://projects.datameet.org/covid19/non-virus-deaths/

**Comment by thejeshgn** [comment]
API details if anyone is interested. You can cache it on your server as it changes only once a day.

https://twitter.com/thej/status/1244342448664371200

**Comment by asdofindia** [comment]
From a public health perspective, it is important to contextualize numbers to be able to make right decisions. There are no clear rights and wrongs in medicine. There are only relatively better/worse options.

Therefore integrating deaths due to non-virus causes is important.

It would also be useful to have breakdown of these deaths into different categories (eg: Non-COVID deaths due to lack of ventilators/ICU beds in hospitals, non-COVID deaths due to inability to refill on medications, accidents during migration, deaths due to police action, and so on).

These figures enable weighing risks and benefits for every time-critical decision, like provisions to be made in a hospital, or measures to take in local self governance, etc.

**Comment by thejeshgn** [comment]
We have a reason columns which can contain one more values from 

Medical Emergency
Road Blocked
Suicide
Lockdown
Exhaustion, 
Migration
Hunger

etc. We can add more as when we encounter
```

{
  "id": "2020-03-25|non_virus_deaths|17",
  "key": "2020-03-25|non_virus_deaths|17",
  "value": {
    "_id": "2020-03-25|non_virus_deaths|17",
    "_rev": "3-3381b76df61bff8c3b28276a1cffad27",
    "type": "non_virus_deaths",
    "location": "Rasingapuram",
    "district": "Theni",
    "state": "KL",
    "incident_date": "2020-03-24",
    "deaths": 4,
    "reason": [
      "Forest fire",
      "Roadblock"
    ],
    "source_date": "2020-03-25",
    "source_link": "https://www.thehindu.com/news/national/tamil-nadu/death-toll-rises-to-4-in-theni-forest-fire-tragedy/article31160605.ece",
    "source": "www.thehindu.com"
  }
}

```

**Comment by esafwan** [comment]
> API details if anyone is interested. You can cache it on your server as it changes only once a day.
> 
> https://twitter.com/thej/status/1244342448664371200

I think the API is not allowing cross-origin requests. I was just trying out the API after @anivar  shared the same. 

[](https://data.thejeshgn.com/covid19/_design/india/_view/non_virus_deaths?descending=false)

**Comment by thejeshgn** [comment]
@esafwan  Can you cache it on your server and use it. Server side pull should be okay right?

**Comment by esafwan** [comment]
Yes, it should work. 

I had forked this repo and was directly accessing via axios from client-side to see if I can send a PR.

**Comment by thejeshgn** [comment]
Let me know.

Else I will add this site to my CORS list.

**Comment by esafwan** [comment]
@thejeshgn Sorry got a bit held up. Correct me if I am wrong, I think `covid19india.org` is not using a backend. It's reading data from JSON files. In that case, we only have two options:

1. Write a CRON job somewhere to periodically download data of non-virus death and update the JSON file from where we update the site. 
2. Add covid19india.org to the CORS list. 

I think this decision should be taken by the maintainers (@jeremyphilemon)  and  @thejeshgn .

**Comment by thejeshgn** [comment]
Give me an hour. I will add cors for this domain.

Regards,
Thej

Thejesh GN ⏚ ತೇಜೇಶ್ ಜಿ.ಎನ್
http://thejeshgn.com

**Comment by thejeshgn** [comment]
I have added the CORS. It should work.

In case if it didn't use one of the CORS proxies. https://gist.github.com/jimmywarting/ac1be6ea0297c16c477e17f8fbe51347



Example, this should work too
http://api.allorigins.win/get?url=https%3A//data.thejeshgn.com/covid19/_design/india/_view/non_virus_deaths%3Fdescending%3Dfalse&callback=?

using

https://allorigins.win/

**Comment by shuklaayush** [comment]
Sorry, but this seems out of our scope.
