### ISSUE TITLE
Test Coverage

### ISSUE THREAD

**Issue by tannakartikey** [covid19india/covid19india.github.io#355]
**Describe the solution you'd like**

The project is attracting lots of contributors and the data we display is critical. So I thought if we add some test coverage to the codebase it will be great. That way we will be sure that the calculations are correct, new changes are not breaking anything and we will be confident while refactoring... (you know the benefits of the tests)

Since our project is open source we can use any CI/CD tool like Travis or use Zeit's build step.

**Comment by shuklaayush** [comment]
Yes! We need something other than just prettier errors to fix when pushing.

**Comment by jeremyphilemon** [comment]
Closing this because we now support tests. Henceforth we shall open new issues for adding specific test cases. 

@tannakartikey you can recommend, we can assign it to people looking to contribute :)
