### ISSUE TITLE
Add graphs for each state (data is available on state health dept websites)

### ISSUE THREAD

**Issue by sachingargtech** [covid19india/covid19india.github.io#362]
The speed-of-spread and the lockdown-effect will vary across different states, and knowing which states will open sooner or later will depend on the trend of rise or fall in new cases over time in each state. 

The site currently shows historical data and charts for all-india, but only shows current totals for each state. The historical data for each state and rising/falling trend data is not available per state.

There are plenty of international websites visualizing data for India, but none of them show the split across states and the woresing/improving trends for each state.

UI Suggestion - the charts in lower-right corner can update to show data for only the currently selected state in map above it, or the state selected from the list on left.

Data suggestion - historical data for each state can be found on state health departments websites:

For example, Delhi:
  http://health.delhigovt.nic.in/wps/wcm/connect/doit_health/Health/Home/Covid19/Health+Bulletin

For states where historical data is not available, historical data can at least be maintained from now on.

Thanks for all the good work.

**Comment by shuklaayush** [comment]
Hey @sachingarg05, those are great suggestions, but this discussion is already happening in #219. Feel free to comment over there. Closing
