### ISSUE TITLE
Overlapping of text and button under SPREAD TRENDS  section in home page.

### ISSUE THREAD

**Issue by ashish199820** [covid19india/covid19india.github.io#367]
**Describe the bug**
The text and button overlap when the screen width is between 375 to 405 px. "SCALE UNIFORMLY" should also be clickable. Mainly a bug for mobile users.

**To Reproduce**

1. Go to '/HOME' and scale the width in between 375 to 405 px.
3. Scroll down to 'spread trend ' section

**Expected behavior**
No overlapping between button and text. And the text should also provide a toggle effect.

**Screenshots**

![COVID-19 Tracker   India](https://user-images.githubusercontent.com/46785034/77881959-9dac1380-727d-11ea-99c0-f529d540c785.png)

**Comment by ashish199820** [comment]
solved the issue.PR #379. Kindly, review and merge.

**Comment by jeremyphilemon** [comment]
Closed by #363
