### ISSUE TITLE
The charts & title are difficult to interpret

### ISSUE THREAD

**Issue by suryaceg** [covid19india/covid19india.github.io#37]
Without a "Y axis" and related legends for the colours the charts look tough to interpret. The title "spread trends" are not very clear. Needs a different title. 

![image](https://user-images.githubusercontent.com/840117/77310030-a2277800-6d23-11ea-94c2-b9f22a7fd6a1.png)

**Comment by kracekumar** [comment]
I'm no UI person. 

<img width="580" alt="Screenshot 2020-03-23 at 4 27 18 PM" src="https://user-images.githubusercontent.com/311929/77310497-6f31b400-6d24-11ea-84fe-6764700b2c24.png">

In the first image, the graph has no x-axis, y-axis, no hover information. There is no interaction for the user, just an interpretation of the trend - `upward`, `even`, `downward`. If the intention is to show the trend, using "arrows" next to text may make sense or use some other strategy.

<img width="610" alt="Screenshot 2020-03-23 at 4 27 30 PM" src="https://user-images.githubusercontent.com/311929/77310524-78228580-6d24-11ea-8689-07dc98c21a9a.png">

In the second image, the graph has no y-axis unit now the number is in hundreds when numbers reach thousands, this is confusing without axis info. Even when the cursor changes while hovering the data, the data isn't displayed as a tooltip in the browser but at the beginning of the graph. I don't know this is optimization for mobile. It's confusing without the y-axis info.

Keep up the good work!

**Comment by jeremyphilemon** [comment]
@kracekumar really appreciate the detailed issue description and the screenshots! Will address them!

- [x] More context to timeseries charts
- [ ] Tooltip for minigraphs

**Comment by jeremyphilemon** [comment]
Closing this because we've made progress with the charts' readability by now. Will have to figure out the tooltips for the minigraphs since it's just an interpretation "upward/downward" we want people to visualize at the moment.
