### ISSUE TITLE
Improvement of mobile experience

### ISSUE THREAD

**Issue by pushkar8723** [covid19india/covid19india.github.io#372]
**Is your feature request related to a problem? Please describe.**
Right now on mobile, the table is shown before the graphs. Degrading the experience on mobile devices slightly.

**Describe the solution you'd like**
The experience on mobile can be enhanced by recording the content. Such that we have the table of raw data below the maps and graphs. We can use the CSS grid for this. That way the desktop experience will not be hampered to enhance the mobile experience.

**Describe alternatives you've considered**
An alternative would be to have the table on the right after the graph and put the map in place of the table. 

**Additional context**
On a dashboard, it is always preferred to have summarised data before the raw data.

**Comment by pushkar8723** [comment]
If and when we have an agreement on the solution. I would like to raise a PR for this.

**Comment by JunaidBabu** [comment]
This will be fixed in the redesigned version. Closing now.
