### ISSUE TITLE
TUMAKURU hovering issue

### ISSUE THREAD

**Issue by KarthikRao07** [covid19india/covid19india.github.io#374]
When selected  STATE Karnataka (hovering over TUMAKURU map not highlighted.

Easy to reproduce 
while checking source code   found this in karnatak.json 
st_nm": "Karnataka",
"district": "Tumkur"

while checking the state  found this 
Tumakuru
{confirmed: 1, lastupdatedtime: ""}
confirmed
1
lastupdatedtime
""
  sorry if the explainatiion is bad

**Comment by pk1997** [comment]
Fixed in #375

**Comment by shuklaayush** [comment]
Fixed via #429
