### ISSUE TITLE
Punjab Map - Shaheed Bhagat Singh Nagar District Cases 

### ISSUE THREAD

**Issue by balrajsingh9** [covid19india/covid19india.github.io#376]
**Describe the bug**
Shaheed Bhagat Singh Nagar district in Punjab has **19** cases till now, but when you hover over the map of Punjab it shoes as **0**.

**To Reproduce**

1. Go to https://www.covid19india.org/ desktop website.
2. Click on Punjab on the map view.
3. Hover over _Shaheed Bhagat Singh Nagar_.
4. See error - **0** cases, when in the table it shows the actual count, which is **19**

**Expected behavior**
When you hover over _Shaheed Bhagat Singh Nagar_, it should show **19** cases and percentage accordingly.

**Screenshots**
[Map View](https://imgur.com/a/uq0Vba6)
[Table View](https://imgur.com/a/BBZ6N5k)

**Desktop (please complete the following information):**

- OS: _MacOS_
- Browser: _Chrome and Microsoft Edge(Chromium Based)_.
- Version: _Chrome - 80.0.3987.149 (Official Build) (64-bit), Edge - Version 80.0.361.66 (Official build) (64-bit)_

**Comment by rachit995** [comment]
Fixed in #378
