### ISSUE TITLE
Show "tested" data

### ISSUE THREAD

**Issue by suryaceg** [covid19india/covid19india.github.io#38]
As we decided in Telegram the top KPIs should be,

1. Tested
2. Confirmed (showing active numbers like this)
3. Recovered 
4. Deceased 

![image](https://user-images.githubusercontent.com/840117/77310306-1f52ed00-6d24-11ea-83bc-8efa9bd42ba0.png)

**Comment by sirajalam049** [comment]
Is this just the design (and removing active and adding tested) change for the image below?

![image](https://user-images.githubusercontent.com/22110988/77398132-ec186880-6dcc-11ea-86e9-6f53636bb198.png)

**Comment by jeremyphilemon** [comment]
Duplicate, please discuss over at #9
