### ISSUE TITLE
District names overflowing to the back button - Reopening #304

### ISSUE THREAD

**Issue by Nitin96Bisht** [covid19india/covid19india.github.io#384]
Reopen #304 as It was closed without fixing.

On mobile, long district names overflow and appear over the back button in expanded view.

![image](https://user-images.githubusercontent.com/23516674/77900992-7f094500-729c-11ea-8aa5-0929d4b17bda.png)

**Comment by sudevschiz** [comment]
Thanks for looking into this and sorry for the huge delay in us getting back to you. 

Making this low priority thought.

**Comment by shuklaayush** [comment]
Closed due to inactivity
