### ISSUE TITLE
Throws an error after clicking on total in the state table

### ISSUE THREAD

**Issue by chinmaydalvi** [covid19india/covid19india.github.io#387]
**Description **
Throws an error after clicking on Total in the table state table
you can see the error in the JS console. Refer to the screenshot.

**To Reproduce**
1. Go to the [https://www.covid19india.org/](https://www.covid19india.org/) 
2. open JS console.
2. Click on Total in State table 

**Expected behavior**
Should not throw any error.

**Screenshots**
<img width="1671" alt="Screenshot 2020-03-30 at 4 00 30 PM" src="https://user-images.githubusercontent.com/14978241/77903341-51be9600-72a0-11ea-8d93-a7d77432d581.png">

**Comment by chinmaydalvi** [comment]
Will take this as I have started working on it.

**Comment by rakeshreddy1410** [comment]
#389 can you review this PR

**Comment by shuklaayush** [comment]
@chinmaydalvi I think someone fixed it already in #389

**Comment by chinmaydalvi** [comment]
@shuklaayush  Ok close the PR once it is fixed

**Comment by yuvarajvemula** [comment]
It seems PR #389  still open due to conflict.
Please check #588 - may solve the issue
Please review it once.

**Comment by chinmaydalvi** [comment]
@shuklaayush 
This issue is fixed now so closing the PR
