### ISSUE TITLE
Add daily change count in the table for each state for deceased and recovered people

### ISSUE THREAD

**Issue by Manvi-Agrawal** [covid19india/covid19india.github.io#399]
Adding daily change count in the table for each state for deceased and recovered helps to evaluate risks

**Comment by shuklaayush** [comment]
Hi @Manvi-Agrawal, the relevant code is there but the API is currently not  publishing this information. Refer to https://github.com/covid19india/covid19india-react/issues/317#issuecomment-605617519.

Closing.
