### ISSUE TITLE
Some visualization problem only for Jammu and Kashmir

### ISSUE THREAD

**Issue by dpnkrpl** [covid19india/covid19india.github.io#403]
![IMG_20200330_222735](https://user-images.githubusercontent.com/27947066/77940062-b9db9f00-72d5-11ea-967a-4d2f660eabbd.jpg)
Some minor visual problem only for J&K state.

**Comment by strikertanmay** [comment]
I check out this bug. Below 382px (width) this glitch occurs. I would like to fix this.

**Comment by shuklaayush** [comment]
Also happens for Andaman and Nicobar islands

**Comment by strikertanmay** [comment]
> Also happens for Andaman and Nicobar islands

Above made PR will fix this issue for all states.
 Check on this - https://covid19india-react-git-fork-strikertanmay-strikertanmay-fx-403.covid19india.now.sh

**Comment by shuklaayush** [comment]
Seems to be fixed
