### ISSUE TITLE
Uttarakhand district-level data not adding up

### ISSUE THREAD

**Issue by rajhrikshit** [covid19india/covid19india.github.io#404]
**Describe the bug**
The number of district-level confirmed cases in Uttarakhand does not add up to the total number of confirmed cases. The only confirmed cases are shown in Dehradun which is less than the total number of confirmed cases. Even the number of people with the unknown district do not compensate for the missing amount.

**To Reproduce**

1. Go to the home page.
2. Click on Uttarakhand on the map.

**Screenshots**
![Screenshot (10)](https://user-images.githubusercontent.com/32279120/77942983-56b82100-7271-11ea-951b-5c75e305027d.png)
![Screenshot (11)](https://user-images.githubusercontent.com/32279120/77942992-5881e480-7271-11ea-9956-d9027c14ff1d.png)

**Comment by shuklaayush** [comment]
Should be solved with #383

**Comment by jeremyphilemon** [comment]
Closed by #521
