### ISSUE TITLE
Uttarakhand Map does not show information for Pauri Garhwal district

### ISSUE THREAD

**Issue by tuxdna** [covid19india/covid19india.github.io#409]
Steps to reproduce are same as in https://github.com/covid19india/covid19india-react/issues/301

However there are two issues:

 * The map file for Uttarakhand state was reverted ( Json pretty formatted ), and district Pauri got reverted back to Garhwal 
 * The correct name should now be "Pauri Garhwal" as in the Google Spreadsheet (rows 640, 921 ) - https://docs.google.com/spreadsheets/d/e/2PACX-1vSc_2y5N0I67wDU38DjDh35IZSIS30rQf7_NYZhtYYGU1jJYT6_kDx4YpF-qw0LSlGsBYP8pqM_a1Pd/pubhtml

 
We need to fix the map to reflect correct district name to "Pauri Garhwal" now.

**Comment by shuklaayush** [comment]
Duplicate of #404
