### ISSUE TITLE
Helpline numbers for every state and the central number

### ISSUE THREAD

**Issue by bhaskarghosh16** [covid19india/covid19india.github.io#412]
**Is your feature request related to a problem? Please describe.**
This app should include the data related to official government helpline numbers, especially numbers for each and every state. 

**Describe the solution you'd like**
The map of India shows the information related to the cases. It would be extremely helpful to anyone to have the government helpline number as well for each and every state.

**Comment by JunaidBabu** [comment]
Already available in https://www.covid19india.org/links

**Comment by bhaskarghosh16** [comment]
Hello. Not as a URL but displayed specifically for each state in the map. There are lots of whitespace that could be used.

Please see PR : https://github.com/covid19india/covid19india-react/pull/407
