### ISSUE TITLE
Update all district shapefiles (JSONs)

### ISSUE THREAD

**Issue by guneetnarula** [covid19india/covid19india.github.io#413]
We are using old district boundaries for most states. Telangana, West Bengal, Manipur, Gujarat, Maharashtra to name a few. This is causing both name mismatch problems and missing data

**Solution**
We have access to district boundaries from 2019, we can replace the JSONs we are using with new ones. The new JSONs also match well with the district names reference we are using for data collection.

Should resolve related issues like #253 and #256

**Comment by harshvitra** [comment]
Can you share the json files we can fix this easily

**Comment by guneetnarula** [comment]
Yes, on it

**Comment by guneetnarula** [comment]
Latest json files are available here: https://github.com/guneetnarula/indian-district-boundaries/tree/master/topojson/state-wise 

In my last PR, jsons for Andhra Pradesh, J&K and Ladakh were integrated. So use the others for now. I'll upload the remaining within a day.

**Comment by sivaanil** [comment]
@guneetnarula Little curious May I know from where can you get these files ?

**Comment by guneetnarula** [comment]
@shuklaayush @JunaidBabu @sudevschiz 
Almost all of the topojsons are available now in the repo link above. Will finalize Tamil Nadu and the remaining states of northeast once we have the latest available.

@sivaanil - these are community led efforts that are more or less manual in nature. See projects.datameet.org/maps/ for more (although we still have to update the datameet repositories with the latest)

**Comment by sivaanil** [comment]
Thank you for the info @guneetnarula

**Comment by limshark** [comment]
I noticed Gwalior District and Datiya District map in Madhya Pradesh state are not showing correctly, Not sure if I need to file a seperate issue or it is taken care by Json file udpate. the official map is hosted at  http://geoportal.mp.gov.in/DistrictPortal.aspx   . Both district you will find in north of Madhya Pradesh map.   The Covid19india site is showing incorrectly.

**Comment by limshark** [comment]
Both are at the north of Madhya Pradesh.

**Comment by psunthar** [comment]
Several maps are not scaled and translated with the actual GIS boundaries.
Tamil Nadu, for instance.  I tried playing around with the transform.scale and transform.translate values, but it is very difficult to determine the correct position by trial and error.

Any clues how to do this easily?

**Comment by shuklaayush** [comment]
@psunthar d3 has [fitSize/fitExtent](https://github.com/d3/d3-geo#projection_fitExtent) methods for this purpose

**Comment by guneetnarula** [comment]
> I noticed Gwalior District and Datiya District map in Madhya Pradesh state are not showing correctly, Not sure if I need to file a seperate issue or it is taken care by Json file udpate. the official map is hosted at http://geoportal.mp.gov.in/DistrictPortal.aspx . Both district you will find in north of Madhya Pradesh map. The Covid19india site is showing incorrectly.
 
@limshark Is it correct here: https://github.com/guneetnarula/indian-district-boundaries/blob/master/topojson/state-wise/madhyapradesh.json ?

**Comment by limshark** [comment]
@guneetnarula , yes, both the district Gwalior and Datiya looks correct in https://github.com/guneetnarula/indian-district-boundaries/blob/master/topojson/state-wise/madhyapradesh.json .

**Comment by KrishnaPravin** [comment]
#530

**Comment by guneetnarula** [comment]
Hey @jeremyphilemon @shuklaayush just uploaded another batch of jsons. Covers all union territories and remaining northeast states. Only MZ and TN are left now. Needs some work. https://github.com/guneetnarula/indian-district-boundaries/tree/master/topojson/state-wise

**Comment by guneetnarula** [comment]
Last two states done! See https://github.com/guneetnarula/indian-district-boundaries/tree/master/topojson/state-wise for TN and MZ
