### ISSUE TITLE
Add support to Kannada language

### ISSUE THREAD

**Issue by developergouli** [covid19india/covid19india.github.io#414]
It would be very helpful to have website display statistics in Kannada language so that people from Karnataka who are not familiar with English can use this website to track the status of Corona

The approach of using some of the automated tools for translation might not convey intended messages due to limitation in translation support for Kannada or any other Indian languages. Hence someone needs to manually translate the strings used in this website.

The solution would be to use react-localization package and replace all hard coded strings with placeholders for messages and use some kind of dictionary to replace the placeholders at run time

![image](https://user-images.githubusercontent.com/25430129/77982237-77b05e80-72d1-11ea-9f4c-b3f7f0393ce3.png)

![image](https://user-images.githubusercontent.com/25430129/77982736-a844c800-72d2-11ea-8dec-42aed2717c3f.png)

![image](https://user-images.githubusercontent.com/25430129/77982649-77fd2980-72d2-11ea-80b8-a4b8563b8ad3.png)

![image](https://user-images.githubusercontent.com/25430129/77982717-98c57f00-72d2-11ea-81dd-bf02d932b343.png)

**Comment by jeremyphilemon** [comment]
Working on this is #357, issues #21 #98 :)
