### ISSUE TITLE
Deltas For Other Columns per state

### ISSUE THREAD

**Issue by manaskhandelwal** [covid19india/covid19india.github.io#418]
### So as you display deltas for confirmed cases try displaying it for other columns like    death/recovered etc.
***
>_**Something like below:**_
![improvmentIdea](https://user-images.githubusercontent.com/53651226/78007051-614ee500-735b-11ea-84a2-c0e64b390146.PNG)

**Comment by vandanachandola** [comment]
@manaskhandelwal I can work on this, if it's not already taken?

**Comment by sivaanil** [comment]
@manaskhandelwal The code is already there. When the data is available it will show up automatically.

Here is the code related to 
**Recovered:** https://github.com/covid19india/covid19india-react/blob/master/src/components/level.js#L63

** Deceased:** https://github.com/covid19india/covid19india-react/blob/master/src/components/level.js#L77

Looks like it needs to be updated here 
Eg: https://github.com/covid19india/api/blob/master/data.json#L568

And also I feel some other files to be updated

**Comment by shuklaayush** [comment]
@sivaanil is right. The relevant code is there, but the API is not currently publishing this information. Refer to https://github.com/covid19india/covid19india-react/issues/317#issuecomment-605617519.

Closing.
