### ISSUE TITLE
Addition of Helpline numbers for each state in the MAP view

### ISSUE THREAD

**Issue by bhaskarghosh16** [covid19india/covid19india.github.io#425]
**Is your feature request related to a problem? Please describe.**
This app should include the data related to official government helpline numbers, especially numbers for each and every state. A PDF is already available for this in Helpful links section, however, having this information in the UI (Map view) is far more convenient. 

**Describe the solution you'd like**
The map of India shows the information related to the cases. It would be extremely helpful to anyone to have the government helpline number as well for each and every state.

Please see  https://github.com/covid19india/covid19india-react/pull/407

**Comment by jeremyphilemon** [comment]
Hey, thanks for filing the issue. I believe this is already there under helpful links, and the numbers are subject to change so we've just linked a PDF at them moment, which should be good!

Thanks anyway :)
