### ISSUE TITLE
Website freezes on expanding Andaman and Nicobar islands

### ISSUE THREAD

**Issue by shuklaayush** [covid19india/covid19india.github.io#427]
**Describe the bug**
Website freezes when expanding to district view of Andaman and Nicobar islands on phone (Chrome/Android).

**To Reproduce**
1. Expand table entry of Andaman and Nicobar Islands
2. Tap on any district

**Additional context**
Appears to be a problem with the complexity and/or size of the Andaman and Nicobar islands map JSON. A solution might be to simplify the map.

**Comment by jeremyphilemon** [comment]
Whoa good catch!

**Comment by AjithKumarvm** [comment]
https://www.covid19india.org/maps/andamannicobarislands.json is 135KB(zipped) and 652KB(unzipped). the `arcs` key has too much data that mobile can handle. tested on One plus 7. It took like 2 - 3 minutes to unfreeze.

**Comment by varungupta3009** [comment]
Was this fixed? Because it works perfectly fine on my low-end device.

**Comment by shuklaayush** [comment]
@varungupta3009 Don't think it was. It still freezes on my phone. The weird part is that it works fine on Firefox mobile.

**Comment by KrishnaPravin** [comment]
@shuklaayush I would like to work on this. could you assign me?

**Comment by varungupta3009** [comment]
> @varungupta3009 Don't think it was. It still freezes on my phone. The weird part is that it works fine on Firefox mobile.

Yes. Turns out that it hangs on Chrome, but it's perfectly fine on Chrome Canary. I was using Canary on both. So it's an optimization issue that will probably be fixed in the near future.

**Comment by shuklaayush** [comment]
> > @varungupta3009 Don't think it was. It still freezes on my phone. The weird part is that it works fine on Firefox mobile.
> 
> Yes. Turns out that it hangs on Chrome, but it's perfectly fine on Chrome Canary. I was using Canary on both. So it's an optimization issue that will probably be fixed in the near future.

Thanks! I guess there's nothing to fix then.
