### ISSUE TITLE
A few districts of Gujarat are not highlighted upon hover

### ISSUE THREAD

**Issue by tannakartikey** [covid19india/covid19india.github.io#434]
**Describe the bug**
All the cities are highlighted in Gujarat's map upon hover except below(spelled as in the list):
 - MAHESANA
 - KACHCHH
 - GIR SOMNATH

I think it is happening because the spelling of these cities is wrong on the map. In the map they are spelled correctly as below:

 - MEHSANA
 - KUTCH
 - The district of Gir Somnath is not there on the map.

**To Reproduce**

1. Open the list of the districts of Gujarat
2. Hover over any of the districts listed above

**Expected behavior**
The cities should be highlighted upon hover.

**Screenshots**
Notice that KACHCHH is not highlighted on the map

![image](https://user-images.githubusercontent.com/422544/78102100-17bbd400-7407-11ea-8a6c-80e974caeeaf.png)

**Additional context**
Map of Gujarat for the reference: https://en.wikipedia.org/wiki/South_Gujarat#/media/File:Map_GujDist_South.png

**Comment by guneetnarula** [comment]
This should be resolved by fix #521
