### ISSUE TITLE
Show daily increase in recovery and deceased columns, statewise

### ISSUE THREAD

**Issue by bigfoot31** [covid19india/covid19india.github.io#438]
**Describe the solution you'd like**
which states has deaths today. .e.g. +2 in deceased column of main plot. Duplicate of functionality already present in column 1.

**Comment by shuklaayush** [comment]
Hi @bigfoot31, the relevant code is there but the API is currently not publishing this information. Refer to https://github.com/covid19india/covid19india-react/issues/317#issuecomment-605617519.

Closing.
