### ISSUE TITLE
Right Padding Needed at Graph

### ISSUE THREAD

**Issue by codeslane** [covid19india/covid19india.github.io#439]
![Screenshot_20200401-131629_Chrome](https://user-images.githubusercontent.com/26877201/78112066-493e9a80-741b-11ea-89c0-a9b0760382c0.jpg)
The number are attaching to the corner.

**Comment by Amritesh** [comment]
What needs to be done here is to format the numbers in place of playing with the padding. So that
1500 become 1.5k and 15000 becomes 15K. 
I can also adjust the padding if reuqired. Going to create a PR to format the numbers.

**Comment by jeremyphilemon** [comment]
Closed by #363
