### ISSUE TITLE
Palghar district level not distinguished in map (carve out from Thane).

### ISSUE THREAD

**Issue by abdullahkhilji** [covid19india/covid19india.github.io#440]

**Comment by Nitin96Bisht** [comment]
@abdullahkhilji Can you please describe it in detail along with a screenshot if possible?

**Comment by abdullahkhilji** [comment]
Actual Maharashtra Map with Palghar:
<img width="127" alt="Screenshot 2020-04-01 at 10 54 31 PM" src="https://user-images.githubusercontent.com/33245628/78167289-ddd0e900-746b-11ea-8795-4ad09b2760cf.png">

Current Map:
<img width="155" alt="Screenshot 2020-04-01 at 10 55 00 PM" src="https://user-images.githubusercontent.com/33245628/78167335-f0e3b900-746b-11ea-83ba-7c65f0b0650b.png">

How should I update the map and start a Pull Request?

**Comment by guneetnarula** [comment]
Yes, this will be resolved by #413

**Comment by guneetnarula** [comment]
Watch out for fix #521

**Comment by abdullahkhilji** [comment]
Yes, the issue is fixed.
