### ISSUE TITLE
Change to state table view upon clicking on a state in map

### ISSUE THREAD

**Issue by sandeephegde16** [covid19india/covid19india.github.io#444]
**Describe the bug**
Upon clicking on state to see district wise data, left side table should show particular state and district data. Now, if user clicked on state map and accidentally hovers on left side table, then map changes automatically to India map.

**To Reproduce**
1. Double click on any state to get district view.
2. Hover courser on left side statewise tracker (Any other state)
3. State map changes to India map.

**Expected behavior**
Once clicked on state map, left side table data should change to particular statewise data. Clicking on back button should take user back to India map and all states data.

- OS: Windows
- Browser: Chrome

**Comment by hiren0ded** [comment]
Instead of onHover on table row, It would be good if **click** on table row and then it reflects on India map.

**Comment by milap1296** [comment]
I would like to take this up if not already ? @jeremyphilemon

**Comment by jeremyphilemon** [comment]
This has been patched but with a different strategy in mind, thanks for raising the issue :)
