### ISSUE TITLE
A + sign on the patient in the cluster map if the patient is a doctor or a healthcare worker

### ISSUE THREAD

**Issue by keepitopen** [covid19india/covid19india.github.io#445]
If there is incoming data about the cases being citizen or doctor, we can show them up in the cluster. 
However, this has a little bit of a potential downside with inaccurate representation of such patients in case of non-availability of data, thereby rendering our main concern of making the public aware of the conditions in which health workers are working. If this is not a significant problem though, such an addition might be helpful.

**Comment by shuklaayush** [comment]
Please report on https://github.com/covid19india/covid19india-network
