### ISSUE TITLE
Districts Unknown entry in state view

### ISSUE THREAD

**Issue by sandeephegde16** [covid19india/covid19india.github.io#446]
**Describe the bug**
An entry unknown districts appearing in state view.

**To Reproduce**
1. Double click on any state
2. See an entry 'Unknown Districts' on left side below district name.

**Expected behavior**
I believe it should show total no of districts in a state.

**Screenshots**
![image](https://user-images.githubusercontent.com/35073693/78121686-4e0a4b00-7429-11ea-9e6e-16e45230cb55.png)

**Desktop (please complete the following information):**

- OS: Windows
- Browser: Chrome

**Comment by shuklaayush** [comment]
@mykerehittal It represents the number of cases in the state for which we don't have district information. I don't think showing total number of districts adds any value to the map. We're already short on space. Thanks, I'm closing this for now. We can reopen it if the need ever arises.
