### ISSUE TITLE
Recovery and deceased count should be shown state wise atleast like showing in confirmed cases

### ISSUE THREAD

**Issue by dehalder22** [covid19india/covid19india.github.io#451]
As we see everyday there is a red up arrow beside the count of state wise confirm cases. The same should be reflected in case recovery as well as deceased. Because we are observing for example total 13 recovery in India in a day but couldn't indentify the delta or in which state many value has been increased. This should be same as confirmed case feature.

**Comment by shuklaayush** [comment]
Hi @dehalder22, the relevant code is there but the API is currently not publishing this information. Refer to https://github.com/covid19india/covid19india-react/issues/317#issuecomment-605617519.

Closing.

**Comment by dehalder22** [comment]
Hi @shuklaayush  thanks for the info.
