### ISSUE TITLE
Spelling Mistake in District Name [West Bengal]

### ISSUE THREAD

**Issue by Baibhab97** [covid19india/covid19india.github.io#452]
**Describe the bug**
The district 'Darjeeling' in West Bengal is wrongly spelt as 'Darjiling'.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to the home page.
2. Click on the state of West Bengal.
3. Scroll to the topmost district.

**Expected behaviour**
The name of the district should be 'Darjeeling'.

**Screenshots**
![Screenshot from 2020-04-01 16-30-28](https://user-images.githubusercontent.com/20902312/78130146-5f0d8900-7436-11ea-9ef7-2bbdb804f092.png)

**Desktop (please complete the following information):**

All versions.

**Smartphone (please complete the following information):**

All Versions.

**Comment by Baibhab97** [comment]
Please assign it to me. Have already fixed this.

**Comment by Nitin96Bisht** [comment]
@shuklaayush Kindly check PR #479

**Comment by guneetnarula** [comment]
This should be resolved by fix #521
