### ISSUE TITLE
Embed Total Time Passed Countdown Since COVID-19 Outbreak

### ISSUE THREAD

**Issue by codeslane** [covid19india/covid19india.github.io#456]
Please add the total time passed since the COVID-19 Outbreak below header.

Fact: The First case reported in India was 30th January.

Also, it would be great if every individual city can have their own countdown

**Comment by strikertanmay** [comment]
I hope (https://github.com/covid19india/covid19india-react/issues/337) will solve this issue. I thought both issues are almost the same. If I'm wrong, please correct me.

**Comment by codeslane** [comment]
Yeah Almost Same to feature #337 but with additional countdown

**Comment by sudevschiz** [comment]
Does this really add any value? If we know that the first reported case in say, Himachal Pradesh is 15th March, how can it be used?

**Comment by tannakartikey** [comment]
@sudevschiz I am not sure the first reporting date (#337) will add any value or not but countdown surely will not. I think we should close this one.

**Comment by strikertanmay** [comment]
> Does this really add any value? If we know that the first reported case in say, Himachal Pradesh is 15th March, how can it be used?

This feature will help people to get information that may be important sometimes as the date of the first reported case shows the level of danger in the particular state/district. This will also help doctors, analysts, and other people to take important decisions if required.
Suppose first reported case of any district xyz is 11 April, it helps gov to take steps and people to stay aware

**Comment by tannakartikey** [comment]
@strikertanmay good point.
I agree with the first report date with your argument but the countdown will clutter the UI. People can manually count from the first reported date.

**Comment by bee-rickey** [comment]
This feature does not add any value. Closing.
