### ISSUE TITLE
Display daily growth factor

### ISSUE THREAD

**Issue by sandeephegde16** [covid19india/covid19india.github.io#464]
**Is your feature request related to a problem? Please describe.**
For a desease like covid19, we need to make use of every analysis possible. It would be great to show a daily growth factor of the disease in a map.

We can have a drop down to select daily growth factor of new cases, daily growth factor of deaths.

Daily Growth Factor of New Cases = Total new cases of yesterday/ Total new cases of today

Daily Growth Factor of Deaths = Total new deaths of yesterday/ Total new deaths of today

**Comment by krunal704** [comment]
It should also have Daily Growth factor of Recovered patients
Daily Growth Factor of Recovery = Total new Recovered patients of yesterday / Total new recovered patients of today
This option also should be added to dropdown

**Comment by jeremyphilemon** [comment]
You can see that we do display negative deltas under dailys, but I don't see why adding percentages would be a problem! 

Based on the formula you've provided, it seems to be the case that the percentages can allow better understanding of the rise/fall of the slopes besides the numerical delta – and ofc visually the graph itself.

<img width="502" alt="Screen Shot 2020-04-02 at 5 23 02 AM" src="https://user-images.githubusercontent.com/17938322/78204377-0e337a00-74a2-11ea-837f-1389290814e9.png">

I think the percentages can be added but it'd be better if done inside the graph itself, but I'd like suggestions on where we should place them!

**Comment by sandeephegde16** [comment]
@jeremyphylemon We cab create a drop down for different graphs and allow user to select type of graph needed. In this case, daily growth factor would be a separate graph since the values generally revolves around 1 as x axis. 
In this case, we would have 3 drop down options, Cumulative/Total, Daily, Growth factor.

**Comment by sandeephegde16** [comment]
It would also be better to add no of people tested vs no of active or recovered or deceased cases. That gives better insight on  need of rigorous testing too.

**Comment by architchandra** [comment]
It would be great if daily change _percentage_ can be added (or ratios as the OP mentioned). The number can be added right next to the _absolute_ daily change number when hovering on a daily sample (right next to `-36` in the screenshot above but in parentheses perhaps).

This number can give a more direct understanding of whether a "flattening" of the curve is actually being achieved or not.

**Comment by jeremyphilemon** [comment]
Closed in favor of #1496
