### ISSUE TITLE
Different Result for Desktop and Mobile at the same time

### ISSUE THREAD

**Issue by iindranil** [covid19india/covid19india.github.io#467]
Hi Developers,

I've noticed that the result is showing different for desktop and mobile at the same time. I am using the chrome web browser for desktop and mobile. 

If you guys save data in a single database then why the result is showing differently for desktop and mobile at the same time.

NOTE: Browsing location also the same for both.

Thank you,
Indranil

**Comment by Nitin96Bisht** [comment]
@iindranil Can you please give a detailed explanation along with a screenshot and result that you are referring too.

**Comment by jeremyphilemon** [comment]
This doesn't seem right, could you try again and let us know? And by "result", what type of data are you referring to?
