### ISSUE TITLE
Need some more space for district names

### ISSUE THREAD

**Issue by jkandasa** [covid19india/covid19india.github.io#469]
**Describe the bug**
We do not have enough room for district names. Need to increase cell width bit more

**To Reproduce**
Expand any of state to show district details

**Screenshots**
![image](https://user-images.githubusercontent.com/1004403/78153156-69407f00-7458-11ea-87fc-b1bc8f731275.png)
**Desktop (please complete the following information):**

- OS: fedora 31
- Browser:  chrome
- Version: 79.0.3945.130

**Comment by jeremyphilemon** [comment]
Hey thanks for working on this fix! 

So I've tested it on a mobile screen width and it seems to be working great!
However, on desktops it tends to resize the tables. Could you possibly have that fixed too?

![Kapture 2020-04-02 at 5 12 43](https://user-images.githubusercontent.com/17938322/78203874-ca8c4080-74a0-11ea-9c2f-33ede8b542a4.gif)
