### ISSUE TITLE
Ramanathapuram Map was incorrect . 

### ISSUE THREAD

**Issue by shyam2794** [covid19india/covid19india.github.io#472]
##### Bug 

When hovered over rameshwaram - virudhunagar was getting highlighted as well .  Have raised a fix for the same - [ PR ](https://github.com/covid19india/covid19india-react/pull/470) .

**To Reproduce**

1. Go to https://www.covid19india.org/ 
2. Click on TamilNadu State to get the view of district maps
3. Hover over rameshwaram - virudhunagar gets highlighted . 

**Expected behavior**

When hovered over rameshwaram - ramanathapuram needs to be highlighted . 

**Screenshots**

Current :- 

<img width="321" alt="Screenshot 2020-04-01 at 8 28 42 PM" src="https://user-images.githubusercontent.com/30238125/78155065-9f7efe00-745a-11ea-9148-27c3d485d310.png">

Fix : -

<img width="328" alt="Screenshot 2020-04-01 at 8 31 39 PM" src="https://user-images.githubusercontent.com/30238125/78155086-a574df00-745a-11ea-85dc-deb622d43002.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by guneetnarula** [comment]
This is related to #413 but will take sometime, latest Tamil Nadu district boundaries are still being worked on
