### ISSUE TITLE
Logo on "title bar"

### ISSUE THREAD

**Issue by AYUSHMAN-PANDA** [covid19india/covid19india.github.io#473]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. 
**The logo seems too tiny when opened in desktop site,though its not so clear in phone either**

**Describe the solution you'd like**
The same logo can be enlarged (and/or) made colourful

**Comment by jeremyphilemon** [comment]
Closing this because the logo was meant to be small.
