### ISSUE TITLE
Covid19 Map Data for Tumkur, Karnataka

### ISSUE THREAD

**Issue by saipradeep1** [covid19india/covid19india.github.io#475]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by saipradeep1** [comment]
data needed

**Comment by guneetnarula** [comment]
Tumakuru district is showing 2 cases right now. What's the issue exactly?

**Comment by jeremyphilemon** [comment]
Closing this because Tumakuru district is visible on the website now!
