### ISSUE TITLE
Unpleasant colors when hovered over GitHub button

### ISSUE THREAD

**Issue by pinnamanivenkat** [covid19india/covid19india.github.io#476]
**Describe the bug**
When the "OPEN SOURCED ON GITHUB" is hovered, #8ffe09 is showing a gloss effect. 

**To Reproduce**

1. Go to the footer section.
2. Hover on the Github button
3. Look at the gloss.

**Expected behavior**
Since the $light is being used for the background, it's better to invert the colors.
![expected](https://user-images.githubusercontent.com/18073292/78163147-95163180-7465-11ea-9a43-ea40849161c9.PNG)

**Screenshots**
Current Behaviour
![present](https://user-images.githubusercontent.com/18073292/78163116-892a6f80-7465-11ea-9df4-985a07c31b5e.PNG)

**Desktop (please complete the following information):**

- OS: Windows
- Browser: Chrome
- Version: Version 80.0.3987.149 (Official Build) (64-bit)

**Comment by Nitin96Bisht** [comment]
@shuklaayush @jeremyphilemon @JunaidBabu @sudevschiz Kindly check and let me know if we can work on it. If yes then assign it to me, please.

**Comment by jeremyphilemon** [comment]
Patched it since it was a minor code change, thanks @Nitin96Bisht and @pinnamanivenkat!
