### ISSUE TITLE
Months map does not have key '05' and value 'Dec'

### ISSUE THREAD

**Issue by burnout-projects** [covid19india/covid19india.github.io#477]
**Describe the bug**
In src/utils/common-functions.js, the months var doesn't have key '05' and val 'Dec'. I don't know if this intentional. If so, please ignore this bug. Thanks.

**To Reproduce**

Open file src/utils/common-functions.js

**Expected behavior**
```
const months = {
  '01': 'Jan',
  '02': 'Feb',
  '03': 'Mar',
  '04': 'Apr',
  '05': 'May',
  '06': 'Jun',
  '07': 'Jul',
  '08': 'Aug',
  '09': 'Sept',
  '10': 'Oct',
  '11': 'Nov',
  '12': 'Dec',
};
```

**Comment by jeremyphilemon** [comment]
Haha my bad, fixed it! Thanks for reporting :)
