### ISSUE TITLE
Map can show total cases in the form of markers

### ISSUE THREAD

**Issue by steffyjohn** [covid19india/covid19india.github.io#48]
On page loading, the map can show the total cases  per state in the form of markers/circles and on hover you can show its details.

**Comment by jeremyphilemon** [comment]
You mean showing the numbers on the states?

**Comment by steffyjohn** [comment]
@jeremyphilemon  Yes showing number in the form of circle markers

**Comment by sudevschiz** [comment]
We will stick to choropleth. Closing.

Thanks for the comment @steffyjohn
