### ISSUE TITLE
Chatbot can be integrated

### ISSUE THREAD

**Issue by Bhumika0201** [covid19india/covid19india.github.io#480]
Hi I want to contribute,I have made a chatbot which could be useful.Any suggestions are welcomed.Please see the screenshots attached
![Screenshot (31)](https://user-images.githubusercontent.com/40764170/78165243-a90f6280-7468-11ea-94b9-3c9d1879052e.png)
![Screenshot (32)](https://user-images.githubusercontent.com/40764170/78165249-ab71bc80-7468-11ea-83ee-394021518c31.png)
![Screenshot (33)](https://user-images.githubusercontent.com/40764170/78165252-ac0a5300-7468-11ea-90ee-12b536193539.png)
![Screenshot (30)](https://user-images.githubusercontent.com/40764170/78165254-aca2e980-7468-11ea-9ce5-9d0635183630.png)

**Comment by nikitha90** [comment]
very innovative idea. Can we integrate this chatbot with most commonly used social media applications like facebook messenger and whatsapp?

**Comment by Bhumika0201** [comment]
Thank you .It can be integrated with react applications

**Comment by ParthGoyal1508** [comment]
@bhumika0201 could you please clarify what's the use of chatbot here? Who will resolve those queries and what will be general queries ?

**Comment by nikitha90** [comment]
My idea is that this could be more of an automated bot which will answer queries based on menu interactions. More like how facebook provides in its messenger apps. we can provide buttons like (view states/UT), on clicking the button, the state list should be displayed. On clicking each state, the current details can be displayed. And we can add helpline numbers and safety measures as part of this menu. Another option could be to train the bot such that it returns value when the state name is given?

Just a thought :)

**Comment by jeremyphilemon** [comment]
@sudevschiz @JunaidBabu thoughts?

**Comment by aashish-chaubey** [comment]
Yes, I think this should be integrated, as it will help people to

A. Reach out to the authorities with very specific contact details (I can help train the chatbot)
B. Find any data in specific the user is looking for instead of having to through the drill through

Please let me know if I could be of any help here!

**Comment by bee-rickey** [comment]
Overkill IMO. Not sure how good they will work on mobile screens as 95% of the traffic we have is from mobiles.

**Comment by shuklaayush** [comment]
Closed due to inactivity
