### ISSUE TITLE
Cluster map is not working

### ISSUE THREAD

**Issue by ankitkatiyar91** [covid19india/covid19india.github.io#481]
**Describe the bug**
Cluster map is not loading

**To Reproduce**
Open the cluster page

**Expected behavior**
Cluster mapo should be loaded

**Desktop (please complete the following information):**

- OS: Mac
- Browser Chrome, Firefox

**Smartphone (please complete the following information):**

- Device: Oneplus 6
- OS: Android
- Browser Chrome

**Additional context**
Error on console 
```
error Error: Object argument required.
    at m (index.js:1)
    at p (index.js:1)
    at index.js:1
    at Array.forEach (<anonymous>)
    at or (index.js:1)
    at index.js:1
```

**Comment by sandeephegde16** [comment]
Cluster map tends to get slow in windows + chrome too. Clicking on P2P map, searching couple of patient codes and again navigating to States/ Travel cluster map makes application very slow and hangs many times. Might be data load!?

**Comment by jeremyphilemon** [comment]
Hey thanks for filing an issue!

Please file issues on clusters at https://github.com/someshkar/covid19india-cluster repo since the people working on the development will be able to track and address it!
