### ISSUE TITLE
Customize graphs to view content

### ISSUE THREAD

**Issue by nikitha90** [covid19india/covid19india.github.io#482]
Currently we are able to view only the graphs that shows the entire data from the beginning till date. This can be customized with two options:
* hour range  which shows the data for last 30 minutes, last 6 hours, last 24 hours (idea could be a drop down with any hour range as values)
* date and month range (last one week, one month) can be provided with a calendar button for the user to select the from date and  to date and view data.

* Yesterdays and today's comparison of data graph is really helpful.

**Comment by jeremyphilemon** [comment]
Hey thanks for filing this!

We've already had a feature request about this and was discussed here. #317 

Closing this so that further discussion about this can be directed there instead! It'd also be great if you could add your comment above there too!
