### ISSUE TITLE
Clusters map of state and P2P not working

### ISSUE THREAD

**Issue by Starksid007** [covid19india/covid19india.github.io#483]
When we click on the clusters page it take alot of time to load the page . And the clusters map doesn't work and get freezed , and after that site doesn't work.

The cluster page should be load faster and should not get freezed after opening.

- Device: Realme 3 pro
- OS: Android 10
- Browser : Chrome

**Comment by sandeephegde16** [comment]
Duplicate of #481
 https://github.com/covid19india/covid19india-react/issues/481#issue-592069563

**Comment by jeremyphilemon** [comment]
Closed cause duplicate. Please find your answer at #481
