### ISSUE TITLE
Covid-19 Tracker Plugin

### ISSUE THREAD

**Issue by sandeephegde16** [covid19india/covid19india.github.io#484]
Its good to develop and provide a plugin to integrate COVID-19 Tracker to any other websites to directly display the data concisely borrowing from our data source.

This can be integrated to major news websites, Google search page and many other android and ios apps. Currently, (As i have seen) some android apps (Confirmtkt for instance) display data from [worldometer ](https://www.worldometers.info/coronavirus/country/india/) which shows quite old data and not as updated/ advanced as covid19india.

**Comment by jeremyphilemon** [comment]
Hey, it'd be cool if you could give us examples of websites using a plugin like this?

**Comment by shuklaayush** [comment]
Closed due to inactivity
