### ISSUE TITLE
Github footer links should open in new tab

### ISSUE THREAD

**Issue by ghost** [covid19india/covid19india.github.io#487]
**Describe the bug**
Github footer links when clicked opens in same tab. Rest footer links opens in new tab.

**To Reproduce**

1. Go to https://www.covid19india.org
2. Scroll down to Footer
3. Click on 'Open Sourced on Github'
4. Notice the link is opening in same tab

**Expected behavior**
The link should open in new tab

**Comment by ghost** [comment]
Just noticed. COVID19INDIA link in footer has also same behaviour. The link should open in new tab.

**Comment by Nitin96Bisht** [comment]
@vimalkaul I have created PR for the same. It needs to be reviewed and merged.

**Comment by ghost** [comment]
Thanks @Nitin96Bisht checked here - 
https://covid19india-r-git-fork-nitin96bisht-fix-open-github-lin-009a57.covid19india.now.sh

It's working fine.

**Comment by jeremyphilemon** [comment]
Haha nice find! Thanks for filing the issue :)
