### ISSUE TITLE
we can add symbols corresponding to  instructions along with present instructions in banner section.

### ISSUE THREAD

**Issue by Rahul-skush** [covid19india/covid19india.github.io#490]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jeremyphilemon** [comment]
Not sure what you mean. Please have the issue template filled so that it can help us understand the problem. Feel free to open the issue again describing the problem clearly :)
