### ISSUE TITLE
Compiled from State Gov. Numbers text on clicking compiled link redirects to FAQ

### ISSUE THREAD

**Issue by nikitha90** [covid19india/covid19india.github.io#493]
**Describe the bug**
The text "COMPILED FROM STATE GOVT. NUMBERS" contain a link for the text "compiled". It is redirecting to FAQ page. Is this intented? Is compiled alone meant to be hyperlinked?

**To Reproduce**
click on compiled text in "COMPILED FROM STATE GOVT. NUMBERS" phrase
it redirects to FAQ page. also compiled alone is Hyperlinked.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows
- Browser : Chrome
- Version: 80.0.3987.162

**Smartphone (please complete the following information):**

**Additional context**
![image](https://user-images.githubusercontent.com/25319527/78178903-fa761c80-747d-11ea-95b1-c75b534f5f37.png)

**Comment by Nitin96Bisht** [comment]
@jeremyphilemon @JunaidBabu @sudevschiz Indeed it redirects to the FAQ page. What are your views on it? Does it require any other functionality?

**Comment by jeremyphilemon** [comment]
Yes this was intentional, I had to decide on underlining a "call to action" word hence the decision to underline "compiled". We later patched it to use "Know more" since it's more apt! 

Thanks for filing the issue :)
