### ISSUE TITLE
New map with location of Confirmed cases

### ISSUE THREAD

**Issue by Nikhiljoseph31** [covid19india/covid19india.github.io#496]
A GIS map integration with location of Confirmed cases, I believe  this information is already available as public layer in ESRI.

**Comment by jeremyphilemon** [comment]
I believe this information is already available on the website? 🤔 

If you're talking about integrating the [lat,lng] of confirmed cases, that would be out of scope of the project + the privacy issues that can stem out of it. 

Thanks for reaching out!
