### ISSUE TITLE
Cluster animation slowing down the browser. It also takes much time.

### ISSUE THREAD

**Issue by subratappt** [covid19india/covid19india.github.io#497]
OS: Windows 10 
    Browser: Firefox

**Cluster animation becomes useless now. It takes too much time to load and animate. It also slows the browser down. Switching between the tabs sometimes does not work.**

 It will be very good if you improve it.

**Comment by Nitin96Bisht** [comment]
@jeremyphilemon @JunaidBabu @sudevschiz Kindly check it. It is indeed getting very slow.

**Comment by jeremyphilemon** [comment]
Thanks for reporting!

Please file issues about the cluster at https://github.com/someshkar/covid19india-cluster
