### ISSUE TITLE
API response is wrong  

### ISSUE THREAD

**Issue by RahulRanjan7201** [covid19india/covid19india.github.io#500]
Hi 
 API can be consumed by other application ,as you all already mentioned. 
1. https://api.covid19india.org/data.json - Gives Wrong Data It shows only till 31st

**Comment by jeremyphilemon** [comment]
Please file issues relating to the API here https://github.com/covid19india/api/issues

About the data, the timeseries graphs are filled only till T-minus one day, hence if today is April 2, the data for timeseries is only available till April 1 since the day is not over yet.
