### ISSUE TITLE
Map color not as per count in Goa

### ISSUE THREAD

**Issue by shivendersingh** [covid19india/covid19india.github.io#504]
**Describe the bug**
Color of North Goa map is not as per the map color chart. 

**To Reproduce**

1. Go to https://www.covid19india.org/
2. Click on Goa map
3. See error : As per the map color chart with the count of 3, the color of North Goa map is showing red.

**Expected behavior**
As per the map color chart with the count of 3, the color should be orange.

**Screenshots**
![GoaCovid](https://user-images.githubusercontent.com/24454507/78190533-cdcc0000-7491-11ea-8e12-aeeff7daf5b1.jpeg)

**Desktop (please complete the following information):**

- OS : Windows 10
- Browser : Chrome
- Version : 80.0

**Smartphone (please complete the following information):**
NA

**Comment by chamow97** [comment]
This is reproducible for States having very less confirmed total cases. Odisha, Assam, Mizoram,  Uttarakhand, Himachal Pradesh, Mizoram, Manipur, Bihar, Chhattisgarh, Jharkhand  to name a few. Can I work on this issue?

**Comment by guneetnarula** [comment]
This seems like an issue of the continuous scale algo we are using for the choropleths in D3. Right?

**Comment by chamow97** [comment]
Yes, if we have a mapping of the scale and map's color then it will be easier to solve. I think its happening even for the India Map. Kerala's color is deeper than expected for example.

**Comment by AkhileshK8y** [comment]
@guneetnarula Yes, I tried to solve this issue last night... 
For color bar the code written is
`const color = d3
      .scaleSequential(d3.interpolateReds)
      .domain([0, statistic.maxConfirmed / maxInterpolation || 10]);`
This code does discreet interpolation of red in.

For coloring the region the code is
`const n = parseInt(mapData[d.properties[propertyField]]) || 0;
          
          const color =
            n === 0
              ? '#ffffff'
              : d3.interpolateReds(
                  (maxInterpolation * n) / (statistic.maxConfirmed || 0.001)
                );

          return color;`
Takes number of cases into account before assigning color.

As pointed out by @chamow97 Screen shot is attached.

<img width="1121" alt="Screenshot 2020-04-02 at 12 31 44 PM" src="https://user-images.githubusercontent.com/15231116/78219849-01347c00-74de-11ea-890f-57e5c9807eb6.png">

**Comment by shuklaayush** [comment]
I think the discussion in #57 is relevant. Just making the colouring discrete might not solve the issue. We would also need to adjust the number of discrete intervals for each state.

**Comment by jeremyphilemon** [comment]
@shuklaayush so is this still open?

**Comment by shuklaayush** [comment]
@jeremyphilemon Wait for the next PR :wink:

**Comment by shuklaayush** [comment]
Fixed in #1133
