### ISSUE TITLE
Number of people tested daily.

### ISSUE THREAD

**Issue by Himanshu54** [covid19india/covid19india.github.io#509]
Number of cases is corelated to number of people tested. Number of tests done are already questionable.

Get number of tests done daily data and plot it against active cases discovered.
This helps to understand importance of testing in fight against covid19

**Comment by pranay-jain** [comment]
ICMR has started releasing daily updates on testing stats for [April 3](https://icmr.nic.in/sites/default/files/whats_new/ICMR_testing_update_03April_9PM_IST.pdf) and [April 4](https://icmr.nic.in/sites/default/files/whats_new/ICMR_testing_update_04April_9PM_IST.pdf) (links attached). Unfortunately, they are pdf's. If these updates are shared daily, we could perhaps copy over the data points manually?

**Comment by Himanshu54** [comment]
Those links don't work anymore for me.
There is also state wise testing stats being published by some states. We can scrape that data state wise.

**Comment by shuklaayush** [comment]
Added via #699
