### ISSUE TITLE
Change District Name in Google Sheet.

### ISSUE THREAD

**Issue by sarankumar-ns** [covid19india/covid19india.github.io#510]
District Number 568: Thoothukkudi to Thoothukudi. 
I thought this may affect map update problem.

**Comment by guneetnarula** [comment]
This is related to #413

**Comment by sarankumar-ns** [comment]
The name mentioned at https://github.com/covid19india/covid19india-react/blob/2a658276b6fc74a44657d9f01b4f14316b6833b3/public/maps/tamil-nadu.json?short_path=dc72922#L1643 is correct one(**Thoothukudi**).

So It's need to change in Google Sheets(It's named as **Thoothukkudi**).

Src: https://en.wikipedia.org/wiki/Thoothukudi_district
https://thoothukudi.nic.in/

**Comment by guneetnarula** [comment]
Thanks. Yeah there are different spellings in different sources. We'll stuck to Thoothukkudi, the data will match the JSON in the coming release
