### ISSUE TITLE
Forecast of future growth

### ISSUE THREAD

**Issue by GaneshKandu** [covid19india/covid19india.github.io#511]
**Is your feature request related to a problem? Please describe.**
Forecast of future growth

**Describe the solution you'd like**

[Exponential growth](http://ccnmtl.columbia.edu/projects/biology/lecture1/expogrow.html)

[Forecasting of Population: 9 Methods | Water Quantity | Water Engineering](http://www.engineeringenotes.com/water-engineering-2/water-quantity/forecasting-of-population-9-methods-water-quantity-water-engineering/16158
)

**Comment by sudevschiz** [comment]
Could be a candidate for Deep-Dive.

**Comment by jeremyphilemon** [comment]
Hey thanks for filing the issue, unfortunately we're gonna have to mark this as abandoned since the feature addition in question is either out of scope or that we simply don't have enough data to support said feature. 

Feel free to open an issue in the future if you think otherwise :)
