### ISSUE TITLE
Minor text update needed on text above the political map of India

### ISSUE THREAD

**Issue by keerthigaragu** [covid19india/covid19india.github.io#517]
Describe the bug
Above the map, the text below `INDIA MAP` says only about state and not about UTs.

Go to home page, see the political map of India.
Above the map, the text says only about state and not about UTs.

Expected behavior
Should say "HOVER OVER A STATE/UT FOR MORE DETAILS"

Screenshots
<img width="540" alt="Screen Shot 2020-04-02 at 11 59 17 AM" src="https://user-images.githubusercontent.com/19683558/78217330-73ef2880-74d9-11ea-8253-54805b0fbb5f.png">

Desktop (please complete the following information):
OS: macOS 10.12.6
Browser: Chrome

**Comment by keerthigaragu** [comment]
I can work on it if it's okay for you guys.

**Comment by KrishnaPravin** [comment]
fixed, works as expected
