### ISSUE TITLE
Last updated shows two different values...

### ISSUE THREAD

**Issue by mananthprabhu** [covid19india/covid19india.github.io#518]
Last updated shows different values over the tab vs map. Looks like an inconsistency.

![image](https://user-images.githubusercontent.com/220212/78218393-56bb5980-74db-11ea-8bab-707e713f33ac.png)

**Comment by shuklaayush** [comment]
@mananthprabhu Hey! The right one is the last updated time for the current state (Maharashtra in this case), while the left one is the overall last updated time. Closing
