### ISSUE TITLE
Helpful links open on same tab

### ISSUE THREAD

**Issue by Nitin96Bisht** [covid19india/covid19india.github.io#519]
**Describe the bug**
All helpful links open on the same tab.

**To Reproduce**

1. Go to Helpful Links
2. Click on any of the links.
3. See issue

**Expected behavior**
All links should open in a new tab.

**Desktop (please complete the following information):**

All desktop

**Smartphone (please complete the following information):**

All smartphone

**Comment by Nitin96Bisht** [comment]
@jeremyphilemon Kindly review it.

**Comment by ghost** [comment]
is this issue still open to work on ?

**Comment by hemantpandey17** [comment]
> is this issue still open to work on ?

I think it is already fixed

**Comment by ghost** [comment]
i'd like to contribute, but the telegram link isn't working. Any help would be appreciated!
