### ISSUE TITLE
Cluster tab hits data API twice | Performance Improvement

### ISSUE THREAD

**Issue by jrishabh81** [covid19india/covid19india.github.io#524]
<img width="960" alt="CovidIssue" src="https://user-images.githubusercontent.com/13431633/78223714-f7fadd80-74e4-11ea-91aa-0b3aac154911.PNG">

**Comment by dsouzadyn** [comment]
Hi, can you post the headers of both the requests.

**Comment by jrishabh81** [comment]
@dsouzadyn  Check this out.
<img width="960" alt="Header1" src="https://user-images.githubusercontent.com/13431633/78228097-eb2db800-74eb-11ea-8458-edd7a226beca.PNG">

**Comment by jrishabh81** [comment]
@dsouzadyn  The header of other request is exactly the same.

**Comment by dsouzadyn** [comment]
It seems to be happening of `useEffect()`. Apparently this function is called on each re-render of component. It's not that big of an issue. but fixing it will be a good performance improvement. I'll see what I can do. Till then we can wait for this issue to be reviewed by a mod.

**Comment by dsouzadyn** [comment]
Actually @jrishabh81 you may wan't to report the issue [here](https://github.com/someshkar/covid19india-cluster). Since this project just uses an iframe which points to this site

**Comment by KrishnaPravin** [comment]
cluster tab is no longer shown
