### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by Richu98** [covid19india/covid19india.github.io#525]
**Describe the bug**
Website down due to build error

**To Reproduce**

1. Go to https://www.covid19india.org/

**Expected behavior**
Web Page 

**Screenshots**
https://drive.google.com/file/d/1FLkTBt4L2YRiXDAE28oVd5Nqde_ukZ4s/view?usp=sharing

**Desktop (please complete the following information):**

- OS: Windows
- Browser Chrome

**Additional context**

**Comment by Richu98** [comment]
Its working fine now

**Comment by jeremyphilemon** [comment]
:)
