### ISSUE TITLE
Rajasthan & Telangana - Wrong last updated

### ISSUE THREAD

**Issue by sandeephegde16** [covid19india/covid19india.github.io#526]
Rajasthan has last updated as 19 hours ago which clearly seems wrong considering we have 9 fresh cases today morning itself.

Whereas Telangana was not updated from yesterday but its showing as 3 hours ago.

![image](https://user-images.githubusercontent.com/35073693/78224975-0ba74380-74e7-11ea-9db7-c8731d5a8602.png)

![image](https://user-images.githubusercontent.com/35073693/78224900-f29e9280-74e6-11ea-9e04-1ebd527019fd.png)

**Comment by sandeephegde16** [comment]
Madhya Pradesh, Gujarath and Assam too have same issue.

**Comment by jeremyphilemon** [comment]
This had to do with the data team, I'm sure this is fixed by now, but feel free to re open this it if you catch it happen again, thanks!
