### ISSUE TITLE
Old District Data [Tripura]

### ISSUE THREAD

**Issue by Baibhab97** [covid19india/covid19india.github.io#527]
**Describe the bug**
The district data of Tripura is old.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to Home Page
2. Click on Tripura in the Map
3. Four districts will show up only, whereas there are 8 districts

**Expected behaviour**
8 districts are there in Tripura. Instead of 4, those 8 districts should be shown.
The name of the 8 districts are: 
1. Dhalai 
2. Gomati  
3. Khowai 
4. North Tripura 
5. Sipahijala  
6. South Tripura 
7. Unokoti
8. West Tripura
These are mentioned in the COVID19-India: Patient Database Google Sheet.
(https://bit.ly/patientdb)

**Screenshots**
![Screenshot from 2020-04-02 13-42-31](https://user-images.githubusercontent.com/20902312/78225490-f1ba3080-74e7-11ea-8bc5-c69c80e7e2a8.png)

**Desktop (please complete the following information):**

All Versions

**Smartphone (please complete the following information):**

All Versions

**Additional context**

**Comment by guneetnarula** [comment]
This will be fixed by the remaining JSONs in #413

**Comment by jeremyphilemon** [comment]
Closing cause #413 addresses this.
