### ISSUE TITLE
Interactive timeline

### ISSUE THREAD

**Issue by salmandaw** [covid19india/covid19india.github.io#528]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
A date wise timeline that shows the map as per date clicked on would be a nice way to show how the virus is progressing. we could probably make the node of each date in the daily cases graph as the link which would show the date dashboard as per that date.

**Describe alternatives you've considered**
We could alternatively have automated snapshots at the end of day and provide a gallery view in the meanwhile

**Additional context**

**Comment by sudevschiz** [comment]
Could be a candidate for Deep-Dive.

**Comment by jeremyphilemon** [comment]
Closing in favor of #135
