### ISSUE TITLE
State wise daily recovered and deceased cases

### ISSUE THREAD

**Issue by shoyebinamdar** [covid19india/covid19india.github.io#529]
**Is your feature request related to a problem? Please describe.**
State wise daily recovered and deceased cases
**Describe the solution you'd like**
Like we show daily increased cases for each state, we can also show newly recovered and deceased cases.

**Comment by shuklaayush** [comment]
Hi @shoyebinamdar, the relevant code is there but the API is currently not publishing this information. Refer to https://github.com/covid19india/covid19india-react/issues/317#issuecomment-605617519.

Closing.
