### ISSUE TITLE
Map data discrepancies

### ISSUE THREAD

**Issue by tannakartikey** [covid19india/covid19india.github.io#530]
From my tests in #355 I have found out the following discrepancies in the districts' data:

**Describe the bug**
1) **Arunachal Pradesh**
The API response has the state name as `Arunachal Pradesh`
In the `public/maps/arunachalpradesh.json` it is spelled wrongly as `Arunanchal Pradesh`

2) **Andaman and Nicobar Islands**
The API response has the state name as: `Andaman and Nicobar Islands`
In the `public/maps/andamannicobarislands.json.json` it's `Andaman & Nicobar Island`

3) **Chandigarh**
The state is there in API response but the map file does not exist. Nor it is listed in `mapsexplorer.js`
 
4) **Puducherry**
The state is there in API response but the map file does not exist. Nor it is listed in `mapsexplorer.js`

5) **Chengalpattu** (A district of Tamilnadu)
This district is there in the API response but could not find under `public/maps/tamil-nadu.json`

6) **Bhadradri Kothagudem** (A district from Telangana)
This district is there in the API response but could not find under `public/maps/tamil-nadu.json`

**Comment by tannakartikey** [comment]
I am not sure how we are gathering map data at the moment.
Just mentioning a few resources I found in case it helps:
https://github.com/HindustanTimesLabs/shapefiles/tree/master/india
https://github.com/deldersveld/topojson/tree/master/countries/india

**Comment by khaaba** [comment]
> I am not sure how we are gathering map data at the moment.
> Just mentioning a few resources I found in case it helps:
> https://github.com/HindustanTimesLabs/shapefiles/tree/master/india
> https://github.com/deldersveld/topojson/tree/master/countries/india
@tannakartikey Maps in the above links provided by you are old ones. Total number of Districts in the country at present 729 as per latest data updated in 2018/2019.

**Comment by KrishnaPravin** [comment]
@JunaidBabu @sudevschiz @jeremyphilemon
I would like to work on this.

**Comment by guneetnarula** [comment]
@tannakartikey @KrishnaPravin we are working on these. See #413 the source for the latest district data is the Datameet community. I am currently working on the topojsons and hosting them in this repo https://github.com/guneetnarula/indian-district-boundaries/tree/master/topojson

**Comment by KrishnaPravin** [comment]
@guneetnarula got it👍

**Comment by limshark** [comment]
datiya district in Madhya pradesh, the map of Datiya shows extra villages geographically seperated. these are not correct. 


![image](https://user-images.githubusercontent.com/7282526/78517026-51128c00-77d9-11ea-874f-5ea321ee6434.png)

**Comment by guneetnarula** [comment]
Hi @limshark I checked the official SoI / NIC service at bharatmaps.gov.in, the block Datia in this district has panchayats that geographical separated from the main Datia district.
