### ISSUE TITLE
Image of the website when the link is shared on Facebook

### ISSUE THREAD

**Issue by tannakartikey** [covid19india/covid19india.github.io#534]
**Is your feature request related to a problem? Please describe.**
If the link of the website is shared on Social Media the image is not displayed. Refer the attached screenshot.
![image](https://user-images.githubusercontent.com/422544/78239393-474c0880-74fb-11ea-9bb9-32eebb842bbe.png)

**Describe the solution you'd like**
As per Facebook's documentation the `og:image` meta tag has to be included. The meta tag is already there but the image is path is not correct.
https://developers.facebook.com/docs/sharing/webmasters/images/

**Comment by UJPrasad** [comment]
@tannakartikey Is it okay I work on this? I would add a current screenshot of the website in resources

**Comment by tannakartikey** [comment]
By all means, go ahead!

**Comment by JunaidBabu** [comment]
#605
