### ISSUE TITLE
Add Number of Recovered Cases And Death Cases

### ISSUE THREAD

**Issue by codeslane** [covid19india/covid19india.github.io#535]
Please add daily number of death cases row and number of Recovered cases row individually state wise when someone click state.

![Screenshot_20200402-161950_Chrome](https://user-images.githubusercontent.com/26877201/78241553-3355d600-74fe-11ea-8343-ef0ee6c07631.jpg)

**Comment by shuklaayush** [comment]
Hi @codeslane, the relevant code is there but the API is currently not publishing this information. Refer to https://github.com/covid19india/covid19india-react/issues/317#issuecomment-605617519.

Closing.
