### ISSUE TITLE
Adding changes in Recovered and Deceased columns for state

### ISSUE THREAD

**Issue by prabodhmeshram** [covid19india/covid19india.github.io#536]
**Is your feature request related to a problem? Please describe.**
It is related to UI visualization for changes in data for other columns. There is no delta changes shown in the UI for Recovered or Deceased patients.
<img width="614" alt="Screen Shot 2020-04-02 at 3 06 46 PM" src="https://user-images.githubusercontent.com/6660187/78234925-7f504d00-74f5-11ea-809f-0bbbf8254bfe.png">

The code is commented here 

https://github.com/covid19india/covid19india-react/blob/master/src/components/row.js#L124-L140

**Describe the solution you'd like**
Adding data changes beside recovered and deceased columns for each state. Would be a simple code to write, following the Confirmed column code.

**Describe alternatives you've considered**
Should see as is, nothing to be updated. Very simple change, can't think of alternatives.

**Additional context**
It is good to see changes in other column per day as well, cause that helps to visualize all round situations in states.

**Comment by jeremyphilemon** [comment]
Patched :)
