### ISSUE TITLE
Can you make module for Magic mirror 

### ISSUE THREAD

**Issue by p10dulkar** [covid19india/covid19india.github.io#538]
**Describe the solution you'd like**
Helpful Links 

https://magicmirror.builders/
https://github.com/MichMich/MagicMirror
https://docs.magicmirror.builders/development/introduction.html
Example :https://github.com/bibaldo/MMM-COVID19 
make it specific for india if you have time

**Comment by sudevschiz** [comment]
Whoah. You want these saddening numbers on a mirror? :0

Anyways, opening it up for somebody

**Comment by p10dulkar** [comment]
Well very few news around the world happy to feel about still we read them to stay updated .
However thank you for creating it but can u give me timeline or deadline so that I can follow up on it

**Comment by shuklaayush** [comment]
Closed due to inactivity

**Comment by altamashqureshi9144** [comment]
any live working module for magicmirror or any upcoming?
