### ISSUE TITLE
API Access to patient DB

### ISSUE THREAD

**Issue by Dwijad** [covid19india/covid19india.github.io#541]
Hi
Can i have API access to patient data base like elasticsearch so that any one can do some analysis on patient  data and view them in dashboard like Kibana. 

If you don't have the ES database, i can create one such DB in the cloud for any one to use. You just need to export the data from patient DB in the Google spreadsheets.

Regards

**Comment by viggyprabhu** [comment]
I am also looking for this. Can you please suggest how can I download the google sheets

**Comment by JunaidBabu** [comment]
https://api.covid19india.org/raw_data.json

**Comment by Dwijad** [comment]
I know with a python script the patient data from Google sheets can be read. Just curious about API access to patient DB in case it is available :}

**Comment by Dwijad** [comment]
Data from all the spreadsheets are not available like statewise_tested_numbers_data, case_time_series, district_list, statewise and likes :)

**Comment by aksappy** [comment]
@DwijadasDey  The api repo has the links listed. https://github.com/covid19india/api

**Comment by sudevschiz** [comment]
@DwijadasDey please do create an issue in https://github.com/covid19india/api if you need an API for a specific sheet. We will definitely look into it :)
