### ISSUE TITLE
last updated date in sort table on main page

### ISSUE THREAD

**Issue by test2a** [covid19india/covid19india.github.io#542]
![Untitled 1](https://user-images.githubusercontent.com/39449563/78251302-c565da80-750e-11ea-9f19-67840e0495a3.jpg)

right now, we don't have a glance view of when the last time data was updated. we have to click on state name and then it shows last updated data. having last updated in the table and being able to sort would help us by see if any state data needs attention or whatever

**Comment by sudevschiz** [comment]
I think there is a UX impact when the number of columns on that table is increased. 
This information is available when users taps on the state for district-wise view. I feel that's the right amount of exposure for this information. 

The PR was made before accepting. However, @jeremyphilemon please check if this is required addition.

**Comment by hitesh-tarani** [comment]
Though the last-updated information is available after user clicks on state for state-district view, I feel that having it as an additional column with sorting feature is good-to-have.
I agree that the adding new column in that table messes UX on mobile devices.
Moderators / @jeremyphilemon please review this feature request and provide suggestions for the same.

**Comment by sudevschiz** [comment]
@hitesh-tarani I think adding a new column would not be preferable. The information density is already too high.

Also, we are working on adding more details regarding each state right to the dropdown. So last updated time is more preferable there. Thanks for the ticket.
