### ISSUE TITLE
global tracker should have/include johns hopkins tracker

### ISSUE THREAD

**Issue by test2a** [covid19india/covid19india.github.io#543]
[https://gisanddata.maps.arcgis.com/apps/opsdashboard/index.html#/bda7594740fd40299423467b48e9ecf6](url)
 johns hopkins university data is the most up to date tracker which is updated hourly/half hourly and publications like the guardian and NYT use this tracker in their reporting so i suggest the same be added here so that more people are exposed to this information

**Comment by sudevschiz** [comment]
This is currently not in our scope. We will stick to cases in India. 
However, this can be added to the Helpful Links. 

https://coronavirus.jhu.edu/map.html

I will do that.

**Comment by test2a** [comment]
oh i'm sorry. i didn't  mention where. there is a link in the bottom of the links page. i am asking to have a link to johns hopkins website there

https://www.covid19india.org/links
