### ISSUE TITLE
Add sanity check to only plot spread trend graphs till yesterday

### ISSUE THREAD

**Issue by sudevschiz** [covid19india/covid19india.github.io#544]
**Describe the bug**
The Cases_Time_Series sheet is vulnerable to extra rows of dates being added. This will cause an empty value to be added. Things like below could happen

**To Reproduce**
1. Add an extra date in Cases_Time_Series sheet without any valid Confirmed/Recovered/Deceased values and wait for <9 minutes

**Expected behavior**
Even if empty dates are present, they shouldn't be plotted. Only rows with a valid value should be plotted.

**Screenshots**
![image](https://user-images.githubusercontent.com/4298868/78257017-45526b80-7534-11ea-8fa6-d3c622e2be27.png)

**Additional context**
We had decided earlier to only show spread trend till yesterday so that there are no 0 values at the edge of the graph,

**Comment by vedadeepta** [comment]
willing to work on this, please assign @jeremyphilemon

**Comment by jeremyphilemon** [comment]
@vedadeepta all yours! :)

**Comment by sudevschiz** [comment]
@jeremyphilemon please review :)
