### ISSUE TITLE
Disable Scale Mode Uniform by default.

### ISSUE THREAD

**Issue by avinasshcm** [covid19india/covid19india.github.io#545]
Disable Scale Mode Uniform by default.

This will add more clarity to graph when we see the curve. If it is enables by default, 2nd and 3rd Graphs looks like a straight line.

**Comment by kousiksatish** [comment]
@avinasshcm I also feel the same. In coming days, recovery and death is going to be nowhere close to new cases. It makes sense to have uniform turned off.
@jeremyphilemon @JunaidBabu Please review.

**Comment by sudevschiz** [comment]
I think this is debatable. Ideally, all three curves should be shown on the same graph so that in future we can see recoveries reaching towards the total cases.

Having Uniform scaling on, is closer to that reality. @jeremyphilemon thoughts?

**Comment by avinasshcm** [comment]
With your close to reality recommendation, people cannot see proper variation in the graph. Please see the attached one.

Scale it not the thing which users see, what makes usability better is what is the variation in number compared to yesterday or day before or week before.
 
![Uniform_false](https://user-images.githubusercontent.com/63049624/78332213-33f57780-75a5-11ea-87a5-c3cea6183d27.JPG)
![Uniform_true](https://user-images.githubusercontent.com/63049624/78332220-3526a480-75a5-11ea-9b4f-02505b2b50ac.JPG)

**Comment by kousiksatish** [comment]
Please refer https://www.worldometers.info/coronavirus/country/india/
They have graphs without uniform scaling. 
They have comparison graphs as below which makes more sense for such data. We can also implement that. May be Recovered vs Death in same graph
![Screen Shot 2020-04-03 at 12 57 48 PM](https://user-images.githubusercontent.com/6641694/78335287-f7c51580-75aa-11ea-9fad-061c268a3af8.png)
![Screen Shot 2020-04-03 at 12 57 04 PM](https://user-images.githubusercontent.com/6641694/78335304-fd226000-75aa-11ea-8bae-9b0efe0c1aa8.png)

This is quite simple to implement and more useful for user.

**Comment by avinasshcm** [comment]
Same thing holds good for this graph too.
Recovered and Deceased is flat.

![Stats](https://user-images.githubusercontent.com/63049624/78340393-a8cfae00-75b3-11ea-98ca-f127a469b714.JPG)

**Comment by sudevschiz** [comment]
Once the recovery numbers pick up, won't it be nice to see it peaking :)

**Comment by avinasshcm** [comment]
Fine, if you want to stick to your so called **Close to reality** feature. leave it.

**Comment by avinasshcm** [comment]
If you dont have mindset to understand what graph is, its waste arguing with you.

**Comment by jeremyphilemon** [comment]
@avinasshcm thanks for your feedback, I have to back @sudevschiz decision on this, not just on his intention to have it represent something "close to reality", but to have proper design in showing the graphs in the first place. 

When you first see the graphs without uniform scaling turned on, there is a significant possibility of misinterpreting the graphs that the deaths are in par with the numbers of confirmed cases. Since both the graphs, without having checked what the y-axis are, look alike.

Your idea of "understanding the graph" is falling short behind not understanding that users may not see the Y-axis as non-uniform on first sight. 

Hence, the button. Go ahead and click it for clarity. We wouldn't want to confuse users into thinking that the graphs for death are in scale in with the graphs for confirmed/recovered :)

**Comment by kousiksatish** [comment]
I agree with @jeremyphilemon that there is a chance of misinterpretation.

**Comment by avinasshcm** [comment]
Firstly, thanks for your explanation.
Secondly, soon Worldometer is going to implement statewise patient data, and once it comes in, no body will be damn interested in your page. no matter what improvements you give it on your page.

**Comment by avinasshcm** [comment]
Good Luck guys

**Comment by avinasshcm** [comment]
To tell you about End user experience, no body will give a damn about what number you display in y-axis scale. the only information they expect is compared to yesterday or day before, what is the change today. whether it is more than yesterday or less than yesterday.

**Comment by avinasshcm** [comment]
![Worldometer](https://user-images.githubusercontent.com/63049624/78470248-8c637b00-7745-11ea-869c-305368a41268.JPG)

**Comment by jeremyphilemon** [comment]
@avinasshcm aww :)
