### ISSUE TITLE
More graphs will be helpful.

### ISSUE THREAD

**Issue by vivekuno** [covid19india/covid19india.github.io#55]
Hi @covid19india ,

As we have patient data with state, age, sex, mode of transmission.

Displaying it with graphs (can be simple bar graph) will bring more meaning out Covid-19 patient data base.

Like by Age upon date:-
![image](https://user-images.githubusercontent.com/4516272/77402437-acee1580-6dd4-11ea-9053-32c11e2394a7.png)

Gender count:-
![image](https://user-images.githubusercontent.com/4516272/77402522-ca22e400-6dd4-11ea-88a7-8b0cf233603f.png)

State count:-
![image](https://user-images.githubusercontent.com/4516272/77402612-ef175700-6dd4-11ea-921c-c5f5ba5918e5.png)

Transmission mode.
Here we need classification of mode as Notes columns have freestyle text. It needs to be replaced with fixed types of modes. like:

![image](https://user-images.githubusercontent.com/4516272/77406938-651ebc80-6ddb-11ea-9a96-933ad4b30b24.png)

Of course few of them will require manual entry.

I am working of Excel formula to replace free notes with fixed types of modes.

Thank you,
N Vivek Raj

**Comment by vivekuno** [comment]
Just saw this site https://againstcovid19.com/singapore/dashboard
Exactly the requirement. The template is very similar can you reuse the code ??

**Comment by jeremyphilemon** [comment]
Closed by #539
