### ISSUE TITLE
Ahmadabad showing under maharashtra state

### ISSUE THREAD

**Issue by sachinsangle8652** [covid19india/covid19india.github.io#556]
![Screenshot_2020-04-02-23-22-56-701_com android chrome](https://user-images.githubusercontent.com/63068702/78282312-ae88ad80-7539-11ea-9622-352e2bb3958a.png)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by hitesh-tarani** [comment]
Duplicate of #553.

**Comment by sudevschiz** [comment]
This has been fixed at a data end. Thanks for reporting.
