### ISSUE TITLE
Link to latest update source from each state

### ISSUE THREAD

**Issue by kousiksatish** [covid19india/covid19india.github.io#558]
**Is your feature request related to a problem? Please describe.**
No. It is a new feature which would help people like me who would like to know more about the update. 

**Describe the solution you'd like**
In recent days, we see that each state government is mostly giving one update per day. It would be good if we could the link to the source of this update.

**Comment by kousiksatish** [comment]
https://github.com/covid19india/api/issues/63 - Have raised the same in API repository also.
I would like to work on this feature if accepted. Please assign it to me.

**Comment by sudevschiz** [comment]
Have assigned the change in the API to you.

On the website, you like to know where and how you plan to show these links. If it's on the table, it might be bad UX.

Please discuss.

**Comment by kousiksatish** [comment]
@sudevschiz I was just thinking we could show it as below:
Please let me know if there is any better way

![Screen Shot 2020-04-03 at 12 52 29 PM](https://user-images.githubusercontent.com/6641694/78335434-3b1f8400-75ab-11ea-9928-5a3a758affb8.png)

**Comment by sudevschiz** [comment]
Yes, this has become high priority. Rather than the latest update, we need to make sure that the numbers that we are showing are in line with the state bulletins or press releases.

I think the sources that are mentioned should be those.

**Comment by shuklaayush** [comment]
Sources have been added in the state pages. Closing
