### ISSUE TITLE
Border for every path is a shade of red, does not clearly demarcate

### ISSUE THREAD

**Issue by georgyjacob2020** [covid19india/covid19india.github.io#559]
![Screenshot 2020-04-03 at 12 48 03 AM](https://user-images.githubusercontent.com/63071885/78292586-e5b08c00-7544-11ea-88aa-25c3cc3f85a5.png)
**The Border between states and districts is also a shade of red**
If neighbouring states or districts have almost the same number they look like one blob

**It would be better if the border color is black or a contrast color like green **

**Comment by georgyjacob2020** [comment]
covid19india-react/src/components/choropleth.js
Line 121 will need the necessary change 
        .attr('stroke', '#ff073a20')

I can make the changes, I might be a little slow to get of the blocks and test etc etc..

**Comment by sudevschiz** [comment]
@georgyjacob2020 Please try to make the change. Personally, I think a lighter color like white might be better to demarcate the boundaries rather than black.
But it's up to yours and @jeremyphilemon 's imagination

**Comment by Invoker96** [comment]
@sudevschiz  @georgyjacob2020, I have made the required changes. White color was looking way off as our eastern states have light shade and background is also White.

![image](https://user-images.githubusercontent.com/40684561/78332511-d150ab80-75a5-11ea-921d-4c927c4a4be0.png)

**on Hover**
![image](https://user-images.githubusercontent.com/40684561/78332584-f1806a80-75a5-11ea-8a4a-09e193f578b8.png)


Attached the updated change. Should I raise a PR for this?

**Comment by georgyjacob2020** [comment]
@Invoker96 thanks a lot, 
Just curious... 
Can you try light green color too ?

**Comment by Invoker96** [comment]
@georgyjacob2020 
Light green will look like this.
![image](https://user-images.githubusercontent.com/40684561/78334560-96507700-75a9-11ea-96fb-b9098443db1c.png)

Olivedrab looks much better

![image](https://user-images.githubusercontent.com/40684561/78334628-baac5380-75a9-11ea-860e-72e8c3803f6c.png)

**Comment by georgyjacob2020** [comment]
Olivedrab does look good, maybe redure to 1px instead of 2

**Comment by georgyjacob2020** [comment]
Do the districts view also get the borders

**Comment by georgyjacob2020** [comment]
Country States 
![Screenshot 2020-04-03 at 1 00 30 PM](https://user-images.githubusercontent.com/63071885/78335424-365ad000-75ab-11ea-840d-e8a82a232486.png)
Districts
![Screenshot 2020-04-03 at 1 00 42 PM](https://user-images.githubusercontent.com/63071885/78335439-3ce94780-75ab-11ea-95d3-78fd6ab5434f.png)

**Comment by Invoker96** [comment]
Yes, districts also has the same border, reduced the width to 1px
![image](https://user-images.githubusercontent.com/40684561/78335461-48d50980-75ab-11ea-9bf3-5e5e04b7c025.png)

![image](https://user-images.githubusercontent.com/40684561/78335554-7326c700-75ab-11ea-99fa-9c38a859d7bd.png)

Looks good now? Raising a PR

**Comment by Invoker96** [comment]
@georgyjacob2020 @sudevschiz Changes are pushed and available in the https://github.com/covid19india/covid19india-react/pull/573

**Comment by georgyjacob2020** [comment]
Hello @Invoker96, 
when a state or district is highlighted, the highlighted border is dark red in color.
I believe this should also be a dark variant of green. 

src/App.scss
line 790 
.map-hover {
  stroke: #6B8E2FF0;
  stroke-width: 2;
}

will give a good effect

**Comment by georgyjacob2020** [comment]
For Example 

![Screenshot 2020-04-03 at 7 05 55 PM](https://user-images.githubusercontent.com/63071885/78366495-36c08e80-75de-11ea-99c5-7b63b073468e.png)
![Screenshot 2020-04-03 at 7 05 14 PM](https://user-images.githubusercontent.com/63071885/78366515-3c1dd900-75de-11ea-9e59-54dc96a0bb9b.png)

**Comment by Invoker96** [comment]
@georgyjacob2020 Thanks for the input.
Added the fix for the same.

![image](https://user-images.githubusercontent.com/40684561/78367659-109bee00-75e0-11ea-86d3-f45f149edb19.png)
Working fine on hovering on state and districts.

**Comment by georgyjacob2020** [comment]
Hello @sudevschiz @jeremyphilemon.
Is there anything else we ought to do here

**Comment by sudevschiz** [comment]
Assigning @jeremyphilemon for review and comments.

**Comment by jeremyphilemon** [comment]
Hey thanks for opening this issue, just got to read the comments. In my opinion, any light colors for the stroke would only result in a less appealing version the map to the eyes. Green doesn't look that bad, but just replacing the colors isn't solving the problem at hand.

A potential solution I'm looking for is to have the borders colored based on the fill of the shape. Say if the percentage of a state is 0.2, so the fill colors of the state shapes are assigned by redPalette[0.2], which is a lighter shade. Now the opposite of that lighter shade would be redPalette[0.8], just a subtraction from 1, resulting in a darker shade for a lighter fill.

If we use this strategy, we can then consistently maintain the border colors wrt the fill colors. I'm sure this is doable, and if anyone's willing to take this up, I'll try to help you out with it too :)

**Comment by georgyjacob2020** [comment]
[test2.mov.zip](https://github.com/covid19india/covid19india-react/files/4434802/test2.mov.zip)
@jeremyphilemon, 
I tried the option you mentioned above, where we have a darker border for a lighter fill and a lighter border for a darker fill. 
Have a look at the attached movie file, it looks a bit flashy. 

The states which are around 0.4 gets a 0.6 border and the ones on 0.6 gets a 0.4 border which is not much of a contrast. 

Darker filled states almost gets a white border and the ones with single digit numbers gets a very dark border, which is too much of a contrast.

**Comment by jeremyphilemon** [comment]
Mhmm this is interesting,

Can you try something like this and share a video, would really appreciate it!

```
const contrast = 1-(datapoint)/100;
if (contrast>=0.4 && contrast<0.6) return d3.interpolateReds(0.8);
return d3.interpolateReds(contrast);
```

**Comment by georgyjacob2020** [comment]
[4060.mov.zip](https://github.com/covid19india/covid19india-react/files/4436561/4060.mov.zip)

@jeremyphilemon, 
If you hover on Kerala and Telangana, you will see a darker border, these 2 states fall in the 40-60% as of this time when the video was made.
imo users will wonder why these states are getting a dark border.

**Comment by georgyjacob2020** [comment]
Since we have used a single color to represent the range of the numbers (in this case, light red to dark red), To demarcate between these ranges (i.e. borders) if we use the same color in reverse (dark red to light red) will not demarcate well... its better to use a contrast color.

**Comment by georgyjacob2020** [comment]
[extrapolateGreenPropotionately.mov.zip](https://github.com/covid19india/covid19india-react/files/4436668/extrapolateGreenPropotionately.mov.zip)

This video gives the states a proportionately interpolating green border on hover. Its dark green for max numbers like Maharashtra and light green for states with lesser numbers.

**Comment by georgyjacob2020** [comment]
[BetterStillWithAGreenBorder.mov.zip](https://github.com/covid19india/covid19india-react/files/4436757/BetterStillWithAGreenBorder.mov.zip)

A little better version imo, with an already dark olive 1 px border and a proportionately interpolating green border on hover

**Comment by Invoker96** [comment]
@georgyjacob2020 dark olive looks better now. If I get some more contrasting color, will update in the comments.
