### ISSUE TITLE
Tirupattur district is mentioned twice under the list of districts in Tamilnadu

### ISSUE THREAD

**Issue by fibbysib** [covid19india/covid19india.github.io#561]
Tirupattur district is mentioned twice under the list of districts in Tamilnadu
![Screenshot_20200403-024817](https://user-images.githubusercontent.com/63075730/78302087-c838ed80-7557-11ea-8b03-7c1edc926cf1.jpg)

**Comment by sudevschiz** [comment]
Thanks for reporting. For now, I have fixed the Tirupattur and Tirupathur case in the data.
Team is working on fixing the district list to reflect the new districts carved in TN recently.
