### ISSUE TITLE
Screen Freezing problems

### ISSUE THREAD

**Issue by SaiKathika** [covid19india/covid19india.github.io#563]
**Describe the bug**
In the clusters section when I tried to select City or state it was freezing for some time, after that it changes the option but the was still in freeze and I can't able to scroll. This happened on mobile browser.

**To Reproduce**

1. Go to clusters
2. Click on state
3. Scroll down to we can't scroll down or up because at this point the screen freezes.

**Expected behavior**
Enhance the way that works

**Screenshots**

**Smartphone (please complete the following information):**

- Device: Pixel 3a
- OS: Android 10
- Browser chrome
- Version 80.0.3987.162 - browser version

**Additional context**

**Comment by sudevschiz** [comment]
Let me refer you here : https://github.com/someshkar/covid19india-cluster

They are actively working on improving the performance.
