### ISSUE TITLE
State specific Spread Trends when a state is selected

### ISSUE THREAD

**Issue by fadikar** [covid19india/covid19india.github.io#564]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
When a state is selected on the India map, the corresponding spread trend plots of that state can replace the overall trend plots. That will allow us to see trend of individual state, which should be different for different states, providing additional insights.

**Comment by KrishnaPravin** [comment]
@JunaidBabu is it possible to have data for cases_time_series for all states?
I guess currently we don't have.

**Comment by JunaidBabu** [comment]
https://api.covid19india.org/states_daily.json

This is the json of Date_wise_Delta sheet. I think this is what you're looking for. Unfortunately this only contains data from March 30th.

**Comment by KrishnaPravin** [comment]
@JunaidBabu is it possible to extract data by going through the commits of api repo? for older data.

**Comment by JunaidBabu** [comment]
Yes that's the only way to fill up the old data.. would you like to take this up?

@sudevschiz can you support this?

**Comment by KrishnaPravin** [comment]
@JunaidBabu  Yes, I would like to take it.

**Comment by JunaidBabu** [comment]
@KrishnaPravin that would be awesome. Could you send your email ID to [JunBot](https://t.me/junbot). I will add you to the Sheet. You can download a copy of Date_wise_Delta and fill it locally. We'll later review it and add to the master sheet. Sounds good?

**Comment by KrishnaPravin** [comment]
@JunaidBabu Absolutely!

**Comment by ksathyareddy7** [comment]
The current structure of the daily state wise data API is not so well structured. It would be great to have restructured to something like this
```
[
  "assam": {
      "14/03/2020": {
          confirmed: 1,
          active: 1,
          recovered: 0,
          deaths: 0
       },
      "15/03/2020": {
          confirmed: 4,
          active: 4,
          recovered: 0,
          deaths: 0
       }
    },
"andhra pradesh": {
      "14/03/2020": {
          confirmed: 7,
          active: 7,
          recovered: 0,
          deaths: 0
       },
      "15/03/2020": {
          confirmed: 14,
          active: 14,
          recovered: 0,
          deaths: 0
       }
    }
]
```

**Comment by KrishnaPravin** [comment]
@JunaidBabu as we have the date now, can I start working on this feature on the website?

**Comment by Jaisinghpeter** [comment]
can you add my email also for the sheet. Ill also try the same task . and i Dont know that i can complete or not but let me give a try
