### ISSUE TITLE
Add a Refresh Button to refresh the data instead of reloading the page

### ISSUE THREAD

**Issue by ghost** [covid19india/covid19india.github.io#565]
**Is your feature request related to a problem? Please describe.**
As a web user, where pages are kept open in browser & on revisiting them I don't need to reload the complete page to get the latest count. It's not much user friendly.

**Describe the solution you'd like**
A refresh button, on the top or next to _Last Updated_  would suffice as it'll just refresh the counts and updates other states instead of reloading the complete webpage. Much more efficient & React can easily do so.

**Describe alternatives you've considered**
NONE

**Comment by panwarab** [comment]
can I take this up?!

**Comment by hitesh-tarani** [comment]
This can be enhanced to provide feature to auto-refresh at regular intervals, like enable auto-refreshing every 5 minutes.

**Comment by sudevschiz** [comment]
Auto refresh is much better.
This is being worked on here :  https://github.com/covid19india/covid19india-react/issues/300

Closing this ticket.
