### ISSUE TITLE
Active column is showing date and time

### ISSUE THREAD

**Issue by srivenkatesh92** [covid19india/covid19india.github.io#567]
**Describe the bug**

All Active column in UI showing date and time instead of active number count

**To Reproduce**

Just refresh and see the landing page

**Expected behavior**

**Screenshots**
![active issue](https://user-images.githubusercontent.com/26417731/78328315-80888500-759c-11ea-99dd-b0e2e6827b1b.PNG)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Ankit895** [comment]
@jeremyphilemon seems to be a database issue
![Screenshot from 2020-04-03 11-19-32](https://user-images.githubusercontent.com/31807034/78328568-1a503200-759d-11ea-892a-9d45142555d7.png)

**Comment by akshayjadhav9** [comment]
Also Active Cart shows Wrong Count

**Comment by Ankit895** [comment]
> Also Active Cart shows Wrong Count

yes, this seems to be a database issue

**Comment by Ankit895** [comment]
Please close this issue as it's fixed

**Comment by srivenkatesh92** [comment]
Thank you @Ankit895 for quick response
