### ISSUE TITLE
Active number of infected person wrongly binded in latest update

### ISSUE THREAD

**Issue by urveehm** [covid19india/covid19india.github.io#569]
Active number of infected person column wrongly binded in latest updatsd

**Comment by Invoker96** [comment]
Please elaborate more on this.

**Comment by panwarab** [comment]
@urveehm  Please elaborate on what you are seeing and what is the expectation

**Comment by urveehm** [comment]
This active column in table was showing date and time in previous update,
corrected in latest updated

I Appreciate the quick resolution.
Great work 👍

**Comment by jeremyphilemon** [comment]
Fixed :)
