### ISSUE TITLE
Andhra Pradesh unknown cases were not added to the respective districts

### ISSUE THREAD

**Issue by sasivarenan** [covid19india/covid19india.github.io#571]
Hi Team,

Under the AP state view, unknown cases are still not added to the respective districts. Referring to the link below, the data needs to be added to the district. Please check.

https://www.indiatoday.in/coronavirus-outbreak/story/andhra-pradesh-reports-38-new-covid-19-cases-tally-rises-to-149-1662711-2020-04-03

**Comment by sudevschiz** [comment]
Working on this. Thank you :)
