### ISSUE TITLE
Issue with district name

### ISSUE THREAD

**Issue by ravi-shankar-ojha** [covid19india/covid19india.github.io#572]
**Describe the bug**
District wise report for kerala state is generating wrong. For last column it is showing something else.

**Expected behavior**
Only district name should be there.

**Screenshots**
![Screenshot_20200403-125855](https://user-images.githubusercontent.com/8983606/78335692-b97c2600-75ab-11ea-9d7d-db7d5bce25f3.png)

**Smartphone (please complete the following information):**

- Device: Nokia 8.1
- OS: android 10
- Browser :Chrome
- Version:80.0.3987.149

**Additional context**

While looking for district wise details of kerala state, it shows error at last column.

**Comment by sudevschiz** [comment]
Fixed the data. Thanks a lot for reporting!
