### ISSUE TITLE
District should stay highlighted after a user clicks on it

### ISSUE THREAD

**Issue by shekhars271991** [covid19india/covid19india.github.io#574]
**Is your feature request related to a problem? Please describe.**
When I click on a state the state maps opens. Now when I hove over a district the district numbers are displayed, but as soon as a take the pointer away some random district (possibly the one pointer hovered over last before getting away from the map).

**Describe the solution you'd like**
If any district is clicked on a map, the numbers should be displayed. But as soon as mouse pointer is taken away the numbers should not change, it should only change when the user selects/clicks another district.

**Describe alternatives you've considered**

**Additional context**
![image](https://user-images.githubusercontent.com/12534893/78337157-301a2300-75ae-11ea-8afd-ea22975f756a.png)

**Comment by sudevschiz** [comment]
Very keen UX consideration! 
Also, when the state map is opened, the default district shown is the one with maximum number of cases. Then that district should be highlighted with a boundary too.

Making this available.

**Comment by shuklaayush** [comment]
@sudevschiz This behaviour was pretty deliberate on our part. We didn't want to keep something always highlighted on the map. Will be happy to change it if you want

**Comment by sudevschiz** [comment]
Oh. My vote is for highlighting the district for which the numbers are shown on top. 
Many a times, I confused those numbers to be the entire state numbers. What do you think?

**Comment by shuklaayush** [comment]
@sudevschiz Something like [this](https://covid19india-react-110g0jl7j.now.sh/)? I agree it's less misleading. But I would prefer not displaying any stats unless a region is hovered on, instead of always displaying both the stats of the last hovered-on region as well as highlighting it on the map.

**Comment by shuklaayush** [comment]
Districts are now highlighted by default. Closing
