### ISSUE TITLE
Filter by means of state

### ISSUE THREAD

**Issue by kondannangi163** [covid19india/covid19india.github.io#575]
we can filter the data by means of state in cluster view and see the map by means of state.
Searching by means of state will be more helpful when compared to P2P filter.

Some of the data is mentioned as unknown with location.
It would be better if we update the data asap so the people in the location can be intimated,

Clustering in cluster page is too slow we can increase speed if we pre process the data in server side and give the image to the client when it is reloaded if the data is modified. 
So that there is no need to process the data again and again when ever we reload the page.

we can choose a state and find the latest cases in that region.
we just  need to show that latest person found in that state and the source of the information.

**Comment by sudevschiz** [comment]
Could you report here :  https://github.com/someshkar/covid19india-cluster
