### ISSUE TITLE
Kadapa and ysr states are same

### ISSUE THREAD

**Issue by kondannangi163** [covid19india/covid19india.github.io#576]
kadapa state and ysr state are same but you gave it as a different things

**Comment by guneetnarula** [comment]
I am not sure if I understand this issue correctly. Y.S.R. is a district in AP and Kadapa is its common name. The map on the website is showing data correctly under Y.S.R.

**Comment by jeremyphilemon** [comment]
Closing cause ^ 🤷‍♂

**Comment by kondannangi163** [comment]
Now it is showing correctly.previosly it is wrong. Anyway usefull
application.chill
