### ISSUE TITLE
Confused Text to Understand

### ISSUE THREAD

**Issue by iindranil** [covid19india/covid19india.github.io#577]
Hello,

Users getting confused with this text. Can you please check and let me know.

![image](https://user-images.githubusercontent.com/39942912/78337928-7459f300-75af-11ea-90e8-d445ea609e40.png)

Thank you,

**Comment by twozero88** [comment]
Data in the main table and the map can be updated at the same time?

**Comment by sudevschiz** [comment]
The date reflects any change in the active number of cases. That means a confirmed case, recovery or death.
