### ISSUE TITLE
Hover on VIRUDHUNAGAR district in Tamilnadu state map wrong city highlighted

### ISSUE THREAD

**Issue by SARAN-thala** [covid19india/covid19india.github.io#579]
**Tamilnadu state map hovering issue**
When we hover district of VIRUDHUNAGAR in TamilNadu state map, It highlights the Rameswaram Town as well. But Rameswaram as not part of VIRUDHUNAGAR district, it is part of Ramanathapuram district.

**To Reproduce**

1. Go to India Map
2. Click on TamilNadu state
3. Hover on VIRUDHUNAGAR district 
4. See error: It highlights Rameswaram as well

**Screenshots**

![image](https://user-images.githubusercontent.com/15261261/78339550-44f8b580-75b2-11ea-91f2-4433c8c2c07f.png)

**Desktop (please complete the following information):**

- OS: [macOS]
- Browser [chrome]
- Version [80.0.3987.149]

**Comment by guneetnarula** [comment]
This will be fixed by #413

**Comment by jeremyphilemon** [comment]
Closing cause #413 addressed this :)
