### ISSUE TITLE
Get nearest affected area from your location using area pincode/gps/address and display the visual on map.

### ISSUE THREAD

**Issue by ashish199820** [covid19india/covid19india.github.io#581]
**Is your feature request related to a problem? Please describe.**
This feature provides the ease of tracking the affected area via GPS/area pin-code/address.
Nearest hospitals and test centers can also be added on the map that will help users to locate them in different situations.

**Describe the solution you'd like**
Added map and features to fulfill the stated problem. Need Geo-location and details of hospitals and test centers to plot them on map.

**Additional context**
![COVID-19 Tracker   India (1)](https://user-images.githubusercontent.com/46785034/78344913-b0468580-75ba-11ea-9f2e-cc5e2c88e79f.png)

**Comment by sudevschiz** [comment]
Nice work! Where is the data source for this? How do we make sure that it's authentic?
Are suspected patients supposed to go to the fever clinic directly or call the state helpline?

**Comment by ashish199820** [comment]
> Nice work! Where is the data source for this? How do we make sure that it's authentic?
> Are suspected patients supposed to go to the fever clinic directly or call the state helpline?

Data for the affected area is fetched from https://api.covid19india.org/raw_data.json and is plotted district-wise. 
For data regarding test facility, we can fetch JSON data from -https://covid.icmr.org.in/index.php/testing-facilities?option=com_hotspots&view=jsonv4&task=gethotspots&hs-language=en-GB&page=1&per_page=500&total_pages=1&total_entries=177&cat=&level=4&ne=47.685816%2C114.463016&sw=1.831785%2C30.439579&c=27.047009%2C72.451297&fs=0&offset=0&format=raw
The data consist of 194 test including public and private test facilities. As the counts are increasing rapidly, these data may help people to take quick action for there wellness.

**Comment by sudevschiz** [comment]
The data available at our end is mostly at a district level. The location accuracy is too small to suggest anybody recommended hospitals.

Also, the ICMR data might not be fresh enough.
