### ISSUE TITLE
Percentage of Cases in a state/district is shown only on map hover and not on navigating through the main table

### ISSUE THREAD

**Issue by twozero88** [covid19india/covid19india.github.io#582]
**The Problem**
Percentage of Cases in a state/district is shown only on map hover and not on navigating through the main table.

**To Reproduce**
1. Go to https://www.covid19india.org
2. Hover on Any state
3. Now navigate to the same state in the main table

**Expected behavior**
On 2, we see %age of cases in that region.
On 3, the area is highlighted but %age is not shown.

**Environment**
- Windows 7
- Chrome Browser

**Additional context**
Not a bug though.Would be better if corrected.

**Comment by sudevschiz** [comment]
https://github.com/covid19india/covid19india-react/issues/592

Issue above is available which fixed the problem mentioned in this ticket. Closing this one.
