### ISSUE TITLE
forking for other markets/countries

### ISSUE THREAD

**Issue by shaksi** [covid19india/covid19india.github.io#585]
great work on this, love the simplicity and overview, I have understood mostly how it works - the only thing leaving me baffled is the map generation.

so instead of just assuming things, i thought i would ask - to adapt this for another market (thinking of Kenya/Somali/Ethiopia etc. What is required? happy to do the work, would be glad for topline advice.

**Comment by sudevschiz** [comment]
@shaksi Please do join the dev group in Telegram to discuss more regarding this :)

Another effort here : https://github.com/covid19india/covid19india-react/issues/590

**Comment by shaksi** [comment]
where is the dev group telegram? i have only been able to find the Ops group.

**Comment by jeremyphilemon** [comment]
@shaksi apologies about the late response, here you go https://t.me/joinchat/Mb0ZhVRvI-VZyGuE8uvMbA :)
