### ISSUE TITLE
Percentage by population, area

### ISSUE THREAD

**Issue by ncpanigrahy** [covid19india/covid19india.github.io#586]
Dear team,
Really you are doing well by showing all these things. I am requesting to add increase rate of percentage by population and area. That will help user to know exact increase ratios.
Thanks

**Comment by purut18** [comment]
Hey, can you assign it to me if it is available?

**Comment by ncpanigrahy** [comment]
> Hey, can you assign it to me if it is available?

I think admin only assign to someone, and its a good feature to show in the table, for this we have to know population and area of all the states after that we can do some calculation based on population, area and number of people affected in covid-19 case

**Comment by jeremyphilemon** [comment]
@purut18 sure, just a quickie – how are you planning on adding this functionality? And where do you suggest we add the increase ratios?

For starters, let's not equate the population. How about just figuring out the increase/decrease in percentage?

**Comment by purut18** [comment]
@jeremyphilemon I think we should add this in the district table, 
so there are two ways. either do the calculation in the API or do it on the frontend side.

you mean the increase/decrease in number of cases per day?

**Comment by ncpanigrahy** [comment]
> @jeremyphilemon I think we should add this in the district table,
> so there are two ways. either do the calculation in the API or do it on the frontend side.
> 
> you mean the increase/decrease in number of cases per day?

This should be in the state table , and if population and area available ten we can calculate on frontend side as well.

**Comment by ncpanigrahy** [comment]
> @purut18 sure, just a quickie – how are you planning on adding this functionality? And where do you suggest we add the increase ratios?
> 
> For starters, let's not equate the population. How about just figuring out the increase/decrease in percentage?

@jeremyphilemon its better if we guys consider population and area as a parameter to calculate , lets example there are 635 cases in maharashtra and 445 cases in delhi. 

Maharshtra having 307,713 km2 with 112,374,333 no of people
Delhi having 1,484.0 km2 with 16,787,941 no of people

if you compare then you will able to know delhi is affected more then Maharashtra.

Maharashtra and delhi is just an example.

Hope you guys understood
--

**Comment by purut18** [comment]
@ncpanigrahy so we have to calculate for population or per area or per population per area? that could get confusing

**Comment by ncpanigrahy** [comment]
> @ncpanigrahy so we have to calculate for population or per area or per population per area? that could get confusing

It should be both population and area , first lets approve the issue after that i will give the logic to you

**Comment by mdfaizan7** [comment]
Hello, is this issue available? If it is, then I would like to work on it too

**Comment by jeremyphilemon** [comment]
Closed in favor of #1496
