### ISSUE TITLE
Details needed to be shown on clicking the particular district from the table

### ISSUE THREAD

**Issue by Ritsz123** [covid19india/covid19india.github.io#592]
On the map of the state when mouse is hovered it shows percentage of infections and name of the state and the state is highlighted as well. **But on the table when hovered it just highlight the state or district but does not show the data.**

##I request a feature:
-Clicking the table shall show the percentage and name of the district and highlight it.

**Comment by lavjoshi** [comment]
I would like to contribute.

**Comment by sudevschiz** [comment]
@lavjoshi will assigning to you. However, could you share a mock up of how it would look like before progressing?

**Comment by kirandeep123** [comment]
I would like to work on this one. please assign, if available

**Comment by lavjoshi** [comment]
> @lavjoshi will assigning to you. However, could you share a mock up of how it would look like before progressing?

![image](https://user-images.githubusercontent.com/20904159/78452405-bdda3900-76a8-11ea-9ea7-5f29cfd40c13.png)

**Comment by lavjoshi** [comment]
> @lavjoshi will assigning to you. However, could you share a mock up of how it would look like before progressing?

![image](https://user-images.githubusercontent.com/20904159/78453078-0ac00e80-76ad-11ea-8a6f-ec45bedfdad3.png)

**Comment by Ritsz123** [comment]
@lavjoshi I think it  will be great if you could make the details visible on the map insteed of on the table or you could consult with @sudevschiz before processing.

**Comment by shuklaayush** [comment]
Closed due to inactivity
