### ISSUE TITLE
Add resource list to Helpful Links

### ISSUE THREAD

**Issue by sudevschiz** [covid19india/covid19india.github.io#595]
**Is your feature request related to a problem? Please describe.**
Group of volunteers have prepared a crowdsourced list of resources. Please add this to Helpful links for now. Later this could be make into a separate tab on the website itself with filter functionality.

**Describe the solution you'd like**
Link : bit.ly/covid19resourcelist

Original link : https://docs.google.com/spreadsheets/d/e/2PACX-1vShWjNeNn8n0hen_5KIWQhq_RLCq4Obn23SUzRSAT5fKCQgOZuZnWe57g79elkwum2zavntG_GSawDM/pubhtml?gid=1775152218&single=true

Add this to helpful links as : 
"Crowdsourced list of Resources & Essentials from across India"

**Additional context**

**Comment by strikertanmay** [comment]
Please review at https://github.com/covid19india/covid19india-react/pull/619

**Comment by sudevschiz** [comment]
@strikertanmay thanks for the PR.
But the link is not redirecting to external page. Could you test again?

**Comment by KrishnaPravin** [comment]
@sudevschiz please check now

**Comment by jeremyphilemon** [comment]
Closed by #619
