### ISSUE TITLE
State not highlighted on the map when site is opened initially or after auto refresh

### ISSUE THREAD

**Issue by lavjoshi** [covid19india/covid19india.github.io#600]
**Describe the bug**
By default state with recent activity is shown but the same is not highlighted on India Map 
**To Reproduce**

1. Go to 'https://www.covid19india.org/' or wait for auto refresh

2. See error
![image](https://user-images.githubusercontent.com/20904159/78375555-9886f580-75ea-11ea-9395-827b2ea6aac7.png)

**Expected behavior**
State should be highlighted

**screenshot**
![image](https://user-images.githubusercontent.com/20904159/78375872-13e8a700-75eb-11ea-852e-5b6266a59365.png)

**Comment by lavjoshi** [comment]
If you consider this issue as valid, please assign it to me.

**Comment by sudevschiz** [comment]
Didn't try to reproduce the error. But assigning to you

**Comment by lavjoshi** [comment]
happening due to mouse-leave event, not a valid bug hence closing.
