### ISSUE TITLE
Patient database should present a CalendarView with each day displaying the count of positive cases

### ISSUE THREAD

**Issue by joelewis** [covid19india/covid19india.github.io#601]
**Problem: How can I know how many people were infected in a particular state/district on a given day?**
Right now the patients database page is an indefinite grid of patients, grouped by date. While it gives importance to each patient, getting to a particular day is hard. 

**Solution:**
The top level list is a calendar view, and users can drill through by clicking a day, or a week to find the list of patients.

**Comment by shireeshaBongarala** [comment]
@jeremyphilemon I would like to work on this. Please assign it to me

**Comment by sudevschiz** [comment]
@jeremyphilemon Awaiting your consideration :)

**Comment by jeremyphilemon** [comment]
Patched by #847
