### ISSUE TITLE
Helpful links page should help users to find a testing centre nearby, if they have symptoms

### ISSUE THREAD

**Issue by joelewis** [covid19india/covid19india.github.io#602]
Link to find a testing centre nearby: https://covid.icmr.org.in/index.php/testing-facilities

The site's UX can be better. Future enhancement: It'd be better if we can scrap that data and put out a finder tool as part of the website, itself.

**Comment by sudevschiz** [comment]
I am not sure about the authenticity of this information. It's better if this comes directly from the ICMR official website.

Also, at least for now, nobody is supposed to go to a testing center and get themselves tested. One is supposed to call the state helpline if they are symptomatic. 

Closing this.

**Comment by joelewis** [comment]
Makes sense. Thanks!
