### ISSUE TITLE
urgent Site is broken

### ISSUE THREAD

**Issue by tarun7singh** [covid19india/covid19india.github.io#607]
**Describe the bug**
website is looking completely broken and unformatted
**To Reproduce**
Open website in chrome or Firefox
1. Go to the website

**Expected behavior**
Clear and formatted website

**Screenshots**
![Screenshot_2020-04-03 COVID-19 Tracker India](https://user-images.githubusercontent.com/12068093/78386581-777ad080-75fb-11ea-82d6-173743c27172.png)

**Comment by pranav1698** [comment]
Yeah, same for me 
The site appears completely broken

**Comment by rupesh-raj1997** [comment]
![Screenshot from 2020-04-03 22-39-44](https://user-images.githubusercontent.com/46243931/78386930-17d0f500-75fc-11ea-9e7d-41445f8bf1db.png)
Issue is with the CSS file.

**Comment by tarun7singh** [comment]
@zigmint Yes it seems main CSS is 404
@jeremyphilemon @JunaidBabu

**Comment by rupesh-raj1997** [comment]
A long term solution could be to put the CSS and JS files over to a [CDN](https://rollout.io/blog/use-a-cdn-for-all-static-assets/), seeing the number of visitors you have, you might wanna implement that. @JunaidBabu  @jeremyphilemon

**Comment by zigmint** [comment]
A long term solution could be to put the CSS and JS files over to a [CDN](https://rollout.io/blog/use-a-cdn-for-all-static-assets/), seeing the number of visitors you have, you might wanna implement that. @JunaidBabu  @jeremyphilemon

**Comment by jeremyphilemon** [comment]
Working on a fix :)

**Comment by tarun7singh** [comment]
It's working now, for me at-least. 👍

**Comment by sasivarenan** [comment]
Yes now it's working, I too created another bug request for this, wondering how to close it

**Comment by jeremyphilemon** [comment]
Fixed!
