### ISSUE TITLE
Website sometimes shows a basic version

### ISSUE THREAD

**Issue by Akhil2149** [covid19india/covid19india.github.io#608]
**Describe the bug**
Sometimes the website shows only basic one with all the styles removed. 

**To Reproduce**

1. Go to https://covid19india.org
2. A weird looking website without any style appears (sometimes)

**Expected behavior**
A beautiful website with all styles should be observed
**Screenshots**
![Screenshot_20200403-223519](https://user-images.githubusercontent.com/55274431/78386776-cfb1d280-75fb-11ea-8999-9a15782446c5.png)
**Desktop (please complete the following information):**

Not applicable
**Smartphone (please complete the following information):**

- Device: [e.g. iPhone6] Moto G6
- OS: [e.g. iOS8.1] Android 9
- Browser [e.g. stock browser, safari] Chrome
- Version [e.g. 22] Not sure. Latest version

**Additional context**

**Comment by moumita-saha** [comment]
Same as #607

**Comment by jeremyphilemon** [comment]
working on it, closing cause duplicate

**Comment by ashmis12** [comment]
Console error:

![image](https://user-images.githubusercontent.com/49391760/78387839-99755280-75fd-11ea-9911-597ac875f0c9.png)
