### ISSUE TITLE
The Model on Patients DB is looking off the Viewport

### ISSUE THREAD

**Issue by denvamsi** [covid19india/covid19india.github.io#611]
**Describe the bug**
You can see that when i click on Patient ID in Database, It opens a model with details. It was off the viewport and looks ugly.
**To Reproduce**

1. Go to 'PATIENTS DB'
2. Click on 'Any ID'
3. See the modal box

**Expected behavior**
Actually it should be in middle of viewport and look good.

**Screenshots**
Before it was :

![image](https://user-images.githubusercontent.com/38683119/78387693-6763f080-75fd-11ea-92a1-d4564933d159.png)

**SOLUTION**
Just add this CSS :

.modal .modal-content {
    height: 30rem;
    overflow-y: auto;
}

So it will be fixed like this :
![image](https://user-images.githubusercontent.com/38683119/78387992-dfcab180-75fd-11ea-9936-49daab91c374.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Chrome

**Smartphone (please complete the following information):**

- Device: Samsung
- OS: S9
- Browser : Chrome

**Comment by saym146** [comment]
Change  App.css line no 1781

.modal .modal-content {
    position: fixed;
    padding: 1rem;
    border-radius: 5px;
    align-self: center;
    background: #fff;
    width: 40rem;
    /* height: 40rem; */
    /* overflow-y: scroll; */
    top: 6%;
}

**Comment by denvamsi** [comment]
https://covid19india-react-git-fork-denvamsi-patch-1.covid19india.now.sh/database

**Comment by denvamsi** [comment]
See this, This one fixed it :)

**Comment by denvamsi** [comment]
#606

**Comment by denvamsi** [comment]
Hey there, I have suggested the solution here : #606 . If it successfully executes it will be perfect

**Comment by jeremyphilemon** [comment]
Closed by #753
