### ISSUE TITLE
Incorrect District Name Jajapur, Correct Name :-Jajpur, coming under State Odisha 

### ISSUE THREAD

**Issue by kparida** [covid19india/covid19india.github.io#613]
Correct the district name

**Comment by jeremyphilemon** [comment]
@guneetnarula is it incorrect?

**Comment by kparida** [comment]
https://en.m.wikipedia.org/wiki/Jajpur_district

**Comment by guneetnarula** [comment]
We went with the name Registrar General uses in the census, and survey of india uses in bharatmaps.gov.in. Let's stick to this for now, the point is to report the cases appropriately
