### ISSUE TITLE
Link pointing to cryptocurrency website

### ISSUE THREAD

**Issue by dheerajbarnwal** [covid19india/covid19india.github.io#614]
**Describe the bug**
Link pointing to cryptocurrency website

**To Reproduce**

1. Go to 'FAQ'
2. Click on link with text "list is here
3. check where its pointing to
4. Its pointing to cryptocurrency wallet

**Expected behavior**
It should point to correct and genuine website

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. iOS] iOS
- Browser [e.g. chrome, safari] chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by swingcake** [comment]
Cannot replicate, points to https://telegra.ph/Covid-19-Sources-03-19 as it should.

**Comment by sudevschiz** [comment]
Closing this issue. However, @dheeraj92 please do report again if you notice this in any copy-cat websites.
