### ISSUE TITLE
How to Prevent yourself from the COVID-19 page not available.

### ISSUE THREAD

**Issue by aashish2307** [covid19india/covid19india.github.io#615]
**Prevent yourself from the COVID-19 page not available.**

Some basic do's and don't
To spread knowledge which can have some picture or videos.
How to wash your hands.
Maintain social distance. 
And many more.

**Comment by swingcake** [comment]
How about you submit a PR for the same?

**Comment by sudevschiz** [comment]
We will only point to MOHFW and WHO sites as these are critical information.
