### ISSUE TITLE
Add a column to show percentage/ratio of population infected

### ISSUE THREAD

**Issue by manukushaal22** [covid19india/covid19india.github.io#621]
A new colum to the table that displays the percentage or ratio of number of people infected to total population.

**Comment by darshanhegde13** [comment]
@manukushaal22: It's a good idea,but right now this value will be negligible in India case if we go with the district level also. What do you think?

**Comment by manukushaal22** [comment]
We can multiply the ratio a sufficient power of 10. That gives a value like 2 per million infected. This is what a few other sites have done and I found it useful as it gives a brief idea on how serious the situation is.

**Comment by purut18** [comment]
I would take up this issue if it is available

**Comment by ramprasanth-pyt** [comment]
@purut18 , hey are working on this percentile feature ?

**Comment by purut18** [comment]
no @ramprasanth-pyt, I haven't been assigned yet

**Comment by sudevschiz** [comment]
Could be a good add to state-wise view. @jeremyphilemon, in your court.

**Comment by jeremyphilemon** [comment]
Closed in favor of #1496
