### ISSUE TITLE
district wise Percentages not totalling 100 for delhi

### ISSUE THREAD

**Issue by hotmonk** [covid19india/covid19india.github.io#624]
**Describe the bug**
Sum of cases percentage in delhi state not equaling to 100%.

**To Reproduce**

1. Go to delhi in the map
2. hover on individual districts and see the percentages, their sum doesnt equal to 100 whereas it does in states like maharastra.

- Browser [chrome]

**Comment by shuklaayush** [comment]
Hi @hotmonk, can you verify again that it adds up to 100% in other states? For a lot of cases, the district information is not available and hence, they are tagged as Unknown districts (whose count is shown on the top left in the state map). This is the reason why the percentages aren't adding up to 100%.

**Comment by darshanhegde13** [comment]
@shuklaayush: You are right, but some states doesn't have UNKNOWN districts(ex: TamilNadu). in those states it's adding up to 100%.

**Comment by shuklaayush** [comment]
@darshanhegde13 Thanks! I think that makes sense. It would be misleading if we just ignore the count of unknown districts while calculating percentages. Closing
