### ISSUE TITLE
Please Update Recovered and Death   Section in Rajasthan State

### ISSUE THREAD

**Issue by anju946** [covid19india/covid19india.github.io#625]
**The Rajasthan contains 21 recovered as of now and 3 deaths but your tracker do not updating it ,so please make it sure to provide correct information about Rajasthan State. **

**Comment by anju946** [comment]
Kindly also 'update deceased' patients in Rajasthan State

**Comment by jeremyphilemon** [comment]
Please file issues pertaining to the codebase only. Data discrepancies should be reported in the telegram group (check footer of the website)
