### ISSUE TITLE
Auto scroll by double-tap on state name. 

### ISSUE THREAD

**Issue by manukushaal22** [covid19india/covid19india.github.io#627]
Problem:
It is required by the user to scroll down manually to view the map after double tapping on the state name in mobile screens as the map is below the table.

Possible Solution:
The application should auto scroll to pull the map into viewport when a state has been double tapped so that the user can view it immediately without any interrupt. 

I believe little things like these would enhance the user experience by a great extent.

**Comment by Ninad99** [comment]
I'd like to work on this if it's available

**Comment by jeremyphilemon** [comment]
@Ninad99 Could you also extend this to districts as well? When clicking on any of the district row, you have yourself scrolled to the map? 

The highlighting of the districts already happen, it would just be a matter of scrolling :)

**Comment by Ninad99** [comment]
> @Ninad99 Could you also extend this to districts as well? When clicking on any of the district row, you have yourself scrolled to the map?
> 
> The highlighting of the districts already happen, it would just be a matter of scrolling :)

Sure I could try!

**Comment by jeremyphilemon** [comment]
@Ninad99 also instead of double tapping, it would make sense to have a floating button (https://material.io/components/buttons-floating-action-button/ ) come up when you open the district table, which on a click event will scroll down to the map.

This will work for districts as well, just have a button float up on click of the state row!

**Comment by Ninad99** [comment]
I'm gonna be adding a small package (react-scroll-into-view) to get the best functionality for scrolling, which is about ~450 B minified + gzipped.
https://www.npmjs.com/package/react-scroll-into-view

**Comment by Ninad99** [comment]
> @Ninad99 also instead of double tapping, it would make sense to have a floating button (https://material.io/components/buttons-floating-action-button/ ) come up when you open the district table, which on a click event will scroll down to the map.
> 
> This will work for districts as well, just have a button float up on click of the state row!

This works but the problem is that on clicking the floating button, the highlighted portion of the map is getting reset.

**Comment by Ninad99** [comment]
@jeremyphilemon I've successfully added the scrolling functionality in #696, although the highlighted region does get reset in the map. I tried creating a workaround by changing the function in the onMouseLeave event but that made the map buggy, hence I switched it back to the original function.
