### ISSUE TITLE
Make graphs' x-axis rolling 30 days instead of starting from 30 Jan

### ISSUE THREAD

**Issue by aman4512** [covid19india/covid19india.github.io#629]
Considering that the number of cases in India was fairly dormant in the first month, showing data from the beginning doesn't make much sense. This is especially true for the linear scale now that number of cases is pretty high.

I believe a 30 day (or some other number) rolling representation of data will be cleaner and easier to see. Can probably add that as an option.

**Comment by umanghome** [comment]
Should this be configurable? Options could be last 7 days, last 30 days, since Jan 30.

Would like to work on this if nobody has picked it up yet.

**Comment by faisal3389** [comment]
@jeremyphilemon I would like to work on this issue. Please assign it to me.

**Comment by faisal3389** [comment]
Hi @jeremyphilemon, I would like to work on this. Please assign it to me.
Also, I see that the mini graphs already show the graph for the past rolling 20 days and not from Jan 30th.

**Comment by jeremyphilemon** [comment]
@faisal3389 I'm gonna have to go with @umanghome since he had requested to be assigned earlier.

@umanghome and yes, go ahead! Let me know if you have any questions in the process :)

**Comment by umanghome** [comment]
@jeremyphilemon What should the UI look like for the options? What should the default be?

**Comment by jeremyphilemon** [comment]
Something like this would be good :)

<img width="490" alt="Screen Shot 2020-04-06 at 1 56 09 AM" src="https://user-images.githubusercontent.com/17938322/78512015-ce260d00-77a9-11ea-8878-a8229c5a5300.png">

**Comment by umanghome** [comment]
Using these colors from the image:
- Border: `#C9D6FB`
- Background: `#EDF1FE`
- Background for selected pill: `#C9D6FB`
- Text: `#007bff` ($blue in App.scss)

**Comment by jeremyphilemon** [comment]
@umanghome Sure :)

**Comment by shuklaayush** [comment]
Added in #712
