### ISSUE TITLE
Create Patient timeline with his travel history.

### ISSUE THREAD

**Issue by Vaibhav2812** [covid19india/covid19india.github.io#630]
1. on the selection of State- Taluka corresponding patient list should come 

2. on select particular patient his whole travel history like 
- what time and which place he/she visited.
-  whom he/she met.

3. The timeline should end when he/she admitted in the hospital.

4. Can give patient names like P1, P2...

**Comment by priyadharshini-github** [comment]
Yes. Travel history JSON is already there, but not updated for past 11 days!. It will be useful if that's updated. That is what expected by most of us.

**Comment by jeremyphilemon** [comment]
@sudevschiz is the travel data deprecated or will it be worked on sometime?

**Comment by priyadharshini-github** [comment]
Any update yet?

**Comment by sudevschiz** [comment]
Quite understandably, the state authorities are not releasing patient travel history now. Using that to plot patient travel history is no more a feasible solution. 

Probably a large scale community solution - like the app Singapore developed, Aarogya Sethu released by India Govt., or the one Apple/Google planning to work would be more useful candidates.


Closing this.
