### ISSUE TITLE
Last Updated time inconsistency

### ISSUE THREAD

**Issue by the-sajith** [covid19india/covid19india.github.io#631]
**Describe the bug**
Delhi's cases were updated a minute ago but it still shows Last Updated 18 hours ago. As you can see Delhi has scaled up the chart and is second to Maharashtra

**To Reproduce**

**Expected behavior**
Last Updated time should get updated when numbers get updated. 

**Screenshots**
![Screenshot_20200404-175540](https://user-images.githubusercontent.com/48672482/78450764-90888d80-769e-11ea-92b4-fc1c623a3090.png)
![Screenshot (35)](https://user-images.githubusercontent.com/48672482/78450812-d9404680-769e-11ea-8b16-0b3dfaf9be50.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by vaibhavvikas** [comment]
This bug never occurred to me. I tried on various Operating Systems as well as mobile phones.

**Comment by jeremyphilemon** [comment]
Please file issues pertaining to the codebase only. Data discrepancies should be reported in the telegram group (check footer of the website)
