### ISSUE TITLE
The number of confirmed, recovered and deaths for today is not updating correctly

### ISSUE THREAD

**Issue by starlord2826** [covid19india/covid19india.github.io#633]
**Describe the bug**
On the main page, the number of new confirmed, recovered and deaths in the last 24 hrs is showing up as 0

**To Reproduce
Open the website and look at the screen
You will be able to find the new count to be 0 as attached in the screenshot

**Expected behavior**
The new count should have the number of new cases in the last 24 hrs.

**Screenshots**
![IMG-20200404-WA0007](https://user-images.githubusercontent.com/49427066/78452539-6a1c1f80-76a9-11ea-8d55-8382c6216818.jpg)

**Smartphone (please complete the following information):**

- Device: [e.g. Poco F1]
- OS: [e.g. android 9]
- Browser [e.g. Google Chrome]

**Additional context**

**Comment by Invoker96** [comment]
@Trijwal, It's working now. Please check again

**Comment by vedadeepta** [comment]
Works now - check please, i think maybe there was some issue with the db data.

**Comment by starlord2826** [comment]
Checked and it works now. Closing the issue.
