### ISSUE TITLE
Time series graph showing today's data & date with description "Yesterday"

### ISSUE THREAD

**Issue by vedadeepta** [covid19india/covid19india.github.io#634]
**Describe the bug**
Time series chart under spread trends section showing today's date with label "Yesterday" under it.

**To Reproduce**

1. Go to the website
2. Scroll down to Spread Trends section
3. Today's data & date is displayed on the chart but with the label "Yesterday"

**Expected behavior**
Two possible solutions

1. Show data till yesterday(included) as before.
OR
2. Remove "Yesterday" label under today's date

**Screenshots**
![Screenshot_20200404-192006](https://user-images.githubusercontent.com/25954325/78452540-6e483d00-76a9-11ea-8d42-94c5e16b2f39.png)

**Desktop (please complete the following information):**

All browsers & desktops.

**Smartphone (please complete the following information):**

All mobile devices.

**Comment by vedadeepta** [comment]
Seems fixed now.

**Comment by starlord2826** [comment]
Yes. Just checked! Working fine now

**Comment by vedadeepta** [comment]
Closing, although not sure what happened.
