### ISSUE TITLE
Can we also add some info to have the contact person state/district wise as a point of contact

### ISSUE THREAD

**Issue by arasub** [covid19india/covid19india.github.io#638]
Is your feature request related to a problem? Please describe.**
We can give a point of contact, it could be some one who lead from front in that state/district. Like Health Minister(PA)...

Describe the solution you'd like
To have this a dashboard for INDIA, and to show case number

Describe alternatives you've considered
This could be a additional info, but this could be helpful and become a point of contact.

Additional context
Possible we can make users to subscribe, to know around them

**Comment by sudevschiz** [comment]
I think the state helplines provided in Helpful Links is the right way to contact the government. We can't be releasing personal numbers and overloading the system.

Thanks for your enhancement request though.
