### ISSUE TITLE
West bengal status not updated for 2days

### ISSUE THREAD

**Issue by ushnik99** [covid19india/covid19india.github.io#641]
The count on west bengal has not been updated for 2days straight. 
Also the district/city count is not done completely either.
Please have a look into that.

Its a good thing you guys are doing here. Keep up the good work 
Thank you.

**Comment by jeremyphilemon** [comment]
Please file issues pertaining to the codebase only. Data discrepancies should be reported in the telegram group (check footer of the website)

Thank you for the kind words tho :)
