### ISSUE TITLE
many states have not been updated for a long time

### ISSUE THREAD

**Issue by lyadhcoder** [covid19india/covid19india.github.io#643]
**Telangana, West Bengal, Chandigarh, Ladakh, Andaman and Nicobar islands, Himachal Pradesh, Puducherry, Jharkhand, Manipur, Arunachal Pradesh**. These states have not been updated for a long time. Like _2 or 5 or 8_ days. Kindly Check.
Thank You.

**Comment by jeremyphilemon** [comment]
Please file issues pertaining to the codebase only. Data discrepancies should be reported in the telegram group (check footer of the website)
