### ISSUE TITLE
Unknown is shown as "Evacuees"

### ISSUE THREAD

**Issue by SinghRajenM** [covid19india/covid19india.github.io#645]
**Describe the bug**
Unknown is shown as "Evacuees". Refer screenshot

**To Reproduce**

1. Go to 'Rajasthan map'
2. Expand it and see Right After "Jaipur"

**Expected behavior**
Unknown should be shown rather than "Evacuees"

**Screenshots**

![image](https://user-images.githubusercontent.com/14791461/78456630-6cd73e80-76c2-11ea-9b40-a521e60b5ecd.png)

**Desktop (please complete the following information):**

- OS: [e.g. iOS] Win10
- Browser [e.g. chrome, safari] Firefox
- Version [e.g. 22] latest

**Smartphone (please complete the following information):**
N/A

**Additional context**

**Comment by sudevschiz** [comment]
This is not a bug. Those cases are actually evacuees from Iran (AFAIK). We are working on ascertaining the districts for those.
