### ISSUE TITLE
 update district wise list in Telangana

### ISSUE THREAD

**Issue by swathigrate** [covid19india/covid19india.github.io#646]
hello sir,,
 update district wise positive cases in Telangana.. 
Telangana government officially released press note about district wise possitive list in Telangana..
[office source link ](https://twitter.com/IPRTelangana/status/1246477230068228098?s=20) 

https://covid19.telangana.gov.in/announcements/

https://twitter.com/Eatala_Rajender/status/1246477067576700929?s=20

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Media bulletin on status of positive cases of <a href="https://twitter.com/hashtag/COVID19?src=hash&amp;ref_src=twsrc%5Etfw">#COVID19</a> in Telangana .<a href="https://twitter.com/TelanganaHealth?ref_src=twsrc%5Etfw">@TelanganaHealth</a> <a href="https://t.co/YEgnMjSzJw">pic.twitter.com/YEgnMjSzJw</a></p>&mdash; IPRDepartment (@IPRTelangana) <a href="https://twitter.com/IPRTelangana/status/1246477230068228098?ref_src=twsrc%5Etfw">April 4, 2020</a></blockquote>

**Comment by jeremyphilemon** [comment]
Please file issues pertaining to the codebase only. Data discrepancies should be reported in the telegram group (check footer of the website)
