### ISSUE TITLE
Fix links like https://www.covid19india.org/faqs

### ISSUE THREAD

**Issue by JunaidBabu** [covid19india/covid19india.github.io#65]
Links do not work when they are opened directly. Need to design a better way of routing.

Maybe something like 
https://www.covid19india.org/?faqs or https://www.covid19india.org/?page=faqs etc

**Comment by Abiram-N** [comment]
exact path need to be removed in other Routes

In App.js

`<Router history={history}>
        <Route render={({ location }) => (
          <div className="Almighty-Router">
            <Navbar />
            <Route exact path="/" render={() => <Redirect to="/" />} />
            <Switch location={location}>
              <Route exact path="/" render={(props) => <Home {...props} />} />
              <Route  path="/links" render={(props) => <Links {...props} />} />
              <Route  path="/summary" render={(props) => <Summary {...props} />} />
              <Route  path="/clusters" render={(props) => <Cluster {...props} />} />
              <Route  path="/faqs" render={(props) => <FAQ {...props} />} />
            </Switch>
          </div>
        )}
        />
      </Router>`

**Comment by Abiram-N** [comment]
exact path need to be removed in other routes

![Annotation](https://user-images.githubusercontent.com/42763936/77458485-42fd5c80-6e24-11ea-9ec8-87239dd1564f.jpg)

**Comment by sirajalam049** [comment]
Handling at server-side needed. It is very common problem in SPAs.

https://stackoverflow.com/questions/27928372/react-router-urls-dont-work-when-refreshing-or-writing-manually

**Comment by sirajalam049** [comment]
No @Abiram-N no, this isn't exact path problem.

**Comment by SahajR** [comment]
Yup. Some static deployment services like Netlify and Zeit allow this via an extra file for configuration. 
Netlify has the `_redirects` file and zeit uses [this](https://zeit.co/docs/configuration#project/routes)

**Comment by SahajR** [comment]
Why not move the deployment to Netlify? A CD can be setup from their service dashboard
