### ISSUE TITLE
Full Screen view of map and table (state data). [feature not for mobile view]

### ISSUE THREAD

**Issue by Binu42** [covid19india/covid19india.github.io#655]
**Is your feature request related to a problem? Please describe.**
so, as we can see on home page except for few states, we are not able to see both map and table data simultaneously which is not comfortable for users to enhance user experience this feature is required.

**Describe the solution you'd like**
okay, so my solution is give a button near map to open/close only home component (i.e. table and map) to/from full screen mode, and then give them scrolling option for right-side(map) and left-side(table) separately. so, that they can view the table and map simultaneously.

**Describe alternatives you've considered**
I have started working on it. if you consider these feature please assign it to me. I would like to contribute.

**Additional context**
#### Half-Demo
![demo-giffy](https://res.cloudinary.com/dykt1kcdk/image/upload/v1586026359/after-half-comp_owtbn7.gif)

**Comment by jeremyphilemon** [comment]
Hey thanks for this issue, this has already been raised here #415. Would appreciate it if we could have a discussion there about a potential fix :)
