### ISSUE TITLE
Delhi is missing in Map !!! Please check it 

### ISSUE THREAD

**Issue by AnuragMCAsharma** [covid19india/covid19india.github.io#656]
![4A1B8152-D019-43E1-A56B-B06DC5A710E4](https://user-images.githubusercontent.com/63166112/78459298-9ea5d080-76d5-11ea-8f09-bb6921b0c005.jpeg)
lear and concise description of what the bug is.

**To Reproduce**

1. Go to website
Scroll down to Map view
Then check delhi in map view 

- OS: iOS
- Browser Safari
- Version 13.4

**Comment by Binu42** [comment]
i

> ![4A1B8152-D019-43E1-A56B-B06DC5A710E4](https://user-images.githubusercontent.com/63166112/78459298-9ea5d080-76d5-11ea-8f09-bb6921b0c005.jpeg)
> lear and concise description of what the bug is.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Go to website
>    Scroll down to Map view
>    Then check delhi in map view
> 
> * OS: iOS
> * Browser Safari
> * Version 13.4

Delhi is there
![Screenshot from 2020-04-05 00-50-42](https://user-images.githubusercontent.com/45959932/78459583-aa929200-76d7-11ea-8a04-9a1517c72d2c.png)

**Comment by jeremyphilemon** [comment]
Closing cause Delhi is there and seems to be working fine :P
