### ISSUE TITLE
Include state-wise data of number of tests done; how many negative, pending

### ISSUE THREAD

**Issue by sachinksalim** [covid19india/covid19india.github.io#66]
**Problem statement**
It would be great if we could know how many tests are conducted and how many of those are positive-negative-pending.

**Details**
As of March 24, Kerala and Maharashtra are leading quite ahead of other states in positive cases. But these numbers don't speak truth since Kerala is way ahead of other states in terms of number of people tested. So to get a clearer picture, we could have data like:
1. Number of people tested
2. Number of negative
3. Number of pending results
4. Ratio of people tested with respect to population of state

I know that these numbers are quite hard to get as some state govt themselves haven't released these data. But at least if we update the available data, it would be great!!

**Context**
I came across such a data in a THE HINDU article of March 24. 
![Testing rates](https://user-images.githubusercontent.com/23056099/77458660-8f489c80-6e24-11ea-828b-8c8b5d674e37.jpeg)

**Comment by Goutham88** [comment]
Yeah that would be great to add.
But do we have the data?

**Comment by JunaidBabu** [comment]
@sudevschiz we need to keep statewise test stats. Current test data in the APIs doesn't have any useful information

**Comment by anjannath** [comment]
Yes +1 we need state-wise and in total number of tests conducted, ICMR publishes total number of test conducted count in a pdf though :(

**Comment by aadityadar** [comment]
is there a google sheet that people are collaboratively working on entering the data? the state media bulletins are here https://github.com/aadityadar/covid-19-indian-state-reports

**Comment by jeremyphilemon** [comment]
Is this data readily available now?

@aadityadar I don't think the google sheets we're using enter the data for tests done at the moment, but that may change if we get reliable numbers from a reliable source!

**Comment by jeremyphilemon** [comment]
Closing this because lack of reliable and timely data about the testing numbers.
