### ISSUE TITLE
Enhancement 

### ISSUE THREAD

**Issue by rkaushik0408** [covid19india/covid19india.github.io#667]
Gujarat total cases 122, 11 deaths
13 new cases in MP
9 new cases HP, Total 15
12 new cases in UP
Rajasthan total cases 210, 1 new death
Tamil nadu Death toll reaches 5
6 new cases in Punjab
2 new cases in Delhi

Source Indiatoday and ANI

**Comment by AbhishekRaj-droid** [comment]
https://telegra.ph/CoVID-19--India-Ops-03-24

Please follow the google form to report the cases.

**Comment by shuklaayush** [comment]
Not relevant here
