### ISSUE TITLE
Need a pie chart showing nationalities of the confirmed cases

### ISSUE THREAD

**Issue by akshaykiran** [covid19india/covid19india.github.io#67]
![Screenshot_20200324-234233__01](https://user-images.githubusercontent.com/62459144/77462048-84443b00-6e29-11ea-99f1-347e97d49416.jpg)
Something like this, maybe

**Comment by turbanpride** [comment]
I'll do it . There is only one problem,as of now there is no data in JSON for the pie chart from the API service . We need data w.r.t countries. The format of data required for the graph  is attached in below text file. 
[pieChart.txt](https://github.com/covid19india/covid19india-react/files/4379265/pieChart.txt)

**Comment by sangamesh1439** [comment]
@turbanpride : We can make use of https://api.covid19india.org/raw_data.json api to get all data. This data set has nationality field. What do you think ?

**Comment by turbanpride** [comment]
> @turbanpride : We can make use of https://api.covid19india.org/raw_data.json api to get all data. This data set has nationality field. What do you think ?

we can use that data for sure, but before using this data for plotting, we need to consolidate data or group it with countries so that we can sort it accordingly. :D 

Also we need to make sure where we need to keep the graph. Alignment should be good at look.

**Comment by sangamesh1439** [comment]
Ok, I will start working on it.

**Comment by shirshandu** [comment]
> Ok, I will start working on it.

did you else I can?

cc @s-naveen

**Comment by jeremyphilemon** [comment]
Closed by #539
