### ISSUE TITLE
Unnecessary URLs in "Helpful Links"

### ISSUE THREAD

**Issue by SachinRammoorthy** [covid19india/covid19india.github.io#671]
**Describe the bug**
URLs present rather than links in the Helpful Links section.
Not a bug, an enhancement.

**To Reproduce**

1. Go to 'covid19india.org'
2. Click on 'Helpful Links'
3. See error

**Expected behavior**
Links should replace the URLs

**Screenshots**
![Screen Shot 2020-04-05 at 12 15 35 PM](https://user-images.githubusercontent.com/20569603/78468603-23750680-7737-11ea-900b-86d410795997.png)

vs

![Screen Shot 2020-04-05 at 2 12 00 AM](https://user-images.githubusercontent.com/20569603/78468607-296ae780-7737-11ea-8b37-1db79e1a3a8e.png)

**Desktop (please complete the following information):**
**For all devices**

**Smartphone (please complete the following information):**
**For all devices**

**Comment by SachinRammoorthy** [comment]
@pravinagrawal145 I already created a pull request. This issue has not been reviewed yet.

**Comment by jeremyphilemon** [comment]
Hey thanks for opening this issue, unfortunately this is a stylistic choice to show the contents of the url instead of having them hidden :)
