### ISSUE TITLE
UT of Dadar & Nagar Haveli, Pondicherry and Lakshadweep seem to be missing on the covid19.org map

### ISSUE THREAD

**Issue by sudevschiz** [covid19india/covid19india.github.io#674]
**Describe the bug**
The small territories was probably smoothened out during the size reduction of the polygon.

**Expected behavior**
All territories should be present in the map. Better still, there should be zooming option to select them.

More details from a previous issue comment :  

This geoJSON was created from this source : http://projects.datameet.org/maps/states/
That was the only source that I could find where at least Telangana was plotted correctly.

They have an open issue regarding this here : datameet/maps#45

If someone can work on this and provide the boundaries (probably by using the district-wise polygons) it'll be great! Would be a cool open-source initiative too!

Other sources and resources

GADM.org The GADM data does not represent the Indian version of the maps : https://gadm.org/download_country_v3.html. So doubt if that source can be used.

If a correct geoJSON or Shapfile file is identified (which could be 10-100MB depending on the details), one can use https://mapshaper.org/ to simplify it to a few kB in size.

State names have to confer with the ones mentioned in the sheet. If it's not visible, http://geojson.io/ can be used to tag the properties.

**Additional context**
India map polygon was selected from datameet. Later Ladakh region was hand drawn on top of it.
Post that, the polygon was smoothened to reduce size. The small territories probably got lost in this step

**Comment by nikhilsamant** [comment]
I have extracted the topoJson for the UTs from  http://projects.datameet.org/maps/states/
using https://mapshaper.org/ 

Please check below file and use them if useful

[puducherry.txt](https://github.com/covid19india/covid19india-react/files/4434530/puducherry.txt)
[damandiu.txt](https://github.com/covid19india/covid19india-react/files/4434533/damandiu.txt)
[dadranagarhaveli.txt](https://github.com/covid19india/covid19india-react/files/4434534/dadranagarhaveli.txt)
[lakshadweep.txt](https://github.com/covid19india/covid19india-react/files/4434535/lakshadweep.txt)

**Comment by opheliagame** [comment]
@sudevschiz I have tried extracting the topologies. You can check the files [here](https://drive.google.com/open?id=1VZdMq30nGT9waN5qDYJpbhtFLJdyZEWm)

**Comment by shuklaayush** [comment]
Seems to have been added
