### ISSUE TITLE
District wise recovered, active, and deceased cases numbers

### ISSUE THREAD

**Issue by sam2964** [covid19india/covid19india.github.io#675]
District wise report is not visible. No of total cases are visible but in that total no. of cases no. Of active,recovered,deceased figure is not  visible.

![Screenshot_2020-04-05-13-07-43-15](https://user-images.githubusercontent.com/56807608/78469395-78684b00-773e-11ea-871d-006659be3237.png)

**Comment by sam2964** [comment]
#Type:bug

**Comment by sam2964** [comment]
`enhacement`

**Comment by sarkar-sayantan** [comment]
<img width="960" alt="covid1" src="https://user-images.githubusercontent.com/21034360/78866271-b5914d80-7a5c-11ea-922a-f1ab13f43651.PNG">
I was checking it. The reason behind this was - two different types of data is recieved. Look at the right side of the picture (highlighted).

**Comment by sarkar-sayantan** [comment]
I think, I can fix it. Please assign it to me. @jeremyphilemon

**Comment by sudevschiz** [comment]
This is because there is good data at district level for many of the recovered and deceased case. However, it's being worked on here to provide whatever data is available through : https://github.com/covid19india/api/issues/114

**Comment by jeremyphilemon** [comment]
Closed by #1407
