### ISSUE TITLE
Add page with display and utilize the Crowdsourced Resource List

### ISSUE THREAD

**Issue by sudevschiz** [covid19india/covid19india.github.io#676]
**Is your feature request related to a problem? Please describe.**
Team has collected a vast number of resources that would be helpful for the general public here : 
https://bit.ly/covid19resourcelist

This need to be displayed with useful filtering capability in a separate tab in the main website.

**Describe the solution you'd like**
1. The sheet needs to be converted into an API endpoint (https://github.com/covid19india/api/issues/73)
Update : This is now available in the endpoint https://api.covid19india.org/resources/resources.json

2. Separate tab called "Resource List" to be added to the main website.

3. Provide a filter-view for user to select the state and/or district. 
4. Provide an option fo the user to select the category for which they need help. Simple icons might be better?

5. Filter the right information from JSON above and show it in a card format to the usre.
6. Necessary disclaimers about the usage of the data needs to be added
7. An option to Report Error/Add new resources to be added.

Please try to use the same color scheme and design paradigm as of the main website.

**Describe alternatives you've considered**
Currently the resource list is present as a link in "Helpful Links"

**Comment by nikita-11** [comment]
Sure. We will take this up from here.

**Comment by ashwin06k** [comment]
I too am working with Nikita on this.

**Comment by sama007** [comment]
Hi, I was working on this with Nikita and finished this issue. Need to raise pull request. Can I please get assigned?

**Comment by sama007** [comment]
Attaching screenshot for mobile view

![Screenshot_2020-04-08-02-44-49-084_com android chrome](https://user-images.githubusercontent.com/14778332/78720336-25131a00-7943-11ea-90aa-9bb973843d78.png)
![Screenshot_2020-04-08-02-45-00-799_com android chrome](https://user-images.githubusercontent.com/14778332/78720357-2f351880-7943-11ea-9515-f11e31f4fd87.png)
