### ISSUE TITLE
Arrow marks are not showing properly for some boxes

### ISSUE THREAD

**Issue by Deepu0311** [covid19india/covid19india.github.io#683]
**Describe the bug**
In the states table for some states arrow mark is showing above the numbers

**To Reproduce**

1. Go to 'covid19india.org' 
2. See the arrow mark for Maharashtra state deceased colum and andhraprabdesh state confirmed box and also total confirmed box. 

**Expected behavior**
The arrow mark need to show beside the table. 

**Smartphone (please complete the following information):**

- Device: honor 8x
- OS: android
- Browser : chrome
- Version : 10

**Comment by mayurisakpal** [comment]
This is the expected behavior of `up arrow and it's label` if space is not available on the same row, right?  

![Screenshot (1)](https://user-images.githubusercontent.com/36845563/78500488-57bae800-7774-11ea-85a1-c15e4127fdac.png)

**Comment by surbhi239** [comment]
This issue is arising because column of deceased is not flexible as confirmed cases and recovered cases.

**Comment by mayurisakpal** [comment]
If the length of the number increases, this is going to happen for confirmed cases and recovered cases as well. To avoid that we can shift the whole `up arrow with its label` above the second number when space is not available instead of just shifting the `up arrow`.

**Comment by mayurisakpal** [comment]
Working on these issues:
1. fix alignment of `chevron right  icon within a circle` and show `up arrow  beside its label`
![Screenshot (4)](https://user-images.githubusercontent.com/36845563/78505274-10425500-7790-11ea-9bad-9cfae7d21c99.png)

2. fix update badge which is overlapping with text on the small screen
![Screenshot (3)](https://user-images.githubusercontent.com/36845563/78505331-6ca57480-7790-11ea-8435-4c89bb6b9676.png)

**Comment by surbhi239** [comment]
![image](https://user-images.githubusercontent.com/25776004/78505982-b1e38b00-772b-11ea-9fc7-196e2fffdabe.png)
I agree it will go down if the number of cases increases for the deceased row. But see confirmed cases section is flexible. so, it enlarges as the count increases. We need same thing for every column.
Check the exact behavior at the 1024px screen.
Note: This problem is only coming when this site is accessed through the mobile phone.

**Comment by mayurisakpal** [comment]
Yea, this issue is happening only for the small screen, as the table is taking the device width. Also, this is going to happen for all columns if we increase the number.
![Screenshot (5)](https://user-images.githubusercontent.com/36845563/78506568-03c1fa80-7798-11ea-8908-3ab1727fc0b5.png)

**Comment by surbhi239** [comment]
I totally agree with you on this point. Thus, increasing width as the number of cases increases instead of making it increase as device width increases.
