### ISSUE TITLE
Banner: bold tag 

### ISSUE THREAD

**Issue by kryptocodes** [covid19india/covid19india.github.io#684]
**Describe the bug**
bold tag is visible in the banner

**To Reproduce**

1. Go to 'covid19india.org'
2. Look at the snippet
"State Electricity Boards have asked citizens not to switch off or switch on lights and appliances  <b`>all at the same time</b`>  as it could cause a blackout."

3. See error <`b> </b`>

**Expected behavior**
The tag should be hidden

**Screenshots**
![Capture2](https://user-images.githubusercontent.com/40030019/78472471-abb6d400-7756-11ea-8682-1df749d7c27f.PNG)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Chrome
- Version: 80.0.3987.163

**Comment by SamirDasarwad** [comment]
banner is changing only on-click i think it should be changeable after some time or can be moving

**Comment by vaibhavvikas** [comment]
I can work on this. If you assign me on this.

**Comment by xi1570-krupeshanadkat** [comment]
I think this issue is solved now, 
- Banner is changing automatically,
- html b tag bug is fixed. 
I think we can close this issue?

**Comment by SamirDasarwad** [comment]
yes i saw that issue is solved good work , i also want help here if anything required i will help

**Comment by jeremyphilemon** [comment]
This has been patched, thanks :)

@sameerdasarwad you can pick any issue labelled "available" and submit PRs :)
