### ISSUE TITLE
Refactor code for footer component

### ISSUE THREAD

**Issue by himanshu8426** [covid19india/covid19india.github.io#686]
**Is your feature request related to a problem? Please describe.**
Footer code is written in app.js. Code should be written as a component.
**Describe the solution you'd like**
make a footer component and import it to app.js

**Comment by sudevschiz** [comment]
Could you add more details on what improvement this change makes?

(Just trying to make the maintainers' lives easier)

**Comment by himanshu8426** [comment]
Just made the react app more component based(footer component is written in app.js should be an another component). Also footer component was outside router.
