### ISSUE TITLE
Simultaneously switching on the Uniform and Logarithmic toggle switch

### ISSUE THREAD

**Issue by fenil25** [covid19india/covid19india.github.io#687]
**Describe the bug**
When the user toggles on the logarithmic scale, the uniform scale should be automatically switched off. However, in the current scenario, both the toggle switches are simultaneously "on" which shouldn't be the case. Also, when disabling the logarithmic scale, the uniform scale should be switched on by itself. 

**To Reproduce**

1. Go to 'Special Trends'
2. Click on 'Cumulative Mode'
3. Switch on the logarithmic scale

**Expected behavior**
At a time, exactly one of the switches should be toggled on. Also, either one of those should always be ON and both of them should not be switched off.

**Screenshots**
![image](https://user-images.githubusercontent.com/32615205/78473097-92645680-775b-11ea-9972-9af096853e90.png)
![image](https://user-images.githubusercontent.com/32615205/78473107-a0b27280-775b-11ea-850b-ba2d87790960.png)

**Desktop (please complete the following information):**

- All OS
- All browsers
- All versions

**Smartphone (please complete the following information):**

- All Devices
- All OS
- All browsers
- All versions

**Comment by milap1296** [comment]
@fenil25 As far as I can understand the reason to put the switcher is you can enable both Uniform & Logarithmic scale at a same time.
If it wasn't like that it could have been more simpler to put just one switcher or add radio buttons.

**Comment by fenil25** [comment]
"Uniform & Logarithmic scale at the same time"- How is that possible? The y-axis can't be mapped to both the scales simultaneously, right?
Also, I agree that one switcher should just do the work.

**Comment by shuklaayush** [comment]
@fenil25 I think you misunderstood what the term 'Uniform' means in this context. Here, it just means that the scale of all the three charts is the same, whereas 'Logarithmic' actually switches the scale between a linear and a log scale. Closing for now.
