### ISSUE TITLE
Extra Column of Number of tests done.

### ISSUE THREAD

**Issue by ravishk1** [covid19india/covid19india.github.io#688]
The work is wonderful. Just for the curiosity, can we include extra Column of number of tests done till now ? That will also be useful.

**Comment by swapdewalkar** [comment]
I can do this, can you assign it to me. Extra column or better it can be a block like recovered,active deceased for every state, we can do tested,pos,neg,%.

**Comment by shuklaayush** [comment]
Since there's no more space in the table, added as a block like @swapdewalkar mentioned.  See #699
