### ISSUE TITLE
Figures for WB

### ISSUE THREAD

**Issue by Ashwin56** [covid19india/covid19india.github.io#689]
Can you please update the figures for West Bengal, there have been plentiful changes in the past 24 to 48 hours and the figures are not yet displayed correctly on the website.
Thanks.

**Comment by sudevschiz** [comment]
Awaiting detail from the government.

**Comment by sayan801** [comment]
New data available  from west bengat govt health department.

- https://www.wbhealth.gov.in/pages/corona/bulletin
- https://www.wbhealth.gov.in/uploaded_files/corona/Bulletin_West_Bengal_04.04_.pdf

![image](https://user-images.githubusercontent.com/438014/78501092-d36a6400-7777-11ea-8dcb-4e6ae8aa4d0f.png)

Mohfw website also updated the data about west bengal. Please update here as well.

https://www.mohfw.gov.in/

![image](https://user-images.githubusercontent.com/438014/78501142-0280d580-7778-11ea-81b2-911a908c56f1.png)
