### ISSUE TITLE
No data in patient db. As well tabs are not working.

### ISSUE THREAD

**Issue by bh22mi** [covid19india/covid19india.github.io#69]
![Screenshot_20200324_235222](https://user-images.githubusercontent.com/38246549/77462829-ac806980-6e2a-11ea-857b-c53ae1d36032.jpg)

Device - vivo v9
Browser - Uc browser

**Comment by JunaidBabu** [comment]
Javascript is disabled?

**Comment by skandtandon** [comment]
db is up and tabs are working might be an issue at your end
