### ISSUE TITLE
Region is not highlighted even though it is showing the statistics about the same region 

### ISSUE THREAD

**Issue by sumukhah** [covid19india/covid19india.github.io#695]
**Hovered region should remain highlighted until the next hover**
Users hover on a region and get some statistics. Later they move the pointer(mouse) away from the map. It will show data about the same region(state/district) but the region will not remain highlighted.

**To Reproduce**

1. Hover on a region(state/district)
_The region will be highlighted and the Statistics about that region will be displayed_
2. Move the pointer away from the region
3. See error
The region will not stay highlighted even though statistics displaying related to it.

**Expected behavior**
It should remain highlighted until the next Hover(highlight).

**Screenshots**
![Screenshot from 2020-04-05 18-34-35](https://user-images.githubusercontent.com/23723464/78499089-3655fe00-776c-11ea-8f3c-06f1bfc11295.png)

**Desktop (please complete the following information):**

- OS: All Os

**Comment by sumukhah** [comment]
Working on the issue

**Comment by karanshah0206** [comment]
I would like to be assigned to fix this bug.

**Comment by sumukhah** [comment]
thank you @sudevschiz, I will fix this soon,
can you suggest some UI design to handle this?
because from my old pr(https://github.com/covid19india/covid19india-react/pull/697), @shuklaayush suggested me
not to put time on that UI design.
