### ISSUE TITLE
Link Google Maps API to show vulnerable areas !

### ISSUE THREAD

**Issue by Apoorve73** [covid19india/covid19india.github.io#702]
I have seen many websites providing real time data but it always seems good to get a visual experience of the spread of pandemic and that too real time.

I want to add Google Maps Javascript API for locating these regions on Map .

I had developed an application for representing those vacant lands in Dallas, Texas that are fit to develop a hospital.

Here is a screenshot!
The only difference will be these markers will be replaced by a circular marker represent the range of  affected areas.
![Map_Dallas](https://user-images.githubusercontent.com/55204045/78501798-0b26db00-777b-11ea-954b-96da2a94eb06.png)

**Comment by sudevschiz** [comment]
Only very few cases have city level information. The lowest granularity that we have good coverage is district-level (even that is missing in many cases). Hence, it would be incorrect to plot it on a map this way.

Closing.

**Comment by Apoorve73** [comment]
Okay! But what about areas too prone to this disease? We have almost every single detail for them.
