### ISSUE TITLE
Adding relevant graphs to track the severity of the spread.

### ISSUE THREAD

**Issue by TheDominus** [covid19india/covid19india.github.io#708]
**Is your feature request related to a problem? Please describe.**
Currently, we have only 3 graphs that are 
1. Confirmed
2. Recovered
3. Deceased
But, to track the spread of the virus and the pressure on the medical infrastructure, we need more relevant graphs. 

**Describe the solution you'd like**
1. The most relevant graph to track the pressure on the medical infrastructure is the number of active cases i.e. ``` Active Case = Confirmed Case - Recovered - Deceased.```
2. We need to determine the increase in the number of confirmed cases with respect to the last day
i.e. Suppose on the first-day number of new confirmed cases was 5 and the next day the number of new confirmed case 10 than ROR will be 100% if the next day number of new case in 7 then ROR will be -30% 
Simply, we can say ```ROI = (New confirmed case today/ New confirmed case yesterday) * 100```

**Describe alternatives you've considered**
For ROI Graph We can track in decimal ```ROI = (New confirmed case today/ New confirmed case yesterday) ``` instead of using the percentage

**Additional context**
There is a good video that explains which graphs are relevant to track if we are beating coronavirus or not. 
https://www.youtube.com/watch?v=54XLXg4fYsc

**Comment by TheDominus** [comment]
@JunaidBabu  Part 1 of the solution can be easily implemented on the new deep dive, India total case graph and the graph can be reused.

**Comment by shuklaayush** [comment]
Active cases graph has been added to the home page. Closing
