### ISSUE TITLE
Add option to show total tested samples

### ISSUE THREAD

**Issue by kracekumar** [covid19india/covid19india.github.io#709]
**Is your feature request related to a problem? Please describe.**
It's been repeated written in many articles India is testing fewer people per million. The Govt releases data on how many samples tested and how many cases are positive out of the tested samples. The [API](https://api.covid19india.org/data.json) contains the same data under the field name `totalsamplestested`. It may be a good idea to represent the information as a ratio or any other metric both at the country and state level.

**Describe the solution you'd like**
1. Display a table containing state name, total samples tested, total positive cases, positive cases/samples. 
2. Already home page contains similar data, maybe add a column to the existing column(only ratio).
3. A graph containing ratio over a time period for both states and the country.

**Describe alternatives you've considered**
The above solution can be added in multiple places depending on the UI and other parameters.
 
**Additional context**
NA

**Comment by shuklaayush** [comment]
Fixed via #699
