### ISSUE TITLE
Wrong number of deceased on 5th April 2020 in API

### ISSUE THREAD

**Issue by abhishekakade** [covid19india/covid19india.github.io#716]
**Describe the bug**
`case_time_series` for 05 April 2020 shows `totaldeceased` as 121 -

```diff
{
  "dailyconfirmed": "605",
- "dailydeceased": "22",
  "dailyrecovered": "42",
  "date": "05 April ",
  "totalconfirmed": "4289",
- "totaldeceased": "121",
  "totalrecovered": "328"
}
```

while the `statewise` for Total (India) as of 06/04/2020 00:11:24 shows 118 `deaths` - 

```diff
{
  "active": "3843",
  "confirmed": "4289",
- "deaths": "118",
  "deltaconfirmed": "0",
  "deltadeaths": "0",
  "deltarecovered": "0",
  "lastupdatedtime": "06/04/2020 00:11:24",
  "recovered": "328",
  "state": "Total",
  "statecode": "TT"
}
```

**To Reproduce**
Go to https://api.covid19india.org/data.json and compare both.

**Expected behavior**
Number of deaths to not have reduced as it is impossible. If the number of deaths 121 on 5th April 2020 was because of false reports, then it should be corrected/updated in the API itself as well for 5th April 2020 from 121 to 118. Might have to check the number of `dailydeceased` as well for 4th and 5th April 2020.

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Chrome
- Version: 80.0.3987.149 (Official Build) (64-bit)

**Additional context**

**Comment by shuklaayush** [comment]
Should be fixed now
