### ISSUE TITLE
When user mouse hover on State/UT at  the bottom of a list, User need to scroll up screen for more details. So this is not user friendly way!

### ISSUE THREAD

**Issue by rohitaneja91** [covid19india/covid19india.github.io#717]
**Is your feature request related to a problem? Please describe.**
This is not a user friendly way like When user mouse hover on State/UT at  the bottom of a list I need to scroll up screen for looking the more details. 

**Describe the solution you'd like**
If possible you can move a Spreads Trend above and more detail state/UT map section below that and hard code the More Details state section, so we scroll up and down hovering the list of states accordingly it will change the state/UT detail map 

**Describe alternatives you've considered**

**Additional context**

**Comment by Binu42** [comment]
This is already mentioned here #415 and a of solution it is here #680

**Comment by Binu42** [comment]
you can use this link to save yourself from scrolling and all... https://covid19india-react-git-fork-binu42-fullscreen.covid19india.now.sh/

**Comment by parichay28** [comment]
@Binu42 I've noticed that it's been quite difficult for me to click on an UT Dadra & Nagar Haveli on the map. So far I've been unsuccessful in doing so even after zooming in aggressively. Is that an issue you are facing as well ?

**Comment by Binu42** [comment]
@parichay28 ya i'm also facing same for 3 union territory chandigarh, PUDUCHERRY and dadra & nagar haveli. i think there map are not included that's why this is happening and I think this is not any big issue because these UT doesn't have district inside it.

**Comment by sudevschiz** [comment]
What is the status here?
@KrishnaPravin are you working on this?

**Comment by KrishnaPravin** [comment]
@sudevschiz we have added nav buttons for mobile screen.
Preview: https://covid19india-react-q4wrovyi3.now.sh/
PR: https://github.com/covid19india/covid19india-react/pull/930

This PR has the state wise time series graph too

**Comment by jeremyphilemon** [comment]
Patched by #1364
