### ISSUE TITLE
Feature Donate on Homepage

### ISSUE THREAD

**Issue by smittal1209** [covid19india/covid19india.github.io#719]
**Is your feature request related to a problem? Please describe.**
A donate page on the homepage of the site that will show all the official information on how a user can donate to for the cause. For Example : A section showing information on how to donate to PM Cares fund or State Govt. Funds and a section showing various NGOs to which donation can be made via UPI or Paytm or any other channel.

**Describe the solution you'd like**
Currently data will be updated to the google sheet database and fetched from there as done for other APIs like FAQ.

**Describe alternatives you've considered**
No alternative as this is the need of the hour. This will motivate people and even a small amount raised through it will be of high help.

**Additional context**
Future enhancements include showing Twitter and Instagram trends and post of users like celebs who are supporting so that more and more people will be encouraged to donate or come forward to help the needy and poor.

Sections will be like given below in screenshots.
<img width="1391" alt="Screenshot 2020-04-01 at 6 21 39 PM" src="https://user-images.githubusercontent.com/23252949/78528052-1bcb6580-77fc-11ea-9ce0-b8d70d802c19.png">

**Comment by smittal1209** [comment]
@jeremyphilemon and Team, Kindly review the feature request.

**Comment by shuklaayush** [comment]
Hi @smittal1209, I see that you've put a lot of thought into this. But please comment and continue the discussion on #672. It would be easier for us to track
