### ISSUE TITLE
Change the label name.

### ISSUE THREAD

**Issue by Irshad-pega** [covid19india/covid19india.github.io#721]
**Change of Label**

Change the Label to "Kishtwar"

I have attached screen shot for more reference 
![Screenshot_20200406-142237_Chrome](https://user-images.githubusercontent.com/63225224/78529337-f185a200-7813-11ea-892e-7ef1863621e0.jpg)

**To Reproduce**

1. Go to 'State/ UT'
2. Click on 'Jammu and Kashmir'
3. Scroll down to districts.
Label "Kashmir" should be replaced to "Kishtwar"

Thank you. 

**Expected behavior**
N/A

**Screenshots**
Attached above
**Desktop (please complete the following information):**

- OS: [N/A]
- Browser [N/A]
- Version [N/A]

**Smartphone (please complete the following information):**

- Device: [N/A]
- OS: [N/A]
- Browser [N/A]
- Version [N/A]

**Additional context**
NR

**Comment by mehrapiyush** [comment]
I think the data from api is incorrect that's why showing such errors.

**Comment by Irshad-pega** [comment]
From google sheets distt. list is okay.
![Screenshot_20200406-180823_Chrome](https://user-images.githubusercontent.com/63225224/78547678-0b35e200-7832-11ea-8f3f-a8eb59d11d2f.jpg)

**Comment by shuklaayush** [comment]
Seems to be fixed
