### ISSUE TITLE
Spelling of cities are wrong

### ISSUE THREAD

**Issue by klakho0400** [covid19india/covid19india.github.io#723]
example:- Ahemdabad marked 'Ahmadabad' in the map in Gujarat
                 Ahmednagar marked 'Ahmadnagar' in the map in Maharashtra

**Comment by g-ravity** [comment]
@klakho0400 can you provide a complete list of such errors? I can fix these typos with a PR then

**Comment by guneetnarula** [comment]
Hey, we are using names as per the registrar general of india and survey of india. These districts are spelt like that by them, but it is true that there is no consistency among different government bodies
