### ISSUE TITLE
Forecasting

### ISSUE THREAD

**Issue by alpha-k911** [covid19india/covid19india.github.io#727]
We can forecast the data and present it here.

There are so many R library Packages which will forecast the data and present them here

I would like to contribute to that.

Previously I have worked on Stock Market prediction on Time Series.
So, I feel adding this feature to this project will be a good idea

**Comment by chaira19** [comment]
@alpha-k911 I would like to work with you in this feature. Please let me know if you start working on this.

**Comment by alpha-k911** [comment]
Sure

**Comment by kiku511** [comment]
Here's a resource that I was reading for forecasting. http://www.healthdata.org/covid/updates
It's released by the IHME and they used it to predict the course of the spread through different states in the US. I think following a similar model might help us forecast better. 
Link for the projections: https://covid19.healthdata.org/projections
Details on the methodology and formulae used: www.medrxiv.org/content/10.1101/2020.03.27.20043752v1.full.pdf

**Comment by Krutarth-Bhatt** [comment]
> We can forecast the data and present it here.
> 
> There are so many R library Packages which will forecast the data and present them here
> 
> I would like to contribute to that.
> 
> Previously I have worked on Stock Market prediction on Time Series.
> So, I feel adding this feature to this project will be a good idea

I definitely feel this feature will be very useful, I also love to join for it!!!

**Comment by alpha-k911** [comment]
I have hosted(on port 8000) forecasted data on my system for testing the graph(i have added another graph for forecasted data) but, I'm Network Error generated by Axios. Does anyone know why..?

**Comment by alpha-k911** [comment]
Pull Request: https://github.com/covid19india/covid19india-react/pull/1120
Deployment: https://covid19india-react-k9qct90h3.now.sh/

I have resolved the Network Error.

I have made the Forecast script and raw_data. Pull Request Link is provided above. Any suggestions are welcomed  :smile:

**Comment by shuklaayush** [comment]
Duplicates #511

**Comment by alpha-k911** [comment]
Can you assign me for that feature...?
