### ISSUE TITLE
Change flexbox spacing between the child divs of the Home component

### ISSUE THREAD

**Issue by jaymovaliya** [covid19india/covid19india.github.io#73]
There is no space between "INDIA COVID-19 TRACKER" and "STATISTICS BY STATE" titled div in laptop view

**To Reproduce**
1. Go to 'https://www.covid19india.org'

**Expected behavior**
There should be space between above mentioned two divs

**Screenshots**

![covid19bug](https://user-images.githubusercontent.com/22033842/77500197-5b986180-6e7a-11ea-9b1f-87baff0d6546.png)

***It should be like this***

![covid19bugsolved](https://user-images.githubusercontent.com/22033842/77500414-f2fdb480-6e7a-11ea-99c3-906aaa6a983e.png)

**I am also adding pull request to solve the same**

**Comment by Amritesh** [comment]
This issue is resolved right?
