### ISSUE TITLE
Info icon display for "West Bengal" 

### ISSUE THREAD

**Issue by DhiralKaniya** [covid19india/covid19india.github.io#731]
**Describe the bug**
Info(FAQ) icon is displayed for a state "West Bengal". It is redirecting to the FAQ page. 
It should not be displayed as a behavior of all-state.

**To Reproduce**
1:- Go to https://www.covid19india.org/
2:- Find West Bengal in the table view.

**Screenshots**
- 
<img width="726" alt="Screenshot 2020-04-06 at 3 19 19 PM" src="https://user-images.githubusercontent.com/21332852/78546205-a58a2b80-781a-11ea-908a-9d88a4ca84a3.png">

**Desktop (please complete the following information):**

- OS: iOS
- Browser:- chrome
- Version:- 80.0.3987.163 (64 bit)

**Comment by shuklaayush** [comment]
This is deliberate to focus attention on this particular FAQ.
![image](https://user-images.githubusercontent.com/27727946/78547499-d23f4280-781c-11ea-8a8e-1c2c38559a8d.png)

Will be removed when necessary.
