### ISSUE TITLE
West Bengal Database Related.

### ISSUE THREAD

**Issue by shekzek** [covid19india/covid19india.github.io#735]
New Update For west Bengal Official Press Release.

https://bengali.abplive.com/news/covid-19-india-live-updates-21-corona-cases-in-bengal-mamta-banerjee-pm-modi-680247

**Comment by KrishnaPravin** [comment]
@Kalibaba-Pro please use [this form](https://forms.gle/MLeSrdwRuf8AjFkp9)

https://forms.gle/MLeSrdwRuf8AjFkp9
