### ISSUE TITLE
Api Response Changed Suddenly

### ISSUE THREAD

**Issue by dhruvkaushal11** [covid19india/covid19india.github.io#736]
**Describe the bug**
The response of the api at "https://api.covid19india.org/data.json" was changed suddenly.
Previously there was state wise and active data but everything just messed up last night.
**To Reproduce**
Just go to https://api.covid19india.org/data.json
You have mentioned [here](https://api.covid19india.org/) also that "**National time series, statewise stats and test counts**" is available on this endpoint but it's no where to be found.

Please look into this.

**Comment by shuklaayush** [comment]
Hey @dhruvkaushal11, I think it's best if you post this on the [API repository](https://github.com/covid19india/api/issues). We're only tracking website issues over here.
