### ISSUE TITLE
Patient Recovered Data

### ISSUE THREAD

**Issue by muniramotorwala** [covid19india/covid19india.github.io#738]
I want you to please update the data of patients who have recovered so far and also the details of the patient from where the virus have infected them. This is could be a great help...

**Comment by JunaidBabu** [comment]
https://docs.google.com/spreadsheets/d/e/2PACX-1vSz8Qs1gE_IYpzlkFkCXGcL_BqR8hZieWVi-rphN1gfrO3H4lDtVZs4kd0C3P8Y9lhsT1rhoB-Q_cP4/pub?gid=200733542&single=true
