### ISSUE TITLE
Suggest for showing more visualization

### ISSUE THREAD

**Issue by sohamnandi77** [covid19india/covid19india.github.io#739]
Suggest for showing more visualization like 
- % of male/female/children affected
- age graph of which age group most affected

**Comment by nakradheer** [comment]
temporal analysis of each district from starting of march to get.when click on district name,chart should appear for that district.

**Comment by nakradheer** [comment]
I can try some advance excel analysis if you give source file.

**Comment by shuklaayush** [comment]
Seems to be have been addressed in Deep Dive
