### ISSUE TITLE
Show nearest essentials on state page

### ISSUE THREAD

**Issue by ketank1000** [covid19india/covid19india.github.io#741]
The data given over here [here](https://docs.google.com/spreadsheets/u/1/d/e/2PACX-1vShWjNeNn8n0hen_5KIWQhq_RLCq4Obn23SUzRSAT5fKCQgOZuZnWe57g79elkwum2zavntG_GSawDM/pubhtml?gid=1775152218&single=true) is perfect
We need a page which will plot this data on map so the people open the map and root to nearest lab or ward unit. it will be very help full to see this data

**Comment by Manjukb** [comment]
@ketank1000 how to download the spread sheet ??

**Comment by ketank1000** [comment]
I dont know who maintains the sheet, but i can see very useful data over there.

I can see 2 way over here:
Case 1:
    - Download the file on the server side.
    - Parse the file and add it in our own database
    - we have to schedule this for everyday

Case 2:
    - Download the file on the client side.
    - Parse the the data and then directly plot it on the map

**Comment by Manjukb** [comment]
looks  they already have parsed  data here https://github.com/covid19india/api/blob/master/resources/resources.json  not sure its exposed ?? @jeremyphilemon

**Comment by sudevschiz** [comment]
This data is exposed through https://api.covid19india.org/resources/resources.json

However, the question whether we should have this view should be looked at by @nikita-11 and @sama007

**Comment by jeremyphilemon** [comment]
Closing in favor of #848
