### ISSUE TITLE
Show percentage of recovered patients column

### ISSUE THREAD

**Issue by hLokre** [covid19india/covid19india.github.io#744]
**Problem**
I would like to see percentage of patients in individual states/districts that have recovered. A percentage of people recovered will be a good indicator on how individual states or districts are responding.

Ex: 312 total cases 32 recovered. 
Percentage column would be: **10.25%**  (32/312 *100 rounded to two decimal places)

**Solution**
A column to show percentage of recovered patient.

**Alternatives**
Sorting based on number of patients recovered, mentally calculate the percentage but it's obviously error prone/time consuming and unsorted.

**Comment by sudevschiz** [comment]
Potentially could be added to statewise view.
@jeremyphilemon

**Comment by jeremyphilemon** [comment]
Closed in favor of #1496
