### ISSUE TITLE
Demographics blocks modal issue

### ISSUE THREAD

**Issue by denvamsi** [covid19india/covid19india.github.io#746]
**Describe the bug**
It's an amazing feature though, When we click on any patient ID, the whole website getting stretched, Seems small, But it will better if we fix it :)
**To Reproduce**

1. Go to 'Demographics.'
2. Click on 'Click on Patient ID'
3. Scroll down to 'Observe Blocks and Modal Background'

**Screenshots**
Check the below presentation

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/38683119/78628888-314f9680-78b3-11ea-8855-2431724e47db.gif)

**Desktop (please complete the following information):**

- OS: [Windows 10]
- Browser [All Major Browsers]

**Additional context**
Hope you can sort this out and i suggest you to add feature to close popup by clicking anywhere outside of the modal :) That way we can check them fastly. 

Thanks & Regards,
Vamsi

**Comment by jeremyphilemon** [comment]
Thanks for filing the issue :)

@Binu42 saw your PR a couple of days regarding the modal fix, can you help me fix that? I'll have it assigned to you!

**Comment by denvamsi** [comment]
#606 This is the PR :) Can you please help it @binu42

**Comment by Binu42** [comment]
> Thanks for filing the issue :)
> 
> @Binu42 saw your PR a couple of days regarding the modal fix, can you help me fix that? I'll have it assigned to you!

ya sure, assign it to me. i started working on it.
