### ISSUE TITLE
Why not style dropdowns on the Demographics and Fix the Description :)

### ISSUE THREAD

**Issue by denvamsi** [covid19india/covid19india.github.io#747]
**Is your feature request related to a problem? Please describe.**
No it is not, But a sweet styling :)

**Describe the solution you'd like**
The website has a whole new level of UI, But on the select dropdown styling is not good and didn't matched at all:)

**Describe alternatives you've considered**
I have written some CSS code, I know you can write more better :)

![image](https://user-images.githubusercontent.com/38683119/78630569-b177fb00-78b7-11ea-890c-534daa2f0525.png)

My CSS Code :
`select {
    background-color: #babbbc;
    cursor: pointer;
    min-height: 1em;
    outline: 0;
    border: none;
    vertical-align: baseline;
    background: #e0e1e2 none;
    color: rgba(0,0,0,.6);
    font-family: Lato,"Helvetica Neue",Arial,Helvetica,sans-serif;
    padding: 0.8em 1em;
    font-weight: 700;
    line-height: 1em;
    font-style: normal;
    text-align: center;
    text-decoration: none;
    border-radius: 0.3rem;
    user-select: none;
    transition: opacity .1s ease,background-color .1s ease,color .1s ease,box-shadow .1s ease,background .1s ease;
    -webkit-tap-highlight-color: transparent;
}
select {
    width: 10rem;
    margin-right: 0.25rem;
}`

**Fix for Description**
![image](https://user-images.githubusercontent.com/38683119/78630686-09166680-78b8-11ea-9782-d8a0e4eeaa7c.png)

Can you please try making like this, so it looks good on visit instead of scrolling and we can understand more better :)

Thanks & Regards,
Vamsi

**Comment by KrishnaPravin** [comment]
@bee-rickey what the plan for #877 👆?
