### ISSUE TITLE
Deaths in hp

### ISSUE THREAD

**Issue by ridiis** [covid19india/covid19india.github.io#748]
The no of deaths in hp is 1 and the no of recovered is 2
And active cases are 25
3 jamatis from una
12 others una
1 from kangra 
3 Solan 
4 chamba
Do check and update

**Comment by KrishnaPravin** [comment]
@ridiis please use [this form](https://docs.google.com/forms/d/1HVXi3-0ckxGTS81yAN1RmgrVnvg9cg2pyPTuPgBeVEo) to report cases
https://docs.google.com/forms/d/1HVXi3-0ckxGTS81yAN1RmgrVnvg9cg2pyPTuPgBeVEo
