### ISSUE TITLE
Average growth in percentage

### ISSUE THREAD

**Issue by kiku511** [covid19india/covid19india.github.io#749]
**Is your feature request related to a problem? Please describe.**
This is a feature request related to the graphs right under the map. 

**Describe the solution you'd like**
I think another interesting metric is to see what the average growth rate is in new cases as compared to previous day, previous week and previous X days. This is inspired from a visualization provided by [91-divoc](http://91-divoc.com/pages/covid-visualization/). Hovering over every data point gives you an idea of what the average growth has been (see stats about the selected data point for Washington). This is especially helpful when you are trying to evaluate the situation to see if the curve is "flattening". This is essentially the average slope in the past X days.
![image](https://user-images.githubusercontent.com/22063646/78638435-21a76200-7861-11ea-9845-fb2dd19d86b8.png)

**Describe alternatives you've considered**
An alternative could be just a text field somewhere that would report the average growth rate for today but that would not show the historical trend for the numbers.

**Additional context**
Tag me for more information or mockups. I can work on this feature if required.
This could be related to #464.

**Comment by anuragsetia** [comment]
Is someone working on this? I had a similar idea of representing daily growth rate in terms of percentage. Attached is an example based on data. This helps get a real picture of how fast the disease is spreading.

I am willing to take this up as well

![12-Apr](https://user-images.githubusercontent.com/15847056/79120261-219ee900-7db0-11ea-8619-8249caa177ca.png)

**Comment by jeremyphilemon** [comment]
Closed in favor of #1496
