### ISSUE TITLE
Provide the data in CSV files for predictive analysis

### ISSUE THREAD

**Issue by amita-kapoor** [covid19india/covid19india.github.io#75]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by amita-kapoor** [comment]
It would be good if you can add the Google sheets as csv files as well. Also if symptoms can be collected. This will help in predictive analysis.

**Comment by jeremyphilemon** [comment]
Hey, thanks for raising this! Isn't it possible to export the sheets as a .csv file currently?

**Comment by jeremyphilemon** [comment]
Added in #661
