### ISSUE TITLE
2 Confirmed case found in Mathura District UP but not added into report.

### ISSUE THREAD

**Issue by guptadev** [covid19india/covid19india.github.io#750]
**Describe the bug**
While clicking the Uttar Pradesh state drop-down no data found for Mathura district.

**To Reproduce**

1. Go to '...' **https://www.covid19india.org/**
2. Click on '....' UTTAR PRADESH

**Expected behavior**
Mathura District data should be shown.

**Screenshots**

![image](https://user-images.githubusercontent.com/15716246/78639466-a4fd9d80-78cb-11ea-95bd-2006c1fecdd6.png)

![image](https://user-images.githubusercontent.com/15716246/78639641-f27a0a80-78cb-11ea-8c36-55ddad27f731.png)

Please find the below sources.
https://epaper.amarujala.com/mathura/20200407/01.html?format=img&ed_code=mathura

https://epaper.jagran.com/epaper/07-apr-2020-198-mathura-edition-mathura-page-3.html

**Comment by jeremyphilemon** [comment]
Thanks!

**Comment by guptadev** [comment]
Thanks for your update.
