### ISSUE TITLE
Add growth factor

### ISSUE THREAD

**Issue by kiranreddysn** [covid19india/covid19india.github.io#751]
Try to add another graph for Growth factor

**Comment by sudevschiz** [comment]
What do you mean by growth factor? Can you provide more details and an example?

**Comment by kiranreddysn** [comment]
Growth Factor = Todays' new cases / Yesterday's new cases

Example : =783 / 500 = 1.566

**Comment by sudevschiz** [comment]
This could be part of the new state page that we are creating. Will keep in mind. Thank you!

**Comment by jeremyphilemon** [comment]
Closed in favor of #1496
