### ISSUE TITLE
Duplicate Nationality 

### ISSUE THREAD

**Issue by anuragguptanbmc** [covid19india/covid19india.github.io#754]
**The bug**
In the Nationality Donut chart, you can see two Indian and India.

**To Reproduce**
https://www.covid19india.org/deepdive
look for patient nationality chart.

**Expected behavior**
Indian should be merged in India nationality.

**Screenshots**
![Bug_Covid19_Nationality](https://user-images.githubusercontent.com/36069918/78645320-ff4f2c00-78d4-11ea-949a-04c2fca545a4.png)

**Comment by s-naveen** [comment]
Fixed.
