### ISSUE TITLE
PWA with offline support

### ISSUE THREAD

**Issue by vamshi9666** [covid19india/covid19india.github.io#758]
**Is your feature request related to a problem? Please describe.**
It would be better to make this into PWA for mobile users. so that they dont need to open browser everytime
**Describe the solution you'd like**
To use workbox for enabling offline support.

**Describe alternatives you've considered**
Minimum is to just have a icon for homescreen without offline support

**Additional context**
mobile users can just open app from their home screen and for any updates, we can send a push notification

**Comment by sudevschiz** [comment]
Personally, I feel it's quite unnecessary. This would involve a pop up or a request to add to home page? Bad UX, I would say. 

Will keep the issue open for others to vote.

**Comment by tannakartikey** [comment]
I was also not in favor of this but we have got 3 issues asking for this and it seems many people are checking the website multiple times a day. So upvoting!

https://github.com/covid19india/covid19india-react/issues/637
https://github.com/covid19india/covid19india-react/issues/1121

**Comment by jeremyphilemon** [comment]
Closing in favor of #1322
