### ISSUE TITLE
thoothukudi map selection is showing zero always

### ISSUE THREAD

**Issue by vasanth-rajan** [covid19india/covid19india.github.io#760]
table is showing correct figures , where as it doesn't match with the value above map

**Comment by vasanth-rajan** [comment]
<img width="1447" alt="Screenshot 2020-04-07 at 4 49 41 PM" src="https://user-images.githubusercontent.com/10737996/78663513-dc7e4100-78ef-11ea-87bd-ff231a0e2250.png">

Attached the screenshot

**Comment by shuklaayush** [comment]
@vasanth3045 Good catch. It's because of the different spellings (extra 'k') in the table and the map.

**Comment by Arusara** [comment]
i would like to work this one

**Comment by sudevschiz** [comment]
Marking @guneetnarula to the conversation.

**Comment by guneetnarula** [comment]
Should be resolved by the upcoming Tamil Nadu json in #413

**Comment by Zindra** [comment]
Need fix this below API : 
https://api.covid19india.org/state_district_wise.json
