### ISSUE TITLE
Broken css on mobile

### ISSUE THREAD

**Issue by radiohertz** [covid19india/covid19india.github.io#765]
**Describe the bug**
Broken css on mobile.

**To Reproduce**

1. Go to the site on Mobile

**Screenshots**

**Smartphone (please complete the following information):**

- Device: Moto G6
- OS: Android 9
- Browser Chrome

**Additional context**

**Comment by DhiralKaniya** [comment]
Same experience with Google Chrome Web also.

Link:- https://www.covid19india.org/

OS:- Mac 
Chrome version:- 80.0.3987.163

<img width="1680" alt="Screenshot 2020-04-07 at 8 01 34 PM" src="https://user-images.githubusercontent.com/21332852/78681700-b31ede80-790a-11ea-9b35-a8952495efe1.png">

**Comment by karankiri** [comment]
@DhiralKaniya @davejon1337 It's working for me now. Can you check?

**Comment by radiohertz** [comment]
Can confirm it's working.
