### ISSUE TITLE
Demographics filter is not working

### ISSUE THREAD

**Issue by userhasnoname0** [covid19india/covid19india.github.io#771]
**Describe the bug**
Demographics filter is not working

**To Reproduce**

1. Go to demographics
2. Click on states and city

**Expected behavior**
To show the filtered data

**Screenshots**
![image](https://user-images.githubusercontent.com/62875345/78691308-17936b00-7916-11ea-9ab5-2116ac929f49.png)

![image](https://user-images.githubusercontent.com/62875345/78691191-fcc0f680-7915-11ea-80bb-bae6e6a03317.png)

**Desktop (please complete the following information):**
Desktop
- OS: [e.g. iOS] windows 7
- Browser [e.g. chrome, safari] chrome

**Smartphone (please complete the following information):**
not tested yet.
- Device: [e.g. iPhone6] Mi A3
- OS: [e.g. iOS8.1] Android
- Browser [e.g. stock browser, safari] Chrome

Screenshot

![demographics_issue](https://user-images.githubusercontent.com/62875345/78691915-cb94f600-7916-11ea-8470-b3288c786768.jpeg)

**Additional context**

**Comment by kiku511** [comment]
I think it breaks when there are no cases in a particular area on a particular date. When I go through the case you provided, I saw that there were no reported cases on 7th April (till around 5 mins ago) but the date is still available in the date selector. When you select it, the patients component does not re-render as there are no updated cases for the day.

**Possible solution**
- Edit the dropdown for dates based on the areas selected.
- Show messaging for no patients on this day

**Comment by userhasnoname0** [comment]
Hi @kiku511 ,

Today and yesterday itself i checked from mobile, it is showing sorted data even when not selected the date.
Reference: 
![Screenshot_20200408-112027](https://user-images.githubusercontent.com/62875345/78749090-29fbbc00-798b-11ea-8694-afbf7e663656.png)

**Comment by sudevschiz** [comment]
https://github.com/covid19india/covid19india-react/issues/771

**Comment by srikoushik** [comment]
@userhasnoname0 Are those the reproducing steps? Is this specific to data?

**Comment by jeremyphilemon** [comment]
@srikoushik The filters seem to be working fine now, I think it must've been fixed in between patches, thanks :)
