### ISSUE TITLE
"Thoothukkudi" district under TamilNadu state under the table and map are mismatched

### ISSUE THREAD

**Issue by amrishkhan05** [covid19india/covid19india.github.io#773]
**Describe the bug**
the district thoothukkudi is misspelled somewhere either under the table or under the map which causes 
**To Reproduce**

1. Go to 'https://www.covid19india.org/'
2. Click on 'state tamilnadu and compare the table with state map '
3. we will find the district thoothukudi mismatching in data

**Expected behavior**

**Screenshots**
![covid19bug](https://user-images.githubusercontent.com/24294357/78693718-452de380-7919-11ea-8d81-11b5b36b78bb.png)

**Desktop (please complete the following information):**

- OS: [e.g. Windows 10]

**Comment by shuklaayush** [comment]
Duplicates #760

**Comment by amrishkhan05** [comment]
@shuklaayush just saw #760 thanks for the update

**Comment by amrishkhan05** [comment]
Issue still exists @shuklaayush
