### ISSUE TITLE
 NPM install is getting failed after clone.

### ISSUE THREAD

**Issue by Vaibhav2812** [covid19india/covid19india.github.io#778]
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno ENOENT
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/srowhani/gonzales-pe.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\346043\AppData\Roaming\npm-cache\_logs\2020-04-07T18_36_32_303Z-debug.log

- node
  12.16.1
-npm
  6.13.4

**Comment by shuklaayush** [comment]
It's an issue with git. Check if it's properly installed by running ``` git  --version ``` in ```cmd```.

**Comment by aashish-chaubey** [comment]
@Vaibhav2812  I faced the same issue once!

As @shuklaayush pointed out, improper installation of git could be the primary reason.

Else, this may be a `node-gyp issue` not being able to find the file. Could you please try to reinstall Node if there is no hard dependency on your local version in any of your projects?

**Comment by jeremyphilemon** [comment]
@Vaibhav2812 Did it work?

**Comment by Vaibhav2812** [comment]
@shuklaayush @aashish-chaubey @jeremyphilemon 
 
 it's  problem with git.  now working fine. closing this issue.
  Thanks.
