### ISSUE TITLE
Collapsed navbar for mobile

### ISSUE THREAD

**Issue by discountedcookie** [covid19india/covid19india.github.io#779]
**Is your feature request related to a problem? Please describe.**
After adding new items to the navbar, it doesn't fit anymore on mobile.

**Describe the solution you'd like**
A collapsed navbar, with an activator button, which opens a list with all the items.

**Describe alternatives you've considered**
Scrollable navbar? May be harder to use.

**Additional context**
![screenshot](https://user-images.githubusercontent.com/509463/78711955-774d3e80-7935-11ea-85f6-12193c84c0d3.png)

I can open a pull request with that if the issue will be accepted.

**Comment by shubh0107** [comment]
Hey @jeremyphilemon , maybe I can take this up.

**Comment by jeremyphilemon** [comment]
Closed by #790
