### ISSUE TITLE
PWA | Add to Home Screen Support

### ISSUE THREAD

**Issue by kdqed** [covid19india/covid19india.github.io#78]
Can we include Add to Home Screen support for Chrome on Android?

Just went through the public folder on the source code and realized we need to a service worker script and include bigger icons in the manifest.

**Comment by sangamesh1439** [comment]
@kdnanmaga : I am able to add to home screen in android. Please find below screenshot.
![Screenshot_20200325-001907_Chrome](https://user-images.githubusercontent.com/12668386/77511565-91aff400-6e2e-11ea-94a9-9c56cf188bca.jpg)

**Comment by kdqed** [comment]
Yes, but new users are not getting an automatic prompt to do so when they visit the site.

**Comment by sangamesh1439** [comment]
Boss, requirement about having a "prompt" is not where mentioned in your issue description. Manually still we can do. Do you suggest a feature to show prompt ?

**Comment by kdqed** [comment]
According to PWA specification the prompt should appear automatically without us manually having to do it. I'm suggesting we implement that.

**Comment by vrajeshkanna** [comment]
PR #122 raised for this issue

**Comment by vrajeshkanna** [comment]
Also as file names are hashed. so we need not worry about cache
