### ISSUE TITLE
Date mentioned in the "Updates" section is non-intuitive

### ISSUE THREAD

**Issue by sudevschiz** [covid19india/covid19india.github.io#781]
**Describe the bug**
Update section has a date mentioned. Does it mean that all the updates are for that date?
If that is the case, there could be confusion in the news card below, because the time in that seems to be for next day?

![image](https://user-images.githubusercontent.com/4298868/78732967-0df21d80-797f-11ea-91f1-993095743aef.png)

Also, unsure when that date will change.

**Expected behavior**
1. Mention something like "Updates for 8th Apr" ?
2. Or, we can only show the updates that are part of the date shown above?
3. Hijacking this issue to request one more feature : Can we make add a slowly blinking beacon 🔵to make the updates more responsive? (However, slow enough so that it doesn't look like an Web1.0 site :) )

**Comment by JunaidBabu** [comment]
Why not remove the date field itself.

Just show "Updates" and below that the card with relative time.

**Comment by userhasnoname0** [comment]
> Why not remove the date field itself.
> 
> Just show "Updates" and below that the card with relative time.

Agrees with @JunaidBabu . Moreover it should come on the top for better readability, mentioned in #777

**Comment by BhaveshSGupta** [comment]
> 
> 
> Why not remove the date field itself.
> 
> Just show "Updates" and below that the card with relative time.

Or we could date with time, something like updates till 8 April 11:00 am IST
So that if someone keeps tab through the day they are viewing an old instance of data.

For better visibility we could add time and in small text size besides of Updates.

**Comment by userhasnoname0** [comment]
@BhaveshSGupta @sudevschiz  as individual update log times we can see, in that case time besides date will be over information. Rather than, showing in each and every log like, "about four hours ago", we can show the original timings of update log.

**Comment by userhasnoname0** [comment]
@sudevschiz 

Will this below one be ok?

![image](https://user-images.githubusercontent.com/62875345/78762918-24f63700-79a2-11ea-9268-443d0a05d448.png)

**Comment by sudevschiz** [comment]
@userhasnoname0 No. I would prefer Updates to be in its current location. 

About the Date field, I echo with @JunaidBabu ,we should just remove that date and keep a relative time on the cards. 

Opening this issue for that behaviour.

**Comment by srikoushik** [comment]
@sudevschiz Can you assign this to me? I can take this.

**Comment by jeremyphilemon** [comment]
Patched.
