### ISSUE TITLE
Pimpri Chinchwad shows up twice in city dropdown 

### ISSUE THREAD

**Issue by aman4512** [covid19india/covid19india.github.io#782]
**Describe the bug**
Pimpri Chinchwad shows up twice in city dropdown when Maharashtra state and Pune district are selected

**To Reproduce**
1. Go to Demographics
2. Select Maharashtra in the state dropdown
3. Select Pune in the district dropdown
4. See error (Pimpri Chinchwad is visible twice, once as Pimpri Chinchwad and once as Pimpri-Chinchwad)

**Expected behavior**
There should only one instance of every city

**Screenshots**
![image](https://user-images.githubusercontent.com/43100283/78738561-cadc7e00-796f-11ea-8beb-4a24f4723f23.png)

**Desktop:**

- OS: Windows 10 1909
- Browser Firefox
- Version 74.0.1

**Comment by shrisha-h** [comment]
This looks like an issue with the raw_data.json where Pimpri Chinchwad is present only once and Pimpri-Chinchwad is present elsewhere.

**Comment by bee-rickey** [comment]
Issue with sheet entry. Fixed.
