### ISSUE TITLE
Clicking outside the modal in `Demographics` should close it

### ISSUE THREAD

**Issue by DarkPrince304** [covid19india/covid19india.github.io#784]
**Is your feature request related to a problem? Please describe.**
Not really, it's just a UX thing. While using the website I felt like clicking outside the modal should also close it

**Describe the solution you'd like**
- Go to `Demographics`
- Click on any Patient ID
- Modal Opens up
- Clicking outside the Modal should close it

**Additional context**
I would like to work on it if possible! :)

**Comment by Binu42** [comment]
> **Is your feature request related to a problem? Please describe.**
> Not really, it's just a UX thing. While using the website I felt like clicking outside the modal should also close it
> 
> **Describe the solution you'd like**
> 
> * Go to `Demographics`
> * Click on any Patient ID
> * Modal Opens up
> * Clicking outside the Modal should close it
> 
> **Additional context**
> I would like to work on it if possible! :)

it's already solved here #753

**Comment by jeremyphilemon** [comment]
Closed by #753
