### ISSUE TITLE
'Districts Unknown ...' text overlaps with legend

### ISSUE THREAD

**Issue by shuklaayush** [covid19india/covid19india.github.io#785]
**To Reproduce**
On phone, 
1. Go to the India map
2. Double tap Madhya Pradesh to open district view

**Screenshots**
![image](https://user-images.githubusercontent.com/27727946/78750417-cfb02a80-798d-11ea-8aa3-ee09a490b90c.png)

**Comment by ajwad-shaikh** [comment]
@shuklaayush would like to take this up!

I will send in a PR by EOD

Seems simple enough to getting started here 

Thanks, please assign the issue to me :)
