### ISSUE TITLE
Duplicate like (Hatras , Hathras) District Name in Uttar Pradesh . Only one district in Uttar Pradesh i.e Hatharas  which is correct 

### ISSUE THREAD

**Issue by guptadev** [covid19india/covid19india.github.io#786]
**Describe the bug**
Only one District in Uttar Pradesh like Hathras which is correct. this issue is in Demographics page and report section

**To Reproduce**

1. Go to  https://www.covid19india.org/
2. Click on : Uttar Pradesh 
3. Scroll down to  Report  Hatras and Hathras Ditrict which should be one only like Hathras

**Expected behavior**
Only one should be shown in report and Demographics page.

**Screenshots**
![duplicate](https://user-images.githubusercontent.com/15716246/78751248-7812be80-798f-11ea-9f6b-694f99ee2f3f.png)

![image](https://user-images.githubusercontent.com/15716246/78751457-e9527180-798f-11ea-9212-841393fea853.png)

**Comment by bee-rickey** [comment]
Issue fixed on the sheet entry.
