### ISSUE TITLE
Andhra Pradesh cases not updated from the last 14 hrs

### ISSUE THREAD

**Issue by vamsineelam** [covid19india/covid19india.github.io#788]
**Describe the bug**
Andhra Pradesh cases not updated from the last 14 hrs.

**To Reproduce**

1. open https://www.covid19india.org/
2. Click Andhra Pradesh in the carona cases tracker table
3. can see the last updated time is 14hrs ago

**Expected behavior**
The update should be more frequent in sync with the state government bulletin.
Please check the correct source feed to update latest numbers and increase the update frequency.

**Screenshots**
![image](https://user-images.githubusercontent.com/63335695/78752308-71437600-79a6-11ea-832e-ee8d7d8d3b28.png)

**Desktop (please complete the following information):**

- Windows 7
- chrome
- Version 80.0.3987.149

**Additional context**
none

**Comment by kann87** [comment]
![Screen Shot 2020-04-08 at 11 35 16 PM](https://user-images.githubusercontent.com/63366780/78818021-a1643680-79f1-11ea-879a-dd229838274b.png)
Seems not an issue, Getting updated with latest data.
