### ISSUE TITLE
Demography for dates when no new cases have been detected.

### ISSUE THREAD

**Issue by jainprabhash** [covid19india/covid19india.github.io#789]
**Is your feature request related to a problem? Please describe.**
It seems like the website is not able to fetch the demographics data because data of the previously selected date is shown if there were no new cases on the selected date. 

**Describe the solution you'd like**
"No New Case" label can be shown instead of the data of the previously selected date.

**Additional context**
I would like to work on it, if possible.
![2f02c03a-3536-4614-8f2f-fc718d2f6533](https://user-images.githubusercontent.com/14644440/78752987-b78eda00-7992-11ea-99ef-5516d26dff43.png)

**Comment by pushkalsingh3** [comment]
I think this issue should be categorised as a bug not an enhancement.

**Comment by pushkalsingh3** [comment]
![Screenshot_20200409-155552](https://user-images.githubusercontent.com/21074557/78887195-0f097480-7a7d-11ea-88d6-e864bcffd3f4.jpg)

**Comment by pushkalsingh3** [comment]
Same issue found for mobile application as well.

**Comment by sudevschiz** [comment]
@jainprabhash Good catch. Assigning you.

**Comment by shubhamjain2998** [comment]
hey, @jainprabhash unassign yourself if you are not working on it, I would like to take this up.

**Comment by jainprabhash** [comment]
@shubhamjain2998 carry on. I've made some progress in it. let me know if you want to discuss.

**Comment by shubhamjain2998** [comment]
@jainprabhash Yes will definitely like to discuss it.

**Comment by shubhamjain2998** [comment]
I have also tried to do some changes, attached gif for that also.
just asking if I have understood the issue correctly and does this change solve it, please have a look and provide feedback, so I can rectify it. @jainprabhash @sudevschiz 
![demo](https://user-images.githubusercontent.com/30628775/79692934-97f68c00-8285-11ea-9349-75fe0e12c46c.gif)

EDIT - 
look at the form of an updated message.

![Screenshot from 2020-04-19 23-44-01](https://user-images.githubusercontent.com/30628775/79696055-e4e35e00-8297-11ea-847c-5a34c5d74738.png)

Should I make a PR of this?

**Comment by jainprabhash** [comment]
nice work @shubhamjain2998 . Nice thinking about using 'fetched'.
