### ISSUE TITLE
Is there any option to download the network?

### ISSUE THREAD

**Issue by DivyaLekha** [covid19india/covid19india.github.io#79]
Thanks for the great job!

Is there any option to download the networks/graphs?  (may be as a CSV or any other graph format like gml) It would have been extremely useful for analysts.

**Comment by turbanpride** [comment]
Is PDF or excel format download okey? I can contribute for that if its okey.

**Comment by turbanpride** [comment]
> Thanks for the great job!
> 
> Is there any option to download the networks/graphs? (may be as a CSV or any other graph format like gml) It would have been extremely useful for analysts.

Is PDF or excel format download okey? I can contribute for that if its okey.

**Comment by DivyaLekha** [comment]
Excel format will be good. Thank you!

**Comment by turbanpride** [comment]
> Excel format will be good. Thank you!

I have been working on the similar dashboards since 2.5 years. And its advised to download the webpage in pdf or ppt format to maintain the alignment of the webpage . Will try that as of now

**Comment by someshkar** [comment]
To be clear, you want to download the cluster map for offline viewing? 
(P.S. This is not the same as downloading an excel file for offline viewing.)

**Comment by miztiik** [comment]
If i can add my two cents to the discussion here, If data export option is being explored,
Can you make it into a json format.
You can further expand it through APIs, 
For example a the json extract can have keys for state wise data or date-wise data or generating clusters based on travel etc.

**Comment by unmesh-shukla** [comment]
> If i can add my two cents to the discussion here, If data export option is being explored,
> Can you make it into a json format.
> You can further expand it through APIs,
> For example a the json extract can have keys for state wise data or date-wise data or generating clusters based on travel etc.

Does this work -> [https://api.rootnet.in/](https://api.rootnet.in/) ??

**Comment by DivyaLekha** [comment]
> To be clear, you want to download the cluster map for offline viewing?
> (P.S. This is not the same as downloading an excel file for offline viewing.)

I would like to download the cluster map (network) as an adjacency list or matrix ( a graph). Yes, for offline analysis.; not only for viewing

**Comment by DivyaLekha** [comment]
> > If i can add my two cents to the discussion here, If data export option is being explored,
> > Can you make it into a json format.
> > You can further expand it through APIs,
> > For example a the json extract can have keys for state wise data or date-wise data or generating clusters based on travel etc.
> 
> Does this work -> https://api.rootnet.in/ ??

Yes! This is good. Thank you!
