### ISSUE TITLE
SATNA DISTRICT IS NOT IN MAHARASHTRA 

### ISSUE THREAD

**Issue by gh1914** [covid19india/covid19india.github.io#791]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kambleaa007** [comment]
@gh1914 What is `...` means actually, where to click?

**Comment by kambleaa007** [comment]
i clicked on > Maharashtra
then i can see Satna, actually it must be in Madhya Pradesh

**Comment by rohanharikr** [comment]
This is coming from the API.

**Comment by kambleaa007** [comment]
> This is coming from the API.

I dont think so, 
search for `SAT`, only single correct entry,
![image](https://user-images.githubusercontent.com/19818679/78767614-74d7fc80-79a8-11ea-8fe0-b2a746885140.png)
There is only one name in maharashtra.json file, search for `SAT`


Two for string `SA`
![image](https://user-images.githubusercontent.com/19818679/78767989-efa11780-79a8-11ea-8d4b-7623f3f25c3d.png)
Which is correct

**Comment by rohanharikr** [comment]
Will look into it.

**Comment by rohanharikr** [comment]
@kambleaa007 When I checked a while back, Satna district was coming in the Maharastra districtData. Now, they have removed "Satna" altogether; the reason why it's no longer being shown in the website. Prolly they are working on a fix in the back end.

**Comment by sudevschiz** [comment]
Yes. It was a wrong mapping between Satna and Satara districts. Fixed in the data. Thanks for reporting.

**Comment by kambleaa007** [comment]
@rohanharikr @sudevschiz  Thanks, Its Fixed
