### ISSUE TITLE
Text overlap in “Spread Trends” graph [Screenshot added]

### ISSUE THREAD

**Issue by akshat112** [covid19india/covid19india.github.io#792]
**Describe the bug**.
Name of the Month and date overlaps in the graph x-axis if we toggle 14D option.
**To Reproduce**

1. Go to home page
2. Scroll to the graphs and see the option of choosing time frame. [All, 1M, 14D]
3. Select 14D option
4. Check the x-axis labels of graphs

**Expected behavior**
Text should not overlap and name of the month should be slightly below the dates.

**Screenshots**
Refer the highlight part:
![B13071EF-105B-4236-9469-FC1225487854](https://user-images.githubusercontent.com/36301928/78763338-a352d900-79a2-11ea-9a17-384300c61f84.jpeg)

**Desktop (please complete the following information):**

- Not tested on Desktop

**Smartphone (please complete the following information):**

- Device: iPhone 7+
- OS: 13.3
- Browser: Safari

**Comment by shuklaayush** [comment]
Should be fixed in #776

**Comment by akshat112** [comment]
Great!
