### ISSUE TITLE
Can we create an API for the hotspot areas are declared in India and point them out in Map

### ISSUE THREAD

**Issue by userhasnoname0** [covid19india/covid19india.github.io#793]
We should create an API for the declared hotspot places over India and point them out in map, for as an information.

**Comment by bootleg-icarus** [comment]
The data is only available for districts. eg: We can know the reported cases in Jaipur as a whole but not more refined areas such as 'Malviya Nagar'. This would make sense too, seeing as making the information of the home of the infected public, could cause panic in that area.
If you can find a more refined data set, would love to make this enhancement

**Comment by sudevschiz** [comment]
Doubt if we will ever have this data. Closing.
