### ISSUE TITLE
Scroll inappropriate

### ISSUE THREAD

**Issue by kambleaa007** [covid19india/covid19india.github.io#794]
**Describe the bug**

**To Reproduce**

1. Go to 'Home'
2. Click on '> of any state'
3. Scroll down to 'more info'

DISTRICT | CONFIRMED gets Overwritten, after further scroll down which must not,

STATE/UT | CONFIRMED | ACTIVE | RECOVERED | DECEASED is still visible, which must not after scrolled further more down,

**Expected behavior**
District and Confirmed should be visible

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

1) Initial Scroll
![image](https://user-images.githubusercontent.com/19818679/78764285-f5482e80-79a3-11ea-9a00-eeea69771d2e.png)

2) Further More
![image](https://user-images.githubusercontent.com/19818679/78764324-02651d80-79a4-11ea-8a67-f9cec68ae6e0.png)

3) Its gets wrong here
![image](https://user-images.githubusercontent.com/19818679/78764350-0c871c00-79a4-11ea-80fd-cd5ee5954d6c.png)

**Comment by rohanharikr** [comment]
Working on this issue.
