### ISSUE TITLE
Add Weblinks

### ISSUE THREAD

**Issue by namanmodani** [covid19india/covid19india.github.io#8]
Append logos that link to our **Twitter** (already present), **Instagram** and **Facebook** handle in order to make it easier for the social team to propagate news and infographics in the general public.

**Comment by selva-ts** [comment]
It seems Insta not allowing to share from another website. Also, we can include LinkedIn.

**Comment by caffeinatedHuman** [comment]
Adding `LinkedIn` doesn't make sense to me.

**Comment by jeremyphilemon** [comment]
We're not actively working on supporting social icons on the frontpage at the moment.
