### ISSUE TITLE
Statewise trend graph

### ISSUE THREAD

**Issue by kracekumar** [covid19india/covid19india.github.io#80]
**Is your feature request related to a problem? Please describe.**

Now that half the states /UTs(13) have double-digit cases, it may be better time to add statewide trends in `SPREAD TRENDS` as cases are doubling every day in few states.

**Describe the solution you'd like**
A user can select the state from the list of states, the trend can be displayed rather than having a single map for each state.  By default, the highest state graph will be displayed.

**Additional context**
Along with issue #12, this may help in tracking statewide spreads.

**Comment by turbanpride** [comment]
We can use the bar charts in place of `SPREAD TREADS` and we can sort them in descending order. Also once we click the state, we can change it.

**Comment by JunaidBabu** [comment]
This is under consideration. We do not have the data ready for this rn

**Comment by sksavant** [comment]
Hi @JunaidBabu I've used raw data (using `dateannounced` and `state`) to make a graph for confirmed cases on state-by-state basis. Let me know if this is of interest 
You can see the demo at this preview : https://covid19india-react.sksavant.now.sh/ 

Obviously, the UX can be improved as per what's needed

**Comment by jeremyphilemon** [comment]
@sudevschiz @JunaidBabu ^ check this.

**Comment by sudevschiz** [comment]
@sksavant thanks for the PR.

Few questions

1. Plot only up to yesterday as today's values are incomplete?
2. Should this be part of the state map rather than under the table?
3. Some differentiation marker to separate it from All India values. ?

**Comment by sksavant** [comment]
@sudevschiz : 
I've created a PR with the changes (plot up to yesterday, plot under map)
