### ISSUE TITLE
Medical resources per district

### ISSUE THREAD

**Issue by mayankbhagya** [covid19india/covid19india.github.io#803]
**Is your feature request related to a problem? Please describe.**
Policy makers need a clear view of how many medical resources (beds, icus, ventilators, doctors) have been provisioned per district. If projections for a city cross the number of available resources, it is a red flag and proactive measures can be taken to save lives.

**Describe the solution you'd like**
Data for medical resources to be collected in google sheets based on various state govt measures. We've already started work there but need more hands. This'd be "capacity" data and would not change rapidly. Later, if this succeeds, we can aim for collecting everyday "utilisation" data actively.
This data to be exported to json periodically and hosted on covid api. React app to display the data in another tab, similar to home page.

**Additional context**
We've finished UI implementation and if approved, we can raise a PR as soon as the data looks ready. Currently calls a dummy API for data.
![medresources2](https://user-images.githubusercontent.com/557860/78788380-57675a80-79c9-11ea-9a45-c5b20976829e.png)

**Comment by sudevschiz** [comment]
We have already started collecting this information in "StateWise_Tested_Numbers_Data" sheet.

However, if this should be the way it should shown would need further discussion. @jeremyphilemon  @JunaidBabu

**Comment by sudevschiz** [comment]
Until have more coverage for this data across states, let's put this on hold.

**Comment by mayankbhagya** [comment]
is statewise_tested_numbers_data already exposed as an api?

**Comment by mayankbhagya** [comment]
besides, are there plans to incorporate projections anytime soon? that'll help in authorities getting a clear picture of what is expected demand and what is available supply of resources.

anywhere we can brainstorm?

**Comment by crypticrod** [comment]
> We have already started collecting this information in "StateWise_Tested_Numbers_Data" sheet.
> 
> However, if this should be the way it should shown would need further discussion. @jeremyphilemon @JunaidBabu

Can you please point me to the discussion on why the parameters to be tracked in the statewise_tested_numbers_data sheet were chosen? If a few more parameters become relevant, then recollecting them can be a difficult actitvity.

**Comment by crypticrod** [comment]
> Until have more coverage for this data across states, let's put this on hold.

I think that this is a very important feature and would vote to get this unhold. Would love to participate in further discussion.

**Comment by jeremyphilemon** [comment]
@mayankbhagya now that verifiable data is available through http://covidwarriors.gov.in, someone can get those numbers into the api so that we can display them on the website.

Keeping this on hold until someone adds this functionality over at the api repository.

**Comment by mayankbhagya** [comment]
Thanks Jeremy.

**Comment by jigar1101** [comment]
@mayankbhagya @sudevschiz @jeremyphilemon 

I have raised an issue [here](https://github.com/nic-delhi/AarogyaSetu_Android/issues/330) which I think can help us get the data, please give your views.

**Comment by sudevschiz** [comment]
From the track record of data availability till now, we have realized that this is not within our scope. Not denying its value add. Hope that there are some initiative from the government who would have the accessibility to this data.
