### ISSUE TITLE
Wrong Link of Sources

### ISSUE THREAD

**Issue by rahul-chavda** [covid19india/covid19india.github.io#804]
**Describe the bug**
patient information in https://www.covid19india.org/demographics having wrong links of source 2 and 3 (both are of source 1)

**To Reproduce**
open any patient information having 2 or 3 sources

**Expected behavior**
Should have the correct link to sources

**Screenshots**
source link of patient id 4921
![image](https://user-images.githubusercontent.com/12614320/78791589-b8912d00-79cd-11ea-8065-a519fdba58fb.png)

these are the line needs to be updated.
https://github.com/covid19india/covid19india-react/blob/master/src/components/patients.js#L363
https://github.com/covid19india/covid19india-react/blob/master/src/components/patients.js#L370

**Comment by sudevschiz** [comment]
Is it specific to P4921?

**Comment by rahul-chavda** [comment]
> Is it specific to P4921?

no its fow every patient details having multiple sources.

**Comment by faisal3389** [comment]
looks like this is a valid bug, I would like to pick this up if accepted
