### ISSUE TITLE
TAP OVER A DISTRICT FOR MORE DETAILS

### ISSUE THREAD

**Issue by sagarhodar** [covid19india/covid19india.github.io#805]
![IMG_20200408_190753](https://user-images.githubusercontent.com/16621185/78791656-ca72d000-79cd-11ea-9889-06bccb203117.jpg)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by shuklaayush** [comment]
Duplicates #675
