### ISSUE TITLE
Showing Data in Tabular Structure With Filter, Sort and Export Functionality

### ISSUE THREAD

**Issue by prabhakaryalla** [covid19india/covid19india.github.io#806]
**Describe the solution you'd like**
Displaying the data to show in Tabular structure using material-table library. 
It has built in features sorting, filtering, Export options. 
This makes users to see the data in detail.

**Additional context**
The below is the sample screenshot how the screen looks
![image](https://user-images.githubusercontent.com/42337157/78797258-15441600-79d5-11ea-92a0-dd687aba01b4.png)

**Comment by prabhakaryalla** [comment]
I can work on it, if the feature is accepted

**Comment by sudevschiz** [comment]
Are you referring to the State/District table? My opinion is that it's good as it's. 
Do you see any UX improvements?

**Comment by prabhakaryalla** [comment]
I  was referring to the Patent details.  In order to the see the patient details i need to go Patent Database where the user experience is not that great. 

So my Idea is to create a new Page which will show all the Patient Details with Search, Filter, Sort Options with below Fields
Patent Name
Age
Gender
State
District
Status

On click of Patient Name it will redirect to the source_1

**Comment by prabhakaryalla** [comment]
@sudevschiz  Any update ?

**Comment by prabhakaryalla** [comment]
![image](https://user-images.githubusercontent.com/42337157/79071255-6e26ed80-7cf8-11ea-9cf7-d777f7fc5387.png)

**Comment by jeremyphilemon** [comment]
Hey, thanks for the feature request. However, the tabular look is already achieved in the excel sheet whose link is provided in the footer. Closing this because it would be redundant and putting in a lot of effort into something that's already there :)
