### ISSUE TITLE
Wrong district name as Italians are showing in State Rajasthan & Haryana

### ISSUE THREAD

**Issue by gaurav7118** [covid19india/covid19india.github.io#808]
**Describe the bug**
There are wrong entries in districts as "Italians*" in the table of states "Rajasthan" & "Haryana".
**To Reproduce**

1. Go to State Rajasthan/Haryana and expand it
2. You will find entries like "Italians" which is clearly not a district.

**Screenshots**
![Bug_district](https://user-images.githubusercontent.com/46915693/78801110-dbc1d980-79d9-11ea-976f-ec029ab79dc7.png)

**Additional context**
Note: The data coming from api is wrong as you can check on  [https://api.covid19india.org/state_district_wise.json](url)

**Api Response**

`"Rajasthan": {
    "districtData": {
      "Italians*": {
        "confirmed": 2,
        "lastupdatedtime": "",
        "delta": {
          "confirmed": 0
        }
      },`

Similar case is present for Haryana also.

**Comment by sudevschiz** [comment]
This is by design. 

Maybe it's better to show it as "Others"? We will have to implement a feature to add a footnote then.

**Comment by gaurav7118** [comment]
@sudevschiz I think "Others"(under "**District**" column) can be used for **Indian** citizens if they are being confirmed in other districts but under district column we can not write any nationality because that doesn't make any sense and also creates confusion.

**Solution can be:**
To add one more row under total as "Total Confirmed Cases Including Foreign Nationals" and just add total confirmed foreign nationals in total confirmed cases of Indian Citizen.
![screenshot-www covid19india org-2020 04 08-23_07_01](https://user-images.githubusercontent.com/46915693/78816207-09fde400-79ef-11ea-8036-2104fe413013.png)

**Comment by aakashsbhatia2** [comment]
This looks like an error thats starting at the crowdsourced data in the raw_data tab 

![image](https://user-images.githubusercontent.com/55904554/78860239-b0ea7c00-79ff-11ea-929b-875e768a150e.png)

Correct me if I'm wrong please

**Comment by KrishnaPravin** [comment]
similar #822
