### ISSUE TITLE
City cluster view not working

### ISSUE THREAD

**Issue by zeffirara** [covid19india/covid19india.github.io#81]
**Describe the bug**
The city cluster view isn't working due to, I assume, the city Kasaragod added in both the Kerala state map as well as the Karnataka state map that appears in the logs. It's probably broken from [this data update](https://github.com/covid19india/api/commit/be26d953ed681e9a485beb00535f84b265eff399#diff-02a4c04ac53f38622fff9f5b603eb934R474) which incorrectly marked an unknown city as Kasaragod in Karnataka.

**To Reproduce**
1. Open clusters -> city view.
2. Check console for error.

**Screenshots**
- The error: 
![image](https://user-images.githubusercontent.com/6768571/77507127-b8e9de00-6e8d-11ea-9000-232e636997d0.png)
- What it seems to be coming from:
![image](https://user-images.githubusercontent.com/6768571/77507081-93f56b00-6e8d-11ea-9ce2-9079c7fb685d.png)
![image](https://user-images.githubusercontent.com/6768571/77507108-abccef00-6e8d-11ea-8f68-ebc00f5b0f00.png)

**Comment by vrajeshkanna** [comment]
Fixed as part of https://github.com/someshkar/covid19india-network/pull/54

**Comment by someshkar** [comment]
Yes, this got fixed. @jeremyphilemon you can close this.
