### ISSUE TITLE
Who are patient E0 and E1 in column "contractedfromwhichpatientsuspected" column in raw data ?

### ISSUE THREAD

**Issue by bodasheera** [covid19india/covid19india.github.io#810]
![image](https://user-images.githubusercontent.com/16837816/78808057-88a05480-79e2-11ea-94be-1c5d5110390d.png)

**Comment by sudevschiz** [comment]
E0 is the Delhi Congregation event
E1 is the Noida cluster

**Comment by bodasheera** [comment]
Thanks a lot
