### ISSUE TITLE
Embed Our-World-In-Data Tests per thousand people chart

### ISSUE THREAD

**Issue by vedadeepta** [covid19india/covid19india.github.io#811]
**Is your feature request related to a problem? Please describe.**
Test data not shown.

**Describe the solution you'd like**
[OurWorldInData](https://ourworldindata.org/grapher/full-list-cumulative-total-tests-per-million?time=45..76&country=IND) has "Total tests per thousand" graph. They maintain and update it. It can be embedded in the website.

**Describe alternatives you've considered**
No alternative as it would require us to extract data from icmr pdf releases which would be very cumbersome.

**Comment by bee-rickey** [comment]
Embedding some external feed which we have little control over or have little understanding of is not a good idea. Closing this.
