### ISSUE TITLE
Enabling crossfiltering on analytics graphs to make it more interactive

### ISSUE THREAD

**Issue by ninjakx** [covid19india/covid19india.github.io#812]
**Is your feature request related to a problem? Please describe.**
We can add cross filter which can help to see the graph based on other criteria. Like If a user click on female gender on piechart then all the graph displayed should be based on that gender.

**Describe the solution you'd like**
We will use frame works which allows crossfiltering. For that we will be using D3.js and Dc.js.

![Screenshot from 2020-04-08 23-08-37](https://user-images.githubusercontent.com/29797787/78815460-f140fe80-79ed-11ea-8c42-9b81464868df.png)

An interactive dashboard like this example:
http://bl.ocks.org/jun9/raw/5631952/

**Comment by sudevschiz** [comment]
Thanks for raising the issue.

Can you provide more details on which all graphs would come under the filters?
Also, what would be the placement, an overall UI?

**Comment by ninjakx** [comment]
except for Patient nationality, I can connect all 5. Like if a user click on the recovered graph from the total cases. It will show all the graphs related to recovered cases. Patient gender and age who recovered and also the states recovery line graph. 
Similarly, thing will be observed via all the other 4 graph.

But I can see there are 3 JSON files. first 2 and below two have the same JSON file. So they can be cross filtered easily. 

First three can be made to link each other by dates so cross-filtering can be done for them. the bottom two can be made to link with the above three but that's will be a bit tricky as they are different data, one is based on overall cases not considering gender, age. 

The JSON for age and gender looks like this. Through this, I can capture datewise data for state cases, total active/recovered/death cases. 
```
agebracket: "20"
backupnotes: "Student from Wuhan"
contractedfromwhichpatientsuspected: ""
currentstatus: "Recovered"
dateannounced: "30/01/2020"
detectedcity: "Thrissur"
detecteddistrict: "Thrissur"
detectedstate: "Kerala"
estimatedonsetdate: ""
gender: "F"
nationality: "India"
notes: "Travelled from Wuhan"
patientnumber: "1"
source1: "https://twitter.com/vijayanpinarayi/status/1222819465143832577"
source2: "https://weather.com/en-IN/india/news/news/2020-02-14-kerala-defeats-coronavirus-indias-three-covid-19-patients-successfully"
source3: ""
statecode: "KL"
statepatientnumber: "KL-TS-P1"
statuschangedate: "14/02/2020"
typeoftransmission: "Imported"
```

Integrating react with dc.js is tricky but possible to do so.

https://www.lighttag.io/blog/react-dc-js/

**Comment by sudevschiz** [comment]
@jeremyphilemon @JunaidBabu thoughts?

**Comment by jeremyphilemon** [comment]
We're currently in need of something similar to this, we're also looking forward to porting the deep dive to D3.js. @ninjakx would you like to help us with this?

**Comment by ninjakx** [comment]
@jeremyphilemon: I would like to. I have just started working on dc.js and d3.js 2-3 weeks ago. I don't know how much time it will take with this data. Also, I can't find state district historical data. Do you have api for that also? I can see the api for the current one.

**Comment by jeremyphilemon** [comment]
@ninjakx, thanks for the PR! We've unfortunately deprecated DeepDive at the moment, but we're working on a refactored version which will be out soon.

Also we'll be posting issues about the refactored deep dive soon, so please keep an eye out for that and your PRs will be very appreciated :)
