### ISSUE TITLE
Adding date range filter for the graphs.

### ISSUE THREAD

**Issue by ninjakx** [covid19india/covid19india.github.io#813]
**Is your feature request related to a problem? Please describe.**
We can add this to show graphs between two dates which will give more insight. 

**Describe the solution you'd like**
We will use pre built library to create date time range sliding filter. Based on range it will create a slice of data. All the graphs will be based on this sliced data.

**Additional context**
![Screenshot 2020-04-08 23:52:24](https://user-images.githubusercontent.com/29797787/78819544-0ae54480-79f4-11ea-802d-1968f4ae7a2e.png)

**Comment by bee-rickey** [comment]
A good option to have in the deep-dive section.

**Comment by vedadeepta** [comment]
Willing to give it a try, please assign.

**Comment by ninjakx** [comment]
I have already started there is some issue that has to be resolved then it's ready to go.

**Comment by vedadeepta** [comment]
NP, thanks for letting me know.

**Comment by jeremyphilemon** [comment]
Commented in #989
