### ISSUE TITLE
New Graph, New Cases Vs Total Cases

### ISSUE THREAD

**Issue by jhataka** [covid19india/covid19india.github.io#814]
Pl add a graph which I think will be more correct representative of state. Measure on y axis new cases vs on x axis total cases...this would give a better' comprehension as against the number of cases vs days.

A drop in new cases will bee seen immediately as against wait for trend to develop..

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by aruncodes** [comment]
I think OP is trying to explain this https://aatishb.com/covidtrends/ .

**Comment by bee-rickey** [comment]
Could be a good addition for deep dive

**Comment by jhataka** [comment]
> I think OP is trying to explain this https://aatishb.com/covidtrends/ .

Delighted to see that someone has already thought about it.

Exactly something like that I was thinking.  

Please consider adding it to deep dive or even on front page, if possible.

**Comment by shuklaayush** [comment]
Duplicates #349
