### ISSUE TITLE
Delhi map not working properly

### ISSUE THREAD

**Issue by chaharnishant11** [covid19india/covid19india.github.io#815]
The map of Delhi is not showing cases by districts.

1. Go to map of India.
2. Click on Delhi. 
3. See error
![Screenshot from 2020-04-09 00-50-00](https://user-images.githubusercontent.com/44123094/78824613-45eb7600-79fc-11ea-83a0-76d06bf86c72.png)

**Comment by KrishnaPravin** [comment]
@chaharnishant11 I guess it is working can you check again?
