### ISSUE TITLE
* in Haryana district wise data

### ISSUE THREAD

**Issue by nmnrna** [covid19india/covid19india.github.io#818]
**Describe the bug**
Haryana District wise list has * in front of Italians, but what this * signifies is not written

**To Reproduce**

1. Go to covid19india.org
2. Click on ">Haryana" from state table
3. Scroll down to Italians in the district wise data
4. See * in front of Italians

**Expected behavior**
An explanation of what the * in front of Italians signifies

**Comment by sudevschiz** [comment]
Yes. This info note need to be more intuitive. Will be fixed by #1041 .

Please follow that issue for updates. Closing this
