### ISSUE TITLE
Mismatch in the deaths delta count.

### ISSUE THREAD

**Issue by bee-rickey** [covid19india/covid19india.github.io#819]
![image](https://user-images.githubusercontent.com/63364562/78832885-a339f400-7a09-11ea-9ee7-9fd783516eac.png)
![image](https://user-images.githubusercontent.com/63364562/78832911-acc35c00-7a09-11ea-869e-f9db713caea3.png)

The top count mismatches with the bottom one.

**Comment by hemantpandey17** [comment]
Can take a look into it. Please assign

**Comment by shuklaayush** [comment]
@hemantpandey17 I think this might be because of the [API](https://api.covid19india.org/data.json). The top count is calculated from the 'statewise' entry, while the bottom graph takes the last value of 'cases_time_series'.

**Comment by hemantpandey17** [comment]
> @hemantpandey17 I think this might be because of the [API](https://api.covid19india.org/data.json). The top count is calculated from the 'statewise' entry, while the bottom graph takes the last value of 'cases_time_series'.

I think you right. Bottom graph takes data by using some validateCTS() function which reduces the count of records by 1. That means, it is taking number of cases till the day before.  Any idea what is that function for ? It was my first time hovering over code today.

And yes, the values are different as they are taken by two different sources

**Comment by hemantpandey17** [comment]
@jeremyphilemon Is there any particular reason of getting data from two different sources.
For time series graph, it is taking value from the last value of 'cases_time_series' and top levwl count is from 'statewise'.

Should we focus on changing the timeseries data source or getting value of 'cases_time_series' more frequently ?

**Comment by shuklaayush** [comment]
@hemantpandey17 That's because the bottom graph only plots data till the previous day. The counter on the top is the live data at any particular time. It could be handled in the code by looking at the date and timestamp, but this is what we have right now

**Comment by hemantpandey17** [comment]
> @hemantpandey17 That's because the bottom graph only plots data till the previous day. The counter on the top is the live data at any particular time

I am assuming that is part of the backend code. Correct me if I am wrong.
Curious to know, how frequent is data updated here : https://api.covid19india.org/data.json

**Comment by shuklaayush** [comment]
> I am assuming that is part of the backend code. Correct me if I am wrong.

No. its' there in our code. For the graphs, check out home.js -> timeseries.js. For counters, see home.js -> label.js

> Curious to know, how frequent is data updated here : https://api.covid19india.org/data.json

The API repository is here: https://github.com/covid19india/api. I think it's updated every 10mins or so.

**Comment by hemantpandey17** [comment]
> > I am assuming that is part of the backend code. Correct me if I am wrong.
> 
> 
> 
> No. its' there in our code. For the graphs, check out home.js -> timeseries.js. For counters, see home.js -> label.js
> 
> 
> 
> > Curious to know, how frequent is data updated here : https://api.covid19india.org/data.json
> 
> 
> 
> The API repository is here: https://github.com/covid19india/api. I think it's updated every 10mins or so.

Both the top and bottom are getting values from  https://api.covid19india.org/data.json. It is just response.data.statewise is updated more frequently than response.data.case_time_series.

**Comment by shuklaayush** [comment]
Fixed now
