### ISSUE TITLE
Hovering out of states in map doesn't change data for that top left panel.

### ISSUE THREAD

**Issue by turbanpride** [covid19india/covid19india.github.io#82]
Clearly, when we hover over a state in the map, the respective data is shown at the top left panel. But on hovering out of the state doesnt revert back the data in the top left panel to total. 

**To Reproduce**
1. Hover to any state in the map.
2. Check the changes on the top left panel of map component which shows data of hovered state.
3. Hover out of the state and the data at the panel remains same. 
![bug](https://user-images.githubusercontent.com/36756462/77507290-24cc4680-6e8e-11ea-99fa-e63c62b9abea.png)

**Expected behavior**
It should have shown the total data on the left top panel of map component. (refer the screenshot attached).

**Comment by sangamesh1439** [comment]
looking into the issue.

**Comment by turbanpride** [comment]
> looking into the issue.

I have solved the issue. commiting it now

**Comment by sangamesh1439** [comment]
@turbanpride : I have also resolved. https://github.com/covid19india/covid19india-react/pull/83

Sorry for duplicate work .

**Comment by shuklaayush** [comment]
I think resetting to state 1 doesn't make sense. Maybe have a total count by default. Thoughts?

**Comment by turbanpride** [comment]
> I think resetting to state 1 doesn't make sense. Maybe have a total count by default. Thoughts?

Well we already have an object containing total values. We just need to check for that object in mouseout handler and set the state as per that. That's what my solution was. I have shared the handler below

`const handleMouseout = (name) => {
    states.map((state, index) => {
      if (state.state.toLowerCase()==="total") {
        setState(state);
        setIndex(index);
      }
    });`

**Comment by sangamesh1439** [comment]
When app loads for first time, we are setting default state as state 1. API returns state list in decreasing order (More counts will be first state) .On MouserEnter we are changing state and onMouseLeave we should revert it. Thats why I am setting it to state 1. Please run the code and check the user expirence. Its looking good.

**Comment by arushibhat** [comment]
It might not be useful for the user to see the data getting reset to some state he's not intending to look at. As a use case i was thinking users can click state after state to compare the data for their own use case. it'll be difficult for the user to comprehend why the data is getting reset to some unkown state.
Thoughts...

**Comment by sangamesh1439** [comment]
In my opinion, first state has more number of corona counts. Thats why I was thinking to select that on mouseLeave . Let me know what exactly needs to do. I will do changes as required.

**Comment by arushibhat** [comment]
I understand.
Can we add a state compare feature instead of single state select. That way we can keep the default state as the most cases one and add your(user) state.
what do you think?
I am just thinking what users might be interested to know.

**Comment by sangamesh1439** [comment]
we should not do that, There is another PR which supports district level map analysis when user clicks on state.

**Comment by turbanpride** [comment]
I am not in a favour to highlight area with max cases because people should
see total cases as a default. And then they have the option to check per
region.

**Comment by sangamesh1439** [comment]
we already have option to show total cases.

**Comment by turbanpride** [comment]
Where?

**Comment by sangamesh1439** [comment]
![Screenshot 2020-03-25 at 2 45 03 AM](https://user-images.githubusercontent.com/12668386/77523244-af875400-6e42-11ea-9a36-023789606439.png)

**Comment by turbanpride** [comment]
Then for the first time rendering we are showing redundant data.

**Comment by sangamesh1439** [comment]
Boss, read all comments since morning. 2 times I explained. When app loads for first time, we are setting default state as state 1. API returns state list in decreasing order (More counts will be first state) .On MouserEnter we are changing state and onMouseLeave we should revert it. Thats why I am setting it to state 1. Please run the code and check the user expirence. Its looking good.

**Comment by turbanpride** [comment]
> Boss, read all comments since morning. 2 times I explained. When app loads for first time, we are setting default state as state 1. API returns state list in decreasing order (More counts will be first state) .On MouserEnter we are changing state and onMouseLeave we should revert it. Thats why I am setting it to state 1. Please run the code and check the user expirence. Its looking good.

To be very honest, i have been working on real time dashboards since 2.5 years. If ur showing highest cases by default, then u need to highlight the respective region. Else show total. Because ur not doing justice with the map component. This is not how functionalilty should work. After first render whever user hovers over any  region it gets highlighted and on hovering ur removing the highlight section.

**Comment by jeremyphilemon** [comment]
Really appreciate all the feedback and discussion here. The section is called statistics by state and we also have a neighboring section that displays the total, it wouldn't be nice if we have totals listed on may places at once, also looking at a state's stat (in this case we've chosen the highest to not have any bias) it'll hint the user to interact with the map to check out the stats for other states!

And once the mouse leaves the map, it's best we show the data that was last inspected!
