### ISSUE TITLE
Showing wrong district name  in Rajasthan

### ISSUE THREAD

**Issue by soninishank** [covid19india/covid19india.github.io#822]
<img width="551" alt="Screen Shot 2020-04-09 at 9 08 44 AM" src="https://user-images.githubusercontent.com/39820546/78855697-3db62980-7a42-11ea-8957-4dfc8a14085c.png">
There is no such district EVACUEES in Rajasthan

1. Open https://www.covid19india.org/
2. Choose Rajasthan state 
3. Then you can  **EVACUEES** district.

**Comment by soninishank** [comment]
There is one more field  i can see Italians . Is it a bug too. Please review it once in Rajasthan state .


<img width="1440" alt="Screen Shot 2020-04-09 at 9 20 30 AM" src="https://user-images.githubusercontent.com/39820546/78856259-e0bb7300-7a43-11ea-95de-7fcc73fcdd36.png">

**Comment by aakashsbhatia2** [comment]
This looks like incorrect entries in the crowdsourced patient database. It is showing up in the "Raw_data" section and hence as entries in 'state_district_wise.json'. 

![image](https://user-images.githubusercontent.com/55904554/78859502-8697bf00-79fd-11ea-8d6c-7f5c24859e1b.png)

**Comment by lokeshbansal76** [comment]
These are not belong to any particular district of rajasthan as these indians are evecuted form others countries & quarantined at Jodhpur & jaisalmer facilities.
![Screenshot_2020-04-10-00-31-58-989_com android chrome](https://user-images.githubusercontent.com/63422719/78931102-f8860c00-7ac2-11ea-892d-367e5cd4dec9.jpg)

**Comment by sudevschiz** [comment]
This intentionally mentioned so because the press bulletin also does the same and doesn't assign a district to these patients. We will try to make it more intuitive to understand that.
Closes #808
