### ISSUE TITLE
Search functionality in the table component

### ISSUE THREAD

**Issue by burlarajesh** [covid19india/covid19india.github.io#824]
I thought it would be a great idea if we can have a search functionality where we can filter by state names.

The screen looks like below:

![image](https://user-images.githubusercontent.com/10438863/78860524-0cdcf100-7a50-11ea-87f3-966dc5b46f6c.png)

**Comment by bee-rickey** [comment]
Since there are only 36 states, there's little usage for this. Closing as of now.
