### ISSUE TITLE
Graph of active cases

### ISSUE THREAD

**Issue by trilloc** [covid19india/covid19india.github.io#825]
Hi

Could you also add the graph of active cases along with the new/confirmed cases, recovered cases and deaths.

Thank you.
Rajesh

**Comment by acorreya** [comment]
I second this! Please add!

**Comment by Zindra** [comment]
Hey @trilloc , Is this what you are talking about ? SS attached.
![image](https://user-images.githubusercontent.com/30254595/78928079-a1ca0380-7abd-11ea-9101-8d82da0f3e1e.png)

If yes , please assign it to me.. I am trying to add that feature.

**Comment by acorreya** [comment]
@zindra This is what i was asking. I think this is what the OP wants too.

**Comment by Zindra** [comment]
Okay @acorreya , Is it possible for you to assign this ticket to me ? I am working on this.

**Comment by TheDominus** [comment]
![Capture](https://user-images.githubusercontent.com/21247346/78929577-49e0cc00-7ac0-11ea-92c7-94784fea695c.JPG)

I too was working on it some days back but I did some progress. But, you can continue the changes.

**Comment by acorreya** [comment]
@Zindra / @TheDominus , i am not very sure how i can assign this to you. I tried clicking a bit, but nothing works. Maybe you could guide?

**Comment by trilloc** [comment]
> Hey @trilloc , Is this what you are talking about ? SS attached.
> ![image](https://user-images.githubusercontent.com/30254595/78928079-a1ca0380-7abd-11ea-9101-8d82da0f3e1e.png)
> 
> If yes , please assign it to me.. I am trying to add that feature.

Hi .. thanks for accepting. how do I assign this to you.

Cheers
Rajesh

**Comment by vikkyomkar** [comment]
I will give it a try

**Comment by Zindra** [comment]
@jeremyphilemon can you please help us here to assign the ticket ?

**Comment by Zindra** [comment]
https://api.covid19india.org/data.json is not having the 'totalactive' data. @jeremyphilemon can you please help us here fixing this API.

**Comment by TheDominus** [comment]
@Zindra, I earlier raise a feature request for the same but it was declined as it id redundant. 
You can calculate the total active cases instead.
https://pastebin.com/YF7L3bVC

**Comment by Zindra** [comment]
Thanks much @TheDominus . This is how it is looking now.

![image](https://user-images.githubusercontent.com/30254595/79007410-bfa86e80-7b78-11ea-87c7-de8008f10fd7.png)

But doing like this we may encounter a Bug . See below :
shuklaayush commented 14 days ago
The numbers in brackets reflect the daily change where:
Active = Confirmed - Recovered - Deceased.

Right now, this is (18 - 17 - 2 = -1). Hence the negative value. Don't think this is a bug.

For deatils  =>**Please check Issue #226.**

**Comment by TheDominus** [comment]
@Zindra No, You won't as "-1" in the above calculates the daily increase in the active account which can be negative. 
Even it is very good that we see -ve values. -ve Values will show that we are defeating the disease.

In addition to it. Ping me if you need help with CSS for graph?

**Comment by Zindra** [comment]
@TheDominus  Yes , -1 can suggest that we are doing our best to stop the spread of the disease. 
Still I want you to please check #226 . They have closed it.

**Comment by dhruvsema4** [comment]
I have added the complete thing in PR #936, sorry I didn’t notice this thread.


https://github.com/covid19india/covid19india-react/pull/936

**Comment by iDhruv22** [comment]
I did a complete thing in PR #936, sorry I missed this thread. Moreover, I think issue #899 duplicate to #825.

**Comment by Zindra** [comment]
@iDhruv22 I see that your PR is not merged. Anyway not an issue if you want to work on the same.

**Comment by Zindra** [comment]
@TheDominus can you please ping me ?? need some help

**Comment by trilloc** [comment]
Looks like the pull request is not going through? Any possibility of bumping this up pls

**Comment by tannakartikey** [comment]
Hello, @trilloc 

Thank you for showing interest.

We are working on lots of fronts at once and there is quite a lot of activity going on so it might take us a while to get back to you.

Your patience is highly appreciated!

**Comment by trilloc** [comment]
Thank you very much team. Fantastic effort!👍🙏
