### ISSUE TITLE
Comparision of Worlds DAILY CASES to INDIA

### ISSUE THREAD

**Issue by yashsinghcs** [covid19india/covid19india.github.io#830]
This would provide a good view to the citizens of india that How good or bad they are doing from other powerfull countries . It could be a sence of motivation to all.

This could be done with a drop down Saying how well indians are doing on COVID-19 Crisis as compared to Worlds Out having more Facility but failing misserably.

btw:sorry for my bad English

**Comment by rishabh091** [comment]
I can do this.
It can be done like showing line graphs as the graphs we had seen earlier, those will be quite good at depicting how well we are performing as compared with the rest of the world.

**Comment by yashsinghcs** [comment]
if possible try that,
the grap line must be overlapped with total cases today with recovered and died people for different countries including india, which would allow highest extraction of info from least studying the data from the user's end.

**Comment by bee-rickey** [comment]
This is out of scope for our cause. Although a comparison could help, we do not have a reliable source which we can use to build this. Closing.
