### ISSUE TITLE
map the patient for visualisatation of chain

### ISSUE THREAD

**Issue by yashsinghcs** [covid19india/covid19india.github.io#832]
graphically map the patients ,area wise dipicting possible chain through which it spread .which will allow peple to know the affected people in thier area and and possibly notice the chain it could have spread. therefore maintaining the distance from suspected people.
also it would help people who are showing some symptoms to go in self qurantine if they are facing some symptoms and assume them to be somewhere in the chain

**Comment by bee-rickey** [comment]
Data provided by the state govts is not enough to carry this development out.
