### ISSUE TITLE
Share covidmaps link under helpful links section ?

### ISSUE THREAD

**Issue by Siddharth11** [covid19india/covid19india.github.io#837]
**Is your feature request related to a problem? Please describe.**
I'm part of a [small team](https://github.com/covid-maps), united by a [common cause](https://covidmaps.in/about) 🙂 
Our platform helps user find essential services by their location. The project is still in infancy (barely 2 weeks old), and we have already reached around 30k users globally. It would be great if you could share our platform under `Helpful Links` section. All our of code is open-sourced and data is crowd sourced too! 

**Describe the solution you'd like**
Adding [covidmaps.in](https://covidmaps.in/) link on [covid19india.org/links](https://www.covid19india.org/links), to extend our reach.

cc: @asanjeevrao @arjun27 @Sapeksha

**Comment by bee-rickey** [comment]
Have a look at this once? https://github.com/covid19india/covid19india-react/issues/848 Seems like the two of you can sync up.

**Comment by shuklaayush** [comment]
Closed due to inactivity.
