### ISSUE TITLE
Refresh button to update all the data

### ISSUE THREAD

**Issue by ameyasd007** [covid19india/covid19india.github.io#839]
**Is your feature request related to a problem? Please describe.**
I use the this website a lot. Usually I keep it open in one of the tabs of my browser. When I come back to this tab after few minutes or hours to check latest data, I still looking at the older data and I have to hit the refresh button which loads the entire page and I am just waiting for it to load.

**Describe the solution you'd like**
Let's add a refresh button at the top like this:
![image](https://user-images.githubusercontent.com/19249276/78882072-44aa5f80-7a75-11ea-911d-bcade946a7a9.png)
When this button is clicked, the latest data is fetched and chart, graphs are updated.

**Describe alternatives you've considered**
Instead of refresh button, we can also fetch the latest data after every few minutes (eg. every 20 minutes).
But this can cause unnecessary API calls if the web app is open is some tab and user don't close it. 

Please assign this to me if it is accepted.

**Comment by bee-rickey** [comment]
Will be taken up in the subsequent change.

**Comment by bee-rickey** [comment]
Reassigning. Please talk to @jeremyphilemon before you pick this up.

**Comment by jeremyphilemon** [comment]
Please refer to https://github.com/covid19india/covid19india-react/pull/711#issuecomment-617447680
