### ISSUE TITLE
fix text position on essentials page 

### ISSUE THREAD

**Issue by swapniltomake** [covid19india/covid19india.github.io#842]
**Describe the bug**

**To Reproduce**

1. Go to 'essentials page'
2. select state->city->category
3. click search button
4. Scroll down to 'pagination'

![Screenshot from 2020-04-09 15-34-48](https://user-images.githubusercontent.com/19332878/78885464-4e829180-7a7a-11ea-9e8f-72df4b136b46.png)

**suggetion**
add  `flex-direction: unset;`

> .pagination select {
>     margin: .7rem .7rem .2rem .1rem;
>     **flex-direction: unset;**
> }

**Comment by saberprashant** [comment]
Hi @sudevschiz @jeremyphilemon,
I can fix this one in a day. Should I take this?

**Comment by swapniltomake** [comment]
hi @sudevschiz, @jeremyphilemon  can i fix this. i want to contribute on this project for some bugfix.

**Comment by theviveksahu** [comment]
This will already be fixed in #877

**Comment by nikita-11** [comment]
@shuklaayush @swapniltomake Pagination has been removed. We can close this one too.
