### ISSUE TITLE
Typo in city name 'Ahmadnagar'

### ISSUE THREAD

**Issue by TauseefMalik** [covid19india/covid19india.github.io#845]
Description of PR
fixed spelling mistakes in cities -> 'Ahmadnagar' to 'Ahmednagar'
https://en.wikipedia.org/wiki/Ahmednagar

Type of PR

[✓] Bugfix
 New feature
Relevant Issues
Fixes #...

Checklist

[✓] Compiles and passes lint tests
[✓] Properly formatted
[✓] Tested on desktop
[✓] Tested on phone
Screenshots

**Comment by shuklaayush** [comment]
Refer to https://github.com/covid19india/covid19india-react/issues/662#issuecomment-609377552
