### ISSUE TITLE
Map Healthcare Facilities nearby

### ISSUE THREAD

**Issue by aswaathb** [covid19india/covid19india.github.io#848]
**Is your feature request related to a problem? Please describe.**
Show nearby hospitals on map.

**Describe the solution you'd like**
Show hospitals closest to me on the tracker page (by @ashish199820) which also shows the cases near me.

**Describe alternatives you've considered**
Current substitute of the essentials page?

**Additional context**
![HospitalsKNN](https://user-images.githubusercontent.com/25769767/78892907-45de8b00-7a7b-11ea-8ff4-2026bb463dd2.png)

(PS: screenshot taken using data from https://github.com/planemad/india_health_facilities/blob/master/map/public_health_facilities_nic.geojson , would need to change to a more relevant, upto date source from ICMR)

**Comment by sudevschiz** [comment]
Where would the data for this be available?
If it's available, a user-generated custom map on Google Maps solve this requirement?

**Comment by aswaathb** [comment]
Ive just modified the dataset. ICMR has a list of hospitals and private labs. heres a working version (with the rest of the elements stripped off)
aswaathb.github.io/covid19india-react

![knn_new](https://user-images.githubusercontent.com/25769767/78915998-dded6c00-7a9d-11ea-8f2d-d58fa41e8114.png)


Also only static maps are free via google maps. You need to pay for it beyond a certain point (only on web, not on mobile)

**Comment by bee-rickey** [comment]
This request seems like they already have the workflow setup: https://github.com/covid19india/covid19india-react/issues/837 Might be interesting to have a look at this once.

**Comment by Siddharth11** [comment]
Hi @aswaathb, our platform [covidmaps.in](https://covidmaps.in/) is solving a similar problem. We need developers, designers and content writers (for localization). You can also [contribute to it](https://github.com/covid-maps/covid-maps) :)

**Comment by aswaathb** [comment]
Thanks for the link @bee-rickey @Siddharth11 .

I'll try contribute where I can! :D

P.S. I think this project also has or is trying to implement a similar [feature](https://www.covid19india.org/essentials), it'd be great if everyone shared the data!

**Comment by jeremyphilemon** [comment]
Closed by #1383
