### ISSUE TITLE
Typo in DISTRICT name Thoothukkudi

### ISSUE THREAD

**Issue by rajeshkannanv** [covid19india/covid19india.github.io#849]
**Describe the bug**
Spelling mistakes in city name Thoothukkudi 
Count mismatch in District Map and District list Please find attached image 
Please change city name to **Thoothukudi** from Thoothukkudi

https://en.wikipedia.org/wiki/Thoothukudi

**To Reproduce**
1. Go to https://www.covid19india.org/  
2. Click on "TAMIL NADU" from state
3. Find the DISTRICT "Thoothukkudi"
4. Click/Hover on  "Thoothukudi" from right side map
5. See the confirmed count mismatch between the two records

**Expected behavior**
1. Go to https://www.covid19india.org/  
2. Click on "TAMIL NADU" from state
3. Find the DISTRICT "Thoothukkudi"
4. Click/Hover on  "Thoothukudi" from right side map
5. Confirmed Count should be same in map and the list

**Screenshots**
<img width="1024" alt="Screenshot 2020-04-09 at 5 19 11 PM" src="https://user-images.githubusercontent.com/5030459/78893056-34e84680-7a88-11ea-979c-5a5690e80382.png">

**Comment by srikanthlogic** [comment]
Will be fixed along #413

**Comment by shuklaayush** [comment]
Duplicates #760
