### ISSUE TITLE
Drop down menus don't follow ( on mobile devices) the website theme 

### ISSUE THREAD

**Issue by dpnkrpl** [covid19india/covid19india.github.io#852]
Drop down menus do not maintain the entire website theme.

**Comment by saberprashant** [comment]
Hi @sudevschiz @jeremyphilemon ,
I would like to work on this one.
I think that dropdown burger button can be made a little bigger and claiming, and the list background and text style can be made attractive just like the one we are using in tables.
With this, it will fit properly in the website theme.
If you want other additions too, you can tell me.

So, can I start working on this issue?

**Comment by KrishnaPravin** [comment]
#747 duplicate

**Comment by dpnkrpl** [comment]
@Binu42 does this PR style the drop down menus on mobile devices too? Latest update has fixed this issue for desktop version Only.
I'm still getting this .
![Screenshot_2020-04-10-08-08-30-912_com android chrome](https://user-images.githubusercontent.com/27947066/78958096-c09fb880-7b04-11ea-9435-9ee5d74acfc1.jpg)

**Comment by Binu42** [comment]
@jeremyphilemon `maintainer` have not merged it yet. @deep5050 ya, this PR is for all devices.
