### ISSUE TITLE
KARNATAKA state missing from Deep Dive Line graph

### ISSUE THREAD

**Issue by thecodegenie** [covid19india/covid19india.github.io#854]
The line graph in deep dive section was having Karnataka state a few days ago and now its missing. Might be a bug or an overlap with other states.

**Comment by sudevschiz** [comment]
Deep-dive tab needs serious upgrades. Making a user-friendly way to compare all the states in teh state daily graph would be one key thing Making it issue available for interested folks to pick up and work on!

**Comment by ninjakx** [comment]
@sudevschiz  Can't we have interactive dashboard like this one ?

![img](http://adilmoujahid.com/images/viz_demo.gif)

**Comment by RamaKrishnaKunda** [comment]
In States - Total Cases, showing all states(lines) at one place is looking clumsy, it is difficult to differentiate. Why can't we have a slider inside the card to select state. For showing all states together(as it is there now) we can give an option 'ALL'

**Comment by kousiksatish** [comment]
I have added a "Toggle Selection" button in #1003 fixing #836. That may make it more useable, when you want to compare only few states

**Comment by pradeepAtcodingmart** [comment]
You guys showing only the top 10 states so that's why Karnataka is not visible because it's in 11th place. I have two suggestions for this issue.
1)I can show the top 12 states so that Karnataka will be visible
2) or else, we can show the states which have the count of corona cases >150. 
NOTE : Showing all the states might be clumsy.
Suggest me the right one

**Comment by tannakartikey** [comment]
@ninjakx I suggest you create an issue with the Enhancement template with proper specifications to keep the discussions relevant.  And if the suggestion is accepted then we can assign you the task and let you submit the PR for the same.

**Comment by pradeepAtcodingmart** [comment]
I am saying about the above  issue (#854)

**Comment by drhadia** [comment]
i want to work on this, please assign this to me

**Comment by pradeepAtcodingmart** [comment]
@shuklaayush As we discussed in #1108 , I Made a PR

**Comment by jeremyphilemon** [comment]
Closing in favor of #812
