### ISSUE TITLE
Host Header Injection

### ISSUE THREAD

**Issue by inderpreetsinghips** [covid19india/covid19india.github.io#858]
**Describe the bug**
An attacker can manipulate the Host header as seen by the web application and cause the application to behave in unexpected ways.

Very often multiple websites are hosted on the same IP address. This is where the Host Header comes in. This header specifies which website should process the HTTP request. The web server uses the value of this header to dispatch the request to the specified website. Each website hosted on the same IP address is called a virtual host.

But what happens if we specify an invalid Host Header? If Apache receives an unrecognized Host Header, it passes it to the first virtual host defined in httpd.conf. Therefore, it's possible to send requests with arbitrary Host Headers to the first virtual host.

Another way to pass arbitrary Host headers is to use the X-Forwarded-Host Header. In some configurations, this header will rewrite the value of the Host header. Therefore it's possible to make a request like:

**To Reproduce**
Change the Host header's website name to another website. It will not verify and redirect to that website. Eg. bing.com

**Expected behavior**
REQUEST:
GET /static/css/ HTTP/1.1
**Host: www.bing.com**
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:74.0) Gecko/20100101 Firefox/74.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Connection: close
Cookie: _ga=GA1.2.1174409912.1586238617; _gid=GA1.2.1851037266.1586238617
Upgrade-Insecure-Requests: 1

RESPONSE:
HTTP/1.1 301 Moved Permanently
Connection: close
Content-Length: 162
Content-Type: text/html
Server: GitHub.com
**Location: https://bing.com/static/css/**
X-GitHub-Request-Id: 9714:67E0:141C2D:165EE6:5E8F35B9
Accept-Ranges: bytes
Date: Thu, 09 Apr 2020 14:56:17 GMT
Via: 1.1 varnish
Age: 472
X-Served-By: cache-bom18227-BOM
X-Cache: HIT
X-Cache-Hits: 1
X-Timer: S1586444177.059176,VS0,VE0
Vary: Accept-Encoding
X-Fastly-Request-ID: f28f8618ca19176e59bdbdeca81a8be4cf7064e8

<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>

**Desktop:**
- OS: Windows 10
- Browser: Firefox and Chrome

**Additional context**
This vulnerability is found by doing VAPT on this website, therefore, it is a Security Vulnerability.

**Comment by JunaidBabu** [comment]
How can we solve this?

**Comment by inderpreetsinghips** [comment]
Please read this to slove for different type of servers. 

https://niiconsulting.com/checkmate/2018/10/manipulating-host-headers-not-anymore/

**Comment by JunaidBabu** [comment]
@inderpreetsinghips thank you. as you already know we are using github pages to serve the website, how can we make the changes proposed in our case?

**Comment by inderpreetsinghips** [comment]
You can make changes from the server end from where the website is hosted and managed. Like GoDaddy or something else.

**Comment by bee-rickey** [comment]
Hi @inderpreetsinghips, as explained, we are using github pages to serve the website. Is there a way to do this for github pages?

**Comment by inderpreetsinghips** [comment]
Sorry I don't have idea of git pages. But where the website is hosted?

**Comment by bee-rickey** [comment]
@inderpreetsinghips Github pages. That's where we have hosted. Closing the issue.
