### ISSUE TITLE
Mismatch of Topology Thoothukudi district name

### ISSUE THREAD

**Issue by cedricsandars** [covid19india/covid19india.github.io#859]
**Describe the bug**
Looks like the district name has an extra "K" in it, which results in empty result in Tamil Nadu district map.

**To Reproduce**

1. Drill down to TN Map
2. Hover Thoothukudi
3. It has empty results, whereas the actual result is 20+

Solution:

Remove the additional K from Thoothukkudi to match Topology data Thoothukudi

**Comment by shuklaayush** [comment]
Duplicates #760
