### ISSUE TITLE
Make the Right side MAP section non static

### ISSUE THREAD

**Issue by Zindra** [covid19india/covid19india.github.io#861]
_When we are selecting any particular District we can not see the map of that State/Disctrict_

Make the **Right side MAP section non static**. So when we are expanding the district section then we can see the map of that district on mouse_hover.

This issue in impacting more for the states or districts showing in below part like Arunachal Pradesh, Goa etc..

![image](https://user-images.githubusercontent.com/30254595/78915951-5b1ede00-7aaa-11ea-923b-c7ee00964aa4.png)

**Comment by KrishnaPravin** [comment]
#415 #717

**Comment by jeremyphilemon** [comment]
Patched by #1364

**Comment by Zindra** [comment]
Thank you everyone
