### ISSUE TITLE
Table size is not fixed in essential

### ISSUE THREAD

**Issue by ninjakx** [covid19india/covid19india.github.io#863]
**Describe the bug**
Table is getting expanded and compressed due to length of text under Description column.

**To Reproduce**

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/29797787/78923988-b2c34680-7ab6-11ea-956f-6a531b5e5c85.gif)

**Comment by kaustumbh7** [comment]
I would like to take this up 😊

**Comment by akshat112** [comment]
I am willing to work on it.

**Comment by ninjakx** [comment]
I ain't working on it. @kaustumbh7 you can proceed with it.

**Comment by kaustumbh7** [comment]
Okay 👍🏼@ninjakx

**Comment by kaustumbh7** [comment]
@ninjakx  @bee-rickey  I have set a fixed width for all the columns and the above mentioned problem has been solved. Should I give different widths? Or is this fine?

**Comment by ninjakx** [comment]
@kaustumbh7  Ask @bee-rickey and create a pull request then.

**Comment by nikita-11** [comment]
@ninjakx  This has been fixed with this release of Essentials page. We can close the issue for now. @shuklaayush
