### ISSUE TITLE
Add toggle for dailys in DeepDive

### ISSUE THREAD

**Issue by TheDominus** [covid19india/covid19india.github.io#866]
**Is your feature request related to a problem? Please describe.**
In the daily cases, add toggle option to enable disable a category. 

**Describe the solution you'd like**
3 toggle buttons for each decreased, confirmed and recovered to see the status with multiple combinations.

**Describe alternatives you've considered**
Nothing

**Additional context**
N/A

**Comment by s-naveen** [comment]
You can already click on label to show/hide specific category.

**Comment by KrishnaPravin** [comment]
<img width="805" alt="Screenshot 2020-04-10 at 2 42 54 AM" src="https://user-images.githubusercontent.com/17372422/78941282-fdec5200-7ad4-11ea-9b6f-a464c326a286.png">

@s-naveen Label is missing in Daily Cases. Is this what are you saying @TheDominus ?

**Comment by TheDominus** [comment]
Yes, Similar to the total cases, there should be labels in the "daily cases" to hide and show a particular category.

In addition to this, there could be a new category for "total cases" i.e. "Active Cases"
@KrishnaPravin @s-naveen

**Comment by kousiksatish** [comment]
I would like to work on this. Please assign it to me.

**Comment by TheDominus** [comment]
@kousiksatish, Are you working on this feature request?
@shuklaayush, Can you assign him, if he is interested like to get this feature in the website?

**Comment by kousiksatish** [comment]
@shuklaayush @TheDominus Will start working on this
