### ISSUE TITLE
Covid-19 testing labs data issue

### ISSUE THREAD

**Issue by saikrishnareddythummala** [covid19india/covid19india.github.io#867]
A same lab is showing twice.

URL: https://www.covid19india.org/essentials
Search filters: Telangana=> Hyderabad => Covid-19 Testing labs => Search

Centre for cellular and molecular biology should show once.

![image](https://user-images.githubusercontent.com/14174956/78931685-f1133280-7ac3-11ea-8f7a-7deb665ae1ee.png)

**Comment by nikita-11** [comment]
Fixed. Closing this.
