### ISSUE TITLE
Feature to sort states on recovered and deceased

### ISSUE THREAD

**Issue by mhlaskar1991** [covid19india/covid19india.github.io#869]
The main table of states which shows the total cases, active cases, recovered cases and deceased cases is by default sorted by total cases. It would have been nice yo have a feature that would allow the records to be be sorted based on active cases or recovered cases or deceased cases. This can be achieved by making the column headers clickable, which upon clicking sort the records based on the column that is clicked

**Comment by resparx** [comment]
hey hi , What i understood from @mhlaskar1991  comment is to have a sorting feature based on the categories, But the feature is already present. If I am wrong would you please give some more context on the feature which you expect 😄.

**Comment by mhlaskar1991** [comment]
Hello. I missed that. I could see that the feature is available. Actually the headers dont look like clickable and therefore I missed that.

Thank you
