### ISSUE TITLE
Calendar overlap in clusters

### ISSUE THREAD

**Issue by arushibhat** [covid19india/covid19india.github.io#87]
**Describe the bug**
Calendar is blocking the view of clusters.(it comes on bottom right corner and stays there throughout)
The dates do not have any functionality, i tried clicking them.
Can we fix this.

**To Reproduce**

**Expected behavior**
Dates do not serve any purpose, either we add functionality to it or we just drop it.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: win10
 - Browser chrome

**Smartphone (please complete the following information):**
 - Device: oneplus 6 T
 - Browser chrome

**Additional context**

**Comment by arushibhat** [comment]
![cluster_issue](https://user-images.githubusercontent.com/52503268/77512204-8beef880-6e98-11ea-821b-9687bce79f6e.PNG)

**Comment by sirajalam049** [comment]
It would be great to have a show/hide button for the calendar when a user is focussing on the graph after selecting a date, then keeping the calender there doesn't make much sense. And making the calendar opaque coloured also improve the UX while browsing calender.

As overlapping of the graph with the calendar is totally upon the user, that how much zoom he/she has in the graph. So the best solution in that scenario is what I suggested above.

**Comment by arushibhat** [comment]
as of now the calendar does not serve any purpose, i was thinking it'd be simpler to just remove.
Let me know if I am missing something.

**Comment by someshkar** [comment]
This got fixed in someshkar/covid19india-network#63
