### ISSUE TITLE
Typo in README under Contribution Section

### ISSUE THREAD

**Issue by helios1101** [covid19india/covid19india.github.io#871]
**Describe the bug**
There is a typo in README file. At last statement, under Contribution section there is .. instead of .

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to https://github.com/covid19india/covid19india-react#contribution
2. Read the line
2. See error at 2 dot.

**Expected behaviour**
Single dot should happen.

**Screenshots**
NA

**Desktop (please complete the following information):**

- OS: MacOS
- Browser: Chrome
- Version: 22

**Smartphone (please complete the following information):**

- Device: iPhone6
- OS: iOS8.1
- Browser: Chrome
- Version: 22

**Additional context**
NA

**Comment by bee-rickey** [comment]
(╬ ಠ益ಠ)

**Comment by jeremyphilemon** [comment]
Hey, thanks for raising the issue. Unfortunately, that period was put there intentionally. It's hard to notice at first sight, but that extra . keeps all the components of this repo together. @JunaidBabu also used it to fix a major outage we experienced a few days ago, so removing it might bring everything down and crash the whole thing.

**Comment by JunaidBabu** [comment]
Thank you :)
