### ISSUE TITLE
Normalise City names in the essentials page

### ISSUE THREAD

**Issue by aswaathb** [covid19india/covid19india.github.io#873]
**Describe the bug**
Unmoderated city names in the [essentials](https://www.covid19india.org/essentials) page.

**To Reproduce**
Essentials -> {Andhra Pradesh, Kerela, Maharastra} -> _unmoderated cities_

**Expected behavior**
Uniform list of cities throughtout the website instead of instances such as
_AreaName-1, AreaName2_
or 
_City Railway station_

**Screenshots**
![F issue](https://user-images.githubusercontent.com/25769767/78937445-94167d00-7ac1-11ea-9525-c40ffcc02127.png)

**Desktop (please complete the following information):**

- Ubuntu
- Google Chrome 80.0.3987.149 

**Smartphone (please complete the following information):**
Data issue, not UI

**Comment by rominj** [comment]
https://github.com/covid19india/api/blob/master/resources/resources.json 
This file has F as District name for Andhra Pradesh. It should be changed to Visakhapatnam. because The Integrated Rural Development of Weaker Sections in India (WIDA) is located at Visakhapatnam and comes under Fund Raisers.

**Comment by vedadeepta** [comment]
@aswaathb  can you give some more examples. I don't think i understand. In the screenshot you provided which city name aren't normalized - i'm guessing its "F" - in that case how it should be normalized ? Also for Maharastra i'm not able to understand which city names are you referring to, most of them seem fine ? some examples of what cities and how do you imagine them to be normalized will be helpful to me. trying to correctly understand this issue.

**Comment by aswaathb** [comment]
![20200410_210556](https://user-images.githubusercontent.com/25769767/79008874-5a03b480-7b6f-11ea-9179-ce8b06afa6e7.jpg)
![Screenshot_20200410-210505_Chrome](https://user-images.githubusercontent.com/25769767/79008894-61c35900-7b6f-11ea-9e83-337a109576f8.jpg)

Sorry if it wasn't clear enough. Here are some additional screenshots for kerala and maharashtra, respectively. 

I was referring to the _F_ entry in my first comment. I think it's trying to show a statewide entry in which case should either come up for every city or just under 'All cities' instead of being a separate _city_ entry. 

Likewise, I think these should be changed for examples like the screenshot from Kerala and Maharashtra:

A - multiple enumerating entries should be collated as a single valid entry. 

B - entries that have railway stations and popular roads as cities should be converted to the respective city the landmarks are located in.

I assume the data is being collated through some sort of form so normalising the city entries earlier on will help avoid these duplicates when the db gets larger.  😃

**Comment by jeremyphilemon** [comment]
@nikita-11 thoughts?

**Comment by nikita-11** [comment]
@aswaathb Can you check it now? Data refining has been done.

**Comment by aswaathb** [comment]
@nikita-11 Yeah I think the refining sorted out this issue. 

@jeremyphilemon Issue has been resolved, closing  it.
