### ISSUE TITLE
Tapping outide of navbar ( on mobile devices) should hide the already expanded navbar

### ISSUE THREAD

**Issue by dpnkrpl** [covid19india/covid19india.github.io#878]
Tapping outside of a navbar are on mobiles devices should hide the already expanded navbar menu.
![gnome-shell-screenshot-U8CSI0](https://user-images.githubusercontent.com/27947066/78954676-74e81180-7afa-11ea-9bc4-4dfa50a4f736.png)

**Comment by vedadeepta** [comment]
willing to work on this, please assign.

**Comment by akshat112** [comment]
I can work on this. Do assign.

**Comment by pooja3** [comment]
Can u assign this bug to me? I am willing to work on this.

**Comment by jeremyphilemon** [comment]
Patched due to redesign. Thanks!
