### ISSUE TITLE
Link telephone numbers for click to call

### ISSUE THREAD

**Issue by dpnkrpl** [covid19india/covid19india.github.io#881]
While many modern mobile browsers automatically detect phone numbers and convert them to links, it’s a good idea to do this directly in your code. By manually tagging each phone number, you can ensure that phone numbers are always enabled for click to call and that they will be styled to match your site.

To mark a phone number as a link, use the tel: scheme. The syntax is simple:

example: 
`<a href="tel:+1-303-499-7111">+1 (303) 499-7111</a>`
thanks,

**Comment by bee-rickey** [comment]
Good to have feature. In case anyone wants to pick this up.

**Comment by tmw9** [comment]
Hey, @bee-rickey , I'd like to take this up

**Comment by dpnkrpl** [comment]
@KrishnaPravin your PR is working fine on phone. Thanks 😊

**Comment by deepa696398** [comment]
Hi Team,

I can pick this issue, Please assign on my name.
