### ISSUE TITLE
last update text climbs up the back button under the MAP

### ISSUE THREAD

**Issue by dpnkrpl** [covid19india/covid19india.github.io#883]
last update text climbs up the back button some times.
**Lastly, There should not be a back button either as i have not clicked on a state.**

![image](https://user-images.githubusercontent.com/27947066/78956556-49682580-7b00-11ea-9fe6-fa94d4adc8f1.png)

**Comment by shuklaayush** [comment]
@deep5050 Does this happen every time? I've only faced this intermittently. Let me know if you have any concrete steps to consistently reproduce it.

**Comment by dpnkrpl** [comment]
@shuklaayush  you are right , it happens between clicking a state and the getting the district view sometimes. I don't know the logic behind the implementation. But it could be due to slow internet connection or system lag / website poor performance.

**Comment by sudevschiz** [comment]
Couldn't reproduce. Please reopen if you're seeing this issue consistently.
