### ISSUE TITLE
Data mismatch between Updates and state table 

### ISSUE THREAD

**Issue by DhiralKaniya** [covid19india/covid19india.github.io#886]
**Describe the bug**
Updates show 14 new cases in WB and 4 new cases in ODISHA but the table shows 14 new cases only WB. 
If I see data state-wise then I found only 1 case in UNKNOWN.

Screenshot for reference.

<img width="639" alt="Screenshot 2020-04-10 at 9 58 50 AM" src="https://user-images.githubusercontent.com/21332852/78962593-30687000-7b12-11ea-816f-35b342507c3a.png">

<img width="618" alt="Screenshot 2020-04-10 at 9 58 24 AM" src="https://user-images.githubusercontent.com/21332852/78962585-29d9f880-7b12-11ea-8583-729294428911.png">

**Comment by DhiralKaniya** [comment]
A similar case happened earlier as well. 
Issue link:- https://github.com/covid19india/covid19india-react/issues/766

**Comment by DhiralKaniya** [comment]
Again observe this issue for Maharashtra state.  Update shows 210 but in the table it shows 410.

![Screenshot_20200410_214459](https://user-images.githubusercontent.com/21332852/79005650-fa100c80-7b74-11ea-9d87-63658eca6ceb.jpg)
![Uploading Screenshot_20200410_214511.jpg…]()

**Comment by shuklaayush** [comment]
Refer to #781
