### ISSUE TITLE
Timeseries for tests

### ISSUE THREAD

**Issue by ravigaggad** [covid19india/covid19india.github.io#887]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ravigaggad** [comment]
We can show the graph of number of test done date wise and then confirm recoverd and decided patient. So that we can get the ration of positive patient to the number of test.By this features we can check the spread and seviourity in the Country

**Comment by Zindra** [comment]
@ravigaggad I think 'no of test done ' this data is not coming in the JSON file  from this month . Please check and confirm .

**Comment by kunalpgithub** [comment]
@Zindra  which json you are looking at for data?

**Comment by Zindra** [comment]
State-district-wise | https://api.covid19india.org/state_district_wise.json
-- | --
State-district-wise V2 | https://api.covid19india.org/v2/state_district_wise.json

I checked the first one and the data was not there.. check the v2.

**Comment by kunalpgithub** [comment]
@ravigaggad @ravigaggad yeah, it seems no. of test done data is not there.
 {
        "district": "Meerut",
        "confirmed": 74,
        "lastupdatedtime": "",
        "delta": {
          "confirmed": 0
        }
      },
