### ISSUE TITLE
No. of  patient confirm,recovered and deceased showing for the state we can also show for perticular district too

### ISSUE THREAD

**Issue by ravigaggad** [covid19india/covid19india.github.io#888]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by sudevschiz** [comment]
Not all states provide information regarding recovery and deaths at a state level. We are working on improving the data to have this info.

Data needs to be cleansed and made available before this can be worked on.

**Comment by ravigaggad** [comment]
Maximum States are giving info about recovery to.

**Comment by jeremyphilemon** [comment]
Closing cause duplicate of #675
