### ISSUE TITLE
Create a patient wise recovery chart

### ISSUE THREAD

**Issue by arushibhat** [covid19india/covid19india.github.io#89]
**Is your feature request related to a problem? Please describe.**
This is a feature request.

**Describe the solution you'd like**
The idea is to reduce panic by showing the recovery rate go up as more people complete the quarantine duration. We can pick it up in a day or two.
Data wise we might have to update all patient data we are using for Clusters. It'll be our way of promoting social distancing and reducing panic.
We can discuss more.

**Describe alternatives you've considered**
We can pop up a recovery graph on the top of the page. 
Time series for how many reported- how many recovered - by a red and green line.

**Comment by sirajalam049** [comment]
IDK if I understood you correctly. But I guess this is what you want.

![image](https://user-images.githubusercontent.com/22110988/77526559-cf556100-6eb0-11ea-8035-e2bc184cdc8c.png)

**Comment by arushibhat** [comment]
i think my comment was confusing.
i was thinking we can some patient wise , 15 day quarantine timeline.
how many patients are expected to complete quarantine and what's the expected recovery.
Something like this.
![image](https://user-images.githubusercontent.com/52503268/77566902-5a078180-6eec-11ea-85db-f2f9abf3ebfa.png)

**Comment by JunaidBabu** [comment]
@sudevschiz do we have the data for this?

**Comment by jeremyphilemon** [comment]
Hey thanks for filing the issue, unfortunately we're gonna have to mark this as abandoned since the feature addition in question is either out of scope or that we simply don't have enough data to support said feature. 

Feel free to open an issue in the future if you think otherwise :)
