### ISSUE TITLE
Search Button enabled even if no indian state is selected on essesntial screen

### ISSUE THREAD

**Issue by Sanskar95** [covid19india/covid19india.github.io#890]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Sanskar95** [comment]
Pull Request: 
https://github.com/covid19india/covid19india-react/pull/891

**Comment by nikita-11** [comment]
@jeremyphilemon @Sanskar95 We can close this one. Currently we have "All States" button , so need not disable the search button for any such case. "All States", "All Cities" "All Categories" Are selected by default.
