### ISSUE TITLE
Irregular size of the button in essentials page

### ISSUE THREAD

**Issue by mohitm15** [covid19india/covid19india.github.io#892]
**Describe the bug**
The size of the button is very much larger and also the text written on it is not properly aligned
 
**To Reproduce**

1. Go to '...' essentials page
2. Scroll down to 'filter section
3. See error

**Expected behavior**
The text should be properly aligned

**Screenshots**
![Screenshot from 2020-04-10 13-37-28](https://user-images.githubusercontent.com/35539313/78974908-a1b71b80-7b30-11ea-8319-f9a2fc075d7f.png)

**Desktop (please complete the following information):**

- OS: [e.g. iOS] Linux 18.04
- Browser [e.g. chrome, safari] chrome
- Version [e.g. 22]  79.0.3945.88 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

**Additional context**
I am working on it

**Comment by nikita-11** [comment]
@shuklaayush  We can close the issue. This has been taken care of in this release.
