### ISSUE TITLE
Essential page link should be navigate to the new tab instead of same page

### ISSUE THREAD

**Issue by DhiralKaniya** [covid19india/covid19india.github.io#896]
**Describe the bug**
Website link mentioned in the essential page is opening on the same page.
Since it is an external resource link it should be open in the new tab.

**To Reproduce**
1:- Go to essential page
2:- Select any random state and city
3:- Click Seach 
4:- Click on any WebSite link in the table.

**Expected behavior**
The Resource link is open on the same page. It should open in the new page. 

**Screenshots**
<img width="1408" alt="Screenshot 2020-04-10 at 3 02 27 PM" src="https://user-images.githubusercontent.com/21332852/78981110-dc26b580-7b3c-11ea-918d-8ee7710c871b.png">

**Comment by bee-rickey** [comment]
Duplicate https://github.com/covid19india/covid19india-react/issues/879

**Comment by shuklaayush** [comment]
Should be fixed via #920
