### ISSUE TITLE
Add Visitor count in the home page ->https://www.covid19india.org/

### ISSUE THREAD

**Issue by Zindra** [covid19india/covid19india.github.io#898]
Add Visitor count in the home page i.e., https://www.covid19india.org/

**Acceptance criteria :-**
Adding a visitor count will help them to rely on these data easily. You know what I mean, right !  

**Enhancement or Upgrade :-**
_Total visitor / Daily visitor / Currently active or using_

![image](https://user-images.githubusercontent.com/30254595/78983527-0169f280-7b42-11ea-83ea-9703f919990c.png)

**Comment by shuklaayush** [comment]
I don't see how this is relevant.

**Comment by Zindra** [comment]
Hi @shuklaayush , 
The use of this counter is to let the user know how many people are seeing this and as per simple rating-review system logic that user will follow this website data over others.

**Comment by bee-rickey** [comment]
Closing this. Doesn't add any value towards the cause.

**Comment by Zindra** [comment]
@jeremyphilemon can you please have a look at this ? I still believe this is relevant.

**Comment by sudevschiz** [comment]
> Adding a visitor count will help them to rely on these data easily. **You know what I mean, right !**

No. Could you explain?

**Comment by Zindra** [comment]
@sudevschiz Thanks for replying.

The use of this counter is to let the user know how many people are seeing this and as per simple rating-review system logic that user will follow this website data over others. 
It is a common practice now-a-days to do what others are doing . That is why we have TRENDING in every app.
