### ISSUE TITLE
Alter and append more figures onto the landing

### ISSUE THREAD

**Issue by namanmodani** [covid19india/covid19india.github.io#9]
This suggestion is in terms of altering 

> confirmed, deaths, recovered and states infected

to present it more holistically by talking of:

1. Tested
2. Active/Confirmed
3. Hospitalized
4. Recovered
5. States and UTs infected
6. Deaths

**Comment by jeremyphilemon** [comment]
@JunaidBabu @sudevschiz Do we have numbers for hospitalized? Also how many figures do you think must be there on the landing?

**Comment by sudevschiz** [comment]
@jeremyphilemon We don't have that number of hospitalized from all states, yet. Let me pass it on to the data_ops team if they can collect this information.
Number of tests is actually an important information to the shown and we already have this data. 

This is available in `"tested"` field in https://api.covid19india.org/data.json

**Comment by jeremyphilemon** [comment]
All the data that we can safely and responsibly show on the website are being shown at the moment. When we're absolutely sure about the data we have in hand, we won't hesitate to put them out!
