### ISSUE TITLE
Change the map view stats layout in desktop & mobile

### ISSUE THREAD

**Issue by suryaceg** [covid19india/covid19india.github.io#90]
Push the stats on top like this.

![image](https://user-images.githubusercontent.com/840117/77520551-5f8ea880-6ea7-11ea-82cf-52bd3f66a8ed.png)

![image](https://user-images.githubusercontent.com/840117/77520477-47b72480-6ea7-11ea-9ad1-29e1d9167826.png)

**Comment by sirajalam049** [comment]
Done in 
https://github.com/covid19india/covid19india-react/pull/92#issue-393477338
Commit: 7e5637a36d8748f0da49feb6a86f4243db28f0d1

**Comment by suryaceg** [comment]
@sirajalam049 Cool. When it will be pushed to live?

**Comment by sirajalam049** [comment]
IDK, I have made PR, and also posted in the group. It might be done within a day I guess.

**Comment by suryaceg** [comment]
@sirajalam049 can you rebase this over master?

**Comment by shuklaayush** [comment]
I think it would make sense to increase the width of the map along with this.

**Comment by jeremyphilemon** [comment]
Fixed!
