### ISSUE TITLE
"Last updated about hrs ago" estimation time is not correct

### ISSUE THREAD

**Issue by Parag-Yadav-09** [covid19india/covid19india.github.io#900]
**Describe the bug**
The data last updated at 11:40am, at 4:20pm it is displaying 'updated 5hrs ago' which isn't correct

**To Reproduce**

1. Go to 'website' and verify last updated

**Expected behavior**
'updated 4hrs ago' should get displayed 
I in this case.

**Screenshots**
![Screenshot_2020-04-10-16-29-25-583](https://user-images.githubusercontent.com/63452743/78986263-80fac000-7b48-11ea-9af8-54850573d790.jpeg)

**Comment by jeremyphilemon** [comment]
Patched.
