### ISSUE TITLE
Page Number can be set negative in essentials page

### ISSUE THREAD

**Issue by the-sajith** [covid19india/covid19india.github.io#901]
![Screenshot (54)](https://user-images.githubusercontent.com/48672482/78987377-7261d800-7b4b-11ea-93d3-3f0db4db9eee.png)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by robintom** [comment]
The issue was reproducible. I am taking this up and working on this. I will submit a PR for this soon.

**Comment by nikita-11** [comment]
Hi. Since we are done away with the essentials page pagination. We can close this issue. We now have infinite scroll implemented.
