### ISSUE TITLE
Jabalpur,madhya pradesh cororna update

### ISSUE THREAD

**Issue by jamy007** [covid19india/covid19india.github.io#902]
Jabalpur district of madhya pradesh has now total 9 corona positive cases
On wednesday, 8 april a new corona case has been test positive in adarshnagar in jabalpur but it has not been updated yet in this site.
The new patient is 60-year-old man his contact history is being traced, said sources. He is from Adarsh Nagar locality from the city and had returned to Jabalpur from Hyderabad on March 20.
Plz update...

**Comment by KrishnaPravin** [comment]
@jamy007 please use [this form](https://docs.google.com/forms/d/1HVXi3-0ckxGTS81yAN1RmgrVnvg9cg2pyPTuPgBeVEo/) to report cases
https://docs.google.com/forms/d/1HVXi3-0ckxGTS81yAN1RmgrVnvg9cg2pyPTuPgBeVEo/

**Comment by jamy007** [comment]
I reported the cased yesterday that jabalpur has total 11 cases sinse
previous sunday but still it has not beet updated yet, it is still showing
10 cases, i also has mentioned the the link-
https://www.google.com/amp/s/www.naidunia.com/lite/madhya-pradesh/jabalpur-jabalpur-coronavirus-update-one-more-coronavirus-positive-found-in-jabalpur-city-5482432

**Comment by KrishnaPravin** [comment]
@jamy007 we usually update the data only if it is from official sources like government social media handles, press bulletins, official government websites, etc
