### ISSUE TITLE
The setting for chart scale modes keep getting reset

### ISSUE THREAD

**Issue by jaibatrik** [covid19india/covid19india.github.io#906]
**Is your feature request related to a problem? Please describe.**
The switches for scale mode for chart keeps resetting on refreshing the page or when re-opening the page. I have to change them according to my preference over and over.

**Describe the solution you'd like**
The settings for scale modes should persist across sessions.

**Describe alternatives you've considered**
This is a basic problem, hard to find alternative.

**Additional context**
The settings can be persisted using browser storage.

**Comment by paragsh** [comment]
@jaibatrik I would like to work on this ticket

**Comment by jaibatrik** [comment]
Hey, I actually already submitted a PR #904 for this.

**Comment by keerthanakumar** [comment]
This issue should be closed!
