### ISSUE TITLE
Showing wrong district name in Maharastra

### ISSUE THREAD

**Issue by toransahu** [covid19india/covid19india.github.io#909]
There are no such district `OTHER STATES` in Maharastra

1. Open https://www.covid19india.org/
2. Choose Maharastra state
3. Then you can see `OTHER STATES` district

![Screenshot from 2020-04-10 19-37-59](https://user-images.githubusercontent.com/10332436/78997444-35560f80-7b64-11ea-8366-43f736632f12.png)

**Comment by toransahu** [comment]
The intension might have to make an entry with `OTHER DISTRICTS`, but committed a typo?

`s/STATES/DISTRICTS/`?

**Comment by bee-rickey** [comment]
By design. Some of the cases in MH are from different states and MH classifies them so in their news bulletin.
