### ISSUE TITLE
The 'clusters' tab doesn't look highlighted when selected

### ISSUE THREAD

**Issue by eeshwarg** [covid19india/covid19india.github.io#91]
**Describe the bug**
The home, helpful links and FAQ tabs are highlighted when selected. But the clusters tab is not highlighted when selected.

**To Reproduce**
1. Go to 'https://www.covid19india.org/'
2. Observe that the home tab is highlighted
3. Click on 'CLUSTERS'
4. Notice that the clusters tab isn't highlighted though it's the currently open tab

**Expected behavior**
When the clusters tab is clicked, it's expected to be highlighted like how the other active tabs are

**Screenshots**
![image](https://user-images.githubusercontent.com/12463742/77520535-5b628b00-6ea7-11ea-96b0-8a0424582480.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version 80.0.3987.149 (Official Build) (64-bit)

**Additional context**
Home tab:
![image](https://user-images.githubusercontent.com/12463742/77520697-9795eb80-6ea7-11ea-90a2-8009d4b3cb9b.png)

**Comment by sirajalam049** [comment]
Fixed in 
https://github.com/covid19india/covid19india-react/pull/92#issue-393477338
Commit: 8de3d90f899ed97cf8e355f9f03f22804d1e45de

**Comment by iamsh4shank** [comment]
Are you working on this issue?

**Comment by sirajalam049** [comment]
I've already made a PR on this.

**Comment by iamsh4shank** [comment]
Nice

**Comment by shuklaayush** [comment]
Seems to be fixed now. Closing
