### ISSUE TITLE
Future cases prediction of corona to provide better insight of data

### ISSUE THREAD

**Issue by pushpulldecoder** [covid19india/covid19india.github.io#910]
It would be nice to add an extrapolation graph of future possible cases from the previous and current data to give better insights into the data using machine learning techniques. People might become nothing but more aware and become more cautious reading those insights

**Comment by Krutarth-Bhatt** [comment]
I would definitely support this. By getting such insights even front-line workers like police and doctors can also bewell prepared and well alert for the coming time. 
And if we have data we should definitely make the most out of it!!

**Comment by bee-rickey** [comment]
A good candidate for deep-dive section.

**Comment by shuklaayush** [comment]
I'm closing this since it duplicates #727
