### ISSUE TITLE
Add better smooth slideshow animation in banner snippet

### ISSUE THREAD

**Issue by nayakrahul** [covid19india/covid19india.github.io#911]
The snippet in banner is not smooth transitioning. 
It can be made better with smooth horizontal transition.

**Comment by akshat112** [comment]
Hey!
Can you please attach a screenshot of the banner and snippet you are referring to?

**Comment by bee-rickey** [comment]
Please provide more info if you have a specific idea.

**Comment by nayakrahul** [comment]
of this sort : https://codepen.io/Washable/pen/Oxqjbq?editors=1100

It can be made using carousel component.
https://react-bootstrap.github.io/components/carousel/
