### ISSUE TITLE
Adding package-lock.json to gitignore

### ISSUE THREAD

**Issue by mohitm15** [covid19india/covid19india.github.io#913]
**Describe the bug**

Adding ` package-lock.json` file to .gitignore

**Additional context**
All other info.are not relevant
Working on it

**Comment by SukhjinderArora** [comment]
`package-lock.json` should not be added to `.gitignore`, it should always be committed.

>This file is intended to be committed into source repositories, and serves various purposes:
> * Describe a single representation of a dependency tree such that teammates, deployments, and continuous integration are guaranteed to install exactly the same dependencies.
> * Provide a facility for users to “time-travel” to previous states of node_modules without having to commit the directory itself.
> * To facilitate greater visibility of tree changes through readable source control diffs.
> *  And optimize the installation process by allowing npm to skip repeated metadata resolutions for previously-installed packages.

[More information on `package-lock.json`](https://docs.npmjs.com/files/package-lock.json)
