### ISSUE TITLE
We can provide the information in collective way to the public regarding the different schemes in the covid 19 Hotspot areas, like direct income support related information

### ISSUE THREAD

**Issue by skumar-commits** [covid19india/covid19india.github.io#914]
**Is your feature request related to a problem? Please describe.**
Due to Covid 19 pandemic , most hit is the poor families and by providing this feature we can help them in getting their survival

The poor people have the mobiles but they dont know , what programs are run by the govt which can help them monetary and material wise .
We can have a dropdown based based on the district which are the hotspot for the pandemic and can provide the info regarding the schemes what government is doing there , how to get that support in regional language so that they can use this information for there survival.

**Describe the solution you'd like**
Dropdown with the hotspot districts with the relevant info from the govt for the downtrodden.

**Describe alternatives you've considered**
NA

**Additional context**
Not available , but will try to make some mock up screens .

**Comment by bee-rickey** [comment]
Related to #793 Please add a comment on that issue. Closing this as duplicate.
