### ISSUE TITLE
Link should open in new tab for website column in resource table.

### ISSUE THREAD

**Issue by Sanskar95** [covid19india/covid19india.github.io#915]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Sanskar95** [comment]
Some links are returning 404 .

**Comment by Sanskar95** [comment]
Pull Request :
https://github.com/covid19india/covid19india-react/pull/916

**Comment by dpnkrpl** [comment]
Same as #879

**Comment by bee-rickey** [comment]
Duplicate of #879
