### ISSUE TITLE
Rajasthan list contain 2 times EVACUEES

### ISSUE THREAD

**Issue by ravigaggad** [covid19india/covid19india.github.io#917]
![IMG_20200410_213507](https://user-images.githubusercontent.com/63439607/79004851-304c8c80-7b73-11ea-8899-a24e529e6b0f.JPG)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by swingcake** [comment]
That's a poor practice for raising an issue. At least go through the template provided.
