### ISSUE TITLE
Need outcome of cases Statewise with percentag (deceased/Total outcome cases)*100

### ISSUE THREAD

**Issue by ravigaggad** [covid19india/covid19india.github.io#918]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by bee-rickey** [comment]
Need more clarity on this. Can you please explain what you want?

**Comment by ravigaggad** [comment]
Need to calculate the mortality rate State wise.To calculate this we have to first check Outcome i.e ( No. of Patient Recover +No. Of Patient Deceased) 
Example Recoverd patient =792
                 Deceased patient = 250
So outcome of total patient =1042
Out of total 1042 patient 250 patient deceased. So Deceased rate is (250/1042)*100 = 23.99 percent till now.
So we can show whole Indian deceased rate + state wise deceased. So that we get info that which state is efficiently tackling the dieses. This feature is also in Worldometer website

**Comment by jeremyphilemon** [comment]
Closed in favour of #1496
