### ISSUE TITLE
Add comma separator(s) in all numerical counts

### ISSUE THREAD

**Issue by akshitmehra** [covid19india/covid19india.github.io#919]
**Is your feature request related to a problem? Please describe.**
Numbers written like `1000`, `10000` and `100000` are difficult to read without comma separators

**Describe the solution you'd like**
Numbers like `1000`, `10000` and `100000` should be written as `1,000`, `10,000` and `1,00,000` respectively for better readability

**Describe alternatives you've considered**
N/A

**Additional context**
All numerical counts

**Comment by bee-rickey** [comment]
Metric system needs to be followed on this. Avoid usage of libraries for the same. Should be a vanilla solution :)

**Comment by KrishnaPravin** [comment]
@bee-rickey Metric system uses either dot or space to group the numbers. 1k -> 1.000 or 1 000. Do you want to go with that?
I would prefer the Indian locale for the site 10,00,000.

**Comment by bee-rickey** [comment]
@KrishnaPravin How difficult would it be to change it later? The Metric system is the standard used for international numbers. So anyone using our site as a reference would be a bit confused. If it's an easy switch, lets keep the locale for now. Later take a call on metric.

**Comment by ameya-pandilwar** [comment]
@bee-rickey -- I would like to pick this up.

**Comment by guptadev** [comment]
Hi @pb03,

As I can see every numeric data count is now separated with comma, except district wise count. Please refer below screen capture:
![image](https://user-images.githubusercontent.com/15716246/79046787-88959400-7c30-11ea-9aae-fcff8acd09e5.png)

Can we have district wise data count separated by comma as well?

Thanks,
Dev

**Comment by ameya-pandilwar** [comment]
Hi @guptadev -- I have added formatting for district wise count. Please reivew and merge the PR. Thanks!
