### ISSUE TITLE
Duplicate PATIENT NATIONALITY (India and indian)

### ISSUE THREAD

**Issue by ikshitiz** [covid19india/covid19india.github.io#921]
**Describe the bug**
In deepdive page Patients nationality section, Indian and India are tagged as a different nationality

**To Reproduce**
Merge Indian and India.

1. Go to 'DeepDive'
2. Click on 'PATIENT NATIONALITY'
4. Check India and Indian are different nationalities

**Expected behavior**
Both should be merged.

All Devices

**Comment by Nitin96Bisht** [comment]
@iKshitiz issue is with API. Kindly report the issue https://github.com/covid19india/api.

We have an issue with https://api.covid19india.org/raw_data.json API. 
"nationality": "Indian"
"nationality": "India"

Both can be found here.

**Comment by piyush-repo** [comment]
I believe over here we can translate the Indian to India and then plot the chart

**Comment by Nitin96Bisht** [comment]
@piyush-repo Indeed we can do this but this is not the best practice approach. It is better we change the name in the excel sheet from where data is coming then it would be great.

**Comment by bee-rickey** [comment]
Avoid client side changes for this. This issue is fixed on the sheet. Thank you!
