### ISSUE TITLE
Improve website speed on slow networks

### ISSUE THREAD

**Issue by 25prathamesh** [covid19india/covid19india.github.io#923]
covid-19 site loads slow on 3G mobile network it takes 5 second for first paint. lot of indian users are on slow network. 

There are lot of things we can do 
but right now below are some quick fix - 
1) adding preconnect tags for www.googletagmanager.com & api.covid19india.org , so till css & javascript gets downloaded , dns & tcp connection will resolved for this domain , this will remove waiting time
2) lossless compression for images , example icon.png file is 18Kb if lossless compression applied it will be 5kb only
3) add   font-display:swap;  property while defining  fonts , swap property will ensure rendering will not blocked till fonts file gets downloaded. browser will render with system font & once font downloaded it will applied on texts.
![covid19_waterfall](https://user-images.githubusercontent.com/10120153/79017549-38b2c080-7b8f-11ea-8ed2-0dc258690e93.jpg)

**Comment by bee-rickey** [comment]
Thank you for the detailed quick fixes!

**Comment by umanghome** [comment]
Would like to pick this up.

**Comment by jeremyphilemon** [comment]
@umanghome I'm un-assigning myself due to limited knowledge on this topic, so go ahead :)

**Comment by jeremyphilemon** [comment]
Opening this up again /available

**Comment by karankiri** [comment]
/claim Would like to work on this
