### ISSUE TITLE
ESSENTIALS Page - Clicking on arrows to change the page does not change page index in input

### ISSUE THREAD

**Issue by anupriy97** [covid19india/covid19india.github.io#924]
**Describe the bug**
When using arrows to change page in search results in ESSENTIALS page, it does not change the value of page index in input field (as shown below). Also, page index input field can take input anything like negative numbers and letters.

**To Reproduce**

1. Go to 'ESSENTIALS'
2. Choose "Assam" as state.
3. Click on "Search"
4. Click on right arrow in bottom.
5. Page changes but number in input field in the right remains same.

**Expected behavior**
Page number shown in the table view should be in sync everywhere. Page index input field should only take numbers between 1 and total number of pages.

**Screenshots**
![Screenshot from 2020-04-11 01-06-36](https://user-images.githubusercontent.com/16060171/79018346-381b2980-7b91-11ea-801b-a98e112e38b0.png)
After clicking next page (">" arrow), "Page 2 of 2" not in sync with "1" in input field.
![Screenshot from 2020-04-11 01-07-11](https://user-images.githubusercontent.com/16060171/79018341-35203900-7b91-11ea-8e00-0db94097bad7.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by nidhidad** [comment]
Can I contribute?

**Comment by jeremyphilemon** [comment]
Thanks for raising this issue! It looks like the essentials team went ahead and implemented an infinite scroll instead, so no more pagination worries :)
