### ISSUE TITLE
Hotspots/ Red zone will be helpful in map

### ISSUE THREAD

**Issue by wilsonrakesh** [covid19india/covid19india.github.io#926]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by bee-rickey** [comment]
Hello. Currently this data is not available as a part of state govts' press releases. Hence this would not be possible as of now.

**Comment by bee-rickey** [comment]
Related to #793 Closing as duplicate for now. Please comment on that issue.
