### ISSUE TITLE
On Telangana more details boxes, link to source do not show up as Tested value is not available. Link to data source should be present irrespective of tested column value (this link validates the other column values e.g. Confirmed, Active etc.)

### ISSUE THREAD

**Issue by debopamb** [covid19india/covid19india.github.io#928]
**Describe the bug**

**To Reproduce**

1. Go to https://www.covid19india.org/ 
2. Click on Telangana 
3. Scroll down to 'Hover Over A state /UT for more details'
4. No source link is present as Tested column is empty

**Expected behavior**
the source link should be present irrespective of Tested Column having value or not. As the source link validates other column values like Confirmed, Active etc.

**Screenshots**
![image](https://user-images.githubusercontent.com/3934569/79026084-4f641200-7ba5-11ea-9191-9508675b5883.png)

**Desktop (please complete the following information):**
desktop and phone all OS

- OS: [ iOS, Windows, macOS]
- Browser [chrome, safari]

**Comment by sudevschiz** [comment]
In most cases, the source for the patient statistics and testing numbers are different. Also the patient statistics is sourced from multiple releases. 
Hence, this is not a bug. Thank you for exploring this thought.
