### ISSUE TITLE
Adding drilldown till hotspot level

### ISSUE THREAD

**Issue by niteeshravi** [covid19india/covid19india.github.io#929]
**Problem statement.**
The current website shows data drilldown till the district. A user would not know the hostpots in his/her district.They do not know how close they are to a hotspot (unless they explicitly follow news or search for hotspots in their region) and the density of cases in that hotspot.

**Solution:**

Add another level of drilldown to the district and circle them on the map.
![map_bbplot](https://user-images.githubusercontent.com/5737665/79025549-bda7d500-7ba3-11ea-96ab-c3f99609553d.png)

Attached a sample picture. But this would be at a district level. The size of the bubble to indicate the number of cases in that region.

**Alternative:**
As an alternative you can show the hotspots along with the numbers in the main table.

Let me know if this helps. I would also love to be a part of this effort.
Thanks

**Comment by sudevschiz** [comment]
https://github.com/covid19india/covid19india-react/issues/932

Closing.
