### ISSUE TITLE
showing city wise increment of new cases

### ISSUE THREAD

**Issue by Dhrumit8596** [covid19india/covid19india.github.io#932]
**Is your feature request related to a problem? Please describe.**
New cases in different cities are not shown when we dropdown a particular state.
For example, we can see the number of new cases in Maharashtra but not able to find the number of new cases in Mumbai.
1. Go to 'https://www.covid19india.org/'
2. Click on 'Maharastra'
3. No specific new cases are been shown citywide 

**Describe the solution you'd like**
Showing number of new cases towards cities the same way as done for states.

**Comment by sudevschiz** [comment]
We rarely get information at a city level, except from few state bulletins. Hence it's not possible to bring in this feature. Please do re-open this, if you find a vast data source that has this information. Closing for now.

**Comment by Dhrumit8596** [comment]
I feel there is some issue with city level cases because till evening it was showing the increment city-wise but suddenly now it is not showing the same.
Please have a look at the snapshot.

![image](https://user-images.githubusercontent.com/17471088/79054328-bbbc3100-7bf8-11ea-8ab8-dfd7c1231ab3.png)

**Comment by sudevschiz** [comment]
@jeremyphilemon The delta numbers has to remain till 7AM IST, the next day even for district wise numbers. _That's one of the auto legs of the wind based motor mechanism that we have_

**Comment by Dhrumit8596** [comment]
Commenting to bringing issue in notice, its still having same issue.
