### ISSUE TITLE
Single graph for spread trend

### ISSUE THREAD

**Issue by ayusun** [covid19india/covid19india.github.io#933]
**Is your feature request related to a problem? Please describe.**
It's not very comfortable to compare the recovery rate and case rate and death rate in 3 different graph

**Describe the solution you'd like**
A combined graph to show all 3 in a single graph

**Describe alternatives you've considered**
None

**Additional context**
Got the idea from this graph
https://www.coronatracker.com/country/india/

**Comment by shuklaayush** [comment]
Hey, it's there in the deep dive section
