### ISSUE TITLE
Delhi subdivision shows 90% as unknown

### ISSUE THREAD

**Issue by thehitechpanky** [covid19india/covid19india.github.io#934]
**Describe the bug**
If you drill down in Delhi, it shows around 90% cases as from unknown area. These need to be properly classified.

**To Reproduce**
1. Go to Delhi
2. Click on Arrow in left-most position
3. Scroll down to bottom
4. See Unknown showing most of the cases

**Expected behavior**
Area-wise distribution should be there.

**Desktop (please complete the following information):**
- OS: Linux
- Browser Chrome
- Version 80+

**Comment by sudevschiz** [comment]
Yes. This is because we are not able to map individual patients to corresponding districts. Data team is working on this.

**Comment by sudevschiz** [comment]
District level information is not clearly published in the govt press bulletin. We have added a note for the same.
