### ISSUE TITLE
Stats display on top right should show overall count

### ISSUE THREAD

**Issue by kabzzy** [covid19india/covid19india.github.io#937]
As of now, the stats on top right (above the map) shows stats for the last state the mouse was hovered over and defaults to Maharashtra on page load. 

Behavior should change so that the stats show overall, national count when the mouse if not over a particular state on the map.
![Capture](https://user-images.githubusercontent.com/3241528/79037910-cd9ad580-7bf2-11ea-90f9-0060729c58de.PNG)

**Comment by sudevschiz** [comment]
Yes, this is a UX improvement. Those numbers could be confused with India numbers. @jeremyphilemon please take a mental note for next version.

**Comment by kabzzy** [comment]
> Yes, this is a UX improvement. Those numbers could be confused with India numbers. @jeremyphilemon please take a mental note for next version.

Exactly. They look like India numbers on first glance.

**Comment by dpnkrpl** [comment]
Yeah that's right that should be nation's total count

**Comment by vidyashreen1991** [comment]
I would like to work on it.

**Comment by shuklaayush** [comment]
Seems to be fixed
