### ISSUE TITLE
Please change and update the currentstatus column in the api link

### ISSUE THREAD

**Issue by srikanth009** [covid19india/covid19india.github.io#94]
The currentstatus column has to be updated for recovered cases regularly in the api json file for given link below. This quite essential for data analytics, since the rate of recovery and the rate of infection would determine on how much time would a quarantine be required.
The api link described above being:
https://api.covid19india.org/raw_data.json

**Comment by akshaykiran** [comment]
Wrong repo. please raise issue in https://github.com/covid19india/api
