### ISSUE TITLE
Number of Cases in Mumbai Suburban shows zero

### ISSUE THREAD

**Issue by atharvaj77** [covid19india/covid19india.github.io#941]
**Describe the bug**
While navigating through the map the cases in Mumbai Suburban displays zero as its confirmed cases.

**To Reproduce**

1. Go to Maharashtra State
2. Hover over Mumbai Suburban
3. See error

**Expected behavior**
Should display number of cases in Mumbai Suburban area

**Screenshots**
![Screenshot from 2020-04-11 13-43-11](https://user-images.githubusercontent.com/58818674/79038948-430aa400-7bfb-11ea-81cc-2cfd3c808847.png)

**Desktop (please complete the following information):**
-Ubuntu 18.04 LTS
-Mozilla Firefox Browser

**Suggestion**
Please add a separate map for Mumbai and its suburban areas

**Comment by sudevschiz** [comment]
Separate numbers are not being published by the state government. Mumbai and Mumbai suburban are clubbed under Mumbai in bulletins.
