### ISSUE TITLE
Total number of test vs positive cases

### ISSUE THREAD

**Issue by ikshitiz** [covid19india/covid19india.github.io#945]
**Is your feature request related to a problem? Please describe.**
A detailed total number of test vs positive found ratio. This will give an overview of the statewide infection rate and nation-wide.

Say for example:
Karnataka 

- Total Tests: 8k (Approx)
- Total Individuals Tested: 6.5k (Approx)
- Total positive: 214 
- Infection rate: 3%

**Comment by yashshah1** [comment]
Can I work on this?

**Comment by sudevschiz** [comment]
This is a good idea for Deep-Dive page. Assigning @yashshah1 . However, please wait for more guidelines regarding the structure of that page from @jeremyphilemon @shuklaayush before working on it.

@shuklaayush @jeremyphilemon could you share any ideas?

**Comment by srip1** [comment]
Would like to contribute developing this enhancement. Please let me know if i can raise pull request.

**Comment by sudevschiz** [comment]
It won't be useful to crowd this in the main table. @yashshah1 can you provide a mockup of any chart that you can add to the deep-dive section?
@srip1 please do suggest ideas your ideas for a graph too.

**Comment by jeremyphilemon** [comment]
Closing in favor of #1496
