### ISSUE TITLE
Green color on Map for all positives cases recovered from that state/UT

### ISSUE THREAD

**Issue by ikshitiz** [covid19india/covid19india.github.io#946]
We will be seeing 100% recovered in Ladakh, few NE states and the Andaman region in the coming days. Highlighting those areas with green color will give some positivity amidst this chaos in the pandemic.

**Comment by bee-rickey** [comment]
IMO not required. We will end up with places like Nagaland that have no cases yet being white, places with recovery being green and then lots of shades of red. Although the intention seems noble, it creates confusion and the legend becomes complex.
