### ISSUE TITLE
Recoveries in Madhya Pradesh not added to the counter

### ISSUE THREAD

**Issue by SuyashD95** [covid19india/covid19india.github.io#947]
In the updates section, it has been reported that MP has 14 recoveries... This news update came 2 hours ago (on April 11th) and yet, this stat has not been added to the total recoveries counter of the country as well as the state...

Hence, it is imperative that we add the 14 people that have succeeded recovered today, especially an unclear count could lead to the numerous graphs to display incorrect numbers and could potentially lead people to jump into wrong conclusions...

Correction of this issue is especially crucial for residents of MP because currently, the recovery to death ratio is almost 1:1 and adding 14 recoveries, would reduce the anxiety of the residents and can bring some light in this dire situation...

Also, this tracker is also being used by other news and data collection agencies as their official source...

**Smartphone Details**

- Device: Nokia 6.1 Plus
- OS: Android 10
- Browser: Google Chrome 
- Version: Latest (as of April 11th, 2020)

**Screenshots**

1. The updates section with report of recoveries in Madhya Pradesh (3rd from the top):

    ![Screenshot_20200411-145031](https://user-images.githubusercontent.com/15222897/79040517-b0700200-7c06-11ea-97e8-7e344a38088b.png)

2. No updates either on the total counter at the top of the page or in Madhya Pradesh row of the States table (indicated by no green arrow next to 'Recovered' column):

    ![Screenshot_20200411-145042](https://user-images.githubusercontent.com/15222897/79040617-50c62680-7c07-11ea-8aeb-4ec6de61d332.png)

**Comment by shuklaayush** [comment]
Duplicates #766. We're looking into it
