### ISSUE TITLE
Maharshtra state contain name of Nagaur district which is not in Maharashtra State

### ISSUE THREAD

**Issue by ravigaggad** [covid19india/covid19india.github.io#948]
![IMG_20200411_153336](https://user-images.githubusercontent.com/63439607/79040970-d9de5d00-7c09-11ea-921f-89d5c614d8fc.JPG)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by abhaybaiju** [comment]
Is this still an issue? I am not able to reproduce it.

**Comment by ravigaggad** [comment]
Done.issue resolved

**Comment by ravigaggad** [comment]
Issue resolve
