### ISSUE TITLE
Homepage is not scaling up properly on mobile

### ISSUE THREAD

**Issue by dpnkrpl** [covid19india/covid19india.github.io#951]
Only the homepage isn't scaling up properly on mobile devices. You can see the extra padding at the right side. I have zoomed and taken the screenshot for better visualization.

![Screenshot_2020-04-11-16-44-46-931_com android chrome](https://user-images.githubusercontent.com/27947066/79042310-4199a580-7c14-11ea-878a-b1f3284a2cb1.jpg)
** That happened due to the addition of `TESTED` count near map **

**Comment by shivang2joshi** [comment]
It is working Fine in my browser. Tried on Safari & Chrome for iOS. can you check again?

**Comment by Binu42** [comment]
@jeremyphilemon @shuklaayush assign it to me. i'm working on it.

**Comment by DashmeetArt** [comment]
@shuklaayush can you please assign this issue to me, I would like to work on it.

**Comment by DashmeetArt** [comment]
Made required changes to resolve this issue, Kindly check at #956

**Comment by dpnkrpl** [comment]
@shuklaayush What's your plan regarding this issue? The right blank space is expanding day by day as the numbers are increasing. 


![Screenshot_2020-04-14-14-52-24-185_com android chrome](https://user-images.githubusercontent.com/27947066/79208413-a137c100-7e5f-11ea-95a4-975b5e6ad24b.jpg)

**Comment by shuklaayush** [comment]
@deep5050 For the testing numbers above the map, @jeremyphilemon is working on a redesign.

As for the table, we were thinking of making it horizontally scrollable. From an implementation point of view, this would involve somehow making the first column sticky like the table header is right now. Then we can also add more columns to the table and not worry about the UI breaking on phone. Let me know if you can help with this.
