### ISSUE TITLE
Addition of data header for cases per million population

### ISSUE THREAD

**Issue by spidynikhil** [covid19india/covid19india.github.io#953]
**Is your feature request related to a problem? Please describe.**
As we all know India is second-largest populous country in the world. According to worldometers.info, we are 1,380,004,385 as of April, 2020. It would be better to show "total, active and death" cases at per million population base. I believe this will give our users a broad and better perspective on COVID 19 spread in India.

**Describe the solution you'd like**
In header before data table, a new information should be added with totalCases/1M population, activeCases/1M population, deathCases/1M population and totalCases-India/totalCases-World.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by sudevschiz** [comment]
I think any statistics in India is skewed by the large population. I feel a better judge of the testing numbers would be to compare it with the number of cases detected. If more cases are detected, that means those cases have contacts and those contacts need to be tested aggressively. 

https://github.com/covid19india/covid19india-react/issues/945 talks about this.

And definitely, top header is not the place for this. This could be a graph in deep-dive. What do you think?

**Comment by spidynikhil** [comment]
I saw issue #945 and I think that's also a good idea. Please don't be confused that my idea is also the same. I will try to give a clear view of my idea: 

The idea is to show the users how good/bad we are tackling corona virus spread in India. I talked about the ratios (no stats or graph needed), like totalCases-India/totalCases-World (this will give the spread ratio in India over world), totalCases/1M (as of now: 8453/1000000 = "0.008453", you see how small this is). The smaller the ratio would be, the  more optimistic we would be, or if it increases we could be more cautious about the spread. We can also show totalCases/totalPopulation instead of per million population, if you want. Adding these ratios in header with other counts will inform our users about the progress (and position in the world) of our battle against corona virus. If we can show the ratios' skewed graph in Deep Dive then it would be better, but adding the ratios in Home header will fulfil the idea for now.

**Comment by jeremyphilemon** [comment]
Closing in favor of #1496
