### ISSUE TITLE
Change in filters showing previous filters data

### ISSUE THREAD

**Issue by ManojPathak1** [covid19india/covid19india.github.io#958]
**Describe the bug**
Change in filters showing previous filters data

**To Reproduce**
1. Open Home Page
2. Go to demographics
3. Select State and District with available data
4. Data will be displayed with patients
5. Now select state and district with no available patient data.
6. Data will be displayed of previously selected state and district.

**Expected behavior**
State and District selection should update the patient data.
For no data available show proper message for the same.

**Screenshot**
<img width="1020" alt="Screenshot 2020-04-11 at 6 38 40 PM" src="https://user-images.githubusercontent.com/13708371/79045927-6ea58280-7c2b-11ea-8fb4-b95aa76616a0.png">
Data for state - Uttar Pradesh & District - Hapur is displayed.

**Comment by ManojPathak1** [comment]
Created a pull request for the same
https://github.com/covid19india/covid19india-react/pull/955

**Comment by jeremyphilemon** [comment]
Patched by #1363
