### ISSUE TITLE
Code splitting

### ISSUE THREAD

**Issue by iDhruv22** [covid19india/covid19india.github.io#959]
**Is your feature request related to a problem? Please describe.**
No, it's not a problem but it would be good to have as our codebase is increasing.

**Describe the solution you'd like**
Split the code based on router and lazy load other routes than "Home" so its performance can be a boost. It'll be great for low internet speed users.

**Comment by iDhruv22** [comment]
I would like to get assigned this to me.

**Comment by bee-rickey** [comment]
Please speak to @jeremyphilemon before you pick this up for development.

**Comment by iDhruv22** [comment]
##### Routing scheme - 
 - ***Demographics*** and ***Deep dive*** will have their own separate chunk.
 - The rest all will be in one main chunk.
##### Implementation - 
The react Suspense and lazy will be used to achieve this. As a fallback of Suspense, the spinner Icon will be considered

@jeremyphilemon can I start working on this?

+Edit
Added PR as well, let me know you have any feedback on top that.
