### ISSUE TITLE
Android App for Covid19India

### ISSUE THREAD

**Issue by ankit-ankuagrawal** [covid19india/covid19india.github.io#96]
GitHub link for the code https://github.com/ankit-ankuagrawal/covid19india

Currently on opening app the website is open.

Here is the link to the app https://drive.google.com/file/d/158_09xrTnNG_QJGoYgNJIMbuprUjG0oy/view?usp=sharing

**Comment by ThePiyushGupta** [comment]
I think that creating an app in expo would be much easier as the project is based on react

**Comment by ankit-ankuagrawal** [comment]
@ThePiyushGupta, in the app opening website of covid19india. Though we will be restricted to android devices if we go by my approach.

What you suggest?

**Comment by vrajeshkanna** [comment]
@ThePiyushGupta @ankit-ankuagrawal Why do we need an app? As per #78, we can make it as a PWA. It works as good as an app

**Comment by nachiketbhuta** [comment]
I think PWA will be a better idea

**Comment by kdqed** [comment]
Once we have PWA we can get an apk and publish on Play Store by converting to TWA:

[Reference](https://css-tricks.com/how-to-get-a-progressive-web-app-into-the-google-play-store/)

**Comment by vrajeshkanna** [comment]
PWA PR #122 raised

**Comment by rajathsn** [comment]
GitHub link for the code and apk https://github.com/rajathsn/covid19

**Comment by JunaidBabu** [comment]
Not relevant. Closing.

**Comment by Ayush1325** [comment]
I wrote a flutter app if anyone is interested
https://github.com/Ayush1325/Coronavirus-Status
although it's mostly like a personal project.

**Comment by vrajeshkanna** [comment]
@Ayush1325 App Looks nice.

**Comment by Ayush1325** [comment]
Thanks

**Comment by Ayush1325** [comment]
@vrajeshkanna Thanks
