### ISSUE TITLE
Tablighi Jamaat / reason

### ISSUE THREAD

**Issue by thehitechpanky** [covid19india/covid19india.github.io#963]
**Is your feature request related to a problem? Please describe.**
The Indian media is constantly saying something and social media is saying something and other blogs are depicting something else. There's so much of confusion over the breakup of diagnosed cases based on the reason.

**Describe the solution you'd like**
Is it possible to add a filter so that we can know exactly how much is foreign travel the culprit and how much has tablighi jamaat contributed to this menance. Since you are recording data for reason, creating a filter won't be much of a problem I suppose.

**Describe alternatives you've considered**
I've heard in news that all states are already recording Tablighi Jamaat cases separately except Rajasthan, so depicting that would not be that much difficult. If you could add religion / gender / age / travel history or any such characteristic, that might also be a good start.

**Comment by dpnkrpl** [comment]
These things are not so important i guess, at least at this point of time (as most of the data is not available/ UNKOWN till this date) Thsese will just degrade the website's performance. Already it became heavier as lots of features have been added recently.

**Comment by bee-rickey** [comment]
Closing this. We will never add religion or anything that can lead to discrimination.
