### ISSUE TITLE
Active, recovered and deceased in district-wise results

### ISSUE THREAD

**Issue by thehitechpanky** [covid19india/covid19india.github.io#964]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I'm unable to find out the district of deaths and recoveries. There are a lot of rumours circling around that this district is case-free or this district is hot-spot.

**Describe the solution you'd like**
Just like we have 4 tabs for states, we can have 4 tabs for districts.

**Describe alternatives you've considered**
We can go for 5 tabs for states and districts, 5th one being the quantum of tests being conducted.

**Comment by kash1102** [comment]
4 tabs for districts should be picked first and then we can bring the 5th one as part of enhancement.

**Comment by shuklaayush** [comment]
This has been duplicated a number of times. Please go through the issues before submitting a new one. The implementation for this is already there in the code. The bottleneck is the lack of data, which unfortunately is not being released by the respective state governments. Thanks
