### ISSUE TITLE
Add a graph to display doubling rate

### ISSUE THREAD

**Issue by kracekumar** [covid19india/covid19india.github.io#966]
**Is your feature request related to a problem? Please describe.**

Now that cases are doubling quicker, it may be better to have a doubling rate at country level and state-level as a time-series. Y-axis "no of days" and x-axis "number of cases".

**Describe the solution you'd like**
This is a step to find out the "flatten the curve" is happening or not.
Example: https://covid19-india.datameet.org//dashboard/

By this one can say, how each state is performing, who is lacking, and who are doing well

**Comment by swap-pakhare** [comment]
Hi, I'd like to work on this.

**Comment by paragsh** [comment]
@kracekumar : I would like to work on this ticket please

**Comment by pooja3** [comment]
Can u assign this enhancement to me? I am willing to work on this.

**Comment by kunalpgithub** [comment]
@kracekumar  this is really good feature. Do we have data for this API or can someone guide how can we use existing data that we have.

**Comment by vipulnewaskar7** [comment]
Hi @kunalpgithub ,
We can use existing data.
say, we have day and cumulative confirmed cases,
Below snippet may help
```
cnf_cases= [365, 678, ....]
log_cnf_cases[0] = 0
for (i = 1 ; i< len(cnf_cases); i++)
{
   log_cnf_cases[i] = Math.log(cnf_cases[i]) - log_cnf_cases[i-1]
}
// plot chart(day vs log_cnf_cases)
```

**Comment by vipulnewaskar7** [comment]
**Note**
log to the base 2

**Comment by jeremyphilemon** [comment]
Closing in favor of #1496
