### ISSUE TITLE
Age of deceased chart

### ISSUE THREAD

**Issue by iDhruv22** [covid19india/covid19india.github.io#967]
Deep dive can have bar chart for patients who sadly died in this pandemic based on their age.

**Comment by strikertanmay** [comment]
I would like to work on this issue. Please assign me this one

**Comment by JunaidBabu** [comment]
You'll have to make use of this
https://api.covid19india.org/deaths_recoveries.json

**Comment by strikertanmay** [comment]
> https://api.covid19india.org/deaths_recoveries.json

Can U please suggest the title of this graph.

**Comment by strikertanmay** [comment]
@JunaidBabu @sudevschiz Can u please suggest the title of this graph !

**Comment by strikertanmay** [comment]
please review this https://github.com/covid19india/covid19india-react/pull/978 and suggest the changes if required

**Comment by strikertanmay** [comment]
> I would like to work on this issue. Please assign me this one

@jeremyphilemon Please assign me this one
