### ISSUE TITLE
No of tests for Tamil Nadu as of 11th April  is displayed as NAN

### ISSUE THREAD

**Issue by sourav-patra** [covid19india/covid19india.github.io#970]
The number of tests for Tamil Nadu as of 11 April is displayed as NAN. Looks like a formatting issue

**Steps to reproduce the behavior:**
1. Go to1 `https://www.covid19india.org/1`
2. Click on any state in the map
4. `NAN` displayed in `Tested` card

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/61248036/79050451-be924280-7c47-11ea-9775-8bf71091654a.png)

**Desktop:**

- OS: Windows 10
- Browser: Chrome
- Version: 80.0.3987.163

**Comment by shuklaayush** [comment]
Fixed
