### ISSUE TITLE
Time series legend count not displaying with '+' symbol

### ISSUE THREAD

**Issue by guptadev** [covid19india/covid19india.github.io#974]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/15716246/79051174-585bee80-7c4c-11ea-9e75-ca2fdca70788.png)

![image](https://user-images.githubusercontent.com/15716246/79051323-331bb000-7c4d-11ea-809c-8107a315d35e.png)

**Comment by bee-rickey** [comment]
Duplicate of #973
