### ISSUE TITLE
Patient Id 4933 has the city as Kannur but State is Missing.  It may be updated to kerela

### ISSUE THREAD

**Issue by baronpankaj** [covid19india/covid19india.github.io#977]
Patient Id 4933 has the city as Kannur but State is Missing.  It may be updated to Kerela

You refer the data and see the state is empty in raw data for patient id 4933

**Comment by sudevschiz** [comment]
This is a tricky one.

So, Patient 4933 was considered as part of Kerala numbers till today when he sadly, demised. Mahe, Puducherry has not claimed this case as part of their numbers too. The case is not tied to either states now. We will update the state when more information is available.
