### ISSUE TITLE
Correction in no of deaths for himachal Pradesh

### ISSUE THREAD

**Issue by ridiis** [covid19india/covid19india.github.io#979]
Current data shows 22 active cases from hp,8 recovered  and 2  deaths,as on 3:20am on 12 April, but the actual no of recovered cases is 9 and only 1 tibetian had died from kangra.
PFA the snapshot of the national health mission data and try to rectify the same.[](http://www.nrhmhp.gov.in/) 

![Screenshot_2020-04-12-03-13-06-71](https://user-images.githubusercontent.com/63258358/79055808-7be36100-7c6d-11ea-9672-cb602869c884.jpg)

**Comment by shuklaayush** [comment]
Please read this https://github.com/covid19india/covid19india-react/issues/662#issuecomment-612361044
