### ISSUE TITLE
District level details to have Active, Recovered, Deaths, Delta

### ISSUE THREAD

**Issue by alokaroramca** [covid19india/covid19india.github.io#982]
**Is your feature request related to a problem? Please describe.**
When we click on State (table) to show District wise breakup (row), it is not showing all colums like for state e.g. Active, Recovered, Deceased and their Deltas. 

Only DISTRICT, CNFMD are shown

**Describe the solution you'd like**
It is Low hanging fruit.
Low cost, High return

Step-1) Just add Deltas and these column values in api response for
https://api.covid19india.org/state_district_wise.json

Step-2)row.json to have columns head and values similar to as in table.json

I can raise PR if u can do step-1 or Tell me repo or where to do that

**Describe alternatives you've considered**
Not any at moment

**Additional context**

**Comment by shuklaayush** [comment]
Please go through old issues before posting a new one
