### ISSUE TITLE
All Emergency Phone Numbers across States

### ISSUE THREAD

**Issue by amateur-dev** [covid19india/covid19india.github.io#983]
**Is your feature request related to a problem? Please describe.**
The current list of important numbers are hidden behind a PDF doc and not so easily accessible.

**Describe the solution you'd like**
Data Table to show the stat wise (searchable) list of phone numbers

I have collated this list from all the sources: https://docs.google.com/spreadsheets/d/1Cq9yLURiA5KW_nM3_beW32UaRFLmV8K77Z7e8pt3FOM/edit#gid=0

You can also use this code to call data formatted:

```
const axios = require('axios');
async function getPhoneNumbers(state) {
  var reply = await axios.get(`https://spreadsheets.google.com/feeds/list/1Cq9yLURiA5KW_nM3_beW32UaRFLmV8K77Z7e8pt3FOM/od6/public/values?alt=json`);
  let entries = reply.data.feed.entry
  // console.log(entries[0])
  let ans = entries.find(obj => obj["title"]['$t'] === state);
  // console.log(ans)
  let phoneNumbers=[];
  // let num = 3
  // console.log(ans[`gsx$phoneno${num}`]["$t"])
  for (i=1;i<7;i++) {
    phoneNumbers.push(ans[`gsx$phoneno${i}`]["$t"])
  }
  // console.log(phoneNumbers);
  phoneNumbers = phoneNumbers.filter(Boolean);
  let message = `The emergency helpline numbers of ${state} are ` + phoneNumbers.toString().replace(/,/g, ', ');
  console.log(message);

}
```
Following is the example of the command and output: 
```
getPhoneNumbers("Maharashtra");
The emergency helpline numbers of Maharashtra are 022-22027990, 020-26127394
```

**Comment by nikita-11** [comment]
Why do you say it is inaccessible? Can you please visit the Essentials tab. Select All states, All cities followed by Govt helpline in filters. You will be able to see the helpline numbers being displayed city wise. We can integrate it with your collated list as well, but that would need a city-wise filter to be shown.

**Comment by jeremyphilemon** [comment]
This is available through essentials.
