### ISSUE TITLE
Incorrect spelling for district of Beed city

### ISSUE THREAD

**Issue by ameya-pandilwar** [covid19india/covid19india.github.io#984]
**Describe the bug**
The spelling for the district of Beed city is incorrectly written as `Bid` in the Google Spreadsheet (https://docs.google.com/spreadsheets/d/e/2PACX-1vSc_2y5N0I67wDU38DjDh35IZSIS30rQf7_NYZhtYYGU1jJYT6_kDx4YpF-qw0LSlGsBYP8pqM_a1Pd/pubhtml#) and hence showing up incorrectly on the website.

**To Reproduce**

1. Go to 'https://www.covid19india.org'
2. Click on 'Maharashtra'
3. Scroll down to 'Bid'

**Expected behavior**
The correct spelling is `Beed` instead of `Bid`
Source: https://en.wikipedia.org/wiki/Beed

**Screenshots**
<img width="388" alt="Screen Shot 2020-04-11 at 9 28 13 PM" src="https://user-images.githubusercontent.com/8572890/79060566-740ac900-7c3b-11ea-8b0c-12aa9c75d9ac.png">

**Desktop (please complete the following information):**

- OS: [e.g. iOS] Mac OS
- Browser [e.g. chrome, safari] Firefox
- Version [e.g. 22] 73

**Smartphone (please complete the following information):**

**Additional context**

**Comment by shuklaayush** [comment]
Refer to https://github.com/covid19india/covid19india-react/issues/662#issuecomment-609377552
