### ISSUE TITLE
Last updated time is not update at a time of Recovery and Death count update

### ISSUE THREAD

**Issue by DhiralKaniya** [covid19india/covid19india.github.io#988]
**Describe the bug**
Last updated time is not been updated at the time of death and recovery.

**Screenshots**

![Screenshot_20200412_113223](https://user-images.githubusercontent.com/21332852/79061856-df8f7d80-7cb1-11ea-96e2-830d956fcf34.jpg)
![Screenshot_20200412_113232](https://user-images.githubusercontent.com/21332852/79061858-e1f1d780-7cb1-11ea-9d75-c13a4070fc1c.jpg)

**Comment by strikertanmay** [comment]
@sudevschiz I checked both the APIs(https://api.covid19india.org/updatelog/log.json) & (https://api.covid19india.org/data.json) from which data is fetched to update the time. And I found that there is no problem on the react-app side. I also compared timestamps but no such big difference found. Only 4-5 min difference is coming which is also justifiable.
If u have any point on this issue, please share
