### ISSUE TITLE
India map having district wise heatmap

### ISSUE THREAD

**Issue by ninjakx** [covid19india/covid19india.github.io#992]
**Is your feature request related to a problem? Please describe.**
[#13](https://github.com/covid19india/covid19india-react/issues/13)
It has been implemented for a state-wise map but not for the whole India map.

**Screenshot:**
![districtindia](https://user-images.githubusercontent.com/29797787/79062290-9261da80-7cb6-11ea-90e5-1ecffcc48208.jpg)

Can we do the same?
![Screenshot 2020-04-12 12:12:30](https://user-images.githubusercontent.com/29797787/79062325-f1bfea80-7cb6-11ea-95ba-92d352fd6937.png)

**Comment by bee-rickey** [comment]
@jeremyphilemon @shuklaayush Thoughts? I prefer this TBH.

**Comment by ninjakx** [comment]
We can add filter too showing how the spread happens by varying the filter(date). currently it will show the latest date graph but we can add an animation button too and a filter.

**Comment by shuklaayush** [comment]
@bee-rickey I agree it's a better representation. Apart from procuring the map file, the other issue that I see is availability of district-level data. What are we going to do about states like Telangana which only provide state-level data? It could be misleading if we just ignore them on the map

**Comment by bee-rickey** [comment]
@shuklaayush Valid point. It would be extremely difficult to map that data if the states do not give district break up. Telangana does provide district breakup, just that in between they stopped and hence we've not mapped. But the point is valid.

**Comment by np000** [comment]
It would be a good visualization when a specific state (with district level data available) is selected.

**Comment by shuklaayush** [comment]
@np000 But that's already there, right? When you click on a state on the map. Or am I missing something?

**Comment by iDhruv22** [comment]
Its there, if you click on State.

**Comment by np000** [comment]
@shuklaayush yes , its there already. I didn't noticed it earlier  . You are right.

**Comment by JunaidBabu** [comment]
This can be an item in the deep-dive page.

**Comment by shuklaayush** [comment]
I think the hotspot view is a good alternative for this. In my opinion, a district-wise heatmap isn't a viable option since the number of cases differs by an order of magnitude across districts. This results in the visualization being extremely sparse.

![image](https://user-images.githubusercontent.com/27727946/82140006-12e1a100-984a-11ea-9423-4a7ef0886a12.png)
