### ISSUE TITLE
Timeline for map

### ISSUE THREAD

**Issue by ninjakx** [covid19india/covid19india.github.io#996]
**Is your feature request related to a problem? Please describe.**
We can add the animation play and stop and date filter to see the heatmap. Since we have the previous data too. We can do it for table too.

On this page we can add it on the right side of spread trend.
![Screenshot 2020-04-12 15:39:15](https://user-images.githubusercontent.com/29797787/79066221-e333fc00-7cd3-11ea-9584-3feab8c18fd1.png)

Similar to this one:
https://www.amcharts.com/demos/corona-virus-animated-dashboard/

**Comment by vamshikilari** [comment]
hello @JunaidBabu @jeremyphilemon 
i would like to work on this
please assign this to me

**Comment by jeremyphilemon** [comment]
@vamshikilari Sure, go ahead :)

**Comment by jeremyphilemon** [comment]
Closed by #2009 :)
