### ISSUE TITLE
City wise chart of growth 

### ISSUE THREAD

**Issue by darsh7807** [covid19india/covid19india.github.io#999]
**Is your feature request related to a problem? Please describe.**
It will be good to see if we can have a graphs city wise
**Describe the solution you'd like**
A chart like we have for countries 

**Describe alternatives you've considered**
NA

**Additional context**
I dont have any, I can pick this up if no one else is alreadt doing this

**Comment by sudevschiz** [comment]
Do you have city wise data available?

**Comment by darsh7807** [comment]
No  I dont have, I think its possible, It will need push I think

**Comment by sudevschiz** [comment]
Sorry, didn't get you. What sort of push?

**Comment by darsh7807** [comment]
like we need to push this to data providers, and ask them to publish the day wise count also, it possible but dont know how. Will be great feature though

**Comment by darsh7807** [comment]
we are updating the city stats daily, so we can query from our sheet only to get daily data of cities and can keeo updating it?

**Comment by sudevschiz** [comment]
The coverage of city data is very less. It would be futile to plot this as of now.

**Comment by anidotnet** [comment]
I think city level graph is relevant now.. Any thoughts on adding this?

**Comment by darsh7807** [comment]
@anidotnet I agree, I wonder the way in which city wise data is updated, that can be used to create graphs!
